### ISSUE TITLE
Fix XML documentation for new AddOrUpdateParameter methods

### ISSUE THREAD

**Issue by alexeyzimarev** [restsharp/RestSharp#1002]
I should have raised this in the PR but it is already merged. XML documentation is missing on all overloads of `AddOrUpdateParameter`

https://github.com/restsharp/RestSharp/blob/5d0286598bb0523524e9a6de684633d2b6356dea/RestSharp/RestRequest.cs#L461

**Comment by alexeyzimarev** [comment]
@andrewchaa any news on the XML documentation for the method you have added?

**Comment by andrewchaa** [comment]
Sorry for the delay. Let me do that today or tomorrow :-)

**Comment by andrewchaa** [comment]
@alexeyzimarev I've added comments. Thanks for your patience.
https://github.com/restsharp/RestSharp/pull/1021
