### ISSUE TITLE
Install RestSharp into PLC project? How to?

### ISSUE THREAD

**Issue by biapar** [restsharp/RestSharp#1003]
Is't enough to install RestSharp via nuget and reference .netstandard lib into PLC project?

**Comment by alexeyzimarev** [comment]
What does Refit have to do with RestSharp?

**Comment by biapar** [comment]
Sorry, my mistake. I would to write RestSharp. I made the same question on Refit because it's not possible to install into a Xamarin PLC project.

**Comment by alexeyzimarev** [comment]
As I can read [here](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/net-standard/), you have a choice of using PCL and .NET Standard. We are going to support .NET Standard soon - see #992.

**Comment by biapar** [comment]
So, I can reference your .NET45 DLL into my PLC project and using nuget to install RestSharp to IOS/Android project. It's right?

**Comment by alexeyzimarev** [comment]
To be honest, I don't know. I know this can be an issue and we are working to solve it but I don't think you can install .NET 4.5 library in a PCL project, to be honest.
