### ISSUE TITLE
IRestResponse IsSuccessful property missing

### ISSUE THREAD

**Issue by MorganVergara** [restsharp/RestSharp#1007]
I'm using version 4.4.0 of RestSharp (from NuGet).  The IRestResponse interface on Git has the IsSuccessful method, but the one in 4.4.0 does not.  Should it have that property?

**Comment by alexeyzimarev** [comment]
The latest version is 105.2 and it does not have this method. It has not yet been released. You could have easily checked it yourself by looking at git blame.
