### ISSUE TITLE
Error: Operation is not supported on this platform in ASP.NET Core 2.0 application

### ISSUE THREAD

**Issue by a-patel** [restsharp/RestSharp#1010]
```
RestClient client;
client = new RestClient(Configuration.APIUrl);
            client.Authenticator = new HttpBasicAuthenticator(Configuration.Username, Configuration.Password);

RestRequest request = new RestRequest(Configuration.EndPoints.Clients, Method.GET);
            IRestResponse<ClientResult> response = client.Execute<ClientResult>(request);

            if (response.StatusCode != System.Net.HttpStatusCode.OK)
            {
                if (response.ErrorException != null)
                {
                    throw new Exception(response.ErrorMessage); // Error: Operation is not supported on this platform
                }
            }
```

## Expected Behavior
Get the actual result in json,
same call is working fine with HttpClient and in Postman

## Actual Behavior
Error: Operation is not supported on this platform 

## Steps to Reproduce the Problem

 Simple rest call setup

## Specifications
ASP.NET Core 2.0 console application 

## StackTrace
<details>
```
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternal(String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)
```
</details>

**Comment by alexeyzimarev** [comment]
.NET Core is not yet supported. You need to wait until we are done with the version.

https://github.com/restsharp/RestSharp/issues/992

**Comment by haifengsu-dehavilland** [comment]
good to know, I got the same issue. lol.

**Comment by alexeyzimarev** [comment]
@haifengsu-dehavilland have you tried the alpha package?

**Comment by alexeyzimarev** [comment]
For anyone experiencing this please try using the pre-release package (106.0-alpha) and report any issues you get to #992

**Comment by akberc** [comment]
Just reporting that this specific issue went away with alpha-284. Will report any .NET Core issues to #992

**Comment by ed-graham** [comment]
I can verify that 106.0.0-alpha0284 solves the problem.  However, it is still present in later builds; e.g. 106.2.0-alpha0060.

**Comment by alexeyzimarev** [comment]
@ed-graham I need to know what the issue is. This specific issue has no explanation what actually happened. It is probably related to the default proxy and it was fixes a while ago, but the "fix" resulted in issues with using explicit request proxy.

If you get "not supported" issue with 106.2 stable package - please create a new issue and include stack trace from the exception and also any special configuration and environment details, related to proxy.

**Comment by seankanderson** [comment]
I'm experiencing this in a .NET Standard 2.0 project.  I switched to the RestSharp.NetCore pre-release v105.2.4-rc4-24214-01 library and resolved the issue.

**Comment by alexeyzimarev** [comment]
@seankanderson Hence that `RestSharp.Core` is not from RestSharp team and is not open-source. So I personally have no idea what the code looks like.

**Comment by ed-graham** [comment]
@alexeyzimarev : as per your comment on related issue #1061 this issue is now fixed for me using stable version 106.2.1 .  Thanks!

**Comment by grantwinney** [comment]
In case anyone else stumbles on this like I did after updating their NuGet references, I received the same _"Operation is not supported on this platform."_ error after updating NuGet references on a .NET Core 2.0 app _(while doing a x-www-form-urlencoded POST),_ which moved me from 106.2.2 to 106.4.2.

I just rolled back to 106.2.2 and it worked again.

**Comment by alexeyzimarev** [comment]
@grantwinney please post the stacktrace

**Comment by grantwinney** [comment]
I can open a new issue if you'd like. Was just adding it as an FYI to future visitors.

The exception was:

```
{System.PlatformNotSupportedException: Operation is not supported on this platform.
    at System.Net.SystemWebProxy.GetProxy(Uri destination)
    at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
    at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
    at System.Net.HttpWebRequest.get_ServicePoint()
    at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
    at RestSharp.Http.PostPutInternal(String method)
    at RestSharp.Http.AsPost(String httpMethod)
    at RestSharp.RestClient.DoExecuteAsPost(IHttp http, String method)
    at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)}
```

**Comment by alexeyzimarev** [comment]
@grantwinney Yeah, please open a new issue. Thanks!

**Comment by alexeyzimarev** [comment]
We seem to be having this regression coming back :( What platform are you on, Windows? Do you have a proxy server?

**Comment by grantwinney** [comment]
No proxy server @alexeyzimarev. I'm on a Mac using Visual Studio for Mac. I copied the details to a [new issue](https://github.com/restsharp/RestSharp/issues/1179).
