### ISSUE TITLE
Wait for a file to be generated

### ISSUE THREAD

**Issue by nicrf** [restsharp/RestSharp#1011]
## Actual Behavior
How to wait and download for a file that the server generate?

If I do this, I get the HTML file 
`using (var writer = File.OpenWrite("DFCC3V_document.pdf"))
            {
                var client2 = new RestClient("http://pdf.schneider-electric.nu/default.aspx?salesorgid=21&dist=276&lang=1&form=no&documenttype=plain&productid=DFCC3V&render=eShopV3&TemplateID=1");
                var request = new RestRequest("DFCC3V_document.pdf");
              /*  request.AddParameter("salesorgid", "21"); // adds to POST or URL querystring based on Method
                request.AddUrlSegment("dist", "276");
                request.AddUrlSegment("lang", "1");
                request.AddUrlSegment("form", "no");
                request.AddUrlSegment("documenttype", "plain");
                request.AddUrlSegment("productid", "DFCC3V");
                request.AddUrlSegment("render", "eShopV3");
                request.AddUrlSegment("TemplateID", "1");*/
                request.ResponseWriter = (responseStream) => responseStream.CopyTo(writer);
                var response3 = client2.DownloadData(request);
            }`

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:105.2.3
  - Platform: Windows 7 Professional
  - Subsystem:

**Comment by alexeyzimarev** [comment]
Is this an issue? For me it sounds like a question.
