### ISSUE TITLE
Remove all headers except ones that I have added

### ISSUE THREAD

**Issue by zachyarid** [restsharp/RestSharp#1012]
Wouldn't really consider this an issue. The package works great in my C# application.

However, it is adding unnecessary headers that I do not need/want.

Is there any way to remove all the headers that go along with the request except for the ones that I have explicitly added through the use of: 
request.AddHeader("header", "value");

Anyone have any ideas?

**Comment by alexeyzimarev** [comment]
What kind of headers are those?

**Comment by dgritsko** [comment]
One example would be the `User-Agent` header.

**Comment by zachyarid** [comment]
No longer an issue for me. I found an alternative.

**Comment by mattasaro** [comment]
What was the alternative that you found?
