### ISSUE TITLE
Warning on publish of restsharp.netcore usage..? can you help me how to solve

### ISSUE THREAD

**Issue by RaviSamsher** [restsharp/RestSharp#1013]
Warning message is 
"RestSharp.NetCore 105.2.3 depends on System.Runtime.Serialization.Formatters (>= 4.0.0-rc4-24217-03) but System.Runtime.Serialization.Formatters 4.0.0-rc4-24217-03 was not found. An approximate best match of System.Runtime.Serialization.Formatters 4.3.0-preview1-24530-04 was resolved."

Can you help me how to resolve..

i am using linux system and dotnet core

**Comment by alexeyzimarev** [comment]
RestSharp.NetCore is not this repository. Please get in touch with that library owner.
