### ISSUE TITLE
OAuth v1 & v2 authentication examples using HmacSha512

### ISSUE THREAD

**Issue by HarmenJeurink** [restsharp/RestSharp#1014]
I added SHA512 to the library (locally) and I am struggling using the OAuth1Authenticator. 

An updated example would be very welcome. 

I made a start for implementing the OAuth2Authenticator but after the code below I am stuck ;)

```      
        protected class BittrexAuthenticator : OAuth2Authenticator
        {
            protected BittrexAuthenticator(string accessToken) : base(accessToken)
            {

            }
            public override void Authenticate(IRestClient client, IRestRequest request)
            {
                throw new NotImplementedException();
            }
        }
```

**Comment by alexeyzimarev** [comment]
You need to look at the documentation of the API that you are planning to use and find out what parameters you need to add to the request to make the call. Then, you add these parameters in your `Authenticate` method override.
