### ISSUE TITLE
POST request to .net webAPI is sent as GET

### ISSUE THREAD

**Issue by matthew798** [restsharp/RestSharp#1019]
I expect the following code to generate a POST request with the parameter in the *body* yet I get a GET request with the parameter in the URL.
```
RestClient client = new RestClient("http://192.168.0.193:45455/api");

                try
                {
                    RestRequest apiRequest = new RestRequest("login/google", Method.POST);
                    apiRequest.RequestFormat = DataFormat.Json;
                    apiRequest.AddParameter("token", e.Account.Properties["id_token"]);
                    //apiRequest.AddHeader("Content-type", "application/x-www-form-urlencoded");
                    var apiResponse = client.Get(apiRequest);
                }
                catch(Exception ex)
                {
                    Log.WriteLine(LogPriority.Error, "HTTP Request", ex.Message);
                }
```

Here is the actual request from the wire:

![request](https://user-images.githubusercontent.com/379965/32081920-2b33d524-ba86-11e7-8273-75dffec212d7.png)

This is running in mono on android (xamarin).

**Comment by mjwsteenbergen** [comment]
Instead of using `var apiResponse = client.Get(apiRequest);` try using `var apiResponse = client.Post(apiRequest);`

**Comment by alexeyzimarev** [comment]
I guess we can close this one

**Comment by victorcassel** [comment]
The verb client.Get, client.Post, client.Delete doesn't do any difference for the Http verb strangely. To avoid confusion set the verb either in RestRequest constructor or with the RestRequest Method property, then use the Execute call instead of the Post, Get, Delete calls.

**Comment by alexeyzimarev** [comment]
When you call those extensions methods we actually replace the method in the request. So it should work, I know people use it and it works fine. If it doesn't, I'd like to see the code.
