### ISSUE TITLE
Setting  ParameterHandling to UrlOrPostParameters adds the oauth parameter in cookies

### ISSUE THREAD

**Issue by fbarnard** [restsharp/RestSharp#1022]
## Expected Behavior
The parameter should be added to querystring

## Actual Behavior
It gets places inside cookies

## Steps to Reproduce the Problem

  1.Create new Restclient
  2.Set Authenticator to OAuth1Authenticator.ForProtectedResource
  3.Change authenticator.ParameterHandling to OAuthParameterHandling.UrlOrPostParameters

## Specifications

  - Version: 105.2.3
  - Platform: Windows 10
  - Subsystem:

## StackTrace
<details>

JSFiddle Request

```
POST  HTTP/1.1
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/105.2.3.0
Content-Type: application/json
Host: 
Cookie: oauth_consumer_key=; oauth_nonce=; oauth_signature_method=HMAC-SHA1; oauth_timestamp=; oauth_version=1.0; oauth_token=; oauth_signature=
Content-Length: 2
Accept-Encoding: gzip, deflate
Connection: Keep-Alive
{}
```
I tried it with post and get also tryed it with full url on client and then baseurl and resource on request also tryed it with client Execute and ExecuteTaskAsync
</details>

**Comment by alexeyzimarev** [comment]
Which query parameters are you talking about? There is no code sample, it is not easy to imagine what you were doing. We don't manipulate cookies with OAuth, we add headers from parameters that have names starting with `oauth_` or `x_auth_`

**Comment by fbarnard** [comment]
If you set the OAuthParameterHandling.UrlOrPostParameters should the oauth.consumerkey not be in the query string and not in cookies

**Comment by alexeyzimarev** [comment]
That's what I wrote. We don't touch cookies and we move parameters to headers.
