### ISSUE TITLE
.NET Standard Dependencies

### ISSUE THREAD

**Issue by niemyjski** [restsharp/RestSharp#1026]
![image](https://user-images.githubusercontent.com/1020579/32495364-0b4195b8-c38b-11e7-86de-7569aae625d8.png)

We probably should investigate what's causing this as I don't know why I'd need a reference to open ssl when installing this package. I don't even think we need to bring in any references for .net standard 2.0 (probably only full framework?)?? .NET Standard 2.0 has a ton of packages it brings in by default.

**Comment by alexeyzimarev** [comment]
Well, there are just two (or three?) explicit references. I remember I added one to support .NET Standard 1.6 but may be these are not required any more, I will try to check asap.

**Comment by alexeyzimarev** [comment]
Fixed in package v106.0.1
