### ISSUE TITLE
'Invalid parameter' error when sending dictionary to SugarCRM REST API

### ISSUE THREAD

**Issue by beeksma** [restsharp/RestSharp#1031]
Hi,
 
I'm trying to use RestSharp to connect to our SugarCRM REST API to update a record in the 'Opportunities' module. I used SugarCRM's support page on [/module/:record PUT](http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.7/Integration/Web_Services/v10/Endpoints/modulerecord_PUT/) and the [PHP example](http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_7.7/Integration/Web_Services/v10/Examples/PHP/How_to_Manipulate_Records_CRUD/) to determine the right syntax for building my RestRequest, however I keep ending up with a StatusCode 422 ('A parameter in your request was invalid').
 
Here's my code, which runs after succesfully acquiring the OAuth2 access token in a separate method ('_accessToken') and the Opportunity record that needs changing ('SugarProject'). I tried several ways of adding the required parameter, indicating which field should be changed, plus its new value. Obviously I ran only one of the possible scenarios below on each attempt. The goal here is to change the record's 'name' field to 'Test':

```
public bool SetProjectName(SugarProject project)
        {
            var request = new RestRequest("Opportunities/{id}", Method.PUT);

            request.AddUrlSegment("id", project.Id); // Set the record's UUID in the URL
            request.AddHeader("Cache-Control", "no-cache");
            request.AddParameter("OAuth-Token", _accessToken); // Use OAuth2 token acquired earlier

            // SCENARIO 1: Adding a dictionary directly as a parameter
            var updatedFields = new Dictionary<string, string>();
            updatedFields.Add("name", "Test");
            request.AddJsonBody(updatedFields);

            // SCENARIO 2: Creating a new object and adding that as a Object parameter
            request.AddObject(
                new
                {
                    name = "Test",
                });

            // SCENARIO 3: Adding the parameter using the default method
            request.AddParameter("name", "Test", ParameterType.RequestBody);

            // SCENARIO 4: Adding the parameter as a JSON body
            request.AddJsonBody(new { name = "Test" });

            var response = _client.Execute(request);
            return response.IsSuccessful;
        }
```

## Used value in the RestRequest's 'Parameters' property

Scenario 1: `{application/json={"name":"Test"}}`
Scenario 2: `{name=Test}`
Scenario 3: `{name=Test}`
Scenario 4: `{application/json={"name":"Test"}}`

## Result in IRestResponse (for each scenario)

Response: `"StatusCode: 422, Content-Type: application/json, Content-Length: 88)"`
Content: `"{\"error\":\"invalid_parameter\",\"error_message\":\"A parameter in your request was invalid.\"}"`

## cURL

The cURL command below successfully changes the record's name to 'Test' when I pause the C# code during debugging and use the access token from _accessToken. This leads me to believe all is well in the code above, except for the string containing the record field that needs changing, and its new value:

`curl -X PUT -H OAuth-Token:*_accessToken* -H Cache-Control:no-cache -d '{"name":"Test"}' https://*SugarCRM URL*/rest/v10/Opportunities/4faab519-bea0-37b0-a3f9-5810bfa3dea6`

Any help would me much appreciated!

Kind regards,

Beeksma

## Specifications

  - Version: 106.0.0
  - Platform: Windows

**Comment by dmxengine** [comment]
You need change: 

`request.AddParameter("OAuth-Token", _accessToken); // Use OAuth2 token acquired earlier`

to

`request.AddHeader("OAuth-Token", "_accesstoken"); // Use OAuth2 token acquired earlier`

also 

`request.AddParameter("name", "Test", ParameterType.RequestBody);` 

only work when previosly not added any other parameters with ParameterType.GetOrPost and only first 
parameter with ParameterType.RequestBody type is accepted.

https://github.com/restsharp/RestSharp/wiki/ParameterTypes-for-RestRequest

**Comment by beeksma** [comment]
Thank you so much dmxengine, that solved it for me!
