### ISSUE TITLE
Traffic cannot be captured by fiddler. Using Proxy property will generate an Exception

### ISSUE THREAD

**Issue by PYasonau** [restsharp/RestSharp#1032]
latest version 
Setting up proxy will throw an Exception during request

Requests without Proxy property will not be captured by Fiddler

## Actual Behavior
var client = new RestClient("http://www.google.com");
client.Proxy = new WebProxy("127.0.0.1", 8888);
 var req = new RestRequest("/", Method.GET);
var resp = client.Execute(req);

## Specifications

  - Version: 106.0.1
  - Platform:Win10
 -  target framework: .net core 2.0

## StackTrace
<details>
System.PlatformNotSupportedException: Operation is not supported on this platform.   at System.Net.SystemWebProxy.GetProxy(Uri destination)   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)   at System.Net.HttpWebRequest.get_ServicePoint()   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)   at RestSharp.Http.GetStyleMethodInternal(String method)   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)}

</details>

**Comment by alexeyzimarev** [comment]
Yeah, this was just waiting to happen... I will see what I can do.

**Comment by alexeyzimarev** [comment]
@PYasonau could you check this version to see if the problem goes away?
https://www.nuget.org/packages/RestSharp/106.1.0-alpha0038

**Comment by PYasonau** [comment]
@alexeyzimarev seems it is ok now. This code will not throw an Exception, and after setting up Proxy it will be executed and captured by fiddler. We are happy.
BTW, seems, that client dont use IE Proxy(system proxy) by default and requests will not be captured without Proxy, but requests that are done by System.Net.HTTP.HTTPClient are captured. Is this is expected behavior?

**Comment by alexeyzimarev** [comment]
Yes, this is because WebRequest lacks full system proxy support in .NET Core. I plan to use HttpClient instead of WebRequest in the future but this will be a major refactoring.

**Comment by firstdivision** [comment]
This alpha (and adding the line to manually set the proxy)  also fixed the same problem I was having (RestSharp requests not appearing in Fiddler).  My project is ASP.NET WebForms / .NET 4.6.2.

**Comment by alexeyzimarev** [comment]
Cool. I will make a release when I get back from BuildStuff.

**Comment by alexeyzimarev** [comment]
106.1 is out.
