### ISSUE TITLE
RestSharp 106.1.0 supports only .NET 4.5.2 and above

### ISSUE THREAD

**Issue by nirhp** [restsharp/RestSharp#1041]
## Expected Behavior
RestShatp will support atleast .NET 4.5.1 and above

## Specifications

  - Version: 106.1.0
  - Platform: windows 7

**Comment by alexeyzimarev** [comment]
Sorry, won't happen.

Read this: https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by nirhp** [comment]
Is it done to enforce security?

**Comment by alexeyzimarev** [comment]
It is done because we support the lowest supported .NET version, which supports async/await. So, this is 4.5.2.

**Comment by wbrussell** [comment]
Actually, 4.5.0 is the lowest version that supports async/await.  This is what my apps target.  This will cause 4.5.0 code to be recompiled at 4.5.2 unnecessarily.

**Comment by alexeyzimarev** [comment]
I think I clearly expressed myself:

> lowest *supported* .NET version, which supports async/await

And the lowest *supported* version is 4.5.2. If you find unsupported version of .NET Framework usable - it is your own choice and I appreciate this. You can still use RestSharp 105.
