### ISSUE TITLE
Unable to compile package with Visual Studio 2017 community

### ISSUE THREAD

**Issue by mamekudz** [restsharp/RestSharp#1046]
## Expected Behavior
I get always an error MSB4044, also on a clean installed system. (German error message: "Die GetAssemblyVersion-Aufgabe hat keinen Wert für den erforderlichen NuGetVersion-Paramteer erhalten." no valid NuGetVersion parameter)

## Steps to Reproduce the Problem

  1. load into VS 2017
  2. start "create"
  3.

## Specifications

  - Version:
  - Platform:
Windows7 / Windows10 64Bit
  - Subsystem:

## StackTrace
<details>

```

```

</details>

Anybody kowns this problem?
Thanks and regards
Meinolf

**Comment by alexeyzimarev** [comment]
Do you have .NET Core 2.0 SDK installed?

**Comment by mamekudz** [comment]
thank you for your answer. yes, core 2.0 sdk is installed, but it doesn't help. 

I have deleted the NuGet dependence and than I can compile the dll.

**Comment by alexeyzimarev** [comment]
Which dependency have you deleted?

**Comment by mamekudz** [comment]
[view image](http://www.dongleware.com/restsharp.gif)

**Comment by alexeyzimarev** [comment]
So, what are these arrows pointing to? You said you deleted something, but could you explain what have you deleted?

**Comment by mamekudz** [comment]
I have only deleted the NuGet references (marked by the arrows). If I don't delete this, I get error MSB4044.

**Comment by alexeyzimarev** [comment]
Just push your changes to your fork and send me the link so I can diff it.
