### ISSUE TITLE
COPY Method 

### ISSUE THREAD

**Issue by smietanka** [restsharp/RestSharp#1048]
Hello I need to send request with COPY method. 

Open Stack Object Storage API have method with COPY request. Can you add it?

**Comment by alexeyzimarev** [comment]
It is not a priority now, if you wish - please submit a pull request.

**Comment by smietanka** [comment]
#1049

**Comment by alexeyzimarev** [comment]
Fixed by #1049

**Comment by alexeyzimarev** [comment]
@smietanka Thank you for your contribution! Here is the latest preview package, which includes your change. https://www.nuget.org/packages/RestSharp/106.2.0-alpha0025
