### ISSUE TITLE
Can we use the latest Newtonsoft.Json version?

### ISSUE THREAD

**Issue by pooran** [restsharp/RestSharp#1050]
## Expected Behavior
If we have bunch of projects in a solution are using latest version of Newtonsoft, they should work without issues with restsharp.

## Actual Behavior
Could not load file or assembly 'Newtonsoft.Json' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

## Steps to Reproduce the Problem

  1. Use one project with latest version of newtonsoft
  2. Use in another project with restsharp and dependent newtonsoft version

## Specifications

  - Version: latest
  - Platform: windows 10
  - Subsystem: ASP.Net MVC WebAPI project

## StackTrace
<details>
[FileLoadException: Could not load file or assembly 'Newtonsoft.Json' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]

[FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
</details>

**Comment by alexeyzimarev** [comment]
RestSharp does not have a dependency on Newtonsoft.Json. You must be using something else.
