### ISSUE TITLE
How to include a fieldname like "$fieldname" in RestRequest.AddJsonBody()?

### ISSUE THREAD

**Issue by newbyca** [restsharp/RestSharp#1051]
Hi there, I need to POST a body containing a json string that looks like this:
```
{
    "$a": "b",
    "c": "d"
}
```

In the past I've created RestSharp requests using code like this:
```
var request = new RestRequest("someApiEndPoint", RestSharp.Method.POST);
request.AddJsonBody(new
{
    a = "b",
    c = "d"
});
```

What's the best way to add a "$" to the "a" property in this case?

Thanks!

**Comment by alexeyzimarev** [comment]
Why have you ignored the issue template?

**Comment by newbyca** [comment]
Apologies! I'll post my question on the google group or on SO.

**Comment by newbyca** [comment]
Moved to https://stackoverflow.com/questions/47721020/using-restsharp-how-to-include-a-fieldname-like-fieldname-in-restrequest-add.
