### ISSUE TITLE
RestSharp with TestServer

### ISSUE THREAD

**Issue by dorlandode** [restsharp/RestSharp#1052]
## Expected Behavior
Get back a valid response from a controller endpoint using RestTest

## Actual Behavior
I always get back a 404.

## Steps to Reproduce the Problem

  Example call with RestSharp

```
public async Task<Example> GetExample(Guid exampleId)
{            
       this._restClient = new RestClient("http://localhost");
       Example example = null;
       RestRequest request = new RestRequest("api/example/{id}");
       request.Method = Method.GET;
       request.AddUrlSegment("id", exampleId);
       request.AddHeader("Content-Type", "application/json; charset=utf-8");
       var response = this._restClient.Execute<Example>(request);
       example = response.Data;
       return example;
}
```

Working example with HttpClient
```
TestServer server = new TestServer(
               new WebHostBuilder()
                   .UseStartup<Startup>());

HttpClient client = server.CreateClient();

var exampleId= new Guid("e2e8e066-2586-446a-9668-099eeb3e14ff");
var response = await client.GetAsync($"/api/example/{exampleId}");
response.EnsureSuccessStatusCode();
var responseJson = await response.Content.ReadAsStringAsync();
var example= JsonConvert.DeserializeObject<Example>(responseJson);
```
## Specifications

  - Version: 106.1.0
  - Platform: Windows 10
  - Subsystem:

## StackTrace
<details>

A 404 is returned and a break point on the Controller is never it when using RestSharp.

</details>

**Comment by alexeyzimarev** [comment]
Please submit the server side code too.

**Comment by alexeyzimarev** [comment]
Please create a repository where this issue can be reproduced. The sample code with RestSharp has no TestServer configuration and I don't see the service code.

**Comment by jacodv** [comment]
@alexeyzimarev - I have the same issue, is there a workaround?  Or are the TestServer only accessible from the `server.CreateClient();` and not another client such as RestSharp?

**Comment by alexeyzimarev** [comment]
@jacodv It is in my backlog. .NET Core changed a lot since the issue was opened and I need to check what is the status now.

**Comment by alexeyzimarev** [comment]
Unfortunately, the `TestServer.CreateClient` produces an instance of `HttpClient` only. The only possible solution is to write something similar, which is quite a lot of work.

**Comment by jacodv** [comment]
@alexeyzimarev : Before I close this book and put it in file 13.  Is there anything I (the community) can do to help?  Maybe it is easier if the TestServer exposes objects that can be used by RestSharp?  We have invested a lot of time to write our test base with RestSharp.  But we see the value that the test web server provides for testing, and for this reason we might need to rewrite with that in mind if RestSharp is off the table.

**Comment by alexeyzimarev** [comment]
@jacdevos I am open to any suggestion. As far as I was able to explore this topic, it was either impossible or I wasn't looking well enough. I would be happy to receive any suggestions/PRs

**Comment by jacodv** [comment]
Ok, I have not cloned your repo yet.  I will put this in the TODO and try and see what I can do / suggest

On Wed, 1 May 2019 at 13:08, Alexey Zimarev <notifications@github.com<mailto:notifications@github.com>> wrote:

@jacdevos<https://github.com/jacdevos> I am open to any suggestion. As far as I was able to explore this topic, it was either impossible or I wasn't looking well enough. I would be happy to receive any suggestions/PRs

**Comment by alexeyzimarev** [comment]
As nobody did it, I had to do it myself. Enjoy...

**Comment by jacodv** [comment]
Thanks @alexeyzimarev.  We moved away from RestSharp and switched to HttpClient.   Some test projects still reference RestSharp, I will try it out.  👍🏼
