### ISSUE TITLE
The request was aborted: The connection was closed unexpectedly

### ISSUE THREAD

**Issue by thomasd3** [restsharp/RestSharp#1053]
I am using Restsharp to do regular GET requests to several hosts.
After several days of running at about 250 requests per hour in a multi-threaded environment, all requests will fail and timeout with the message: The connection was closed unexpectedly.

The host doesn't see the request and restarting the application cures the problem.
The same request with Curl will work without problem.

The code is as is:

    var Client = new RestClient("http://...");
    var Request = new RestRequest("...", Method.GET);
    Request.AddHeader("X-auth-Token", KEY);
    Request.AddQueryParameter("timeFrame", TimeFrame);

    // execute the query
    var Response = Client.Execute(Request);
    if (Response.StatusCode != HttpStatusCode.OK)
    {
        return false;
    }

So nothing special, just a lot of parallel requests for a long time will create that problem.
The data returned is quite large, if it makes a difference.

From the symptoms, it looks like RestSharp is just not able to open a socket anymore, so maybe there is something still hanging after each call.

This is using the latest from Nuget, in a .NET 4.7 app and running on Windows Server 2016.

**Comment by alexeyzimarev** [comment]
Link to SO question: https://stackoverflow.com/questions/47794228/restsharp-the-request-was-aborted-the-connection-was-closed-unexpectedly

Please check the latest alpha, try setting you the `ConnectionGroupName` and see if it helps.

**Comment by alexeyzimarev** [comment]
I am closing this issue due to lack of communication. If you still have problems with it, please feel free to reopen the issue.
