### ISSUE TITLE
"XmlText" in RestClient.Execute Returns Null

### ISSUE THREAD

**Issue by LGFN** [restsharp/RestSharp#1055]
I'm not too familiar with XML, so I apologize for not using the technical terms here.

Here's an example XML:

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<RootNode>
	<Element attribute1="9999" attribute2="shpr">Some text in here</Element>
</RootNode>
```

Here's the class I use to deserialize it:

```
public class XmlClass
{
    [XmlRoot(ElementName = "Element")]
    public class Element
    {
        [XmlAttribute(AttributeName = "attribute1")]
        public string Attribute1 { get; set; }
        [XmlAttribute(AttributeName = "attribute2")]
        public string Attribute2 { get; set; }
        [XmlText]
        public string Text { get; set; }
    }

    [XmlRoot(ElementName = "RootNode")]
    public class RootNode
    {
        [XmlElement(ElementName = "Element")]
        public Element Element { get; set; }
    }
}

```
When I deserialize it with XmlSerializer, as such :
```
XmlSerializer serializer = new XmlSerializer(typeof(XmlClass));

using (StringReader reader = new StringReader(response))
{
   reply = (XmlClass)serializer.Deserialize(reader);
}
```
It returns everything, including the text within the brackets ("Some text in here"),

However, when  I deserialize it with RestSharp, as such:
```
IRestResponse<XmlClass> response = client.Execute<XmlClass>(request);
```
The text within the brackets are returned as null.

**Comment by scmason07** [comment]
In your example de-serializing with XmlSerializer, you are using the Deserialize() method from the System.Xml.Serialization namespace. However, when RestSharp performs built-in deserialization it uses its own deserializer from the RestSharp.Deserializers namespace. 

The RestSharp deserializer expects different attributes against your Element and RootNode classes. In particular, the one that is causing issues is :
```
[XmlText]
public string Text { get; set; }
```

which should be replaced with
```
[RestSharp.Deserializers.DeserializeAs(Content = true)]
public string Text { get; set; }
```
You may also be interested in setting attributes and custom element names:
```
[RestSharp.Deserializers.DeserializeAs(Name = "RootNode")] 
[RestSharp.Deserializers.DeserializeAs(Attribute = true)] 
```
Personally, I found it useful to look at the XmlDeserializerTests in the RestSharp.Tests project.
