### ISSUE TITLE
AddJsonBody() will convert local time to UTC time

### ISSUE THREAD

**Issue by zuozhiwen** [restsharp/RestSharp#1056]
![image](https://user-images.githubusercontent.com/12888275/34146441-03d173dc-e4d5-11e7-8288-0127b8a5ea80.png)

**Comment by alexeyzimarev** [comment]
Please change the issue according to the template.

**Comment by alexeyzimarev** [comment]
This is actually the case. It is how SimpleJson works. Try using Json.Net instead.
