### ISSUE TITLE
are you writing your own json serde??

### ISSUE THREAD

**Issue by liweys** [restsharp/RestSharp#1058]
that's crazy. It does not even work for a simple Dictionary... I did not expected that and wasted a lot of time trying it...

**Comment by liweys** [comment]
... seem the .Net Web Api does not work with dictionary either. I need to pass string and do ser/deser with json.net.

**Comment by alexeyzimarev** [comment]
I appreciate your feedback but please show some more respect to people maintaining this repository. Check the documentation - we explain that we use SimpleJson, and that you also can use Json.Net.
