### ISSUE TITLE
Where is DotNetXmlDeserializer.cs?

### ISSUE THREAD

**Issue by shorbachuk** [restsharp/RestSharp#1059]
Is there any reason why this was removed in 106.0?

The commit it just titled "Netstandard 1.6 fixes"

**Comment by alexeyzimarev** [comment]
Yeah, System.Xml is incompatible with .NET Standard 1.6. I will bring it back.

**Comment by natelowry** [comment]
+1 on this. Any plan?

(also, thx for the awesome library) 🎉
