### ISSUE TITLE
Package downgrade error after installing .net core 2.0

### ISSUE THREAD

**Issue by nuwanwi** [restsharp/RestSharp#1060]
I am using RestSharp.NetCore 105.2.3 in one of my projects( .net core 1.1). It is working fine as expected. I have installed Dot.net Core 2.0 in my Laptop for a different project. Now i am getting bellow error in my previous project where i have not changed anything. How can .net core 2.0 installation effects my previous project  

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: System.Runtime.Serialization.Primitives from 4.3.0-preview1-24530-04 to 4.1.1. Reference the package directly from the project to select a different version. 
 XXXXXXXXXXXXXXX -> RestSharp.NetCore 105.2.3 -> System.Runtime.Serialization.Formatters 4.3.0-preview1-24530-04 -> System.Runtime.Serialization.Primitives (>= 4.3.0-preview1-24530-04) 
 XXXXXXXXXXXXXXXXXXXXXXX -> RestSharp.NetCore 105.2.3 -> System.Runtime.Serialization.Primitives (>= 4.1.1)	XXXXXXXXXXXXXXXXXXXXXXX	

I have tried both available versions in the nuget none of them works.

![capture](https://user-images.githubusercontent.com/18161463/34451100-b28473a6-ed41-11e7-97b9-473ad6244145.PNG)

**Comment by alexeyzimarev** [comment]
I am sorry but this is your local set up issue. Please consult in StackOverflow what this could be.

**Comment by nuwanwi** [comment]
This happened two of my team members. We both getting the same error. Seems like this is not related local setup. Restsharp works fine in .net core 1.1 . But when the .net core 2.0 is installed it is not working

**Comment by alexeyzimarev** [comment]
By "local set up" I don't mean that it is "one machine accident".

Restsharp supports .NET Standard 2.0 and .NET Framework 4.5.2. It should not work with .NET Core 1.1 since it requires .NET Standard 1.6 libraries.

All tests we run are on .NET Core 2.0, which you can check in the test projects.
