### ISSUE TITLE
AddObject incorrect serialization for List

### ISSUE THREAD

**Issue by ericnewton76** [restsharp/RestSharp#1063]
Sample code:

```csharp
	public class Person { public string Name { get; set; } }

	class Program
	{
		static void Main(string[] args)
		{
			var list = new List<Person>();
			list.Add(new Person { Name = "Joe" });
			list.Add(new Person { Name = "Mary" });

			var request = new RestRequest("url");
			request.AddObject(list);

			new RestClient("http://localhost:1234").Execute(request);
		}
	}
```

## Expected Behavior

```
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/106.2.0.0
Content-Type: application/json
Host: api.godaddy.com
Content-Length: xxx
Accept-Encoding: gzip, deflate

[{"name":"Joe"},{"name":"Mary"}]

<!-- If this issue is a feature request remove text below -->

```

## Actual Behavior

serialized:
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
Authorization: XXXXXXXXXXXXXXXXXXXXXX
User-Agent: RestSharp/106.2.0.0
Content-Type: application/x-www-form-urlencoded
Host: api.godaddy.com
Content-Length: 141
Accept-Encoding: gzip, deflate

Length=1&LongLength=1&Rank=1&SyncRoot=ConsoleApp1.Person%5B%5D&IsReadOnly=False&IsFixedSize=True&IsSynchronized=False

## Steps to Reproduce the Problem

  1. paste code
  2. run
  3. observe via Fiddler

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
The code is identical to #1062. Please do some clean up.

**Comment by alexeyzimarev** [comment]
Ok, here we go:

`AddObject`

Calls AddParameter() for all public, readable properties specified in the includedProperties list

What you want is `AddJsonBody`
