### ISSUE TITLE
Conflict between StatusCode and IsSuccessful

### ISSUE THREAD

**Issue by EMostafaAli** [restsharp/RestSharp#1064]
## Expected Behavior
IsSuccessful property is true

## Actual Behavior
It returns false

## Steps to Reproduce the Problem

  1. I have the following class
```
public class Customer
    {
        public Customer()
        {
            Project = new HashSet<Project>();
        }

        public uint Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }

        public HashSet<Project> Project { get; set; }
    }
```
  2. The following method
```
protected async Task<IRestResponse> ApplyRequest<T>(string resource, Method method, T data) where T : class, new()
        {
            var client = new RestClient(_connectionConfig.BaseUrl);
            client.FollowRedirects = false;
            var request = new RestRequest(resource, method);
            request.RequestFormat = RestSharp.DataFormat.Json;
            request.AddParameter("application/json", JsonConvert.SerializeObject(data), ParameterType.RequestBody);
            //request.AddJsonBody(data); //This also doesn't work
            var response2 = await client.ExecuteTaskAsync<T>(request);
            return response2;
        }
```
  3.Now if I call this method with Post method, the return statuscode is "created" (and it is actually created). However, the property IsSuccessful gives "false" and the error message is

> Unable to cast object of type 'SimpleJson.JsonArray' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]

## Specifications

  - Version: 106.1.0
  - Platform: Windows 10

**Comment by alexeyzimarev** [comment]
SimpleJson does not support your structure. Since you are already using Json.Net, why don't you use as a JSON serialiser for Restsharp as well? It will solve your problem.

**Comment by EMostafaAli** [comment]
@alexeyzimarev , thanks for your reply. Can you clarify more how to do that?
I tried to use the lib [here](https://github.com/adamfisher/RestSharp.Serializers.Newtonsoft.Json), which wraps Json.Net as follows but it gives the same error.

`request.JsonSerializer = new NewtonsoftJsonSerializer();`

**Comment by alexeyzimarev** [comment]
I need to look at it but the title of this issue is confusing. You certainly did not have a successful request because serialisation failed.

**Comment by alexeyzimarev** [comment]
Due to lack of feedback I have to close this issue.

**Comment by alexeyzimarev** [comment]
> I tried to use the lib here, which wraps Json.Net as follows but it gives the same error.

You cannot get an error with casting `SimpleJson.Array` when using Json.Net, this makes no sense. Please add some more context.

**Comment by JoacimWall** [comment]
Hi 
I use restsharp and the request.JsonSerializer = new NewtonsoftJsonSerializer();
i have issue that restsharp returns IsSuccessful = false
when the StatusCode = HttpStatusCode.OK. and return null in data. 

if i use this 
 var stageResponse = JsonConvert.DeserializeObject<StageResponse>(response.Content);
i am able to get data.  

Regards Joacim

**Comment by alexeyzimarev** [comment]
That's because we check not only the status code but also the response status. If deserialization of the response has failed, we create an error response. In this case, the response status is set to error.

**Comment by alexeyzimarev** [comment]
There will be a new property on the client to not set the status to error when serialisation fails for a successful request. The default will be the same (will still return an error) but it can be changed. Next version will have it.

**Comment by PaddySe** [comment]
I realize this issue is closed, and that I am **very** late in finding it, but I just had this "conflict" between StatusCode and IsSuccessful. At least it was a conflict for me :)

A very common practice in RESTful services, is that when you create a record with POST, and return 201 Created, a Location: header is also added to the reply to indicate where the created record can be fetched from. If you simply return 200 Ok, no such header is usually added.

**My** expected behavior from RestSharp was that it detected the 201 Created response code, saw that there was a Location: header, issued a GET for that URL, and then deserialized the returned Content into the requested object type and set IsSuccessful to _true_ (and if the deserialization failed, IsSuccessful would be _false_).

It would be nice if RestSharp could fully support the 201 Created status code ;)

[Yes, yes, I know I can create a PR for this...]
