### ISSUE TITLE
Version 106.2.0 switches the application proxy to Internet Explorer proxy settings

### ISSUE THREAD

**Issue by CosminLazar** [restsharp/RestSharp#1066]
This was a bug in version 106.2.0 that got fixed in version 106.2.1 but I am posting here to help others stuck with older versions and also to have some sort of history on the issue.

If you were using the RestSharp client without specifying a proxy you would automatically receive the IE proxy settings and your whole application would get configured to use the IE proxy settings for the rest of it`s lifetime. 

This was highly undesirable for us because we were specifying the application proxy settings in the web.config (`system.net/defaultProxy`) and expecting it to be picked up automatically (same as `HttpClient` and all .net libraries), however, when code using RestSharp was executed, the application-wide proxy (`WebRequest.DefaultWebProxy`) was being changed to the IE proxy settings, highly undesirable in our case.

**Comment by alexeyzimarev** [comment]
If you look at the code, you will see that "as all other .NET libraries" is an overstatement. If you are on the full framework, we do this:

```csharp
            if (http.Proxy == null)
                http.Proxy = HttpWebRequest.GetSystemWebProxy();
```

**Comment by alexeyzimarev** [comment]
May be I need to check if the config file has proxy settings. There were complains that Fiddler does not work and this is why this code is there.

**Comment by alexeyzimarev** [comment]
@CosminLazar can you check this version and see if it fixes your problem? https://www.nuget.org/packages/RestSharp/106.3.0-alpha0002

**Comment by CosminLazar** [comment]
With all other .NET libraries I meant libraries from the .NET BCL, as they all eventually end up using the `WebRequest.DefaultWebProxy`. The current version of RestSharp (106.2.1) is fine, the previous version (106.2.0) had issues because it was doing

`      http.Proxy = this.Proxy ?? WebRequest.GetSystemWebProxy();
      IWebProxy defaultWebProxy = WebRequest.DefaultWebProxy;
      WebRequest.DefaultWebProxy = http.Proxy;`

The problem was that `WebRequest.DefaultWebProxy = http.Proxy`, in the case when you didnt actively configured RestSharp with a Proxy setting, it was switching your current application-wide proxy configuration to the `WebRequest.GetSystemWebProxy`.

I think the commit https://github.com/restsharp/RestSharp/commit/8d0b99eae57f348868b4be42cb0ca4efd1e0498b makes sense, however keep in mind that by default `WebRequest.DefaultWebProxy` will might never be null - not sure though (even if no proxy settings have been configured in the *.config file)

**Comment by alexeyzimarev** [comment]
It seems like we have solved the proxy issue...
