### ISSUE TITLE
Compatibility issues between Excel 2010 and 2013/16

### ISSUE THREAD

**Issue by ASJ-2016** [restsharp/RestSharp#1067]
Hi Everyone!

I use Visual Studio to create a C# DLL to be used un Excel. In this C# DLL I have a function that POST an array of numbers to an API and get another array of numbers as a result. The funny thing here is that my code works perfectly in Excels versions 2013 and 2016 and fails in Excel 2010. I've checked whether the x64 or x86 may be the responsible, that all of my office versions are x86. 

The following line in VBA is the one that produces the error:
`v = R.getAPIResults(df, p, ts, f, "Fcst") `

May I miss something in the compilation of the DLL? Or something have changed among the different Office Versions? I'll appreciate any hint and help here. Please find bellow both C# and VBA code.

Thank you!

Alex

### FUNCTIONs in C#:

```
public double[] getAPIResults(object inputMATRIX, int p, double ts, int f, string resultType)
        {
            _prev = p;
            _freq = f;
            json = PostUri(inputMATRIX, p, ts, f);
            _model = JsonConvert.DeserializeObject<List<ListJSON>>(json);
            double[] output = _model[0].GetResults(resultType,0);
            return output;
        }

private string PostUri(object inputMATRIX, int p, double ts, int f)
        {
            var client = new RestClient(MakeUri(p, ts));
            var request = new RestRequest(Method.POST);

            request.AddHeader("postman-token", "07fc5047-0be1-c8f7-9d62-e61dd68b08b4");
            request.AddHeader("cache-control", "no-cache");
            request.AddHeader("content-type", "application/json");
            request.AddParameter("application/json", FillJSONclass_Simple(inputMATRIX, f), ParameterType.RequestBody);

            IRestResponse response = client.Execute(request);

            return response.Content;
        }
```

### FUNCTION in VBA:

```
Sub POST(rgFrom As Range, rgTo As Range, Action As String)
   
    Dim p As Integer, ts As Double, f As Integer
    Dim v As Variant, darray() As Variant, df() As Double

    p = Me.Periods
    ts = 722433920 ' CInt(RValues("ts"))
    f = 12
    
    Set rgFrom = rgFrom.resize(1, rgFrom.Columns.Count - PeriodsValid)
    darray = rgFrom.value
    df = VtD(darray)

            Set rgTo = rgTo.Offset(0, -PeriodsValid).resize(1, rgTo.Columns.Count + PeriodsValid)
            v = R.getAPIResults(df, p, ts, f, "Fcst") 
           
    Set rgTo = rgTo.resize(, UBound(v) + 1)
    rgTo.ClearContents
    Call ArrayToRange(v, rgTo, PeriodsFix)

End Sub
```

###  Visual Studio info:

> Microsoft Visual Studio Community 2017 
> Versión 15.4.1
> VisualStudio.15.Release/15.4.1+27004.2005
> Microsoft .NET Framework
> Versión 4.7.02556
> Versión instalada: Community
> 
> Visual Basic 2017   00369-60000-00001-AA885
> Microsoft Visual Basic 2017
> Visual C# 2017   00369-60000-00001-AA885
> Microsoft Visual C# 2017
> 
> Administrador de paquetes NuGet   4.4.0
> ASP.NET and Web Tools 2017   15.0.30925.0
> ASP.NET and Web Tools 2017
>

**Comment by alexeyzimarev** [comment]
What is the error?

**Comment by ASJ-2016** [comment]
Dear alexeyzimarev, thanks for your fast answer. I am getting the following error: `Compile Error: Method or data member not found`

The weird thing here is that when I try to use intellisense in the VBA editor, my function getAPIResults does not appear to exist in my R object. However, when I execute the code in Excel 2013/16 it appears.

**Comment by alexeyzimarev** [comment]
I am not an expert but I think RestSharp is not loading to Excel 2010. You might need to get an old 105.X version for .NET 3 or 3.5. The latest version of ReshSharp do not support very old versions of .NET Framework.

**Comment by ASJ-2016** [comment]
Thanks Alexey. I'll try to change my .NET version and recompile the project. Hopefully it will not affect the rest of the libraries I've included in the DLL. I'll let everybody know it this solution works!

In this line, I've to add that the GET method of this RestSharp version works perfectly in all Office versions (2010/13/16). Only the POST appears to pop the error.

**Comment by alexeyzimarev** [comment]
Sorry, I can't help really. This usage is quit exotic. I suggest asking on StackOverflow, the audience there is much larger. I have to close it since there is nothing to fix in the code base.
