### ISSUE TITLE
multi-request in one call

### ISSUE THREAD

**Issue by wilsonlichina** [restsharp/RestSharp#1068]
Hello everyone,I'm integrate Restsharp into my project, just have a problem about it. my code as follow:
        /// <summary>
        /// Checks the account.
        /// </summary>
        /// <param name="mobile">Mobile.</param>
        /// <param name="type">Type.</param>
        /// <param name="success">Success.</param>
        /// <param name="failure">Failure.</param>
        public void CheckAccount(string mobile, int type, Action<CheckAccountModel> success, Action<BlingException> failure) 
        {
            CheckAccountRequest request = new CheckAccountRequest(mobile, type);
            RestClientHelper.ExecuteAsync<CheckAccountModel>(_Client, request, success, failure);
        }

        /// <summary>
        /// Gets the verify code.
        /// </summary>
        /// <param name="mobile">Mobile.</param>
        /// <param name="type">Type.</param>
        /// <param name="scene">Scene.</param>
        /// <param name="success">Success.</param>
        /// <param name="failure">Failure.</param>
        public void GetVerifyCode(string mobile, int type, int scene, Action<AccountVerifyCodeModel> success, Action<BlingException> failure)
        {
            CheckAccount(mobile, type, (response) =>
            {
                if (response.IsSuccessful())
                {
                    SendSmsRequest request = new SendSmsRequest(mobile, scene, 0);
                    RestClientHelper.ExecuteAsync<AccountVerifyCodeModel>(_Client, request, success, failure);
                }
                else
                {
                    AccountVerifyCodeModel model = new AccountVerifyCodeModel();
                    model.Code = response.Code;
                    model.Message = response.Message;
                    success(model);
                }
            }, failure);
            
        }

in GetVerifyCode method call CheckAccout, is there graceful solution for multi-request in one funtion? like this:

public void GetVerifyCode(string mobile, int sene, Action<AccountVerifyCodeModel> success, Action<BlingException> failure)
{
  CheckAccountRequest request = new CheckAccountRequest(mobile, type);
   RestClientHelper.AddRequest(request);
SendSmsRequest request2 = new SendSmsRequest(mobile, scene, 0);
RestClientHelper.AddRequest(request2);
RestClientHelper.ExecuteAsync(Client, request, success, failure);
}

make both requests to use the same callback?

**Comment by alexeyzimarev** [comment]
You think it is a bug?

**Comment by wilsonlichina** [comment]
this is not a bug of RestSharp,  just i want to use RestSharp gracefully

**Comment by alexeyzimarev** [comment]
This is nice of you but you have ignored the [contribution guidelines](https://github.com/restsharp/RestSharp/blob/develop/CONTRIBUTING.md).

**Comment by wilsonlichina** [comment]
AccountService.instance.GetVerifyCode(mobile, 0, (int)VerifyCodeScene.Register, 
                   (response) => 
                   {
                    
                   }, 
                
                  (error) =>
                  {
                    string message = error.Message;
                    var okAlert = UIAlertController.Create("Bling", message, UIAlertControllerStyle.Alert);

                      //Add Action
                    okAlert.AddAction(UIAlertAction.Create("确定", UIAlertActionStyle.Default, null));
                    PresentViewController(okAlert, true, null);
                  });

a question again,  above code in my xamarin.ios code,  okAlert can't display. so i guss error callback is running in background thread instead of ui thread?

**Comment by alexeyzimarev** [comment]
Sorry but this is not a place to ask questions. I tried to make this clear.
