### ISSUE TITLE
Invalid, and some valid, Range header values being blocked

### ISSUE THREAD

**Issue by kf6kjg** [restsharp/RestSharp#1069]
## Expected Behavior

I expect to be able to send Range headers as they were typed - even is the value of the header is malformed.  As it stands I can't even use the open-ended ranges specified in https://tools.ietf.org/html/rfc7233#appendix-D

Why do I want this? I use RestSharp almost exclusively in unit tests for my web APIs. I need to unit test how my server responds to invalid input. RestSharp is blocking me from doing this.

## Actual Behavior

Only the "X-Y" format is allowed.

## Steps to Reproduce the Problem

  1. Set up a request to a mock or test server
  2. Add one of the below AddHeader commands
  3. Execute the request and check to see if the server received the header.

## List of AddHeader Commands
```
request.AddHeader("Range", $"bytes=0"); // Fails to send, not RFC compliant.
request.AddHeader("Range", $"bytes=0-"); // Fails to send, RFC compliant.
request.AddHeader("Range", $"bytes=0--"); // Fails to send, not RFC compliant.
request.AddHeader("Range", $"bytes=0-1"); // Sends, RFC compliant.
request.AddHeader("Range", $"bytes=-1"); // Fails to send, RFC compliant.
request.AddHeader("Range", $"bytes=-1-"); // Fails to send, not RFC compliant.
request.AddHeader("Range", $"bytes=-1--2"); // Fails to send, not RFC compliant.
request.AddHeader("Range", $"bytes=0-1,1-,-1"); // Fails to send, RFC compliant.
request.AddHeader("Range", $"bytes=0-1,1-2,2-3"); // Sends, RFC compliant.
```

## Specifications

  - Version: 106.2.1
  - Platform: Linux Mono
  - Subsystem: Ubuntu 16.04, MonoDevelop 7.3.2 (build 12) from FlatPak with Mono 5.4.1

**Comment by kf6kjg** [comment]
For my own project's use I did work out how to build a Regex-based fully compliant parser: http://rextester.com/YSKLH42433

Yes, Regex isn't probably the fastest, but it works.

**Comment by kf6kjg** [comment]
For now I've switched out to the more verbose System.Net.Http.HttpClient built into .NET for the tests where I need to do this kind of stuff.

**Comment by kf6kjg** [comment]
And it turns out that the new and improved Nuget-managed System.Net.Http.HttpClient does similarly. Gah.

**Comment by kf6kjg** [comment]
After cloning RestSharp and digging around, it looks like the Range header is considered a "restricted" header, and is handled by invoking the [AddRange](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.addrange(v=vs.110).aspx) method.  Which will then refuse anything it considers invalid.  So the problem is at the MS level, not the RestSharp level.  Yuck.

Closing until such time as I find a workaround and feel sufficiently motivated to integrate it here.

**Comment by kf6kjg** [comment]
After further digging I found a hack: https://stackoverflow.com/a/7560279/7363787

```C#
var request = WebRequest.Create(uri) as HttpWebRequest;
request.Headers.GetType().InvokeMember(
	"ChangeInternal",
	System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.InvokeMethod,
	null,
	request.Headers,
	new object[] { "Range", "bytes=0" }
);
```

**Comment by alexeyzimarev** [comment]
Yeah, reflections... You can create an extension method to do this.

```csharp
public static void AddNastyHeader(this HttpWebRequest request, object addme)
{
    request.Headers.GetType().InvokeMember(
	"ChangeInternal",
	System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.InvokeMethod,
	null,
    request.Headers,
    addme);
}
```
