### ISSUE TITLE
Package cannot be installed

### ISSUE THREAD

**Issue by grammatn** [restsharp/RestSharp#1070]
## Expected Behavior
Install the package

## Actual Behavior
Refuse to install

## Steps to Reproduce the Problem

  1.Install the package

## Specifications

  - Version: v4.5
  - Platform:Xamarin Forms
  - Subsystem:

## StackTrace
Could not install package 'RestSharp 105.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework.

</details>

**Comment by alexeyzimarev** [comment]
This is not an issue. Version 105.0.0 has no library for 4.5. Check later versions, the latest 105.X version has all supported libraries before we moved to .NET Standard.
