### ISSUE TITLE
How add entire request header on rest request?

### ISSUE THREAD

**Issue by felipeoriani** [restsharp/RestSharp#1071]
Hey guys.

I have been using RestSharp in some projects and it works as expected. Now, we have a scenario where the user can configure a request to hit on the outside of the project and it can be anything. We provide two fields (textarea) where the user can configure the Request Header and Request Body. For the request body, we [found a solution ](https://groups.google.com/d/msg/restsharp/3NVVMridDJ0/ihfTITSrhPYJ) using the method AddParameter and specifying the name as `text/json` and it put the string as raw on the request (as we need):

     restRequest.AddParameter("text/json", requestBodyString, ParameterType.RequestBody);

We wish just to add what the user put on the textarea on the request header and that's our question,  how can we do the same thing for the request header? 

We know we can split the content by line and each line by `:` and use the `AddParameter` with `ParameterType.HttpHeader`, but is there any way to just add the entire data on the http request header by rest sharp?

Thank you.

**Comment by alexeyzimarev** [comment]
Unless you are reporting a bug or a feature suggestion, please consider asking questions on StackOverflow.
Carefully read out contributing guidelines before opening issues on Github.
