### ISSUE TITLE
Release notes are helpful

### ISSUE THREAD

**Issue by loosleef** [restsharp/RestSharp#1072]
## Expected Behavior
Be able to know without comparing commits what was changed from 105 -> 106 (why the major version bump?)

**Comment by alexeyzimarev** [comment]
The major version bump is removing all projects except .NET Standard 2.0. It was announced in the README.

**Comment by alexeyzimarev** [comment]
Plus, RestSharp traditionally was not using minor version, hence 106 is not a low number.

**Comment by totht91** [comment]
It would be good if the project maintains the releases page like before:
![image](https://user-images.githubusercontent.com/8333960/36664818-1f5dd964-1ae6-11e8-94b0-0be347c3343e.png)

**Comment by alexeyzimarev** [comment]
If releasenotes file is maintained, I personally see little value in making releases like this. I think one or another.
