### ISSUE TITLE
Deserializing XML Lists doesn't work like example

### ISSUE THREAD

**Issue by kd5ziy** [restsharp/RestSharp#1074]
## Expected Behavior

I attempted to create objects to mirror the example in the Deserialization documentation (https://github.com/restsharp/RestSharp/wiki/Deserialization).  

Quote from example

```csharp
public class ListSample
{
    public List<Image> Images { get; set; }
}
    
public class Image
{
    public string Src { get; set; }
    public string Value { get; set; }
}
```

I created the following Objects.

## Actual Behavior
The list object was created with 0 items in the list.  

Line 264 in XmlDeserializer.cs would treat the List as a Generic Type.  (Note: if I skip this case and use the case at line 284 then the object would deserialize as specified in the example documentation.)

I was able to work around this issue by sending in a `List<Order>` instead of the `OrderList` object.  (See below for class definitions.)

Please note that if instead of a `List<Order>` I used just `Order` in `OrderList` then a single item would be populated.

## Steps to Reproduce the Problem
Used objects:

```csharp
public class OrderList
{
   public List<Order> Orders { get; set; }
}

public class Order
{
  public orderId {get; set;}
}
```

Sample XML:
`<OrderList><orders order_id="1000000" /><orders order_id="1000001" /><orders order_id="1000002" /><orders order_id="1000003" /><orders order_id="1000004" /><orders order_id="1000005" /><orders order_id="1000006" /><orders order_id="1000007" /><orders order_id="1000008" /><orders order_id="1000009" /><orders order_id="1000010" /></OrderList>`

## Specifications

  - Version: 106.0.0
  - Platform: 
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by kd5ziy** [comment]
@alexeyzimarev, did I miss understand how this should work?

**Comment by alexeyzimarev** [comment]
@kd5ziy I am not the one who wrote this wiki article so I can't really say. I don't remember making any changes in XML part tbh.

**Comment by kd5ziy** [comment]
@alexeyzimarev, ok thank you for taking a look.  I was able to figure out a way to make this work.  I just wanted to make sure it was reported.

**Comment by alexeyzimarev** [comment]
Still want to fix it.
