### ISSUE TITLE
Call main thread from ExecuteAsync response scope? 

### ISSUE THREAD

**Issue by eppz** [restsharp/RestSharp#1076]
Hi, I'm using RestSharp 105.2.3, since I have to use .NET 3.5 in a Unity project.
**Async** request is awesome, but I **can't access main (UI) thread from the callback**.

Is there a simple way to do this?
Is there something in .NET 3. I can wrap my main thread call into?

```csharp
client.ExecuteAsync(
    new RestRequest("ping", Method.GET),
    (IRestResponse response) =>
    {
        Debug.Log(response.Content);
        ui.responseText.text = response.Content; // Boom, exception.
    }
);
```

**Comment by alexeyzimarev** [comment]
Please do not igmnore contribution guidelines and do not use Github issues for anything else then reporting bugs. Seek help in the google group or StackOverflow, remember to put the `restsharp` tag to your question.

**Comment by rmesquit** [comment]
@eppz , did you ever find the answer to this issue?
