### ISSUE TITLE
Overriding Namespace

### ISSUE THREAD

**Issue by Laestic** [restsharp/RestSharp#1077]
https://github.com/restsharp/RestSharp/blob/fe2b032d4e3601a93cf51a2db58f23efbe3e04ac/RestSharp/RestRequest.cs#L286

This will override the XmlSerializer Namespace property with the empty string parameter,  since you can assign a custom serializer with an already set namespace, ending in erasing the original property on calling AddBody without letting the user know.

**Comment by alexeyzimarev** [comment]
Would be nice to see a failing test or something, I don't really get the issue description.

**Comment by alexeyzimarev** [comment]
Ok, I figure out what you mean. It is fixed now.
