### ISSUE TITLE
Question - How to interact with sites that support oly TLS 1.2

### ISSUE THREAD

**Issue by Korporal** [restsharp/RestSharp#1080]
We have code that interacts with Vendors using REST, most of these systems use RestSharp. Yesterday we got hit by failures (nothing to do with RestSharp) which are detailed here:

https://github.com/octokit/octokit.net/issues/1756

As you can see Github temporarily set their site to no longer support TLS 1.0 and things failed. 

My question is that we are interacting with other sites that we know will upgrade to TLS 1.2 in March and we have no idea if we must update RestSharp or adjust our code to somehow tell RestSharp to use TLS 1.2.

Can anyone shed light on this?

**Comment by alexeyzimarev** [comment]
Please do not ignore contribution guidelines and ask questions on StackOverflow

**Comment by Korporal** [comment]
Hi Alexey,

I'm sorry but I'm not able to use StackOverflow because they prohibit users from asking questions if their previous questions are not deemed "interesting" the site is useless and not well regarded and as I say is not an option for me.

Can you at least summarize what TLS support or options exist within RestSharp?

Thank you.

**Comment by Korporal** [comment]
@alexeyzimarev - Hi,

Was it really necessary to close this so soon?

**Comment by Lechus** [comment]
@Korporal : just use Google: How to enable TLS 1.2 on my pc... It is RestSharp independant. 
Resolution: https://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/

**Comment by hgleaves-ncuadmin** [comment]
@Lechus - How am I to know that RestSharp provides no way of setting this unless I ask first? I have "googled" the subject and I have already found and read these articles. I simply wanted to know if RestSharp did or did not handle this, for all I know RestSharp may explicitly set the protocol to support 1.2 or it may provide some option for doing so, that's why I asked the question.

Thanks

**Comment by alexeyzimarev** [comment]
RestSharp is not reinventing the week (well, it does to some extent but still) and uses `HttpWebRequest`. .NET 4.6 has TLS 1.2 enabled by default. 

> NET 4.6 and above. You don’t need to do any additional work to support TLS 1.2, it’s supported by default.
