### ISSUE TITLE
Unable to use StackOverflow

### ISSUE THREAD

**Issue by Korporal** [restsharp/RestSharp#1081]
I'm not reporting a problem, simply seeking information.

My question is in the issue that was closed earlier:

https://github.com/restsharp/RestSharp/issues/1080

As I tried to explain, I cannot use StackOverflow because they have a ridiculous policy of restricting people's ability to ask questions if their previous questions are not deemed "interesting".

Thank you.

**Comment by Korporal** [comment]
For anyone interested I believe that RestSharp currently exposes no control over TLS versions nor does it specify a TLS version.

The TLS version used by clients is governed by the version of the .Net framework they are built with and by whether they have forced a TLS version using the

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

I do not yet know if this is a one-off initialization that is done once per AppDomain or if it is somehow tied to each created socket or REST request.

Perhaps someone who knows more about RestSharp can comment?

**Comment by alexeyzimarev** [comment]
Millions of developers help each other on StackOverflow so I would be careful calling their policies “stupid”. I reopened the other issue but I won’t expect many reactions on that.
