### ISSUE TITLE
Expose standard list of handler content-types

### ISSUE THREAD

**Issue by zaus** [restsharp/RestSharp#1082]
Rather than the magic strings at the following, expose the list of registered content types.  May address the comment "make this configurable" (#1018 ?) as well.  It would make it easier to override the default deserializer (by looping the list).

https://github.com/restsharp/RestSharp/blob/8d0b99eae57f348868b4be42cb0ca4efd1e0498b/RestSharp/RestClient.cs#L63

**Comment by zaus** [comment]
Attached patch with fix --
[0001-fix-1082-exposing-standard-handler-content-types.patch.txt](https://github.com/restsharp/RestSharp/files/1724769/0001-fix-1082-exposing-standard-handler-content-types.patch.txt)

**Comment by alexeyzimarev** [comment]
Would be nice to see a PR instead of a patch.

**Comment by alexeyzimarev** [comment]
No PR, so I assume you don't want it that much. Sorry.
