### ISSUE TITLE
Parameter Protocol Version On Request

### ISSUE THREAD

**Issue by JRRN** [restsharp/RestSharp#1083]
## Expected Behavior

Gettter/Setter For WebRequest Protocol Version

ENUM { HTTP1.0, HTTP1.1, HTTP2.0}

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform: Net.Core / ALL
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
I have no idea what you mean. Could you please elaborate a bit more?

**Comment by JRRN** [comment]
HttpWebRequest.ProtocolVersion=HttpVersion.Version10;

**Comment by alexeyzimarev** [comment]
So you have read their docs and you see that it only supports 1.0 and 1.1, why do you offer to have 2.0 in the enum? Plus, why do we need an enum if we can use the `Version` type?

**Comment by alexeyzimarev** [comment]
Closing due to lack of response. Can be configured using the new request configuration delegate anyway.
