### ISSUE TITLE
Add support for RsaSha1 using a separate certificate

### ISSUE THREAD

**Issue by jachin84** [restsharp/RestSharp#1088]
It looks like a change recently added support for the RsaSha1 signature method. See #794. 
Would it be possible to add support for using a separate certificate, rather than using the consumer secret to produce the signature?

**Comment by alexeyzimarev** [comment]
I have no idea? Do you have a code snippet? Or willing to submit a PR?

**Comment by alexeyzimarev** [comment]
Duplicate #1088

**Comment by alexeyzimarev** [comment]
I would be happy to reconsider if there will be any communication about this.

**Comment by jachin84** [comment]
Sorry I've been sidetracked with some other issues. Happy to provide whatever information you require and potentially a PR. If you could reopen the issue I'll try and be more responsive.

At work we use RestSharp to talk to the Xero API which requires that messages are signed using RSA-SHA1. Details can be found [here](https://developer.xero.com/documentation/auth-and-limits/partner-applications) and [here](https://developer.xero.com/documentation/auth-and-limits/partner-applications). 

We've forked an older version of RestSharp (much older) and added the required functionality. The changes required are around https://github.com/restsharp/RestSharp/blob/develop/RestSharp/Authenticators/OAuth/OAuthTools.cs#L345. The current code makes an assumption that messages are signed using the consumer secret however in the Xero Api a public/private key is required for message signing in addition to the consumer secret.

Make sense?

**Comment by alexeyzimarev** [comment]
Can you create a gist with your changes so I can look at it?

**Comment by jachin84** [comment]
Here is a gist: https://gist.github.com/jachin84/c5aba3b96d6f8a8a832115e6e4c19b7e

I've only added the GetSignature method as that is the most relevant change.

**Comment by jachin84** [comment]
So the current version has this:
```
using (var provider = new RSACryptoServiceProvider { PersistKeyInCsp = false })
                    {
                        provider.FromXmlString2(unencodedConsumerSecret);

                        SHA1Managed hasher = new SHA1Managed();
                        byte[] hash = hasher.ComputeHash(encoding.GetBytes(signatureBase));

                        signature = Convert.ToBase64String(provider.SignHash(hash, CryptoConfig.MapNameToOID("SHA1")));
                    }
                    break;
```
I have the following which takes a AsymmetricAlgorithm parameter:
```
case OAuthSignatureMethod.RsaSha1:
            {
                if (privateKey == null) { throw new Exception("A key is required for RSA-SHA1 signing."); }
                var sha1 = new SHA1CryptoServiceProvider();
                byte[] dataBuffer = Encoding.ASCII.GetBytes(signatureBase);
                var cs = new CryptoStream(Stream.Null, sha1, CryptoStreamMode.Write);
                cs.Write(dataBuffer, 0, dataBuffer.Length);
                cs.Close();
                var formatter = new RSAPKCS1SignatureFormatter(privateKey);
                formatter.SetHashAlgorithm("MD5");

                byte[] s = formatter.CreateSignature(sha1);

                signature = Convert.ToBase64String(s);


                break;
            }
```

**Comment by rudrvij** [comment]
Perfect timing. I need to send messages with RSA-SHA1 for Xero API as well. Will this be included in the main release?

Thanks
Vijay

**Comment by jasond-s** [comment]
Any news on this functionality? I came across this while looking for solutions for calling the Xero API also, would be not to have to fork, or go looking for a different library.

**Comment by alexeyzimarev** [comment]
I guess people that use Xero API can collaborate and submit a PR since this seems to be an edge-case.

**Comment by jachin84** [comment]
I have a working solution for this however I deleted what is currently under the  OAuthSignatureMethod.RsaSha1 case. Happy to work with someone on this but I'll need some help as I've not contributed to something like this before.

**Comment by jachin84** [comment]
I have a fork at https://github.com/jachin84/RestSharp. See https://github.com/jachin84/RestSharp/blob/39fd0adb213e76fc4393d513a7c0e92743e73940/RestSharp/Authenticators/OAuth/OAuthTools.cs#L347 for the change. What I can't work out in the latest version of RestSharp is how to change the ForXXX static methods in OAuth1Authenticator.

**Comment by jasond-s** [comment]
Yeah, there are a lot of statics involved here that make unpicking the API quite hard without, IMO, making too many changes, just to support an edge case. I have fallen back on not using an Authenticator at all and using a library called Dust (used in Xero's own C# client implementation) to build the header manually.
