### ISSUE TITLE
Cannot use Timeout.Infinite

### ISSUE THREAD

**Issue by sdahlbac** [restsharp/RestSharp#1093]
## Expected Behavior

I'd like to disable timing out by setting Timeout to Timeout.Inifinite (i.e. -1) but it seems that is not possible, since RestSharp checks Timeout > 0 (https://github.com/restsharp/RestSharp/blob/develop/RestSharp/RestClient.cs#L475) and (https://github.com/restsharp/RestSharp/blob/develop/RestSharp/RestClient.cs#L479).

**Comment by alexeyzimarev** [comment]
Yeah, I guess we should be comparing with the `default`. It would be nice if you submit a PR.
