### ISSUE TITLE
Expect100Continue isn't being taken into account if proxy is set

### ISSUE THREAD

**Issue by nmalyarsky** [restsharp/RestSharp#1094]
In ConfigureWebRequest method of Http class ServicePoint.Expect100Continue property is set to false first, followed by Proxy property's value assignment. According to .NET source code setting request's proxy re-resolves request's service point (by calling private FindServicePoint method, which leads to ServicePointManager.FindServicePoint method invocation), effectively resetting Expect100Continue property.

HttpClient class allows Expect configuration via its DefaultRequestHeaders property, HttpWebRequest - provides access to ServicePoint itself. RestClient lacks any of these options, so RestSharp users are left with only one way to overcome aforementioned issue, which is ServicePointManager.Expect100Continue property usage. This approach may be not acceptable in scenarios when domain-wide settings are inappropriate.

Is it possible to change property assignment order in ConfigureWebRequest or provide any other solution to the problem?

**Comment by alexeyzimarev** [comment]
I added a `HttpWebRequest` configuration delegate on the client level, would this solve this issue?

**Comment by nmalyarsky** [comment]
Absolutely. Thank you.

**Comment by alexeyzimarev** [comment]
I will try to release this week.
