### ISSUE TITLE
Cookie missing in Response and client.CookieContainer

### ISSUE THREAD

**Issue by ahmed-ben-s** [restsharp/RestSharp#1096]
## Expected Behavior
Hello
It appears that I receive no cookies in the client.CookieContainer where it has always 0 items after I successfully authenticate to our server. It's weird because the same request is sent with Postman and I receive a JSESSIONID cookie that is not present when the request is sent with Restsharp.

## Steps to Reproduce the Problem

  1.Send a request to a server that answers with a  JSESSIONID cookie with HttpOnly and Secure flags
  2.find out that the cookieContainer is still empty in debug mode.

## Specifications

  - Version: 106.2.1
  - Platform: WPF - .Net4.6.1
  - Subsystem:

## StackTrace
<details>
RestResponse with RestSharp (cookies count = 0 ):

"StatusCode: OK, Content-Type: application/json, Content-Length: -1)"

+		cancellationTokenSource	{System.Threading.CancellationTokenSource}	System.Threading.CancellationTokenSource
+		cancellationTokenSource.Token	IsCancellationRequested = false	System.Threading.CancellationToken
+		restClient	{RestSharp.RestClient}	RestSharp.RestClient
+		restRequest	{RestSharp.RestRequest}	RestSharp.RestRequest
-		restResponse	"StatusCode: OK, Content-Type: application/json, Content-Length: -1)"	RestSharp.IRestResponse {RestSharp.RestResponse}
		Content	"{xxxxxxxxxxxxxxxxXXXxxxxxxxXXXxx(pivate data...) }"	string
		ContentEncoding	""	string
		ContentLength	-1	long
		ContentType	"application/json"	string
-		Cookies	Count = 0	System.Collections.Generic.IList<RestSharp.RestResponseCookie> {System.Collections.Generic.List<RestSharp.RestResponseCookie>}
		
+		ErrorException	null	
		ErrorMessage	null	

-		Headers	Count = 12	System.Collections.Generic.IList<RestSharp.Parameter> {System.Collections.Generic.List<RestSharp.Parameter>}
	+		[0]	{Access-Control-Allow-Origin=*}		RestSharp.Parameter
	+		[1]	{Access-Control-Allow-Methods=POST}	RestSharp.Parameter
	+		[2]	{Access-Control-Allow-Headers=Authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,X-API-TOKEN,X-WS-INSTANCE}	RestSharp.Parameter
	+		[3]	{Vary=Accept-Encoding,User-Agent}	RestSharp.Parameter
	+		[4]	{Content-Encoding=}			RestSharp.Parameter
	+		[5]	{Keep-Alive=timeout=15, max=100}	RestSharp.Parameter
	+		[6]	{Connection=Keep-Alive}			RestSharp.Parameter
	+		[7]	{Content-Language=fr}			RestSharp.Parameter
	+		[8]	{Content-Length=753}			RestSharp.Parameter
	+		[9]	{Content-Type=application/json}		RestSharp.Parameter
	+		[10]	{Date=Thu, 15 Mar 2018 15:23:17 GMT}	RestSharp.Parameter
	+		[11]	{Server=Apache}	RestSharp.Parameter
	+		Affichage brut		
			IsSuccessful	true	bool
+		ProtocolVersion	{1.1}	System.Version
+		RawBytes	{byte[1049]}	byte[]
+		Request	{RestSharp.RestRequest}	RestSharp.IRestRequest {RestSharp.RestRequest}
		ResponseStatus	Completed	RestSharp.ResponseStatus
+		ResponseUri	{https://xxxxxxxxxxxxxxx.xxxxx/xxxx}	System.Uri
		Server	"Apache"	string
		StatusCode	OK	System.Net.HttpStatusCode
		StatusDescription	""	string

```

RestResponse with Postman:
Body
{
   private data 
}

Cookies :
Name : JSESSIONID
Value : xxxxxxxxxxx-drt-xxxxxxx
Domain xxxx.xxxx.com
Path: /xx1/admin
HTTPOnly: true
Secure: true

Headers :
Access-Control-Allow-Headers →Authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,X-API-TOKEN,X-WS-INSTANCE
Access-Control-Allow-Methods →POST
Access-Control-Allow-Origin →*
Connection →Keep-Alive
Content-Encoding →gzip
Content-Language →fr
Content-Length →757
Content-Type →application/json
Date →Thu, 15 Mar 2018 22:26:02 GMT
Keep-Alive →timeout=15, max=100
Server →Apache
Vary →Accept-Encoding,User-Agent


</details>

**Comment by alexeyzimarev** [comment]
Cookies are returned in response.Cookies. the CookieContainer is only used to make a request.
