### ISSUE TITLE
Compilation flags. Is it me or RestSharp

### ISSUE THREAD

**Issue by mynkow** [restsharp/RestSharp#1098]
Bellow is a screenshot of the latest stable version. Is it me reading wrong the Compilation info OR RestSharp is compiled in debug?

https://gyazo.com/a77474890c8ef086f32e85be7b3f132f
https://gyazo.com/f2d8a5beaaf706effa826166f044357f

**Comment by alexeyzimarev** [comment]
Seems like it. Fixing it.

**Comment by alexeyzimarev** [comment]
Fixed in develop
