### ISSUE TITLE
RestSharp connects to WebApi - Datetime Timezone problems

### ISSUE THREAD

**Issue by Dryadwoods** [restsharp/RestSharp#1100]
I'm having problems with Datetime properties in objects between the communication of:

site#1 using RestSharp
and site#2 using WebApi.

##########################################
**Version 1**

**Site#1**

```
// SEND 
var client = new RestClient(baseUrl);
var request = new RestRequest(serviceUrl, Method.POST);
var jsonBody = JsonConvert.SerializeObject(model);
request.AddParameter("text/json", jsonBody, ParameterType.RequestBody);
var result = client.Execute<T>(request);
```

```
// RECEIVE 
var client = new RestClient(baseUrl);
var request = new RestRequest(serviceUrl, Method.GET);
var data = client.Execute<T>(request).Data

```
**Site#2**

```
GlobalConfiguration.Configuration.Formatters.JsonFormatter.SerializerSettings =
     new JsonSerializerSettings
         {
              DateFormatHandling = DateFormatHandling.IsoDateFormat,
              DateTimeZoneHandling = DateTimeZoneHandling.Utc,
         };
```

**RESULT:**

On site#1 I am sending 01.01.2018 12:00 AM
On site#2 I am Receiving 01.01.2018 12:00 AM
When site#1 requests the object, then now I am receiving: 31.12.2017 11:00 PM

##########################################
**Version 2**

I have tried to use a different sending on site#1

`request.AddJsonBody(model);`

RESULT:

On site#1 I am sending 01.01.2018 12:00 AM
On site#2 I am Receiving 31.12.2017 11:00 PM
BUT if I correct the value on the database of site#2, then the value is sent back correctly from site#2 to site#1 (basically, the opposite of version #1)

I am even making this tests in the same machine, same culture, same timezone, but of course that I would like to find a solution that would work in machines with different timezone.

**Comment by alexeyzimarev** [comment]
I believe you need to try finding the cause of this issue. What is being sent over the wire, check your response and post the json here.
