### ISSUE TITLE
Limit of 64k when adding a Parameter

### ISSUE THREAD

**Issue by maurizioceravolo** [restsharp/RestSharp#1102]
Hi,
I'm using a rest api of mailgun.com to send batch mails.
With this api, I can send a template and a parameter with all the datain json.
This parameter can be quite big. I have a 500k string.
But this is a problem. When I add a parameter I get an error in sending because there's a 64 limit in encoding it. I get as error URI to long.
This parameter is send using POST method, so I shouldn't have any limit.
Is there a work around?
Thanks

**Comment by alexeyzimarev** [comment]
What is your code?

**Comment by maurizioceravolo** [comment]
It's the sample code of mailgun for batch sending.
You can see it here
https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending
selectcing c#.
Basically it's this one
`        RestClient client = new RestClient ();
        client.BaseUrl = new Uri ("https://api.mailgun.net/v3");
        client.Authenticator =
            new HttpBasicAuthenticator ("api",
                                        "YOUR_API_KEY");
        RestRequest request = new RestRequest ();
        request.AddParameter ("domain", "YOUR_DOMAIN_NAME", ParameterType.UrlSegment);
        request.Resource = "{domain}/messages";
        request.AddParameter ("from", "Excited User <YOU@YOUR_DOMAIN_NAME>");
        request.AddParameter ("to", "alice@example.com");
        request.AddParameter ("to", "bob@example.com");
        request.AddParameter ("subject", "Hey, %recipient.first%");
        request.AddParameter ("text",
                              "If you wish to unsubscribe, click http://mailgun/unsubscribe/%recipient.id%'");
        request.AddParameter ("recipient-variables",
                              "{\"bob@example.com\": {\"first\":\"Bob\", \"id\":1}, \"alice@example.com\": {\"first\":\"Alice\", \"id\": 2}}");
        request.Method = Method.POST;
        return client.Execute (request)`

This code is written to send multiple mail with a template.
In my case the last AddParameter("recipient-variable", .... has as a value a big string of about 500k. If I don't cut it at 64k, I get an error.
After googling for some time, I found a post who says that the error is caused by this update of the code
https://github.com/restsharp/RestSharp/commit/f67044f829c21e9455141b2c4ca8d5ff04c0e987#diff-0
Each parameter is encoded using Uri.EscapeDataString which as the 64k limit. Since an uri can be longer then 64k.
So every parameter you give to restsharp can be bigger then 64k.
You can test it whi every rest api. When you exec client.execute you get the error, and the api is not called. You can check it with fiddler. There's no call.

**Comment by alexeyzimarev** [comment]
I cannot read this. Please spend some time and make the text readable.

**Comment by haifengsu-dehavilland** [comment]
I am having the same issue, post does not work either. in his code , it has set the request as POST

**Comment by bbonch** [comment]
Why is it closed?

**Comment by alexeyzimarev** [comment]
Because the code shows that the request is sent as GET, causing the "too long URL" problem.

**Comment by bbonch** [comment]
I send by POST. [maurizioceravolo](https://github.com/maurizioceravolo) have pointed out you this f67044f. This is an issue.
Issue is not resolved.

**Comment by alexeyzimarev** [comment]
Ok, I reopened it now, please feel free to submit a PR to fix it.
