### ISSUE TITLE
Parts of a multipart/form-data can't have Content-IDs (or other headers) specified

### ISSUE THREAD

**Issue by bill-godfrey-celaton** [restsharp/RestSharp#1103]
When adding parts to a multipart/form-data, I wanted some of the parts to have a Content-ID header. I could not find a way to specify these or other arbitrary headers.

    RestSharp.RestClient cli = new RestSharp.RestClient("http://localhost:57541/UploadRx.aspx");    
    RestSharp.RestRequest req = new RestSharp.RestRequest(RestSharp.Method.POST);    
    req.AddParameter("example", "parameter");    
    req.AddFile("examplefile", @"D:\Scratch\terrflgl.gif", "image/gif");    
    var resp = cli.Execute(req);

The file part includes the Content-Type and Content-Disposition as expected, but if there is a way to add a Content-ID or other arbitrary headers to this part of the request, I couldn't find it.

(Note that I am not referring to the top-level HTTP header, but the headers inside the multi-part.)

**Comment by tejpratapsingh** [comment]
Guys, I am calling a SOAP web service which has a body parameter and file attached to it. Both have content-id headers to relate them to the original request. 
Please let me know if there is any work going on in this area.
Tej

**Comment by alexeyzimarev** [comment]
@tejpratapsingh this request seems to be very specific for marginal use-cases and if you want it to happen - please consider submitting a pull request.
