### ISSUE TITLE
Serialization of Dictionary<string, bool> ends with Bad Request as it is incorrect

### ISSUE THREAD

**Issue by manconti** [restsharp/RestSharp#1105]
## Expected Behavior
If an entity has a Dictionary<string,bool> I would expect that the request.AddJsonBody correctly serialize the dictionary as 

```
 "Options": {
        "Test 1": true,
        "Test 2": false
    }
```

## Actual Behavior
Actually this is serialized as below, which is incorrect and generates a 400 Bad Request error

```
"Options": [{
        "Test 1": true,
        "Test 2": false
    }]
```

## Steps to Reproduce the Problem

  1. Create an entity with a Dictionary<string,bool> property
  2. Fill the data 
  3. Invoke the PUT method using the AddJsonBody(object) method

## Workaround
Using a different serializer will workaround the problem. The solution we have found is based on Newtonsoft package and works correctly. 

`request.AddParameter("application/json", JsonConvert.SerializeObject(data), ParameterType.RequestBody);`

## Specifications

  - Version: 106.2.1

**Comment by alexeyzimarev** [comment]
The issue here is that I don't want to start fixing SimpleJson but it indeed has many drawbacks. However, it works for 90% of users and because of it, RestSharp is free from dependencies.

**Comment by manconti** [comment]
this means that it won't be fixed right? 
Either we stick with the workaround or we change package, am I understanding correct? 
True that RestSharp is free from dependencies and it's working for most case scenario, but either way the users accept to not use Dictionary types in their entity or they have to stick the workaround.

**Comment by alexeyzimarev** [comment]
I am free to chose another source-based serializer but so far no one offered any working alternative. My plan was (and still is) to have an easy way to use Json.Net so people can just install a package, write one like of code and voila.

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
