### ISSUE TITLE
Strange bad request problem

### ISSUE THREAD

**Issue by wcbarrett** [restsharp/RestSharp#1106]
I have some code that makes a simple call to a service (https://api-sandbox.borderfree.com/ordermanagement/v1)

The request executes fine and all is good on some computers.  On the server where I want to deploy the app I am getting a 400 Invalid Request. 

I have found that if I inject a sleep(30000) anytime after instantiating the restclient the subsequent request executes fine.  Like this:

Dim objClient As New RestClient(strEndpoint)
Threading.Thread.Sleep(30000)

Does anyone have any experience with a problem like this?  It  must be something environmental on the server (Windows 2012 Standard in the AWS cloud).  Why would waiting after instantiating the restclient make a difference?

Many thanks for any help!

**Comment by alexeyzimarev** [comment]
Please consider moving this to StackOverflow.
