### ISSUE TITLE
DELETE with JSON body not respecting Content-Type added Header.

### ISSUE THREAD

**Issue by TheSystech** [restsharp/RestSharp#1107]
## Expected Behavior
I have a request via an API where I specifically have to set the content type to application/vnd.api+json.  RestSharp has worked great for every step of this until I got to the point where I needed to implement a DELETE call to the API.  
When a specific content type is added to the request it should be respected.

## Actual Behavior

However when I capture the request via FIDDLER I see that it is specifically sending the Content-Type header of application/json and ignoring my content-type header.
In my case this means the API I am working with rejects my request.

## Steps to Reproduce the Problem

My code looks similar to the below:
```
var client = new RestClient("https://myweb.uri.com");
var myRequest = new RestRequest("/API-URI", Method.DELETE);
myRequest.AddHeader("Content-Type", "application/vnd.api+json");
myRequest.AddJsonBody(ObjectToSerialize);
var response = client.Execute<List<dynamic>>(myRequest);

```
When captured with FIDDLER, the Request Headers show:
DELETE /API_URI HTTP/1.1
x-api-key: <api-specific key for authentication>
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/106.2.1.0
Content-Type: application/json
Host: <hostname here>
Content-Length: 61
Accept-Encoding: gzip, deflate

 
## Specifications

  - Version:  106.2.1.0
  - Platform: Windows
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
Your code has no execute request call. Please add it.

**Comment by TheSystech** [comment]
There I added the one missing line to my example code.  I simply didn't copy that line out of my actual program...

**Comment by keerthivasanm** [comment]
I see that AddJsonBody property is overwriting the request format and in turn overriding the content type. Try swapping out those two lines of code.

var client = new RestClient("https://myweb.uri.com");
var myRequest = new RestRequest("/API-URI", Method.DELETE);
**myRequest.AddJsonBody(ObjectToSerialize);
myRequest.AddHeader("Content-Type", "application/vnd.api+json");**
var response = client.Execute<List<dynamic>>(myRequest);

**Comment by alexeyzimarev** [comment]
With the latest version, it won't help since we take the content type from the serializer when the request is executed. It can be solved by using a simple custom serializer when a different content type assigned. But the content type is actually set for DELETE requests. we have a test for it.
