### ISSUE TITLE
when use HttpBasicAuthenticator,how to add custom header like "request.AddHeader("Auth", "Basic xxxx");"

### ISSUE THREAD

**Issue by zousq19910623** [restsharp/RestSharp#1108]
## Expected Behavior
Auth: Basic xxxx

## Actual Behavior
Authorization: Basic xxxx

## Steps to Reproduce the Problem

  1.when use HttpBasicAuthenticator
  2.how to add custom header like "request.AddHeader("Auth", "Basic xxxx");"

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
If it is not a bug, please consider asking questions on StackOverflow.

**Comment by zousq19910623** [comment]
ok，thx
