### ISSUE TITLE
FR: Allow to choose parameter separator

### ISSUE THREAD

**Issue by manukoshe** [restsharp/RestSharp#1110]
## Expected Behavior
For my situation querystring parameters must be separated with semicolon ( ; ) instead of ampersand ( & ). Would like to have an option to choose querystring parameter separator.

## Actual Behavior
Ampersand is always used as querystring parameter separator. Requests which require another separator will fail.

## Specifications

  - Version: Latest
  - Platform: All

**Comment by alexeyzimarev** [comment]
I don't think it is a good idea. Using ampersand is how HTTP is defined.
