### ISSUE TITLE
Trying to upload a file and json file to multer in a node server, fails.

### ISSUE THREAD

**Issue by kevingalvez-pro** [restsharp/RestSharp#1111]
## Expected Behavior
Send file and json to node server multer

## Actual Behavior
Throws a TypeError: Cannot read property 'fileName' of undefined

## StackTrace
So I am trying to convert this cordova function to our xamarin project:
![screen shot 2018-04-19 at 3 09 13 pm](https://user-images.githubusercontent.com/38337405/38976371-c1aada3e-43e3-11e8-989a-d7cba48c8039.png)

I thought it was straightforward and just implemented it like this.
![screen shot 2018-04-19 at 3 09 51 pm](https://user-images.githubusercontent.com/38337405/38976375-c4f0b48e-43e3-11e8-92c0-6f8cf721a0b0.png)

But in our node server it fails and throws a TypeError: Cannot read property 'fileName' of undefined. 
![screen shot 2018-04-19 at 3 13 23 pm](https://user-images.githubusercontent.com/38337405/38976583-3dcbe798-43e4-11e8-80fb-37602794fae8.png)

Anyone of you could help? Thanks.

**Comment by alexeyzimarev** [comment]
Debug your call in Fiddler. I don't think this has anything to do with a bug in RestSharp.

**Comment by ParanoikCZE** [comment]
Try to remove header, also if client  has some default content type, remove that too.

**Comment by alexeyzimarev** [comment]
This is server-specific. Uploading files with RestSharp work, see the sample repo.
