### ISSUE TITLE
Newtonsoft date deserialization

### ISSUE THREAD

**Issue by michal880** [restsharp/RestSharp#1112]
IRestResponse.Content is not compatible with Newtonsoft.Json.JsonConvert.DeserializeObject when it comes to parsing a Json Date(which was received in correct format). Not sure where should it be fixed, It took me some time to figure it out and I haven't found anywhere such a problem being reported.

## Expected Behavior

deserialized date: 03.10.2016 14:48:58

## Actual Behavior
deserialized date: 01.01.0001 00:00:00

## Steps to Reproduce the Problem

1.try to parse response with date using  Newtonsoft.Json.JsonConvert.DeserializeObject<>();

## Specifications

Newtonsoft.Json" version="6.0.4", 
RestSharp" version="105.2.3",
Microsoft.AspNet.Mvc" version="5.2.3"

**Comment by alexeyzimarev** [comment]
I need to see the code. RestSharp does not use Newtonsoft.Json.
