### ISSUE TITLE
Assempled in Debug Mode

### ISSUE THREAD

**Issue by dkroegs12** [restsharp/RestSharp#1113]
## Expected Behavior
Most recent version, 106.2.1, builds correctly without errors. 

## Actual Behavior
Build is failing due to 106.2.1 being assembled in debug mode. 
![restsharp](https://user-images.githubusercontent.com/38662358/39133836-b2704986-4704-11e8-9272-9fc979ee4175.PNG)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: 
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
I have no other targets than it builds on the CI server. It has no issues like this.
