### ISSUE TITLE
bug in Get parameter containing colon (:)

### ISSUE THREAD

**Issue by chddv** [restsharp/RestSharp#1115]
Hi,
I got a problem with a GET Request containing colon in the parameters.
I need to pass a parameter in this form:
url?parameter=property:value 
The value is correctly encoded but not the colon wich is not encode to %3A
To make it, I have tried with the method AddParameter("parameter", "property:value", ParameterType.GetOrPost)
When I debug, I see in the response the colon and not %3A.
Thanks.
Christophe.

**Comment by alexeyzimarev** [comment]
I added a test and it works fine. https://github.com/restsharp/RestSharp/blob/develop/RestSharp.Tests/UrlBuilderTests.cs#L303

Check your encoding.

**Comment by alexeyzimarev** [comment]
The response is decoded though. Not sure how response is related to a request.
