### ISSUE TITLE
New Content-Type handler

### ISSUE THREAD

**Issue by ParanoikCZE** [restsharp/RestSharp#1117]
(let's consider this better as question)

I've recently ran into issue where some of our requests stopped working after updating to last version. I've found out that issue was caused by this change

https://github.com/restsharp/RestSharp/commit/5b2995847d3222f8538ba7e5a49c1b1cfa8d3c4d#diff-311f9031cae2dbaecfd7acc8804f9950

As we were using 
AddDefaultHeader("Content-Type", "application/json");
for all clients/requests but expected that Multipart is being handled internally.
Well, I've changed our code to reflect this change, so it's working now OK again. 

However, as we are using RestSharp for testing purposes, I've also hoped that one day, when there will be nothing else to do (read as never), it will be possible to also test how our product works when invalid headers or somehow flawed request is being sent. In this case, it would require to handle all my multipart requests with boundary taken from restsharp code (and hope it will not be changed) to do so. Or is there any easier way to handle this scenario?

Also, shouldn't be boundary a dynamic value based on content to be sure it's not here?

**Comment by Exoow** [comment]
Was going to post the exact same issue. :)

**Comment by alexeyzimarev** [comment]
So what are you suggesting to do? The fix was targeting another issue, which is also valid.

**Comment by alexeyzimarev** [comment]
Sadly I am not getting any communication on this issue. The `needContentType` is only set to `true` when the web request has no content type assigned. If you first set the content type, we do not override it. I can't see what can be wrong with it. If you want it to be fixed - at least talk to me.

**Comment by ParanoikCZE** [comment]
Hi Alex, sorry, I didn't notice previous replies' notifications, I'll investigate further and report my results.

**Comment by ParanoikCZE** [comment]
So .. need to say big sorry for this topic. There are actually two issues there. At first, I've didn't read your code well previously so wasn't aware of `needContentType` handling. I was expecting that ContentType was overridden every time. Another issue is an architecture of our tested application, as it accepts json content type even when it shouldn't and as we supplied it as default for all requests, it always worked. So, at this point I need to say thank you for helping me discover this implementation gap.
