### ISSUE TITLE
Multipart/Form-data can't upload file

### ISSUE THREAD

**Issue by manhcuongpassion** [restsharp/RestSharp#1119]
## Expected Behavior
I want server received file excel when i upload in form

## Actual Behavior
var client = new RestClient("https://webdemo.vietinbank.vn/efast-service/transaction/create/batch-payment");
var request = new RestRequest(Method.POST);
request.AddHeader("Postman-Token", "e04e7ce2-7fbc-4e1d-a8e3-bb44fe59a48c");
request.AddHeader("Cache-Control", "no-cache");
request.AddHeader("Authorization", "Bearer AT-440-68wirtmsK91AJgzIlZnMCoLW7Pu06X0S");
request.AddHeader("content-type", "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW");
request.AddParameter("multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW", "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"requestId\"\r\n\r\n1526353402\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"language\"\r\n\r\nvi\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"version\"\r\n\r\n1.0\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"fileUpload\"; filename=\"C:\\Users\\Maxsys\\Downloads\\fileupload.xls\"\r\nContent-Type: application/vnd.ms-excel\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--", ParameterType.RequestBody);
IRestResponse response = client.Execute(request);

**Comment by alexeyzimarev** [comment]
Is there a bug? Why you don't use `AddFile`?
