### ISSUE TITLE
Include XML Documentation Comments file in NuGet package.

### ISSUE THREAD

**Issue by samrueby** [restsharp/RestSharp#1122]
This repo contains helpful XML doc comments, but you cannot read them if you're consuming the NuGet package, because the XML comments file is not included.

Please include the comments file in the NuGet package.

**Comment by ericschaefer** [comment]
+1

**Comment by alexeyzimarev** [comment]
Well, do you know why it doesn't work? From what I was able to find about it, the documentation should be included by default when using `dotnet pack`

**Comment by alexeyzimarev** [comment]
I think I know what is missing. We need the `DocumentationFile` tag in the project file.

**Comment by alexeyzimarev** [comment]
```xml
  <PropertyGroup>
    <DocumentationFile>RestSharp.xml</DocumentationFile>
  </PropertyGroup>
```

**Comment by samrueby** [comment]
👍 Do you need me to create a pull request?

**Comment by alexeyzimarev** [comment]
```xml
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
```

**Comment by alexeyzimarev** [comment]
I will fix this :+1:

**Comment by alexeyzimarev** [comment]
Done

**Comment by samrueby** [comment]
Thank you- this will be a big help.
