### ISSUE TITLE
Support for Blazor

### ISSUE THREAD

**Issue by TFTomSun** [restsharp/RestSharp#1124]
## Expected Behavior
RestSharp works under Blazor

## Actual Behavior
RestSharp doesn't work under Blazor (the response never returns valid content)

## Steps to Reproduce the Problem
- Create a blazor project
- Try to make a rest call using restsharp
- The call will always return empty content and the error message libc

More info:
https://github.com/aspnet/Blazor/issues/890

**Comment by alexeyzimarev** [comment]
We cannot do this until we start using HttpClient but no one seems to be taking care of this. Sorry. It is not an easy task.
