### ISSUE TITLE
Could not create ssl/tls secure channel

### ISSUE THREAD

**Issue by ASPuma** [restsharp/RestSharp#1127]
## Expected Behavior
Successful response from server with the collection of data expected without the need of adding any certificate

## Actual Behavior
error message: Could not create ssl/tls secure channel

## Steps to Reproduce the Problem

  1.  Execute the following code
```
  var client = new RestClient("https://url/api");
            var credential = new HawkCredential
            {
                Id = "id",
                Algorithm = "sha256",
                Key = "key"
            };
            client.Authenticator = new HawkNetAuthenticator(credential);
            var request = new RestRequest("endpointapi/", Method.GET);
            System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
            System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Ssl3;
            
            IRestResponse response = client.Execute(request);
```

Also created the following class to do the custom Hawk Auth
```
public class HawkNetAuthenticator : IAuthenticator
    {
        private readonly HawkCredential _credential;

        public HawkNetAuthenticator(HawkCredential credential)
        {
            _credential = credential;
        }

        public void Authenticate(IRestClient client, IRestRequest request)
        {
            var uri = client.BuildUri(request);
            var portSuffix = uri.Port != 80 ? ":" + uri.Port : "";
            var host = uri.Host + portSuffix;
            var method = request.Method.ToString();

            var header = Hawk.GetAuthorizationHeader(host, method, uri, _credential);

            request.AddHeader("Authorization", "Hawk " + header);
        }

    }
```
  2. Debug the call to the api

## Specifications

  - Version: 105.2.3.0
  - Platform: .NET

## StackTrace
<details>

```
Anulada la solicitud: No se puede crear un canal seguro SSL/TLS

Could not create ssl/tls secure channel
```

</details>

Hope you guys can help me with this

Best Regards

**Comment by alexeyzimarev** [comment]
1) There is no stack trace
2) This is 99% not a RestSharp issue. Make the same call with HttpClient and see if it works.

**Comment by driekus77** [comment]
I had the same issue when downgrading to .NET 4.5 from version 4.6.2.

I went back to 4.6.2 and the problem solved!

**Comment by ASPuma** [comment]
@alexeyzimarev I manage to solve this issue using RestSharp 106.3.1. Now I'm facing this error **System.Net.HttpStatusCode.ProxyAuthenticationRequired**.  If I'm trying to access an https API should I do some extra configuration on the RestClient? Couldn't find docs on this subject and to be honest this is my first experience with this kind of dev.

Hope you can help me
Best regards
Jose

**Comment by driekus77** [comment]
Don't know RestSharp that wel but maybe this code example will help?:
```
			var client = new RestClient("https://httpbin.org");
			var request = new RestRequest("/get", Method.GET);

			client.Proxy = WebRequest.DefaultWebProxy;  // <== Add this line in your code?

			IRestResponse result = client.Execute(request);
```
Googleing on this showed me that it makes a different which .NET Framework / Core / Standard you use.
If you still have issues point out which one you use.

**Comment by ASPuma** [comment]
Thanks a lot for the feedback Henry @driekus77  , it's nice to get some support when giving your first steps, unfortunately I had tried it already and have something like this

```
var client = new RestClient("https://URL/api");
HawkNet.HawkCredential credenciales = new HawkNet.HawkCredential();

credenciales.Algorithm = "sha256";
credenciales.Key = "Key";
credenciales.Id = "Id";

client.Authenticator = new HawkAuth(credenciales);
client.Proxy = System.Net.WebRequest.GetSystemWebProxy();
//client.Proxy.Credentials = (System.Net.NetworkCredential)System.Net.CredentialCache.DefaultCredentials;
var request = new RestRequest("endpoint/", Method.GET);

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
IRestResponse response = client.Execute(request);
```

I'm usign:
.NET ->  4.5.2
.Net Core -> Not installed (couldn't find the folder)

**Comment by alexeyzimarev** [comment]
It seems like an issue with your specific environment, where you have a proxy, which requires authentication. I cannot reproduce this because I haven't seen places that use http proxy for years. I think you get more luck on StackOverflow.

**Comment by bomzj** [comment]
My site is hosted on IIS, so had to change site's application pool **Identity** to "LocalSystem" to get it working.

**Comment by dankoster** [comment]
I ran into this today. We're on .net 4.6.1 with RestSharp 106.6.3.0 and this is still an issue there. Adding the following line of code prior to my first request resolves the issue for me

`ServicePointManager.SecurityProtocol = (SecurityProtocolType)System.Security.Authentication.SslProtocols.Tls12;`

Here's a configuration based solution (and some good commentary about the root cause) if you don't want to or can't add code: https://stackoverflow.com/questions/43872575/net-framework-4-6-1-not-defaulting-to-tls-1-2

**Comment by linmar22** [comment]
> 1. There is no stack trace
> 2. This is 99% not a RestSharp issue. Make the same call with HttpClient and see if it works.

Even though this is not a RestSharp issue, RestSharp could have a mechanism to handle this common problem, without having to override security  on the global scope or having to re-implement a layer of the package.

**Comment by alexeyzimarev** [comment]
@linmar22 RestSharp adds comfort to making HTTP calls to APIs but it doesn't override the behaviour of the .NET Framework.

**Comment by Lechus** [comment]
ASP.NET with Net Framework 4.7.2 no need for manual setting TLS12. It does NOT work in previous Net Frameworks, like 4.6.2.

**Comment by kironiitdu** [comment]
I have resolved the issue like this way:

```
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };

            HttpClient httpClient = new HttpClient(clientHandler);
            httpClient.BaseAddress = new Uri("https://localhost:44361/");

            var restClient = new RestClient(httpClient);
            var request = new RestRequest("UserLog/GetData", Method.Get) { RequestFormat = DataFormat.Json };
            var response = restClient.Execute<List<QueryExecutionModel>>(request);
```

**Comment by alexeyzimarev** [comment]
`ServerCertificateCustomValidationCallback` is also available in `RestClientOptions`

**Comment by zanyar3** [comment]
I found solation after more searching :)

Replace `https` to `http`

**Comment by chenjing1294** [comment]
> I found solation after more searching :)
> 
> Replace `https` to `http`

it's a joke

**Comment by chenjing1294** [comment]
for self-signed SSL certificates：
```
var options = new RestClientOptions("https://test.example.com/users/1")
{
    RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true
};
_restClient = new RestClient(options);
```
