### ISSUE TITLE
[request] provide more options for list serialization

### ISSUE THREAD

**Issue by Almenon** [restsharp/RestSharp#1128]
Currently there is no way to serialize the following without using the dotnet serializer:

I would like the following code:
```c#
public class ListSample
{
    public List<Image> Images { get; set; }
}
    
public class Image
{
    public string Src { get; set; }
    public string Value { get; set; }
}
```

to serialize to:

```
<InlineListSample>
    <image src="1.gif">value1</image>
    <image src="2.gif">value2</image>
    <image src="3.gif">value3</image>
    <image src="4.gif">value4</image>
</InlineListSample>
```
Instead serialization results in:
```
<NestedListSample>
   <images>
      <image src="1.gif">value1</image>
      <image src="2.gif">value2</image>
      <image src="3.gif">value3</image>
      <image src="4.gif">value4</image>
    </images>
</NestedListSample>
```

Also see [this stackoverflow post](https://stackoverflow.com/questions/13175410/restsharp-serialize-list-without-parent-element)

Thanks for creating restsharp, btw :)

**Comment by alexeyzimarev** [comment]
But we offer you to use .NET XML serialiser, what is the issue here?

**Comment by Almenon** [comment]
The issue is that people are going to try using the default serializer first.  It will take them a while to realize they have a problem and then more time to find how to fix it.  Eventually they realize they need to switch the serialization method which means lots of rework as they change all their attributes.

**Comment by alexeyzimarev** [comment]
I understand that people will try the default one first but the option to use different serializers is exactly to resolve issues when the default serializer is not suitable. I think this can be solved by adding a couple of lines to the documentation unless someone can submit a PR to fix this.

**Comment by Almenon** [comment]
Adding documentation doesn't solve the problem but it would be a good start :)

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
