### ISSUE TITLE
deserialization does not work with list when the field name is the same as the name of the list item

### ISSUE THREAD

**Issue by Almenon** [restsharp/RestSharp#1129]
## Expected Behavior
Deserialization works

## Actual Behavior
Deserialization does not work

## Steps to Reproduce the Problem

  1. Deserialize an xml response
  2. with a list of items
  3. the name of each item should end in s (not sure if this is relavent, but applied to my case)
  4. The name of the field is the same as the name of the item (ex: \<angry-cactus\> and public List<AngryCactus> angryCactus {get;set;} )

## Specifications

  - Version: 106.3.0
  - Platform: Windows

## StackTrace
N/A: no error, it just fails to deserialize

## Misc
This is for a regular list (with no parent) like so:
```
<angry-cactus>
  <id>1</id>
<angry-cactus/>
<angry-cactus>
  <id>2</id>
<angry-cactus/>
```

I apolagize for the lack of code samples - I found the bug while working on a internal project for my company that is not open source.

**Comment by alexeyzimarev** [comment]
XML serialization works, we have many tests for it. If you use snake-case for elements, you need to use `DeserializeAs` attribute on your properties.
