### ISSUE TITLE
Exception with OAuth2.0 service call

### ISSUE THREAD

**Issue by mohammdr** [restsharp/RestSharp#1138]
Hi experts.
I write some code in Microsoft Visual Studio .NET with C#. I call one rest service using RestSharp 106.3.1 library that i get from Microsoft NuGet.
this is a banking service that has no argument and list all customer debit card.
I previously get bearer access token from another service and I can call getCards service with HttpClient successfully. but I want to use RestSharp.

my code is:
var client = new RestSharp.RestClient(webSrvUri);
client.Authenticator = new RestSharp.Authenticators.OAuth2AuthorizationRequestHeaderAuthenticator(accessToken, "Bearer");
var request = new RestSharp.RestRequest(RestSharp.Method.POST);
request.RequestFormat = RestSharp.DataFormat.Json;
request.Parameters.Clear();
request.Resource = "getCards";
request.AddHeader("Accept", "application/json");
request.AddHeader("Content-Type", "application/json");
RestSharp.IRestResponse response = client.Execute(request);

but this code generate following content as result:
{"timestamp":"2018-07-03 10:16:49","status":500,"error":"Internal Server Error","exception":"com.fasterxml.jackson.databind.JsonMappingException","message":"No content to map due to end-of-input\n at [Source: ; line: 1, column: 0]","path":"/core/getCards"}

what do I do?
Thanks in advance.

**Comment by alexeyzimarev** [comment]
Please consider asking questions on StackOverflow.

Your server does not accept your request, returns an error saying that the request is malformed. It has nothing to do with OAuth2
