### ISSUE TITLE
Possibility to have many DeserializeAs attribute on a Property

### ISSUE THREAD

**Issue by mckmonster** [restsharp/RestSharp#1139]
## Expected Behavior
I want to write a stuff like that
```
        [DeserializeAs(Name = "Members")]
        [DeserializeAs(Name = "Users")]
        public List<User> Users { get; set; }
```

## Actual Behavior
Currently, it's just possible to write that
```
        public List<User> Users { get; set; }
        public List<User> Members { get; set; }
```
to have result Members or Users in function of json result

## Steps to Reproduce the Problem

I use this two different with same result class
* https://rocket.chat/docs/developer-guides/rest-api/channels/members/
* https://rocket.chat/docs/developer-guides/rest-api/users/list/

## Specifications

  - Version: 106.3.1
  - Platform: PC Windows 10
  - Subsystem:

**Comment by alexeyzimarev** [comment]
We do not plan to implement any changes in serialization. You can change the serializer and add your own to do whatever you want.
