### ISSUE TITLE
Property on Sub-Object Gets Deserialized From Xml Rather than Attribute on Actual Object

### ISSUE THREAD

**Issue by Attackmonkey** [restsharp/RestSharp#1140]
## Expected Behavior

If I deserialize an XML object with an attribute that matches a property name in the class we're deserializing to, I'd expect that to be used, rather than a matching property from a sub-object in the XML. Adding the DeserializeAs attribute and setting Attribute = true makes no difference.

## Steps to Reproduce the Problem

Create a class like this:

```
public class Job
{
        public string Name { get; set; }

        public string JobType { get; set; }

        public string Platform { get; set; }

        public string Description { get; set; }

        public DateTime NextRun { get; set; }
}
```

Then Deserialize the following XML:

```
<?xml version="1.0" encoding="utf-8"?>
<Job Href="xxx" Type="Job" Name="This Is What I'd Expect To Be Deserialized in Name" >
    <JobType>Backup</JobType>
    <Platform>HyperV</Platform>
    <Description>Created by Steve</Description>
    <NextRun>2018-07-06T21:00:00Z</NextRun>
    <JobInfo>
        <BackupJobInfo>
            <Includes>
                <ObjectInJob Href="xxx" Type="ObjectInJob">
                    <Name>This is What Actually Ends Up in the Name Property</Name>
                    <DisplayName>Blah</DisplayName>
                </ObjectInJob>
            </Includes>
        </BackupJobInfo>
    </JobInfo>
</Job>
```

Instead of getting the Name attribute on the actual Job object, it gets the property from several levels deeper in the XML. As stated, setting the DeserializeAs attribute doesn't appear to make a difference.

## Specifications

  - Version: 106.3.1

**Comment by alexeyzimarev** [comment]
@Attackmonkey does it work with .NET XMK deserialzier?

**Comment by alexeyzimarev** [comment]
Yeah, I found it now. You need to change the serializer to `XmlAttributeDeserializer` and it will work.
