### ISSUE TITLE
"GetAssemmblyVersion" missing required parameter

### ISSUE THREAD

**Issue by DavidGreenfeld** [restsharp/RestSharp#1142]
I download the following rest sharp class and i got the following error
The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion".	
Any help with this issue?
Any advice?
I appreciate,

**Comment by DavidGreenfeld** [comment]
The Simple REST and HTTP API Client for .NET.
The error is by this code
 <Target Name="GetAssemblyVersion">
    <GetAssemblyVersion Condition="'$(AssemblyVersion)' == ''" NuGetVersion="$(Version)">
      <Output TaskParameter="AssemblyVersion" PropertyName="AssemblyVersion" />
    </GetAssemblyVersion>
    
    <PropertyGroup>
      <FileVersion Condition="'$(FileVersion)' == ''">$(AssemblyVersion)</FileVersion>
      <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
    </PropertyGroup>
  </Target>
I don't now what to fix over here.

**Comment by alexeyzimarev** [comment]
I have no idea what are you talking about. Please try formulating the issue properly, otherwise, I will have to close it.
