### ISSUE TITLE
Connection: Keep-Alive Header is not set for POST requests

### ISSUE THREAD

**Issue by philno** [restsharp/RestSharp#1145]
## Expected Behavior

If I set the Connection header like
```
var request = new RestRequest(Method.POST);
request.AddHeader("Connection", "Keep-Alive");
```
or
```
var client = new RestClient(uri);
client.AddDefaultHeader("Connection", "Keep-Alive");
```
and send the request via
```
var cts = new CancellationTokenSource(TimeSpan.FromSeconds(20));
var response = await client.ExecuteTaskAsync<T>(request, cts.Token);
```
It should be set when I check the request with postman echo or a local proxy. 

## Actual Behavior

The header is not set at all for some reason. 
It is really frustrating for me because I can not get access to an API if this header is not set correctly and I can not change said API.
It seems like it works fine with a GET request, but not with a POST request.

## Specifications

  - Version: 106.3.1
  - Platform: Windows 10
  - Subsystem: NET Framework 4.7

**Comment by philno** [comment]
I think I found a solution. So it seems like my problem was related with trying to disable the `Expect: 100-continue` header globally as described on stackoverflow: https://stackoverflow.com/questions/14063327/how-to-disable-the-expect-100-continue-header-in-httpwebrequest-for-a-single

In the meantime, I found the helper to configure the underlying web request in RestSharp, which produces the solution:

```
            var client = new RestClient("https://postman-echo.com/post");
            client.ConfigureWebRequest((r) =>
            {
                r.ServicePoint.Expect100Continue = false;
                r.KeepAlive = true;
            });
```

This sets the keep alive header correctly (desired behaviour). 
Not sure if `r.KeepAlive = true;` is needed there but I added it just to make sure.

The problem was probably caused by the underlying web request and I'm not sure what can be done in RestSharp to prevent this in the future. 
Do you think it would make sense to expose these properties in RestSharp so people do not get drawn to hacky solutions? 
Otherwise, a hint in the documentation that a) RestSharp uses Net.HttpWebRequest internally and b) offers configuration with the helper method above might be really helpful.

**Comment by alexeyzimarev** [comment]
I have added `ConfigureWebRequest` so people can do manipulations with the underlying request. Exposing everything that `WebRequest` has to offer as RestSharp properties is not a good way. I think. There are a lot of edge cases and we cannot cover them all. In addition, I don't think this solution is in any way "hacky". If you need to fine-tune your request - you have a way to do this.

I agree that `ConfigureWebRequest` should be documented better.

**Comment by philno** [comment]
I agree, I think `ConfigureWebRequest` is a very elegant solution in this case. 
The "hacky" solution I was referring to is `System.Net.ServicePointManager.Expect100Continue = false;` that disables the `Expect` header globally (and lead to unintended side effects with the `Connection` header in my case).

I will be happy to help updating the documentation for this case. Is it possible to edit the wiki directly or should I create a pull request?

**Comment by alexeyzimarev** [comment]
I think wiki is only edited by maintainers. I would love to get a separate site for docos under the restsharp.org but I tried to get hold on that domain name and find the repo where the site is hosted, from previous maintainers and no one knows where it is... :(

**Comment by alexeyzimarev** [comment]
@philno btw the docs were moved to the repo itself, so feel free to contribute :)

But I am working on generating md files from XML comments, so all documented properties and methods will be documented too.
