### ISSUE TITLE
Invalid Token Request.

### ISSUE THREAD

**Issue by smoro88** [restsharp/RestSharp#1147]
var client = new RestClient(url);
                var request = new RestRequest("AuthServer/api/Token", Method.POST);
              
                request.AddHeader("Content-Type", "application/json; charset=utf-8");
                request.AddHeader("Authorization", "Basic xxxx");

                request.AddParameter("grant_type", "client_credentials"); 
                request.AddParameter("user_login_id", "1"); 

                IRestResponse response = client.Execute(request);
                return response.Content;

This code above works fine in v106.1.0 but anything newer causes the following error.
     
{\"$type\":\"WMS.V2.Generic.Models.Exceptions.QueryParameterException, WMS.V2.Generic.Models\",\"Parameters\":[\"tokenRequest\"],\"ErrorCode\":\"Invalid\",\"ClassName\":\"QueryParameterException\"}

What do I need to change to make this work.
Thanks
Steve

**Comment by Psypher9** [comment]
Is there an Exception, or is that snippet you added the `response.Content`'s actual content?

**Comment by smoro88** [comment]
This issue has been resolved on my end. The request needed to be changed.
