### ISSUE TITLE
NuGet Package : Add `repository` metadata. 

### ISSUE THREAD

**Issue by MaximRouiller** [restsharp/RestSharp#1153]
Basically, we can now add a repository metadata on a nuspec file to allow the repository to be surfaced on NuGet. This allows you to have a `projectUrl` as well a repository URL now.

I've talked about it [on Twitter](https://twitter.com/MaximRouiller/status/1030468873945075712) but the most basic things to know is here:

[NuSpec Reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec?WT.mc_id=social-github-marouill#repository)

Reference Implementation in Json .NET
![image](https://user-images.githubusercontent.com/209384/44277447-b1c20f00-a218-11e8-9406-4f1f05879d47.png)

**Comment by alexeyzimarev** [comment]
We don't use nuspec files. What you're suggesting is to change this line to point to the repository instead of the main website?
https://github.com/restsharp/RestSharp/blob/develop/RestSharp/RestSharp.csproj#L7

**Comment by MaximRouiller** [comment]
Docs available here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

Basically means adding a `RepositoryUrl` and `RepositoryType` elements to your `csproj` file.

For RestSharp:

```xml
 <RepositoryURl>https://github.com/restsharp/RestSharp.git</RepositoryUrl>
 <RepositoryType>git</RepositoryType>
```

**Comment by alexeyzimarev** [comment]
You are just one step from making a PR 👍

**Comment by natemcmaster** [comment]
+1 to what @MaximRouiller said. This is how we do it in aspnet projects: https://github.com/aspnet/KestrelHttpServer/blob/83488886e0ed32e946af2a25ae7f29ce9bcc4273/Directory.Build.props#L16-L17. The Directory.Build.props file is automatically imported into all projects in the repo.

**Comment by alexeyzimarev** [comment]
@natemcmaster I think we can just change the csproj file, since we only have one project.

**Comment by MaximRouiller** [comment]
@alexeyzimarev incoming.
