### ISSUE TITLE
Question: how to access a service behind siteminder SSO

### ISSUE THREAD

**Issue by RaySheikh** [restsharp/RestSharp#1156]
Hi, 
I was wondering if anyone knows the best way to by pass siteminder sso using rest sharp. Below is the code i'm using but I get forbidden error..
thank you in advance

           `
            RestClient client = new RestClient("http://site/myapp");
            client.CookieContainer = new CookieContainer();
            IRestResponse response = client.Get(new RestRequest("someProduct/orders"));

            //Now add credentials.
            client.Authenticator = new HttpBasicAuthenticator("username", "password");
            //Get resource from the SiteMinder URI which will redirect back to the API URI upon 
             authentication.
            response = client.Get(new RestRequest(response.ResponseUri));
    `

**Comment by alexeyzimarev** [comment]
Please read https://github.com/restsharp/RestSharp/blob/develop/CONTRIBUTING.md#before-you-do-anything-else
