### ISSUE TITLE
IE11 - Javascript sends invalid characters with dates

### ISSUE THREAD

**Issue by cjrogala** [restsharp/RestSharp#1158]
It would be really great if when the headers from an HttpRequestMessage are added to a RestRequest using the AddHeader method would remove invalid Unicode characters.

When an AJAX request is sent from IE, IE adds an Unicode RTL to the header value for Date variables.  When I looped through the headers of the incoming HttpRequestMessage to add certain headers to the RestRequest, the RTL mark was added an the request would fail with the following error:

> Specified value has invalid Control characters.
> Parameter name: value

Because these characters are not visible characters, I did not see them when comparing the Chrome request to the IE request.

## Steps to Reproduce the Problem

  1. Create a simple HTML page that send the value of a Date variable as a header
  2. Create a Controller that create a RestRequest and appends the header from the HttpRequestMessage
  3. Add the below method and pass the HttpRequestMessage to it (Note: it will error as it is and an actual endpoint is not needed)

```
private void SendRequest(HttpRequestMessage inboudRequest)
{
    var client = new RestClient("http://does-not-need-to-exist");
    var outboundRequest = new RestRequest("path-wont-be-used-so-dont-actually-wire-it-up");
    var dateHeader = inboudRequest.Headers.FirstOrDefault(x => x.Key == "some-date-variable-header");

    outboundRequest.AddHeader(dateHeader.Key, dateHeader.Value.FirstOrDefault());
            
    var response = client.Execute(outboundRequest);
    if (response.StatusCode == 0)
    {
        Debug.WriteLine(response.ErrorException);
    }            
}
```

## Specifications

  - Version: 106.3.1.0
  - Platform: MVC Web Application - ASP.Net (.NET Framework 4.7.1)

## StackTrace
<details>

```
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.WebHeaderCollection.Add(String name, String value)
   at RestSharp.Http.AppendHeaders(HttpWebRequest webRequest)
```

</details>

**Comment by alexeyzimarev** [comment]
It seems like a marginal case... What is the definition of "invalid character"?

**Comment by cjrogala** [comment]
Here is the link to the WedHeaderCollection.CheckBadChars method this is being thrown from.  

https://referencesource.microsoft.com/#system/net/system/Net/WebHeaderCollection.cs

Looks like it simply checks the new line characters are correctly formatted and that the string does not contain CTL characters.

My solution was to simply convert the header value to an ASCII string.  This will worked for my app, but I needed it for a very specific case scenario.
