### ISSUE TITLE
Can you support HttpClientFactory of net core 2.1?

### ISSUE THREAD

**Issue by ghd258** [restsharp/RestSharp#1160]
Can you support HttpClientFactory of net core 2.1?

**Comment by alexeyzimarev** [comment]
We do not use HttpClient

**Comment by ghd258** [comment]
Why not use HttpClient? Or is there any merit in HttpClient?

**Comment by alexeyzimarev** [comment]
I have no issues with using the HttpClient, but who is going to do the conversion from using WebHttpRequest to HttpClient? So far many were talking about it but I have not seen a single PR. If you are willing to submit a PR for this - I'll be happy to merge it.
