### ISSUE TITLE
Multipart form data response - Part that contains only file bytes

### ISSUE THREAD

**Issue by MehmetBond007** [restsharp/RestSharp#1161]
## Expected Behavior
Is there any parameter that contains only file bytes of a RestSharp response.
## Actual Behavior
Content and RawBytes parameters contain both file and json part.

<details>

How do I get only file bytes from an IRestResponse. Response content contains not only file bytes also some headers and Json.

My code looks like the following.
```
    var response = client.Execute(request);
    byte[] AudioBytes = response.RawBytes;

    using (FileStream fileStream = File.Create("AudioFile.wav"))
    {
        fileStream.Write(AudioBytes, 0, AudioBytes.Length);
    }

```
My content looks like the following.

> Content-Type: application/json; charset=utf-8 
> Content-Disposition: form-data; name=Json 
> {"type":"message","id":null,"timestamp":"2018-08-27T13:40:19.8311239+00:00","localTimestamp":null,"serviceUrl":"localhost"} 
> 
> Content-Type: audio/wav 
> Content-Disposition: attachment; 
> filename=AudioFromTts.wav; name=Audio Content-Encoding: binary 
> some bytes here that represents audio file 
> --- some other lines

</details>

**Comment by alexeyzimarev** [comment]
There is no support for multipart response in RestSharp.
