### ISSUE TITLE
ResponseStatus Error on non success response

### ISSUE THREAD

**Issue by matheussouza97** [restsharp/RestSharp#1163]
Hello, I need help.

I am not getting the correct answer from my server.
When restsharp receives any response that is not successful it responds to me with Error.

Reproduce:

![screenshot at aug 31 12-17-20](https://user-images.githubusercontent.com/14929125/44921342-b9a1a900-ad18-11e8-9e24-076dabe80911.png)

![screenshot at aug 31 12-18-37](https://user-images.githubusercontent.com/14929125/44921345-ba3a3f80-ad18-11e8-820c-9e4f692bd1af.png)

Specification

- RestSharp 106.3.1
- Visual Studio 7.6.3
- Mono 5.12.0.301
- GTK+ 2.24.23
- Xamarin.iOS 11.14.0.14

Stacktrace

"  at System.Net.HttpWebRequest+<GetResponseFromData>d__244.MoveNext () [0x00152] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:1100 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000b5] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:952 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:1198 \n  at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) [0x00002] in /Users/ASAAS/workspace/RestSharp/RestSharp/Http.Sync.cs:163 "

It should work like this:

![screenshot at aug 31 12-26-08](https://user-images.githubusercontent.com/14929125/44921485-0eddba80-ad19-11e8-9c28-e8fe27e290c5.png)

**Comment by alexeyzimarev** [comment]
We are catching all exceptions, check your debug settings
https://github.com/restsharp/RestSharp/blob/106.3.1/RestSharp/Http.Sync.cs#L162

**Comment by Obvious1992** [comment]
@matheussouza97 can you compare your Mono-versions?
I do think this is based on [this Mono Issue](https://github.com/mono/mono/issues/10304)

**Comment by matheussouza97** [comment]
@Obvious1992  Yes, I did. In version 5.10 of the mono, restsharp works only in a Console App, in 5.12 it does not work in the App Console or in the Xamarin.Android and Xamarin.iOS project. And in 5.16 it works the same way as in 5.10.

**Comment by matheussouza97** [comment]
Yes, you're right, I did not know where to ask this question, either in the RestSharp project or in the Mono project.

Thank you for your help.
