### ISSUE TITLE
Check content-type or other headers in response before processing response stream

### ISSUE THREAD

**Issue by zhaomuzhi** [restsharp/RestSharp#1165]
Can ResponseWriter or other API can support accessing the response headers before deserializing the stream? For example, we would like to implement some logic like this:

restRequest.ResponseWriter = (stream) =>
{
         // if content-type is "application/json", deserialize it as json, otherwise log the raw content as string
};

**Comment by alexeyzimarev** [comment]
You need to use the `AdvancedResponseWriter` instead.
