### ISSUE TITLE
How to send multipart/form-data body request without uploading a file?

### ISSUE THREAD

**Issue by ChrisTheEngineer** [restsharp/RestSharp#1168]
Hello,

I am unable to send a rest request using RestSharp where the body is encoded as multipart/form-data. There seems to be an issue, how would you do this via RestSharp? Below is my current code:

```
string url = NDRoutes.Document;
            Boolean useXml = false;

            NewPaperDocumentRequest paperDocumentEntity = FillPaperDocumentRequest(createPaperDocumentRequest);
            RestRequest rr = _communicationsService.FormRequest(Method.POST, url, useXml);
            
            rr.AddHeader("Content-Type", "multipart/form-data");
            string body = JsonConvert.SerializeObject(paperDocumentEntity);
            rr.RequestFormat = DataFormat.Json;
            rr.AlwaysMultipartFormData = true;
            
            rr.AddParameter("action", paperDocumentEntity.Action, "multipart/form-data", ParameterType.GetOrPost);
            rr.AddParameter("name", paperDocumentEntity.Name, "multipart/form-data", ParameterType.GetOrPost);
            rr.AddParameter("extension", paperDocumentEntity.Extension, "multipart/form-data", ParameterType.GetOrPost);
            rr.AddParameter("cabinet", paperDocumentEntity.Cabinet, "multipart/form-data", ParameterType.GetOrPost);
            rr.AddParameter("failOnError", paperDocumentEntity.FailOnError, "multipart/form-data", ParameterType.GetOrPost);
            rr.AddParameter("return", paperDocumentEntity.Return, "multipart/form-data", ParameterType.GetOrPost);
            rr.AddBody(body);

            _communicationsService.ExecuteRequest(rr);
```

**Comment by alexeyzimarev** [comment]
Would be nice if you explain what are you getting.

**Comment by alexeyzimarev** [comment]
BTW you need to decide either you send JSON or you send the form data. You don't need to specify the content type and parameter type for each parameter.

As far I can see in the code, if you set `AlwaysMultipartFormData` to true, it will use the content type you want. But you should not set it manually.

**Comment by ChrisTheEngineer** [comment]
Thanks for the help. The issue I was having was that I wasn't specifying a boundary in the header

`rr.AddHeader("Content-Type", "multipart/form-data;boundary=[your boundary]");`

After I added that and removed the body (since we are using multipart) it started working correctly.

**Comment by alexeyzimarev** [comment]
@ChrisTheEngineer why can't you use the overload that accepts the stream writer? It doesn't require loading the file in memory and will write directly to the request stream.

```csharp
IRestRequest AddFile(string name, Action<Stream> writer, string fileName, long contentLength, string contentType = null)
```

**Comment by yusbash03** [comment]
> Thanks for the help. The issue I was having was that I wasn't specifying a boundary in the header
> 
> `rr.AddHeader("Content-Type", "multipart/form-data;boundary=[your boundary]");`
> 
> After I added that and removed the body (since we are using multipart) it started working correctly.

what is the boundary in this case please?

**Comment by geomorillo** [comment]
how to get the length if there is no file sent?

**Comment by alexeyzimarev** [comment]
That's right, it's just that RestSharp used the file length as the form boundary in previous versions.
