### ISSUE TITLE
Content type for put request is overwritten with application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by bhagyashreeHebbar** [restsharp/RestSharp#1169]
## Expected Behavior
Stauts code: 200 OK

## Actual Behavior
Status code: System.Net.HttpStatusCode.UnsupportedMediaType

## Steps to Reproduce the Problem

  1.Create instance of Put request.
  2.Add parameter to Put request with the method AddParameter.
  3.Add header ContentType as "application/json"
With the above setting the content type of the request gets set as "application/x-www-form-urlencoded". 
## Specifications

  - Version: RestSharp 106.2.2
  - Platform:  Target framework .NetFramework 4.5.2
  - Subsystem: Windows 7

## StackTrace
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)

**Comment by bhagyashreeHebbar** [comment]
To over come this error,  set the parameterised url  for the Request.Resource with string function not by calling the method AddParameter().
Esample:
Do this: request.Resource = _String.Format("/rest/api/2/user?key={0}", key)_  instead of _request.AddParameter("key", "value");_

**Comment by alexeyzimarev** [comment]
@bhagyashreeHebbar what do you want your request to look like?

**Comment by bhagyashreeHebbar** [comment]
I create the request like this:
var client = new RestClient("http://jiraServerName/rest/api/2/user");
var request = new RestRequest(Method.PUT);
request.AddHeader("Accept", "application/json");
request.AddHeader("Content-Type", "application/json");
request.AddHeader("Authorization", "Basic ************");
request.AddParameter("key", "value");
request.AddParameter("application/json", "{\r\n    \"displayName\": \"Ani, Florin\"\r\n}", ParameterType.RequestBody);
IRestResponse response = client.Execute(request);

And ended with the response Mediatype unsupported

**Comment by alexeyzimarev** [comment]
Hmm, I believe that instead of using `request.AddParameter("application/json", "{\r\n "displayName": "Ani, Florin"\r\n}", ParameterType.RequestBody);` you need to call `AddJsonBody`. Can you try that?

**Comment by bhagyashreeHebbar** [comment]
Actually the method request.AddParameter("application/json", "{\r\n "displayName": "Ani, Florin"\r\n}", ParameterType.RequestBody); is not causing the mediaUnsupported response.

The root cause for the mediaUnsupported error is call tothis function
request.AddParameter("key", "value");
Instead of making this call, add the parameter to URL directly
_request.Resource = String.Format("/rest/api/2/user?key={0}", key)_

**Comment by alexeyzimarev** [comment]
I just find it weird that you add a parameter that has a name `application/json`. That doesn't seem right.

**Comment by alexeyzimarev** [comment]
Also, you really should be using the authenticator, instead of adding the header

```
                var client = new RestClient(baseUrl)
                {
                    Authenticator = new HttpBasicAuthenticator("testuser", "testpassword")
                };
```

**Comment by alexeyzimarev** [comment]
Ok, I fixed that one. But you really can simplify your code by using correct methods.

https://github.com/restsharp/RestSharp/blob/develop/RestSharp.IntegrationTests/RequestBodyTests.cs#L247
