### ISSUE TITLE
CustomJsonSerializationStrategy refactored

### ISSUE THREAD

**Issue by darkonejr** [restsharp/RestSharp#1178]
Per the deserlization [wiki](https://github.com/restsharp/RestSharp/wiki/Deserialization), custom JSON strategy requires the static `SimpleJson.CurrentJsonSerializerStrategy` to be set.  I'm unable to do this in recent versions of RestSharp without explicitly adding the SimpleJson library in my using directives (did not need to do this on version 105.2.3), and the main call to change the current serializers needs an additional `SimpleJson`, e.g.

```
SimpleJson.SimpleJson.CurrentJsonSerializerStrategy = new CamelCaseSerializerStrategy();
```

If this is intended, could you update the docs?

**Comment by alexeyzimarev** [comment]
I am planning to bring back Json.Net for v107. So, I don't really see the value of doing any work that is related to SimpleJson. We have tons of issues that are caused by this library and I just want to end this nightmare.

**Comment by alexeyzimarev** [comment]
I see that we changed the namespace for `SimpleJson` from `RestSharp` to `SimpleJson` and then `RestSharp.Tests` (not sure how that has happened). I am reverting it back. The docs were correct though since there is no mention of the namespace, just the static class name.
