### ISSUE TITLE
Uploading files via PUT method

### ISSUE THREAD

**Issue by rafiix** [restsharp/RestSharp#1180]
## Expected Behavior
Uploading files using the http put method to the openstack object storage server. Finally, it must be possible to transfer large files above 1GB.

## Actual Behavior
Files are uploaded to a server of any size, but headers are added to the content of each file, regardless of their size.

For example:
Content of the file before uploading to the server:

TEST 1234
TEST 1234
TEST 1234
TEST 1234
TEST 1234

And the file after uploading to server:

-------------------------------28947758029299
Content-Disposition: form-data; name="putTest.txt"; filename="putTest.txt"
Content-Type: text/plain

TEST 1234
TEST 1234
TEST 1234
TEST 1234
TEST 1234

-------------------------------28947758029299--

The same applies to all types of files.

## Steps to Reproduce the Problem

  1. I use method below:

public void AddFile(string filepath, string containerName, string subDirectory) 
{
FileInfo file = new FileInfo(filepath);
string contentType = MimeMapping.GetMimeMapping(filepath);

client = new RestClient(authData.StorageUrl + $"/{containerName}{subDirectory}{file.Name}");

request = new RestRequest(Method.PUT);
request.AddHeader("x-auth-token", authData.StorageToken);
request.AddHeader("content-type", contentType);
request.AddFile(file.Name, file.FullName, contentType);

client.ExecuteAsync(request, GetStatus);
}
  2. I tried to use the http POST method, but the file transfer failed.
  3. I tried to add "Content-Disposition" and "Content-Type" headers, but it didn't change anything.

## Specifications

  - Version: 106.4.2
  - Platform: .NET Framework 4.5.2, Microsoft VisualStudio 2015, Windows 10

**Comment by alexeyzimarev** [comment]
That is a service specific issue. It does not handle the proper multiform-data content and perceives the full request body as a file. Here I use a simple WebAPI controller to handle the upload and I get the file as expected: https://github.com/alexeyzimarev/RestSharpUpload
