### ISSUE TITLE
Uploading files via PUT method

### ISSUE THREAD

**Issue by rafiix** [restsharp/RestSharp#1181]
_Originally posted by @alexeyzimarev in https://github.com/restsharp/RestSharp/issues/1180#issuecomment-426007324_

I've made changes to my method, but there are still headers added to my files.
My method after the exchanges:

public void AddFile(string filepath, string containerName, string subDirectory)
{
            FileInfo file = new FileInfo(filepath);
            string contentType = MimeMapping.GetMimeMapping(filepath);

            client = new RestClient(authData.StorageUrl);
            request = new RestRequest($"/{containerName}{subDirectory}{file.Name}").AddFile(file.Name, file.FullName);
            request.AddHeader("x-auth-token", authData.StorageToken);

            response = client.Put(request);
}

**Comment by alexeyzimarev** [comment]
Do you still have an issue?

**Comment by rafiix** [comment]
Yes, currently I have a different type of problem and it occurs when transferring large files such as 5GB, 10GB, because the RAM memory is full. I have to send files as a body, otherwise I have this problem with adding headers to the content of files. Is it possible to send the file as a body but without loading the whole file to memory?

**Comment by alexeyzimarev** [comment]
Why don't you use the overload that takes the stream writer? It writes what you give it directly to the request stream, without reading the file in memory.

```csharp
public IRestRequest AddFile(string name, Action<Stream> writer, string fileName, long contentLength, string contentType = null)
```

**Comment by alexeyzimarev** [comment]
I guess, large files have nothing to do with using the PUT method for uploads, so I am closing the issue.

**Comment by rafiix** [comment]
When I use the AddFile method, there is a problem with headers that add to files after uploading.

**Comment by emmanuelrflores** [comment]
Sorry to raise up such an old issue, however when I try using the `AddFile` like you've suggested above

```csharp
FileParameter fileParameter = ParameterToFile(fileName, fileStream);
request.AddFile(fileParameter.Name, fileParameter.Writer, fileParameter.FileName, fileParameter.ContentLength, contentType);
```

the header information is saved with the file on the server side (a java Spring based). 

```
-----------0E1569DD-263A-4A2E-9805-8E98E64646C7
Content-Disposition: form-data; name="RandomFile1846951106.json"; filename="RandomFile1846951106.json"
Content-Type: application/octet-stream

{"var1":"2078929442"}
-----------0E1569DD-263A-4A2E-9805-8E98E64646C7--
```

Your [documentation for handling files](https://restsharp.dev/usage/files.html) only talks about downloading, not necessarily uploading. Do you have some concrete examples on how to properly do this or how to handle large files?

**Comment by ashokmandial** [comment]
> Sorry to raise up such an old issue, however when I try using the `AddFile` like you've suggested above
> 
> ```cs
> FileParameter fileParameter = ParameterToFile(fileName, fileStream);
> request.AddFile(fileParameter.Name, fileParameter.Writer, fileParameter.FileName, fileParameter.ContentLength, contentType);
> ```
> 
> the header information is saved with the file on the server side (a java Spring based).
> 
> ```
> -----------0E1569DD-263A-4A2E-9805-8E98E64646C7
> Content-Disposition: form-data; name="RandomFile1846951106.json"; filename="RandomFile1846951106.json"
> Content-Type: application/octet-stream
> 
> {"var1":"2078929442"}
> -----------0E1569DD-263A-4A2E-9805-8E98E64646C7--
> ```
> 
> Your [documentation for handling files](https://restsharp.dev/usage/files.html) only talks about downloading, not necessarily uploading. Do you have some concrete examples on how to properly do this or how to handle large files?

That's what I am looking for. Can you share how did send {"var1":"2078929442"} in this request? Basically, want to send Base64 string of file along with header information and some data in JSON format like you did {"var1":"2078929442"}

**Comment by ashokmandial** [comment]
Actually i want to post file like

--0E1569DD-263A-4A2E-9805-8E98E64646C7
Content-Disposition: form-data; name="request"
Content-Type: application/json; charset=UTF-8
Content-Transfer-Encoding: 8bit

{    "id": "7c4303a0-1fa3-4823-9cb6-0106c6517ef2", "Type": "fileType" }
--0E1569DD-263A-4A2E-9805-8E98E64646C7
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: base64

MDAwOlZTUFNLVVNUDQowODQ6UFkNCjA1ODoyMDIwDQowMTA6MTkxNDIxNS0xDQowODM6MjIyMjIyLTEyM0ENCjA4NTpNYWluLCB1c2VyIEFMTA0KMTUwOjEwLDAwDQowNDg6QkFTV0FSRV9JTlZPSUNFUkVBRFkNCjAxNDowNTkyNTQyLTRfSVINCjE5ODoyOTA0MjAyMDExNDAwMg0KOTk5OjENCg==
--0E1569DD-263A-4A2E-9805-8E98E64646C7

Can somebody help how can create file post request like this using restsharp? Thanks in advance!

**Comment by prithamrao542** [comment]
@ashokmandial  where you able to get an example. I need an example as well? Need to create file post request like this using restsharp

--0E1569DD-263A-4A2E-9805-8E98E64646C7
Content-Disposition: form-data; name="request"
Content-Type: application/json; charset=UTF-8
Content-Transfer-Encoding: 8bit

{ "id": "7c4303a0-1fa3-4823-9cb6-0106c6517ef2", "Type": "fileType" }
--0E1569DD-263A-4A2E-9805-8E98E64646C7
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf
Content-Transfer-Encoding: base64

MDAwOlZTUFNLVVNUDQowODQ6UFkNCjA1ODoyMDIwDQowMTA6MTkxNDIxNS0xDQowODM6MjIyMjIyLTEyM0ENCjA4NTpNYWluLCB1c2VyIEFMTA0KMTUwOjEwLDAwDQowNDg6QkFTV0FSRV9JTlZPSUNFUkVBRFkNCjAxNDowNTkyNTQyLTRfSVINCjE5ODoyOTA0MjAyMDExNDAwMg0KOTk5OjENCg==
--0E1569DD-263A-4A2E-9805-8E98E64646C7

**Comment by alexeyzimarev** [comment]
@prithamrao542 these are two files, JSON and PDF. RestSharp currently only supports sending one file.
