### ISSUE TITLE
HttpMethod is not overridden in `RestClient.Sync.Execute(IRestRequest request, Method httpMethod)`

### ISSUE THREAD

**Issue by Psypher9** [restsharp/RestSharp#1183]
## Expected Behavior
I expected this method to override the Request's HttpMethod as documented, but it was not.

## Actual Behavior
The HttpMethod is not overridden.

## Steps to Reproduce the Problem

  1. The code is self evident.

**Comment by alexeyzimarev** [comment]
Thanks for the PR! It is out in 106.5
