### ISSUE TITLE
Serializing strings wrapped in curly braces results in invalid json

### ISSUE THREAD

**Issue by zzanol** [restsharp/RestSharp#1189]
Change introduced in https://github.com/restsharp/RestSharp/pull/1185 makes it impossible to serialize an object who has a string values are wrapped in curly braces.

**Input:**
`new { Thing = "{value}" };`

**Expected:**
{"Thing":"{value}"}

**Actual:**
{"Thing":

**Comment by alexeyzimarev** [comment]
I will revert #1185

**Comment by zzanol** [comment]
Thanks @alexeyzimarev
