### ISSUE TITLE
Force different ContentType?

### ISSUE THREAD

**Issue by scastria** [restsharp/RestSharp#1196]
I am converting from portable restsharp to this RestSharp.  The portable version had the ability to specify the ContentHandlers for different MIME types.  I have a REST service that returns JSON, but the Content-Type in the response incorrectly says text/plain.  I cannot fix this REST service so I was able to tell portable restsharp:

`client.ContentHandlers["text/plain"] = client.ContentHandlers["application/json"]
`

which allows the auto deserialization to work such that my response.Data has the deserialized object I need.  When switching to this RestSharp, the response.Data is null for the same reason that it cannot deserialize the response because it thinks it is plain text.  Yes, I can manually deserialize it, but I was curious if there was something similar to ContentHandlers in portable restsharp?

**Comment by alexeyzimarev** [comment]
StackOverflow is a better place to ask questions, as mentioned in the contribution guidelines.

You can use `client.AddHandler("text/plain", new JsonSerializer());`
