### ISSUE TITLE
.AddJson Body does not properly handle already serialized strings with escape characters

### ISSUE THREAD

**Issue by Bumler** [restsharp/RestSharp#1199]
## Expected Behavior
Given a serialized string in the .AddJsonBody() with escape characters the string should be sent as is.

## Actual Behavior
In the .AddJsonBody() method when sending over a string like
\"data\": [ \n
it is converted to 
\\\"data\\\":[\\\n
in the value of the parameter. This means that in the actual network request I'm trying it's not sending json data but a string with escapes all over it.

## Steps to Reproduce the Problem

  1. Use .AddJsonBody on a request and give a serialized string with escape characters as the object.
  (Optional) use a network tracking tool to see the request that is sent

## Workaround
.AddParameter( "application/json", jsonString, ParameterType.RequestBody ); 
Achieves the same idea but works with a string.

## Specifications

  - Version: 106.5.4 (this worked in 106.5.2)

**Comment by alexeyzimarev** [comment]
AddJsonBody is meant to add an object that we serialise to json. It works as designed.

**Comment by alexeyzimarev** [comment]
But if it worked I will look at it. However, there were no changes in this method between 106.5.2 and 106.5.4, I doubt the observation.

**Comment by zzanol** [comment]
This is related to https://github.com/restsharp/RestSharp/issues/1189.  Reverting https://github.com/restsharp/RestSharp/pull/1185 was the right choice.

Rather than trying to fix SimpleJson, perhaps JsonSerializer should be detecting if the object is already json before handing off the object to SimpleJson for serialization.

```
        public string Serialize(object obj)
        {
            if (obj is string value)
            {
                string trimmed = value.Trim();
                if (trimmed.StartsWith("{") && trimmed.EndsWith("}"))
                {
                    return value;
                }

            }

            return SimpleJson.SerializeObject(obj);
        }
```

**Comment by alexeyzimarev** [comment]
I consider this as fixed after the merge, thanks @zzanol. I agree that fixing SimpleJson was not a very good move. In 107 I plan to get rid of SimpleJson and get back to Newtonsoft.Json.

**Comment by vk5880** [comment]
AddBody method is kind of misleading, because it serializes the object passed. What was expected is to pass body string in raw format. Please add a method to set body in raw format with string/byte[] parameter. This will avoid confusion.

**Comment by PierreCollardSuero** [comment]
After upgrading RestSharp from v106 to v107, I started using `restRequest.AddStringBody(serializedJsonBody, DataFormat.Json);`

**Comment by alexeyzimarev** [comment]
@vk5880 for that we have `AddStringBody`, as @PierreCollardSuero pointed out. `AddBody` was adding objects for serialization before, it was selecting the serialization type based on the request data format. That's why it wasn't consistent, as it allowed adding an object body for serialization, or a string. Now, these two ways are separated.

**Comment by alexeyzimarev** [comment]
Also, `AddJsonBody<T>` has now a `class` constraint, so it won't be possible to send a string to it. I think it makes the usage quite clear.

But also, in the latest version it is easy to pass a string and a given content type. If the content type is specified, it does this:

```csharp
        return
            obj is string str            ? request.AddParameter(new BodyParameter("", str, contentType)) :
            contentType.Contains("xml")  ? request.AddXmlBody(obj, contentType) :
            contentType.Contains("json") ? request.AddJsonBody(obj, contentType) :
                                           throw new ArgumentException("Non-string body found with unsupported content type", nameof(obj));
```

So, when you give it a string and explicitly specify the content type, it will add that string with a give content type as body, and it will work with JSON or XML string.
