### ISSUE TITLE
Cannot de-serialize the object

### ISSUE THREAD

**Issue by Hoang-Minh** [restsharp/RestSharp#1206]
## Expected Behavior
Object should be deseriabled properly

Json format:
[
    {
        "repairFacilityID": 9999,
        "shortName": "Name",
        "printName": "NAME",
        "licenseNumber": "1111"
    }
]

## Actual Behavior
return null

## Steps to Reproduce the Problem
This is how I construct my classes:

public class MyLocation
    {
        public List<Location> Location { get; set; }
    }
    public class Location
    {
        public int repairFacilityID { get; set; }
        public string shortName { get; set; }
        public string printName { get; set; }
        public string licenseNumber { get; set; }
    }

 How I call:

var response = new RestRequest(Method.GET)
return client.Execute<MyLocation>(response);

From the response, I try to access Data property, but it returns null. Please let me know if I construct my class properly. Thanks

**Comment by mstrYoda** [comment]
Your class hierarcyh represents the below json structure:
```
{
    "Location" : [
        {
            "repairFacilityID": 9999,
            "shortName": "Name",
            "printName": "NAME",
            "licenseNumber": "1111"
        }
    ]
}
```

You should do instead:

`return client.Execute<List<Location>>(response);`

**Comment by Hoang-Minh** [comment]
Thank you !!! It works
