### ISSUE TITLE
Move ProcessResponse call to the bottom of ExtractResponseData to make Header, Cookie, Status, etc available to AdvancedResponseWriter

### ISSUE THREAD

**Issue by yurikus** [restsharp/RestSharp#1207]
Move ProcessResponse call to the bottom of ExtractResponseData to make Header, Cookie, Status, etc available to AdvancedResponseWriter.
See https://github.com/restsharp/RestSharp/pull/1208

**Comment by PaulVrugt** [comment]
so, when are we releasing this? We are anxiously awaiting this fix (1208)

**Comment by alexeyzimarev** [comment]
It is released in 106.6
