### ISSUE TITLE
Unsupported operations should not silently be ignored

### ISSUE THREAD

**Issue by simendsjo** [restsharp/RestSharp#1227]
When executing GET with a body, the body is simply ignored as it's not supported.
The user expected a body to be posted, and the server expected to receive a body, but instead only receives null.

`HttpWebRequest` does not support body for `GET`, and would throw in this case, but `RestSharp` choose to silently ignore the body for `GET` requests. I propose that the operation should rather fail. Maybe through using `HttpWebRequest` directly, or throwing its own message.

Looks like body has been ignored for a long time, but you started added body for DELETE and OPTIONS in 2013: https://github.com/restsharp/RestSharp/commit/7d4674da9485d4e6e6d8b9086aad180d22176155

This commit doesn't contain any design notes or rationale, and I think the current behavior of ignoring parts of the user request is dangerous and hides bugs (or simple moves them away from the source as for our case).

``` patch
diff --git a/RestSharp/Http.Sync.cs b/RestSharp/Http.Sync.cs
index 1fab300..f7ea95a 100644
--- a/RestSharp/Http.Sync.cs
+++ b/RestSharp/Http.Sync.cs
@@ -87,10 +87,17 @@ private HttpResponse GetStyleMethodInternal(string method)
         {
             var webRequest = ConfigureWebRequest(method, Url);
 
-            if (HasBody && (method == "DELETE" || method == "OPTIONS"))
+            if (HasBody)
             {
-                webRequest.ContentType = RequestContentType;
-                WriteRequestBody(webRequest);
+                if (method == "DELETE" || method == "OPTIONS")
+                {
+                    webRequest.ContentType = RequestContentType;
+                    WriteRequestBody(webRequest);
+                }
+                else
+                {
+                    throw new NotSupportedException($"Http verb {method} does not support body");
+                }
             }
 
             return GetResponse(webRequest);
```

or

``` patch
diff --git a/RestSharp/Http.Sync.cs b/RestSharp/Http.Sync.cs
index 1fab300..e5a8943 100644
--- a/RestSharp/Http.Sync.cs
+++ b/RestSharp/Http.Sync.cs
@@ -87,7 +87,7 @@ private HttpResponse GetStyleMethodInternal(string method)
         {
             var webRequest = ConfigureWebRequest(method, Url);
 
-            if (HasBody && (method == "DELETE" || method == "OPTIONS"))
+            if (HasBody)
             {
                 webRequest.ContentType = RequestContentType;
                 WriteRequestBody(webRequest);
```

**Comment by alexeyzimarev** [comment]
The commit has a rationale of adding a body to OPTION and DELETE requests since the method `GetStyleMethodInternal` is being used for those verbs too, but I agree that it could have been done better. I'm afraid it cannot be fixed without introducing a breaking change, but I will put the code in to be released in 107, since the major version change could have it as a breaking change.

**Comment by sebastienricher** [comment]
Just to chip in, I think I just bumped into this and somewhat wasted a few hours. An explicit error message would have been much help!

**Comment by alexeyzimarev** [comment]
@sebastienricher are you sure that's the same issue? Because the aforementioned code has been changed already:

```
        HttpResponse GetStyleMethodInternal(string method)
            => ExecuteRequest(
                method, r =>
                {
                    if (!HasBody || !CanGetWithBody()) return;

                    r.ContentType = RequestContentType;
                    WriteRequestBody(r);

                    bool CanGetWithBody() => method == "DELETE" || method == "OPTIONS";
                }
            );
```

**Comment by alexeyzimarev** [comment]
Ah, I see. We still silently ignore it.
