### ISSUE TITLE
Retaining authorization header in RestSharp during redirects

### ISSUE THREAD

**Issue by shahamit** [restsharp/RestSharp#1229]
I am using RestSharp to make a GET api call. The api call is authenticated through HTTP Basic authentication by passing the authorization header.

The server redirects the api call with a status code 307. My client code does handle the redirects but the authorization header is not passed to this redirected api call. This is done for valid reasons as mentioned here. Hence I do get an unauthorized error.

How can I configure the RestClient to restore the authorization header when responding to the redirected api call?

`var client = new RestClient("https://serverurl.com");
var request = new RestRequest(Method.GET);

request.AddHeader("Authorization", "Basic Z3JvdXAxOlByb2otMzI1");
request.AddHeader("Content-Type", "application/json");
request.AddHeader("Tenant-Id", "4892");

IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);`

**Comment by shahamit** [comment]
By client code I meant the C# code that I pasted in the above post.

**Comment by glaucodiogo** [comment]
I have it's problem too.

**Comment by acornforth** [comment]
I am also having a similar problem, but with Oauth2 ...
I can obtain an access token from `domain.com/oauth2/token`
In my code i was then making a request to the API i'm consuming. The Server running the API is configured to automatically redirect anything without a trailing slash, so i was getting a 301 redirect.
While the Bearer token was being correctly added to the headers for the original request, it was definitely not present for the request made to the redirected endpoint.
Sure I could manually write extra code to check for the 301 response, and re-request with the token again, but surely, if restsharp is going to automatically follow the redirect, it should do so while retaining the header from the original request ?

**Comment by SamHard** [comment]
By way of a work-around, you can write your own redirect logic by turning off FollowRedirects in the client object.
`var client = new RestClient(BaseUrl)
{
    FollowRedirects = false // we handle redirects in code, to avoid authorization problems
};`

**Comment by amir-abdi** [comment]
Same problem here. Has this been resolved?

**Comment by ichivers** [comment]
I think this needs to be fixed?
