### ISSUE TITLE
OAuth 2.0 Token Generation via Restsharp

### ISSUE THREAD

**Issue by parwalrahul** [restsharp/RestSharp#1231]
I have done a lot of R&D but could not find a way to automate scenarios with Token Generation using OAuth 2.0.
Is this possible via Restsharp?  If yes, How?

If No?, Are there any plans of adding this facility via Restsharp?

**Comment by AhmetEkmekci** [comment]
Hi,
Of course there would be another ways but the best way I found is below, at least it works;

` 
                var client = new RestClient(baseURL);
                var request = new RestRequest("token", Method.POST);

                request.AddParameter("client_id", clientId, ParameterType.GetOrPost);
                request.AddParameter("grant_type", "client_credentials", ParameterType.GetOrPost);
                request.AddParameter("client_secret", clientSecret, ParameterType.GetOrPost);
                req.AddParameter("scope", scope, ParameterType.GetOrPost);
                req.AddParameter("response_type", response_type, ParameterType.GetOrPost);

                var response = client.Execute(request);`

**Comment by Rzpeg** [comment]
Use [IdentityModel](https://github.com/IdentityModel/IdentityModel2)'s HttpClient extension methods, that were tailored especially for OAuth, including validation
```

var client = new HttpClient();
var disco = await client.GetDiscoveryDocumentAsync("https://demo.identityserver.io");
var response = await client.RequestTokenAsync(new TokenRequest
{
    Address = disco.TokenEndpoint,
    GrantType = "custom",

    ClientId = "client",
    ClientSecret = "secret",

    Parameters =
    {
        { "custom_parameter", "custom value"},
        { "scope", "api1" }
    }
});

```

**Comment by alexeyzimarev** [comment]
@Rzpeg that's basically the same as the code written by @AhmetEkmekci, which can be greatly simplified by using a POST with `AddObject`.

**Comment by alexeyzimarev** [comment]
@parwalrahul look, all OAuth2 APIs are different. We keep getting questions "how to use OAuth2" without mentioning what API are you trying to use, like there is only one way to deal with all of them. The code snippet above works _only_ with the IdentityServer and all products that use it, but it won't work, for example, with Twitter.

So, you need to do the following:

- Go to the API documentation that you are planning to use
- Understand what parameters you will need to send
- Remember that you should not use body parameters. Use `AddParameter(name, value)` and we add encode them and add them to the body when you do the POST request.
- Check the `OAuth2Authenticator` base class and possibly both implementations, which are very simple and can give you an idea of how to implement one for the API you are planning to use
-  Use your authenticator like any other RestSharp authenticator by telling the client to use it.
