### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by VentsislavDinev** [restsharp/RestSharp#1233]
Hello,

var restClient = new RestClient("https://asda.com/as/" + "asd/ads/");
            var request = new RestRequest(Method.GET);
          
            request.Resource = "search-records.json?auth-userid={auth-userid}&api-key={api-key}" +
               "&domain-name={domain-name}&type={type}&no-of-records={no-of-records}" +
               "&page-no={page-no}";
            request.AddParameter("auth-userid", "dassda", ParameterType.UrlSegment);

            request.AddParameter("api-key", "dasdas", ParameterType.UrlSegment);
        
            request.AddParameter("domain-name", "hostingfund.com", ParameterType.UrlSegment);
            request.AddParameter("type", "A", ParameterType.UrlSegment);
             request.AddParameter("no-of-records", 50, ParameterType.UrlSegment);

             request.AddParameter("page-no", 1, ParameterType.UrlSegment);

When i start ot localhost work. When i upload my site to the hosting i have error "The underlying connection was closed: An unexpected error occurred on a send."

  1. Version: 106.5.41
  2. .NET 4.7.2
  3.. Windows shared hosting 
  4. ASP.NET MVC 5.

</details>

**Comment by bob0the0mighty** [comment]
I'm having a similar issue except I'm using a Post request. 

No exceptions are thrown, but the error in the request is the same as above.

I only noticed it when I got my code to a staging environment, where it consistently happens, even though it works without issue on our dev environments and a different staging environment.

**Comment by bob0the0mighty** [comment]
#942 fixed the problem for me. frustrating since it was an intermittent problem
