### ISSUE TITLE
Update readme with housekeeping info

### ISSUE THREAD

**Issue by jasond-s** [restsharp/RestSharp#1235]
Not sure where to ask this question so thought an issue might be helpful. 

Have just updated to v106.5.4 from v106.3.x and all our OAuth1 code has broken, reading around it sounds like the work is ongoing to fix (#1204), but would be good if the readme could be more descriptive.

1. known issues and features in certain versions.
2. Versioning scheme (I am getting quite used to semver these days and so wasn't expecting breaking changes in a `x.{delta y}.z` type version change).

These house keeping things seem separate to the wiki that seems to be for code examples. 

Happy to help, but didn't want to just create a PR (I wouldn't know everything that needed to be in it tbh) without context or discussion.

**Comment by alexeyzimarev** [comment]
There were no plans for breaking changes. I am not sure we need any other place to list the issues that are reported than GitHub issues. To be honest, I have no examples of such information being placed in the readme file, in any OSS project that I know about.
