### ISSUE TITLE
Always fill request in response

### ISSUE THREAD

**Issue by ParanoikCZE** [restsharp/RestSharp#1236]
I've run into behavior where other side timeouts with a message like 'cannot connect to server' with response code 0. However, as I'm auto logging any issues, I'm taking requests' details, but ended with null reference exception.

I've found out that e.g. in sync https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestClient.Sync.cs ln 119, the request is being added only on a successful result. Can this be changed that request is added before the call itself or in finally so info like this is not lost?

**Comment by alexeyzimarev** [comment]
Feel free to change it, I see no issue if you move one line outside of the `if`
