### ISSUE TITLE
DateTime deserialization inconsistencies

### ISSUE THREAD

**Issue by Robik81** [restsharp/RestSharp#1237]
## Expected Behavior
DateTime should be deserialized consistently.

"2018-12-09T15:09:54" is deserialized as UTC... AND the time is not correct after deserialization, the time is one hour off (in my timezone)!

Deserialization of date time that contain with millisecond part produces time correctly.

To fix the issue, I changed my server code to always send DateTime in UTC format (trailing Z). Deserialization then went OK.

Then I noticed another issue, deserialization seems to pick Local or Utc on the whim (atleast it did shift the time accordingly though). It should keep the Utc or Local depending on in what format the time was received.

## Steps to Reproduce the Problem

  1. Try to deserialize DateTime "2018-12-09T15:09:54" in other than UTC zone (if local zone = UTC zone it would be correct I assume, as there is no timeshift to be made), it will mess the value

## Specifications

  - Version: 106.5.4.0
  - Platform: .NET
  - Subsystem: ?

**Comment by vbjay** [comment]
Read up on [DateTime.Kind](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.kind)  Also use [DateTimeOffset ](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset)instead.  If you have control of the api sending the json, make it return "2018-12-09T15:09:54Z" or" 2018-12-09T15:09:54-4:00".  DateTimeOffsets will help in that area.

**Comment by vbjay** [comment]
See #1187

**Comment by Robik81** [comment]
I am not even sure it is the same issue, and it should be fixed in 106.5 and I found the bug in 106.5.4

**Comment by Lechus** [comment]
I swapped built-in (de)serializer for Newtonsoft json (de)serializer and it works.

**Comment by alexeyzimarev** [comment]
Yeah, it would be helpful to mention what serialization is being used. SimpleJson uses UTC and we aren't going to change it. Replace the serializer with Newtonsoft.Json, it is easy now. In v107 it will be the default anyway.

**Comment by Robik81** [comment]
1) messing up date value in deserialization (not just shifting it to a different time zone) has nothing to do with whether SimpleJson uses UTC or not, it is a pretty serious bug

2) I did not mention serializer, because I used default?

3) I feel like I wasted my time trying to help, I am not going to bother you any longer.

**Comment by alexeyzimarev** [comment]
At least it would have helped to say if it was json or xml.

I am sorry you feel that way, but ok. I don’t feel that I am wasting my time my maintaining this project and spending hours at night writing code. Thank you for reporting the issue, we’ll see if it still be there after the default serialisation changes.
