### ISSUE TITLE
JSON deserialization doesn't work

### ISSUE THREAD

**Issue by pfedotovsky** [restsharp/RestSharp#1238]
## Expected Behavior

JSON deserialization works properly

## Actual Behavior

JSON Deserialization fails with System.InvalidCastException: 'Invalid cast from 'System.String' to 'TweetClient.Tweet'.'

## Steps to Reproduce the Problem

  1.  Run the following code
```
public static string BaseURL = "https://tweetazure.azurewebsites.net/api";

public static string ResourceName = "RestSharp";

var client = new RestClient(BaseURL);
var request = new RestRequest(ResourceName, Method.GET, DataFormat.Json);
var tweetResponse = client.Execute(request);

var restSharpContent = tweetResponse.Content;

// TODO fails
SimpleJson.SimpleJson.DeserializeObject<Tweet>(restSharpContent);
```

Or run https://github.com/pfedotovsky/dotnetru-backend/tree/master/TweetClient

## Specifications

RestSharp 106.5.4
Windows 10 x64

</details>

Seems that RestSharp incorrectly escapes characters while downloading. 
Same request with plain HttpClient or Flurl works properly.

**Comment by ParanoikCZE** [comment]
Tried to check, but that url is dead.
What happens if you call client.Execute<Tweet> and check reponse.Data object?

**Comment by pfedotovsky** [comment]
@ParanoikCZE URL is not dead, it's: `GET https://tweetazure.azurewebsites.net/api/RestSharp`

**Comment by ParanoikCZE** [comment]
Now it's working, seems like a disturbance in the force .. I was getting 404.
I've checked that response is "{\"TweetedImage\":\"\"}" .. what you've posted is VS escaped string. I can confirm that there are some wrong settings in RS as if I take minimum code with WebRequest that RS is using, it works flawlessly as well .. 

```
            string BaseURL = "https://tweetazure.azurewebsites.net/api";
            string ResourceName = "RestSharp";
            var request = System.Net.WebRequest.Create(BaseURL + "/" + ResourceName);
            request.Method = "GET";
            var response = request.GetResponse();
            var stream = response.GetResponseStream();
            var reader = new StreamReader(stream);
            var content = reader.ReadToEnd();
            response.Close();
```

**Comment by alexeyzimarev** [comment]
I don't think RestSharp does anything with the content when downloading it.

**Comment by alexeyzimarev** [comment]
It is actually wise to try Fiddler first before opening an issue.

Content type parameter that you set to JSON is only used for body parameters.

For requests without a body, we sent requests with
`Accept: application/xml, text/xml, application/json, text/json, text/x-json, text/javascript`, so the server can decide what to send.

Your API returns a JSON string wrapped in XML:

```
<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">{"TweetedImage":""}</string>
```

The response content type is also set to `application/xml`.

If your API would send the response properly, you'd get it working as expected.

**Comment by alexeyzimarev** [comment]
There are at least three ways to fix this:

- Force JSON on the API side
- Add the `Accepted` header to the request client
- Remove the XML handler `client.RemoveHandler("application/xml")`, which will not add any XML content types to the `Accepted` header, leaving only JSON.

**Comment by pfedotovsky** [comment]
@alexeyzimarev it’s not about Fiddler, it’s about RestSharp not doing a good job of handling such cases while all other tools work as expected.

**Comment by alexeyzimarev** [comment]
@pfedotovsky I am sorry you feel that way but clearly, you are wrong. RestSharp sends the `Accept` header for any response handlers that are registered, in full compliance to the RFC. Your API incorrectly sends an unexpected XML response that wraps your JSON response as a string, instead of at least return a proper XML. It is either a bug in Azure Functions, or something else, I don't know. The response header clearly tells RestSharp that it is XML. If you want to change the request content type to JSON only, you can use one of the methods I pointed to.
