### ISSUE TITLE
Support for DataMember and DataContract

### ISSUE THREAD

**Issue by FrankyBoy** [restsharp/RestSharp#1239]
Related: #210, #458 

RestSharp should support for _the_ standard attributes of deserialization, which is DataContract and DataMember. Forcing everyone to implement a custom serializer/deserializer is not a good option.

**Comment by alexeyzimarev** [comment]
We are not going to do it for SimpleJson. The next major version will get back to Newtonsoft.Json.

**Comment by GlenBoonzaier** [comment]
Why is this closed?
FrankyBoy did not ask for this to be done for SimpleJson.  He was asking for RestSharp to support DataContract and DataMember aware serialization and deserialization.

If the next major version is with Newtonsoft.Json, then it needs to be done there.

**Comment by alexeyzimarev** [comment]
I gave the reason for that and I believe I made myself clear. There's nothing to "fix" for Newtonsoft.Json since it supports serialisation attributes out of the box.

**Comment by GlenBoonzaier** [comment]
I think perhaps we not on the same page...

The current execute method does not take any annotations into account.
Example:
Currently, if you have a POCO such as

     public class Person {
        [JsonProperty("primary_name")]
        public string Name {get;set;}
    }
And you have a JSON object

    {
        primary_name:"Jenny"
    }
Now if you try:

    var restResponse = client.Execute<Person>(request);
RestSharp will not know to map primary_name to Name.  Currently users of the library are required to create their own custom serialization and deserialization implementations to get this rather trivial piece of mapping to work.  We are asking that this should be avoided and RestSharp should honour DataMember, JsonProperty type annotations straight out the box.

**Comment by alexeyzimarev** [comment]
I know that and we aren't going to change SimpleJson for any reason. That is why I made necessary changes to enable people to use any serializer they want. It is described in the wiki and I even added a snippet for Json.NET https://gist.github.com/alexeyzimarev/c00b79c11c8cce6f6208454f7933ad24

And I am completely lost on this:
> If the next major version is with Newtonsoft.Json, then it needs to be done there

Done what where? Newtonsoft.Json supports `DataContract` and `DataMember` attributes out of the box.

**Comment by FrankyBoy** [comment]
I think he is saying the issue should remain open until the version of RestSharp that actually fixes this behavior is released. Personally I don't care because for me this is simply a reason not to consider using this library any more.

**Comment by alexeyzimarev** [comment]
Ok, the new issue is being open still so I will keep it open, but there are people asking to keep the SimpleJson version as well. I am still trying to figure out how to solve it.
