### ISSUE TITLE
Response Encoding (Swedish)

### ISSUE THREAD

**Issue by TakhirMamirov** [restsharp/RestSharp#1240]
When making a POST request to a 3rd party service, we need to get Swedish data back. Using PostMan I see Swedish letters as expected:
```
{
        "regnr": "AMJ500",
        "skadedatum": "2018-11-07",
        "skadetyp": "Skadegörelse"
}
```
but not when using RestSharp:

```
{
      "regnr":"AMJ500",
      "skadedatum":"2018-11-07",
      "skadetyp":"Skadeg�relse"
}
```
I was trying to set request encoding as:

`client.Encoding = Encoding.GetEncoding("ISO-8859-1");`

or

```
 request.AddHeader("Content-Encoding", "ISO-8859-1");
 request.AddHeader("Content-Type", "application/json; charset=\"ISO-8859-1\"");
```

and it didn't help. Version 105.2.2.

**Comment by ParanoikCZE** [comment]
So, you are setting headers for request and expect that response will be encoded this way? I hope you now see what is wrong.
So, when you use RestSharp .. from which property did you get this?
What are response headers?

**Comment by TakhirMamirov** [comment]
I've been also using OnBeforeDeserialization() to set the response encoding as:

```
request.OnBeforeDeserialization = response =>
            {
                Encoding encoding = Encoding.GetEncoding("ISO-8859-1");
                response.ContentEncoding = encoding.ToString();              
            };

var response = await client.ExecutePostTaskAsync<List<MyClaim>>(request).ConfigureAwait(false);
```
but it also didn't help. The response.Data has all correctly mapped "MyClaim" objects, but Swedish values of the properties still have those � signs.

**Comment by TakhirMamirov** [comment]
Solved:

```
request.OnBeforeDeserialization = response =>
            {
                Encoding encoding = Encoding.GetEncoding("ISO-8859-1");
                response.Content = encoding.GetString(response.RawBytes);
            };

            try
            {
                var response = await client.ExecutePostTaskAsync<List<MyClaim>>(request).ConfigureAwait(false);
```
