### ISSUE TITLE
Data at the root level is invalid. Line 1, position 1

### ISSUE THREAD

**Issue by HandsomeBoy01** [restsharp/RestSharp#1247]
## Expected Behavior
Be able to serialize correctly

## Actual Behavior
Data at the root level is invalid. Line 1, position 1

## Steps to Reproduce the Problem

  1.Error reporting when the request returns successfully
  2.
  3.

## Specifications

  - Version:106.6.3
  - Platform:.Net4.6.1
  - Subsystem:

## StackTrace
<details>
var response = client.Execute < HuaWeiPushResultDto > (request);

then  response.ErrorMessage show Data at the root level is invalid. Line 1, position 1

but response.Content have value

I don't know how to Solve the problem

</details>

**Comment by HandsomeBoy01** [comment]
anybody here？

**Comment by alexeyzimarev** [comment]
You haven’t posted the code, request, stack trace. How do you expect people to help you?

**Comment by alexeyzimarev** [comment]
No details provided, closing.
