### ISSUE TITLE
RestClient.AddDefaultParameter the default parameter doesn't show up in request

### ISSUE THREAD

**Issue by yguangotham** [restsharp/RestSharp#1249]
## Expected Behavior
after call RestClient.AddDefaultParameter, the default parameter should show up in request

## Actual Behavior
after call RestClient.AddDefaultParameter, the default parameter doesn't show up in request

in 106.5.4 it works well
in 106.6.3 it doesn't work anymore

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: 106.6.3
  - Platform: win 10
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
Nothing?
