### ISSUE TITLE
Add Async/Await feature for Windows UWP project

### ISSUE THREAD

**Issue by zydjohnHotmail** [restsharp/RestSharp#1250]
## Expected Behavior
The normal async/await

## Actual Behavior
Simply stuck

## Steps to Reproduce the Problem

  1.  Launch VS 2017 to create a UWP project
  2.  Add the following code:
using RestSharp;
using System.Diagnostics;
using System.Threading;
using Windows.UI.Xaml.Controls;

namespace UWPRestSharp
{
    public sealed partial class MainPage : Page
    {
        public async void MainPageAsync()
        {
            this.InitializeComponent();
            RestClient client = new RestClient("http://www.google.com");
            var request = new RestRequest("http://www.google.com");
            var cancellationTokenSource = new CancellationTokenSource();
            var restResponse = await client.ExecuteTaskAsync(request, cancellationTokenSource.Token);
            Debug.WriteLine(restResponse.Content); 
        }
    }
}
  3. Run

## Specifications

  - Version: 106.6.3
  - Platform: Windows 10 1809
  - Subsystem:

## StackTrace
Nothing: program stuck, not going further.
<details>

```

```

</details>

Hello:
I have been using RestSharp for quite some time, and it works very well in Console Project (C#).  But due to the technology advance, we have to migrate most of the development to UWP (Universal Windows Platform) on Windows 10.
One of the often used feature of RestSharp we are using is async/await.  When we tried to migrate some of our code from C# console project, we have some issue using the async/await.
The following code is working even under the new Console App C# (Universal Windows) project:
RestClient client = new RestClient("http://www.google.com");
var request = new RestRequest("http://www.google.com");
var cancellationTokenSource = new CancellationTokenSource();
var restResponse = await client.ExecuteTaskAsync(request, cancellationTokenSource.Token);
            Console.WriteLine(restResponse.Content); 

But if I created a new UWP Blank Universal Windows project, the following code can be compiled, but when run, it stuck without going after the this.InitializeComponent(); statement.  
using RestSharp;
using System.Diagnostics;
using System.Threading;
using Windows.UI.Xaml.Controls;

namespace UWPRestSharp
{
    public sealed partial class MainPage : Page
    {
        public async void MainPageAsync()
        {
            this.InitializeComponent();
            RestClient client = new RestClient("http://www.google.com");
            var request = new RestRequest("http://www.google.com");
            var cancellationTokenSource = new CancellationTokenSource();
            var restResponse = await client.ExecuteTaskAsync(request, cancellationTokenSource.Token);
            Debug.WriteLine(restResponse.Content); 
        }
    }
}

I wish you can fix this issue and make it working in UWP Blank Universal Windows project.  I know it could be a little tough, but to think you already made quite a big progress.  When not so long ago, with RestSharp Version 106.5.4 and below, I can’t even install RestSharp nuget package in UWP project.  Now with RestSharp 106.6.1; 106.6.2 & 106.6.3, I can install all of them in UWP project, and they all work without async/await.  Now, the only issues are async/await not working yet.
Please consider to add the feature for UWP Blank Universal Windows project.
By the way, my development environment is Visual Studio 2017 Version 15.9.4 on Windows 10 1809 (OS build 17763) with latest updates.  I tried at least 4 different version of RestSharp: 106.5.4;106.6.1; 106.6.2 & 106.6.3.  The first one 106.5.4 can’t be installed in UWP project.  Versions106.6.1; 106.6.2 & 106.6.3 all work in UWP projects, but without async/await.
Thanks,

**Comment by jnsn** [comment]
I have observed the same problem in a Xamarin.Forms application. Calling `ExecuteTaskAsync<T>` never completes.

I currently wrap the sync call in a `Task.FromResult`, but this of course means I am losing any `CancellationToken` support.
