### ISSUE TITLE
RestClient.ClearHandlers() does not exist

### ISSUE THREAD

**Issue by JackSteel97** [restsharp/RestSharp#1253]
## Expected Behavior
RestSharp.RestClient.ClearHandlers() Method exists.

## Actual Behavior
Error:
`System.MissingMethodException: Method not found: 'Void RestSharp.RestClient.ClearHandlers()'.`

Has this method been removed or deprecated? I cannot find anything in the release notes and after googling around to say either way.

RestSharp Version: 106.6.3

**Comment by alexeyzimarev** [comment]
Fixed in 106.6.4
