### ISSUE TITLE
Question: Write to RequestStream directly

### ISSUE THREAD

**Issue by grant-d** [restsharp/RestSharp#1256]
I am trying to write directly to the `RequestStream`, but it doesn't work.
I know I can convert to `byte[]` first but we'd prefer not to (and it's not a `File` nor do we know the `ContentLength` ahead of time)
Is this even possible (idiomatic) in RestSharp?

Here's the pattern I tried but it fails:
```csharp
Stream myStream = ...;

_client.ConfigureWebRequest(req =>
{
    req.ContentType = "application/octet-stream"; // Not Json/Xml
    Stream stream = req.GetRequestStream();
    myStream.CopyTo(stream); // Write directly into the request stream
});

IRestResponse response = await _client.ExecuteTaskAsync(request, cancellationToken)
    .ConfigureAwait(false);
```

**Comment by alexeyzimarev** [comment]
Are you sure that your server won't complain about the content length? If it is a multipart form data, you can still use the `AddFile(fileParameter)` and assign `fileParameter.Writer`, which we call to write to the request stream as a body.
