### ISSUE TITLE
ContentType is not being set

### ISSUE THREAD

**Issue by i4rilu** [restsharp/RestSharp#1257]
https://github.com/restsharp/RestSharp/blob/9b59f6942b7a3af4e660f17a95b39b22ef5ff5f3/RestSharp/RestRequest.cs#L359

Different constructor should be used here and ContentType should be set to "application/xml".
With current code incorrect XmlSerializer (first in the list by data format, not the one specified via RestRequest.XmlSerializer property) is being chosen later.

**Comment by alexeyzimarev** [comment]
Hmm, we take the content type from the serializer. Can you post what your request looks like, and your request code?

**Comment by i4rilu** [comment]
```csharp
var client = new RestClient("SomeURL");
var request = new RestRequest("/", Method.POST) { XmlSerializer = new DotNetXmlSerializer() };
request.AddHeader("Content-Type", "application/xml");
request.AddHeader("Accept", "application/xml");
request.AddXmlBody(requestObj);
var result = client.Execute(request);
```
**v106.6.5**: when I execute the code above - XmlRestSerializer is being picked for serialization instead of DotNetXmlSerializer one.

**v106.5.4**: works as expected.

**Comment by OriolBonjoch** [comment]
I had the same error.
It happens with a custom serializer (mine was a Json).

Checking a bit the code looks like due the change from BodyParameter to XmlParameter/JsonParameter it doesn't pick the custom request serializers. I didn't have the time to check the theory and went back to v106.5.4.

**Comment by alexeyzimarev** [comment]
@i4rilu thanks for the snippet! I will write a test to see how it works.

**Comment by alexeyzimarev** [comment]
@i4rilu I don't think you need to add those headers tbh. It should work without it.

**Comment by alexeyzimarev** [comment]
Try 106.6. I added a test and it was indeed an issue. It should work now.

**Comment by i4rilu** [comment]
**v106.6.6** works fine. Thank you!
