### ISSUE TITLE
RestRequest.RootElement is ignored since 106.6

### ISSUE THREAD

**Issue by LarsLautrup** [restsharp/RestSharp#1258]
## Expected Behavior

When I specify the root element in 106.5.4, the response is parsed nicely from the specified root by the Execute method:

client.Execute<MyCustomer>(request)

## Actual Behavior

In versions above 106.5.4, the RootElement specified is ignored and it always parses the actual root of the response, making the resulting Data containing a MyCustomer instance of nulls

**Comment by alexeyzimarev** [comment]
As _clearly_ described in the contribution guidelines, we need:

- Code snippet
- Current behaviour (what response you get)
- Expected behaviour (what you want to get)

**Comment by LarsLautrup** [comment]
Expected/Actual described above.

160.5.4 returns: Href: /v2/networks/norisbike-nurnberg - Id: norisbike-nurnberg
160.6.6 returns: Href:  - Id:

Code snippet:

static void Main(string[] args)
    {
      RestClient client = new RestClient("http://api.citybik.es/v2/networks");
      RestRequest request = new RestRequest(Method.GET);
      request.RootElement = "networks";
      var ret = client.Execute<List<NetworkInfo>>(request);
      Console.WriteLine($"Href: {ret.Data[0].href} - Id: {ret.Data[0].id}");
    }
  }

  class NetworkInfo
  {
    public string href { get; set; }

    public string id { get; set; }
  }

**Comment by alexeyzimarev** [comment]
I will fix it now. It will be out in the next minor.

But, to be honest, I don't like having XML-specific things in `IRestClient`. Also, the fact that our default accept type is XML is weird. The API you are calling returns JSON by default, you could have very easily use JSON and avoid using this weird `RootElement` assignment.

**Comment by LarsLautrup** [comment]
XML? Theres no XML involved anywhere. "networks" is the root element of the data in the returned JSON.
It has been a problem in all versions above 106.5.4

**Comment by nlaslett** [comment]
I'm not sure if this is the same issue, but as of a recent update all my Accept headers prefer XML over JSON, and it starting causing all serialization of returned data to fail and return NULL objects.

What I'm seeing the raw data: Accept:
application/xml, text/xml, application/json, text/json, text/x-json, text/javascript

Going back and changing all my RestRequest objects to manually specify JSON in the header is a no-go.

**Comment by nlaslett** [comment]
I use RootElement all the time with JSON.  Or I did until [everything broke](https://github.com/restsharp/RestSharp/issues/1260).

**Comment by alexeyzimarev** [comment]
You are both right. I fixed it on 106.6.7, but I still don't like it. The default JSON serializer in 107 will be Newtonsoft.Json and I don't think we'll support `RootElement` for JSON in the future. You can always fall back to SimpleJson (at least for some time) or give me an idea how to implement the `RootElement` support for Json.Net.

**Comment by ThomasBarnekow** [comment]
@alexeyzimarev Can you at least provide an example of how we should replace the usage of RootElement for JSON? This seems to be a behavior that is used by a good number of developers, myself included.

**Comment by ThomasBarnekow** [comment]
@alexeyzimarev Would you have any hint on this?

**Comment by kendallb** [comment]
I just ran into this problem myself, not that the code is failing but I am getting warnings now:

'RestRequest.RootElement' is obsolete: 'Add custom content handler instead. This property will be removed.'

It's not clear from the warning what the correct solution to supporting the root element for JSON deserializing should be?

**Comment by kendallb** [comment]
It has been a while and I just ran into this again. For anyone else looking to extract the root element from JSON, you can do it using dynamics and System.Text.Json like this (and similarly you could do it with JSON.NET also):

```C#
    /// <summary>
    /// Venture through the root element keys to find the root element of the JSON string.
    /// </summary>
    /// <param name="data">A string of JSON data</param>
    /// <param name="rootElementKeys">List, in order, of sub-keys path to follow to deserialization starting position.</param>
    /// <returns>The value of the JSON sub-element</returns>
    private static string GoToRootElement(
        string data,
        List<string> rootElementKeys)
    {
        var json = JsonSerializer.Deserialize<dynamic>(data);
        try {
            rootElementKeys.ForEach(key => { json = json[key]; });
            return json.ToString();
        } catch (Exception) {
            return null;
        }
    }
```
