### ISSUE TITLE
Confusion about AddJsonBody

### ISSUE THREAD

**Issue by christianboese** [restsharp/RestSharp#1259]
This might not be a bug but it lead to some code not working and I am not sure about the desired behaviour.

## Expected Behavior
Json string looks the same as before or the change is mentioned in the documentation.

## Steps to Reproduce the Problem
```cs
        string username = "foo";
        string password = "bar";
        object clientToken = "123";
        var content = new {
            payload = new {
                username,
                password,
                clientToken,
            }
        };
        var request = new RestRequest("api/exampleendpoint", Method.POST, DataFormat.Json);
        request.AddJsonBody(content);
        Console.WriteLine(request.Parameters[0]);
        //Console.WriteLine(request.Parameters[0].DataFormat);
        Console.ReadKey(true);
```

In version 106.5.4 this creates
`application/json={"payload":{"username":"foo","password":"bar","clientToken":"123"}}`

In version 106.6.6 this changed to
`={ payload = { username = foo, password = bar, clientToken = 123 } }`
and `request.Parameters[0].DataFormat` becomes `Json`.

I wanted to label this as "help wanted", but could not find how to do so.
Thanks for any kind of clarification, if more information is needed, I will happily provide!

</details>

**Comment by alexeyzimarev** [comment]
It is mentioned in the readme. Parameters aren’t being rerialized until the request is executed.

**Comment by christianboese** [comment]
Thank you for the answer!
I found it now 

> In v106.6 body parameter is serialized just before executing the request. Delaying the serialization allowed us to add the client-level serializer.

That explains the changed behaviour :-)
