### ISSUE TITLE
XML preferred over JSON  causing deserialization to fail starting in version 106.6.2

### ISSUE THREAD

**Issue by nlaslett** [restsharp/RestSharp#1260]
## Expected Behavior
1. Unspecified GET requests and JSON POST requests return JSON by default.
Request Header:
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml

2. Deserialize to Type T when calling RestClient.Execute<T>(request) and return in response.Data

## Actual Behavior
1. Unspecified GET requests and JSON POST requests return XML by default.
Request Header:
Accept: application/xml, text/xml, application/json, text/json, text/x-json, text/javascript

2. response.Data is empty/null.

## Steps to Reproduce the Problem

  1. Upgrade RestSharp to 106.6.2+
  2. Create a new RestRequest. Can be GET or POST.
  3. Execute the request with RestClient.Execute\<T\>(request)
  4. Examine the headers
  5. Check the value of the Data collection of the response object

Prior to version 106.6.x, the default Accept header listed application/json first.  My endpoint (Salesforce API) returned JSON and RestSharp correctly deserialized the object to Type T.

With version 106.6.6, the default Accept header lists application/xml first.  My endpoint correctly returns XML but RestSharp is failing to deserialize the object.  Manually overriding the request "Accept" header causes the endpoint to return JSON and properly deserialize.

The XML response is correctly formatted.  The XML attributes might be handled differently (not sure) but the "Id" values of the "records" collection should deserialize the same.  (This is just one example of many.)

Given that all my existing code was built on the JSON return model, this is a breaking change.  Adding `request.AddHeader("Accept", "application/json")` to all requests is a challenge given the scope of the code base.

Given that XML has no place in my code and that JSON is the _de facto_ web standard for REST data exchange, why are we now having to manually, and without warning, override XML request headers?

## Specifications

  - Version: 106.6.x
  - Platform: .NET Framework 4.7.2
  - Subsystem:

## StackTrace
<details>

```
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: RestSharp/106.5.4.0

{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Account","url":"/services/data/v43.0/sobjects/Account/0014600001U0eQvXXX"},"Id":"0014600001U0eQvXXX"}]}


Accept: application/xml, text/xml, application/json, text/json, text/x-json, text/javascript
User-Agent: RestSharp/106.6.6.0

<?xml version="1.0" encoding="UTF-8"?><QueryResult><done>true</done><records type="Account" url="/services/data/v43.0/sobjects/Account/0014600001U0eQvXXX"><Id>0014600001U0eQvXXX</Id></records><totalSize>1</totalSize></QueryResult>


var request = new RestRequest()
{
	Resource = $"services/data/v42.0/query/",
	RootElement = "records"
};
request.AddQueryParameter("q", query);
var client = new RestClient(url);
var response = client.Execute<List<ReturnId>>(request);

class ReturnId
{
	public string Id { get; set; }
	public Attributes attributes { get; set; }
}

public class Attributes
{
	public string type { get; set; }
	public string url { get; set; }
}
```

</details>

**Comment by nlaslett** [comment]
**Update:** I was incorrect: manually adding the header does NOT fix the deserialization problem.  Even when returning proper JSON, the list does not deserialize.

**Comment by alexeyzimarev** [comment]
I thought we had xml preferred before? It is an easy fix, I will look into it soon. To be honest, I am not exactly happy with the amount of XML stuff we have in RestSharp at the moment, but I have no clear plan to address it and keep the library backwards compatible. Any suggestions are welcomed.

**Comment by alexeyzimarev** [comment]
Btw a quick fix for you would be to use RemoveHandler and remove the XML accept header, it is done one the client level.

**Comment by nlaslett** [comment]
Aside from the XML vs JSON issue, I'm still failing to deserialize the above.  Per the linked issue (#1258) did you by any chance remove or deprecate RestRequest.RootElement for JSON responses?  I know you've been making deep changes to serialization.

Other requests seem to deserialize ok, and this is the only one that specified a root element.  (But note that it's failing to deserialize both JSON and XML.)

**Comment by alexeyzimarev** [comment]
I actually wrote at that issue that the JSON serializer that supports `RootElement` gets it back, it was a bug. But it is hard to support the `RootElement` for custom serializers.

For the upcoming JSON default serializer based on JSON.Net, I can try using something like this: https://www.newtonsoft.com/json/help/html/SerializingJSONFragments.htm

**Comment by nlaslett** [comment]
Thanks for the quick turnaround.  I had to roll back to RestSharp 106.5.4 last night but will give 106.6.7 a try later today or tomorrow.

It sounds like support for `RootElement` may be dropped, however.  In that case I would want to stick with 106.5.4 indefinitely.  I hope you are able to keep that functionality in, even if it only works for the default serializer, for all the reasons mentioned in the JSON.Net "Deserializing Partial JSON Fragments" page.

It seems like the challenges are:
- Traversing multiple nodes down the tree
- Lists vs objects. The example returns a IList<> but what if the root is not an array but a single item?

I'll see if I can work something out to contribute.

**Comment by alexeyzimarev** [comment]
Well, if we can find a way to implement the `RootElement` with Json.net, we can keep it. 

I don't think that the current JSON deserializer is traversing the object tree, I think it only scans the first level.

At the same time, assigning a custom serializer on the client level is now quite easy and it would handle any possible scenario.

**Comment by KCRotary** [comment]
We have version 106.6.7.0 and still see that RootElement is obsolete.

 //
        // Summary:
        //     Used by the default deserializers to determine where to start deserializing from.
        //     Can be used to skip container or root elements that do not have corresponding
        //     deserialzation targets.
        [Obsolete("Add custom content handler instead. This property will be removed.")]
        public string RootElement { get; set; }

**Comment by mowcixo** [comment]
That's probably related with #1306

**Comment by baywet** [comment]
Encountered the same issue when upgrading from 106.3.0 to 106.6.9. Rolling back fixed this issue for now.

**Comment by alexeyzimarev** [comment]
I am not sure what's the status of this issue now.

I added support for external serializers now but none of them support the `RootElement` property.
