### ISSUE TITLE
After 106.6.2 AddUrlSegment dosn't work

### ISSUE THREAD

**Issue by TMily** [restsharp/RestSharp#1262]
After 106.6.2 when i call AddUrlSegment a new parameter was added but the placeholder was not removed

## Expected Behavior
```csharp
RestRequest Request =new RestRequest("/oauth/token?grant_type={grant_type}&username={username}&password={password}")
    { Method = Method.POST };  
Request.AddHeader("Content-Type", "application/x-www-form-urlencoded");  
Request.AddHeader("Authorization",  
    $"Basic {Convert.ToBase64String(Encoding.GetEncoding("ISO8859-1").GetBytes("token"))}");  
Request.AddUrlSegment("grant_type", "password");  
Request.AddUrlSegment("username", "un");  
Request.AddUrlSegment("password", "pd");  
```
I should get a request object with 5 parameters

{Content-Type=application/x-www-form-urlencoded}
{Authorization=~~~~~~~}
{grant_type=password}
{username=un}
{password=pd}

## Actual Behavior
But when the version is new than 106.5.4
I  get a request object with 8 parameters

{grant_type={grant_type}}
{username={username}}
{password={password}}
{Content-Type=application/x-www-form-urlencoded}
{Authorization=~~~~~~~}
{grant_type=password}
{username=un}
{password=pd}

## Steps to Reproduce the Problem

  1.Install RestSharp 106.6.2 or up.
  2.Create a Request object with placeholder and AddUrlSegment

## Specifications

  - Version: 106.6.2 vs 1.6.5.4
  - Platform: Windows 
  - Subsystem: UWP

**Comment by alexeyzimarev** [comment]
Thanks for reporting! I will check it now.

**Comment by alexeyzimarev** [comment]
Yeah, actually the previous behaviour was wrong and what you have now is correct.

When using `AddUrlSegment`, you don't need to put parameters to the resource string. Your code should be:

```csharp
var request = new RestRequest("/oauth/token");  
    AddHeader("Content-Type", "application/x-www-form-urlencoded")
    AddHeader("Authorization",  
    $"Basic {Convert.ToBase64String(Encoding.GetEncoding("ISO8859-1").GetBytes("token"))}")
    AddQueryParameter("grant_type", "password")
    AddQueryParameter("username", "un")
    AddQueryParameter("password", "pd"); 

var response = client.Post(request);
```

You definitely need to understand that query string parameters are _not_ URL segment parameters.

**Comment by nicholashead** [comment]
@alexeyzimarev perhaps the doc/example should be updated then (from homepage):

```cs
var client = new RestClient("http://example.com");
// client.Authenticator = new HttpBasicAuthenticator(username, password);

var request = new RestRequest("resource/{id}", Method.POST);
request.AddParameter("name", "value"); // adds to POST or URL querystring based on Method
request.AddUrlSegment("id", "123"); // replaces matching token in request.Resource
```

I got bit by this too. Was using AddUrlSegment with `{}` params in my RestRequest url, and they suddenly stopped working after upgrading to 106.6.2

**Comment by alexeyzimarev** [comment]
@nicholashead I am not exactly following your suggestion.

The sample is correct, the request resource is `resource/{id}` contains a URL segment parameter. We have a bunch of tests for this and they all pass.

The resource in the issue is `/oauth/token?grant_type={grant_type}&username={username}` and these parameters are **not** URL segment parameters. These are query parameters and we have a nice method to address that particular parameter type.

**Comment by nicholashead** [comment]
@alexeyzimarev Ahh. I see what you mean. That wasn’t apparent to me when looking at the example, and I mistakenly assumed I could use AddUrlSegment (and it worked at least until the newer RestSharp version). But I see how my syntax was wrong. Thanks!
