### ISSUE TITLE
Question: How to robustly detect a timed out async web request.

### ISSUE THREAD

**Issue by Korporal** [restsharp/RestSharp#1264]
@alexeyzimarev 

Hi, this is simply a question.

I can see that when I await an `async `request (e.g. `ExecuteGetTaskAsync`) a timeout is easily detected as the async operation completes and the response contains a `WebException `with a message `"The request timed-out.".`

My question is: is it safe to simply check the response for the presence of **this** exception and **that** message in order to conclude that the request timed out?

I'm just trying to ensure that there are not other code paths within `RestSharp `that might use a different exception or a different message. If anyone ever changed that message my code to detect timeout would fail.

Is this approach the same for other kinds of requests? for example if I were to `await ExecutePostTaskAsync` would that too use the same exception type and message? I can also see that the exception's `HResult` is set to **0x80131509** so is it also safe to check for that value too?

This way a timeout is deemed to have occurred if:

1. A `WebException `is present in the response object.
2. That exception has a message `"The request timed-out.".`
3. That exception has an HResult of **0x80131509**

are all true.

Incidentally why didn't `RestSharp `express the timeout with a `TimeoutException`?

Thanks!

PS: Here is an extension I put together:
```cs

    public static class RestSharpExtensions
    {
        public const string TIMEOUT_MESSAGE = "The request timed-out.";
        public const int TIMEOUT_HRESULT = unchecked ((int) 0x80131509);
        public static bool TimedOut (this IRestResponse Response)
        {
            if (Response.ErrorException != null)
                if (Response.ErrorException.Message == TIMEOUT_MESSAGE)
                    if (Response.ErrorException.HResult == TIMEOUT_HRESULT)
                       return true;

            return false;
        }
    }

```

**Comment by alexeyzimarev** [comment]
I think we have the response status to `Timeout`, is that not enough?

**Comment by Korporal** [comment]
> I think we set the response status to `Timeout`, is that not enough?

@alexeyzimarev - Not what I'm seeing:

![restsharptimeout](https://user-images.githubusercontent.com/12262952/51441185-2697ea00-1c8c-11e9-8c89-5da7c4a5adcf.jpg)

**Comment by alexeyzimarev** [comment]
👍 

`StatusCode` is what the server response (200, 404, etc) but if the request times out, there is nothing to set.
