### ISSUE TITLE
Parameter values containing an equal sign, are ignored.  Starting since 106.6

### ISSUE THREAD

**Issue by pieterh** [restsharp/RestSharp#1267]
## Expected Behavior
It looks as a similar problem as #1241, but is a bit different and not fixed... version 106.5.4 works, but since 106.6.2 - 106.6.7 there is a problem with missing the (last?) parameter.

## Actual Behavior
If the following url is used in a request:
api/data/v8.2/accounts?$select=accountid,name&$filter=name%20eq%20%27Microsoft%27&$expand=primarycontactid($select=contactid,firstname;)

The actual url is the following;
api/data/v8.2/accounts?$select=accountid,name$filter=name%20eq%20%27Microsoft%27

## Steps to Reproduce the Problem

  1. install package 106.6.7
  2. build a url that has three parameters
  3. execute the request

## Specifications

  - Version: 106.6.2 through 106.6.7
  - Platform: Windows & Azure
  - Subsystem:

## StackTrace
no exception

</details>

**Comment by alexeyzimarev** [comment]
Please add the code that configures the request.

**Comment by pieterh** [comment]
I am able to reproduce the error with the following snipped:

            var baseUri = _fixture.ConnectionInfo.ServiceUri; // ie http://localhost:8181/api/data/v8.2/
            var uri = "accounts?$select=accountid,name&$filter=name eq 'Microsoft'&$expand=primarycontactid($select=contactid,firstname;)";

            var restClient = new RestClient(baseUri);

            var request = new RestRequest(uri, Method.GET, DataFormat.Json);
            request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };
            var response = restClient.Get< ODataResponse < AccountEntity >> (request);
`

**Comment by pieterh** [comment]
I think I have found the cause of it. My last parameter in the url has an equal sign (=) in it. The logic parsing the url and captures the parameters doesn't take this into account. If the equal sign is escaped, the behavior is as expected.

The following line in RestRequest creates this behavior:
return pair.Length == 2 ? new NameValuePair(pair[0], pair[1]) : NameValuePair.Empty;

1) not sure if the = sign is allowed. However Dynamics 365 seems to support it in any parameter value ;-)
2) there is a temp workaround by encoding it with %3D
3) the fix would be something like
return pair.Length >= 2 ? new NameValuePair(pair[0], string.Join("=", pair.Skip(1))) : NameValuePair.Empty;

**Comment by alexeyzimarev** [comment]
According to the RFC https://tools.ietf.org/html/rfc3986#section-2.2, the equality sign is the reserved character and should be encoded. We can work around it by trying to split by & first and then find the first = only, but normally the equality sign should be encoded. Encoding happens automatically if you use `AddQueryParameter` instead of putting it to the request resource.

**Comment by pieterh** [comment]
Thank you for the quick response. I will check the rfc and likely start encoding to be compliant.

**Comment by pieterh** [comment]
okay, instead of creating the url our selves, we will use the AddQueryParameter and indicate that we need encoding. This seems to work fine. Issue can be closed.
