### ISSUE TITLE
Parameter nested inside a curly braces are no longer correctly replaced

### ISSUE THREAD

**Issue by NPadrutt** [restsharp/RestSharp#1268]
## Expected Behavior
I have the following URL Segment:
"domains/{domain}/projects/{project}/test-sets?query={id[{test-set-id}]}"

when the parameters are in place it should be: 

"domains/MyDomain/projects/MyProject/test-sets?query={id[123]}"

## Actual Behavior
"domains/MyDomain/projects/MyProject/test-sets?query={id[{test-set-id}]}"

## Code to Reproduce the Problem

```
        private const string PARAMETER_ID = "id";
        private const string PARAMETER_DOMAIN = "domain";
        private const string PARAMETER_PROJECT = "project";
        private const string PARAMETER_TEST_SET_ID = "test-set-id";


           // Code to set the parameter and make the request.
           var request = new RestRequest(URL_TEST_SETS_BY_ID);

           request.AddParameter(PARAMETER_DOMAIN, "MyDomain", ParameterType.UrlSegment);
           request.AddParameter(PARAMETER_PROJECT, "MyProject", ParameterType.UrlSegment);
           request.AddParameter(PARAMETER_TEST_SET_ID, 123, ParameterType.UrlSegment);

           var response = await Task.Run(() => client.Execute(request)).ConfigureAwait(false);
```

## Specifications

  - Version: 106.6.7 (it starts with version 106.6.2 and worked till 106.5.4)
  - Platform: Windows 10 1803, .net framework 4.6.2

**Comment by alexeyzimarev** [comment]
`test-set-id` is the query parameter but you are adding it as a URL segment and that is wrong.

The request resource should by `domains/{domain}/projects/{project}/test-sets` and you need to add a query parameter with the name `query` and the full value of the parameter.

**Comment by NPadrutt** [comment]
Thanks for your fast response. As far as I understand the documentation, I can't accomplish a format like "query={id[123]}" with the query string parameter or did I overlook something?  I guess I then have to build the query part manually, since I have no controll over the server side.

**Comment by NPadrutt** [comment]
Ah, great. Thanks for your help! :)
