### ISSUE TITLE
Nullable TimeSpan that has value - always null

### ISSUE THREAD

**Issue by LeoJHarris** [restsharp/RestSharp#1269]
Hi there, 

I have a complex object which includes a nullable TimeSpan object. When the nullable TimeSpan has value and is being sent in the rest request the value is always null on the other side in my action method. Should I expect to be able to be able send a TimeSpan object without any issues? When I  call the ToString on the TimeSpan and update property as a string I have no issues. Ideally I would like to send as a nullable TimeSpan.

I am using RestSharp in a Xamarin.Forms project .NetStandard 2.0

**Comment by alexeyzimarev** [comment]
Code?

**Comment by LeoJHarris** [comment]
The client side is doing this:

```csharp
private async Task<IRestResponse> executeRestRequestAsync<T>(
            string baseUrl,
           string apiEndpoint,
           Method methodType,
           Dictionary<string, string> parameterDictionary,
           Dictionary<string, string> headerDictionary,
           T content)
        {
            RestClient.BaseUrl = new Uri(baseUrl);

            RestRequest restRequest = new RestRequest(apiEndpoint, methodType);
            restRequest.AddHeader("Accept", "application/json");

            foreach (KeyValuePair<string, string> keyValuePair in headerDictionary)
            {
                restRequest.AddHeader(keyValuePair.Key, keyValuePair.Value);
            }

            foreach (KeyValuePair<string, string> keyValuePair in parameterDictionary)
            {
                restRequest.AddParameter(keyValuePair.Key, keyValuePair.Value);
            }

            if (!EqualityComparer<T>.Default.Equals(content, default(T)))
            {
                restRequest.AddJsonBody(content);
            }

            IRestResponse result = await RestClient.ExecuteTaskAsync(restRequest).ConfigureAwait(false);

            return result;
        }
```

See the request made:

![request](https://user-images.githubusercontent.com/5468757/52006152-58346f00-2530-11e9-9377-fd033b039697.PNG)

And on the server side with the request made from client (see TimeSpan is null):

![captured](https://user-images.githubusercontent.com/5468757/52006296-ab0e2680-2530-11e9-9566-1e8d6447ba32.PNG)

**Comment by LeoJHarris** [comment]
As a side note its all causing my Status enumeration to become the default value. Having also removed the TimeSpan previously the request was fine..

**Comment by LeoJHarris** [comment]
@alexeyzimarev Can I please get some follow up on this issue facing, does there appear to be any issue in the code?

**Comment by alexeyzimarev** [comment]
I would just use Json.net serialiser.

**Comment by LeoJHarris** [comment]
Fixed:

```csharp 
private object serialize<T>(T item)
        {
            return JsonConvert.SerializeObject(item);
        }
```

And

```csharp 
private object serialize<T>(T item)
        {
            restRequest.AddParameter("application/json", serialize(content), ParameterType.RequestBody);
        }
```
