### ISSUE TITLE
send object in request parameter

### ISSUE THREAD

**Issue by abdolrhman** [restsharp/RestSharp#1270]
am consuming an api in which it requires me to send complex object in the url ,
how can i do this in restsharp ?
this is an example of the api i want to consume ,

> http://url/apis/addstd/{"apiusername":"aaaaa","apipassword":aaaaaa","student_code":"asdhrthsefgserg","username":"studenttest","password":"Admin@123","firstname":"studenttestfname","lastname":"studenttestlname","email":"studenttest@studenttest.com"}

also i want to make some keys and values in the object as a variable in which its different from api to api,
any help is much appreciated, thk in advance.

**Comment by alexeyzimarev** [comment]
Please follow our contribution guidelines and don’t use issues to ask questions. The best palace for questions as StackOverflow.

**Comment by abdolrhman** [comment]
@alexeyzimarev  my account is banned at stackoverflow :(
