### ISSUE TITLE
Add mention of default timeout value to XML documentation

### ISSUE THREAD

**Issue by Korporal** [restsharp/RestSharp#1271]
## Expected Behavior
Intellisense XML for RestRequest.Timeout should include what the actual defaulted value is, that is how many seconds exactly is the underlying default.

## Actual Behavior

```
        //
        // Summary:
        //     Timeout in milliseconds to be used for the request. This timeout value overrides
        //     a timeout set on the RestClient.

```
## Steps to Reproduce the Problem

  1. Right click (in VS) the RestRequest class name.
  2. Select "Go to defintion"

## Specifications

  - Version: 106.6.5.0
  - Platform: Windows
  - Subsystem:

## StackTrace
N/A

</details>

**Comment by alexeyzimarev** [comment]
We do not assign the default timeout. We use the default timeout of the `HttpWebRequest`. In the MS docos they say it's 10 sec.
