### ISSUE TITLE
Can't return an Arabic result [Get]

### ISSUE THREAD

**Issue by sulaimanO** [restsharp/RestSharp#1274]
## Expected Behavior
Can return arabic result

## Actual Behavior
Not returning Arabic result

## Code
var client = new RestClient("https://raw.githubusercontent.com/sulaimanO/JsonInArabic/master/Banks.json");
            var request = new RestRequest();
            request.AddHeader("Accept", "application/json");
            request.Parameters.Clear();
            var response = client.Get(request);
            var content = response.Content;

it returns 

{
            "name": "?????? ????? ???????"
}

thanks *hart*

**Comment by sinankeskin** [comment]
Where do you see all those question marks? In Console perhaps? Console doesn't support unicodes very well but try to set `Console.OutputEncoding = Encoding.UTF8;`

I tried in debug mode and I was able to see all Arabic letters in debug console.
