### ISSUE TITLE
Are all properties required?

### ISSUE THREAD

**Issue by kellyelton** [restsharp/RestSharp#1276]
If I'm deserializing the following

```
<MyElement>
    <Name>Element Name</Name>
    <Active>false</Active>
</MyElement>
```

into

```
public class MyElement {
    public string Name { get; set; }
}
```

Will it work, even though I don't have a property for `Active` ?

I can't find any information on this in the wiki.

**Comment by alexeyzimarev** [comment]
Please don't use GitHub issues for questions. We **clearly** mentioned this in the guidelines.

**Comment by kellyelton** [comment]
@alexeyzimarev The issue is that the documentation doesn't clearly explain this. This is an actionable item.

**Comment by alexeyzimarev** [comment]
Can you point me to the line in the, for example, `XmlSerializer` [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer?view=netframework-4.7.2) where such a thing is explicitly mentioned? So we can align the docos better.

**Comment by kellyelton** [comment]
Maybe there's a misunderstanding. I feel like what I'm asking is a very common use case.

The documentation always maps classes 100% to the REST API.

For example in the Serialization page:

```
<Person>
    <Name>John</Name>
    <Id>28</Id>
</Person>
```

Gets mapped to:

```
public class Person {
    public string Name { get; set; }
    public int Id { get; set; }
}
```

It's not clear in the documentation if the following class would also work:

```
public class Person {
    public string Name { get; set; }
}
```

If that's not the case, doing something simple like adding an additional property to the API result that you don't reflect in the class would clearly show you don't need to map the class to the API result 100%:

```
<Person>
    <Name>John</Name>
    <Id>28</Id>
    <Hometown>My Town</Hometown>
</Person>

public class Person {
    public string Name { get; set; }
    public int Id { get; set; }
}
```

**Comment by alexeyzimarev** [comment]
I asked a very simple question - why do you think that particular question must be a part of the docs and I pointed to the Microsoft docs that can be used as the “example’ of all docs, where nothing like this is mentioned for the `XmlSerializer`. There are a lot of different cases for serialisation - how lists work, how complex types work and so on. You might not realise it but we spent more time discussing this “issue” than it would take to write two lines of code to try out that use case in a console app, which is about three minutes work.

**Comment by kellyelton** [comment]
You've been very abrasive every step of the way. Maybe interacting with users on an open source platform isn't something you're very good at.

I ended up just using XmlSerializer and HttpClient in my project because it worked as expected.

**Comment by alexeyzimarev** [comment]
Thank you very much for your feedback. I tried to understand the nature of your question. We carefully prepared the contribution guidelines for Github issues, but you recided to ignore it, so it wasn’t clear if you’re reporting a bug or you think some documentation is missing.

Again, thank you for pointing out to my communication style.

I, in response, can point you to the `DotNetXmlSerializer` that uses exactly the same serialiser that you decided to use at the end. It is properly documented in our Wiki.
