### ISSUE TITLE
Auto Cookie management stumbling on cookies with a comma in value

### ISSUE THREAD

**Issue by Xodaru** [restsharp/RestSharp#1281]
RestSharp does not seem like cookie values that have comma's in them (both via cookiecontainer and manually set via request.AddCookie)
There is some mention in other issues about escaping the value, however in my situation this makes the expected value invalid.

For example I have a cookie value "tm-Pickup,f-4258"
If i escape it: Message=Requested value 'Pickup%2Cf-4258' was not found.

The cookie is set by a third party I have no control over. At a bit of a loss how I can make this work unfortunately.

**Comment by alexeyzimarev** [comment]
I don’t think it is something that RestShart doesn’t like since we send cookies as is to the HttpWebRequest

**Comment by Xodaru** [comment]
Looking into this more and yep your right, not a restsharp issue. 

I don't think there is any way around this either?

**Comment by alexeyzimarev** [comment]
If there's anything we can tell to HttpWebRequest to make it work - we can do it, but, unfortunately, no more.

**Comment by Xodaru** [comment]
Seems this 'issue' has existed with HttpWebRequest for well over 10 years now so i don't think there is any solution or workaround.
I can work around it for now but I'd be interested if anyone ever has a solution for this in the future.
