### ISSUE TITLE
Why my body is incorrect?

### ISSUE THREAD

**Issue by bartosz-macczak** [restsharp/RestSharp#1283]
Curl:
 `-d 'client_id={client_id}'
`

My c# code:
```
Body body = new Body()
            {
                client_id = "20...8351"
            };
string json = JsonConvert.SerializeObject(body, Formatting.Indented);
request.RequestFormat = DataFormat.Json;
MessageBox.Show(json);
request.AddJsonBody(json);
```

In response I get communicate that client_id doesn't match to my account. I am 100% sure that it's correct, because in online curl tester it works good. I think that it's problem with json variable format. Have you any suggestions?

**Comment by alexeyzimarev** [comment]
Please read the docs. You need to use the `Body` object as a parameter for `AddJsonBody`, not the serialized string.
