### ISSUE TITLE
Default value for 404

### ISSUE THREAD

**Issue by riezebosch** [restsharp/RestSharp#1284]
## Expected Behavior
`null` for complex objects and default for simple types.

## Actual Behavior
Instance with all `null` fields

## Steps to Reproduce the Problem

```
[Fact]
public void NotFoundIsNull()
{
    var client = new RestClient();    
    client.BaseUrl = new Uri("https://reqres.in/");
    client.Execute<Data<Person>>(new RestRequest("/api/users/23")).Data.ShouldBeNull();
}
  
public class Data<TData>
{
    public TData data { get; set; }
}

public class Person
{
    public int id { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    public string avatar { get; set; }
}
```

Currently the data is an empty object on deserialization which makes it hard to distinguish from a succesfull get.

**Comment by alexeyzimarev** [comment]
You do get the status code and `IsSuccessful`, isn't that enough?

**Comment by riezebosch** [comment]
I created this workaround:
```c#
        public static T DefaultIfNotFound<T>(this IRestResponse<T> response)
        {
            return response.StatusCode == HttpStatusCode.NotFound ? default(T) : response.Data;
        }
```

And in another exension method I check for `if (!response.IsSuccessful && response.StatusCode != HttpStatusCode.NotFound)` to throw an exception. Now I have to double check for `NotFound` because I want to treat that as `default` and not as unsuccesful.

**Comment by alexeyzimarev** [comment]
I think it is an overall issue that we got the failures wrong in the first place and now if I get it fixed, a lot of people will start to complain because it will break their code. Catch 22... Not sure how to solve this issue, open for suggestions.

**Comment by alexeyzimarev** [comment]
@riezebosch are you doing JSON requests, right? Sync or async?

**Comment by riezebosch** [comment]
Sync.
<small>But in the meantime, I replaced restsharp altogether. I'm sorry</small>
