### ISSUE TITLE
Can't resolve dependency 'Microsoft.SourceLink.GitHub'

### ISSUE THREAD

**Issue by MichaelSafro** [restsharp/RestSharp#1285]
## Expected Behavior
Nuget installs package

## Actual Behavior
Produces error: Says it can't resolve dependency - 'Microsoft.SourceLink.GitHub'

## Steps to Reproduce the Problem

  1. Run nuget install RestSharp -Version "106.6.8"
  2. To compare run the same command with different version 

## Specifications

  - Version: 106.6.8
  - Platform: Windows 
  - Subsystem: 10, Server 2008

## StackTrace
<details>
Attempting to gather dependency information for package 'RestSharp.106.6.8' with respect to project 'C:\XXX', targeting 'Any,Version=v0.0'
Gathering dependency information took 1.49 sec
Attempting to resolve dependencies for package 'RestSharp.106.6.8' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'Microsoft.SourceLink.GitHub'. Source(s) used: 'nuget.org' 
</details>

**Comment by alexeyzimarev** [comment]
Resolved by #1282
