### ISSUE TITLE
How to replace username and password in URL

### ISSUE THREAD

**Issue by eecklund** [restsharp/RestSharp#1287]
## Expected Behavior
I'm trying to replace the username and password that is required to be in the URL.  Since the password contains special character, I figure I would have to escape them.  I can't seem to figure out how to replace the segments.

## Actual Behavior
AddUrlSegment does not replace segements

## Steps to Reproduce the Problem

`var client = new RestClient();

var request = new RestRequest("https://{username}:{password}@demo.test.com/api/verify", Method.POST);

request.AddUrlSegment("username", "123");

request.AddUrlSegment("password", "456");`

## Specifications

  - Version: 106.6.9

**Comment by alexeyzimarev** [comment]
This is not a query, not a resource, this is the basic authentication.
https://en.wikipedia.org/wiki/Basic_access_authentication

Use https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/HttpBasicAuthenticator.cs
