### ISSUE TITLE
Allow to explicitly set the content-type header.

### ISSUE THREAD

**Issue by Mathieu-Beliveau** [restsharp/RestSharp#1290]
## Expected Behavior

The user should be able to easily specify the content type without resorting to hacks. 
Right now, it seems it is not possible to set the content type for something like messagepack or anything else than the small set supported. The mechanism to specify the content-types should allow for future, unexpected content-types.

## Actual Behavior

The library seems to implicitly set the content type to one of the few supported content types.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
I am not sure what is the issue there. Content types don't appear out of the thin air. Content types are _always_ associated with the way how requests and responses are serialised. We support _any_ content type by adding a custom handler or serialiser, which is the correct way of doing it. Otherwise, how would you expect the code to detect what kind of (de)serialisation method can be used for an arbitrary content type?

**Comment by Mathieu-Beliveau** [comment]
“We support any content type by adding a custom handler or serialiser”

 

Can you point out the documentation to see how this is done?

I thought the library did not allow to add custom serialisr and that it was limited to use the built-in ones.

 

Thanks!

 


Mathieu Béliveau 
Développeur Meta
Meta Developer

 <https://apnglobal.ca/> 

2659, boul. du Parc-Technologique 
Québec, (Québec) G1P 4S5 CANADA
Tél. : 418-266-1247, poste # 230 
 <http://www.apnca.com> apnca.com
 <https://apnglobal.ca/> 

 

De : Alexey Zimarev [mailto:notifications@github.com] 
Envoyé : March 14, 2019 1:43 PM
À : restsharp/RestSharp <RestSharp@noreply.github.com>
Cc : Mathieu-Beliveau <mathieu.beliveau.1@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [restsharp/RestSharp] Allow to explicitly set the content-type header. (#1290)

 

I am not sure what is the issue there. Content types don't appear out of the thin air. Content types are always associated with the way how requests and responses are serialised. We support any content type by adding a custom handler or serialiser, which is the correct way of doing it. Otherwise, how would you expect the code to detect what kind of (de)serialisation method can be used for an arbitrary content type?

**Comment by alexeyzimarev** [comment]
Wiki: https://github.com/restsharp/RestSharp/wiki/Serialization#note-on-serialization
describes the new `UseSerializer` method on the client.

You can also use `AddHandler` for deserialization of responses.

**Comment by Mathieu-Beliveau** [comment]
Hi! 

 

Thanks for the info regarding the custom implementation of deserializers and serializer.

 

Unfortunately, UseSerializer takes an object that implements IRestSerializer which requires the serialization methods to return a string. In the case of messagepack, a byte array should be return, so I cannot use this.

My intuition for RestSharp was that it was a wrapper to simplify calls to Httpclient in most rest scenarios. In this case, it does everything I want except… I cannot set the content-type to msgpack and the server will just not answer properly in that case.

 

What would be the best way forward in your opinion? 

 


Mathieu Béliveau 
Développeur Meta
Meta Developer

 <https://apnglobal.ca/> 

2659, boul. du Parc-Technologique 
Québec, (Québec) G1P 4S5 CANADA
Tél. : 418-266-1247, poste # 230 
 <http://www.apnca.com> apnca.com
 <https://apnglobal.ca/> 

 

De : Alexey Zimarev [mailto:notifications@github.com] 
Envoyé : March 14, 2019 4:29 PM
À : restsharp/RestSharp <RestSharp@noreply.github.com>
Cc : Mathieu-Beliveau <mathieu.beliveau.1@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [restsharp/RestSharp] Allow to explicitly set the content-type header. (#1290)

 

Wiki: https://github.com/restsharp/RestSharp/wiki/Serialization#note-on-serialization
describes the new UseSerializer method on the client.

You can also use AddHandler for deserialization of responses.

**Comment by Herve-M** [comment]
I join Mathieu Béliveau on this issue, they are many non documented _unknow_ about custom de/serializer.

`DataFormat` is a non extensible enum and some code rely on it, `DataFormat.None` seem fine but I think that a `DataFormat.Custom` with internal check would be better. 

`ISerializer`, `IDeserializer`, `IRestSerializer` are in the main nuget, would be nice to have an `RestSharp.Abstractions` package/nuget to simplify deployment of custom serializer. 

`IRestClient.UseSerializer` is marked as Obsolete

`IRequest` has `AddJsonBody` && `AddXmlBody` but nothing as `AddCustomBody`

Herve-M

**Comment by alexeyzimarev** [comment]
Well, I can add a couple of things here

If we want to be more flexible on making the request body from the body parameter, we need to get away from using string as the request body. I think it is feasible, we can perfectly stream to the request body.

Regarding ReatSharp serialisation interfaces, I don’t know if using Abstractions package is something I would like. Any custom serialisation library for RestSharp will only be used for RestSharp. So if we get a RestSharp.Utf8Json and it references RestSharp, you get the correct version of RestSharp installed with it.

Another option would be to get rid of those interfaces and use functions instead. Personally I would prefer that.

**Comment by Herve-M** [comment]
Interface are a good way to do, at my view/cent. 
Any guide / thinking about this task? Maybe I could make a PR :-) 

Goal would be to `Request` having a `byte[]` as data holder and serializer working arround it. Saddly it will be possibly break the API..

**Comment by alexeyzimarev** [comment]
I looked closer to the code and I don't really see an issue there if you just want to _send_ a MessagePack payload.

Seems like all you need to do is to use
```
request.AddParameter(new Parameter("", byteArray, "application/x-msgpack", ParameterType.RequestBody));
```

By default, the data type for all parameters is `None` and in that case, if the value is a byte array, we just copy it as-is to the request stream.

**Comment by alexeyzimarev** [comment]
@Mathieu-Beliveau I don't think that your statement is correct
> The library seems to implicitly set the content type to one of the few supported content types.

We only do that for payload types that we support. It is more like a convenience feature.

RestSharp has no issues, as far as I can see, to add a request body parameter with an arbitrary content type, which will be sent as-is and no serialization will take place in that case.
