### ISSUE TITLE
NETSTANDARD2_0 not defined after 106.4.0

### ISSUE THREAD

**Issue by mattyellen** [restsharp/RestSharp#1294]
`RestSharp.Http.ConfigureWebRequest()` contains conditional compilation for `NETSTANDARD2_0`:
https://github.com/restsharp/RestSharp/blob/master/RestSharp/Http.Sync.cs#L202

When get version 106.4.0 from NuGet and decompile it:
```
// Decompiled with JetBrains decompiler
// Type: RestSharp.Http
// Assembly: RestSharp, Version=106.4.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75
// MVID: 73B2AA7A-7911-49D1-A31F-BBC4E3426998
// Assembly location: /Users/mattyellen/.nuget/packages/restsharp/106.4.0/lib/netstandard2.0/RestSharp.dll
```
it appears to be correct:
```
      webRequest.UnsafeAuthenticatedConnectionSharing = this.UnsafeAuthenticatedConnectionSharing;
      webRequest.Proxy = (IWebProxy) null;
      webRequest.ServicePoint.Expect100Continue = false;
```

However when I get version 106.4.1:
```
// Decompiled with JetBrains decompiler
// Type: RestSharp.Http
// Assembly: RestSharp, Version=106.4.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75
// MVID: E278AA8E-A40F-4A14-89AD-E72A0F5DAC43
// Assembly location: /Users/mattyellen/.nuget/packages/restsharp/106.4.1/lib/netstandard2.0/RestSharp.dll
```
the line is missing:
```
      webRequest.UnsafeAuthenticatedConnectionSharing = this.UnsafeAuthenticatedConnectionSharing;
      webRequest.ServicePoint.Expect100Continue = false;
```

I also checked several other version after 106.4.1 including 106.4.2, 106.5.0, 106.6.7, and 106.6.9

**Comment by alexeyzimarev** [comment]
Hmm, that is something weird. The dotnet should set it correctly. I will check.

**Comment by jnyrup** [comment]
I tried to dig in this:
https://github.com/restsharp/RestSharp/commit/02e51bc94954b135410e88f32109e7ac96d15dda
`/p:DefineConstants=APPVEYOR` *doesn't* add `APPVEYOR` as an extra constant, it sets it as the *only* constant.

I don't know a pretty way to define this, but here's an example of how this could be achieved:
https://stackoverflow.com/a/5053070/1087627
