### ISSUE TITLE
Remove default constructor requirement from T on Execute method

### ISSUE THREAD

**Issue by horato** [restsharp/RestSharp#1296]
Hello,
It seems that the new() constraint on Execute methods was added back in. Is there any reason for this? Could this be removed again? 
Every detail on this feature request was already discussed in #584.

Thank you

**Comment by alexeyzimarev** [comment]
Hmm, strange. I don't remember adding it back. Will check.

**Comment by dahovey** [comment]
Are there any updates on this? Using version 106.6.10 and RestClient requires `new()` constructor still.
