### ISSUE TITLE
Feature proposal for Caching HTTP responses (if enabled)

### ISSUE THREAD

**Issue by egbertn** [restsharp/RestSharp#1297]
Hi Alex and other RestClient dudes

I have built a feature by inheriting RestClient which enables RestClient to utilize HTTP Response headers that enable caching using Expires, ETAG Cache hints etc.

THis greatly optimizes performance and costs. I can built it into RestClient if you wish.
The source code is online, here.
It utilizes Microsofts MemoryCache extension, which is very much like Redis, but then in memory. It could be configured using options (such as expiring items and compacting memory on .NET Standard 2.0)

https://github.com/egbertn/RestApi/blob/master/src/ADC.RestApiTools/SmarterRestClient.cs

Let me know.

**Comment by alexeyzimarev** [comment]
RestSharp currently has zero dependencies and I am not feeling comfortable taking any dependency, including those from Microsoft. I might suggest creating a `RestSharp.Contrib` repository and organize it so it gets built and published, but outside of the core repo.

**Comment by egbertn** [comment]
I see. I could create a fork. But on .NET Core, and when you deploy on non-windows, the whole framework is included anyway😊 but you’re the boss.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by alexeyzimarev** [comment]
It's less about the size but more about package versions and so on. Plus, when building native binaries or self-contained apps, it doesn't include the full framework. Also, when building Docker images, only the necessary libraries get published.

My point wasn't to create a fork but to create a separate package. I am doing that now, for example, for Newtonsoft.Json serialzier.
