### ISSUE TITLE
NullReferenceException for body parameters that don't have a name

### ISSUE THREAD

**Issue by stodolos** [restsharp/RestSharp#1300]
## Expected Behavior
I would not have to add a name, or the error message would be clearer that a parameter name was missing.

## Actual Behavior
A NullReferenceException is thrown.

## Steps to Reproduce the Problem

  1. Add a request body parameter without a name

This must be the issue in RestClient.ConfigureHttp (it's assuming the name is there):

```
var parameterExists =
                    request.Parameters.Any(p =>
                        p.Name.Equals(defaultParameter.Name, StringComparison.InvariantCultureIgnoreCase)
                        && p.Type == defaultParameter.Type);
```

## Specifications

  - Version: 106.6.9.0
  - Platform: .NET Framework
  - Subsystem:

## StackTrace
<details>
System.NullReferenceException: Object reference not set to an instance of an object.
   at RestSharp.RestClient.<>c__DisplayClass172_0.<ConfigureHttp>b__8(Parameter p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at RestSharp.RestClient.ConfigureHttp(IRestRequest request)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, String httpMethod, Func`4 getWebRequest)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, Method httpMethod)
</details>

**Comment by alexeyzimarev** [comment]
@vbenedichuk any reason why you don't want to submit a PR?

**Comment by alexeyzimarev** [comment]
Closed in the next release. Breaking change!

**Comment by mitcht** [comment]
I was attempting to debug / fix a problem but found that your change introduced a bug.  See line https://github.com/restsharp/RestSharp/blob/a8a9f3473be30317fc449c1c47e3f3cd74e8bab4/RestSharp/RestRequest.cs#L335

You'll see that the line is 
AddParameter(new JsonParameter("", obj));

Not sure how you'd like to go about handling this, but i'll not submit a pull request for something changed so recently.  Thanks!

**Comment by alexeyzimarev** [comment]
Seems like we are missing some tests. Indeed body parameters don't need a name. I think a better fix would only check if the name is not empty for parameters that aren't of type body.

**Comment by mitcht** [comment]
I updated the pull request to reflect your idea.

**Comment by mitcht** [comment]
I only caught this issue because I was trying to understand RestSharp better. It doesn't seem to be an issue in the nuget package at this time.

**Comment by alexeyzimarev** [comment]
Yeah, the new version isn't published yet. I made some more changes in preparation to move to better async handling and also to address some of the issues with exceptions handling

**Comment by MKI-Miro** [comment]
when it will be fixed?

**Comment by MKI-Miro** [comment]
I can see tha there is version 106.7.0 but my visual studio shows only 106.6.10 why?

**Comment by alexeyzimarev** [comment]
Fixed in 106.9

**Comment by ronaldfeb** [comment]
This remains a problem in the latest build Alexey

**Comment by alexeyzimarev** [comment]
@ronaldfeb I merged the PR that claimed to fix this issue, could you please post your code?

**Comment by ronaldfeb** [comment]
@alexeyzimarev i just have a simple post function that takes in a JSON object as the body. The name parameter for the body is null.
 public async Task<Result> postAsync(object objectToUpdate, string apiEndPoint)
        {
            Result result = new Result();


            try
            {
                var client = new RestClient(apiEndPoint);

                var request = new RestRequest(apiEndPoint, Method.POST);
                request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };
                request.RequestFormat = DataFormat.Json;
                request.AddJsonBody(objectToUpdate);
                var response = await client.ExecuteTaskAsync(request);
                //var response = client.ExecuteDynamic(request);


                if (response.StatusCode != HttpStatusCode.Created)
                {

                    Console.WriteLine("Access Token cannot obtain, process terminate");
                    result.Success = false;
                    result.Message = response.ErrorMessage;
                    return result;
                 
                }
              
                result.Success = true;
                result.Message = "OK";
                return result;

            }
            catch
            {
                throw;
            }

            // await Audit(_settings, new AuditEntry() { Action = EnumTypes.Actions.Add.ToString(), Area = "Testcase", AuditId = obj.key, DatetimeStamp = DateTime.Now, ClientId = userId, NewValue = obj, OldValue = null });
            

        }

The json body:
{
  "smartloadId": "string",
  "clientReference": "string",
  "smsRecipientMsisdn": "string",
  "deviceId": "string",
  "productId": 0,
  "amount": 0,
  "pinless": true,
  "sendSms": true,
  "orderRefID": 0
}

**Comment by alexeyzimarev** [comment]
Could you paste the exception details, including the stack trace?

**Comment by windstormtm** [comment]
System.ArgumentNullException
  HResult=0x80004003
  Сообщение = Value cannot be null.
Arg_ParamName_Name
  Источник = System.Private.CoreLib
  Трассировка стека:
   at System.Text.EncodingTable.GetCodePageFromName(String name)

**Comment by namilkimfree** [comment]
MemberSignUp signup = new MemberSignUp()
            {
                Email = "TEST",
                NickName = "TEST",
            };
 RestRequest req = new RestRequest("/my/resource", Method.POST);
            
            req.AlwaysMultipartFormData = true;
            req.AddHeader("content-Type", "multipart/form-data");
            req.AddJsonBody(signup);

but -> req.Parameters[1].Name = is empty.
![image](https://user-images.githubusercontent.com/44854923/74148805-a4d57e80-4c49-11ea-8253-00fe8e60eccd.png)

**Comment by veliev** [comment]
I have a similar error
Code
```
string url = "http://????????????????????????????/reports/new/Report2_11_1?page=reports/new/Report2_11_1&rep_nd=04.03.2020&rep_nd_h=18&rep_nd_min=00&rep_kd=05.03.2020&rep_kd_h=18&rep_kd_min=00&&rep_nd_fact_time=&rep_nd_h_fact_time=00&rep_nd_min_fact_time=00&rep_kd_fact_time=&rep_kd_h_fact_time=00&rep_kd_min_fact_time=00&train_registration=1&kind_rep_type=1,2&four_report_save=4,5&usw=1007&ush=1108";
CookieContainer container = new CookieContainer();
RestClient client = new RestClient();
client.CookieContainer = container;

RestRequest request = new RestRequest(url, Method.GET);
```
Error
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'name')
   at RestSharp.RestRequest..ctor(String resource, Method method, DataFormat dataFormat)
   at RestSharp.RestRequest..ctor(String resource, Method method)
```

I tried on different versions: 106.10.1, 106.10.0б, 106.9.0

**Comment by alexeyzimarev** [comment]
@veliev it is a different issue, please open a separate one

**Comment by alexeyzimarev** [comment]
Ok, the issue of the request body parameter requiring to have a name is _fixed_. If there any other problems with the parameter name being null, please open a separate issue.

**Comment by bsalmeida** [comment]
How did you add a breaking change (remove the parameterless constructor of Parameter class) without changing the major version?
I've tried to update from 106.2.1 to the latest version, assuming that if it has the same major (106) without breaking changes but NOT!

**Comment by alexeyzimarev** [comment]
@bsalmeida like that. Ideally, the parameter class should be internal. We cannot accept parameters that aren't configured correctly since it creates more issues that people post here.
