### ISSUE TITLE
Updating Authenticators

### ISSUE THREAD

**Issue by mattosaurus** [restsharp/RestSharp#1304]
## Expected Behavior
Authenticators should update request parameter value if name already exists.

## Actual Behavior
Authenticate method checks for name and only adds parameter if it doesn't exist.

## Steps to Reproduce the Problem

  1. Add a new client with a JwtAuthenticator with an expired token.
  2. Execute request and receive expired 401 error.
  3. Fetch new token and set client authenticator to be new JwtAuthenticator with valid token.
  4. Execute request again with updated client.

I'm trying to implement an execute method using the JwtAuthenticator that will acquire a new token if the current one is expired and then try to send the request again. However this new token isn't being set in the request parameters as a parameter with the name Authorization already exists.

I think the expected behavior should be that if a new authenticator is added then it will update the existing parameter rather than doing nothing.

This should hopefully just be a case of using the AddOrUpdateParameter method rather than the AddParameter method in the authenticators.

`request.AddParameter("Authorization", authHeader, ParameterType.HttpHeader);`

to

`request.AddOrUpdateParameter("Authorization", authHeader, ParameterType.HttpHeader);`

I'm happy to submit a PR with these changes if you agree with this.

Thanks

**Comment by alexeyzimarev** [comment]
Ok, I made some changes to your code. I want to keep the behaviour as it was but give the possibility to address the issue with supplying a new token.

Now, there're two ways to update the token.

1. Use the new constructor: `new JwtAuthenticator(token, true)`, where the second parameter tells the client to update the header parameter. If the second parameter is `false` or not supplied (which is the default), it will work as before.

1. Keep the authenticator reference in a variable and call `authenticator.SetBearerToken(token)`, which will also force the header update.
