### ISSUE TITLE
Feature Request - FIPS-compliant

### ISSUE THREAD

**Issue by ericjameszimmerman** [restsharp/RestSharp#1308]
## Request
Replace SHA1Managed (not fips-compliant) with SHA1Cng (fips-compliant)

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha1cng?redirectedfrom=MSDN&view=netframework-4.5.2

They appear to create the same resultant hash

**Comment by alexeyzimarev** [comment]
I don't think it's possible. Microsoft has removed the SHA1Cng from .NET Standard and it seems not to be supported in .NET Core.

**Comment by alexeyzimarev** [comment]
https://github.com/dotnet/standard/issues/269

https://docs.particular.net/nservicebus/compliance/fips

> FIPS policy enforcement does not exist at all in .NET Core.

If you are on .NET Framework and you need to enable FIPS, the best way would be to create a custom implementation of `IAuthenticator` by copying the code of `OAuth1Authenticator` and changing the code where necessary.
