### ISSUE TITLE
How to post raw bytes?

### ISSUE THREAD

**Issue by nikoudel** [restsharp/RestSharp#1309]
The [documentation](https://github.com/restsharp/RestSharp/wiki/Recommended-Usage) says:

> To include a request body like XML or JSON, use AddXmlBody or AddJsonBody

but what if the content is neither XML nor JSON (nor form arguments) but some custom binary data format like Protocol Buffers? How to post such data? Is there a reason why no `AddBytesBody` exists?

**Comment by alexeyzimarev** [comment]
The reason for `AddBytesBody` to exist is to add the stream content. It is an edge case. I don't know why you would use RestSharp for ProtoBuf. There are very good native ProtoBuf libraries that handle the flow very well.

**Comment by nikoudel** [comment]
I like using RestSharp for other API networking so I was surprised to realize I need to switch the library just because content type is different. The [native library](https://www.nuget.org/packages/Google.Protobuf/) handles serialization but not the transport layer which makes sense I guess. Anyway, I just switched to using HttpClient for protobuf stuff.

**Comment by alexeyzimarev** [comment]
Yeah, .NET Core 3 will add even more to ProtoBuf support. To properly implement ProtoBuf we need to spend significant effort to support HTTP/2 and implement a proper serializer for ProtoBuf. It requires some level of dedication from people that really want to have it and use RestSharp. So far, I can't see any PRs for that, so...

**Comment by nikoudel** [comment]
I didn't mean full support for Protocol Buffers (or any other data format) but rather a generic method for passing a byte array (or a stream) in. That would leave handling serialization to the user.
But you have a good point there - the lack of PRs is an understandable reason indeed :)
