### ISSUE TITLE
Request with encoding UTF-8

### ISSUE THREAD

**Issue by rsalvadorg** [restsharp/RestSharp#1311]
As far as I understood.... RestSharp serializer's output is always a String. String is defined by .Net as collection of characters using UTF-16. So there is no way to modify the encoding of the request, so I can change it, the header will be changed, the XML header will be UTF-8 for example, but the encoding of the request will be always a String so it will be UTF-16.

https://docs.microsoft.com/en-gb/dotnet/api/system.string?view=netframework-4.8

using System;namespace RestSharp.Serializers
{
    public interface ISerializer
    {
        string ContentType { get; set; }        
        string Serialize(object obj);
    }
}

**Comment by alexeyzimarev** [comment]
https://github.com/restsharp/RestSharp/blob/master/RestSharp/IRestClient.cs#L56

**Comment by rsalvadorg** [comment]
But for the body, https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestRequestExtensions.cs

It's not used anywhere, it just adding a requestSerializer.Serialize, that's a string.  And string is always UTF-16

**Comment by rsalvadorg** [comment]
I guess i found it, please could you confirm it:

https://github.com/restsharp/RestSharp/blob/master/RestSharp/Http.cs#L341

**Comment by alexeyzimarev** [comment]
`WriteStringTo` uses the `Encoding` property, which is `Utf8` by default.

Also, we assign the `Http.Encoding` to `RestClient.Encoding`, which is also `Utf8` by default.

Are you talking about request or response?
