### ISSUE TITLE
Problem installing package in .NETCoreApp,Version=v2.1 - Visual Studio for Mac Community

### ISSUE THREAD

**Issue by george-weare8** [restsharp/RestSharp#1314]
## Actual Behavior
Doesn't install nuget package RestSharp

Message in Package Console: 
Restoring packages for .NETCoreApp,Version=v2.1...
Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/4.7.0/index.json.

## Steps to Reproduce the Problem

  1. Create a console .NET Core app 2.1
  2. Try to add package RestSharp
  3. Check Package Console output for information

## Specifications

  - Version: .NET Core 2.1
  - Platform: Mac OS X Mojave 10.14.4
  - IDE: Visual Studio for Mac Community Edition

## StackTrace
<details>

```
Restoring packages for .NETCoreApp,Version=v2.1...
Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/4.7.0/index.json.
```

</details>

**Comment by alexeyzimarev** [comment]
I want to help but please have some respect, follow the contribution guidelines. At least post the error message.

**Comment by george-weare8** [comment]
@alexeyzimarev the error is in stacktrace details. Edited for better understanding from people.

**Comment by george-weare8** [comment]
There is something wrong with my environment or Visual Studio for Mac and a private feed. Fixed with removing the nuget source.

**Comment by aku2003** [comment]
I have the same problem on my Visual Studio for Mac. What was the solution?
