### ISSUE TITLE
post request: Due to insufficient system buffer space or queue full...

### ISSUE THREAD

**Issue by leoterry-ulrica** [restsharp/RestSharp#1315]
## Expected Behavior
post request successfully

## Actual Behavior
![QQ图片20190516112417](https://user-images.githubusercontent.com/18339429/57824324-4a4be680-77cd-11e9-96f8-fb27fdb901ec.jpg)

**Comment by alexeyzimarev** [comment]
Please try following the contribution guidelines next time.
