### ISSUE TITLE
Does this libary support http2

### ISSUE THREAD

**Issue by Zapnologica** [restsharp/RestSharp#1316]
Does this library support multiple requests over a single tcp socket?

We are looking for a high performance http client that can send millions of http post requests a day without exhausting the system sockets.

**Comment by Niekvdm** [comment]
Would love to know this aswell, if not are there any plans of integrating this?

**Comment by alexeyzimarev** [comment]
RestSharp is _not_ a low-level http library. It uses what .NET Core/Framework gives, currently it is the `HttpWebRequest` that is used as the lowest level we go. Everything that is supported by `HttpWebRequest` is supported by RestSharp and nothing more, nothing less.

**Comment by 564064202** [comment]
did you test?
theHttpWebRequest.ProtocolVersion=HttpVersion.Version20;
