### ISSUE TITLE
Port to be used by RestSharp for making API call

### ISSUE THREAD

**Issue by abhi2ab** [restsharp/RestSharp#1317]
## Steps to Reproduce the Problem

  1. Need to know the port number which RestSharp usage internally to make api call. Need to ask IT team to enable the same. Thanks in advance.
  2.
  3.

## Specifications

  - Version: 106.6.9
  - Platform: Window 10
  - Subsystem: 

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
Don’t use issues for questions please. The port is what you specify. RestShapr doesn’t use any ports except those that you are calling.
