### ISSUE TITLE
support for complex queries

### ISSUE THREAD

**Issue by hulluP** [restsharp/RestSharp#1318]
## Expected Behavior
if add a query like http://services.odata.org/V4/OData/OData.svc/Categories?$expand=Products($expand=ProductDetail) rest shap would allow me that

## Actual Behavior
everything after the first expand is cut of seem like the brackets are not parsed

## Steps to Reproduce the Problem

  1. add the above url as a url to the request
  2. fire the request 
  3. parse the response it is missing all the expands like it shows in the browser

## Specifications

  - Version: 106.6.9
  - Platform: android / iOS
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
Where’s your code?

**Comment by hulluP** [comment]
I cloned the repo and tried to fix this my self. After stepping a little through the code I was able to get following test to pass. Which means that this is working just needs documentation. Maybe you can add the test as well it is passing with 106.6.9

      ```
  [Test]
        public void Should_not_remove_special_query_parameters()
        {
            var request = new RestRequest();

            request.AddParameter("$expand", "Products($expand=ProductDetail)", ParameterType.QueryStringWithoutEncode);

            var client = new RestClient("https://services.odata.org/V4/OData/OData.svc/Categories");
            var expected = new Uri("https://services.odata.org/V4/OData/OData.svc/Categories?$expand=Products($expand=ProductDetail)");
            var output = client.BuildUri(request);

            Assert.AreEqual(expected, output);
        }
```
