### ISSUE TITLE
Delegate does not take 1 arguments

### ISSUE THREAD

**Issue by stesvis** [restsharp/RestSharp#1320]
In v106.6.9 when I try this sample code:

```
// easy async support
client.ExecuteAsync(request, response => {
    Console.WriteLine(response.Content);
});
```

I get the error: 

> Delegate 'Action<IRestResponse, RestRequestAsyncHandle>' does not take 1 arguments

How should we use **ExecuteAsync** now?

**Comment by alexeyzimarev** [comment]
I admit the documentation is outdated, but the error message does give you the clue that the action needs to parameters, doesn't it?

Also, tbh, I don't see any reason to use the old `ExecuteAsync` syntax with delegates if you can just use the async overload.

**Comment by alexeyzimarev** [comment]
I believe that IntelliSense provides you with the list of overloads where you can see what parameters are expected. I'd suggest switching to using `async` methods because I will soon remove all async methods that accept callbacks.
