### ISSUE TITLE
Send model as FormData - serialize model to formdata

### ISSUE THREAD

**Issue by Misiu** [restsharp/RestSharp#1325]
I have a very simple method in ASP.NET Core 2.2 WebAPI:

```
[HttpPut]
public async Task<IActionResult> Put([FromForm] SimpleRequest request, [FromForm] string param1)
{
    if (request.ExtraData == null) return BadRequest("Please send data");
    await Task.CompletedTask;
    return Ok("Works");
}
```
My model looks like this:

```
public class SimpleRequest
{
    [Required]
    public string UserId { get; set; }
    public RequestType? RequestType { get; set; }
    public DateTime Timestamp { get; set; }
    public bool Test { get; set; }
    public ExtraData ExtraData { get; set; }
}
public enum RequestType
{
    Simple,
    Complex,
}
public class ExtraData
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public ulong Id { get; set; }
    public DateTime RDate { get; set; }
    public uint Nr { get; set; }
}
```
When I do request from Postman my model is binding correctly: 
![RestSharp](https://user-images.githubusercontent.com/1741838/59515314-227c9b00-8ebf-11e9-81cb-6586e384050a.png)

Now I try to create the same using RestSharp. When I use below code it works fine:

```
var client = new RestClient("https://localhost:44325/api/values");
var request = new RestRequest(Method.PUT);

request.AddParameter("UserId", "Sample", ParameterType.GetOrPost);
request.AddParameter("RequestType", "Simple", ParameterType.GetOrPost);
request.AddParameter("Timestamp", DateTime.Now, ParameterType.GetOrPost);
request.AddParameter("Test", true, ParameterType.GetOrPost);
request.AddParameter("ExtraData.FirstName", "John", ParameterType.GetOrPost);
request.AddParameter("ExtraData.LastName", "Smith", ParameterType.GetOrPost);
request.AddParameter("ExtraData.Id", 1234, ParameterType.GetOrPost);
request.AddParameter("ExtraData.Nr", 1, ParameterType.GetOrPost);
request.AddParameter("ExtraData.RDate", DateTime.Now.AddDays(-2), ParameterType.GetOrPost);

request.AddParameter("param1", "YES", ParameterType.GetOrPost);

var response = client.Execute(request);
```
But I want to reuse my models because they are shared in separate DLL.

I create my model like so:

```
var model = new SimpleRequest
{
    UserId = "Sample",
    RequestType = RequestType.Simple,
    Timestamp = DateTime.Now,
    Test = true,
    ExtraData = new ExtraData
    {
        FirstName = "John",
        LastName = "Smith",
        Id = 1234,
        Nr = 1,
        RDate = DateTime.Now.AddDays(-2)
    }
};
```
but I'm unable to pass this model via request so that it can be correctly deserialized to my object. I've tried using request.AddJsonBody but this fails.

What is the correct way to pass model like above via RestSharp? How should I serialize it (or add as a param) to get this working? By working I mean that I want to create my model using class and send it the same way as I would use `AddParameter` for each individual field.

**Comment by alexeyzimarev** [comment]
Perfect question for StackOverflow, have you tried?

`AddJsonBody` should work, unfortunately, you provided a lot of details for the working case but almost none for the error(?) you are getting.

**Comment by Misiu** [comment]
@alexeyzimarev Yes, I've created an almost exact same question on StackOverflow: https://stackoverflow.com/questions/56599268/resrsharp-send-complex-model-to-api-that-can-be-read-via-fromform

I've already tried `request.AddJsonBody(model)` but without luck.
When I try making PUT request I get `BadRequest` with below body:

{"errors":{"UserId":["The UserId field is required."]},"title":"One or more validation errors occurred.","status":400,"traceId":"800013d3-0002-fe00-b63f-84710c7967bb"}

because `UserId ` is marked as required.

**Comment by Misiu** [comment]
@alexeyzimarev I got an answer on StackOverflow: https://stackoverflow.com/a/56625426/965722

```
public static class RestSharpExtension
{
        public static IDictionary<string, string> ToKeyValue(this object metaToken)
        {
        if (metaToken == null)
        {
                return null;
        }

        JToken token = metaToken as JToken;
        if (token == null)
        {
                return ToKeyValue(JObject.FromObject(metaToken));
        }

        if (token.HasValues)
        {
                var contentData = new Dictionary<string, string>();
                foreach (var child in token.Children().ToList())
                {
                var childContent = child.ToKeyValue();
                if (childContent != null)
                {
                        contentData = contentData.Concat(childContent)
                                                .ToDictionary(k => k.Key, v => v.Value);
                }
                }

                return contentData;
        }

        var jValue = token as JValue;
        if (jValue?.Value == null)
        {
                return null;
        }

        var value = jValue?.Type == JTokenType.Date ?
                        jValue?.ToString("o", CultureInfo.InvariantCulture) :
                        jValue?.ToString(CultureInfo.InvariantCulture);

        return new Dictionary<string, string> { { token.Path, value } };
        }
}
```

use case:

```
public async Task<IActionResult> Index()
{
    var model = new SimpleRequest
                        {
                            UserId = "Sample",
                            RequestType = RequestType.Simple,
                            Timestamp = DateTime.Now,
                            Test = true,
                            ExtraData = new ExtraData
                            {
                                FirstName = "John",
                                LastName = "Smith",
                                Id = 1234,
                                Nr = 1,
                                RDate = DateTime.Now.AddDays(-2)
                            }
                        };
    var keyValueContent = model.ToKeyValue();
    keyValueContent.Add("param1", "YES");
    var formUrlEncodedContent = new FormUrlEncodedContent(keyValueContent);
    var urlEncodedString = await formUrlEncodedContent.ReadAsStringAsync();

    var client = new RestClient("http://localhost:51420/api/values/Put");
    var request = new RestRequest(Method.PUT);

    request.AddParameter("application/x-www-form-urlencoded", urlEncodedString, ParameterType.RequestBody);

    var response = client.Execute(request);
}
```

but as You can see it isn't very intuitive - You must convert the object to a dictionary, then convert that dictionary into FormUrlEncodedContent, read from it and then add that string as param.

Can this be simplified?

I think that the use case is very simple: I want to use shared DLL containing models to build API and client code and instead of creating all parameters manually (using `AddParameter`) I would like to create an instance of my model and pass it as a parameter.

**Comment by alexeyzimarev** [comment]
If you strictly want to do a POST with the form data, you can just use `AddObject`. But forms are flat, you cannot send complex objects.

If you want to bind a complex object, you should use `[FromBody]` attribute and in that case, `AddJsonBody` would work. It has nothing to do with RestSharp, I'd suggest you check the [WebApi docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.2#sources) to find out how model binding works.
