### ISSUE TITLE
Add body to Get Request (AddJsonBody) is not working

### ISSUE THREAD

**Issue by Taher-Assad** [restsharp/RestSharp#1330]
## Expected Behavior
Valid response

## Actual Behavior
Not adding any parameter or body
In VS debug mode,
I can see the parameters in req.
But the server didn't receive any body.
and I always have the error message  **"request body invalid or not set"**

**Comment by alexeyzimarev** [comment]
It is because according to RFCs body is not something that GET requests support.

**Comment by alexeyzimarev** [comment]
Here is the background for it. We have no plan to do anything that is not in the RFC scope 
https://stackoverflow.com/questions/978061/http-get-with-request-body

**Comment by Taher-Assad** [comment]
@alexeyzimarev 
Thanks for your Replay!

**Comment by sebastienricher** [comment]
Hi @alexeyzimarev,

I've been bumping into this recently. .Net Core now supports sending GET with bodies, although it's still not clear that this should generally be used, I see a few large APIs use it. Some use it with POST available as an alternative, but I've come across some that do not.

Reference from SO: https://stackoverflow.com/questions/43421126/possible-for-httpclient-to-send-content-or-body-for-get-request/

Of course if would be nice if everyone would get along and follow standards the same way hehe but from a "client developper" point of view. I'm stuck with needing to integrate APIs that for me to use GET with bodies.

This means that I'll have to bypass RestSharp and implement this on my own (which is way less fun).

With .net Core supporting this and APIs adopting this, could you reconsider putting this in?

Reading about this, the RFC has been modified (I think), meaning that the GET Body is supported and allowed, just that servers should ignore it.

Thanks!

**Comment by Leandro-Albano** [comment]
I actually think that should be considered wrong as the current version of the RFC does not explicitly deny a GET request containing a Body.

> A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.

Seems that should be up to the server's implementation to reject it or not.

Blocking it at the client library level invalidates the use of RestSharp in many applications that, at some point, needs to communicate with someone else's server and might face this scenario. 
Working around it would require implementing the use of another library.

**Comment by calebfaith** [comment]
I just spent a frustrating hour debugging this issue. 

I think that RestSharp should either support it or at least should throw an exception to let the user know this behaviour isn't supported instead of silently ignoring it.
