### ISSUE TITLE
How to add custom date format as header

### ISSUE THREAD

**Issue by garciamorenc** [restsharp/RestSharp#1331]
Hi,

My problem is that I need to send the Date header with a custom format. 

When I add a Date header like DateTime type everything is ok. For example:
```csharp
request.AddHeader("Date", DateTime.Now.ToString());
```

But I don't know how to add a custom Date format like this:
```csharp
long milliseconds = DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond;
string timestamp = milliseconds.ToString();
```

The above code return a string like **"63697854194383"**. So if I try to add the Date header with this value, the header is not sent because there is not a DateTime format.
```csharp
request.AddHeader("Date", "63697854194383");
```

Is there any way to send this value into the Date header?

Thanks.

**Comment by alexeyzimarev** [comment]
I believe `Date` is the restricted header parameter, along with `Accept`, `Content-Type` and `Host`. It should be a valid date. Is your server accepting dates in milliseconds?

**Comment by garciamorenc** [comment]
I am agree with you about it should be a valid date. There is not my server, is an external API that I need to use. 

My question was to know if there was any chance to skipping this validation. As you can do in `Postman `or C# `HttpWebRequest` with that lines:
```cshapr
MethodInfo priMethod = httpWebRequest.Headers.GetType().GetMethod("AddWithoutValidate", BindingFlags.Instance | BindingFlags.NonPublic);
priMethod.Invoke(httpWebRequest.Headers, new[] { "Date", timestamp });
```

You can close the issue if you consider it necessary.

**Comment by alexeyzimarev** [comment]
I was just wondering about the scenario. Ok, I see what you need. Let me check the code again to see if there's a way to quickly fix this.

**Comment by alexeyzimarev** [comment]
I think such a marginal use case falls into the custom request configuration category. You can do it like this:

```
client.ConfigureWebRequest(request => AddCustomDateHeader(request, milliseconds));

...

void AddCustomDateHeader(HttpWebRequest request, long milliseconds)
{
    var addWithoutValidate = request.Headers
        .GetType()
        .GetMethod("AddWithoutValidate", BindingFlags.Instance | BindingFlags.NonPublic);
    addWithoutValidate.Invoke(request.Headers, new[] { "Date", milliseconds.ToString() });
}
```

**Comment by garciamorenc** [comment]
Your solution works perfectly.

Thanks.
