### ISSUE TITLE
Restsharp 106.3.1 - Taking longer time to return response in few VDI system

### ISSUE THREAD

**Issue by Maji-Debabrata** [restsharp/RestSharp#1332]
## Expected Behavior
We are using Restsharp.dll (version-106.3.1) to call a rest api service within a asynch/await method with CancellationToken which contain timeout period for 3 seconds. We found that for few VDIs, Restsharp is returning response within 1 second but for few other VDIs it is taking more than 3 second to return the response. So we are getting timeout exception in 2nd scenario as it is taking more than 3 second.

Earlier we used older version(106.1.0.0) of Restsharp.dll and at that time we didn't receive any such issue.
Could you please let me know why we are experiencing this kind of issue in 106.3.1.

## Actual Behavior
Version 106.3.1 is taking longer time (more than 3 second) to return the response in few VDI. But Version 106.1.0 was able to return response within 3 second.

## Steps to Reproduce the Problem

  1. Use 106.3.1  and call the restapi
  2. Getting timeout error
  3.

## Specifications

  - Version: 106.3.1.0
  - Platform: Windows 10 enterprise, 64 bit operating system, x-64-based processor, Ram-8.00 GB, Intel(R) Xenon(R) Gold 6148 CPU @2.40 GHz 2.39 GHz (2 processor)
  - Subsystem: VDI

## StackTrace
thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System. Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n

**Comment by alexeyzimarev** [comment]
I am not sure I understand the issue. So, you want the request to be cancelled after three seconds, is that right? Are you experiencing an issue that 106.3.1 is slower than 106.1 on the same API?

**Comment by Maji-Debabrata** [comment]
Yes, as per current implementation if request does not return response within 3 second then it is throwing timeout exception. 
Right, we are experiencing that in 106.3.1 is slower than 106.1. We received the response using 106.1
Thanks!

**Comment by alexeyzimarev** [comment]
I don't understand this statement:
> We found that for few VDIs, Restsharp is returning response within 1 second but for few other VDIs it is taking more than 3 second to return the response

It is not RestSharp that returns a response. It is your service. Can you test another client, like `HttpClient`? I mean, we change the code here and there and it can bring some small difference in the response processing, but it is your server that takes three seconds or more to respond, what does it have to do with the client?

**Comment by alexeyzimarev** [comment]
I don't know how to address this. Have you tried setting the timeout to 3500 milliseconds, for example?

**Comment by Maji-Debabrata** [comment]
If we increase the timeout to 5000 milliseconds then we are getting the response. But while we use the 106.1 then we are getting the response within 3000 milliseconds.
