### ISSUE TITLE
Issue on json response

### ISSUE THREAD

**Issue by gwumkt** [restsharp/RestSharp#1335]
When making a GET request im expecting to get Json.
but the Json cant be Deserialize because the first char have "\ufeffID"

the response im getting from my GET req is:

```
﻿[
  {
    "Id": "e738c10a-fdb0-df11-ab2e-005056990011",
    "Name": "Afghanistan",
    "Code": "AF",
    "GMT": 4,
    "CC": 93,
    "MLength": 11,
    "LLength": 11,
    "DDD": "",
    "Spotid": 1,
    "BPMguid": ""
  }
]
```

when checking the first [ on the unicode-converter:
https://www.branah.com/unicode-converter

we can see that the UTF-16 is: \ufeff\u005b while normal [ needs to be \u005b

i tried everything, i added charset=UTF-8 but still it doesnt work.

** important to mention when im getting a response from the same utl but with diff method such as (HttpWebRequest), the response content is as expected..

**Comment by alexeyzimarev** [comment]
Where's your code?

**Comment by gwumkt** [comment]
Now its working, but only after i added:
`return response.Content.Replace("\ufeff", ""); //Remove Boom from response.`

i want to know why that BOOM is injected to the response.. its not coming from the endpoint 100%

`content = PostBack.RestSharp(new PostBack.RestSharpReq
                    {
                        endPoint = $"https://da82o7igfeonp.cloudfront.net/json/countries.json",
                        method = RestSharp.Method.GET,
                        ContentType = "text/plain",
                    });`

`public static string RestSharp(RestSharpReq req)
        {
            int sleep = 1000;
            IRestResponse response = null;
            var request = new RestRequest(req.method);

            if (req.method == Method.GET)
            {
                if (!string.IsNullOrEmpty(req.parameters))
                    req.endPoint = string.Concat(req.endPoint, "?", req.parameters);
            }
            else
                request.AddParameter(req.ContentType, req.parameters, ParameterType.RequestBody);

            var client = new RestClient(req.endPoint);
            client.Timeout = req.timeOut;

            if (req.auth == Auth.Basic)
                client.Authenticator = new HttpBasicAuthenticator(req.username, req.password);

            else if (req.auth == Auth.Digest)
                client.Authenticator = new NtlmAuthenticator(req.username, req.password);

            if (req.headers == null)
                req.headers = new List<Headers>();

            req.headers.Add(new Headers
            {
                header = "Content-Type",
                value = req.ContentType
            });

            foreach (Headers header in req.headers)
                request.AddHeader(header.header, header.value);

            for (int i = 0; i < req.retries; i++)
            {
                response = client.Execute(request);

                if (response.ResponseStatus == ResponseStatus.TimedOut || response.ResponseStatus == ResponseStatus.Aborted || response.ResponseStatus == ResponseStatus.Error || response.StatusCode.ToString() != "OK")
                {
                    try
                    {
                        BrandsMaster.Logs.LogsHandler.SaveLog("RestSharp\\", "", $"----------------{DateTime.UtcNow}---------------------", true);
                        BrandsMaster.Logs.LogsHandler.SaveLog("RestSharp\\", "", $"Endposint: {req.endPoint}", true);
                        BrandsMaster.Logs.LogsHandler.SaveLog("RestSharp\\", "", $"Req: {ser.Serialize(req)}", true);
                        BrandsMaster.Logs.LogsHandler.SaveLog("RestSharp\\", "", $"Res: Content: {response.Content} StatusCode: {response.StatusCode}", true);
                    }
                    catch (Exception xc) { BrandsMaster.Logs.LogsHandler.SaveLog("RestSharp\\", "", $"Error: {xc.Message}", true); }
                    Thread.Sleep(sleep);
                    sleep = sleep * 2;
                }
                else
                {
                    if (response.Content == "" || response.Content == "{}")
                    {
                        return response.StatusCode.ToString();
                    }

                    return response.Content.Replace("\ufeff", ""); //Remove Boom from response.
                }
            }

            return response.ResponseStatus.ToString();
        }`

`public class RestSharpReq
        {
            public string endPoint { get; set; }
            public string parameters { get; set; }
            public List<Headers> headers = new List<Headers> { new Headers { header = "Content-Type", value = "application/json" } };
            public int timeOut = 10000;
            public Method method { get; set; }
            public string ContentType = "application/json";
            public int retries = 5;
            public Auth auth { get; set; }
            public string username { get; set; }
            public string password { get; set; }
        }`

**Comment by saggy7001** [comment]
@gwumkt 

This is not an issue.

Why you are trying to remove '[' or ']', This is List<Dictionary> you can de-serialize this as below, 

public void Github() {
            RestClient client1 = new RestClient("https://api.github.com");
            RestRequest request = new RestRequest("/users/saggy7001/repos", Method.GET);
            request.AddParameter("Content-Type", "application/json; charset=utf-8", ParameterType.HttpHeader);

            IRestResponse<List<Dictionary<string, string>>> response = client1.Execute<List<Dictionary<string, string>>>(request);
            System.Console.WriteLine(response.Data);

            foreach (Dictionary<string, string> dict in response.Data) {
                foreach (string key in dict.Keys) {
                    if (key.Equals("name")){
                        System.Console.WriteLine(key + " : " + dict[key]);
                    }
                }
                System.Console.WriteLine("\n\n\n");
            }
        }

FYI @alexeyzimarev
