### ISSUE TITLE
Help with Json Parsing

### ISSUE THREAD

**Issue by zaeemszm** [restsharp/RestSharp#1336]
I want to parse the following JSON response:
```
{
  "message": "string",
  "errorCode": "string",
  "totalSize": 0,
  "offset": 0,
  "done": true,
  "nextRecordsUrl": "string",
  "records": [
    {
      "id": "string",
      "name": "string",
      "external_ID_vod__c": "string",
      "vExternal_Id_vod__c": "string"
    }
  ]
}
```
**Note that there are multiple 'records'

The relevant class I am using to deserialize the JSON response is:
```
public class RecordProduct
        {
            public string id { get; set; }
            public string name { get; set; }
            public string external_ID_vod__c { get; set; }
            public string vExternal_Id_vod__c { get; set; }
        }

public class Products
        {
            public string message { get; set; }
            public string errorCode { get; set; }
            public int totalSize { get; set; }
            public int offset { get; set; }
            public bool done { get; set; }
            public string nextRecordsUrl { get; set; }
            public List<RecordProduct> records { get; set; }

        }
```
The code that is calling the API:
```
public void getAllProductInfo()
        {
            RestClient client = new RestClient("blahblahblah/");

            RestRequest request = new RestRequest("/api/Products", Method.GET);

            string securityToken = getBearerToken();
            request.AddHeader("Accept", "application/json");
            request.AddHeader("Authorization", "Bearer " + securityToken);

            IRestResponse<JsonResponseSetup.Datum.Products> response = client.Execute<JsonResponseSetup.Datum.Products>(request);

            var res = response.Data.records;
            res.ForEach(Console.WriteLine);

         }
```
When I execute the last line: res.ForEach(Console.WriteLine); I do not get the records to print.

**Comment by saggy7001** [comment]
@zaeemszm 
Can you please update JSON you want to parse? above JSON is not complete

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
