### ISSUE TITLE
Bug .NET CORE 2.2 Don't followredirects 

### ISSUE THREAD

**Issue by NULLO0B** [restsharp/RestSharp#1339]
I put FollowRedirects in true and not working in latest .Net Core 2.2.
Tried the same with same code but in .net and worked.

**Comment by JPRO89-Cu** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.allowautoredirect?view=netframework-4.8

it seems that NetCore does not support https to http redirection. Maybe can implement a workaround

**Comment by danifischer** [comment]
@NULLO0B thank you, I searched for hours why 2 identical pieces of code did not work the same way. One is NetCore 3.0. the other is NetFramework 4.8.

Did you find any workaround?

**Comment by NULLO0B** [comment]
> @NULLO0B thank you, I searched for hours why 2 identical pieces of code did not work the same way. One is NetCore 3.0. the other is NetFramework 4.8.
> 
> Did you find any workaround?

it could be done manually overriding(hiding) execute method or making an extension method that follows the location header if the response was 302 BUT whats the purpose of this library i think it is not well maintained even though is a great wrapper
