### ISSUE TITLE
Product Factory Add  method returns existing id

### ISSUE THREAD

**Issue by miguelextremanet** [restsharp/RestSharp#1340]
Hello, 
I am using ProductFactory.add method to save new product in prestashop.
The method seems execute fine, but returns exising id  product.
This id (1 in my case), already exist in database and is assigned to other product

![return_existing_id](https://user-images.githubusercontent.com/38916602/61786370-d0a82880-ae0d-11e9-8a9b-b9878936f438.JPG)

**Comment by alexeyzimarev** [comment]
How is it related to RestSharp???
