### ISSUE TITLE
请求返回结果如果是中文GBK编码格式的会乱码

### ISSUE THREAD

**Issue by agoling** [restsharp/RestSharp#1342]
请求返回结果如果是中文GBK编码格式的会乱码

**Comment by agoling** [comment]
var desc='<p>���㻦��һͰ���ʣ�����ɽ�����������⣬��ϸ����ϵ�ͷ��޸��˷ѡ�</p>\
\
<p>&nbsp;Ʒ����25�����Ͱϴ�ྫ ���25kg/Ͱ ��ζ���������� ��Ҫ�ɷ֣�������Լ���ˮ���ܼ������ˮ�ȡ� ʹ�÷���������ˮ�����α�Ʒ�����;ߡ���ߡ��߲ˡ�ˮ�� �Ƚ�ϴ��������ˮ��ϴ�ɾ����ɡ� ���÷�Χ�������Ƶꡢ���ꡢ���ݡ���λʳ�õ�ϴ��֮�á�</p>';

**Comment by agoling** [comment]
请求的链接：https://descnew.taobao.com/i8/520/940/526944556544/TB1xEQXzQvoK1RjSZFw8qwiCFla.desc%7Cvar%5Edesc%3Bsign%5Ec7747bc37929152b50b969cb62c2b718%3Blang%5Egbk%3Bt%5E1564024683

**Comment by alexeyzimarev** [comment]
English please

**Comment by agoling** [comment]
> English please

If the result of the request is scrambled in Chinese GBK encoding format, the scrambled code can be seen in the second reply. This is the request link:https://descnew.taobao.com/i8/520/940/526944556544/TB1xEQXzQvoK1RjSZFw8qwiCFla.desc%7Cvar%5Edesc%3Bsign%5Ec7747bc37929152b50b969cb62c2b718%3Blang%5Egbk%3Bt%5E1564024683

**Comment by agoling** [comment]
the response result is scrambled when the result is Chinese GBK encoding format,the scrambled code can be seen in the second reply. This is the request link:https://descnew.taobao.com/i8/520/940/526944556544/TB1xEQXzQvoK1RjSZFw8qwiCFla.desc%7Cvar%5Edesc%3Bsign%5Ec7747bc37929152b50b969cb62c2b718%3Blang%5Egbk%3Bt%5E1564024683
