### ISSUE TITLE
form-data with file upload

### ISSUE THREAD

**Issue by kaushalOVE** [restsharp/RestSharp#1344]
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by kaushalOVE** [comment]
Hi,

I want to implement same using restsharp, can anyone help. Please have a look at the following screenshot from the postman.

![image](https://user-images.githubusercontent.com/53041091/62190216-728bc000-b38e-11e9-8f51-5fc0d032c25a.png)

**Comment by alexeyzimarev** [comment]
Please create a new issue according to the contribution guidelines.
