### ISSUE TITLE
form-data upload with Image and Object

### ISSUE THREAD

**Issue by kaushalOVE** [restsharp/RestSharp#1345]
I am very new to it and sorry for anything I do wrong. It will be appreciated If anyone can help me.

## Expected Behavior
Expected document upload successfully Using Click2Mail API: https://stage-rest.click2mail.com/molpro/documents/

## Actual Behavior
Getting error

## Steps to Reproduce the Problem

  1. Create the following code:
var obj = new Click2MailDocumentVM
            {
                documentName = "TestDocument",
                documentClass = "PDF",
                documentFormat = "Letter 8.5 x 11"
            };
RestClient client = new RestClient("https://stage-rest.click2mail.com");
client.Authenticator = new HttpBasicAuthenticator("sanujgandhi","Optimal@1234");
   var request = new RestRequest("/molpro/documents", "POST")
            {
                RequestFormat = DataFormat.Json
            };
request.AddFile("file", filePath, "application/pdf");
var jsonString = JsonConvert.SerializeObject(obj);
                request.AddParameter(Click2MailParams.ContentType, jsonString, ParameterType.RequestBody);
                request.AddObject(obj);
IRestResponse response = client.Execute(request);

2. I have made a request from the postman and it is working, I need help with sending the same request using restsharp.

3. Following is the image for working code from postman:

![image](https://user-images.githubusercontent.com/53041091/62197322-4592d980-b39d-11e9-8a77-86353536e148.png)
[click2mail.pdf](https://github.com/restsharp/RestSharp/files/3450649/click2mail.pdf)

## Specifications

  - Version:
  - Platform: 
  - Subsystem:

## StackTrace
<html><head><title>Apache Tomcat/7.0.70 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - Bad Request</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Bad Request</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.70</h3></body></html>

```
I have also attached the document, I am trying to upload
```

</details>

**Comment by kaushalOVE** [comment]
Can anyone suggest, How to send file in formdata using Restsharp?

**Comment by alexeyzimarev** [comment]
It is only possible to have one parameter of type Body and you are adding two, plus one file. I don't think it will ever work.
