### ISSUE TITLE
How can I to get the cookies of path=/xxxxxx ？

### ISSUE THREAD

**Issue by ChinaPhusun** [restsharp/RestSharp#1347]
![QE(UDY6WU2UQ@R ~L7GA04X](https://user-images.githubusercontent.com/38497378/62674817-b148f800-b9d6-11e9-8cd3-68db4ba78f17.png)

**Comment by ChinaPhusun** [comment]
![QE(UDY6WU2UQ@R ~L7GA04X](https://user-images.githubusercontent.com/38497378/62674804-9d04fb00-b9d6-11e9-8e38-1dd9156c274a.png)

**Comment by alexeyzimarev** [comment]
Please submit the issue following our contribution guidelines. Do not use issues for questions. If you have a question about using RestSharp, please ask a question on StackOverflow.
