### ISSUE TITLE
on debian buster x64 (netcore 2.2) request gives status code 0 very fast < 200ms (with timeout 8000) 

### ISSUE THREAD

**Issue by JPRO89-Cu** [restsharp/RestSharp#1350]
on debian buster x64 (netcore 2.2) request gives status code 0 very fast < 200ms (with timeout 8000)
"The SSL connection could not be established, see inner exception. Authentication failed, see inner exception."

**Comment by alexeyzimarev** [comment]
Issue closed for not following contributions guideline.
