### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by arashsoftco** [restsharp/RestSharp#1352]
HI there i got error while installing:

PM> Install-Package RestSharp 
Installing 'RestSharp 106.6.10'.
Successfully installed 'RestSharp 106.6.10'.
Adding 'RestSharp 106.6.10' to ConsoleApplication2.
Uninstalling 'RestSharp 106.6.10'.
Successfully uninstalled 'RestSharp 106.6.10'.
Install failed. Rolling back...
Install-Package : Could not install package 'RestSharp 106.6.10'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package RestSharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by alexeyzimarev** [comment]
It is not a big. We support 4.5.2 or .NET Standard 2.0 and it is mentioned in the readme
