### ISSUE TITLE
Server Name Indication / SNI

### ISSUE THREAD

**Issue by zenturacp** [restsharp/RestSharp#1353]
## Expected Behavior
I have a webservice running behind an NGINX-Ingress controller exposing a REST api but it seems like my application hits the default website not the actual API - when i test with the browser it works and with PostMan and ARC - i can only see that maybe REST Sharp does not send SNI information with the request?

## Actual Behavior
Hits the default website - the Ingress Controller is not able to determine what resource on the backend to connect to.

Works with Curl and all browsers.

## Specifications

  - Version: 106.3.1
  - Platform: net452

**Comment by alexeyzimarev** [comment]
I don't think there's anything related to RestSharp. If you try to use HttpClient or WebRequest, you'd probably get the same issue. Rev proxy should be completely transparent to the client. I can suggest checking your rev proxy config instead.
