### ISSUE TITLE
Memory leak when RemoteCertificateValidationCallback gets attached

### ISSUE THREAD

**Issue by nschoenberg** [restsharp/RestSharp#1354]
## Expected Behavior
When using RemoteCertificateValidationCallback or ServicePointManager.ServicePointManager.ServerCertificateValidationCallback those events gets attached internally to Class Http.

[Code of event attach here](https://github.com/restsharp/RestSharp/blob/e24f5b462711d5c64ecafb273096f938332e12a2/RestSharp/RestClient.cs#L651)

When Rest Request is done and Response no longer referenced, I expect GC to remove RestResponse from memory. I can't see a point where I can remove the Event my self.

This only happens when I attach the event, GC is fine without event.

## Actual Behavior
In my UWP App this is causing memory leaks and the complete RestRespose / RestRequest and Http Object stays in memory. Because RestResponse stays in memory, all of its content (json string) as well. 

## Steps to Reproduce the Problem

  1. Attach ServerCertificateValidationCallback
  2. Do a request with RestClient
  3. Do GC.Collect / WaitForFinalizer

## Specifications

  - Version: 106.5.4
  - Platform: UWP (Xamarin Forms)

## Screenshot of Memory Profiler (dotMemory)

![memoryProfiler](https://i.imgur.com/kabMEhF.png)

**Comment by alexeyzimarev** [comment]
Strange, the instance of `Http` is transient, so it should be collected after the request is done... Need to look more into it.

**Comment by nschoenberg** [comment]
To be fair this is of my real app and I have not isolated this into a simple case. If you need any further details please let me know because I am running out of ideas to solve this. Thanks for your quick response.

**Comment by nschoenberg** [comment]
@alexeyzimarev I did some further investigation and forked the RestSharp repository. It seems that the callback attached to the webrequest does some how holds a reference to RestResponse

https://github.com/restsharp/RestSharp/blob/b85add797e801376a7049b4d9ef3414b5e7b29c0/RestSharp/Http.Async.cs#L91

I'm not 100% sure about whats going on and would do a pull request to solve this if I can. Any ideas what I could try? Thanks alot

**Comment by alexeyzimarev** [comment]
I see. I plan to replace this call to the `async` method call, but I need to figure out the flow.

**Comment by nschoenberg** [comment]
@alexeyzimarev I did some further tests and changed one of my api calls from using RestSharp to using Flurl instead and the memory leak is gone. I did this because I was not 100% sure it is not something on my side.

I compared the two different methods RestSharp and Flurl are using internally to send the request async. RestSharp is using `HttpWebRequest.BeginGetResponse` with callback methods, Flurl is using a  `await HttpClient.SendAsync(HttpRequestMessage)`

What do you think, is it possible to change RestSharp to use HttpClient as well?

**Comment by alexeyzimarev** [comment]
Yeah, HttpClient seems to pop up in every second issue... I will plan some work to make it happen.

**Comment by A9G-Data-Droid** [comment]
It looks like this was closed without being fixed. A memory leak is a serious issue. Did this get fixed by a commit not linked to this issue? Or is it still open?

**Comment by jeffmowens** [comment]
If it was, what other reason could there be considering we're seeing the behavior in 108.x, @A9G-Data-Droid?  Can we view the 108 source to check ourselves?

**Comment by A9G-Data-Droid** [comment]
@jeffmowens You're posting in the repo where the source is. Yes, you can read it here on GitHub. I'm asking here to see if anyone else who saw this issue is still experiencing it.

@nschoenberg Do you consider this issue closed? Is the problem gone for you?

**Comment by nschoenberg** [comment]
> @jeffmowens You're posting in the repo where the source is. Yes, you can read it here on GitHub. I'm asking here to see if anyone else who saw this issue is still experiencing it.
> 
> @nschoenberg Do you consider this issue closed? Is the problem gone for you?

Hi, in 2019 (3.5 years ago ..) my Team and I worked around the issue by using the sync methods and wrapping those into a Task. I recently changed my employeer and dont have access to the code any longer. So I can't reproduce it. You can find everything needed in the description

**Comment by alexeyzimarev** [comment]
RestSharp has been using `HttpClient` for quite some time now. I don't expect this particular issue to occur.

The issue was closed by the bot due to inactivity. From the project maintenance perspective, there was no obligation to keep inactive issues open. Atm, I consider this issue as obsolete as the way RestSharp is making calls changed entirely, and if the issue with the remote certificate check callback is still there, someone needs to open another issue.

**Comment by alexeyzimarev** [comment]
Using a privately-signed CA is still legit, and assigning the `RestClientOptions.RemoteCertificateValidationCallback` will set the `ServerCertificateCustomValidationCallback` for the HTTP message handler. I saw people advising using a custom trust store for this purpose and adding that store to the chain in the callback.
