### ISSUE TITLE
In linux Centos7, use RestSharp Post request error

### ISSUE THREAD

**Issue by ddgweb** [restsharp/RestSharp#1356]
The same code ,for windows +ngix no error , everythiny is ok , bu in linux centos, error tips:
The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

bythe way, I from httpwebrequest try convert httpclient untill your's Rest sharp ,all same error

**Comment by ddgweb** [comment]
by the way, I already set "http.RemoteCertificateValidationCallback += (sender, certificate, chain, errors) => true;"  and also set "<servicePointManager
        checkCertificateName="false"
        checkCertificateRevocationList="false"
      />" ,but it's don't work

**Comment by alexeyzimarev** [comment]
It is not our issue, I think. Linux is stricter on CA roots and you seem to use a self-signed certificated. You would need to add the root authority certificate to your OS to make it work. The issue is quite common.

**Comment by dl-bgu-project** [comment]
@ddgweb Hi,

Did you found the solution for that?
I'm using CentOs too.
Why with CURL or WGET the 'skip SSL errors' is working? but with this library, this skip is not working?
