### ISSUE TITLE
RestSharp 106.6.10 problem with .Net Core

### ISSUE THREAD

**Issue by TimOfTcc** [restsharp/RestSharp#1359]
Dear All.

I am using RestSharp version 106.6.10 with .NET Core WebApi within Visual Studio successfully. However, after deploying to IIS receiving error:

> System.IO.FileNotFoundException: Could not load file or assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. The system cannot find the file specified.

My code:

```
            try
            {
                var restclient = new RestSharp.RestClient(Globals.ReportingHostAddr);

                RestRequest request = new RestRequest("ReportManagement/GetStudentIdPhotos", Method.POST);
                request.RequestFormat = DataFormat.Json;
                request.AddJsonBody(args);
                response = restclient.Execute(request);

                if (!response.IsSuccessful)
                {
                    var ex = JsonConvert.DeserializeObject<AppExceptionMessage>(response.Content);

                    return new BadRequestObjectResult(ex);
                };
            }
            catch (Exception ex)
            {
                var parsedEx = CurrentExceptionMgr.ParseErrorMsg(ex.Message);
                return new BadRequestObjectResult(parsedEx);
            };
```

Thanks.

**Comment by alexeyzimarev** [comment]
Please try StackOverflow. There's something with the app publishing in your solution that gives you this error. It is not a RestSharp bug.

**Comment by TimOfTcc** [comment]
Dear @alexeyzimarev. My consern is that all referenced third party libraries are working as expected, however RestSharp not. I read that, starting from 106.6 it is built with .NetStandard - yes, it is working, however why there is problem after deployment. Thanks.

**Comment by alexeyzimarev** [comment]
It is the setup issue, not the library issue as such.
