### ISSUE TITLE
did you test theHttpWebRequest.ProtocolVersion=HttpVersion.Version20;

### ISSUE THREAD

**Issue by 564064202** [restsharp/RestSharp#1364]
did you test theHttpWebRequest.ProtocolVersion=HttpVersion.Version20;

**Comment by alexeyzimarev** [comment]
Btw, `HttpWebRequest` parses the protocol version and doesn't let you assign v2. I hope when I am done with the `HttpClient` version of the REST Client, you will be able to use HTTP2.

**Comment by 564064202** [comment]
@alexeyzimarev hi,sir ,how about the HttpClient version of the REST Client now?
