### ISSUE TITLE
Does RestSharp cache the network login?

### ISSUE THREAD

**Issue by vickyrathee** [restsharp/RestSharp#1365]
## Expected Behavior
Network authentication must re-login when username/password changes in loop for WebProxy.

## Actual Behavior
I am changing my `NetworkCredential` username in for loop to refresh the proxy/ip address. But it seems that RestSharp is caching the NetworkCredential and not logging again on each request s if I change the username.

While HttpClient is working fine and logging in again when username changed in loop > which result in `ip` address changed in server response.. see the result screenshot

I already tried to implement `client.CachePolicy = new HttpRequestCachePolicy(HttpRequestCacheLevel.Revalidate);` but that's not also helpful.

## My Code

```
static string proxyUserName = "username";	
static string proxyPassword = "password";

async Task Main()
{
	await RestSharpTest();
	await HttpClientTest();
}

private async Task RestSharpTest()
{
	Console.WriteLine($"**RestSharp Test**");
	for (int i = 0; i <= 10; i++)
	{
		bool shouldRefreshProxy = false;
		if (i % 3 == 0)
		{
			Console.WriteLine($"**Proxy refresh at request {i} using RestSharp**");
			shouldRefreshProxy = true;
		}
		var client = GetRestClient();
		client.Proxy = GetProxy(shouldRefreshProxy);
		var request = new RestRequest(Method.GET);
		//request.Dump();
		IRestResponse response = await client.ExecuteTaskAsync(request);
		Console.WriteLine($"Status: {response.StatusCode} Content: {response.Content}");
	}
}

private static RestClient GetRestClient()
{
	RestClient client = new RestClient("http://lumtest.com/myip.json");
	return client;
}

private async Task HttpClientTest()
{
	Console.WriteLine($"**HttpClient Test**");
	for (int i = 0; i <= 10; i++)
	{
		bool shouldRefreshProxy = false;
		if (i % 3 == 0)
		{
			Console.WriteLine($"**Proxy refresh at request {i} using HttpClient**");
			shouldRefreshProxy = true;
		}
		var client = GetHttpClient(shouldRefreshProxy);
		var response = await client.GetAsync(new Uri("http://lumtest.com/myip.json"));
		var content =	await response.Content.ReadAsStringAsync();
		Console.WriteLine($"Status: {response.StatusCode} Content: {content}");
	}
}

private static HttpClient GetHttpClient(bool shouldRefreshProxy)
{
	var selectedProxy = GetProxy(shouldRefreshProxy);

	var handler = new HttpClientHandler
	{
		Proxy = selectedProxy,
		UseCookies = false,
		AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
	};
	HttpClient client = new HttpClient(handler);
	return client;
}

public static WebProxy GetProxy(bool refreshProxy)
{
	WebProxy webProxy = new WebProxy("zproxy.lum-superproxy.io:22225")
	{
		BypassProxyOnLocal = true
	};
	if (refreshProxy)
	{
		// Add the random session to refresh the IP if refreshProxy = true
		proxyUserName += $"-session-{DateTime.UtcNow.Ticks}";
		webProxy.Credentials = new NetworkCredential(proxyUserName, proxyPassword);
	}
	else
	{
		webProxy.Credentials = new NetworkCredential(proxyUserName, proxyPassword);
	}
	return webProxy;
}
```

Result screenshot

![image](https://user-images.githubusercontent.com/6106479/66112399-67504d00-e5e8-11e9-88d8-332b2b1acaac.png)

**Comment by alexeyzimarev** [comment]
`RestClient` is stateless in regards to the request and each request is executed independently. The behaviour can be caused by the `WebRequest` default behaviour and there's little we can do about it.

**Comment by alexeyzimarev** [comment]
I don't really think it is related to the network login but rather how proxy is supported in .NET standard. Btw we explicitly ask to provide environment details in the issue.

**Comment by vickyrathee** [comment]
@alexeyzimarev 

But the HttpClient works perfectly fine with almost same code implementation. I can send you test credentials for proxy on email to test if you want to take a look?

Environment : .Net 4.6 and the RestSharp 106.6.10

**Comment by alexeyzimarev** [comment]
Yeah, but we don't use `HttpClient`, we use `HttpWebRequest`. It is quite weird that .NET Framework 4.6 has those issues, usually, we get complaints about .NET Core apps that have issues with proxy.

**Comment by alexeyzimarev** [comment]
@vickyrathee are you on .NET Core or .NET Framework?

On .NET Core, `HttpWebRequest` uses `HttpClient` and it should work the same way.

**Comment by vickyrathee** [comment]
.Net framework. And it doesn’t work same as http client.

**Comment by alexeyzimarev** [comment]
@vickyrathee ok, I haven't made myself clear. RestSharp _does not_ cache anything. If something gets cached - it happens in `WebRequest`. We cannot fix it, it is the .NET code. When we'd have the HttpClient-based implementation, it will probably be fixed.
