### ISSUE TITLE
Support .Net Core 3.0

### ISSUE THREAD

**Issue by will056** [restsharp/RestSharp#1367]
When is support planned for .Net core 3.0?

**Comment by alexeyzimarev** [comment]
What do you mean by "support"? You can use the library with .NET Core 3. What exactly are you asking for?

**Comment by will056** [comment]
Sorry, I didn’t put it that way. Yes, that's what I meant

**Comment by attiqe** [comment]
@alexeyzimarev just a follow-up question:

What are your thoughts on using the [System.Text.Json](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#fast-built-in-json-support) instead of Newtonsoft.JSON? I am asking this because I read the [note ](https://github.com/restsharp/RestSharp#note-on-json-serialization)on it.

**Comment by alexeyzimarev** [comment]
@attiqe that is exactly my thought. The only issue I see is that SimpleJson is so bad but people use it for so long that we can have compatibility issues when we do it right. 

In addition, `System.Text.Json` is .NET Core only so it will never be available in the full framework, which a lot of people still use.

I thought of creating a base library like `RestSharp.Core` and then `RestSharp` package will have it as a dependency and use `SimpleJson` by default. Then, we can have separate packages for serialisation using Newtonsoft.Json, System.Text.Json and Utf8Json for example.

Another way is to have the base library that will only contain interfaces. Then there will be a full split, like the legacy version will go as it does and the new version will be using HttpClient.

It would be nice to get some feedback in this issue.

**Comment by attiqe** [comment]
I like the second approach where we can have a base library that contains interfaces.  This way it will be much more flexible design-wise as well.

**Comment by alexeyzimarev** [comment]
True. We can also name it like Microsoft does, like `RestSharp.Abstractions`

**Comment by MKI-Miro** [comment]
when next version will be released?

**Comment by xsoheilalizadeh** [comment]
> In addition, System.Text.Json is .NET Core only so it will never be available in the full framework, which a lot of people still use.

Are you sure that it's only support .NET Core? I don't think so.
You could see the [`System.Text.Json`](https://www.nuget.org/packages/System.Text.Json) nuget package and its dependencies, it targeted by full framework too, also Immo Landwerth mentioned it in the Try the new  System.Text.Json APIs [blog](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/).
@alexeyzimarev

**Comment by attiqe** [comment]
@xsoheilalizadeh you are right it support .NETFramework 4.6.1 onwards.

**Comment by alexeyzimarev** [comment]
But our lowest LTS is 4.5.2

**Comment by alexeyzimarev** [comment]
`System.Text.Json` serialiser is now available as a separate package https://restsharp.dev/usage/serialization.html#system-text-json

It targets .NET Standard 2.0 and .NET Framework 4.6.1
