### ISSUE TITLE
encode ampersand(&) character in x-www-form-urlencoded

### ISSUE THREAD

**Issue by satuday** [restsharp/RestSharp#1368]
## Expected Behavior
ampersand character should be encoded when using content type x-www-form-urlencoded

## Actual Behavior
ampersand is not encoded, which cause the server to interpret the string after ampersand as another parameter  

## Steps to Reproduce the Problem

  1. create a POST request
  2. AddParameter("description", "string with & character");
  3. send request

## Specifications

  - Version: 105
  - Platform: .net fw 4.5.1
  - Subsystem: Windows server 2016

**Comment by alexeyzimarev** [comment]
Sorry, v105 is not being maintained. I need to know if this issue can be reproduced on the latest version.
