### ISSUE TITLE
RestSharp through network interface

### ISSUE THREAD

**Issue by clintnetwork** [restsharp/RestSharp#1369]
Hi,

I would like to know if it's possible to make a HTTP call through a network interface, and not by an IP, by example through eth1, I've a lot of interfaces with the same IPs so I need to do this like this!

Thank you

**Comment by alexeyzimarev** [comment]
Please respect our contribution guidelines and don’t use GitHub issue for questions. Short answer though: everything you can do with WebRequest, you can do with RestSharp but on the low level - not much more. RestSharp is the convenience tool on top of WebRequest and not an HTTP client.
