### ISSUE TITLE
request to add support for http2

### ISSUE THREAD

**Issue by Varorbc** [restsharp/RestSharp#1370]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/

![image](https://user-images.githubusercontent.com/5714438/66382556-052f8780-e9ee-11e9-852c-e704c516b1b9.png)

**Comment by alexeyzimarev** [comment]
RestSharp is not using HttpClient. I am not sure how to proceed with http2 unless Microsoft implements it for WebRequest.

**Comment by Varorbc** [comment]
https://github.com/dotnet/corefx/blob/4ac4c0367003fe3973a3648eb0715ddb0e3bbcea/src/System.Net.Requests/src/System/Net/HttpWebRequest.cs#L1091-L1100

I found that the underlying implementation of HttpWebRequest is HttpClient, which means that http2 can be supported as long as netstandard 2.1 is supported.

**Comment by alexeyzimarev** [comment]
Thanks for the heads up. I would rather prefer moving RestSharp to use HttpClient, I was missing the grip of some properties on the request. I hope the link you posted will understand how to close those gaps.

**Comment by Varorbc** [comment]
https://github.com/dotnet/corefx/issues/41645

**Comment by scalablecory** [comment]
@alexeyzimarev please reach out if you need any info re: porting to `HttpClient`.

**Comment by Varorbc** [comment]
@alexeyzimarev https://github.com/dotnet/corefx/issues/41645#issuecomment-566762539
