### ISSUE TITLE
Просьба добавить возможность взаимодействия с progressbar

### ISSUE THREAD

**Issue by Exolithus** [restsharp/RestSharp#1371]
Вы не могли бы, добавить метод DownloadData, но с параметром progressbar, чтобы можно было качественно отслеживать состояние загрузки

**Comment by alexeyzimarev** [comment]
The communication language for this repository is English.

**Comment by Exolithus** [comment]
Sorry, but my english is not so good
You can add a data loading method, but with a progress bar parameter, so that you can accurately monitor the download status
