### ISSUE TITLE
suggest to custom deserializer for a request

### ISSUE THREAD

**Issue by Acgnu** [restsharp/RestSharp#1374]
## Expected Behavior
Request to a server and response Content-Type is "text/xml" but the practical content is json string, and RestSharp will deserialize it use xmlDeserializer then cause a exception, and the response.Data will be null, I wish to custom deserializer such like JsonDeserializer just for current request

**Comment by alexeyzimarev** [comment]
Use `OnBeforeDeserialization` and change the content type accordingly.
