### ISSUE TITLE
System.ArgumentNullException: 'Value cannot be null. (Parameter 'name')'

### ISSUE THREAD

**Issue by MKI-Miro** [restsharp/RestSharp#1375]
Hi

I get this error System.ArgumentNullException: 'Value cannot be null. (Parameter 'name')'
on this code

            ```
var request = new RestRequest();
            request.Method = Method.GET;
            request.RequestFormat = DataFormat.Json;
            request.AddHeader("X-Application-Name", "apiary");
            request.AddHeader("Content-Type", "application/json");

            var mallOrderClientSk = new RestClient($"https://mpapi............");
            var resultSk = mallOrderClientSk.Execute(request);
```

## Specifications

  - Version: 106.6.10
  - Platform: .NET CORE 3
  - Subsystem:

## StackTrace
   at System.Text.EncodingTable.GetCodePageFromName(String name) in /_/src/System.Private.CoreLib/shared/System/Text/EncodingTable.cs:line 34

**Comment by MKI-Miro** [comment]
@alexeyzimarev
1. I dont think it is duplicat, because i dont have any params..
2. When you will fix it?

**Comment by alexeyzimarev** [comment]
1. It is the same issue.
2. I am the maintainer of this project, not customer support. The PR to fix it has been merged and will be released in the next version.

**Comment by MKI-Miro** [comment]
is it possible to get niglty build to get it working?

**Comment by MKI-Miro** [comment]
or any other way how to get application working?
