### ISSUE TITLE
Retrying to the request after 2 minutes

### ISSUE THREAD

**Issue by prasad-yadav** [restsharp/RestSharp#1377]
I am using RestSharp.RestClient to call the API which downloads the file. This API takes 3 minutes to process the file and send the response. The RestClient timeout after 100s which is default timeout. I changed that to 180s but still, the request fails. I verified that the server API is properly working. 

After doing some debugging, I find that RestClient retries the request again after 2 minutes. I was not able to find the configuration to disable or update the timeout for retry.

## Expected Behavior
There should be any configuration to increase the timeout for retry or disable the retry. 
Note: This is more of a question. Not sure what is expected behavior by considering best practice. 

## Actual Behavior
RestSharp.RestClient retries the request after every 2 minutes if the response from the API is not received. 

## Steps to Reproduce the Problem

  1. Create the sample RestSharp project to call the API of the server.
  2. Design API to return the response after 3 minutes.
  3. Execute the project
  4. The request is passed to API which takes 3 minutes to execute.
  5. While the execution of an API completes two minutest, then RestSharp retries the request again.

## Specifications

  - Dotnet Version: 4.7 
  - Operating System: Window 10 
  - RestSharp Version: 105.2.3.0

**Comment by alexeyzimarev** [comment]
Please provide the request code.
