### ISSUE TITLE
Parameter with null value for Name is allowed, but then a null reference exception is thrown

### ISSUE THREAD

**Issue by Andrius-Dobrotinas** [restsharp/RestSharp#1378]
Parameter (class) constructor allows nulls for "name" argument as long as parameter "type" value is ParameterType.RequestBody. However, a null reference exception is thrown when there are default parameters due to a bug in code: at the point where it is adding default parameters to the request, it iterates over all parameters and calls .Equals method on parameter name (which was allowed to be null by the Parameter constructor), resulting in a null reference exception. Location RestClient.cs, around line 548 (master branch at the time of writing).

So either one of these fixes should be made:
* Parameter constructor should not allow nulls for "name" regardless of parameter type, or
* the bug in RestClient should be fixed.

I think both changes should be made. The second one would fix a bug, and the first one would make code a bit more elegant - allowing nulls for certain constructor arguments depending on the value of other arguments makes things obscure. The constructor should not allow any nulls. Instead, to make things nicer, a derived class, BodyParameter, could be created where constructor doesn't ask for a name and automatically assigns parameter type). But this would be a breaking change, so I'm not sure whether it would be accepted.

## Steps to Reproduce the Problem

  1. Add any default parameter to the Rest Client
  2. Create new Parameter(null, "value", Type = ParameterType.RequestBody)
  2. Add said parameter to the request
  3. Execute the request

## Specifications

  - Version: Current master branch (though bug has been there since at least 
  - Platform: Any
  - Subsystem:

**Comment by alexeyzimarev** [comment]
Fixed now.
