### ISSUE TITLE
Exceptions are not thrown, response with status code 0 returned

### ISSUE THREAD

**Issue by Andrius-Dobrotinas** [restsharp/RestSharp#1379]
When an exception is thrown inside RestClient (for example, due to a bug), it returns a Response object with Status set to 0 and an exception message in Message property. This is not helpful, for two reasons:
* if there's a bug in RestClient, we can't really tell what went wrong. If an error message says something like "Object reference not set to an instance of an object", as a user I don't even know what to think of it, and when reporting an issue, it's not as helpful as it could be (unless I debug the source code). It would be much more informative if an exception was simply propagated instead of returning a response object. That way, we'd have a proper error stack and possibly more useful information.
* request timing out. 0 is not a valid HTTP status code, and apparently it's not reserved for a particular exception. So if a request times out, I might want to maybe retry it, or do something special about it in my code. That's not possible if an exception is not thrown because it's unfeasible to parse an error message to determine what went wrong in code.

## Expected Behavior
So I just propose any sort of exception is propagated outside RestClient for users to deal with in an informed way rather than just returning a valid response with an error message.

## Steps to Reproduce the Problem

  1. Add any default parameter to the Rest Client
  2. Create new Parameter(null, "value", Type = ParameterType.RequestBody)
  3. Add said parameter to the request
  4. Execute the request
  5. check response object - Status is 0, and message says something like "Object reference not set to an instance of an object".

**Comment by alexeyzimarev** [comment]
I agree that handling exceptions this was isn’t optimal but if we do what you propose, I am sure it will immediately break hundreds of thousands projects that expect the request not to throw. I guess the only option is to exhibit such new behaviour only by opting-in explicitly.

**Comment by Andrius-Dobrotinas** [comment]
I see. Explicit opting-in would be alright. I could work on this once it's agreed on.

**Comment by alexeyzimarev** [comment]
I believe that should an option in the configuration but not sure if it’s for the client or for request.

**Comment by alexeyzimarev** [comment]
It is actually by design.

Async methods throw always. `Execute` doesn't throw. Specific overloads, which I would recommend using, like `Get`, `Post` and so on - they all throw.
