### ISSUE TITLE
ContentEncoding in RestResponse throwing error

### ISSUE THREAD

**Issue by MKI-Miro** [restsharp/RestSharp#1381]
In RestResponse string encoding is empty and throwing error 

public static string AsString(this byte[] buffer, string encoding)
        {
            Encoding enc;
            try
            {
                enc = Encoding.GetEncoding(encoding);
            }
            catch (Exception)
            {
                enc = Encoding.UTF8;
            }

            return AsString(buffer, enc);
        }

## Specifications

  - Version: Latest
  - Platform: .NET CORE 3

**Comment by alexeyzimarev** [comment]
It doesn't throw. It is your IDE that stops on the exception because you have the option enabled.

It is fixed in the last version.
