### ISSUE TITLE
How to get ReponseHeader while using DownloadData

### ISSUE THREAD

**Issue by noufionline** [restsharp/RestSharp#1383]
We are using Alfresco Document Management System internally in our server. When I am downloading a file using Alfresco API the file name and the mimetype is sent as ResponseHeader. I want to build the file name with proper extension based on the mimetype before calling the Save Extension method on DownloadData. Need a way to grab the response header before calling Save.

Can you help?

**Comment by alexeyzimarev** [comment]
Please follow the contribution guidelines of this project and not use issues for questions.
