### ISSUE TITLE
RestSharp 106.6.10 is built in debug mode

### ISSUE THREAD

**Issue by drewfreyling** [restsharp/RestSharp#1384]
## Expected Behavior
Nuget builds are built in release mode. Looks like a regression issue of #1113 

## Actual Behavior
Nuget build is built in debug mode

## Steps to Reproduce the Problem

  1. Install the package from nuget into a .net framework 4.6 app
  2. Check the dll in dotpeek

## Specifications

  - Version: 106.6.10
  - Platform: .net framework 4.6
  - Subsystem:

![image](https://user-images.githubusercontent.com/1145869/68905546-58cf8680-078d-11ea-9b46-4ae937a9d94e.png)

**Comment by alexeyzimarev** [comment]
It is now fixed in the GitHub actions build script.
