### ISSUE TITLE
{   "$id": "1",   "Message": "The request is invalid.",   "MessageDetail": "The parameters dictionary contains a null entry for parameter 'Id' of non-nullable type 'System.Int32' for method 'System.Collections.Generic.List`1[Sys.Data.LangLight] GetTranslatesLight(Int32)' in 'SysWebApi.Controllers.DefaultController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter." }

### ISSUE THREAD

**Issue by charpdevelooper** [restsharp/RestSharp#1385]
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by charpdevelooper** [comment]
Im sending Int32 I have nothing null parameters.what i have to do


{   "$id": "1",   "Message": "The request is invalid.",   "MessageDetail": "The parameters dictionary contains a null entry for parameter 'Id' of non-nullable type 'System.Int32' for method 'System.Collections.Generic.List`1[Sys.Data.LangLight] GetTranslatesLight(Int32)' in 'SysWebApi.Controllers.DefaultController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter." }

**Comment by alexeyzimarev** [comment]
Please follow the contribution guidelines when opening an issue.
