### ISSUE TITLE
IRestResponse cannot get access token

### ISSUE THREAD

**Issue by chanmmn** [restsharp/RestSharp#1387]
## Expected Behavior
Get back access token

## Actual Behavior
Cannot get back access token

## Steps to Reproduce the Problem

  1.
IRestClient client = new RestClient("http://172.1111.1111.111:8080/coresecurityops/connect/token");
            IRestRequest request = new RestRequest("token", Method.POST);
            request.AddHeader("Accept", "application/json");
            request.AddParameter("grant_type", "client_credentials");
            //request.AddParameter("scope", "spark-payroll");
            request.AddParameter("scope", "xxxxxxx");
            request.AddParameter("client_id", "xxxxxxxxxxxx");
            request.AddParameter("client_secret", "xxxxxxxxxxxxxnHym7iBBxBGvaILGGS/SSS/5");
            IRestResponse response = client.Execute(request);
  2.
  3.
Found this problem everywhere from google but no solution works. 
## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
What "cannot" means here? You don't get a response? The call times out? Have you checked the returned response? Does it deserialize?

**Comment by chanmmn** [comment]
Null value returned.

**Comment by alexeyzimarev** [comment]
What is the response status? What is the response error message, if any?
