### ISSUE TITLE
Returns DateTime in CurrentCulture not InvariantCulture

### ISSUE THREAD

**Issue by oznetmaster** [restsharp/RestSharp#1393]
https://github.com/restsharp/RestSharp/blob/de1d1ad136d7858bcc81fbd46449fc757b2eda9a/RestSharp/Serialization/Xml/XmlSerializer.cs#L243

If obj is a DateTime, but no DateFormat has been set, then this code return obj.ToString(), which uses the current CultureInfo to format the DateTime.

The code needs to check for DateTime as the object type, and return ((DateTime)obj).ToString (CultureInfo.InvariantCulture) if DateFormat is not set.

**Comment by alexeyzimarev** [comment]
I think a lot of people actually expect it to be CurrentCulture. We cannot just change this behaviour out of a sudden. If we aim to fix this issue, it should keep the existing behaviour and using InvariantCulture should be opt-in.
