### ISSUE TITLE
RestRequest does not support "=" as a value in the query parameter use to work correctly before

### ISSUE THREAD

**Issue by DHirani** [restsharp/RestSharp#1394]
## Expected Behavior
http://test.com/myQuery?Select=test&Where=OrderId=>1000

## Actual Behavior
It throws the Where=OrderId=>1000 from the query so it the URL is then wrong

## Steps to Reproduce the Problem
Create RestRequest and pass in myQuery?Select=test&Where=OrderId=>1000

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
Please supply a code sample to reproduce the issue.

**Comment by DHirani** [comment]
var request = new RestRequest("myQuery?Select=test&Where=OrderId=>1000", Method.Get, DataFormat.Json);

var client new RestClient("http://localhost:5000");
var response = client.Execute(request);

// Request built as http://test.com/myQuery?Select=test
// Request should be http://test.com/myQuery?Select=test&Where=OrderId=>1000

// Problem is in the constructor of RestRequest it can't handle "=" when in the value field i.e. OrderId=>1000

**Comment by alexeyzimarev** [comment]
That’s not how you would usually do it. By using AddQueryPrameter method on the request you can avoid having the issue. But I will check anyway.

**Comment by DHirani** [comment]
Correct but the previous version supported it by passing it through the constructor and then you're extracting and adding to parameter but the code looks for "=" on the split..

it needs to do something like this.

            var queryStringStart = uri.IndexOf('?');
            if (queryStringStart >= 0 && uri.IndexOf('=') > queryStringStart)
            {
                var queryParams = ParseQuery(uri.Substring(queryStringStart + 1));
                request.Resource = uri.Substring(0, queryStringStart);

                foreach (var param in queryParams)
                    request.AddQueryParameter(param.Name, param.Value, false);
            }

        private static IEnumerable<NameValuePair> ParseQuery(string query) =>
            query.Split('&').Select(splitByAnd => new {splitByAnd, firstEqual = splitByAnd.IndexOf('=')})
                .Where(@t => @t.firstEqual >= 0)
                .Select(@t => new {@t, leftPart = @t.splitByAnd.Substring(0, @t.firstEqual)})
                .Select(@t => new {@t, rightPart = @t.@t.splitByAnd.Substring(@t.@t.firstEqual + 1)})
                .Select(@t => new NameValuePair(@t.@t.leftPart, @t.rightPart)).ToList();

**Comment by alexeyzimarev** [comment]
I found it, the issue is in the `ParseQuery` local function. It splits the parameter with `=` and if there're more than one equality signs, it drops the parameter. I fixed it now. The issue is that I can't build RestSharp with tests, it consistently hangs on async tests... As soon as I'll be able to fix it, I will make a new version (long-pending)...

**Comment by DHirani** [comment]
Thank you for the quick turn around

**Comment by alexeyzimarev** [comment]
It would be great if you can test with the latest preview package.

**Comment by DHirani** [comment]
working in build 10.9.0

**Comment by alexeyzimarev** [comment]
Awesome
