### ISSUE TITLE
Error in class 'OAuth2UriQueryParameterAuthenticator'

### ISSUE THREAD

**Issue by Henry-if78x** [restsharp/RestSharp#1398]
For my project I have to use the 'oauth_token' parameter as a query parameter. Thus I tried to use the class 'OAuth2UriQueryParameterAuthenticator'. Basically it works. But from my point of view it contains two errors. The first error is that it adds the parameter every time when you start a request. After five requests, you have the 'oauth_token' paramter 5 times in your request. I think the error is in the function 'Authenticate'. It doesn't check if this parameter is already in the parameter list. (In the class 'OAuth2AuthorizationRequestHeaderAuthenticator' there is a check in the function 'Authenticate' that prevents that the parameter is added more than once. So I guess that this check is missing in the class 'OAuth2UriQueryParameterAuthenticator'.)
The second problem is that the parameter is added with the type 'GetOrPost'. From my point of view I think that this type needs to be set to 'QueryString'.

To work around these two problems I've created my own 'OAuth2UriQueryParameterAuthenticator' class. This is the source code for my class:

```csharp
  /// <summary>
  /// The OAuth 2 authenticator using URI query parameter.
  /// </summary>
  /// <remarks>
  /// Based on http://tools.ietf.org/html/draft-ietf-oauth-v2-10#section-5.1.2
  /// </remarks>
  internal class OAuth2UriQueryParameterAuthenticator2 : OAuth2Authenticator
  {

    private readonly string _tokenName = "oauth_token";

    /// <summary>
    /// Initializes a new instance of the 'OAuth2UriQueryParameterAuthenticator2' class.
    /// </summary>
    /// <param name="accessToken">The access token.</param>
    public OAuth2UriQueryParameterAuthenticator2(string accessToken)
      : base(accessToken)
    {
    }

    /// <summary>
    /// This function adds the authentication information to the request parameter list
    /// </summary>
    /// <param name="client"></param>
    /// <param name="request"></param>
    public override void Authenticate(IRestClient client, IRestRequest request)
    {
      bool found = false;

      //
      foreach (Parameter p in request.Parameters)
      {
        if (p.Name.Equals(_tokenName, StringComparison.OrdinalIgnoreCase))
        {
          found = true;
          break;
        }
      }

      if (!found)
      {
        request.AddParameter(_tokenName, AccessToken, ParameterType.QueryString);
      }
    }

  }
```

**Comment by alexeyzimarev** [comment]
I agree about the first part. It is easy to fix by removing the check alltogether (it was creating issues for Jwt, for example) and use `AddOrUpdateParameter` instead.

About the second issue, I don't think there's one. As [mentioned](http://restsharp.org/usage/parameters.html#get-or-post) in the docs:

> This behaves differently based on the method. If you execute a GET call, RestSharp will append the parameters to the Url in the form url?name1=value1&name2=value2.

I don't think query parameters are even relevant for POST requests, so adding the token to the form seems correct, unless there's some documentation or standard that says that we shouldn't be doing that.

**Comment by alexeyzimarev** [comment]
Ok, I changed the code to use `AddOrUpdateParameter` so if there was an issue, it should be resolved.
