### ISSUE TITLE
Issue with GetMethod with Body request - RestSharp (DotnetCore 2.2)

### ISSUE THREAD

**Issue by ramgkn** [restsharp/RestSharp#1399]
Hi Team,

can you help me here, what i am doing wrong - i am getting an error as bad request for Get method with body.

var client = new RestClient("http://abc-api-cma-cais-cis-uk-cma-dev.apps.appcanvas.net/cais?Display=All");
                client.Timeout = -1;
                var request1 = new RestRequest(Method.GET);
                request1.AddHeader("Content-Type", "application/json");
                request1.AddHeader("Authorization", "Bearer 111");
                JObject jObjectbody = new JObject();
                jObjectbody.Add("FirstName", "Narayn");
                jObjectbody.Add("LastName", "Kaluri");
                jObjectbody.Add("UserName", "NaraynKaluri");
                jObjectbody.Add("Password", "Password@123");
                jObjectbody.Add("Email", "abc@hotmail.com");

                request1.AddParameter("application/json", jObjectbody, ParameterType.RequestBody);

                IRestResponse response = client.Execute(request1);

                Console.WriteLine(response.Content);

I am getting the below error -  seems like body is no get identified.

{"errors":{"":["A non-empty request body is required."]},"title":"One or more validation errors occurred.","status":400,"traceId":"0HLSKFCCSHR42:00000001"}

**Comment by ramgkn** [comment]
Additionally... adding as a AddJsonBody is also giving me the same error... unfortunately.

**Comment by alexeyzimarev** [comment]
You suppose to send a proper typed object as a parameter, not some sort of `JObject`.

It is described in the docs, let us know if you have any questions.

http://restsharp.org/usage/parameters.html#request-body

**Comment by ramgkn** [comment]
I followed the suggestions recommended by you with "proper typed object as a parameter" with the same issue that 

{"errors":{"":["A non-empty request body is required."]},"title":"One or more validation errors occurred.","status":400,"traceId":"0HLSKFCCSHR42:00000001"}

Interestingly when i updated RestSharp to 16.10.1, i am getting a different message the GET method does not support body.

var request1 = new RestRequest(Method.GET);
request1.AddHeader("Content-Type", "application/json");
request1.AddHeader("Authorization", "Bearer 111");


    var test = new SearchRequest()
        {
            ABC= "1253",
    EFG = "5254",
    Name = new SearchRequestName()
    {
        Title = "",
        Forename = "",
        Mid_Initial = "",
        Surname = "",
        Suffix = ""
    },
    Dob = "",
    Address = new SearchRequestAddress()
    {
        Sub_Bld_Name = "",
        House_Name = "",
        House_Nb = "",
        Street = "",
        District = "",
        Town = "",
        County = "",
        Postcode = ""
    }
};


         request.RequestFormat = DataFormat.Json;

            var SerializedJsonBody = JsonConvert.SerializeObject(requestBody);

            request.AddJsonBody(requestBody);

Could you please help us here.

To my understanding Resharp support "httpclient", please correct me if i am wrong.

Your assistance would be appreciated.
