### ISSUE TITLE
106.10.0 doesn't authenticate oauth 1.0a (one leg) anymore (106.9.0 is fine)

### ISSUE THREAD

**Issue by mhwlng** [restsharp/RestSharp#1400]
## Expected Behavior

oauth 1.0a (one leg) authentication 

## Actual Behavior

no oauth 1.0a (one leg) authentication

## Steps to Reproduce the Problem

```
client = new RestClient("https://restapi.mailplus.nl/integrationservice-1.1.0")
{
  Authenticator = OAuth1Authenticator.ForProtectedResource(ConsumerKey, ConsumerSecret, null, null),
Proxy = new WebProxy("xxxxxxxxxxx")
  {
    Credentials = CredentialCache.DefaultNetworkCredentials
  }
};
```

## Specifications

with  106.9.0 this works fine
with 106.10.0 the rest server won't authenticate anymore ?

**Comment by alexeyzimarev** [comment]
Are you able to trace the request with both versions and find out what the difference is?

**Comment by alexeyzimarev** [comment]
Found the issue, my bad.
