### ISSUE TITLE
Single Cookie set when Multiple Cookies should be set.

### ISSUE THREAD

**Issue by MrKinauJr** [restsharp/RestSharp#1402]
## Expected Behavior
Array Of Multiple Cookies in response.cookies
## Actual Behavior
Array Of just one Cookie in response.cookies

## Steps to Reproduce the Problem

  1. Make a Request that sets multiple Cookies via one Set-Cookie

## Specifications

  - Version: 106.10.0
  - Platform: Win10

## Informations
`Set-Cookie: __Host-device_id=AQDx4WuRq1Vkh4ER6XAyZCtr4bOg1eiNydb8espt0ivTh8lNUkfUQchpUHFkup6iyibVP_AbRN67VtV1VI-HsvL53glELz_UNbY;Version=1;Path=/;Max-Age=2147483647;Secure;HttpOnly;SameSite=Lax,csrf_token=AQDDJvDRVpQHvqOQswqNJPpQR9MqMJrlApwADKjUPYRSi1M07dSBiINDdGJdPBS_uxXZPRnu7dUAtmY;Version=1;Domain=;Path=/;Secure;SameSite=Lax` is a example. This Leads to only One Cookie set in response.cookies

**Comment by alexeyzimarev** [comment]
Please provide the code example as we request in the contribution guidelines.

**Comment by MrKinauJr** [comment]
`var client = new RestClient("");
            //client.Authenticator = new HttpBasicAuthenticator("username", "password");
            
            client.UserAgent = "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko";

            var request = new RestRequest("");

            request.AddHeader("Pragma", "no-cache");
            request.AddHeader("Accept", "*/*");

            var response = client.Get(request);
            
            Console.WriteLine(response.Headers);
            Console.WriteLine(response.Cookies.Count);

            foreach (var author in response.Headers)
            {
                Console.WriteLine(author.Name);
                Console.WriteLine(author.Value);
            };
            foreach (var author in response.Cookies)
            {
                Console.WriteLine(author.Name);
                Console.WriteLine(author.Value);
            };`

this is my current code.
