### ISSUE TITLE
HTTP 401 "Unauthorized" does not throw an error in GetAsync<>

### ISSUE THREAD

**Issue by adamrkerr** [restsharp/RestSharp#1409]
According to the documentation, the extension methods should throw an error for any response except 200.

> Asynchronous generic methods GetAsync<T>, PostAsync<T> and so on, which aren't a part of IRestClient interface (those methods are extension methods) return Task<T>. It means that there's no IRestResponse to set the response status to error. We decided to throw an exception when such a request fails. It is a trade-off between the API consistency and usability of the library. Usually, you only need the content of RestResponse instance to diagnose issues and most of the time the exception would tell you what's wrong.

Today, we discovered an issue with our NTLM authentication - while there are larger issues with NTLM, this was particularly problematic because the call to GetAsync<> returned an **empty** object, **not null**, instead of throwing an error, upon receiving 401 Unauthorized. The calling program continued on, unaware, until strange errors later in the program alerted us.

I believe the error lies in this code in the RestClientExtensions.cs. Only certain errors trigger the response, and if the error isn't matched, nothing is thrown.

```
        static void ThrowIfError(IRestResponse response)
        {
            var exception = response.ResponseStatus switch
            {
                ResponseStatus.Aborted   => new WebException("Request aborted", response.ErrorException),
                ResponseStatus.Error     => response.ErrorException,
                ResponseStatus.TimedOut  => new TimeoutException("Request timed out", response.ErrorException),
                ResponseStatus.None      => null,
                ResponseStatus.Completed => null,
                _                        => throw response.ErrorException ?? new ArgumentOutOfRangeException()
            };

            if (exception != null)
                throw exception;
        }
```

**Comment by alexeyzimarev** [comment]
Clearly, if the exception is not matching, it throws ArgumentOutOfRange. It doesn’t throw only if the result is None or Conpleted. What makes you think that it doesn’t thrown? For me it looks like we have two issues. First, 401 for some reason results in Completed or None. Second, ArgumeotOutOfRange is not a good idea, very misleading. Can you try using EcecureAsync instead and check the ErrorException and RwaponseStatus if the returned response? It would help a lot.

**Comment by adamrkerr** [comment]
What makes me think that it wasn't thrown?

1. The entire call was inside a `try/catch` block, with logging in the `catch` section, but nothing was "caught"
2. Directly after the call was a check for a null result, and that passed (response was not null)
3. However, every property of the object was empty
4. We found the 401 in our http logs

When I did switch to using ExecuteAsync and ResponseStatus, then it would return a status of "Unauthorized".

**Comment by alexeyzimarev** [comment]
I meant that the code snippet you provided has no sign of an unlisted exception to be swallowed. That was my question, I thought you saw something that I missed.

The status code seems to be correctly set. So, it is quite easy to add a missing case to the exception handler.
