### ISSUE TITLE
Having trouble adding parameters for Request Method Patch

### ISSUE THREAD

**Issue by varnk** [restsharp/RestSharp#1413]
Trying to execute a rest call using Patch method.  The call also has parameters that I am trying to add with AddJsonBody.  However, AddJsonBody sets the Content-Type to "**applicaiton/json**".  How do I set the content type to be "a**pplicaiton/json-patch**" as indicated in the error message that I get in the response (See below)?

`{"$id":"1","innerException":null,"message":"The request indicated a Content-Type of \"application/json\" for method type \"PATCH\" which is not supported. Valid content types for this method are: application/json-patch+json.","typeName":"Microsoft.VisualStudio.Services.WebApi.VssRequestContentTypeNotSupportedException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"VssRequestContentTypeNotSupportedException","errorCode":0,"eventId":3000}`

**Comment by alexeyzimarev** [comment]
I am not sure I understand. You are trying to send JSON as a payload but you don't want to set content type tp `application/json`? What content type do you want then?

**Comment by varnk** [comment]
> I am not sure I understand. You are trying to send JSON as a payload but you don't want to set content type to `application/json`? What content type do you want then?

I am basing my determination of the REST required content type based on the exception that was thrown when I just used **application/json**.  The exception states that the valid content-type for PATCH should be **application/json-patch+json**.  See the original post containing the exception.

**Comment by alexeyzimarev** [comment]
I see, thanks for the info. Interesting is that it was never reported before...

As a workaround, you can add the content type right after adding JSON body using the `AddHeader`.

It seems our serializers need to be extended to support different content types based on the HTTP method...

**Comment by varnk** [comment]
> I see, thanks for the info. Interesting is that it was never reported before...
> 
> As a workaround, you can add the content type right after adding JSON body using the `AddHeader`.
> 
> It seems our serializers need to be extended to support different content types based on the HTTP method...

Not quite sure how to do that.  Could you provide an example?  

I tried this, but it's not working, probably because I'm doing it wrong:

```
IRestRequest request = MyNewRestRequest();
dynamic qObj = new ExpandoObject();
qObj.op = "add";
qObj.path = "title";
qObj.value = "My Title";

request.AddJsonBody(pObj);
request.AddHeader("Content-Type", "application/json-patch+json");
```

**Comment by alexeyzimarev** [comment]
It might be because we override the content type. I need to check the code.

**Comment by alexeyzimarev** [comment]
It might be that you can get it to work by using

```csharp
request.AddParameter(new JsonParameter("application/json-patch+json", pObj));
```

Could you try it out?

**Comment by varnk** [comment]
Tried it.  It didn't work.  I still get the same exception.  The request somehow still uses a content-type of  "application/json"  I think your example only sets the name of the parameter, not the content-type.

**Comment by alexeyzimarev** [comment]
Yeah, that might be the case. It _should_ definitely work, by doing it almost by hand:

```csharp
request.AddParameter(new Parameter("", pObj, "application/json-patch+json", ParameterType.RequestBody));
```

**Comment by varnk** [comment]
Hmmm... Something still seems to be wrong.  When I tried your example I got a different exception:

`{"$id":"1","innerException":null,"message":"The request indicated a Content-Type of \"\" for method type \"PATCH\" which is not supported. Valid content types for this method are: application/json-patch+json.","typeName":"Microsoft.VisualStudio.Services.WebApi.VssRequestContentTypeNotSupportedException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"VssRequestContentTypeNotSupportedException","errorCode":0,"eventId":3000}`

**Comment by alexeyzimarev** [comment]
So, it means the value of the `name` parameter is being used for the content type. I know there's some weirdness there. If you replace the first parameter in the constructor call from an empty string to `application/json-patch+json`, it should work. I made some changes locally that would allow specifying a custom content type for JSON body parameter when calling `AddJsonBody` . But I am not very convinced that it's the best solution.

**Comment by varnk** [comment]
Well, it looks like it may almost be working, but still not quite.  Now I am getting this exception:

`{"$id":"1","innerException":null,"message":"You must pass a valid patch document in the body of the request.","typeName":"Microsoft.VisualStudio.Services.Common.VssPropertyValidationException, Microsoft.VisualStudio.Services.Common, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"VssPropertyValidationException","errorCode":0,"eventId":3000}`

Seems like the JSON body may not be getting rendered in the proper format for PATCH.

**Comment by alexeyzimarev** [comment]
Well, now you need to check if you are sending the correct patch document.

**Comment by varnk** [comment]
I am not sure if the parameters are being serialized in the correct format for the patch document.   Isn't that a function of the RestSharp library?   Just as an FYI, I am calling Create Work Item TFS REST API as referenced in the link below:  
https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/wit/work-items?view=tfs-2015#create-a-work-item

**Comment by alexeyzimarev** [comment]
@varnk well, I was trying to help but I think it's time for you to do some debugging. Run Fiddler, check the request body and ensure that it is what your server wants.

**Comment by varnk** [comment]
I appreciate the help.  Maybe I made too many assumptions on how RestSharp would serialize parameters based on the post method.  I am not an expert on REST and JSON formatting, but I'll try to see if I can figure out what is going on and post an update when I can gather more info.

**Comment by alexeyzimarev** [comment]
RestSharp will serialize your request. But it's you who controls the object model to be serialized and it must match with what the server expects.

If you make this call:

```csharp
var response = await client.ExecutePostAsync(request);
```
then you'll get an instance of `IRestResponse` and there you can find the `Request` property that contains your original request and also the `Body` property that will contain the serialized body. You can check the content of the body to see if it matches with what you expect to send.

**Comment by varnk** [comment]
OK.  I think I finally got it working.  I'll post my solution for the benefit of anyone else who may need to do this.  I think the problem was that I assumed that RestSharp would format the body content according to the RequestMethod, but that does not seem to be the case after looking under the hood at the code.

Instead, I used the Newtonsoft.Json.JsonConvert class on the parameters (which consists of an IList) as follows:

```
IRestRequest request = MyNewRestRequest();
IList<object> parameters = new List<object>();
dynamic qObj = new ExpandoObject();
qObj.op = "add";
qObj.path = "title";
qObj.value = "My Title";
parameters.Add(pObj);
string content = JsonConvert.SerializeObject(parameters, Formatting.Indented);
Parameter bodyParam = new Parameter("application/json-patch+json", content, "application/json-patch+json", ParameterType.RequestBody);
request.AddParameter(bodyParam);

```
After doing this, the body was formatted correctly and the REST call was able to complete successfully.  Yay!

**Comment by alexeyzimarev** [comment]
I am not sure I understand what was the issue. Are you able to post the request body for the “normal” request and for the “fixed” request?

**Comment by varnk** [comment]
Not sure what you mean by "normal" request.  If you mean trying to use AddJsonBody, then no, I could not get it to work calling AddJsonBody.  I had to use the "fixed" method shown above with AddParameter.   It would appear that AddJsonBody sets the content-type to ""application/json" which does not work for method-type of PATCH (at least in the case of the REST API that I was calling). 

I think some of the issue was on me making incorrect assumptions on how the parameters would get serialized when using method-type of PATCH.  I assumed that the content-type would get set according to the method-type.  Also, I assumed that the collection list would get serialized in the format that matched PATCH.  

I also found a link describes the formatting for PATCH.  https://apisyouwonthate.com/blog/put-vs-patch-vs-json-patch

**Comment by alexeyzimarev** [comment]
It would help if you can compare the request body you made with your initial code and with the current (working) code. That would greatly help to understand the underlying request formatting issue and allow me to address it.

**Comment by varnk** [comment]
OK, got it!  

The working request body is shown below using AddParameter:

```
-		Body	{RestSharp.RequestBody}	RestSharp.RequestBody
		ContentType	"application/json-patch+json"	string
		Name	"application/json-patch+json"	string
		Value	"[\r\n  {\r\n    \"op\": \"add\",\r\n    \"path\": \"/fields/System.Title\",\r\n    \"value\": \"Sample Test Case 1\"\r\n  }\r\n]"	object {string}

```

The non-working request body is shown below using AddJsonBody:

```
-		Body	{RestSharp.RequestBody}	RestSharp.RequestBody
		ContentType	"application/json"	string
		Name	"application/json"	string
		Value	"[{\"op\":\"add\",\"path\":\"/fields/System.Title\",\"value\":\"Sample Test Case 1\"}]"	object {string}

```

The issue may just be with not being able to set ContentType with AddJsonBody or possibly with AddJsonBody using the content-type of "application/json-patch+json" if the method is PATCH.    I am not sure which would make the most sense.  

It appears that the collection serialization is being done correctly using either AddParameter (with content serialized using JsonConvert) or AddJsonBody (aside from newlines).  So, maybe it is just the content-type that is the issue.

**Comment by alexeyzimarev** [comment]
So, basically the body itself is the same. We just don't specify the correct content type.

**Comment by varnk** [comment]
Yeah, unless JSON requires newlines, which I don't think that it does.

**Comment by alexeyzimarev** [comment]
This will be in the next version:

```csharp
        IRestRequest AddJsonBody(object obj, string contentType);
```

**Comment by alexeyzimarev** [comment]
Closing because of the latest release.
