### ISSUE TITLE
PostAsync without return value

### ISSUE THREAD

**Issue by codemunkie15** [restsharp/RestSharp#1417]
How do we do an async post request that doesn't return any value? There is a PostAsync extension method but it returns a generic. Is there an extension method that returns an empty task?

Thanks

**Comment by alexeyzimarev** [comment]
Won't this overload work for you?

```csharp
Task<IRestResponse> ExecutePostAsync(IRestRequest request, CancellationToken cancellationToken = default);
```

**Comment by codemunkie15** [comment]
Didn't see that overload, that will work nicely.

Many thanks
