### ISSUE TITLE
Get generic result from request

### ISSUE THREAD

**Issue by WashingtonARamos** [restsharp/RestSharp#1424]
I have an endpoint in my API that may return either a List<T> or a generic response that all endpoints may send when errors occur. The generic response is defined as:

```
{
    "Message" : "Message of the error",
    "Code": 0
}
```

So, the base Dto is:

```
public class BaseDto {
    public string Message { get; set; }
    public int Code { get; set; }
}
```

This way, for every other endpoint that have a return type T, I can make T inherit from BaseDto and have those properties deserialized. But I can't make List<T> inherit from BaseDto, which is where my problem lies. I would like to know if there's a way to have have Response.Data being deserialized to something else when an error code is returned (if succesful, deserialize using one type, else deserialize using some other type), or to have an `object` which contains all the data from the response.

**Comment by alexeyzimarev** [comment]
So, why can't you do like `GetAsync<List<BaseDto>>(...)`?

**Comment by WashingtonARamos** [comment]
> 
> 
> So, why can't you do like `GetAsync<List<BaseDto>>(...)`?

Because the endpoint's response is either a `SomeType`, `List<SomeOtherType>` or a `BaseDto`, which happens when something wrong happened (user not logged in, user doesn't have permission, etc). When it's a `List<SomeType>` (like `GetAllRecipes`) it returns a JSON Array, like so: `[ "Pizza", "Sandwich" ], but when a non-collection type (like `GetRecipeDetails`) it returns a flat JSON object, like so: `{ "Name": "Pizza", "Price" : 1.00 }`. I can make a `RecipeDetailsDto.cs` class extend `BaseDto.cs`, which gives me the ability to check if `IRestResponse.Data.Message` is null or not. Should `IRestResponse.Data.Message` be null, it means no errors occured and I can proceed whatever the user wanted to do, but I can't make a `List<SomeType>` extend `BaseDto.cs`.

I actually "fixed" it by creating an extension method that takes `IRestResponse.Content` and tries to deserialize it into a `BaseDto` then returns it which works fine for my case, so I'm not sure if this is overengineering or useless to the general population or if I should re-engineer my API so I don't need these things.

**Comment by alexeyzimarev** [comment]
We do have a generic overload too (https://github.com/restsharp/RestSharp/blob/master/src/RestSharp/RestClientExtensions.cs#L19), or untyped overload (`ExecuteAsync(request, cancellationToken)`).

The first one will return a dynamic, the second one will return the raw content and you can handle deserialisation yourself.
