### ISSUE TITLE
AddDefaultHeader differs in semantic from AddDefaultHeaders

### ISSUE THREAD

**Issue by hacst** [restsharp/RestSharp#1426]
## Expected Behavior
Plural AddDefaultHeaders function should have the same semantics as calling singular AddDefaultHeader function on all elements of the collection

## Actual Behavior
Singular only adds, plural adds or updates.

See underlying calls for plural: https://github.com/restsharp/RestSharp/blob/e8a51d2f92d9609198761cf865ec21d9f20bd1d8/src/RestSharp/RestClientExtensions.cs#L381
and singular:
https://github.com/restsharp/RestSharp/blob/e8a51d2f92d9609198761cf865ec21d9f20bd1d8/src/RestSharp/RestClientExtensions.cs#L339

This functional difference is unexpected and undocumented. It leads to artifacts in code where the plural function is used for single header entries just to get the other semantics and "fixing" that leads to bugs.

Ideally either both functions should have add or update semantics or another set of convenience functions for that (e.g. AddOrUpdateDefaultHeader(s)) should be added.

**Comment by alexeyzimarev** [comment]
Thanks for reporting. It might be a bug.

**Comment by hacst** [comment]
@alexeyzimarev Any update on this? Or was there actually a won't fix decision?

**Comment by alexeyzimarev** [comment]
@hacst I agree it's a bug but I don't have immediate plans doing a fix. It's an open-source project, so feel free to contribute.

**Comment by hacst** [comment]
@alexeyzimarev Fair enough. Though from the outside it is hard for me to know what kind of fix maintainers would prefer.

Would making `AddDefaultHeaders` behave the same as `AddDefaultHeader` and adding `AddOrUpdateDefaultHeader`/`AddOrUpdateDefaultHeaders` functions be acceptable? It would be a breaking change for people now relying on the "broken" semantics of `AddDefaultHeaders`.
