### ISSUE TITLE
With multipart/form-data When using addjsonbody(), the body is empty.

### ISSUE THREAD

**Issue by namilkimfree** [restsharp/RestSharp#1427]
## Expected Behavior

With multipart/form-data When using addjsonbody() and addfile(), the body should be filled.

## Actual Behavior

With multipart/form-data When using addjsonbody() and addfile(), the body is empty.

but below code is not fail

`Request.AddParameter("test", JsonConvert.SerializeObject(myobject), "application/json", ParameterType.RequestBody);`

## Steps to Reproduce the Problem

  1. Request.AddHeader("content-Type", "multipart/form-data");
  2. RequestFormat = DataFormat.Json;
  3. Request.AddJsonBody(myobject);  ->  myobject parameter name set -> "test"
  4. Request.AddFile("file",byte[],"test.jpg");
  5. IRestResponse rs = client.Execute(Request);

## Specifications

  - Version: 106.10.0
  - Platform: Dotnet Core , OS: Windows 10
  - Subsystem: 

## StackTrace
<details>

```
Required request part 'test' is not present.
```

</details>

**Comment by alexeyzimarev** [comment]
I think it's by design. Sending JSON in a multipart form data is nothing that is defined by the standard. If you are sending a multipart form, you cannot send a regular body. That's why people usually use the form POST to send additional data together with the file.

**Comment by alexeyzimarev** [comment]
https://phil.tech/api/2016/01/04/http-rest-api-file-uploads/

**Comment by namilkimfree** [comment]
@alexeyzimarev  
Thank you.  I will this issue close.
