### ISSUE TITLE
RestSharp Could not install

### ISSUE THREAD

**Issue by pedrogfx** [restsharp/RestSharp#1428]
i'm doing a ETL process and i need do extract a web api (Konviva) by SSIS, i only tried by the RestSharp (C#).

**RestSharp** but i had a error when i install him:
>Could not install package 'RestSharp 106.10.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"

Im already checked the Framework version and is the Framework 4.7 (Windows 10)

That is the script what im trying to use:
```
var client = new RestClient("http://xxxxxxxxxx.com/action/api/course");
client.Timeout = -1;
var request = new RestRequest(Method.GET);
request.AddHeader("Authorization", "password");
request.AddHeader("Content-Type", "application/json");
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);```

**Comment by alexeyzimarev** [comment]
Sorry but we support 4.5.2 and above, or .NET Standard 2 and above.

It doesn't matter what version of .NET Framework is installed on your machine, if you project target framework is 4.5 - that's what it builds to.
