### ISSUE TITLE
How to OutputRows in SSIS

### ISSUE THREAD

**Issue by pedrogfx** [restsharp/RestSharp#1429]
Hey, im doing a ETL Process, extracting from a API, but i dont know how i do to output the rows;
Thats my code, but i dont know how to do a "FOREACH" to return.

>          
           var client = new RestClient("http://xxxxxxxxxxxxxxxx/action/api/getCursos");
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            request.AddHeader("Authorization", "KONVIVA xxxxxxxxxxxxxxxxxxxx");
            request.AddHeader("Content-Type", "application/json");
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);

i have a list like
cod_course
cod_user
cod_employee
 i need to return all the information from that

**Comment by alexeyzimarev** [comment]
Sorry, but we explicitly ask not to use issues for questions.
