### ISSUE TITLE
Trying to use HttpResponseMessage as a response will get an empty HttpResponseMessage.Content

### ISSUE THREAD

**Issue by MoathAlrefai** [restsharp/RestSharp#1430]
Dears,

We are trying to use RestSharp into our projects instead of using HttpClient directly. In one of our case, we expect the type of the response is HttpResponseMessage, and from this response, we use the HttpResponseMessage.Content to complete our logic (we do this by running response.Content.ReadAsStringAsync().Result). This logic is working properly by using httpClient, while in RestSharp we noticed the HttpResponseMessage.Content is empty.

Here is the code:

`var client = new RestClient(url);`
`IRestResponse<HttpResponseMessage> response = client.Execute<HttpResponseMessage>(request);`
`HttpResponseMessage httpResponse = response.Data;`
`string content = httpResponse.Content.ReadAsStringAsync().Result;`

Please advise what should I do to overcome this issue. In addition, we do not need to use the IRestResponse.Content, as we send the HttpResponseMessage to different areas in the code and we do not need to change the logic.
We are using RestSharp version 106.10.0

**Comment by alexeyzimarev** [comment]
You don't need to use the typed `Execute` method, use the non-generic overload and you will get what you need.

```csharp
var response = await client.ExecuteAsync(request, cancellationToken);
```

Then, you get the raw content in the response.

**Comment by MoathAlrefai** [comment]
Hi,
The proposed method (ExecuteAsync) returns IRestResponse. But in my case, I need the HttpResponseMessage to be the response type, is this doable by RestSharp or not!!

**Comment by alexeyzimarev** [comment]
No, it's not possible.
