### ISSUE TITLE
Files with dot in name only uploading value before dot

### ISSUE THREAD

**Issue by fraher** [restsharp/RestSharp#1434]
## Expected Behavior

Add a file with the name "Testing.123.ext" should be passed as "Testing.123.ext" when the file has been added using AddFileBytes. Similar to if the file was added using AddFile.

## Actual Behavior

The file and content are being passed during the call, but the filename only shows "Testing.ext".

## Steps to Reproduce the Problem

  1. Create a byte array and fill it with the results from a File.ReadAllBytes method call.

RestRequest request = RestRequest request = new RestRequest(Method.POST);
... add all headers

  2. Create a RestRequest object and add the bytes using .AddFileBytes
byte[] file = File.ReadAllBytes(<path to file>);
request.AddFileBytes("collection", file, "Testing.123", "multipart/form-data");

  3. Execute the API call

## Specifications

  - Version: 106.6.10
  - Platform: .NET Core 2.2, C#

## Workaround
I ended up using request.AddFile(...). This worked for my case.

</details>

**Comment by alexeyzimarev** [comment]
Actually, `AddFile` and `AddFileBytes` have the same code when it comes to the file name.
