### ISSUE TITLE
ErroMessage property on IRestResponse is duplicated

### ISSUE THREAD

**Issue by mlevinmail** [restsharp/RestSharp#1435]
When no connection could be established the ErrorMessage property on IRestResponse is duplicated.

The exact message is the following:

No connection could be made because the target machine actively refused it. No connection could be made because the target machine actively refused it.

  - Version: 106.6.10

**Comment by alexeyzimarev** [comment]
We just pass it throgh: https://github.com/restsharp/RestSharp/blob/92ad955adb8032d4306cf7cceb1ea1b93eead67d/src/RestSharp/RestClient.Sync.cs#L138

You can tell the client to throw instead and look at the exception yourself:

```csharp
client.ThrowOnAnyError = true;
```
