### ISSUE TITLE
a bug in interface IHttp.Headers.Add

### ISSUE THREAD

**Issue by MrSong0607** [restsharp/RestSharp#1436]
## Expected Behavior
add a header value in OnBeforeRequest

## Actual Behavior
this function will add a comma: "," to header value position, if there already have a same header, it will be ok,but if there have no header that same key with one to be added, there will have a unnecessary  comma 

## Steps to Reproduce the Problem

  1. create a new  RestRequest named "req"
  2. set action value named "middle" to  OnBeforeRequest of req
  3. in the "middle" function, do this : param.Headers.Add(new HttpHeader{Name="aaa",Value=""})

## Specifications

  - Version: 106.10.1
  - Platform: netstandard2.1
  - Subsystem: windows 10

## Code
<details>

```
            var req = new RestRequest("test.com", Method.POST);
           req.OnBeforeRequest = r =>
            {
                r.Headers.Add(new HttpHeader { Name = "aaa", Value = $"bbb" });
            };
```

</details>

## Http Header
<details>
```
aaa: , bbb
```
</details>

**Comment by alexeyzimarev** [comment]
Nope, it doesn't happen. I am sure your code is different somewhere since you use string interpolation for the value but in your snippet, it's a constant string. I wrote a test with the same code and it passes.
