### ISSUE TITLE
POST request with GZIPPED json not working with request.AddJsonBody

### ISSUE THREAD

**Issue by driekus77** [restsharp/RestSharp#1438]
## Expected Behavior

GZIP Compression with POST working in combination with request.AddJsonBody.

## Actual Behavior

Get a Gateway timeout when using request.AddJsonBody in combination with Content-Encoding: gzip.

Works when I gzip the serialized json myself and post it. (See beneath code).

### This code is working:
```csharp
	...
	IRestResponse restResponse;

	var dataStream = new MemoryStream();

	using (var zipStream = new GZipStream(dataStream, CompressionMode.Compress))
	using (var writer = new StreamWriter(zipStream))
	{
	    writer.Write(serializedBody);
	}

	var compressedBytes = dataStream.ToArray();

	request.AddHeader("Content-Encoding", "gzip");
	request.AddHeader("Content-Type", "application/json");
	request.AddParameter("application/x-gzip", compressedBytes, ParameterType.RequestBody);

	restResponse = client.Post(request);
	...
```

Fiddler's raw request header:
```
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: RestSharp/106.0.0.0
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Content-Encoding: gzip
Content-Type: application/json
Content-Length: 524946
```

and raw response header:
```
HTTP/1.1 200 OK
x-powered-by: Express
x-request-id: k7wm6l5h
x-frame-options: SAMEORIGIN
content-type: application/json; charset=utf-8
etag: W/"xxx-xxx"
date: Wed, 18 Mar 2020 00:55:36 GMT
connection: close
vary: Accept-Encoding
content-encoding: gzip
set-cookie: JSESSIONID=xxx; Path=/; HttpOnly; Secure
transfer-encoding: chunked
```

### This code is NOT working:
```csharp
	...
    request.JsonSerializer = JsonResultSerializer;

    // Note: When I comment beneath line out it works as normal. (But without compression...)
    request.AddHeader("Content-Encoding", "gzip"); 

    request.AddJsonBody(vergoedingSetQueue);

   	restResponse = client.Post(request);
	...    
```

Fiddler's raw request header:
```
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: RestSharp/106.0.0.0
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Content-Encoding: gzip
Content-Type: application/json
Content-Length: 8581208

NOTE: JSon shows up hier...!
```

Raw response header:
```
HTTP/1.1 504 Gateway Timeout
x-powered-by: SAP Application Controller
x-request-id: xxx
x-frame-options: SAMEORIGIN
cache-control: no-cache, no-store, must-revalidate
set-cookie: JSESSIONID=xxx; Path=/; HttpOnly; Secure
date: Wed, 18 Mar 2020 01:08:05 GMT
connection: close
transfer-encoding: chunked

f
Gateway Timeout
0
```

## Specifications

  - Version:  RestSharp 106.10.1
  - Platform:   Windows 10(Client) with dotnet core 2.2
  - Subsystem:  Server side is SAP XSA with Node JS Expressjs service

**Comment by alexeyzimarev** [comment]
RestSharp wasn't designed to compress the payload. `AddJsonBody` just instructs the `RestClient` to call an appropriate serializer and also set the correct content type.

So, it is not a bug and there's no word in the docs that give a clue that it would compress the payload based on the content type set in the header.

It can be done very easily by creating a custom serializer https://restsharp.dev/usage/serialization.html#custom

So, I can mark it up for grabs, if you are willing to contribute.

**Comment by driekus77** [comment]
Thank you for quick response!

Ah me not reading & interpreting the docs oke: Sorry.

Can try to make a PR for this with a GZipSerializer that can be decorated with an JSonSerializer.

For the time being as an optional class to be set if wanted?

**Comment by driekus77** [comment]
Looked at the code and found out that its not a trivial task to introduce Compression using the IRestSerializer/ISerializer/IDeserializer interface(s). 
In order not to break anything either these Interfaces must be extended using 
```csharp
byte[] Serialize(object payload); //  in stead of string. 
// or
void Serialize(Stream stream); 
```
Or introduce a new Interface for e.g. "RestSharp.Sinks" with an Interface that supports Stream and/or byte[].

So extend existing Interfaces or add a new one?
What do we prefer?

Kind regards

**Comment by alexeyzimarev** [comment]
I would prefer that serializers will use byte arrays but it will be a breaking change, so I'll have to merge it after the last minor release of v106 so we can take it in to v107.

**Comment by driekus77** [comment]
Oke I will give it a go.

Thanks for replying quickly!
