### ISSUE TITLE
Feature request: NegotiateAuthenticator - Update documentation

### ISSUE THREAD

**Issue by scholtz** [restsharp/RestSharp#1439]
## Expected Behavior

I expect all standard authorization methods to be implemented in RestSharp.

## Actual Behavior

RestSharp is missing negotiate protocol.

## Steps to Reproduce the Problem

```c#
                var client = new RestClient("https://service.mydomain.com");
                // client.Authenticator = new RestSharp.Authenticators.NegotiateAuthenticator();
                var request = new RestRequest($"WeatherForecast", Method.GET, DataFormat.Json);
                var response = client.Execute(request);
                Assert.AreEqual(System.Net.HttpStatusCode.OK, response.StatusCode);
```
Currently returns 401.

## Specifications

Any service which supports negotiate protocol.

## Other solutions works

```c#
                var cl = new System.Net.WebClient();
                cl.UseDefaultCredentials = true;
                var str = cl.DownloadString("https://service.mydomain.com/WeatherForecast");
```
returns weather forecast for user where app is running

The service I have tested this used [linux docker container](https://stackoverflow.com/questions/60296237/windows-authentication-in-linux-docker-container), and authenticates with browser successfully. The client i have tested it was simple console application in docker.

For me this is stopshower for restsharp, and will have to manage all connections by WebClient :(

**Comment by alexeyzimarev** [comment]
`request.UseDefaultCredentials = true`, why is it missing?

**Comment by scholtz** [comment]
Hi @alexeyzimarev thanks.. Thats it :) I confirm it works.

👍 

Now task should be changed to update documentation : http://restsharp.org/usage/authenticators.html

**Comment by alexeyzimarev** [comment]
I guess the `NtmlAuthenticator` would work too

https://github.com/restsharp/RestSharp/blob/master/src/RestSharp/Authenticators/NtlmAuthenticator.cs

**Comment by alexeyzimarev** [comment]
@scholtz do you want to help to update the docs?
