### ISSUE TITLE
JsonPropertyAttribute doesn't work with JsonNetSerializer used

### ISSUE THREAD

**Issue by VitaliiIsaenko** [restsharp/RestSharp#1442]
## Expected Behavior
`JsonPropertyAttribute` changes the serialized property name
## Actual Behavior
`JsonPropertyAttribute` doesn't make a difference to the serialized property name

## Steps to Reproduce the Problem
  1. Create new `RestClient`
  2. Use serializer `JsonNetSerializer`
  3. Set `[JsonProperty("HRB")]` attribute over `public string HRB {get;set;}` property
  4. Check out request body - there will be `hrb` field name instead of `HRB`

## Specifications

  - Version: 106.10.1
  - Platform: Linux
  - Subsystem:

## Code
```
public class Company 
{
    [JsonProperty("HRB")]
    // [SerializeAs(Name="HRB")]
    // [DeserializeAs(Name="HRB")]
    public string HRB {get;set;}
}

public class Test 
{
    [Fact]
    public void Test() 
    {
        var client = new RestClient("sampleapi.com");
        // client.UseNewtonsoftJson(); 
        client.UseSerializer(() => new JsonNetSerializer());
        var request = new RestRequest("/companies/", Method.POST);
        request.AddJsonBody(requestPostAdd);
        var response = client.Post(request);
    } // <-- breakpoint here, checking what is in Body property of the request
}
```

**Comment by alexeyzimarev** [comment]
It is not a bug. `JsonProperty` has nothing to do with casing. Check Json.Net settings https://www.newtonsoft.com/json/help/html/SerializationSettings.htm
Make it work without RestSharp first, then tell RestSharp what settings to use. The default settings are documented.
