### ISSUE TITLE
JsonDeserializer doesn't deserialize all properties

### ISSUE THREAD

**Issue by emanuelefirmani** [restsharp/RestSharp#1444]
## Expected Behavior
All properties should be deserialized.

## Actual Behavior
Customer.Number is not correctly filled

## Steps to Reproduce the Problem
Run code as in https://gist.github.com/emanuelefirmani/54065e631312d30da61386ebcd96306a
Project must reference Netwonsoft and RestSharp

## Specifications

  - Version: 106.10.2-alpha.0.8
  - Platform:Windows 10
  - Subsystem: VS2019

## StackTrace
No error is thrown. Simply Customer.Number is null
</details>

**Comment by alexeyzimarev** [comment]
Since there's no code for the model class provided in the gist, I tried to figure it out myself and the issue is definitely in the `Data` class. With the `Number` property properly decorated for SimpleJson, it works just as expected:

```csharp
        public class Data
        {
            [DeserializeAs(Name = "customernumber")]
            public string Number { get; set; }
        }
```

**Comment by emanuelefirmani** [comment]
Here is the code of 
```
    public class FilterBaseModel<T>
    {
        [JsonProperty("panes")]
        public Panes<T> Panes { get; set; }
    }

    public class Panes<T>
    {
        [JsonProperty("filter")] 
        public Filter<T> Filter { get; set; }
    }

    public class Filter<T>
    {
        [JsonProperty("records")]
        public List<Record<T>> Records { get; set; }
    }

    public class Record<T>
    {
        [JsonProperty("data")]
        public T Data { get; set; }
    }
```
