### ISSUE TITLE
'' is not a supported encoding name

### ISSUE THREAD

**Issue by dfbarrios-adl** [restsharp/RestSharp#1447]
Hello! I have an issue about RestSharp implementation. I'm using version 106.6.9.0 on runtime versión v4.0.30319. This is all information wich the stack-trace throw it:

`2020-04-08 17:35:08,060 ERROR CentralSolution.CentralApi.WebApiApplication+<>c System.ArgumentException: '' no es un nombre de codificación admitido. Para obtener información sobre la definición de una codificación personalizada, consulte la documentación del método Encoding.RegisterProvider.
Nombre del parámetro: name
   en System.Globalization.EncodingTable.internalGetCodePageFromName(String name)`

The base error I think is: '' is not a supported encoding name

Could you help me to find a solution, please? This is filling full our logs. Thanks so much!

**Comment by alexeyzimarev** [comment]
Duplicate #1321 #1358
