### ISSUE TITLE
Content-Type header is not passed exactly as we set it

### ISSUE THREAD

**Issue by lukasz-chmielewski** [restsharp/RestSharp#1448]
Hi guys,

The issue is that we have some API that we want to connect to and it's quite restrictive.
We need to set content-type header exactly this way:
Content-Type=application/json;charset=UTF-8

But restsharp adds space after semicolon and we get:

Content-Type=application/json; charset=UTF-8

Is there any way we can make the call with the exact content-type as expected and set in the request?

Regards,
Łukasz

**Comment by alexeyzimarev** [comment]
It's not RestSharp, it's the `HttpWebRequest`. These headers are restricted so we cannot just set them, we use properties of `HttpWebRequest` instead, like:

https://github.com/restsharp/RestSharp/blob/92ad955adb8032d4306cf7cceb1ea1b93eead67d/src/RestSharp/Http.cs#L78

Unfortunately, it's how it is. I have to say there's nothing wrong with the space character, it's the server issue, although I know it doesn't help you.
