### ISSUE TITLE
Index out of range issue in case of multiple threads (latest version)

### ISSUE THREAD

**Issue by shrey-shah** [restsharp/RestSharp#1449]
In case of multiple concurrent requests, it gives the following error.

`LINE NUMBER : 0***Message = Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
ActualValue =
ParamName = index
Data = System.Collections.ListDictionaryInternal
InnerException =
TargetSite = Void ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
StackTrace =    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
  at System.Collections.Generic.List`1.RemoveAt(Int32 index)
  at System.Collections.Generic.List`1.Remove(T item)
  at RestSharp.RestClientExtensions.AddOrUpdateDefaultParameter(IRestClient restClient, Parameter p)
  at RestSharp.RestClient.AddHandler(String contentType, Func 1 deserializerFactory)`

This issue was consistent in the older version so following this thread, https://github.com/restsharp/RestSharp/issues/951, upgraded it to the latest version. but the issue still exists. 

If I try to make 100 parallel requests, 1 or 2 gets failed with the above error.

**Comment by anoordover** [comment]
Can you check how the AddHandler is called in your code? Is it called by your code?
I think the AddHandler should only be called once for each RestClient that gets created.
I couldn't do a complete investigation so my conclusion that the AddHandler gets called more than once by your own code is incorrect.

**Comment by nitinkhosla79** [comment]
@anoordover No addhandler is called in our code.

**Comment by nitinkhosla79** [comment]
@anoordover Appreciate any thoughts or advice on above?

**Comment by anoordover** [comment]
Can you search in your code for everything you do with the RestClient?
Some methods should be called once for setup of the RestClient.
These methods aren't thread-safe.
Based on your code I can't see how your RestClient instance is used.

**Comment by shrey-shah** [comment]
@anoordover, we have moved the addhandler in constructor and now it is working fine. Thank you so much for your help.

**Comment by shrey-shah** [comment]
Closed
