### ISSUE TITLE
Impossible to access non generic ExecuteAsync method

### ISSUE THREAD

**Issue by franckleveque** [restsharp/RestSharp#1450]
## Expected Behavior
I would like to access the non generic method :
public Task<IRestResponse> ExecuteAsync(IRestRequest request, CancellationToken token = default) (as in RestClient.Async.cs line 148)
But I'm redirected to the generic method which try to deserialize the result.

## Actual Behavior
When I try to use the non generic method ExecuteAsync wit hthe following line
var response = await this.RestClient.ExecuteAsync(request);
I got compilation error :
error CS0411: The type arguments for method 'IRestClient.ExecuteAsync<T>(IRestRequest, CancellationToken)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

Is it possible to hve a working sample for the non generic method usage  as I have different result from a third party endpoint and need to perform deserialization separataly.
## Specifications

  - Version: 106.10.1
  - Platform: .Net Core
  - Subsystem: Ubuntu

**Comment by kditrj2d** [comment]
The method is present on the concrete implementation as stated above, but it is missing from the interface IRestClient.  Is this just a case of simple omission of the method signature on the interface? If so, please add it back to the interface.

**Comment by alexeyzimarev** [comment]
It slipped away. It would be nice if you submit a PR to fix it.

**Comment by alexeyzimarev** [comment]
It's actually right here: https://github.com/restsharp/RestSharp/blob/92ad955adb8032d4306cf7cceb1ea1b93eead67d/src/RestSharp/IRestClient.cs#L264
