### ISSUE TITLE
Restsharp response returning HTML not JSON

### ISSUE THREAD

**Issue by maitevgithub** [restsharp/RestSharp#1453]
Hi,
I successfully make a POST Request with POSTMAN. Now I'm trying to make the same request with RESTSharp. I don't understand why it is returning an HTML for response.Content

Here is my code:
public string recupererDevises(string endpoint, string resource, string cproAccount, string accessToken)
        { 
           //create RestSharp client and POST request object
            var client = new RestClient(endpoint);
            var request = new RestRequest(Method.POST);

            //request headers
            request.RequestFormat = DataFormat.Json;
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Accept", "application/json");
            request.AddHeader("cpro-account", cproAccount);
            
            request.Resource = resource;

            //add parameters and token to request
            request.Parameters.Clear();
            request.AddParameter("Authorization", "Bearer " + accessToken, ParameterType.HttpHeader);

            //make the API request and get a response
            var response = client.Execute(request);
            var content = response.Content;

            return content;
        }

**Comment by alexeyzimarev** [comment]
It's not RestSharp, it's your server. Check the request you make with RestSharp with the request tracking tool like Fiddler and you'd see the difference between your Postman request and RestSharp request.

Also, the HTML you got most probably contains the clue. It's likely an error message from the server.
