### ISSUE TITLE
RESTSharp: return response in JSON Format

### ISSUE THREAD

**Issue by maitevgithub** [restsharp/RestSharp#1454]
Hi all,
I'd like to know how to specify to return the response in JSON Format with RESTSharp?
Thanks in advance!
Cheers

**Comment by alexeyzimarev** [comment]
If you want to force JSON, you can remove the XML content handler:

```csharp
client.RemoveHandler(ContentType.Xml);
```

It will remove the XML content type from the `Accept` headers.

**Comment by alexeyzimarev** [comment]
BTW, there's an extension method `client.UseJson()`
https://restsharp.dev/api/RestSharp.html#method-usejson-restclient
