### ISSUE TITLE
How to add multiple form-data to AddFile

### ISSUE THREAD

**Issue by TripleNico** [restsharp/RestSharp#1455]
So i use the RestSharp AddFile function to upload a Multipart FormData formated image to a webserver. All goes wel but when i want to **update** an existing picture i have to add a extra form-data parameter value to the AddFile function.

Normal upload without updating:
```
Content-Disposition: form-data; name="my-image1"; filename="iphone-white.png"
Content-Type: image/png
```

Code:
```
'Add file
request.AddFile("file", pic.FilePath, "image/png")
```

Upload with update request:
```
Content-Disposition: form-data; name="my-image1"; filename="iphone-white.png"; PictureId="6166"
Content-Type: image/png
```

As you can see this adds the `PictureId="6166"` to the AddFile line. However i cannot find a way to do this with the RestSharp.Addfile function. If i try to add it as a parameter like the code below it's doesn't get updated by the webserver because i think it doesn't expect the value to be there.

```
request.AddParameter("PictureId", pic.UpdateId.ToString)
```

Output:
```
-------------------------------28947758029299
Content-Disposition: form-data; name="PictureId"

6166
-------------------------------28947758029299
Content-Disposition: form-data; name="my-image1"; filename="iphone-white.png"
Content-Type: image/png
```

**Comment by alexeyzimarev** [comment]
That has never been requested before, I guess it must be implemented. PR welcome :)

**Comment by alexeyzimarev** [comment]
As far as I remember, we always used the `name` parameter to send the details about the server-side location of the image, like it's id. We normally use something like a GUID for that purpose. The `fileName` parameter is enough to keep the real filename information intact.

**Comment by TripleNico** [comment]
Hi alexeyzimarev, 

Thanks for your reply. I found a dirty workarround that works for me, i just insert it in the name of the file, like this:

`
request.AddFile($"file""; PictureId=""{pic.UpdateId}", pic.FilePath, strFileContentType)
`

**Comment by alexeyzimarev** [comment]
Isn't it possible to post form body with the data you need _and_ the file? I believe that's how we normally do it.

**Comment by alexeyzimarev** [comment]
What I meant is to use `AddObject`, for example. It should work.

**Comment by kumarc-123** [comment]
I have been facing similar issues. The issue is happening for the first time itself. I have a request  like this for a feedback service.
1. Name - form-data parameter
2. Email - form-data parameter
3. Topic - form-data parameter
4. Details description - form-data parameter
5. **UploadedFile** - The file
6. Uploaded file description - formdata parameter.

                ```
Request.AddParameter(new Parameter("Name", AuthService.UserInfo.GivenName, ParameterType.GetOrPost));
 Request.AddParameter(new Parameter("Email", AuthService.UserInfo.Email, ParameterType.GetOrPost));
 Request.AddParameter(new Parameter("Topic", Topic, ParameterType.GetOrPost));
 Request.AddParameter(new Parameter("Details", Details, ParameterType.GetOrPost));
 Request.AddParameter(new Parameter($"UploadedDescription_0", UploadDescriptions[index], ParameterType.GetOrPost));
Request.AddFile($"UploadedFile_0", File.ReadAllBytes(filePath), fileName, MimeTypesMap.GetMimeType(fileName));
```
I got a response from my API team that the image data is not being sent. 
The request fails every time.
