### ISSUE TITLE
Basic Usage example doesn't work on .NET 4

### ISSUE THREAD

**Issue by rknetwork** [restsharp/RestSharp#1456]
Trying to run a test script using the code provided from Basic Usage example:
```
using RestSharp;
using RestSharp.Authenticators;

var client = new RestClient("https://api.twitter.com/1.1");
client.Authenticator = new HttpBasicAuthenticator("username", "password");

var request = new RestRequest("statuses/home_timeline.json", DataFormat.Json);

var response = client.Get(request);
```
Getting an error: `cannot convert from 'RestSharp.DataFormat' to 'RestSharp.Method'`

Also `IRestResponse` doesn't exist in this code, but the description says: `IRestResponse contains all of the information returned from the remote server. You have access to the headers, content, HTTP status and more.'

Where is `IRestResponse`?

**Comment by alexeyzimarev** [comment]
What version do you use? I have no problems with your snippet. Do you have a repro code?

The constructor for `RestRequest` has two overloads and one of them accepts `DataFormat`, another one needs the `Method`:

```csharp
        public RestRequest(string resource, Method method) : this(resource, method, DataFormat.Xml) { }

        public RestRequest(string resource, DataFormat dataFormat) : this(resource, Method.GET, dataFormat) { }
```

Not sure what your last question is about. The `request.Get` call returns `IRestResponse`.
