### ISSUE TITLE
The type initializer for 'RestSharp.Extensions.StringEncodingExtensions' threw an exception

### ISSUE THREAD

**Issue by AndreasReitberger** [restsharp/RestSharp#1463]
I was using version 106.11.2 for a while with no problems.
Today I updated to 106.11.3. Now I keep getting following exception:

The type initializer for 'RestSharp.Extensions.StringEncodingExtensions' threw an exception.

Simply downgrading to 106.11.2 solves the problem (no code changes on my end).

I actually have all functions in try and catch, however I cannot locate the position where the exception is caused. I asume it's

`var respone = await client.ExecuteAsync(request);`

in my function below:

```
private async Task<string> sendRestAPIRequestAsync(string command, Method method, string jsonDataString = "", Dictionary<string, string> UrlSegments = null)
{
    try
    {
        var client = new RestClient(string.Format("{0}{1}", Protocol, Address));
        var request = new RestRequest("/api/{slug}");

        request.AddHeader("X-Api-Key", API);
        request.RequestFormat = DataFormat.Json;
        request.Method = method;
        request.Timeout = 2500;

        request.AddUrlSegment("slug", command);
        if (UrlSegments != null)
        {
            foreach (KeyValuePair<string, string> pair in UrlSegments)
                request.AddParameter(pair.Key, pair.Value);
        }

        if (!string.IsNullOrEmpty(jsonDataString))
        {
            request.AddParameter("date", jsonDataString, "text/json", ParameterType.QueryString);
        }

        var fullUrl = client.BuildUri(request);

        var respone = await client.ExecuteAsync(request);
        var result = respone.Content;

        return result;
    }
    catch (Exception exc)
    {
        return string.Empty;
    }
}
```

## Expected Behavior
No exception

## Actual Behavior
Thrown exception:
The type initializer for 'RestSharp.Extensions.StringEncodingExtensions' threw an exception.

## Steps to Reproduce the Problem

  1. Update to 106.11.3
  2. Run the code snippet
  3. Downgrade to 106.11.2

## Specifications

  - Version: 106.11.3
  - Platform: Windows 10

Hope the information provided are helpful to you. Otherwise let me know.

**Comment by alexeyzimarev** [comment]
Yeah, it's a bug and it was reported. It is fixed in 106.11.4 patch version, released today.
