### ISSUE TITLE
Send file from C# to rest API using restsharp

### ISSUE THREAD

**Issue by DeveloperM0303** [restsharp/RestSharp#1466]
## Expected Behavior
I have a specific requirement to send file from my C# class library to rest API .
Should be able to send file from C# to rest API using restsharp

## Actual Behavior
used  request.AddFile("00003800", @"C:\Temp\test\00003800.pdf");
No able to send file. Getting BadRequest error
## Steps to Reproduce the Problem

  1.Add request.AddFile()
  2.request.Files.Add()
  3.request.AddFileBytes()
 4. adding file using request.AddParameter();

None of the above methods worked. 

## Specifications

  - Version:106.11.4.0
  - Platform: .net version 4.5.2
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
I am not sure how we can diagnose the issue with so little information. Your server gives you a BadRequest response, I suggest looking for more details in the server logs or anything else that at least can suggest why your server doesn't accept your request.
