### ISSUE TITLE
Handling redirects with auth parameter?

### ISSUE THREAD

**Issue by CasperWSchmidt** [restsharp/RestSharp#1469]
In #414 a possible fix for handling auth parameters on redirects is suggested. The IRestRequest.Credentials property are marked as obsolete however. So I'm wondering how this could/should be handled these days?

**Comment by alexeyzimarev** [comment]
@CasperWSchmidt it's a warning for the future change. The `Credentials` property is only for NTML, not for Basic Auth as far as I remember. In the issue you mentioned, the Auth header is added in addition to setting credentials and you might try even removing the `request.Credentials` assignment there and check if it would still work (it might).

**Comment by CasperWSchmidt** [comment]
@alexeyzimarev I know it's a warning for the future, thats why I don't like to be dependent on that property - it might be removed in the next release :)

What I need to accomplish is, using OAuth 2, to re-add credentials to the request when following a redirect. Why have a POST end-point for searching that returns a 307 (IIRC) for the client to follow for the result of the search. All endpoints are secured using OAuth. I know this is disabled by default for security reasons, but our RestSharp helper-class is only used to call internal REST APIs.

**Comment by CasperWSchmidt** [comment]
@alexeyzimarev any ideas how to solve the problem mentioned above?

**Comment by alexeyzimarev** [comment]
I don't know to be honest since RestSharp is just a convenience wrapper around the `HttpWebRequest` and can do just as much as the underlying .NET infrastructure allows us to do. I am open to suggestions but frankly, I have no idea.
