### ISSUE TITLE
Reduce delay between opening TCP connection and sending HTTP request.

### ISSUE THREAD

**Issue by andrekoehler** [restsharp/RestSharp#1470]
I am trying to communicate with a Boditrak device (https://boditrak.com/software/dataport/api/) via USB. They ship a local HTTP server which seems to close the TCP connection after no bytes were received for 20 ms. Wireshark revealed, that RestSharp waits 35 ms between opening the TCP connection and sending the HTTP GET request.

**Comment by alexeyzimarev** [comment]
It's not RestSharp, if you try using `HttpWebRequest`, I suspect you will get the same result. That's how .NET works, at least the part which we are using. RestSharp is not doing any networking by itself.
