### ISSUE TITLE
Properties that end with "ID" (in uppercase) will not deserialize properly

### ISSUE THREAD

**Issue by LanFeusT23** [restsharp/RestSharp#1471]
This is an issue that has been occurring on 106.11.2 and above, downgrading to 106.10.1 has fixed the issue.

## Expected Behavior
Deserialization should work regardless of the "ID" casing.

## Actual Behavior
Deserializing properties that end with "ID" (in uppercase) will not deserialize properly

## Steps to Reproduce the Problem

  1. Make a call to an API that returns properties with the a name using "ID" for example: OperationID or ServiceID
  2. Deserialize it into a class, the properties on that class can be written any way you want "operationId, operationid, OperationID"
  3. => the values are not deserialized properly and will return default value for that type

## Specifications

  - Version: 106.11.2+
  - Platform: Windows 10
  - Subsystem: .Net Framework 4.6.2

**Comment by sjmckinney** [comment]
I have also found the same issue with 106.11.4 and used the same remedy.

**Comment by ammard2u** [comment]
i'm having issue with certain field and weirdly only this field, others is ok.

field - LogPDFUrl, RS unable to parse this and return null

**Comment by alexeyzimarev** [comment]
We had some culture-related issues with camel case, it's been fixed. Could you try it now with the latest version?

**Comment by jeffreypolk** [comment]
I had a similar issue casing issue.  An API returns a property named "isSSL" and when deserializing onto an object with a property named "IsSSL" it did not work (version 106.11.4).  When I downgraded (version 106.10.1), it deserialized as expected.

**Comment by bogdanpetcas** [comment]
Still happens on version 106.11.7.
It seems this problem occurs for any property that has 2 or more consecutive uppercase characters in its name. (e.g. isPDF). The only way it works is to name your class properties exactly as they come in JSON format. which is 'isPDF'. You can try naming it 'IsPDF', 'IsPdf', 'ispdf', or any other way but it won't work.
So unless you want some of your class properties starting with lowercase, the only solution so far is to downgrade to 106.10.1.

**Comment by RustinAlexandru** [comment]
07.12.2020 - Latest version, 106.11.7 

The issue is still not fixed. Very annoying. I'd recommend switching to Newtonsoft as a deserializer by default.

**Comment by alexeyzimarev** [comment]
@RustinAlexandru if it annoys you so much, why don't you fix it?
