### ISSUE TITLE
Request resources with colons do not work

### ISSUE THREAD

**Issue by nmggithub** [restsharp/RestSharp#1473]
## Expected Behavior

I send a request to a URL with a resouce that includes a colon (e.g. https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword), and the request is completed successfully.

## Actual Behavior

RestSharp takes the colon in the path as indication of a full Uri. In the case of https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword, if I create a RestClient with the base url "https://identitytoolkit.googleapis.com/v1/" and then make a request with the resource "accounts:signInWithPassword", `client.BuildUri(request)` returns only "accounts:signInWithPassword".

## Steps to Reproduce the Problem

See above.

## Specifications

  - Version: 106.11.4
  - Platform: Windows 10 (.NET Framework 4.8)

**Comment by mikegron** [comment]
We had a similar problem with one of our internal library.. When calling `BuildUri`, internally it's using the [relative path Uri constructor](https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netcore-3.1#System_Uri__ctor_System_Uri_System_String_). However, for some reason the Uri class will parse the relative path and search for the scheme, which is delimited by a semi-colon (like `https:`). If it finds a semi-colon, it thinks the relative path is in fact an absolute uri and overrides the base uri (check the remarks in msdn).
As a workaround, you should add `./` at the beginning of your resource path, and the Uri class should understand it's a relative path.

**Comment by conficient** [comment]
A colon is a reserved character and should only be used in the context of the scheme element of the URI. If used in the authority or path it should be encoded as `%3A`

`v1/accounts%3AsignInWithPassword`

see https://www.ietf.org/rfc/rfc1738.txt - refer to page 3 "Reserved Characters"

**Comment by mikegron** [comment]
A colon _can_ be used outside the scheme, but inside the scheme it is reserved. It is valid to use a colon in the path, query etc. of a Uri but there are limitations like https://tools.ietf.org/html/rfc3986#section-4.2

> A path segment that contains a colon character (e.g., "this:that")
   cannot be used as the first segment of a relative-path reference
