### ISSUE TITLE
Download File help has code which does not work

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [restsharp/RestSharp#1478]
## Expected Behavior
I expected to be able to download bytes from the file

## Actual Behavior
Using your code I get this error: "file extension is not being accepted by your browser"

Your code is poor C# code which is not easily translated to reading bytes synchronously or into VB.Net.

This code is more succinct:

Dim sTempFilePath = System.IO.Path.GetTempFileName() & "." & System.IO.Path.GetExtension(sURL)

        Using myClient As New System.Net.WebClient
            myClient.DownloadFile(sURL, sTempFilePath)
        End Using

**Comment by TriSysBusinessSoftware** [comment]
https://restsharp.dev/usage/files.html

**Comment by TriSysBusinessSoftware** [comment]
No such "file extension is not being accepted by your browser" error when using System.Net.WebClient

**Comment by alexeyzimarev** [comment]
I am not sure what you're trying to say and what `WebClient` has to do with RestSharp. If you want to complain about the code in the docs, I suggest you find some other place to do that.
