### ISSUE TITLE
FailOnDeserializationError is true by default, but docs suggest it should be false.

### ISSUE THREAD

**Issue by dbry23** [restsharp/RestSharp#1479]
## Expected Behavior

On failed deserialization, `response.ResponseStatus` should be set to `ResponseStatus.Completed`. 

## Actual Behavior

Failed deserialization causes `response.ResponseStatus` to be set to `ResponseStatus.Error`. 

Error handling documentation (https://restsharp.dev/usage/exceptions.html) for the `FailOnDeserializationError` property reads:

"Changes the **default behavior** when **failed deserialization results in a successful response** with an empty Data property of the response. **Setting this property to true** will tell RestSharp to consider failed deserialization as an error and **set the ResponseStatus to Error** accordingly."

Line 160 in src/RestSharp/RestClient.cs:
`public bool FailOnDeserializationError { get; set; } = true;`

## Steps to Reproduce the Problem

  1. Create new instance of `RestClient()`, default config
  2. Create new `RestRequest`, pass a string for the URL
  3. Create new `IRestResponse<T>` from `client.Get<T>` or `client.Post<T>` where the response doesn't match `T`
      - My particular use case was just returning a string error message, but the response was expecting a type.
  4. `response.ResponseStatus` set to `ResponseStatus.Error`

## Specifications

  - Version: 106.11.4 (tested 106.10.1 as well)
  - Platform: Windows 10 Pro, Version 1909
  - Subsystem:

## StackTrace
<details>

```
N/A
```

</details>

**Comment by alexeyzimarev** [comment]
The mistake is in the docs. The default value is `true` and RestSharp used to consider deserialisation issues as errors, it has always been like that.
