### ISSUE TITLE
ToCamelCase extension works wrong for ending Id

### ISSUE THREAD

**Issue by lekrus** [restsharp/RestSharp#1480]
## Expected Behavior
"AgreementId".ToCamelCase(CultureInfo.InvariantCulture).Should().Be("agreementId");

## Actual Behavior
in 106.10.1 that works as expected
in 106.11.4 that returns "agreementid", so CamelCaseJsonSerializerStrategy works incorrectly

**Comment by deburau** [comment]
This is a big problem for me, too. Now I have to add `DeserializeAs `attributes to get things working again.

I propose to add the following tests to the `ToPascalCase` test in `StringExtensionsTests.cs`:

`TestCase("thisIsAnotherTest", true, "ThisIsAnotherTest"), TestCase("thisIsAnotherTest", false, "Thisisanothertest")`

and fixing `ToCamelCase`.

**Comment by liquidboy** [comment]
ive hit this too ...
