### ISSUE TITLE
Getting Request in wire format

### ISSUE THREAD

**Issue by mkoppanen** [restsharp/RestSharp#1484]
## Expected Behavior

Call a method and get representation on what gets sent on wire and what comes back. Essentially this would be useful for debugging / tracing / auditing purposes. There are stackoverflow answers like the following:

https://stackoverflow.com/questions/15683858/restsharp-print-raw-request-and-response-headers

But in essence it would be ideal to have a call for this in the library.

## Actual Behavior

Unable to find such a method and creating a workaround. Creates mess.

## Steps to Reproduce the Problem

  1. Install NuGet package
  2. Play around with amazing library
  3. Get asked by business to add auditing on requests and responses

## Specifications

  - Version: N/A
  - Platform: N/A
  - Subsystem: N/A

**Comment by alexeyzimarev** [comment]
You can access to the request content and response content. What exactly are looking for?
