### ISSUE TITLE
Weird HTML response

### ISSUE THREAD

**Issue by infosteo** [restsharp/RestSharp#1487]
## Expected Behavior
I'm trying to get **products** data from a Prestashop web site.
Everything on Prestashop administration in set and working: via Postman everything is ok: I'm getting xml product list.

## Actual Behavior
Source code:

      System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; 
      string strUr = @"https://presthashop.whatever/api"
      RestClient client = new RestClient(strUr);
      RestRequest request = new RestRequest("Products", Method.GET);
      IRestResponse<List<Bukimedia.PrestaSharp.Entities.product>> response = client.Execute<List<Bukimedia.PrestaSharp.Entities.product>>(request);
      string sResp  = response.Content;
      
sResp is always null and ResponseUri changed in
Response.ResponseUri.AbsoluteUri = "https://presthashop.whatever**/index.php?url=Products**"

response.ContentType is "**text/html**; charset=utf-8"

If I try to use HttpWebRequest instead of RestSharp the response.content contains the full **html** page I see via browser.

## Steps to Reproduce the Problem

  1. any c# request

**Comment by alexeyzimarev** [comment]
I am quite confused, you expect RestSharp to deserialize the web page? Deserialization only works for content types with serialises available, like XML and JSON. We were never able to deserialize web pages.

**Comment by infosteo** [comment]
No, I don't expect Restasharp to deserialize the page, the problem is that the response I'm getting is not XML or JSON but HTML.
Sorry, I’ll try to be more specific.

The RAW reponse I'm getting is:
`
HTTP/1.1 200 OK
Date: Mon, 10 Aug 2020 08:18:40 GMT
Server: Apache
X-Powered-By: PHP/7.0.33
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=6guk95apeve9cdenephscunlr4; path=/
Set-Cookie: PrestaShop-e9a607768f9b4c018e9050166de16adc=def5020049f82af3931c2ca4327acd5da2617f05ed8cee675db65695c1d0eb2de6cf015bca6b25746167002537861028b1b4504dd1d1b86001ebe6f26a18c03fd9ec99e10911d5cc8f7ee5dce44dcfef0d1f4697fa64fe0a87f67b11e355357e9e88cfe85a8808bda2d711b38250684da8729d3e13fbe642c9f79d9edea259ab459816f1e8bca766b8cfadc93cff65e9445dfc2615dcea01ff641759127478; expires=Sun, 30-Aug-2020 08:18:40 GMT; Max-Age=1727999; path=/; domain=irrigazioneperfetta.com; secure; HttpOnly
Set-Cookie: PrestaShop-e9a607768f9b4c018e9050166de16adc=def502002890bb7e51c0cd47c97513fe126e62c1adbfd44b8a6559fc4fb55e816c6e1fdb0a3a84978f90cb92cf1fffc7af362aa23d536b7d4f4d3fe831c7307967521bd40587747cb0c66df3e485ccea73e4edc5ad58e57868e1ce80e0829b9fde63ade2c27d852ea41297f4a618ac22ef44cba0b426eccd180ce14d8dc8849d06b4b2075aa1dc63fd85a571af8b1fe89e5d0df85df68ccb0a010182ea9c98bc4c01efd3c66c323b799c195f837f99bf25ca67876ca56e897338dfd67f0bc65479a6; expires=Sun, 30-Aug-2020 08:18:40 GMT; Max-Age=1727999; path=/; domain=<mywebsite>; secure; HttpOnly
Keep-Alive: timeout=5, max=150
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8

<!doctype html>
<html lang="it">

  <head>
    
      
  <meta charset="utf-8">


  <meta http-equiv="x-ua-compatible" content="ie=edge">



  <title>Irrigazione perfetta</title>
  <meta name="description" content="Negozio creato usando PrestaShop">
  <meta name="keywords" content="">
      
                  <link rel="alternate" href="https://irrigazioneperfetta.com/index.php?url=products%2F&amp;display=full&amp;id_lang=1" hreflang="en-us">
                  <link rel="alternate" href="https://irrigazioneperfetta.com/index.php?url=products%2F&amp;display=full&amp;id_lang=2" hreflang="it-it">
        



  <meta name="viewport" content="width=device-width, initial-scale=1">
`

**Comment by alexeyzimarev** [comment]
Well, you use the typed `Execute` and expect to get the typed `IRestResponse` back, which instructs RestSharp to deserialize the response. Just use the untyped `Execute`.

**Comment by infosteo** [comment]
I tried with untyped Execute and it works only setting a generic cookie like this:
request.AddCookie("PsSHop", "PrestaShop-e9a");

**Comment by infosteo** [comment]
Finally I've found then solution: bad settings on prestashop admin.
These are correct settings:
![117590483_10157640012813284_8926029641709409234_n](https://user-images.githubusercontent.com/8542687/89783387-20d85280-db17-11ea-801f-6270473093a6.jpg)
