### ISSUE TITLE
Json deserialization is not working as expected when culture is 'az' or 'tr'

### ISSUE THREAD

**Issue by nesc58** [restsharp/RestSharp#1491]
## Expected Behavior
Deserialized objects should be equivalent independend of `Thread.CurrentThread.CurrentUICulture` or `Thread.CurrentThread.CurrentCulture`.

## Actual Behavior
When the culture is `az` or `tr` or a derived culture of them, serialization not working for properties starting with uppercase `I`.

In the following example the deserialized object contains `null` instead of `MyName`.

DTO:
```
public class Person
{
    public string InternalName {get; set;}
}
```

Json:
```
{
    "internalName": "MyName"
}
```

## Steps to Reproduce the Problem
Here is a repo with unit tests to test all cultures:
https://github.com/nesc58/RestSharpCultureTests

## Specifications

  - Version: `106.11.4`
  - Platform: Windows
  - Subsystem: Windows 10, .netcoreapp 2.2

I am not able to find the right place to fix this. I have found some interesting code places:
While mapping the properties, `TryGetValue` returns `null`: https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/Serializers/Json/JsonSerializer.cs#L120

It might be better not to use the GenericEqualityComparer<string> (default one): https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/Serializers/Json/SimpleJson.cs#L688

Perhaps the problem is solved by using a better (culture invariant comparer) like `StringComparer.InvariantCultureIgnoreCase` or `StringComparer.InvariantCulture`.

Initialization could be easy done by: `new JsonObject(StringComparer.InvariantCulture)`

**Comment by nesc58** [comment]
I have found something interesting:
`var variants = parts[i].GetNameVariants(Culture).Distinct();`
returns for `InternalName` e.g. `ınternalName`  instead of `internalName`

This is not the expected character

**Comment by alexeyzimarev** [comment]
Yeah, seems like the issue is indeed in culture settings. That's why the issue is only experienced by some and not all users. It might even not be found by tests.

**Comment by nesc58** [comment]
I have created a pull request: https://github.com/restsharp/RestSharp/pull/1492

**Comment by nesc58** [comment]
@alexeyzimarev is there a planned release date for `v106.11.5`? What are the open issues or features to release this fix?

**Comment by alexeyzimarev** [comment]
I want to look at two recent issues #1495 #1497 and try to fix them before releasing the new version.
Your fix is in the latest preview package already.

**Comment by alexeyzimarev** [comment]
@nesc58 106.11.5 is out :)

**Comment by nesc58** [comment]
Thanks :-)
