### ISSUE TITLE
RestSharp provides status code 0 when Code Optimization turned on

### ISSUE THREAD

**Issue by tkemp2290** [restsharp/RestSharp#1494]
## Description
When debugging my Xamarin application, all my RestSharp code works fine and the requests make it to the outside world and receive valid responses. However, in release mode this isn't the case, In release mode, all the calls appeared to return an HTTP Response code of 0. 
I compared my debug and release project settings and the only difference i could note was that in Release mode, Code Optimization was turned on. I did a release build without Code Optimization and that made the code work, but increased the app bundle size by around 10mb.

## Expected Behavior
RestSharp to return valid HTTP Responses when in Release Mode and Code Optimization in Visual Studio turned on.

## Actual Behavior
RestSharp returns Status Code 0 when in Release mode and Code Optimization turned on.

## Steps to Reproduce the Problem

  1. Create an apk in Release configuration
  2. Run app that calls a Rest Web API
  3. Observe - HTTP Status Code 0 returned

## Specifications

  - Version: 106.11.4
  - Platform: Xamarin.Android
  - Subsystem: MvvmCross 7.0.0, Visual Studio 19, Windows 10, Android 6.0.1 device, Android 9 device

**Comment by alexeyzimarev** [comment]
I don't really think it has anything to do with RestSharp. Check the response error, it should have something telling you what the issue is.
