### ISSUE TITLE
OAuth failing because oauth_token is not encoded.

### ISSUE THREAD

**Issue by sharok** [restsharp/RestSharp#1495]
## Expected Behavior
OAuth authenticator should get access token.

## Actual Behavior
Using `OAuth1Authenticator.ForAccessToken` I get an error from the provider that `oauth_token` is absent.  But it exists in the header. 
After debugging the source code, I figured out that `RestSharp` doesn't encode `oauth_token`.

After changing the line in `OAuthWorkflow` file:
 `if (!Token.IsEmpty()) authParameters.Add(new WebPair("oauth_token", Token)); `

to

` if (!Token.IsEmpty()) authParameters.Add(new WebPair("oauth_token", Token, true));`

I was managed to get access token.

PS. I use ETrade exchange broker in this case.

## Specifications

  - Version: 106.11.4 ( also tried 106.11.5-alpha.0.21)
  - Platform: .NET Core 3.1
  - Subsystem:  N/A

**Comment by sharok** [comment]
@alexeyzimarev could I have your attention here, please. Because this issue is a big blocker right now.
I can send PR for this, all tests pass, but I cannot check integration tests, because LinkedIn doesn't allow to create OAuth 1 keys anymore, Twitter rejected my application.

**Comment by alexeyzimarev** [comment]
@sharok it would be great to get a PR 👍 
I have Twitter keys, so I can test it locally. I am unable to put it in the CI since it requires a manual step.
