### ISSUE TITLE
How to override ExecuteAsync(IRestRequest request, CancellationToken token = default);

### ISSUE THREAD

**Issue by Edgaras91** [restsharp/RestSharp#1499]
## Expected Behavior
To be able to override `Task<IRestResponse> ExecuteAsync(IRestRequest request, CancellationToken token = default);`

**Comment by alexeyzimarev** [comment]
Why would you want to override it? If I look at communication libraries or database clients, none of their members are virtual.

**Comment by Edgaras91** [comment]
IRestResponse Execute(IRestRequest request) is virtual.
My idea was to override it and log every response.
Is there another way to achieve this?

**Comment by alexeyzimarev** [comment]
By following the same pattern as Microsoft advises, by using the [typed client](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#typed-clients). It's generally a much better way of encapsulating a particular API client than spreading out the direct usage of `IRestClient`.

Also, since we use `HttpWebRequest`, which uses `HttpClient` under the hood, using event listeners from `System.Diagnostics` is usually a good way of low-level generic APM and diagnostic source.

**Comment by Edgaras91** [comment]
Thanks for that technical explanation, are you able to give an example of how to achieve what I requested:
To log every response, by writing code just in 1 place? My typical calls look like this:
```
        internal async Task<ResponseModel> GetSomething(Model requestModel)
        {
            try
            {
                var request = new RestRequest("/api/v1/deals/quick/trade_rate_data", Method.POST);
                request.AddJsonBody(Model );

                var result = await client.ExecuteAsync(request);
                return JsonConvert.DeserializeObject<ResponseModel>(result.Content);
            }
            catch (Exception e)
            {
                Crashes.TrackError(e);
                return null;

            }
        }
```

I want to be able to run every response through an if HttpStatus == XXX Log.Error(data).....

**Comment by alexeyzimarev** [comment]
You can either log in every place, which gives you context. Alternatively, you can create an extension method:

```csharp
public static class RestClientExtensions {
    public static async Task<T> ExecuteAndLog<T>(this IRestClient client, IRestRequest request) {
        var response = awaut client.ExecuteAsync<T>(request);
        if (response.StatusCode != 200) {
             // log here
        }
        return response.Data;
    } 
}
```

```csharp
        internal async Task<ResponseModel> GetSomething(Model requestModel)
        {
            try
            {
                var request = new RestRequest("/somewhere/", Method.POST);
                request.AddJsonBody(Model);

                return await client.ExecuteAndLog(request);
            }
            catch (Exception e)
            {
                Crashes.TrackError(e);
                return null;

            }
        }
```

**Comment by Edgaras91** [comment]
Thanks @alexeyzimarev I ended up with this:
`        public static async Task<IRestResponse> ExecuteAsyncAndLog(this RestClient client, IRestRequest request, CancellationToken token = default)
        {
            IRestResponse result = await client.ExecuteAsync(request, token);

            if(result.StatusCode != System.Net.HttpStatusCode.OK)
            {
                //Log
            }
            return result;
        }`

Now all that's left, is rename every method from ExecuteAsync to ExecuteAsyncLog. An override would have saved this part.
Please correct if the above looks wrong

**Comment by alexeyzimarev** [comment]
I generally find composition and currying preferred to inheritance. It's just better programming.

I still won't use manual deserialization since the point of using RestSharp is to delegate this work to it.

**Comment by Edgaras91** [comment]
Thanks for the feedback, I appreciate your help. I guess we don't need an override after all.
