### ISSUE TITLE
Deprecation warnings using Parameter outside of IRestRequest

### ISSUE THREAD

**Issue by nesc58** [restsharp/RestSharp#1501]
## Expected Behavior
No deprecation warnings.

## Actual Behavior
Writing custom `IRestSerializer` implementation produces some deprecation warning
Deprecation warning: `"Use Add[XXX]Parameter methods of IRestRequest instead of instantiating the Parameter class."`

# General / Questions
Parameters seems not be deprecated at all.
RestSharp self still uses the `Parameter` class e.g. in `IRestRequest`: `List<Parameter> Parameters { get; }`.
Will `Parameter` class removed / replaced at some point? 

# Suggestion
* Remove deprecation warnings for `Parameter` class.
* Add deprecation warnings to `IRestRequest`
  * `IRestRequest AddParameter(Parameter p)`
  * `IRestRequest AddOrUpdateParameter(Parameter parameter);`
  * Maybe: `AddOrUpdateParameters(IEnumerable<Parameter> parameters)`

**Comment by alexeyzimarev** [comment]
The message is not correctly placed, as you mentioned the list of parameters will be available.

However, I want to make parameters more robust by encapsulating more.
- It should not be a `List` but `IReadOnlyCollection` so it cannot be modified
- Parameters to be added only by using `AddParameter` method or any new API.
- Make the `Parameter` class constructor internal

However, I might see how it will hinder some of the use cases and I'd like to hear some feedback.

**Comment by alexeyzimarev** [comment]
Ideally, I'd keep the `Parameter` class internal but I am not sure how people use this collection to make a decision.

**Comment by nesc58** [comment]
I have seen some code lines where instances of `Paramter` written to class fields because they were reused a lot of times. e.g. generating `Authorized` headers instead of using an _Authenticator_. Sometime authentication is only required for special routes and not at all. 

What do you think? Is there an alternative for that? In my mind: Creating multiple instances solves the problem: One with authenticator, one without. But this seems a little bit messy.

**Comment by Slushnas** [comment]
I was confused by this message as well.

I am using a custom helper class to construct a list of parameters based on some conditions and then I pass that list to the `AddOrUpdateParameters()` method. Is there a downside in allowing us to construct a list of parameters outside one of the Add[XXX]Parameter methods?

**Comment by alexeyzimarev** [comment]
That's basically why I need feedback. 👍

**Comment by alexeyzimarev** [comment]
The reason for encapsulation is this:
https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/Parameter.cs#L31-L39

We have specific methods for different parameter types but it all then consolidates in the constructor, where we have to do different checks, depending on what kind of parameter is it. We're also forced to have nullable properties since not all the properties are relevant for all parameter type.

I would rather prefer to have the `Parameter` class abstract and have specific classes for different parameter types. I'd also add static factories like `Parameter.CreateFIle` and `Parameter.CreateBody` that would return the proper instance, then remove the complex check logic from the `Parameter` class constructor.

**Comment by nesc58** [comment]
> Ideally, I'd keep the `Parameter` class internal but I am not sure how people use this collection to make a decision.

Maybe we must cleanup some code paths. The `IRestSerializer` interface needs a public Parameter class `Serialize(Parameter parameter)` .

This interface implementation is only used by `RestRequestExtensions`. 

Can the line also changed to body.Value? https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/RestRequestExtensions.cs#L58

**Comment by alexeyzimarev** [comment]
yeah, but that's exactly where it's wrong. It cannot serialise just _any_ parameter, it must be the `BodyParameter`. That's what I meant.

**Comment by alexeyzimarev** [comment]
> Can the line also changed to body.Value
No, because it will break the request. Nothing on the request call should ever change anything outside it. It must have no side effects on the request itself.

**Comment by nesc58** [comment]
I found what I was looking for

All json serializers will do the following: `public string Serialize(Parameter parameter) => Serialize(parameter.Value);`
So my thought were: Just remove this from the interface and move the logic to serialize parameter.Value to the exentsion method:
```
if (!restSerializers.TryGetValue(body.DataFormat, out var serializer))
	throw new InvalidDataContractException(
		$"Can't find serializer for content type {body.DataFormat}"
	);

request.Body = new RequestBody(serializer.ContentType, serializer.ContentType, serializer.Serialize(body));
```
will be changed to:
```
if (!restSerializers.TryGetValue(body.DataFormat, out var serializer))
	throw new InvalidDataContractException(
		$"Can't find serializer for content type {body.DataFormat}"
	);

request.Body = new RequestBody(serializer.ContentType, serializer.ContentType, serializer.Serialize(body.Value));
```

But i have found the reason for this: The XmlRestSerialzier will handle parameters to set the correct xml namespace.

**Comment by dsparkplug** [comment]
I get this confusing depreciation warning message when retrieving a header value. e.g.

```csharp
Parameter rateLimitHeader = response.Headers.FirstOrDefault(h => h.Name.Equals($"{headerPrefix}Limit", StringComparison.OrdinalIgnoreCase));
if (rateLimitHeader != null && int.TryParse((string)rateLimitHeader.Value, out int rateLimitValue))
	rateLimit = rateLimitValue;
```

I could, of course, use `var`, but my preferred coding style is to use explicit types. Why not put the Obsolete attributes on the constructors rather than the class?

**Comment by alexeyzimarev** [comment]
I agree it should be on the constructor. However, I am not sure if the response will still have the `Parameter` in headers. It is semantically wrong. The response cannot have parameters, the headers need to be explicitly typed as headers or key-value pairs.

**Comment by dsparkplug** [comment]
That's fair enough - but until then we have a warning logged in the stable version with no information on how to deal with it.

**Comment by alexeyzimarev** [comment]
I started fixing it but there's on open PR (stale) that aimed to fix the parameter typing issue. Maybe I can pick it up and finish.

**Comment by mhornbacher** [comment]
What about `AuthenticatorBase` and it's child classes?

This warning is thrown twice when implementing `GetAuthenticationParameter`

**Comment by mhornbacher** [comment]
For example:

```
    public class TokenBearerAuthenticator : AuthenticatorBase
    {
        public TokenBearerAuthenticator(string token) : base(token)
        {
        }

        protected override Parameter GetAuthenticationParameter(string accessToken)
        {
            return new Parameter("Authorization", $"Bearer {accessToken}", ParameterType.HttpHeader);
        }
    }
```

**Comment by dsparkplug** [comment]
I may be wrong, but I've always thought that it was best practice to implement an alternative *before* using the `Obsolete` attribute. The build warnings on my CI server are currently making me a wee bit anxious :anguished:

**Comment by jpactor** [comment]
Our test tooling relies heavily on tracking collections of parameters before adding them to the RestRequest. I suppose we can just roll our own Parameter class and use it to feed the AddXXXParameter methods, but it was very handy for us to have an existing Parameter class we could use. We might have to hold back on upgrading to the latest version until we can sort this out.

**Comment by nesc58** [comment]
Sorry for the stale pull request. The last months i've been running out of time for this.

**Comment by tgaertner-recom** [comment]
For the feedback: when the Parameter constructor is not available, one cannot use initializers to construct the Request anymore:

```
var request = new RestRequest("resource", Method.GET)
{
    Parameters =
    {
        new Parameter("id", "1337", ParameterType.GetOrPost)
    },
    ...
};
```
