### ISSUE TITLE
How to add proxy server

### ISSUE THREAD

**Issue by kaisame** [restsharp/RestSharp#1502]
How to add proxy server?
example:
WebProxy webproxy = new WebProxy(ip, port); 
HttpWebRequest Httpweq = (HttpWebRequest)WebRequest.Create("http://www.baidu.com");
Httpweq.Proxy = webproxy;

**Comment by alexeyzimarev** [comment]
https://restsharp.dev/api/RestSharp.html#property-proxy-3
