### ISSUE TITLE
RestSharp 106.11.5 nuget contains netstandard2.0/restsharp.dll version 106.8.10

### ISSUE THREAD

**Issue by erik-bizzdo** [restsharp/RestSharp#1504]
## Expected Behavior
NuGet contains dll's with advertised version.

## Actual Behavior
Upgraded to RestSharp NuGet version 106.11.5. Get a regression warning with packages containing RestSharp 106.11.4. Due to new restsharp.dll having a lower version.

## Steps to Reproduce the Problem
  1. Download NuGet RestSharp 106.11.5
  2. Unpack nupkg
  3. Display details for netstandard2.0/restsharp.dll
  4. Shows 106.8.10 instead of expected 106.11.5

**Comment by kfkvamme** [comment]
Just discovered this as well, while trying to figure out why a project referencing RestSharp 106.11.5 was having assembly load errors when using another Nuget package that was compiled against RestSharp 106.11.4.

**Comment by alexeyzimarev** [comment]
It's really weird since when I build it locally, it shows the correct assembly version...

**Comment by alexeyzimarev** [comment]
The version attribute was right there in the props file. Previously MinVer seems to handle that but then it didn't.

The 106.11.7 has it solved.
