### ISSUE TITLE
Cannot update the latest version - 106.11.5 - Visualstudio 2019

### ISSUE THREAD

**Issue by TuHQ** [restsharp/RestSharp#1505]
## Expected Behavior
Install latest version 106.11.5 on visual studio 2019 NuGet packages.

## Actual Behavior
The current version: 105.2.3 is ok, but when i try to install new version, the system said that: "_Could not install package 'RestSharp 106.11.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author_"

## Steps to Reproduce the Problem

  1. Go to Visual Studio 2019
  2. Go to Manage Nuget Packages
  3. Search "RestSharp" > select latest vesion > click "Updated"

## Specifications

  - Version: 106.11.5
  - Platform: .Net Framework 4.8
  - Subsystem: Visual Studio 2019

## StackTrace
<details>
Please see the sreenshots:
https://i.imgur.com/yETphlE.png
https://i.imgur.com/0cXVrIK.png
</details>

**Comment by alexeyzimarev** [comment]
RestShar doesn't target .NET 4.5. It is written in the readme and in the docs.
