### ISSUE TITLE
Possible Memory Leak in Async code 

### ISSUE THREAD

**Issue by WayneHiller** [restsharp/RestSharp#1506]
I believe I have discovered a memory leak in Http.Async.cs

```
void SetTimeout(IAsyncResult asyncResult)
        {
            if (Timeout != 0)
                ThreadPool.RegisterWaitForSingleObject(
                    asyncResult.AsyncWaitHandle,
                    TimeoutCallback, _timeoutState, Timeout, true
                );

            static void TimeoutCallback(object state, bool timedOut)
            {
                if (!timedOut)
                    return;

                if (!(state is TimeOutState tos))
                    return;

                lock (tos) tos.TimedOut = true;

                tos.Request?.Abort();
            }
        }
```

The handle In the call to ThreadPool.RegisterWaitForSingleObject is not saved and handle.Unregister is never called.

https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.registerwaitforsingleobject?view=netcore-3.1

My ANTS Memory Profiler is showing the leak.

![image](https://user-images.githubusercontent.com/1186731/94567741-a37cb480-0220-11eb-908d-9fd10094e9f3.png)

## Specifications

  - Version: 106.10.1
  - Platform: Win x64

**Comment by WayneHiller** [comment]
This could be a fix:

```
class TimeOutState
{
      public bool TimedOut { get; set; }
      public HttpWebRequest? Request { get; set; }
      public RegisteredWaitHandle Handle = null;
}

...

void SetTimeout(IAsyncResult asyncResult)
        {
            if (Timeout != 0)
                _timeoutState.Handle = ThreadPool.RegisterWaitForSingleObject(
                    asyncResult.AsyncWaitHandle,
                    TimeoutCallback, _timeoutState, Timeout, true
                );

            static void TimeoutCallback(object state, bool timedOut)
            {
                if (!timedOut)
                {
                     if (_timeoutState.Handle != null)
                     {
                           _timeoutState.Handle.Unregister(null);
                     }
                     return;
                }

                if (!(state is TimeOutState tos))
                    return;

                lock (tos) tos.TimedOut = true;

                tos.Request?.Abort();
            }
        }
```

**Comment by WayneHiller** [comment]
I cloned the repo, made the above changes and tested it in my project. The leak was fixed. Any idea why the Repo I cloned is version 106.8.10 but the nuget version I have already in the project is 106.10.1?

**Comment by mhornbacher** [comment]
Is there a Pull Request for this fix?

**Comment by WayneHiller** [comment]
I did not create a Pull Request because the version number of the Repo I cloned was older than the release.

**Comment by mhornbacher** [comment]
@WayneHiller mind if I take a crack at it? Its effecting our production code.

**Comment by WayneHiller** [comment]
@mhornbacher Go for it.

**Comment by alexeyzimarev** [comment]
Ok, it's merged, @WayneHiller would you be able to check it against your test with the latest alpha nuget package?

**Comment by WayneHiller** [comment]
I have since changed the code to use HttpClient, I won't be able to test it. I did test the code above and the leak was fixed.

**Comment by mhornbacher** [comment]
@alexeyzimarev we deployed this beta package to our QA environment and validated that the memory leak is indeed fixed.

**Comment by alexeyzimarev** [comment]
@mhornbacher awesome, I will make a fix release soon for the stable package.

**Comment by mhornbacher** [comment]
Thank you!

Should we close this issue?
