### ISSUE TITLE
RestSharp AddFile does not work when called from C#

### ISSUE THREAD

**Issue by SimonKravis** [restsharp/RestSharp#1508]
I am using RestSharp to make a request to the Kairos face rcognitionAPI from C# using the following code from the Postman API tester, on which I was able to send the successfully

`var client = new RestClient(“https://api.kairos.com/detect”);
client.Timeout = -1;
var request = new RestRequest(Method.POST);
request.AddHeader(“Content-Type”, “application/json”);
request.AddHeader(“app_id”, “xxx”);
request.AddHeader(“app_key”, “xxxx”);
request.AddFile(“image”, “/C:/Users/Simon/AppData/Local/Temp/Test (36).jpg”);
IRestResponse response = client.Execute(request);`

This  results in a path format error. If I remove the first / from the second parameter of request.Addfile, the request is sent but the response contains  the error “image one or more required parameters are missing”. Changing all the / characters to \ to follow normal Windows path conventions did not make any difference. The specified file exists  and has write permission for Everyone. If i convert the file to a byte array and try to add that to the request I get the same error.

The request is made from a C# Windows Forms application running in VS 2019 in a Win 10 environment.

Please accept my apologies if this is not a RestSharp problem, but one related to the API I am using. There seem to be examples of request.AddFile being used with a Windows file full path as the second parameter.

**Comment by alexeyzimarev** [comment]
Windows path is `“C:\\Users\\Simon\\AppData\\Loca\\/Temp\\Test (36).jpg`

**Comment by SimonKravis** [comment]
Tried, this same error. The error message indicates that the problem is in the API rather than in RestSharp. I can get the same error in Postman using a 1st parameter which is not "image" or the second parameter referring to a non-existent file
