### ISSUE TITLE
Json Array parameters

### ISSUE THREAD

**Issue by DeLuca92** [restsharp/RestSharp#1510]
Hello, peole.
I need help with one think.
How I send a JSON array by restharp?
{
     "body":"Nome 1",
     "chatId":["55519xxxxx@c.us","555198xxx@c.us"]
}

I tried a lot of thinks, but all fail :/.
The server timeout :/, but if I sent my curl works :O

 var serviceUrl = user + "createGroup?token=" + MainWindow.usuarioLogado.Token;

            var client = new RestClient(baseUrl);
            var request = new RestRequest(serviceUrl, Method.POST);
            request.AddParameter("body", "Grupo Legal");

            List<string> nomes = new List<string>();

            nomes.Add("55519xxxxx@c.us");
            nomes.Add("55519xxxxx@c.us");

            string json = JsonConvert.SerializeObject(nomes.ToArray());

            string output = new JavaScriptSerializer().Serialize(nomes);

            Console.WriteLine("Out :"+ output);

            JsonArray arr = new JsonArray();
            arr.Add("55519xxxxx@c.us");
            arr.Add("55519xxxxx@c.us");
            Console.WriteLine(arr);

            request.AddParameter("chatId", arr);

            IRestResponse response = client.Execute(request);

           var content = response.Content;

            Console.WriteLine(content);

**Comment by alexeyzimarev** [comment]
It's a basic programming question about serialising objects to JSON.
