### ISSUE TITLE
ThrowOnAnyError does not throw

### ISSUE THREAD

**Issue by trj2000** [restsharp/RestSharp#1511]
## Expected Behavior

When creating a RestClient, initialized with `ThrowOnAnyError = true`, I expect an exception to be thrown when a request fails, as per the documentation: [Error Handling](https://restsharp.dev/usage/exceptions.html)

## Actual Behavior

No exception is thrown.

For sync requests, the exception is caught in `ExecuteRequest`, for async requests it's caught in `GetStyleMethodInternalAsync`. In both cases the exception is consumed and a HttpResponse with error info is returned. No exception gets thrown. Instead, the error response is returned, regardless of the value of `ThrowOnAnyError`.

## Steps to Reproduce the Problem

A simple request against a non-existing endpoint shows the problem:

```
var req = new RestRequest("nonexisting");
var client = new RestClient("http://localhost:12345") { ThrowOnAnyError=true };
Assert.Throws<Exception>(() => client.Execute(req));    // Fails: no exception is thrown
```

## Specifications

  - Version: 106.11.7
  - Platform: Windows x64

**Comment by jbutlerAG** [comment]
@alexeyzimarev - Any estimate on when this fix will be published to the NuGet feed? We're using 106.11.7 and this is still not throwing the error. I also tried the 106.11.8-alpha.0.14 package, but that did not seem to work either.

**Comment by qz8** [comment]
@FrediKats @alexeyzimarev FYI, this is still happening in 106.12.0.

**Comment by Larsjep** [comment]
@FrediKats @alexeyzimarev This still seems to be a problem in 107.0.2
This basically makes .GetAsync<T>() and .PostAsync<T>() useless 😢

**Comment by alexeyzimarev** [comment]
@Larsjep I think it's a different issue. And I see why it happens.

**Comment by Larsjep** [comment]
Thanks 😀, that was quick 👍
It seems to work now.
