### ISSUE TITLE
.net frameword and .net core 3.0 are not the same response.

### ISSUE THREAD

**Issue by colindcli** [restsharp/RestSharp#1516]
## Expected Behavior

request url: `https://cqsj.tanwan.com/client.php?type=2`

.net 4.6
![111](https://user-images.githubusercontent.com/3311217/95674860-916a2100-0be5-11eb-9275-5a6cce9b334c.jpg)

.core 3.0
![222](https://user-images.githubusercontent.com/3311217/95674864-9b8c1f80-0be5-11eb-90e3-d5dad8acbff4.jpg)

**Comment by alexeyzimarev** [comment]
I believe we provide enough details in the issue guidelines. I have to mark the issue invalid since none of the requested details was provided.

**Comment by colindcli** [comment]
.net4.6 reponse ContentType is application/octet-stream
core3.0 reponse ContentType is text/html

core3.0 reponse wrong ContentType.
