### ISSUE TITLE
Concurrency issue with Task<IRestResponse<T>> ExecuteAsync<T>

### ISSUE THREAD

**Issue by gauravdanani** [restsharp/RestSharp#1518]
## Expected Behavior

When ExecuteAsync<T> is invoked from Parallel.ForEach, it should return with response for all requests.

## Actual Behavior

When ExecuteAsync<T> is invoked from Parallel.ForEach, it doesn't come back with any sort of response for few of the requests. It looks like requests are getting lost.

## Steps to Reproduce the Problem

  1. Invoke  ExecuteAsync<T> for 20 or more times from the Parellel.ForEach loop.

**Sample code:**

     Parallel.ForEach(dtos, async dto =>
            {
                var e = await Record.ExceptionAsync(async () => { await sut.MethodWhichCallsExecuteAsync(dto); });

                if (e != null)
                {
                    ex.Add(e);
                }
            });

     public async Task<TResponse> MethodWhichCallsExecuteAsync<TResponse>(string baseUrl, string resource,
            IEnumerable<Parameter> parameters, string userName, string password)
        {
            var client = new RestClient(baseUrl)
            {
                Authenticator = new HttpBasicAuthenticator(userName, password)
            };

            var request = new RestRequest(resource, Method.POST);

            if (parameters != null)
            {
                request.Parameters.AddRange(parameters);
            }

            // Logging request here

            IRestResponse<TResponse> response;
            try
            {
                response = await client.ExecuteAsync<TResponse>(request);
            }
            catch (Exception e)
            {
                // Logging Exception here
                throw;
            }

            // Logging response here

            if (response.IsSuccessful)
            {
                return response.Data;
            }

            throw new Exception();
        }

Inside MethodWhichCallsExecuteAsync, we do log every request/response/exception, and what we found was for few requests there was no log for the response and no exception as well.

## Specifications

  - Version: RestSharp 106.11.4
  - Platform: .net framework v4.6.1

**Comment by StephenCleary** [comment]
You can't use `Parallel` with `async`.

Try using asynchronous concurrency:

```C#
var tasks = dtos.Select(async dto =>
{
  var e = await Record.ExceptionAsync(async () => { await sut.MethodWhichCallsExecuteAsync(dto); });
  if (e != null)
    ex.Add(e);
});
await Task.WhenAll(tasks);
```
