### ISSUE TITLE
How to enable TCP Keep Alive

### ISSUE THREAD

**Issue by Segflow** [restsharp/RestSharp#1519]
Is it possible to enable TCP Keep alive on the underlying socket used by the client?

**Comment by alexeyzimarev** [comment]
Marking invalid for ignoring the contribution guidelines.

**Comment by Segflow** [comment]
It's a simple question! I'm trying to use the client, but couldn't find how to enable TCP Keep Alive, so I asked the question here, not sure what "contribution" guidelines should apply here..

**Comment by alexeyzimarev** [comment]
https://restsharp.dev/get-help/
