### ISSUE TITLE
RestClient.Execute does not exist

### ISSUE THREAD

**Issue by dave-perry** [restsharp/RestSharp#152]
Using the example on the wiki:

`public T Execute<T>(RestRequest request) where T : new()
    {
        var client = new RestClient();
        client.BaseUrl = BaseUrl;
        client.Authenticator = new HttpBasicAuthenticator(_accountSid, _secretKey);
        request.AddParameter("AccountSid", _accountSid, ParameterType.UrlSegment); // used on every request
        var response = client.Execute<T>(request);
        return response.Data;
    }`

I get the following error:

Error   1   'RestSharp.RestClient' does not contain a definition for 'Execute' and no extension method 'Execute' accepting a first argument of type 'RestSharp.RestClient' could be found (are you missing a using directive or an assembly reference?)

Using 101.3 dll on Windows Phone 7.

**Comment by Programn00b** [comment]
Same issue, but using version 106.6.9 and VisualStudio... I can only find similar problems, but hardly any answer to my problem: [https://groups.google.com/forum/#!topic/restsharp/mZsI_iOk-hs](url)...

**Comment by alexeyzimarev** [comment]
@Programn00b the link doesn't work. I don't understand the issue. If the method is not there - you can't use it. If you're using another library that references RestSharp, you should use the version they reference to avoid conflicts like this.

**Comment by Programn00b** [comment]
@alexeyzimarev , updated my comment. On http://restsharp.org/ , the examples given have an execute() method... so i assumed that was also possible in the newest version of RestSharp.

**Comment by alexeyzimarev** [comment]
@Programn00b I don't control that website and I tried really hard to find out who owns the domain and where the source for the website is located but found nothing. So, I probably need to get a new domain and create a new website.

**Comment by Programn00b** [comment]
@alexeyzimarev thanks for replying, now I know that my problem isn't just because of my code :) 👍
