### ISSUE TITLE
SemVer breaking change

### ISSUE THREAD

**Issue by MatthewSteeples** [restsharp/RestSharp#1520]
RestClient.AddHandler(IDeserializer deserializer, params string[] contentTypes) was public in version 106.6.7.0 but now doesn't exist in 106.11.7.0.

This kind of breaking change should have ideally been indicated by an increase in the major version number (106 to 107), as it's not a forward compatible change

**Comment by alexeyzimarev** [comment]
I agree, but that's what happened and it's impossible to revert. Sorry for the inconvenience and thanks for the heads up.

**Comment by MatthewSteeples** [comment]
Thanks for the quick response. Was only meant as a heads up (and maybe bump the version for the next release anyway)

**Comment by alexeyzimarev** [comment]
Thanks again. I guess the insane value of the major version got me scared... Hence we only had one major release in two years. More to come, I expect. I will hold breaking changes for major versions.

**Comment by alexeyzimarev** [comment]
You can update the release notes Markdown file and add a couple of lines to the docs as a warning.

The `AddHandler` function was marked as obsolete quite a while ago, at least a couple of years by now.

I had to remove the handlers to support custom serialisers properly. It was historically painful with RestSharp and now it's very easy. I fully understand your concern, still what happened has happened.
