### ISSUE TITLE
RestResponse.ResponseStatus is set to ResponseStatus.Error when there is server error

### ISSUE THREAD

**Issue by blooming** [restsharp/RestSharp#1522]
## Expected Behavior
when server return 400 , RestResponse.ResponseStatus is expected to be ResponseStatus.Completed 

## Actual Behavior
 RestResponse.ResponseStatus is set to ResponseStatus.Error

## Steps to Reproduce the Problem

  1. client send request
  2. the server response 400
  3. RestResponse.ResponseStatus is set to ResponseStatus.Error
## Specifications

  - Version: 106.11.7
  - Platform: .net framework
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
HTTP status code is `Bad Request`, why is it not an error?

**Comment by blooming** [comment]
> HTTP status code is `Bad Request`, why is it not an error?

https://restsharp.dev/usage/exceptions.html

If there is a network transport error (network is down, failed DNS lookup, etc), RestResponse.ResponseStatus will be set to ResponseStatus.Error, otherwise it will be ResponseStatus.Completed

**Comment by alexeyzimarev** [comment]
I updated the docs. All 4XX and 5XX are errors. 404 is ok.
