### ISSUE TITLE
Blazor WebAssembly:﻿System.PlatformNotSupportedException: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by Crashdummyy** [restsharp/RestSharp#1524]
Hello there,

some time ago I wrote an RestClient to interact with Jira using RestSharp as my Backend.
When I try to integrate this into my webassembly project I can't perform any request at all.

Everytime I get slapped with this Exception:
`Blazor.webassembly.js:1 ﻿System.PlatformNotSupportedException: Operation is not supported on this platform.`

Here is a sample call to the component ressource:
```csharp
        private const string RESOURCE = "component";

        /// <inheritdoc />
        public Task<Component> GetSingleAsync(string id,
                                              CancellationToken cancellationToken = default)
        {
            return client.GetAsync<Component>(RESOURCE + $"/{id}",
                                              cancellationToken);
        }
----------------------------------------------------------------------------------------
        protected IRestClient Client { get; }

        public async Task<T> GetAsync<T>(string resource,
                                         CancellationToken cancellationToken = default,
                                         params (string key, string value)[] uriParameters)
        {
            IRestRequest request = new RestRequest(resource, Method.GET);
            uriParameters.Aggregate(request,
                                    (x, y) => x.AddQueryParameter(y.key, y.value));
            
            return await this.Client.GetAsync<T>(request,
                                                 cancellationToken);
        }
```

## Expected Behavior
Well it should return a single component poco

## Actual Behavior
`Blazor.webassembly.js:1 ﻿System.PlatformNotSupportedException: Operation is not supported on this platform.`

## Steps to Reproduce the Problem

  1. Open Webassembly Project
  2. Try performing a GET
  3. Get slapped by this issue

## Specifications

  - Version: 106.11.7
  - Platform: Windows 10x64 -- Blazor Webassembly (netstandard2.0)

## StackTrace
<details>

blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)  
blazor.webassembly.js:1 blazor Loaded 6.47 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.  
dotnet.3.2.0.js:1 mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28  
blazor.webassembly.js:1 ﻿System.PlatformNotSupportedException: Operation is not supported on this platform.  
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at System.Net.WebProxy.CreateDefaultProxy () <0x2ab2a50 + 0x00008> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at System.Net.Configuration.DefaultProxySectionInternal.GetSystemWebProxy () <0x2ab27b8 + 0x00000> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at System.Net.Configuration.DefaultProxySectionInternal.GetDefaultProxy_UsingOldMonoCode () <0x2ab2710 + 0x00000> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at System.Net.Configuration.DefaultProxySectionInternal.GetSection () <0x2ab2510 + 0x0002a> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at System.Net.WebRequest.get_InternalDefaultWebProxy () <0x2aada70 + 0x00034> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at System.Net.WebRequest.get_DefaultWebProxy () <0x2aad818 + 0x00000> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at RestSharp.RestClient.ConfigureHttp (RestSharp.IRestRequest request) <0x2a18ff8 + 0x00656> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at RestSharp.RestClient.ExecuteAsync (RestSharp.IRestRequest request, System.Action`2[T1,T2] callback, System.String httpMethod, System.Func`4[T1,T2,T3,TResult] getWebRequest) <0x2a06540 + 0x0008e> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at RestSharp.RestClient.ExecuteAsync (RestSharp.IRestRequest request, System.Action`2[T1,T2] callback, RestSharp.Method httpMethod) <0x29fb298 + 0x00138> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at RestSharp.RestClient.ExecuteAsync (RestSharp.IRestRequest request, System.Action`2[T1,T2] callback) <0x29face0 + 0x0001c> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at RestSharp.RestClient.ExecuteAsync[T] (RestSharp.IRestRequest request, System.Action`2[T1,T2] callback) <0x29faaa8 + 0x0004e> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at RestSharp.RestClient.ExecuteAsync[T] (RestSharp.IRestRequest request, System.Threading.CancellationToken cancellationToken) <0x29fa1c8 + 0x00080> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1 --- End of stack trace from previous location where exception was thrown ---  
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at RestSharp.RestClientExtensions.GetAsync[T] (RestSharp.IRestClient client, RestSharp.IRestRequest request, System.Threading.CancellationToken cancellationToken) <0x29f06a0 + 0x000c8> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at Crashdummy.Extensions.JiraClient.JiraClient.GetAsync[T] (System.String resource, System.Threading.CancellationToken cancellationToken, System.ValueTuple`2[System.String,System.String][] uriParameters) <0x29ea788 + 0x0011e> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at JiraHelper.Client.Program.Main (System.String[] args) [0x000fc] in C:\Users\deschwsi\source\repos\Thingies\JiraHelper\src\Client\Program.cs:28   
f.printErr @ blazor.webassembly.js:1  
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint (System.String assemblyName, System.String[] args) <0x26ac0c0 + 0x0012c> in <filename unknown>:0   
f.printErr @ blazor.webassembly.js:1  

</details>

**Comment by Crashdummyy** [comment]
This is apparently an already known issue with the webassembly implementation of the [HttpClient](https://learn-blazor.com/architecture/rest-api/).

The HttpClient that is to be used has to be the one injected by the webassembly project

**Comment by Toemsel** [comment]
Well, that is a pitty. I would like to add this request
