### ISSUE TITLE
The new Async ExecuteAsync() should be virtual for easing up testing

### ISSUE THREAD

**Issue by rcabreu** [restsharp/RestSharp#1525]
Before, we used to rely on ExecuteTaskAsync(), which was virtual. However, the new one in RestClient.Async, ExecuteAsync(), is not virtual. This complicates our testing suite.

So, the request is for these methods to be virtual.

**Comment by alexeyzimarev** [comment]
None of the HttpClient methods are virtual and it seems to work fine for everyone. Using inheritance for testing is overall not a good idea and we plan to remove virtual modifiers in the future. Use co.position, not inheritance.

**Comment by mhornbacher** [comment]
Do these methods not exist on the `IRestClient` interface? (you could pass a `Moq.Mock<T>` or custom mock implementation instead)

**Comment by cloudhunter89** [comment]
Is there a reason your implementation doesn't use the interface IRestClient?  If you depend on the interface you can pass in anything that implements that interface which makes testing much easier.

**Comment by rcabreu** [comment]
I was working with a large "legacy" testing suite that for some reason used inheritance for mocking. I've since changed it to using the `IRestClient` interface. Thanks, guys!
