### ISSUE TITLE
Array[] in IRestResponse is not supported

### ISSUE THREAD

**Issue by cosmoscowboy** [restsharp/RestSharp#1529]
The RestClient.Execute<T> method does not work when using a model containing an array of class objects. 

For instance:
```
public class A
{
  public string SomeValue {get; set; }
  public B[] BValues {get; set;}
}

public class B
{
  public string SomeOtherValue {get;set;}
}
```

The IRestResponse contains an OK StatusCode and a value is set for 'Content' (which represents my model), but it also contains an Exception: 

No parameterless constructor defined for type 'MyModels.A.B[]'. . 

Consequently the value of 'Data' is null. 

If I use a generic list (i.e. `public List<B> BValues {get; set;}`), then it does work.

**Comment by alexeyzimarev** [comment]
That's how it is. If you have to do arrays, you can use any other serialiser https://restsharp.dev/usage/serialization.html

**Comment by cosmoscowboy** [comment]
Similar to the 'UTC time zone' known issue, it would be nice if the documentation mentions that arrays are not support, oh, btw, you can use a generic list.

**Comment by cosmoscowboy** [comment]
My workaround was to either use a generic list, or use an array[] with Newtonsoft.Json. Case closed.  😉
