### ISSUE TITLE
Will RestSharp support .NET Core 5.0?

### ISSUE THREAD

**Issue by jaldrin** [restsharp/RestSharp#1531]
I am in the process of upgrading my application from CORE 3.1 to 5.0 which was officially released today (10-Nov-2020). I realize that this is early in the cycle, but my requirements are driving me to migrate before going into production in January. 

I looked at the latest Alpha version and it is still supporting NETSTANDARD2.0.

Is it possible to have the next Alpha version add support for CORE 5.0? Thanks...

**Comment by Crashdummyy** [comment]
I use it on an net5.0 CLI tool to use it with the Jira api.
I've yet to encounter any problems

**Comment by jaldrin** [comment]
Thanks for your prompt reply. I ultimately removed the NuGet package and reinstalled it. It is working properly now and passes all of my unit & integration tests.
