### ISSUE TITLE
AddJsonBody where you add the contentType ="application/json-patch+json" when using Patch does not work 

### ISSUE THREAD

**Issue by qamessenger** [restsharp/RestSharp#1532]
## Behavior
I am sending a patch request which contains a patch document in the body. So I have to send contentType ="application/json-patch+json" I pass this into the AddJsonBody(jsonBody , "application/json-patch+json")

When the request is sent the response is getting bad request response back from the server. complaining about the json

If I use the old method  AddParameter (new Parameter("application/json-patch+json", jsonBody , "application/json-patch+json", ParameterType.RequestBody) method everything works fine, However this is now marked Obsolete and will be removed in a future release.

Here is my patch body that I am using for both methods 

string jsonBody = $@"
            [
  	            {{ ""op"": ""replace"",  ""path"": ""/siteStatus"",  ""value"": ""{(int)status}""}}
            ]";
When I look at the body of the request I don't really see any differences. The only differences seen was the AddParameter way which works, Has DataFormat = None where as the AddJsonBody has DataFormat=Json . I could not change it to None . It was not changed when doing this ApiRequest.RequestFormat = DataFormat.None. Taht is the only difference I see. Please do not remove the Obsolete method were I use this in the AddParameter(new Parameter("application/json-patch+json", jsonBody, "application/json-patch+json", ParameterType.RequestBody)) as this is the only way I can get the patch to work

Using AddParameter the parameter settings looks like this 
![image](https://user-images.githubusercontent.com/37448234/98860632-fb1e5a80-2431-11eb-8e17-6ba21536baef.png)

Notice that when you use the Parameter object the Body is set to "application/json-patch+json" just like the parameter "application/json-patch+json". 
![image](https://user-images.githubusercontent.com/37448234/98867931-60c41400-243d-11eb-941e-f280db9987e3.png)

Using AddJsonBody the Parameter looks like this
![image](https://user-images.githubusercontent.com/37448234/98860944-708a2b00-2432-11eb-9689-7d98066d0a80.png)

Notice that when you use the AddJsonBody the Body is set to "application/json" not "application/json-patch+json" and there is no way to change it. I did not see any other differences. This could be the issue.
![image](https://user-images.githubusercontent.com/37448234/98867320-5e14ef00-243c-11eb-9bce-ae4f2bda3f3c.png)

## Specifications

  - Version: 106.11.17
  - Platform: Windows 10
  - Subsystem:

**Comment by alexeyzimarev** [comment]
`AddJsonBody` does the serialisation, so it will serialise the _object_ passed as the parameter, and you pass a string with serialised content. That's just wrong.

**Comment by alexeyzimarev** [comment]
https://restsharp.dev/usage/parameters.html#request-body

**Comment by qamessenger** [comment]
Thanks Alex,

I got it to work this way using AddJsonBody.

  IList<object> parameters = new List<object>();
            dynamic obj = new ExpandoObject();
            obj.op = "replace";
            obj.path = "/siteStatus";
            obj.value = $"{(int)status}";
            parameters.Add(obj);
                       
            ApiRequest.AddJsonBody(parameters, "application/json-patch+json");

**Comment by alexeyzimarev** [comment]
You don't need to use dynamic here, you can just have an anonymous object.

```csharp
var parameters = new []{new { op = "replace", path = "/siteStatus", value = (int)status }};
request.AddJsonBody(parameters, "application/json-patch+json");
```
