### ISSUE TITLE
Missing Add(XXX)Parameter method for UrlSegment

### ISSUE THREAD

**Issue by Shujee** [restsharp/RestSharp#1533]
Version 106.11.7.0 marks `Parameter` and `AddParameter()` as obsolete and tells me that I should use corresponding Add(XXX)Parameter instead, but there is no substitute for `new Parameter(string, string, ParameterType.UrlSegment)`. Or did I miss something?

  - Version: 106.11.7.0
  - Platform: .NET Core 3.1

**Comment by alexeyzimarev** [comment]
Now sure what you mean. It is there

https://github.com/restsharp/RestSharp/blob/33033ce735cba632f7b0da5943d25f5053723501/src/RestSharp/IRestRequest.cs#L410

**Comment by alexeyzimarev** [comment]
It's actually [_in the docs_](https://restsharp.dev/usage/parameters.html#url-segment)

**Comment by Shujee** [comment]
Yep. Can't see how I missed that. Thanks for pointing out the obvious for me. And keep up the good work!
