### ISSUE TITLE
RestSharp failing to authenticate on forwarded requests with basic authentication

### ISSUE THREAD

**Issue by seannybgoode** [restsharp/RestSharp#1536]
## Expected Behavior
Restsharp authenticates normally on redirect

## Actual Behavior
On making a request to a remote server, and being redirected, the remote is returning "Unauthorized", while a postman request composed with the same parameters and also being redirected is working fine. Connecting to the same remote, without using redirects works as expected.

## Steps to Reproduce the Problem

  1. Send a request, with basic auth, to a server that will be redirected 
  2. RestSharp fails to authenticate 
  3. Server returns unauthorized

NOTE: AllowRedirects flag is set to true.

## Specifications

  - Version: 106.11.7
  - Platform: Windows
  - Subsystem: IIS

```

</details>

**Comment by seannybgoode** [comment]
Any chance this issue can get some love? Is RESTsharp not being maintained?

**Comment by alexeyzimarev** [comment]
It is being maintained as long as the community members are willing to fix issues, which they themselves encounter. Alternatively, people can sponsor the project to motivate the maintainers to do the work. Neither are happening, apparently, and my time is very much limited.

**Comment by seannybgoode** [comment]
Yes fair enough. I can try to find time to fix this.
