### ISSUE TITLE
.net frameword and .net core 3.0 are not the same response.

### ISSUE THREAD

**Issue by colindcli** [restsharp/RestSharp#1540]
.net4.6 reponse ContentType is application/octet-stream
core3.0 reponse ContentType is text/html

core3.0 reponse wrong ContentType.

_Originally posted by @colindcli in https://github.com/restsharp/RestSharp/issues/1516#issuecomment-735532333_

**Comment by colindcli** [comment]
![restsharp](https://user-images.githubusercontent.com/3311217/100568024-efbda100-3304-11eb-8fc1-4db019ed942c.jpg)

**Comment by mhornbacher** [comment]
@colindcli if you take a look at the `ResponseUri` you will notice that they are different.

The `ContentType` is a header sent from the server. It is likely the case that these two different servers are sending back different content in different formats.

Another note from your screenshots is that the second request is returning a 302 found code and the content likely includes a redirect link to follow. Perhaps check if `FollowRedirects` is `true` on your `IRestClient`?
