### ISSUE TITLE
[FeatureRequest] Allow tunneling / forwarding of requests

### ISSUE THREAD

**Issue by AndreasReitberger** [restsharp/RestSharp#1541]
Hi,
I'm using this library to control a local based print server. This all works fine aslong as I'm connected to wifi.
Is there a way to integrate tunneling for a rest request using RestSharp?

For now, I'm connecting via a VPN which is working. But I'm looking for a more user friendly solution.

Thank you!

**Comment by alexeyzimarev** [comment]
RestSharp is _not_ a transport library. It's a relatively simple wrapper around the transport and application layers provided by .NET. We only add a more comfortable configuration API and serialisation for different content types.
