### ISSUE TITLE
Mark IRestResponse.ErrorException as nullable

### ISSUE THREAD

**Issue by neoncik** [restsharp/RestSharp#1547]
Hi, someone already posted this : https://github.com/restsharp/RestSharp/issues/1485 but it was auto-closed.

ErrorException field can be null, but is not marked as nullable.

Should be

    Exception? ErrorException { get; set; }

**Comment by alexeyzimarev** [comment]
Yes, it should be. As no one fixed the original issue, what are the chances that this issue will not be closed?

**Comment by mhornbacher** [comment]
It is on the interface but not the implementation :)

**Comment by mhornbacher** [comment]
Looks like this issue actually got closed!

**Comment by neoncik** [comment]
And when we should expect the release of new version ? :)
Closing this , as i see code is changed (in those 19 commits that are waiting to be released) in the right places and it seems to resolve issues i have in latest stable version :)

**Comment by mhornbacher** [comment]
I think it's automatically available as an alpha release. When the next release will be is a question for the maintainers ;)

**Comment by alexeyzimarev** [comment]
Yes, the latest preview package contains this fix.
