### ISSUE TITLE
RestSharp Assembly Binding

### ISSUE THREAD

**Issue by jmawebtech** [restsharp/RestSharp#1550]
I am trying to map RestSharp 105.2.3.0 to RestSharp 106.5.4.0 using assembly binding, but it fails. For some reason, I can't share my code here, but I posted it on Stackoverflow:

https://stackoverflow.com/questions/65498628/restsharp-assembly-binding

Is this a bug? Why does the assembly binding fail?

**Comment by alexeyzimarev** [comment]
Those assemblies aren't compatible.

**Comment by jmawebtech** [comment]
OK, so do I need to reference another RestSharp? How about RestSharp signed? What is the difference?

**Comment by alexeyzimarev** [comment]
I don't understand what you're asking, honestly. You can just use the latest version.

**Comment by mhornbacher** [comment]
@jmawebtech You are attempting to bind 105.2.3.0 to 106.5.4.0. Sadly there are breaking changes in the API surface between these two versions as @alexeyzimarev has pointed out. This means that your code will likely fail at runtime to find the surfaces it's looking for on the assembly you are redirecting to.

Are you able to control the assembly relying on 105.2.3.0 or is it from a 3rd party?
