### ISSUE TITLE
releasenotes out of date

### ISSUE THREAD

**Issue by DonThompson** [restsharp/RestSharp#1553]
I'm on version 106.10 and saw 106.11.7 is the latest, but I have no idea what changed.  There is a releasenotes.md (also linked from the main restsharp website) that has not been updated in 13 months.  Is there another location for these notes?

**Comment by alexeyzimarev** [comment]
https://github.com/restsharp/RestSharp/releases

**Comment by DonThompson** [comment]
For reference if someone wants to fix it, your nuget page links to the old one:
https://www.nuget.org/packages/RestSharp
