### ISSUE TITLE
Blazor web assembly not supported

### ISSUE THREAD

**Issue by Brilbroeder** [restsharp/RestSharp#1565]
When using RestSharp is blazor-server pages it works fine. In Blazor-client pages (webassembly) I get an error of non-supported sub-parts.

Any plans on making it supported on webassembly ? If so, timing please. We'll need to switch to another solution for the time being.

**Comment by alexeyzimarev** [comment]
I expect people who are interested in getting this done would contribute. It's a community project, not a commercial project. We also have no sponsors, although the library is widely used.

**Comment by czmirek** [comment]
It's possible, you just need to inject Blazor's own `HttpClient` into your `RestClient` and it'll start working then.

**Comment by alexeyzimarev** [comment]
@czmirek you are right, it's just that the issue is old and RestSharp was unable to accept a provided `HttpClient` instance. A similar issue was with Xamarin on Android.

**Comment by danmincu** [comment]
Even if you could inject an `HttpClient` instance into ResSharp one will find that this class is controlled by the browser e.g. Chrome and it's very limited by the fact that you cannot read from servers that aren't allowing for Cors policies.

**Comment by alexeyzimarev** [comment]
@danmincu is that something specific to RestSharp? I don't think so.
