### ISSUE TITLE
There is no non-obsolete alternative to manage HttpHeaders

### ISSUE THREAD

**Issue by jscarle** [restsharp/RestSharp#1567]
Using version 106.11.7, the class `Parameter` has been marked obsolete.

The first part is that `IRestResponse.Headers` returns an `IList<Parameter>`. There is no alternative method (which I could see) that returns a non-obsolete result.

So doing something like this throws warnings: `foreach (Parameter header in response.Headers)`

Adding HttpHeaders requires separating an HttpHeader into two parts as such:
```
HttpHeader authorizationHeader = BuildAuthorizationHeader(client, request, response, wwwAuthenticateHeaders[0]);
request.AddParameter(authorizationHeader.Name, authorizationHeader.Value, ParameterType.HttpHeader);
```

I suggest two small additions that would resolve the conflict with the obsolete `Parameter` and simply management of HttpHeaders in general.

1) Add a new property to `IRestResponse` that returns an `IList<HttpHeader>`, perhaps something like `IRestResponse.HttpHeaders`.

2) Add a shortcut method to `IRestRequest` for `HttpHeader`, perhaps something like `IRestRequest.AddHttpHeader(HttpHeader httpHeader)`.

**Comment by clarghi** [comment]
Hi,
I have the same problem too. I have removed Parameter in my solution except in a line of code where I need to read an Header parameter:
`Parameter test = Response.Headers.FirstOrDefault(k => k.Name=="CommonData");`
Actually I have not found a way to get it without the obsolete warning.
B.r.

**Comment by olle-j** [comment]
We got the same issue.

We try to mock a rest response and adjust our logging scope according to headers in the response. It work without warnings in "real code" but we need to create a fake rest response to test out the functionality in our unit tests.

```
var restResponse = new RestResponse();
restResponse.Headers.Add(new Parameter("operation-id-from-external-system", "ABC123", ParameterType.HttpHeader));

using (customLoggingScopeProvider.CreateScope(restResponse))
{
    // Logging scope should be used by all actions inside this
}
```

I can't really see how we can create tests based on the response without using deprecated functionality? Methods for creating response headers it either deprecated or internal.

**Comment by clarghi** [comment]
Hi, I'm waiting for this fix.
B.r.

**Comment by alexeyzimarev** [comment]
@clarghi the `Parameter` class is no longer obsolete in the last version, what exactly are you still waiting for?

**Comment by clarghi** [comment]
I didn't know that ... thanks!

**Comment by alexeyzimarev** [comment]
https://github.com/restsharp/RestSharp/releases/tag/106.13.0
