### ISSUE TITLE
Update client header values.

### ISSUE THREAD

**Issue by kuderdev** [restsharp/RestSharp#1569]
I think it is already fixed. We only add default parameters if there is no parameter with the same name available in the list of request parameters. It can be overridden by `AllowMultipleDefaultParametersWithSameName`, which is `false` by default.

_Originally posted by @alexeyzimarev in https://github.com/restsharp/RestSharp/issues/959#issuecomment-455881725_

I am not sure this solves the problem. If we set this to true wouldn't that mean he would have multiple headers with the same name and different tokens?

We need a AddOrUpdate like parameters has.

**Comment by Lramelot** [comment]
Created the PR #1576 to fix this issue :)
