### ISSUE TITLE
IRestResponse does not contain a definition for Data

### ISSUE THREAD

**Issue by baffourt** [restsharp/RestSharp#1575]
## Expected Behavior
Return deserialized simple object

## Actual Behavior
IRestresponse does not contain a definition of Data

## Steps to Reproduce the Problem

  1. IRestResponse response = client.Execute<LoginDto>(request);
  2. return response.Data
  
Need to do further Deserialization with JSonConvert.Deserialize<LoginDto>(response.Content) before it works.

When a breakpoint is placed on the execute however, I can see the Data property with the correct serialized object.
When I even try in the Command Window with this even with the breakpoint
? response.Data
It gives same error, though I can browse and see Data property in the response object

## Specifications

  - Version: 106.11.7
  - Platform: VS 2019, .NetFramework 4.7
  - Subsystem:

**Comment by Lramelot** [comment]
IRestResponse does not indeed. You should use IRestResponse<T> and Execute<T>, otherwise you won't get the Data property.

https://github.com/restsharp/RestSharp/blob/0ed7b0a6b64ab4b9838c2c0cb76a1808facebe09/src/RestSharp/IRestResponse.cs#L127

**Comment by baffourt** [comment]
Great, thank you @Lramelot for the direction.
