### ISSUE TITLE
overridable RestClient async methods. 

### ISSUE THREAD

**Issue by Abdulrhman5** [restsharp/RestSharp#1578]
https://github.com/restsharp/RestSharp/blob/0ed7b0a6b64ab4b9838c2c0cb76a1808facebe09/src/RestSharp/RestClient.Async.cs#L56-L65

Is it possible to mark the ExecuteAsync methods in RestClient as virtual?

**Comment by ngboardway** [comment]
I second this. I need to mock the client in my unit tests but have to use the deprecated methods in the mean time because it doesn't support mocking out non-overridable methods.

**Comment by alexeyzimarev** [comment]
No, there will be no virtual methods there. Mocking `RestClient` is a bad idea in general, but if you have to do it, use the interface.

**Comment by Abdulrhman5** [comment]
I don't want to mock the RestClient methods, I just need to log some messages before sending a request, and I would have made a Proxy around the `RestClient` but the interface `IRestClient` is too big. anyway, thank you.

**Comment by alexeyzimarev** [comment]
Again, making typed clients for particular use cases is _always_ a better idea, compared with directly using `RestClient` instances randomly, across the whole application. Say, you need to talk to some API, a single API. Make a client for that API, using meaningful wording, which expresses what the API does. Hide the `RestClient` instance inside. Do all you want, including the logging, caching, whatever else, in that client.

**Comment by Abdulrhman5** [comment]
You are absolutely right, but the log messages contain very generic information i.e. "how much a request took time to get a response" and this new behaviour is shared across all `client`s.

**Comment by guilhermemoschen** [comment]
> Again, making typed clients for particular use cases is _always_ a better idea, compared with directly using `RestClient` instances randomly, across the whole application. Say, you need to talk to some API, a single API. Make a client for that API, using meaningful wording, which expresses what the API does. Hide the `RestClient` instance inside. Do all you want, including the logging, caching, whatever else, in that client.

Hello @alexeyzimarev and sorry to bring this topic again.
Yes, I'm following your advice to create a meaningful client to interact with my API, e.g. GitLab.
However, I'm still having issues testing this client without an abstraction.
Check this code:
```cs
public async Task<IReadOnlyList<SearchResultForProjects>> SearchProjectsAsync(string query, CancellationToken cancellationToken)
{
    Guard.Against.NullOrWhiteSpace(query, nameof(query));

    var request = new RestRequest(SearchResource)
        .AddParameter("scope", Scopes.Projects, ParameterType.QueryString)
        .AddParameter("search", query, ParameterType.QueryString);

    var response = await _restClient.ExecuteAsync<IReadOnlyList<SearchResultForProjects>>(request, cancellationToken);
    return response.Data!;
}
````
How can I test `SearchProjectsAsync` in order to check if the RestRequest has the proper parameters? Or, how can I test that the response is handled properly? Like, is the behavior correct if it receives 404 or 200?

Without the interface, it's really hard to test cases like those and implement that Dependency Inversion Principle.

**Comment by alexeyzimarev** [comment]
RestSharp is _infrastructure_. As you don't have any interface on `HttpClient`, you don't have it on `RestClient` as well. The **only** way to test an HTTP call **is to make one**. You gave an example to search for a project in GitLab. You can easily test it against your own GitLab instance or gitlab.com using your access token.

You can also spin up a small Kestrel instance that would tell you how your request looks like, like we have https://github.com/restsharp/RestSharp/blob/dev/test/RestSharp.IntegrationTests/Fixtures/TestServer.cs

Another way to inspect the actual request is to use a delegating handler. In v107 you can configure `RestClient` to wrap the handler in a delegating handler like I've shown here: https://github.com/restsharp/RestSharp/issues/885#issuecomment-994721685

Your delegating handler can return a response that you expect without calling an actual GitLab instance, and you can easily ensure that everything is working properly. You can also inspect all the query, URL segment, and content parameters, as everything is available in the resource, or in the message content.

But then again, the **only** way to know that your client works is to call the actual service. Ensuring that you added all the parameters doesn't ensure authorisation, for example, or encoding, or that your request body is understood by the server, or that you can deserialize the response.

**Comment by guilhermemoschen** [comment]
I understand and agree with you about "The only way to test an HTTP call is to make one".
However, I'm not speaking about integration tests. My goal is to create a unit test where I can check if the method `SearchProjectsAsync` is behaving correctly, or not. And with version 107 is just harder to achieve this.

Please don't get me wrong, ReastSharper it's a great library, I'm using it for years and will continue to do so.

**Comment by alexeyzimarev** [comment]
There's a good answer to this [SO question](https://stackoverflow.com/questions/36425008/mocking-httpclient-in-unit-tests). It is directly applicable to RestSharp, and it uses a custom message handler as I  explained in my previous comment.
