### ISSUE TITLE
Response Code 0 during HTTP post 

### ISSUE THREAD

**Issue by CatWithAutism** [restsharp/RestSharp#1593]
This problem still exists in the latest versions of RestSharp.
#1392

**Comment by GooWen** [comment]
I meet this problem errorMessage via http/2.0 response

**Comment by CatWithAutism** [comment]
> I meet this problem errorMessage via http/2.0 response

same
moreover i use a proxy for requests

**Comment by Gallardo994** [comment]
Same.
```Error message Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null.
Parameter name: src```
I am getting this exception in Unity (Mono Runtime, 4.x) only for 4xx/5xx requests, with statuscode 0. Requests returning 200 work properly.

**Comment by YukiKitaoka** [comment]
I have the same issue - the version of RestSharp -version 106.12.0 for POST request.

**Comment by YukiKitaoka** [comment]
I am getting the same error, too. version 106.12.0

**Comment by Matiquiel** [comment]
Getting this error randomly

**Comment by Matiquiel** [comment]
@alexeyzimarev I tried the pre-release to fix this but it seems it uses a very old System.Runtime.CompilerServices.Unsafe. It looks for version 4.0.4.1 and my installed one is 5.0 (6.0 is already out btw)
I get a "Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies...."

**Comment by alexeyzimarev** [comment]
I am not sure why is that as RestSharp 107 preview has no dependencies on the assembly you mentioned: https://www.nuget.org/packages/RestSharp/107.0.0-preview.4

**Comment by alexeyzimarev** [comment]
This issue has no required information, but it references another issue, which is irrelevant for the latest preview of RestSharp. I, therefore, close it. If anyone experiences weird behaviour with v107, please **open a new issue with a proper description**.

Keep in mind that issues without all the required information mentioned in the template will be **immediately closed**. Show some respect for my time, please.

**Comment by alexeyzimarev** [comment]
What's your target framework? RestSharp doesn't reference `System.Runtime.CompilerServices` at all except for the `ExternalInit`, which is an implicit reference resolved at runtime.

**Comment by alexeyzimarev** [comment]
>  It looks for version 4.0.4.1 and my installed one is 5.0 (6.0 is already out btw)

The `System.Runtime.CompilerServices` assembly is referenced implicitly to make init-only records work on .NET < 5. It's not referenced in the assembly that targets .NET >= 5. If your project targets .NET < 5, it will use the framework assembly from the target framework.

**Comment by chenjing1294** [comment]
I am getting the same error, too. version 108.0.3

**Comment by w2227669390** [comment]
I am getting the same error, too. version 110.2.0
