### ISSUE TITLE
HTTP Version

### ISSUE THREAD

**Issue by aersamkull** [restsharp/RestSharp#1605]
## Expected Behavior

I'd like to be able to somehow set the Default Http Version that is used. This is easily possible with the HttpClient. An old stackoverflow question states it is simply not possible, but I'm not sure if this is still true?

## Actual Behavior

I could not find any documentation or the like about controlling the HTTP Version.

**Comment by aersamkull** [comment]
Any response?

**Comment by alexeyzimarev** [comment]
v107 uses HttpClient, so if it support HTTP/2, RestSharp supports it too.
