### ISSUE TITLE
Amazon (AWS) not working in 106.11.7 version

### ISSUE THREAD

**Issue by HasanHmoud** [restsharp/RestSharp#1607]
I used an older version of Restsharp (105.2.3) it was working fine with amazon calls, but when I upgraded to the newest version of Restsharp (106.11.7) the request always fails its like the secret key is never passed or something, I'm working on the same sample code from the amazon you can find it here

https://developer.amazon.com/docs/incentives-api/incentives-api.html

in c# sample specificly the create gift card code, I don't think that I can provide the Access and the Secret keys that I have but as I said if used the same code with version 105.2.3 it works fine but in version 106.11.7 it always says invalid signature and check your AWS secret access key.
If you need any more info I might be able to provide more

## Specifications

  - Version: 106.11.7
  - Platform: Amazon Web Services
  - Subsystem: Web form

**Comment by alexeyzimarev** [comment]
Compare the request between those two versions, you'll spot the difference. I cannot debug that specific API.
