### ISSUE TITLE
Rest Sharp escape %5F character

### ISSUE THREAD

**Issue by rjaidi** [restsharp/RestSharp#1608]
Hello,
I am trying to make an API call using RestClient. The URI has  some characters %5F in it and I need to call the API as is without encoding the special characters to "_". Can I get some help.

This is my URL
https://abc.com/core/v1/operations/InformationManagement/workers/9200293262974%5F1?$select=processingStatus

When I call the execute method it is returning as unauthorised 401 error and I see the URL has been changed to 

https://abc.com/core/v1/operations/InformationManagement/workers/9200293262974_1?$select=processingStatus

After some research I thought I found a solution if we use a AddURLSegment in the request. But still no luck.  It is replacing %5F with %255F and calling the wrong URL.

I am using .net framework 4.6.1 and restSharp version 106.11.8.0.

Any help is really appreciated.

**Comment by alexeyzimarev** [comment]
With 106.22 you should be able to use `AddUrlSegment(string name, string value, bool encode)` and set `encode` to `false` to fix the issue.

**Comment by rjaidi** [comment]
Thank you @alexeyzimarev . Will upgrade the try .
