### ISSUE TITLE
Documentation is hard to browse

### ISSUE THREAD

**Issue by ftsfranklin** [restsharp/RestSharp#1617]
It's hard to go through the documentation to get a feeling for the library's capabilities.

Issues:
- The documentation is all on a single page. This is nice for searching, but there's already a search bar.
- The sidebar does not expand further than three levels (members of a namespace), so we get a list of classes, but not constructors or methods.
- The RestClient is around 39 pages on my current screen settings, and full of obsolete methods which are only marked by a line of yellow and green in a dark box. These obsolete methods take up about a page each, and are gathered at the top of the class.
- There is no Table of Contents or list, at all, for the methods and properties of a class.

Workaround: I'll go browse the code instead.

**Comment by ftsfranklin** [comment]
The documentation is still hard to browse.

**Comment by alexeyzimarev** [comment]
@ftsfranklin please feel free to submit a PR to fix it.

**Comment by alexeyzimarev** [comment]
Closing for #1667
