### ISSUE TITLE
Hangs open on a LONG post (sync)

### ISSUE THREAD

**Issue by kkriegkxs** [restsharp/RestSharp#1620]
## Expected Behavior
When submitting a long (1h+) synchronous POST request (please don't laugh), response is received OR exception (e.g. timeout) is thrown

client.Timeout = Convert.ToInt32(TimeSpan.FromHours(3).TotalMilliseconds); 
(have tried with this too) client.ReadWriteTimeout = client.Timeout;

Endpoint T/Os are set to 3h, including system.web.httpRuntime executionTimeout="10800"

## Actual Behavior
Endpoint reports operation complete but client is forever sitting at 
var response = client.Post(new RestRequest().AddJsonBody(request));

The longest successful execution of the same request was ~45min

Tested successfully using curl and postman - both return response
Tested UNsuccessfully using HttpWebRequest, HttpClient as well as fiddler 4 - same behavior, perhaps an underlying .Net issue? 

## Steps to Reproduce the Problem

  1. Setup an endoint with 1h 5m sleep | use one with 1h+ response
  2. Set server and session t/os to more than the duration
  3. Run the long request

## Specifications

  - Version: 106.11.17
  - Platform: win10
  - Subsystem: netcore 5.0.302

## StackTrace
None available

</details>

**Comment by slacki123** [comment]
Did this ever get resolved?
