### ISSUE TITLE
What has changed in 106.12.0?

### ISSUE THREAD

**Issue by wojciechrak** [restsharp/RestSharp#1621]
Recently there was new version published *106.12.0*.
I cannot find any changelog for it.

https://github.com/restsharp/RestSharp/blob/dev/releasenotes.md stopped on 106.10
GitHub releases page also does not contain any information regarding this new version.

**Comment by jamesyoder11** [comment]
Not surprised. They broke backwards compatibility again in a "minor" version and failed to document any changes.
I'm ditching this in my companies codebase. It changes too unpredictably and will break things in minor versions.

**Comment by DarekDan** [comment]
> Not surprised. They broke backwards compatibility again in a "minor" version and failed to document any changes.
> I'm ditching this in my companies codebase. It changes too unpredictably and will break things in minor versions.

You sure know how to praise someone. @jamesyoder11 .

**Comment by davidgeary** [comment]
@wojciechrak Not sure what's going on with the releases.  I received a release notification from this repo on 15 July about v106.22, which I can't find any mention of:

> [v106.22](https://github.com/restsharp/RestSharp/releases/tag/106.22)
> Repository: [restsharp/RestSharp](https://github.com/restsharp/RestSharp) · Tag: [106.22](https://github.com/restsharp/RestSharp/tree/106.22) · Commit: [25dba85](https://github.com/restsharp/RestSharp/commit/25dba854c666b4beb4b2d3b305c07f3d1e293303) · Released by: [alexeyzimarev](https://github.com/alexeyzimarev)
>
> * OAuth1: Allow empty customer secrets, according to the specifications
> * GitHub Codespaces configuration
> * SimpleJson JsonSerializer to respect Culture when deserializing primitive types
> * Properties that end with "ID" (in uppercase) to deserialize properly
> * Security updates

The commit mentioned is correct, but the tag doesn't exist and there's no matching release.  I'm wondering if the version number was a typo - 106.22 should have been 106.12 - so it was deleted and republished on Nuget as 106.12 but without the matching tag/release here?

**Comment by alexeyzimarev** [comment]
All the releases are listed on the [Releases](https://github.com/restsharp/RestSharp/releases) page, including [106.12](https://github.com/restsharp/RestSharp/releases/tag/106.12.0)
