### ISSUE TITLE
FailOnDeserializationError not working as expected

### ISSUE THREAD

**Issue by hebaelfadly** [restsharp/RestSharp#1622]
## Expected Behavior
Data should be empty and ResponseStatus should be Error

## Actual Behavior
Data is a new object of T with empty props and ResponseStatus = Completed
![image](https://user-images.githubusercontent.com/61690067/127740076-718f7377-1d5e-433d-8099-43f663aba2f6.png)

## Steps to Reproduce the Problem

  1. ThrowOnDeserializationError and FailOnDeserializationError are set by default to true.
  2. Calling Get<T> or GetAsync<T> or Execute<T> while passing different T other than the type of returned data

## Specifications

  - Version: 106.12.0
  - Platform: Window 10

**Comment by dalehalliwell** [comment]
I'm seeing this too, only I think my T matches the shape of returned data (clearly there's a problem and was hoping those error failure settings would surface some info to help me find it). Happening on XML deserialization for me, regardless of whether I use the default serializer or the dotnet one.

**Comment by alexeyzimarev** [comment]
@hebaelfadly `FailOnDeserializationError` works in case the serialiser actually throws. If it fails silently, we cannot possibly detect if it failed or not. Some serialisers fail silently, expressing the behaviour you described. If you know a way to configure the serialiser you use to fail, the option will work. If you have any other suggestion, please feel free to contribute.
