### ISSUE TITLE
It makes no sense to mark the class Parameter as obsolete

### ISSUE THREAD

**Issue by ericderede** [restsharp/RestSharp#1630]
It makes no sense to mark the class Parameter as obsolete

This class is also present in the IRestResponse interface (the property Headers is a list of Parameter). There are use-cases where you might want to inspect the response-headers.

For example automated testing of a Web-API. If you want to test a operation that can serve up a file as a stream, you might want to inspect the headers to validate the filename.

**Comment by ClayC90** [comment]
It makes no sense even more when you take into consideration that many of RestSharp's client methods such as "AddDefaultParameter", "AddOrUpdateParameters" and more, make use of this class.

![image](https://user-images.githubusercontent.com/8785758/133594913-fb67bb0b-c124-4b52-9309-9c10afbfdfd9.png)

The dev has marked something obsolete before he even done all the necessary changes to his library, meaning some features will trigger a bunch of alerts on our runners, in other words, making the library un-usable for many.

**Comment by alexeyzimarev** [comment]
Feel free to submit a PR to remove the `[Obsolete]' annotation from that class. You apparently have issues with this, why don't you try fixing it?
