### ISSUE TITLE
 No way to affect how AddObject serializes DateTimes

### ISSUE THREAD

**Issue by IgorShch** [restsharp/RestSharp#1631]
## Expected Behavior

Would be great to be able to set a date format used when adding parameters through AddObject method 

## Actual Behavior

Currently there is no way to affect how dates are serialized into parameters. 

https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/RestRequest.cs#L318

**Comment by alexeyzimarev** [comment]
I'd suggest proposing a fix. We just call `ToString` on every property except collections.

**Comment by AR1ES** [comment]
Faced the same problem.
Also I need to properly format floating point values.
