### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by itsmahadi007** [restsharp/RestSharp#1634]
## Read this first!

**Important**
- Please do not use GitHub issues to ask question about using RestSharp.
- Ensure to read the Get help docs page at https://restsharp.dev/get-help/ before opening an issue/ 
- Issues not following our contribution guidelines will be marked as `invalid` and closed in three days.

## Actual Behavior
Package 'RestSharp 106.12.0' is not found in the following primary source(s): 'C:\Program Files 
(x86)\Microsoft SDKs\NuGetPackages\'.

## Steps to Reproduce the Problem

  1. in visual studio 2019 community edition 
  2. not found in search section
  3. can't install using PM

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## StackTrace
<details>

```

```

</details>

**Comment by alexeyzimarev** [comment]
It is not a RestSharp issue. Most probably you are using a runtime not supported by current RestSharp built targets (.NET Framework 4.5.2 and .NET Standard 2.0)
