### ISSUE TITLE
Deserialization is not working when the response entity has arrays

### ISSUE THREAD

**Issue by tnsatish** [restsharp/RestSharp#1637]
var client = new RestClient("URL");
var request = new RestRequest("request").AddJsonBody(input);
var response = client.Post<ResponseEntity>(request);

If the ResponseEntity has an array object, then response.Data is set to null, as deserialization to arrays is failing. If the Array object is changed to List, then the response.Data is set properly with the ResponseEntity object. 

  - Version: 106.12.0
  - Platform: .Net Core 5.1

**Comment by alexeyzimarev** [comment]
You can use another serializer and it will work.
