### ISSUE TITLE
DateTime Kind get converted to Local  in response data of RestClient.Execute<T>(request) 

### ISSUE THREAD

**Issue by zeeshanumar** [restsharp/RestSharp#1640]
In response to Api Call DateTime Kind value has been changed to Local from utc.

I am executing Call using this method :

var response = _client.Execute(_request);

and in response.Data DateTime kind is converted to Local instead of utc.

Is there any workaround for this ?

**Comment by alexeyzimarev** [comment]
Yes, use another serialiser. It's documented how to use them. SimpleJson is just 💩
