### ISSUE TITLE
Versions of RestSharp 106.2.0 return "Bad Request" when trying to upload a file to a Post request.

### ISSUE THREAD

**Issue by warrenkeil** [restsharp/RestSharp#1651]
## Steps to Reproduce the Problem

I am trying to upload a file to a Post request. The block of code below works for restsharp versions up to 106.1.0. However, the response in the same block of code returns a 400 "Bad Request" for versions 106.2.0 and higher, after it runs the client.Execute(request) line.

var client = new RestClient("https://*************/export/csv");
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("Content-Type", "multipart/form-data; boundary=xmlRequest");
            request.AddHeader("Authorization", "Basic d2FycmVuQGRlZXBmb3JrdGVjaG5vbG9neS5jb206RDMzcGYwcmshQmxhbmNjbw==");
            request.AddHeader("Cookie", "AWSALB=Ek*****************************DgwNVPglX/Y1oEFgERsl5LhZSoxPuhKjYI; A************************skGswi6wFyicQNGxhPDgwNVPglX/Y1oEFgERsl5LhZSoxPuhKjYI");
            request.AddFile("xmlRequest", "C:\\Users\\*********************\\Api\\searchFinal.xml");
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);

**Comment by alexeyzimarev** [comment]
I don't see you are adding XML body, what you are doing is uploading the file.

Also, please define "fails" as you provided no details about what actually happens.

**Comment by warrenkeil** [comment]
Thank you for the correction, I'll try to edit the issue to make it more clear. The problems lies in the line where I'm uploading the xml file. I've tried most of the versions to try to locate which version it breaks at. It appears that is working up until version 106.1.0 and it is not working for versions 106.2.0 and higher.

**Comment by tomassev** [comment]
Hi I have similar issue when I tried add restRequest.AddFile or AddFileBytes then the request seems corrupted - body is empty

**Comment by alexeyzimarev** [comment]
I don't know what it is. I do know that adding cookies like you do won't work, they must go to cookie container. I also don't think you need to add the content-type header, it's done automatically.

**Comment by warrenkeil** [comment]
Hi Alexey, I've been pretty busy lately, but if I can find some time, I'll try to find the bug. Like I said in my post, it break precisely at the version I mentioned above. So I should be able to step through the working version and find where it breaks in the later version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexeyzimarev** [comment]
Maybe you can check the latest preview as literally 80% of things have changed, so it would be good to confirm if the issue is still there.

**Comment by warrenkeil** [comment]
Thanks, I'll check that first.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexeyzimarev** [comment]
@tomassev btw we have a couple of file upload tests and they pass. It would be nice to get a bit more details about the issue you're facing, preferably with v107 preview, as I have no plans fixing things in v106.

**Comment by alexeyzimarev** [comment]
Closing due to lack of feedback.
