### ISSUE TITLE
How to send multipart/form-data body request to generate Access Token for Instagram API?

### ISSUE THREAD

**Issue by nalinasanka** [restsharp/RestSharp#1657]
Hi All,

We are unable to get the access token from Instagram API using RestSharp where the body is encoded as multipart/form-data. There seems to be an issue, how would you do this via RestSharp? Below is my current code:

            RestClient _client = new RestClient("https://api.instagram.com");
            RestRequest _request = new RestRequest("/auth/access_token", Method.POST);
            var code = "AQCB6VkVR0hxwj7A2kIgndTU9eqhsqenW1k0RzTVeAGcnusYPcXUUw2ffSppaKJXglgEJE0VO9eaIZYxmXz2sg6v3hReJUXAFQtr3b8pQp_0C55K6uAHnPrDiW4dTuIkyBv-w48oK_Af7AO5iXpe6cv2PII70g";
            
            _request.AddHeader("Accept", "*/*");
            _request.AddHeader("Content-Type", $"multipart/form-data;boundary=255");

            _request.AlwaysMultipartFormData = true;
            _request.AddParameter("client_secret", "xsedd259080f06a3189aa6f8eb3bce57f649", ParameterType.RequestBody);
            _request.AddParameter("client_id", "20886893879533074565", ParameterType.RequestBody);
            _request.AddParameter("grant_type", "authorization_code", ParameterType.RequestBody);
            _request.AddParameter("redirect_uri", "https://httpstat.us/200", ParameterType.RequestBody);
            _request.AddParameter("code", code, ParameterType.RequestBody);

            var response = _client.Execute<object>(_request);

When execute the code, I always gets Not Found status code. Please see below image

![image](https://user-images.githubusercontent.com/8293984/144695939-6c553d1f-1dbb-41f4-acd1-e7e481bb99e0.png)

The same call is working in the Postman.

Thanks

**Comment by alexeyzimarev** [comment]
I could suggest looking at [OAuth tests](https://github.com/restsharp/RestSharp/blob/dev/test/RestSharp.IntegrationTests/OAuth1Tests.cs) instead of using normal requests for authentication purposes. I am not sure what Instagram wants. A simple request body and headers comparison between Postman and your app could also reveal the difference and could give you a clue.

We ask explicitly to post questions on StackOverflow instead of opening issues, so please do ad advised.

**Comment by nalinasanka** [comment]
Hi Alex,

I'm really sorry about the concern brought up here, it was due to the typo issue.

It's working fine now after correct it and complete code is below

```
var client = new HttpClient { BaseAddress = new Uri("https://api.instagram.com/oauth/") };
            var request = new HttpRequestMessage(HttpMethod.Post, new Uri(client.BaseAddress, "access_token"));
            var code = "AQCr60VqUuU5U-_PvSh1Biu2gPUi0cUmU3g0ZEiRjH_MlBNewFcqjiDhw5RaMsEdqhNYiOdmGcaiQ3OyTiSXENP09k2Vct0hjIXvewHpyGzNbuh9WDSAwkEOfemz_B_CyTj16bGOf3hygJjaKPL72FIiIgyuNamNt_qf12iYBldGDCVLMVgNliFZGg8Fwdn6pLND4xRQpzQNKhbz_6BcyFx";

            //HttpClient client = new HttpClient();
            //var request = new HttpRequestMessage(HttpMethod.Post, "https://api.instagram.com/oauth/access_token");
            var myParameters = string.Format("client_id={0}&client_secret={1}&grant_type={2}&redirect_uri={3}&code={4}",
                "20886893879533054447".UrlEncode(),
                "dxcd259080f06a3189aa6f8eb3bce57f649".UrlEncode(),
                "authorization_code".UrlEncode(),
                "https://httpstat.us/200".UrlEncode(),
                code.UrlEncode());

            request.Content = new StringContent(myParameters, Encoding.UTF8, "application/x-www-form-urlencoded");

            var response = await client.SendAsync(request);
```

Thanks,
Nalin
