### ISSUE TITLE
Deadlock on iOS if target is offline and using FQDN (second call)

### ISSUE THREAD

**Issue by AndreasReitberger** [restsharp/RestSharp#1679]
## Bug

I'm getting a deadlock when calling `client.ExecauteAsync(...)` while the target is offline on iOS.
However only on the second call and if the target is a FQDN.
IP-Addresses are working fine.

```cs
CancellationTokenSource cts = new(new TimeSpan(0, 0, 0, 10));
RestClient client = new(FullWebAddress);

RestRequest request = new(
                    $"{target}/{command}")
                {
                    RequestFormat = DataFormat.Json,
                    Method = method
                };

IRestResponse respone = await client.ExecuteAsync(request, cts.Token).ConfigureAwait(false);
```

## Expected Behavior
The CancellationTokenSource will cancel and the method return.

## Actual Behavior
At the moment, on the second call, the method never returns. However, as mentioned, only if the target is offline
and using the FQDN instead.

Working: http://192.168.x.x/api/...
Not working: http://servername.local/api

If the target is reachable, it's working fine.

## Steps to Reproduce the Problem

  1. On iOS, call the method await client.ExecuteAsync() using a cts to cancel after 10 seconds
  2. As target, use any FQDN, it's just important that it is offline
  3. Make the first call, the cts cancels the request as expected
  4. Make a second call, and verify that the method never returns

## Specifications

  - Version: Latest stable
  - Platform: iOS (Xamarin)
  - Subsystem:

## StackTrace
None
<details>

```

```

</details>

**Comment by AndreasReitberger** [comment]
Just updated to the 107-Preview version. So far as I can see, the issue doesn't come up with this version.
I do some further investigation and report back.

**Comment by alexeyzimarev** [comment]
I won't be making any changes in versions prior to v107, so if v107 works, please use it. It might have some minor issues, but it works way better than v106.

**Comment by AndreasReitberger** [comment]
Closed. seems to work stable with v107.
Thanks.
