### ISSUE TITLE
AddUrlSegment accepts object values but internally casts to strings causing exception

### ISSUE THREAD

**Issue by Guerra24** [restsharp/RestSharp#1682]
This change https://github.com/restsharp/RestSharp/commit/8e96bba46d7d2101319529ea68782a39aaa3bfa8#diff-5df1c2c9f9f84319d21c361a0a336251f7698927e2f1c0b0adab575fa407c6e6 simply [casts object values](https://github.com/restsharp/RestSharp/blob/5830af48cf85b8eaadf89d83fbc3bf46106f5873/src/RestSharp/Ensure.cs#L25) into strings, this is causing issues since the [public api accepts object values](https://github.com/restsharp/RestSharp/blob/8e96bba46d7d2101319529ea68782a39aaa3bfa8/src/RestSharp/Request/RestRequestExtensions.cs#L97).

**Comment by alexeyzimarev** [comment]
What do you expect the URL segment to be? It can only be a string. I don't remember that it worked differently ever.

**Comment by Guerra24** [comment]
First of all thanks for the quick fix!

> It would also be nice if you actually follow the contribution guidelines and provide stack trace and exception details.

Sorry about that. I thought pointing out the source of the issue and why it was an *issue* was descriptive enough. Will keep that in mind for next time.

**Comment by alexeyzimarev** [comment]
You're right. I got it right after looking into the links you provided. I usually scan the issue content, and when it has no stack trace, it looks incomplete to me :)

**Comment by alexeyzimarev** [comment]
Btw I made constructors for all parameter types (except the abstract one) more explicit. The old `AddParameter` has to, of course, accept `object?` but then I try converting those values to string, not cast them.

Also, `AddParameter` overload that doesn't accept the parameter type enum, as well as all `AddXXXParameter` now have explicit `string` or `string?` where it's appropriate (not files and body parameters).

**Comment by alexeyzimarev** [comment]
It will break some existing code of course... I understand that you got this error when passing something like a number or a boolean. Not sure how to fix it better. Maybe I need to return the overload that accepts `object`? It might lead to boxing though, need to check.

**Comment by alexeyzimarev** [comment]
Made this, and it clearly shows the boxing issue. Not such a big issue though.
![image](https://user-images.githubusercontent.com/2821205/148457527-6a070232-6653-4c0b-a887-5920afea5c82.png)
