### ISSUE TITLE
v107 and x-www-form-urlencoded

### ISSUE THREAD

**Issue by mabi** [restsharp/RestSharp#1686]
In v107 sending parameters as name=value x-www-form-urlencoded using
request.AddParameter("name", "value");
as stated in usage.md no longer works.
What is the correct way?

**Comment by alexeyzimarev** [comment]
Could you please check the exact version you're using? It should be multipart form in the latest version.

**Comment by mabi** [comment]
Version="107.0.1"
the issue is that body is no longer just name=value

**Comment by alexeyzimarev** [comment]
I don't understand what you need. Do you want to post as url encoded form or as multipart form data?

**Comment by mabi** [comment]
urlencoded form,
Content-Type: application/x-www-form-urlencoded

**Comment by milen-denev** [comment]
I want to mention that after I updated to 107.0.1 nothing works anymore. I am still working to find the reason behind that.

**Comment by milen-denev** [comment]
So I am concluding that in my case it simply doesn't add parameters (Using the AddParameter or AddOrUpdateParameter). 
I just nuked the changes and rolled backed the project and everything works fine with 106.15.0.

**Comment by alexeyzimarev** [comment]
@mabi the latest preview should work for you.

**Comment by mabi** [comment]
tested OK with version 107.0.2-alpha.0.5 more testing on monday.
Thank you @alexeyzimarev

**Comment by alexeyzimarev** [comment]
Released in 107.0.2, if you still get an issue, please reopen.
