### ISSUE TITLE
Making a synchronous request and sending response freeezes program

### ISSUE THREAD

**Issue by kc20121** [restsharp/RestSharp#1691]
## Actual Behavior
I'm using the following simple function
```csharp
        public static string GetMyIP()
        {
            RestRequest webshare_getproxy_ips = new RestRequest("https://ipinfo.io/ip", Method.Get);
            var response = mainclient_inner.ExecuteAsync(webshare_getproxy_ips, default).GetAwaiter().GetResult().Content;
            Console.WriteLine(response);
            return response;
        }
```

And I am calling the function onclick of a button, which would usually work with no issues, but in the latest update with async methods, it is no longer working and it freezes my whole program, it works if I use async or call the function from anywhere but the UI thread

## Steps to Reproduce the Problem

  1. Windows Forms Application, 
  2. Add a button
  3. call GetMyIP on click

## Specifications

  - Version: 107.0.2
  - Platform: Windows 10 64bit 21H2 with .Net Framwork 4.7.2

**Comment by alexeyzimarev** [comment]
It's not a RestSharp issue, it is a common deadlock problem with WinForms UI thread. Please google the issue and you'll find lots of proposed solutions on StackOverflow (for example). Most of them boil down to making the `OnClick` method `async void`. I am not sure what's the right solution, but you can easily try it out.

Also, I will merge my own PR today that adds `ConfigureAwait(false)` to all async calls inside RestSharp, which might help, although I am not exactly sure.

**Comment by kc20121** [comment]
> It's not a RestSharp issue, it is a common deadlock problem with WinForms UI thread. Please google the issue and you'll find lots of proposed solutions on StackOverflow (for example). Most of them boil down to making the `OnClick` method `async void`. I am not sure what's the right solution, but you can easily try it out.
> 
> Also, I will merge my own PR today that adds `ConfigureAwait(false)` to all async calls inside RestSharp, which might help, although I am not exactly sure.

Thank you very much for your response, by the way, tomorrow i'll be sponsoring you for your work on this awesome library.

**Comment by alexeyzimarev** [comment]
Thank you. Please don't hesitate to follow up here on your WinForms issue. I'll keep the issue closed, but we can still discuss possible solutions.

**Comment by alexeyzimarev** [comment]
This might actually work with the latest preview:

```csharp
var response = mainclient_inner.GetAsync("https://ipinfo.io/ip")
    .ConfigureAwait(false)
    .GetAwaiter().GetResult()
    .Content;
```

**Comment by kc20121** [comment]
> ```cs
> var response = mainclient_inner.GetAsync("https://ipinfo.io/ip")
>     .ConfigureAwait(false)
>     .GetAwaiter().GetResult()
>     .Content;
> ```

Hello! Thanks for your followup, the code you sent me had an issue, you can't send the URL directly to GetASync, you need to send it the restRequest, which is fine.

```cs
            var response = mainclient_inner.GetAsync(webshare_getproxy_ips)
                .ConfigureAwait(false)
                .GetAwaiter().GetResult()
                .Content;
```
I did, the problem persisted, i also tried changing the method of the button to async void and it also did not solve my problem

**Comment by alexeyzimarev** [comment]
You're right. Using the resource string is only available for `GetJsonAsync`.

**Comment by kc20121** [comment]
By the way, I am sorry if I am not using the correct terms, I am a self-taught programmer

The solution I used for this is basically just making a thread of the function, and then using P.Invoke to make changes on the UI thread,

**Comment by alexeyzimarev** [comment]
I quickly made this and it works just fine

```csharp
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WinFormsApp1
{
    public partial class Form1 : Form
    {
        RestClient client = new RestClient();
        public Form1()
        {
            InitializeComponent();
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            var result = await GetMyIP();
            textBox1.Text = result;
        }

        public async Task<string> GetMyIP()
        {
            var webshare_getproxy_ips = new RestRequest("https://ipinfo.io/ip", Method.Get);
            var response = await client.ExecuteAsync(webshare_getproxy_ips, default);
            Console.WriteLine(response.Content);
            return response.Content;
        }
    }
}
```

**Comment by kc20121** [comment]
I'm sorry, i was missing the await on GetMyIP(), it is working as intended, thank you!
