### ISSUE TITLE
Client request extensions don't throw

### ISSUE THREAD

**Issue by alexeyzimarev** [restsharp/RestSharp#1692]
Extensions like `GetAsync` or `PostAsync` should throw if the request wasn't successful.

However, it doesn't happen. The reason seems to be that the `RestResponse` instance gets the correct status (error), but doesn't get any exception set because of that. And, `ThrowIfError` only checks the exception, ignoring the status.

**Comment by alexeyzimarev** [comment]
Released in 107.0.3

**Comment by m1dst** [comment]
Shouldn't be closed...

**Comment by m1dst** [comment]
Shouldn't be closed and should be fixed.

**Comment by alexeyzimarev** [comment]
The issue is quite trivial to fix, I am wondering why no one opens a PR to get rid of this issue.

**Comment by m1dst** [comment]
Don't think this ever got fixed.

**Comment by alexeyzimarev** [comment]
It wasn't, but who supposes to fix it? I see you @m1dst commented quite a lot on this, have you considered spending 20 min of your time fixing it?

**Comment by m1dst** [comment]
I see there is a PR that is open which is related to this.   https://github.com/restsharp/RestSharp/pull/2128

**Comment by alexeyzimarev** [comment]
They weren't linked, I am checking with the PR author if it addresses this issue.
