### ISSUE TITLE
107.0.2 Response content always encoded with Encoding.Default 

### ISSUE THREAD

**Issue by andrewkip** [restsharp/RestSharp#1693]
Hello!
I've mentioned that response content always encoded with Encoding.Default.

as I can see the problem is in RestSharp/src/RestSharp/Response/ResponseHandling.cs 

static class ResponseHandling {
    public static string GetResponseString(this HttpResponseMessage response, byte[] bytes) {

   var encodingString = response.Content.Headers.ContentEncoding.FirstOrDefault(); 

ContentEncoding has'no info about charset

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

may be it is better to get charset info from 
response.Content.Headers.ContentType.CharSet?

**Comment by alexeyzimarev** [comment]
Yes, you're right. It worked before because I was using `ReadAsStringAsync` of `HttpResponseMessage`, but it is behaving strangely on some platforms. I think getting the encoding from the charset is the right way.

**Comment by andrewkip** [comment]
Great to hear it. 
Thanks.
By the way if no charset speicifined in Response ContentType how to define charset differ from Encoding.Default?

**Comment by alexeyzimarev** [comment]
In your case, is it the same encoding for request and response? I can use the client option called `Encoding` as a fallback.

**Comment by andrewkip** [comment]
> In your case, is it the same encoding for request and response?

Yes

> I can use the client option called `Encoding` as a fallback

Good decision! 

Thanks

**Comment by alexeyzimarev** [comment]
Released in 107.0.3

**Comment by andrewkip** [comment]
Works like a charm 👍 

Thank you!!!
