### ISSUE TITLE
Please add NtlmAuthenticator back

### ISSUE THREAD

**Issue by GalynaBatig** [restsharp/RestSharp#1694]
## Actual Behavior
src/RestSharp/Authenticators/NtlmAuthenticator.cs was deleted, please see changes in https://github.com/restsharp/RestSharp/pull/1661

Can it be added back? It worked fine in v106 for my needs..
Thank you,
Galyna

**Comment by alexeyzimarev** [comment]
I provided the details in the PR, so I don't understand why it needs any more discussion. Authenticators work on per-request base, which is not how NTML works with `HttpClient` and it cannot be done by an authenticator, but it works out of the box with options.

**Comment by GalynaBatig** [comment]
Thank you! Sorry, I did not see your explanation in the PR. Now everything works well for me.

**Comment by alexeyzimarev** [comment]
Added to the docs as well https://restsharp.dev/v107/#ntml-authentication
