### ISSUE TITLE
Body Parameter Missing on RestRequest

### ISSUE THREAD

**Issue by CenturySparkle** [restsharp/RestSharp#1695]
## Expected Behavior
Able to get the body content from the RestRequest object.

## Actual Behavior
Property is now missing

## Steps to Reproduce the Problem

  1. Upgrade from 106 to 107

**Comment by alexeyzimarev** [comment]
Body parameter can be found among other parameters in the `Parameters` collection

```csharp
    public ParametersCollection Parameters { get; } = new();
```

**Comment by CenturySparkle** [comment]
Thanks, would not have expected this.  And it's not documented.  (That I could find.)

**Comment by alexeyzimarev** [comment]
I see... I guess it doesn't hurt to make them public.

Before it happens, you might just query the collection, as `ParametersCollection` implements `IEnumerable<Parameter>`.

```csharp
public static class RestRequestBodyExtension {
    public static BodyParameter? GetBody() {
        var body = parameters.Where(x => x is T).FirstOrDefault();
        return body == null ? null : body as BodyParameter;
    }
}
```

**Comment by alexeyzimarev** [comment]
I guess I can make this class public, it only has queries

https://github.com/restsharp/RestSharp/blob/ed1ac08d4cea8ee39c03fe3a489bf47a1d94e3df/src/RestSharp/Request/BodyExtensions.cs#L18-L27

**Comment by CenturySparkle** [comment]
Thanks, that extension class would work nicely.  In the meantime, I will use LINQ to pull it out.

**Comment by alexeyzimarev** [comment]
To clarify, the reason for those queries to be internal, as they should normally not be used. If you use it to test your requests, I'd actually suggest using `MockHttp` as it allows you to test the actual request, with all its bells and whistles. As well as you can give it an expected response. So, you also ensure that everything (de)serializes correctly, etc.

But, I might be missing some other use cases you might have.

**Comment by CenturySparkle** [comment]
My use case is for logging.  In the case of an error, we log both the request and response for better production support.

Just at a quick glance, I do like the consolidated error handling with the new version.

**Comment by alexeyzimarev** [comment]
Right, that makes sense. When the diagnostic part is done, it would be easier to log issues. I will think about it, maybe there are some more improvements that can be made for better issue diagnostics.
