### ISSUE TITLE
AddFile does not send content length when using byte array

### ISSUE THREAD

**Issue by antonioatom** [restsharp/RestSharp#1699]
## Expected Behavior
When doing a request with a file upload.
request.AddFile(name, byteArray, filename, contentType);

When receiving the file on the api endpoint the request content length should be > 0.

## Actual Behavior

using the method above the content length on the IFormFile is reported as 0.
If using the method that uses Func<Stream> where you explicitly pass the content length, it works fine. It seems when creating the FileParameter using the bytearray the content length is not passed.

## Steps to Reproduce the Problem

  1. Call a post method with AddFile using a bytearray.

## Specifications

  - Version: 107.0.3
  - Platform: Windows (.net 6.0)

**Comment by alexeyzimarev** [comment]
> If using the method that uses Func where you explicitly pass the content length

Could you please clarify this? There's no single `AddFile` overload that explicitly accepts the content length.

**Comment by antonioatom** [comment]
> > If using the method that uses Func where you explicitly pass the content length
> 
> Could you please clarify this? There's no single `AddFile` overload that explicitly accepts the content length.

Sorry, the old version received the content but I've updated and forgot to edit my note:
So the working method is 
AddFile(string name, Func<Stream> getFile, string filename, string? contentType)

The not working method is:
AddFile(string name, byte[] bytes, string filename, string? contentType)

**Comment by alexeyzimarev** [comment]
I think it doesn't upload anything when you send the bytes array, and I think it's because I write the array to a stream, but I don't flush the stream and don't seek to zero after writing. I am adding some tests for it now.

**Comment by antonioatom** [comment]
[RestSharpTest.zip](https://github.com/restsharp/RestSharp/files/7862953/RestSharpTest.zip)

I've created a simple test API / Client that shows the problem

**Comment by alexeyzimarev** [comment]
It was what I thought it was. The latest preview should work.

**Comment by alexeyzimarev** [comment]
Btw if the controller code in your repro project, which posts the file, is what you use in your real app, I would advise not to do it like this.

**Comment by antonioatom** [comment]
> Btw if the controller code in your repro project, which posts the file, is what you use in your real app, I would advise not to do it like this.

No, this was just a quick and dirty example just to repro the problem but thanks for your concern and for your quick replies

**Comment by bfcavaco** [comment]
Hi,

I'm using the same method of antonioatom and still get this error on preview version: "StatusCode: InternalServerError, Content-Type: application/json, Content-Length: 16)"
my code:
                RestClient client = new(strResource);
                RestRequest request = new("", Method.Post);
                request.AddParameter("Accept-Encoding", "multipart/form-data", ParameterType.HttpHeader);
                request.AddParameter("Authorization", CalibryAuthentication.CalibryToken, ParameterType.HttpHeader);
                request.AddFile("file", strFile, "application/pdf");
                var restResponse = client.ExecuteAsync(request).Result;

**Comment by antonioatom** [comment]
You are getting a 500 and you Content-Length is more than 0 so I don't think this issue is directly related
So you have access to the server endpoint you are calling?

BTW does the code works on 106.*?

The changes were only made on 107 so it should work on 106.

**Comment by alexeyzimarev** [comment]
multipart/form-data is not encoding, it's content type. If you are trying to set the content type, please don't.

**Comment by bfcavaco** [comment]
Hi António,

Yes it works on 106, I kept that version until I'm able to use it on
version 107.

Thank you for the reply.
Best regards,

Bruno Cavaco.

António Albuquerque ***@***.***> escreveu no dia sexta,
21/01/2022 à(s) 09:34:

**Comment by bfcavaco** [comment]
Thank you for the replay,

I just make confuse because was working on version 106.
I'm keeping version 106 until I fix this on version 107.

Best regards,
Bruno Cavaco.


Alexey Zimarev ***@***.***> escreveu no dia sexta, 21/01/2022
à(s) 12:56:
