### ISSUE TITLE
Json Deserialization doesn't support arrays

### ISSUE THREAD

**Issue by jonnii** [restsharp/RestSharp#170]
When deserializing an object which has an array of sub items the default json deserializer complains that there's no default constructor (arrays don't have default constructors).

For now I've replaced the json deserializer with this:

```
public class CustomJsonDeserializer : IDeserializer
{
    public T Deserialize<T>(RestResponse response) where T : new()
    {
        return JsonConvert.DeserializeObject<T>(response.Content);
    }

    public string RootElement { get; set; }

    public string Namespace { get; set; }

    public string DateFormat { get; set; }
}
```

I don't need the date format/namespace/root element stuff. That said, I think the naming convention stuff could use json.net contract resolvers, it might be a cleaner implementation and defer more work to the json.net.

**Comment by Lechus** [comment]
2016 and still no support for arrays? oh

**Comment by hallem** [comment]
@Lechus i'm not sure why you've commented on a really old closed issue...  are you experiencing issues? if so please provide some information and I'll see what i can do to help

**Comment by Lechus** [comment]
@hallem I have to generate classes from XSD so there are arrays (the XSD right now change too often to replace arrays with lists) and default JSONDeserialzier fails. Right now I added handler for json response to use NewtonSoft JsonDeserializer wrapper. 
In theory Arrays could be deserialized to List and then .ToArray() call in built-in JSON deserializer?

**Comment by hallem** [comment]
for right now that's the best solution we have available until i get off the base handler.  it's a little limited when compared to newtonsoft but gets the job done more than 90% of the time.  i'm looking into other ones and possibly switching back to using newtonsoft at the core.

**Comment by heliopassarelli** [comment]
Using `JavaScriptSerializer().Deserialize<List<RootObject>>` not solved?
