### ISSUE TITLE
Problem sending Protobuf content in latest version

### ISSUE THREAD

**Issue by martyt** [restsharp/RestSharp#1700]
Prior to v.107, we used the following code to send a compressed Protobuf payload (an array of bytes, essentially). We've been unable to find the magic sauce for making this work in v.107.
```
            var client = new RestClient("someUrl");

            byte[] compressedBytes;
            var ms = new MemoryStream();
            await using (ms.ConfigureAwait(false))
            {
                var gzip = new GZipStream(ms, CompressionMode.Compress);
                await using (gzip.ConfigureAwait(false))
                {
                    Serializer.Serialize(gzip, request);
                } // scoping ensures gzip stream is flushed and closed

                compressedBytes = ms.ToArray();
            }

            var request = new RestRequest("someMethod", Method.POST);

            // we're sending a gzip'd request in protobuf format
            request.AddHeader("Content-Encoding", "gzip");
            request.AddParameter("application/x-protobuf", compressedBytes, ParameterType.RequestBody);

            // we want protobuf response
            request.AddHeader("Accept", "application/x-protobuf");

            var result = await client.ExecuteAsync(request);
  ```
Now, when we call `.AddParameter()` as shown above, we get an exception: 

```
System.ArgumentException: Non-string body found with unsupported content type (Parameter 'obj')
   at RestSharp.RestRequestExtensions.AddBody(RestRequest request, Object obj, String contentType)
```

I've tried 
```
            request.RequestFormat = DataFormat.None;
            request.AddBody(compressedBytes, "application/x-protobuf");
```
but get the same exception. 

The v107 migration guide suggests that `IRestRequest` has an extension method `AddParameter(string name, object value, string contentType, ParameterType type)` but no such method exists with the given signature. 

I considered a custom serializer, but the `IRestSerializer` interface seems to want `string` as the return from `Serialize()`, which doesn't make any sense. 

Essentially, all I want to do is specify an opaque block of bytes as the request body and set the content type myself, but it seems like v107 doesn't want to play nice in that regard.

Suggestions?

**Comment by alexeyzimarev** [comment]
`AddParameter` won't work in your case as it is not designed to handle byte arrays. I forgot about protobuf, sorry.

About the method suggested by the migration guide, there's just one parameter missing (`bool encode`), but it will only create a `BodyParameter`, which you can also instantiate yourself, it would be more explicit. But it will still try converting the value to a string.

I think the best way is to make a proper serializer, but you're right, the current implementation should return a string. It's a bummer. It's not easy to change without breaking the API.

I added a quick fix to the `BodyParameter`. This might work in the latest preview when it gets published:

```csharp
var request = new RestRequest("someMethod", Method.POST)
    .AddParameter(new BodyParameter("", compressedBytes, "application/x-protobuf") { ContentEncoding = "gzip" });
```

**Comment by martyt** [comment]
@alexeyzimarev Thanks for the quick response. That fix looks like it would work for us, I'll test it when the next preview comes out.

**Comment by alexeyzimarev** [comment]
It's already out https://www.nuget.org/packages/RestSharp/107.0.4-alpha.0.5

**Comment by martyt** [comment]
@alexeyzimarev Thanks, installed and tested and it's working great. Appreciate the fast fix! When do you expect the next official release to come out?

**Comment by alexeyzimarev** [comment]
Got two tests failing, completely unrelated. Will try to look into them tomottow.

**Comment by alexeyzimarev** [comment]
The version is out, so I believe you got it working.

My question is: do you use a "normal" HTTP API with Protobuf as a serialization method, or you use gRPC?

**Comment by martyt** [comment]
@alexeyzimarev We don't use gRPC at present. But we have a number of internal APIs that require either Protobuf serialized content or some other opaque binary payload, so the changes you made have been greatly helpful. We've integrated the latest build with our code and it's working great.
