### ISSUE TITLE
Question: Does AddJsonBody with DateTime properties convert a DateTime with Kind Unspecified, in any way?

### ISSUE THREAD

**Issue by Korporal** [restsharp/RestSharp#1701]
This not an issue or suspected bug report, just a question.

If I pass a DateTime that has Kind set to Unspecified and that was set to "11/7/2021 23:59:59" what does RestSharp do in order to convert that to a string and embed it in the JSON text body?

Does it "convert" it in anyway (and this the time changes) or does it leave it as is and just append "Z" to make it look like a UTC time?

Any clarification is appreciated.

**Comment by alexeyzimarev** [comment]
`AddJsonBody` doesn't do anything with the date format by default, and `DateFormat` cannot be passed to a JSON request since v107.

And this:
![Screenshot 2022-01-13 at 20 42 02](https://user-images.githubusercontent.com/2821205/149398362-13582aca-06fa-4ade-aff9-572108321bc3.png)

**Comment by Korporal** [comment]
@alexeyzimarev 

The cavalier attitude to what was a polite question with a follow up question is all the evidence I need that we should dump RestSharp.

**Comment by alexeyzimarev** [comment]
Thank you for your feedback.
