### ISSUE TITLE
Changes in serialisation

### ISSUE THREAD

**Issue by alexeyzimarev** [restsharp/RestSharp#1703]
Current serialization doesn't support producing binary payloads, which is a serious limitation. Applications might need to post Protobuf or BSON requests, and now it's only possible with the `BodyParameter` using `DataFormat.Binary`, plus manual (de)serialization, which is quite verbose.

The best way to fix it is to change the way how serialization works. Returning a `string` is limiting, so, here's the plan:
- Simplify the serializer interface, leave only one (`IRestSerializer`)
- Refactor both XML serializers accordingly
- Fix the unsafe serialization issue in the XML serializer (namespace reassignment)
- Use request and response encoding in serializers as it should've been done long ago
- Make serializers produce bytes
- Make deserializers to accept bytes

**Comment by schuettecarsten** [comment]
This code worked with earlier versions of RestSharp, but fails with v107.3.0:

```
RestRequest request = this.CreateRequest(@"uploads.json");
request.AddHeader(@"Content-Type", @"application/octet-stream");
request.AddParameter(@"file", attachmentData, ParameterType.RequestBody);
```

It only sends "System.Byte[]" as content.
To make it work again, I had to change the `AddParameter` to:

```
request.AddParameter(new BodyParameter(@"file", attachmentData, @"application/octet-stream", DataFormat.Binary));
```

**Comment by alexeyzimarev** [comment]
@schuettecarsten how is your comment related to the issue? The answer to your inquiry is in the documentation https://restsharp.dev/usage.html#uploading-files

**Comment by schuettecarsten** [comment]
@alexeyzimarev I think it is related because something was changed under the hood that breaks working code from earlier versions and this has to do with serialization or how RestSharp handles parameters. If you think it is not related to, simply ignore my comments. I found a workaround. Btw, AddFile does not work for me, as the target API is broken, but cannot be changed. That's why I had to use AddParameter.

**Comment by alexeyzimarev** [comment]
It's not related to serialization as you are just posting a file as an octet-stream. The way how serialized payloads are handled didn't change between v106 and v107.

I asked the question because it seems like a completely different issue. If you can elaborate on why `AddFile` doesn't work, I might have an answer for you. Also, as adding a `BodyParameter` worked for you, it can be shortened to `AddBody(attachmentData, "application/octet-stream")` as this function will detect the byte array and add the parameter the same way you already do.

**Comment by alexeyzimarev** [comment]
The problem why `AddParameter` with content type as its name stopped working (maybe I need to explicitly mention this) is because it was awkward and implicit to use the content type as the parameter name, and after I added the `contentType` function parameter to all non-specific `AddParameter` overloads it started to contradict the ability to name the parameter. Previously, RestSharp was unable to post more than one body parameter, and this limitation is now gone. This means that you probably need to name parameters properly so they can be properly posted as multipart-form data payload.

**Comment by cYCL157** [comment]
it would be nice if DotNetXmlSerializer would implement IRestSerializer so that it could be used with UseSerializer as would be expected for jsonnetserializer or any custom serializer.

**Comment by alexeyzimarev** [comment]
Not sure what's the issue @cYCL157 https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp.Serializers.Xml/XmlSerializerClientExtensions.cs
