### ISSUE TITLE
Build error re:RestResponsebase.StatusCode running MsBuild2019 to build project with RestSharp

### ISSUE THREAD

**Issue by mhagesfeld** [restsharp/RestSharp#1705]
## Expected Behavior
Project builds successfully using MSBuild via Jenkins

## Actual Behavior
Build fails with the following message:
error CS1545: Property, indexer, or event 'RestResponseBase.StatusCode' is not supported by the language; try directly calling accessor methods 'RestResponseBase.get_StatusCode()' or 'RestResponseBase.set_StatusCode(??)'

## Steps to Reproduce the Problem

  1. Code: 
  ```
var response = Task.Run(() => restClient.ExecuteAsync(request)).Result;
            if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
```
            
  2. Built using MSBuild 2019, -t:build -restore /p:Configuration=Release
  3. 

## Specifications

  - Version: 107.0.3
  - Platform: Windows 10
  - Subsystem: Jenkins

## StackTrace
<details>
error CS1545: Property, indexer, or event 'RestResponseBase.StatusCode' is not supported by the language; try directly calling accessor methods 'RestResponseBase.get_StatusCode()' or 'RestResponseBase.set_StatusCode(??)'
```

```

</details>

**Comment by mhagesfeld** [comment]
Note - I moved back to version 106 and it is building successfully.

**Comment by alexeyzimarev** [comment]
Sorry, I have no plans to support custom builds. You can check GitHub Actions workflow in the repository to see how it builds.
