### ISSUE TITLE
Would you mind helping me please?

### ISSUE THREAD

**Issue by Pureaznangel** [restsharp/RestSharp#1706]
May anyone give me a full example of code how to use this new version of restsharp please? New version seem breaking all code that working fine to me (older version), in a big project with exist wrapping classes.

I'm not familiar with this kind of using HTTP CLIENT as this describe:

"RestClient should be thread-safe. It holds an instance of HttpClient and HttpMessageHandler inside. Do not instantiate the client for a single call, otherwise you get issues with hanging connections and connection pooling won't be possible.

Do create typed API clients for your use cases. Use a single instance of RestClient internally in such an API client for making calls. It would be similar to using typed clients using HttpClient, for example....."

and confusing about this: "Do not use one instance of RestClient across different API clients."

Thanks,

**Comment by alexeyzimarev** [comment]
- It is [documented](https://restsharp.dev/usage.html#recommended-usage), and it is the same as for the previous version
- You don't have to migrate to v107 if the previous version works for you.
- Microsoft provides good [documentation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#implement-your-typed-client-classes-that-use-the-injected-and-configured-httpclient) about using `HttpClient` properly, the same recommendations apply to RestSharp as it is wrapping `HttpClient`.
- We specifically request not to ask questions using GitHub issues and warn that such issues will be closed.
