### ISSUE TITLE
Disposing of HttpClient and HttpMessageHandler

### ISSUE THREAD

**Issue by alexeyzimarev** [restsharp/RestSharp#1711]
This issue is covering the discussion of the commit that adds `IDisposable` interface to `RestClient`, and `HttpClient` disposal.

Here is the discussion: https://github.com/restsharp/RestSharp/commit/95f1324207d60223886566dbc9f1e16ea4294860#r64077599

**Comment by alexeyzimarev** [comment]
@jnyrup I think it should be fine in the latest preview.

**Comment by jnyrup** [comment]
Looks good.
I've got no further comments about the disposing of `RestClient`.

**Comment by alexeyzimarev** [comment]
Thank you for your review. I think it makes sense to make `RestRequest` sealed btw.
