### ISSUE TITLE
Issue with AddFile on Request

### ISSUE THREAD

**Issue by iamsubingyawali** [restsharp/RestSharp#1714]
I am using Restsharp to send a POST request to my REST API running Laravel. Specifically, what I am trying to do is to create a new user from my WPF app which sends some user details and profile image as post params. I tried the same thing with Postman and it is working fine but it didn't work as expected while using Restsharp. I am getting `PHP Warning:  File Upload Mime headers garbled in Unknown on line 0` on my Laravel server.

Code I am using:

```
RestRequest restRequest = new RestRequest("user", Method.Post); 
restRequest.AlwaysMultipartFormData = true;
restRequest.AddHeader("Content-Type", "multipart/form-data");

// Adding other post params
// post_data is a dictionary: Dictionary<string, object> post_data;
post_data.Add("firstname", FirstNameField.Text.Trim());
// and so on
restRequest.AddJsonBody(post_data);

// Adding files
// profile_image is link to the file: E:\MyFiles\Pictures\Screenshots\Screenshot (7).png
restRequest.AddFile("photo", profile_image);
var response_json = await client.ExecuteAsync<JObject>(restRequest);
```

**Environment**
 - OS: Windows 11
 - .NET5 WPF
 - Version 107.1.1
 - Server: Laravel v8.58.0 (PHP v8.0.13)

**Comment by alexeyzimarev** [comment]
How does the request look like in Postman?

**Comment by iamsubingyawali** [comment]
Postman Screenshot:

![image](https://user-images.githubusercontent.com/45819206/150088668-503269d6-1433-4b37-852d-7a274f33709e.png)

**Comment by alexeyzimarev** [comment]
Please use something like https://requestbin.com to compare the request posted with Postman, and with RestSharp. Expand the headers section, and use raw content view when making screenshots.

**Comment by alexeyzimarev** [comment]
I don't think you are posting JSON with Postman, I think you post the form data. Please just take a screenshot from requestbin.com of the raw request coming from Postman.

**Comment by iamsubingyawali** [comment]
Yes, I am using form-data to send the data from Postman as we can't attach file using other formats in Postman. I extracted those requests from the server itself.

**Comment by alexeyzimarev** [comment]
You need to make a choice, whether you are posting form data, or you are posting a JSON payload.

Posting form parameters with RestSharp is done by using `AddParameter(name, value)`, as it is described in the docs.

**Comment by iamsubingyawali** [comment]
I think `AddParameter` fulfils my need. Thanks!
