### ISSUE TITLE
In multipart form, JSON part is missing the JSON content type in the content disposition header

### ISSUE THREAD

**Issue by kbilkhoo** [restsharp/RestSharp#1716]
Describe the bug
**Request.Form containd no data**

To Reproduce

**client side**

        var request = new RestRequest(resource);
        var jsonData = new
        {
                Company = "Microsoft",
                ZipCode = "LS339",
                Country = "USA"

        };

        request.RequestFormat = DataFormat.Json;
        request.Method = Method.Post;
        request.AddHeader("Content-Type", "multipart/form-data");
        request.AddFile("content", file, "application/octet-stream"); 
        request.AddJsonBody(jsonData);

        var response = client.ExecuteAsync(request).Result;

**server side**

       var request = HttpContext.Current.Request;
       Request.Form[0]; // index out of range exception

Expected behavior

        Request.Form[0]; // expected data

Stack trace
There is not stack trace for this issue. Except behaviour has changed
after upgrading from 106.13.0 to 107.1.1

106.13.0 ->  Request.Form contains key called 'application/json'
107.1.1 ->  Request.Form no data

Desktop (please complete the following information):

OS: Windows 10
.NET version 4.7.2
Version: 107.1.1
**Additional context**

workaround 

changed request.AddJsonBody(jsonData) ->request.AddParameter("application/json", JsonConvert.SerializeObject(jsonData));
has resolved the issue in 107.1.1

**Comment by alexeyzimarev** [comment]
Have you followed the bug report issue template? We ask to trace both working and non-working requests, so it's possible to see the difference.

**Comment by kbilkhoo** [comment]
Sorry I did not, but can do later on if you wish

**Comment by alexeyzimarev** [comment]
Here is what I found.

RS 106 JSON data:

```
Content-Type: application/json.
Content-Disposition: form-data; name="application/json".
.
{"Company":"Microsoft","ZipCode":"LS339","Country":"USA"}.
```

RS 107:

```
Content-Type: application/json; charset=utf-8.
Content-Disposition: form-data.
.
{"company":"Microsoft","zipCode":"LS339","country":"USA"}.
```

Apparently, the content type for the JSON form part is not set properly in the content disposition header. I'll look into it.

**Comment by alexeyzimarev** [comment]
No, I think I wrote some rubbish. The content type is correct. The only difference is that the part _name_ is not set to "application/json", which doesn't seem to be any kind of requirement.

Nevertheless, I must've been there for a reason to use the body parameter content type as the content disposition form part name. Looks weird to me, but who knows. The 107.1.2-alpha.0.10 sets it as before, you might want to try it out.

**Comment by kbilkhoo** [comment]
Hi, Upgraded to 107.1.2-alpha.0.18 now I get a different error, when calling client.ExecuteAsync(request).Result;
 
Message = "The type initializer for 'RestSharp.HttpContentExtensions' threw an exception."

Message = "Instance field '_boundary' is not defined for type 'System.Net.Http.MultipartContent'"

   at RestSharp.HttpContentExtensions.GetFormBoundary(MultipartFormDataContent content)
   at RestSharp.RequestContent.GetContentTypeHeader(String contentType)
   at RestSharp.RequestContent.<AddHeaders>g__AddHeader|15_1(Parameter parameter)
   at RestSharp.Extensions.CollectionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at RestSharp.RequestContent.AddHeaders()
   at RestSharp.RequestContent.BuildContent()
   at RestSharp.RestClient.<ExecuteInternal>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestSharp.RestClient.<ExecuteAsync>d__0.MoveNext()

**Comment by alexeyzimarev** [comment]
It seems to be platform-specific. I expected it, the old code is still in place. The issue is that the `MultipartFormBoundary` class doesn't expose the boundary property, although they have it inside. The current implementation accesses it via reflections, but I thought it might not work on some platforms.

I am considering replacing the boundary generated by the content class with another GUID that I can keep and access. It should resolve the issue.

**Comment by alexeyzimarev** [comment]
And, I think you are not on .NET 5 or 6, right?

**Comment by kbilkhoo** [comment]
correct, we are currently using .NET 4.7.2 to test the API,

**Comment by alexeyzimarev** [comment]
Ok, it's better than I thought. It's possible to provide the boundary value instead of letting the content generate it.

**Comment by alexeyzimarev** [comment]
I removed all the stuff with reflections, plus it's now possible to override the boundary if necessary. All good. Please try the next alpha when it gets published, it will take a few minutes.

**Comment by alexeyzimarev** [comment]
I expect that after all the changes those requests will be identical, except the charset in the content type. If it still won't work, you can try eliminating the charset by setting `request.DisableCharSet = true`

**Comment by alexeyzimarev** [comment]
Any news?

**Comment by kbilkhoo** [comment]
all works as expected, thanks
