### ISSUE TITLE
Cannot set content type to multipart/mixed; boundary=changeset

### ISSUE THREAD

**Issue by TimSirmovics** [restsharp/RestSharp#1726]
Before v107 I was able to add a string body with a content type of `multipart/mixed; boundary=changeset` as follows:
`new RestRequest("resource") { Body = new RequestBody("multipart/mixed; boundary=changeset", string.Empty, "body") };`

I have updated this to
`new RestRequest("resource").AddBody("body", "multipart/mixed; boundary=changeset");`

But this results in a format exception within System.Net.Http code:
 `System.FormatException: The format of value 'multipart/mixed; boundary=changeset' is invalid.`

I have also tried `AddStringBody`, and using the `FormBoundary` property but was not able to get around this exception.

I found this related issue: https://github.com/dotnet/runtime/issues/20272 however I was not able to work out how to use any of their workarounds.

**To Reproduce**
```
var client = new RestClient("baseUrl");
var request = new RestRequest("resource").AddBody("body", "multipart/mixed; boundary=changeset");
await client.PostAsync(request);
```

**Expected behavior**
To be able to send a string body, with the content type "multipart/mixed; boundary=changeset".

**Stack trace**
```
System.FormatException: The format of value 'multipart/mixed; boundary=changeset' is invalid.
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.Headers.MediaTypeHeaderValue..ctor(String mediaType)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at RestSharp.RequestContent.Serialize(BodyParameter body)
   at RestSharp.RequestContent.AddBody(Boolean hasPostParameters)
   at RestSharp.RequestContent.BuildContent()
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClientExtensions.PostAsync(RestClient client, RestRequest request, CancellationToken cancellationToken)
```

**Comment by alexeyzimarev** [comment]
You can use

```csharp
var request = new RestRequest("resource") { FormBoundary = "changeset" }
     .AddHeader(KnownHeaders.ContentType, "multipart/mixed");
```

When RestSharp sees you are setting the content type header without the actual body, it will add an empty body.

**Comment by alexeyzimarev** [comment]
It would help if you specify how do you need your request to look like.

**Comment by TimSirmovics** [comment]
> You can use
> 
> ```cs
> var request = new RestRequest("resource") { FormBoundary = "changeset" }
>      .AddHeader(KnownHeaders.ContentType, "multipart/mixed");
> ```
> 
> When RestSharp sees you are setting the content type header without the actual body, it will add an empty body.

I tried this, along with `AddStringBody("body", DataFormat.None)` after the AddHeader, but the Content-Type was only set to `multipart/mixed` and not `multipart/mixed; boundary=changeset`

> It would help if you specify how do you need your request to look like.

I am trying to use a batch request of an OData API, similar to the example here https://www.odata.org/documentation/odata-version-3-0/batch-processing/

The body is a string I have already built.
The Content-Type header needs to be `multipart/mixed; boundary=changeset`.

**Comment by TimSirmovics** [comment]
I have fallen back to `HttpClient` as a workaround for now.

**Comment by alexeyzimarev** [comment]
MInd posting your HttpClient code?

**Comment by alexeyzimarev** [comment]
I got this code:

```csharp
var request = new RestRequest("resource") { FormBoundary = "changeset", AlwaysMultipartFormData = true};
request.AddStringBody(json, ContentType.Json);
var response = await client.PostAsync(request);
```

and it produces the following result:
![image](https://user-images.githubusercontent.com/2821205/152116477-10be8e50-0fc5-4ac6-8a00-bc1bab6e95f1.png)

**Comment by TimSirmovics** [comment]
That works in regards to setting the `Content-Type` header correctly, thanks.

The next problem is, I need to format the request exactly like this:

**Header:**
`Content-Type: multipart/mixed; boundary=changeset`

**Body:**
```
--batch
Content-Type: multipart/mixed; boundary=changeset
--changeset
Content-Type: application/http 
Content-Transfer-Encoding: binary 
Content-ID: 1

PUT https://api.com HTTP/1.1
Content-Type: application/json

{ "foo": "bar1" }
--changeset
Content-Type: application/http 
Content-Transfer-Encoding: binary 
Content-ID: 2

PUT https://api.com HTTP/1.1
Content-Type: application/json

{ "foo": "bar2" }
--changeset
--batch--
```

The set of `--changeset`'s are wrapped with a `--batch` / `--batch--`.
The same `Content-Type` as the header is repeated after the opening `--batch`.
Previously I created the entire body as a string, from the opening`--batch` to the closing `--batch--` with all of the `--changeset`'s in between.
Using the method above I have tried `AddStringBody()` and `AddBody()` but it always wraps my body within a `--changeset`.

Is this supported?

**Comment by alexeyzimarev** [comment]
Sorry, but nested multipart content is not supported at the moment. Please open a new feature request for that. I will close this issue as the original problem is not an issue.

**Comment by empty-k** [comment]
@TimSirmovics Having the same trouble as you were here - I've spent the better part of the day fighting to create a POST request in this format, to send a batch of requests to an ODP db through a REST api.  

I have tried a myriad of things - Ive come to the point of creating an instance of MultipartContent and adding to it a StringContent object with all of my changeset info.
Everything formats perfectly except the content-type under the --batch - no matter what I do, I can't get it to accept 'multipart/mixed; boundary=part' (my sub boundary is 'part')

You mentioned you had fallen back to using httpclient to to get it done - which is what I'm using; would you be willing to share an example of how you were able to create the request with the proper formating?

**Comment by alexeyzimarev** [comment]
The thing is, if there's working code that uses HttpClient, it would show an implementation example that could be brought to RestSharp. However, the original issue clearly shows that `System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat` function doesn't like that content type.

Still, setting the boundary as part of content type creates weird side effects. Like, is the boundary of the content the same? Because if not, the request won't be accepted.

Btw `RestRequest` allows overriding the boundary:

```csharp
    /// <summary>
    /// Overrides the default (random) form boundary
    /// </summary>
    public string? FormBoundary { get; set; }
```
