### ISSUE TITLE
V107.2.0 unable to set Content-Type header

### ISSUE THREAD

**Issue by FSichinger** [restsharp/RestSharp#1731]
**Describe the bug**
before 107 i was able to set content type to whatever i wanted, but after updating I`m unable to change request content type. Something is setting content type to text/plain and i`m unable to change this behavior.

**To Reproduce**
```
            var restRequest = new RestRequest(@"/oauth2/token");
            restRequest.AddHeader(KnownHeaders.ContentType, "application/json");
            restRequest.AddParameter("application/x-www-form-urlencoded", "grant_type=client_credentials&scope=" + scope, ParameterType.RequestBody);
            
            var authenticator = new HttpBasicAuthenticator(ClientID, ClientSecret);
            _ = authenticator.Authenticate(Client, restRequest);
            var response = await Client.ExecutePostAsync<AccessToken>(restRequest);
```

**Expected behavior**
Calling AddHeader should not be ignored.

Request dump:
```
==================== HTTP REQUEST: [POST] ==================== 
    POST .../api/oauth2/token
    Accept: application/json
    Authorization: Basic MTY4OTMzNzQ1MjpDS3I3RnlFRQ==
    --4c7cc334-7992-4d04-8829-1c2204737ccf
    Content-Type: text/plain; charset=utf-8
    Content-Disposition: form-data; name="application/x-www-form-urlencoded"
     grant_type=client_credentials&scope=all
    --4c7cc334-7992-4d04-8829-1c2204737ccf--
```

 - OS: win10
 - .NET version .NET 5
 - Version 107.2.4 - the problem can be reproduced on 107.1 as well.

**Comment by alexeyzimarev** [comment]
I am not sure what you are trying to do, honestly.

You are posting a form url-encoded content, this _must_ set the content type to `application/x-www-form-urlencoded`. What `application/json` has to do with it? Are you sure you are not confusing `Content-Type` with `Accept`?

this code

```csharp
var options = new RestClientOptions("https://endim2jwvq8mr.x.pipedream.net/");
var client  = new RestClient(options);
var request = new RestRequest("oauth2/token");
// request.AddHeader(KnownHeaders.ContentType, "application/json");
request.AddParameter("grant_type", "client_credentials");
request.AddParameter("scope", "somescope");
```

produces the following request:
![image](https://user-images.githubusercontent.com/2821205/152331988-b839421f-61b6-47af-94d8-1e02afe66ae3.png)

Also https://restsharp.dev/support/#content-type

**Comment by alexeyzimarev** [comment]
Btw you might want to look at this as you're trying to get the OAuth2 token https://restsharp.dev/usage.html#authenticator
