### ISSUE TITLE
Postman Generated C# is not compatible with latest RestSharp

### ISSUE THREAD

**Issue by GarryLowther** [restsharp/RestSharp#1734]
**Describe the bug**
Postman has a C# RestSharp generator for Web API calls, however it generates code which is incompatible with the latest RestSharp 107.2.1.0 and fails to compile.

**To Reproduce**
Open a Postman collection with an API function and generate the C# RestSharp code.

**Expected behaviour**
Generated code should compile and run.
Whilst your website https://restsharp.dev/v107/#restsharp-v107 does have information about porting older RestSharp code to the latest version, it does not have any specific code to use instead of the C# code produced by Postman.
I imagine developers would appreciate being able to copy and paste working code from Postman into Visual Studio, then re-create the Postman functions in their own .NET applications.

I have written to Postman to ask that this be rectified, so perhaps you could liaise with them to make sure that they are able to generate the correct code for their customers?

**Comment by alexeyzimarev** [comment]
I think it's better to open an issue with Postman. They generate quite bad code for many years.

**Comment by alexeyzimarev** [comment]
I just remembered that the last time I looked at the Swagger code generator, it was in very bad shape. The main contributor left, and it was not being maintained properly. I am not sure about Postman though.

**Comment by GarryLowther** [comment]
Any news on this issue?
There are dozens of "restsharp" libraries on NuGet. Which ones are compatible with Postman generated code?

**Comment by alexeyzimarev** [comment]
There's a PR in Postman's codegen repo that needs to be merged. It makes little sense to ask here, as we don't maintain Postman codegen.

Also, there's only one RestSharp library on Nuget https://www.nuget.org/packages?q=restsharp
