### ISSUE TITLE
Support nested multipart content

### ISSUE THREAD

**Issue by TimSirmovics** [restsharp/RestSharp#1735]
Here is an example API which requires a nested multipart form: https://developer.channeladvisor.com/batch-requests/combine-two-quantity-updates-with-a-get-to-retrieve-product-data

Requirements, assuming that the outer boundary is "batch" and the inner boundary is "changeset":

**Header**

`Content-Type` header of `multipart/mixed; boundary=changeset`

**Body**
1. Opening outer boundary `--batch`, followed by the same Content-Type as the header.
```http
--batch
Content-Type: multipart/mixed; boundary=changeset
```
2. One or more inner content pieces, each starting with `--changeset`, and a closing `--changeset--` after the final one.
```http
--changeset
// Some content 1
--changeset
// Some content 2
--changeset
// Some content 2
--changeset--
```
3. Closing outer boundary `--batch--`

For this API, an example piece of content looks like this:
```http
Content-Type: application/http 
Content-Transfer-Encoding: binary 
Content-ID: 1

POST https://api.channeladvisor.com/V1/Products(25129205)/UpdateQuantity HTTP/1.1
Content-Type: application/json

{
  "Value":{
    "UpdateType": "UnShipped",
    "Updates": [{
        "DistributionCenterID": 1,
        "Quantity": 71
    }]
    }
}
```

**Comment by alexeyzimarev** [comment]
I think it should be possible by getting away from the "only a single body" limitation, which is artificial now. Plus, atm RestSharp has a way to override the form boundary, but not the form part boundary.
