### ISSUE TITLE
Unable to get the Headers, content, ContentHeaders and Cookies from the Response Base function

### ISSUE THREAD

**Issue by vigneshbabuv** [restsharp/RestSharp#1736]
While running the code in Pipeline.  Below methods are throwing error from response base class

public string? get_Content();
        [CompilerGenerated]
        [NullableContextAttribute(1)]
        public ICollection<string> get_ContentEncoding();
        [CompilerGenerated]
        [return: NullableAttribute(new[] { 2, 1 })]
        public IReadOnlyCollection<HeaderParameter>? get_ContentHeaders();
        [CompilerGenerated]
        public long? get_ContentLength();
        [CompilerGenerated]
        public string? get_ContentType();
        [CompilerGenerated]
        public CookieCollection? get_Cookies();
        [CompilerGenerated]
        [return: NullableAttribute(new[] { 2, 1 })]
        public IReadOnlyCollection<HeaderParameter>? get_Headers();
        [CompilerGenerated]
        public bool get_IsSuccessful();
        [CompilerGenerated]
        public byte[]? get_RawBytes();
        [CompilerGenerated]
        public Uri? get_ResponseUri();
        [CompilerGenerated]
        public string? get_Server();
        [CompilerGenerated]
        public HttpStatusCode get_StatusCode();
        [CompilerGenerated]
        public string? get_StatusDescription();
        //
        // Summary:
        //     Assists with debugging responses by displaying in the debugger output
        [NullableContextAttribute(1)]
        protected string DebuggerDisplay()

Error Message :
##[error]/RestSharpHelper.cs(87,75): Error CS0571: 'RestResponseBase.Headers.get': cannot explicitly call operator or accessor

**Comment by vigneshbabuv** [comment]
Code used : 
ApiResponse.Instance.Clear();
                ApiResponse apiResponse = ApiResponse.Instance;
                apiResponse.apiRequest = apiRequest;
                apiResponse.Headers = restResponse.get_Headers()

**Comment by alexeyzimarev** [comment]
Yeah, but the properties are there, so you need to look at your `RestSharpHelper`.

**Comment by vigneshbabuv** [comment]
RestResponseBase.Headers are not exposed. 

It give option get_headers, get_contentheaders, get_cookies

**Comment by alexeyzimarev** [comment]
I have no idea where this comes from. I am looking at the code, and those properties are all public:

https://github.com/restsharp/RestSharp/blob/f03c297c07d03765d27fb9631ed6496b2a013035/src/RestSharp/Response/RestResponseBase.cs#L93-L101

**Comment by vigneshbabuv** [comment]
i dont know tooo why it is not exposed ..

Need to look on it whether it is issue with restsharp . In Autosuggest, it is not listed .. 
Can you check the both images .. pls help on this 


<img width="484" alt="image" src="https://user-images.githubusercontent.com/99170923/152790770-7f3402ef-b673-487e-a1df-fb0527c8de2f.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/99170923/152790927-2423d47e-49dd-4b4e-a4a1-a1b60b091ca3.png">

**Comment by vigneshbabuv** [comment]
Any update … is it issue with restsharp ???

**Comment by alexeyzimarev** [comment]
No. You are looking at properties of `ApiResponse`, and you aren't using the `restResponse` parameter passed to the function. I am sorry but please ask a colleague to help. There's no such issue with RestSharp, it's in your code.

**Comment by vigneshbabuv** [comment]
Thanks for the prompt answer.  I hope one day Rest Sharp team will found the issue and fix it

Thanks.

**Comment by alexeyzimarev** [comment]
There's no issue with RestSharp, it is in your code.

**Comment by vigneshbabuv** [comment]
As per your comment, it is exposed in public right . 

So can you provide the screenshot with the Headers as variables from ResponseBase in autosuggest.. Like i provide above right

**Comment by alexeyzimarev** [comment]
I am sorry I can't help you.
![image](https://user-images.githubusercontent.com/2821205/152980616-c980b555-7d62-4099-84ce-5b0c88552035.png)

**Comment by vigneshbabuv** [comment]
sorry to disturb again .. this is in .net core and restsharp version 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/99170923/152986793-bab438d7-84cf-4225-ba55-8944d3a5b222.png">

**Comment by vigneshbabuv** [comment]
i got some idea .... i will just transfer the response to json and then i will convert the json into my own class.. then i will get the required things ...

Make it life easier. thanks for your awesome help.. @alexeyzimarev [alexeyzimarev](https://github.com/alexeyzimarev)

**Comment by cloudhunter89** [comment]
The error showing at the bottom of the screenshot (property indexer or
event is not supported by the language...) indicates there is an issue
outside of the source code.  Some causes I have found are referencing a dll
built by a different compiler, such as VB, setting "embed interop types"
for the assembly reference to true, and a corrupted .NET installation.

How did you get your reference?  Have you recently upgraded your IDE or the
dotnet installation?

**Comment by vigneshbabuv** [comment]
Not upgraded anything .. only upgrading the rest sharp changes and adopting the recent change in my framework

**Comment by vigneshbabuv** [comment]
The problem I found is public properties are unable to access.. so what I did for a temporary fix (up to fix from Restsharp)

converted the response to JSON string and get the particular property from the JSON string. That Jsonutil.ModelToJson converts any model into JSON .. and gets the property using the GetJsonPropertyValue method. Now it is working fine... 

But in my view, it needed to be fixed by the Restsharp team. 
.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/99170923/153023624-ad3a3f40-de60-4cd2-a353-e31752a991fd.png">

**Comment by vigneshbabuv** [comment]
@cloudhunter89  any update on the bug

**Comment by alexeyzimarev** [comment]
@vigneshbabuv please stop. There's no such bug in RestSharp.

**Comment by ThatOneBeagle** [comment]
I've also experienced this issue, and found it to be a problem with my environment that was resolved by:
* Removing older, unsupported versions of the .NET Core SDK / Runtime
* Updating my Visual Studio installation

Unclear of the precise mechanism which caused the issue, but hope that by commenting I can help provide a solution to others experiencing similar.

**Comment by vigneshbabuv** [comment]
sure i will try to remove the older version and reinstall the latest version

**Comment by alexeyzimarev** [comment]
I know what it is. It's an issue with older .NET versions that cannot use properties with `init`. https://stackoverflow.com/questions/66054634/cs1545-when-moving-from-visual-studio-2019-back-to-2017

**Comment by vigneshbabuv** [comment]
working as expected
