### ISSUE TITLE
URLs using ipv6 requests not working under macOS

### ISSUE THREAD

**Issue by shirleyyhchang** [restsharp/RestSharp#1743]
Hi

I have a code that runs on .net  on windows perfectly. 
URL using both ipv4 and ipv6 are correct under windows.

The same code  when I copy it to MAC used to work; 
The response is correct when I use the ipv4 url.
But when i use ipv6 url it responds statuscode 0. 

My code could not be simpler:

```
var baseUrl = new Uri("https://[fe80::290:e8ff:fe8b:2537%en10]:8443"); 
var client = new RestClient(baseUrl);
var request = new RestRequest(/api/v1/auth, Method.POST);                
request.RequestFormat = DataFormat.Json;
request.Timeout = 3000;
request.AddHeader("Content-Type", "application/json");
request.AddHeader("Authorization", "Bearer");
request.AddParameter("application/json", payload, ParameterType.RequestBody);
var response = await client.ExecuteAsync(request);
```
The output under MAC OS is:
content received =
status code: 0

By the way,I have tried the method using HttpClient and both ipv4 and ipv6 urls respond correctly. 

Any ideas?

Regards
Shirley

**Comment by alexeyzimarev** [comment]
Please provide the issue details as requested in the issue template.
