### ISSUE TITLE
Error being thrown on 403

### ISSUE THREAD

**Issue by dontbesorry80** [restsharp/RestSharp#1751]
According to the documentation only 404s should throw an error with the default settings.
However, the service I am consuming returns a 403 error for something that isn't an authorization failure and it has a response body. However RestSharp throws an error and the RestResponse is null. 

This seems like a bug, I couldn't find a configuration setting to ensure an exception was NOT thrown for 403 errors.

**Comment by alexeyzimarev** [comment]
Maybe you don't mind **not** ignoring the issue template and post the required information for your issue to be considered.

**Comment by dontbesorry80** [comment]
> Maybe you don't mind **not** ignoring the issue template and post the required information for your issue to be considered.

Sorry, where is the template? I didn't see it.. I'm not a frequent Github user..

**Comment by alexeyzimarev** [comment]
When you created an issue, you got a template.

**Comment by dontbesorry80** [comment]
@alexeyzimarev I will close this one and created a new one here:
https://github.com/restsharp/RestSharp/issues/1754
Hopefully it should have all the info, my apologies for missing that.
