### ISSUE TITLE
Issue adding Parameters to Post type methods

### ISSUE THREAD

**Issue by latharian1983** [restsharp/RestSharp#1753]
I have been working on making some Post calls to my API, but when trying to assign my route parameters to the URL they become lost. I tracked the issue to this bit of code in the ParametersCollection.cs file. Line 54 thru 61. This does work with a GET call.

I am a mid level developer and this is using some concepts I haven't learned about yet. So I don't fully understand what the code is doing to be able to fix it myself.

This is my code trying to create the call, but in the end the url that is called is simply   https://mywebsite.com/index.php    when it should be https://mywebsite.com/index.php?route=rest/category_admin/category

`var request = new RestRequest("index.php");`
`request.AddParameter("route", "rest/category_admin/category");`
`request.AddJsonBody(category);`
`request.Method= Method.Post;`
`var response = await _client.PostAsync<ReturnModelSingle<IDReturnModel>>(request);`

**Comment by alexeyzimarev** [comment]
I think this will work

```csharp
request.AddParameter("route", "rest/category_admin/category", true);
```

**Comment by latharian1983** [comment]
Thank you, I missed that and appreciate your answer!
