### ISSUE TITLE
403 Responses are throwing an Exception

### ISSUE THREAD

**Issue by dontbesorry80** [restsharp/RestSharp#1754]
**Describe the bug**
According to the documentation only 404s should throw an error with the default settings. It says:
"If there is a network transport error (network is down, failed DNS lookup, etc), or any kind of server error (except 404), RestResponse.ResponseStatus will be set to ResponseStatus.Error, otherwise it will be ResponseStatus.Completed"

However, the service I am consuming returns a 403 error for something that isn't an authorization failure and it has a response body. 
However RestSharp throws an error and the RestResponse is null.

**To Reproduce**
I have build a working request bin
https://eozvn4dwnmjsib7.m.pipedream.net which gives a 403 error with a JSON Reponse

Here is my code to reproduce the behavior:

```
TestingResultsViewModel viewModel = new TestingResultsViewModel();
try
{
	var client = new RestClient("https://eozvn4dwnmjsib7.m.pipedream.net");
	var request = new RestRequest("/", Method.Get);
	RestResponse response = await client.GetAsync(request);
	viewModel.RestSharpResult = response.Content;

}catch(Exception ex)
{
	viewModel.RestSharpResult = "Error Message: " + ex.Message;
}

return View(viewModel);
```
**Expected behavior**
If you go direactly to the URL https://eozvn4dwnmjsib7.m.pipedream.net/ 
You should get the following result:
`{"message":"This is the body of the fail"}`

**Stack trace**
```
   at RestSharp.RestClient.ThrowIfError(RestResponse response)
   at RestSharp.RestClientExtensions.<GetAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MainApplication.Controllers.TestingController.<Index>d__4.MoveNext() in TestingController.cs:line 51
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - .NET Core 3.1
 - Version 107.3.0

**Comment by alexeyzimarev** [comment]
Thank you, now I understand what the issue is. It's by design. Please check this page https://restsharp.dev/error-handling.html

You need to use `ExecuteGetAsync`, it won't throw.

**Comment by dontbesorry80** [comment]
@alexeyzimarev 
Thank you for this quick response. That sorted it.
