### ISSUE TITLE
Breaking change in 107.3.0 - No exception if HTTP status code is 404

### ISSUE THREAD

**Issue by danm-de** [restsharp/RestSharp#1755]
**Problem**
After upgrading from 107.2.1 to 107.3.0  `RestClient` does not longer throw a `HttpRequestException` if the endpoint returns a 404.

**Reproduce**

Configure the client as follows:

```csharp
var opts = new RestClientOptions();
opts.ThrowOnAnyError = true;
``` 

Call the static extension method:

```csharp
RestClientExtensions.GetAsync<T>(RestClient, RestRequest, CancellationToken)
``` 
**Expected behavior**
A `HttpRequestException` is thrown (having `RestResponse.ErrorException` as inner exception).

Since this is a feature release (107.**3**.0) breaking changes are not expected.

**Workaround**
I had to fix it using a workaround - which works in **my** environment 😄.

```csharp
private async Task<T?> GetAsync<T>(RestRequest request, CancellationToken cancellationToken = default) 
{
   var response = await _client.ExecuteGetAsync<T>(request, cancellationToken).ConfigureAwait(false);
   var exception = response.ErrorException;
   if (response.ResponseStatus != ResponseStatus.Completed || exception is not null)
   {
        var message = exception is null
           ? $"Request {response.ResponseStatus}"
           : exception.Message;
        throw new HttpRequestException(message, exception, response.StatusCode);
    }
    return response.Data;
}
```

**Comment by alexeyzimarev** [comment]
It's not a bug, it's by design, as described in the docs https://restsharp.dev/error-handling.html

**Comment by alexeyzimarev** [comment]
Basically, it's v106 that has a bug that it throws on 404.
