### ISSUE TITLE
Migration from 106.15.0 to 107.3.0 shows exception that baseurl not found

### ISSUE THREAD

**Issue by Su-s** [restsharp/RestSharp#1759]
Hi, 

**Describe the bug**
I just updated the restsharp today after building the project. The build was not successful and it showed 3 errors. Fixed the first two using the best available option from the package

"**'RestClient' does not contain a definition for 'BaseUrl'**"

![image](https://user-images.githubusercontent.com/37269911/154213520-5681fcde-30fd-4b09-b26c-63d1832ec266.png)

![image](https://user-images.githubusercontent.com/37269911/154213758-a3f8418a-67d3-4a59-8e01-07f71c1d0ab4.png)

**To Reproduce**
 Either install the latest version of restsharp or update the existsing restsharp version in project

**Expected behavior**
The baseurl property should be available and should get a success build

**Stack trace**
![image](https://user-images.githubusercontent.com/37269911/154214240-215ca3a8-a22f-4479-b054-f22f582f04fe.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - .NET version: .NET 6.0
 - Version: 107.3.0

**Comment by alexeyzimarev** [comment]
Please read the docs, the migration guide in particular.
