### ISSUE TITLE
Raw bytes as RequestBody not working anymore in v107

### ISSUE THREAD

**Issue by inimirpaz** [restsharp/RestSharp#1761]
Hi everyone,

   I used to send a POST API request with raw binary data as follows:

`byte[] binaryStream`
```
RestRequest request = new("api/apicall", Method.POST);
request.AddParameter("file", binaryStream, ParameterType.RequestBody);
IRestResponse response = await client.ExecuteAsync(request);
```

Since I updated and migrated to v107 (107.3.0) this stopped to work. The server receives the ".ToString()" of the bytes array: 

> --467e3b83-a3ad-4571-8af1-e505c56e0037
> Content-Type: text/plain; charset=utf-8
> Content-Disposition: form-data; name=file
> 
> System.Byte[]
> --467e3b83-a3ad-4571-8af1-e505c56e0037--

**Comment by alexeyzimarev** [comment]
Please read the docs and use `AddFile`.

**Comment by inimirpaz** [comment]
Sorry to bother but using `AddFile` does not solve the issue for me. On the server side the POST API is processed and the file is extracted from a `HttpListenerRequest.InputStream`. With RestSharp < v107 the `request.AddParameter("file", binaryStream, ParameterType.RequestBody);` worked as expected from the server side which received the raw binary data **only**.

Using `AddFile` in v107 adds to the raw binary data also the HTTP "boundary" preamble and footer:

`--5e04074f-915d-40ab-af14-019fd6116499 Content-Type: audio/wave Content-Disposition: form-data; name="name"; filename="filename"`
[RAW BINARY DATA] <--- The server is supposed to receive only this (at least, this is how it worked with < v107)
`--5e04074f-915d-40ab-af14-019fd6116499--`

**Comment by alexeyzimarev** [comment]
Ok, then you can use `AddBody` with the byte array. It won't work with a stream though.

**Comment by inimirpaz** [comment]
> Ok, then you can use `AddBody` with the byte array. It won't work with a stream though.

Hi, thanks for your promptly reply!
I just tried with `request.AddBody(byteArray);` (byteArray is obviously a byte[]) but on the receiving end all I get is a 13 byte text file with the `.ToString()` of such array:

```System.Byte[]```

**Comment by alexeyzimarev** [comment]
I need to check, it should use the bytes array.

**Comment by alexeyzimarev** [comment]
Ok, I will fix the issue later, but the following code should work:

```csharp
request.AddParameter(new BodyParameter("", byteArray, contentType, DataFormat.Binary));
```

**Comment by inimirpaz** [comment]
> Ok, I will fix the issue later, but the following code should work:
> 
> ```cs
> request.AddParameter(new BodyParameter("", byteArray, contentType, DataFormat.Binary));
> ```

Thanks! It did the job.
