### ISSUE TITLE
ParseJsonDate missing in latest version of RestSharp

### ISSUE THREAD

**Issue by vRITHNER** [restsharp/RestSharp#1762]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
Since installation of latest version of Rest#, the StringExtension `ParseJsonDate `is missing and my code can't compile anymore

**To Reproduce**
Upgrade to latest version

**Expected behavior**
Compile as usual

**Stack trace**
Copy the full stack trace here if you get an exception.

**Desktop (please complete the following information):**
 - Windows 11 pro
 - .NET version : netcore 
 - Version 6.0.200

Thanks
-Vince

**Comment by alexeyzimarev** [comment]
This particular extension was used by the legacy deserialization as was removed due to the deprecation of SimpleJson and all the supporting code. You can copy the function from v106 and make it your own.

**Comment by vRITHNER** [comment]
Cool. Txs for quick response :-)
