### ISSUE TITLE
client.DeleteAsync in v107

### ISSUE THREAD

**Issue by hamidish** [restsharp/RestSharp#1764]
var client = new RestClient("http://rubicode1.ir/api/");
                var request = new RestRequest("UserFavourites/" + id);
                var responset = await client.DeleteAsync<UserFavourite>(request,CancellationToken.None);
i use this ut got error: 
System.Text.Json.JsonException
  Message='<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
  Source=mscorlib
  StackTrace:
  at RestSharp.RestClient.ThrowIfError (RestSharp.RestResponse response) [0x0000a] in <4853702ec6dc400bbce6833a41cf78f5>:0

**Comment by alexeyzimarev** [comment]
Your server returns an error as HTML. Use `ExecuteAsync` with a request where the method is set to `Method.Delete`, so you can inspect the response.
