### ISSUE TITLE
AddFile() parameters ignore order

### ISSUE THREAD

**Issue by gfu-tt** [restsharp/RestSharp#1773]
**Describe the bug**
When sending form data as POST the file parameter is sent first.

**To Reproduce**
var client = new RestClient(endpoint);
var request = new RestRequest("", Method.Post);
request.AddHeader("Content-Type", "multipart/form-data");
request.AddParameter("data", "[{\"some\":\"data\"}]");
request.AddFile("file", filePath);
var response = client.ExecuteAsync(request);

**Expected behavior**
The API expects the "data" parameter before "file".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET 4.8
 - Version 107.3.0

**Comment by alexeyzimarev** [comment]
The parameters order should not matter. If you can point out the HTTP protocol spec that says that parameters order matters, I'd consider looking at it.

**Comment by gfu-tt** [comment]
I reported the case to the developers of the API. They will look into it.

Until then I will use RestSharp 106.15.0.

Thank you.
