### ISSUE TITLE
Reintroduction of delegate FormatMultipartContentType

### ISSUE THREAD

**Issue by K-i-m-o** [restsharp/RestSharp#1774]
Hello,

I am uploading XML-Files to a website which doesn't offer any type of API. In order to achieve that I use RestSharp for
a) logging in to the website and b) sending the xml using the RestRequest extension-method AddFile.
The code itself is pretty simple as just a request with two parameters and the file is created.
However, since upgrading from RestSharp 105.0.1 to the latest version (107.3.0) i ran into a problem as the webserver responds to my upload attempt with an error message ("Request contains no data").

After analyzing my requests and reading through the issues here i found a solution as described in #1713: The problem can be solved by using RestSharp version 107.1.2 alpha 09 and assigning a delegate to `FormatMultipartContentType ` (https://github.com/restsharp/RestSharp/issues/1713#issuecomment-1020041899).
It changes the request from 
`
...
Content-Type: multipart/form-data; boundary="f252e8c1-9a7c-4b43-ac3a-f0b9d1ee0e0a"
...`
to 
`
...
Content-Type: multipart/form-data; boundary=f252e8c1-9a7c-4b43-ac3a-f0b9d1ee0e0a
...`

Any version after 107.1.2 alpha 09 had the delegate removed as it was concluded
> that both the filename and the name parameters in Content-Disposition need to be in quotes...

Unfortunately, the server can't handle the request with quotes in the boundary-definition (I have also tried enabling `MultipartFormQuoteParameters`).
Since i found that the only way for the server to accept my request is by using `FormatMultipartContentType`I kindly suggest you reintroduce the delegate again.

Best regards,
Moritz

This is the working request created with RestSharp 105.0.1:
```
POST ... HTTP/1.1
Host: ...
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/105.0.1.0
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Cookie: PD-S-SESSION-ID=...
Content-Type: multipart/form-data; boundary=-----------------------------28947758029299
Content-Length: 9391

-------------------------------28947758029299
Content-Disposition: form-data; name="name1"; filename="myfile.xml"
Content-Type: application/octet-stream

<?xml version="1.0" encoding="iso-8859-1"?>
 ...
```

This is the one created with 107.3.0 (not working):
```
POST ... HTTP/1.1
Host: ...
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: RestSharp/107.3.0.0
Accept-Encoding: gzip, deflate, br
Cookie: PD-S-SESSION-ID=...
Content-Type: multipart/form-data; boundary="f252e8c1-9a7c-4b43-ac3a-f0b9d1ee0e0a"
Content-Length: 9441

--f252e8c1-9a7c-4b43-ac3a-f0b9d1ee0e0a
Content-Type: application/octet-stream
Content-Disposition: form-data; name="name1"; filename="myfile.xml"

<?xml version="1.0" encoding="iso-8859-1"?>
 ...
```

And this is the working one with `FormatMultipartContentType` assigned from version 107.1.2:
```
POST ... HTTP/1.1
Host: ...
Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
User-Agent: RestSharp/107.1.2.0
Accept-Encoding: gzip, deflate, br
Cookie: PD-S-SESSION-ID=...
Content-Type: multipart/form-data; boundary=99e7c7b8-17f2-4abf-b4b8-15d85ef80666
Content-Length: 9436

--99e7c7b8-17f2-4abf-b4b8-15d85ef80666
Content-Type: application/octet-stream
Content-Disposition: form-data; name=name1; filename=myfile.xml

<?xml version="1.0" encoding="iso-8859-1"?>
...
```

**Comment by alexeyzimarev** [comment]
The reason for me to remove that function is that it was a massive hack. It's not RestSharp adding quotes around the boundary, it's how the `System.Net.Http.MultipartContent` works, here is their code:

```csharp
            MediaTypeHeaderValue contentType = new MediaTypeHeaderValue("multipart/" + subtype);
            contentType.Parameters.Add(new NameValueHeaderValue(nameof(boundary), quotedBoundary));
            Headers.ContentType = contentType;
```

**Comment by K-i-m-o** [comment]
Thank you for your time and response.

I digged a little bit into the RestSharp source code and unfortunately I currently don't see any way to modify the MultipartFormDataContent in order for it to fit my requirement.
Do you have any idea, if there is another approach i could try?
Unfortunately i don't have any influence on how the server acts since it is a government run server.

Best regards,
Moritz

**Comment by CorzzaH** [comment]
Found a workaround for this in the latest RestSharp version after dealing with the same issue and needing to remove them for the request to work correctly and thought it would be worth posting here in case anyone else runs into the same issue.

You can remove the quotes around the boundary in content type using the following code before executing the request:

```
request.OnBeforeRequest = (http) =>
{
    var boundary = http.Content.Headers.ContentType.Parameters.First(o => o.Name == "boundary");
    boundary.Value = boundary.Value.Replace("\"", String.Empty);
    return default;
};
```

**Comment by alexeyzimarev** [comment]
I think we can still get the function back, it's just that I hardly can find time to do it.
