### ISSUE TITLE
Restsharp: Returns 0 content with error "unable to read data from the transport connection"

### ISSUE THREAD

**Issue by russr999** [restsharp/RestSharp#1777]
At first I thought I was going mad as all was working okay on windows but when I run my console app on Debian (v9), it will constantly fail with the error: unable to read data from the transport connection. I've narrowed it down to restsharp and not a api/server issue.

When I run a debugger in parallel (HTTP Debugger) I can see the request go out from my console app on Debian and I can also see the endpoint return a result with content! This content does not come into restsharp and so restsharp gives me a content-length of 0 and an error message of:
>unable to read data from the transport connection: An existing connection was forcibly closed by the remote host

**Desktop (please complete the following information):**
Background: Console app built in .Net 4.6.2
Dll: Restsharp 106.15.0.0
Mono: Mono JIT compiler version 6.12.0.122
API Endpoint: http server (not https)

**Additional context: code calling restsharp (vb.net)**
```
Dim myUri As New Uri(url)
Dim client = New RestSharp.RestClient(myUri)
Dim request = New RestRequest With {.Method = Method.GET}
request.AddHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9")
request.AddHeader("Connection", "keep-alive")
Dim response As RestResponse = client.Execute(request)
Dim strResponse as String = response.Content)
```

(I've also tried without sending the headers - makes no difference, same error message)

**Comment by alexeyzimarev** [comment]
Sorry but RestSharp 106 won't be updated, and it's most probably the issue with Mono.
