### ISSUE TITLE
RestRequest ResponseWriter and AdvancedResponseWriter are init only properties

### ISSUE THREAD

**Issue by kendallb** [restsharp/RestSharp#1787]
These are written to C# 9.0 spec, which means they are init only setter properties. This means any code attempting to consume RestSharp and use these features needs to update their toolchain to support C# 9.0 or the code will not compile. We still have a lot of developers using Visual Studio 2019, which does not support C# 9.0. While we are migrating to VS2022, it's a process to get everyone moved over.

Please change these back to regular setters so they can be used with earlier versions of Visual Studio.

**Comment by kendallb** [comment]
Here is a PR

https://github.com/restsharp/RestSharp/pull/1788

**Comment by kevinpohlmeier** [comment]
For people coming here that got a build error from this even in VS2022, be sure to add the LangVersion to your csproj. You can use either of the following:
```
<LangVersion>9.0</LangVersion>
<LangVersion>latest</LangVersion>
```

**Comment by alexeyzimarev** [comment]
The language version is already specified in the `Directory.build.props` file.
