### ISSUE TITLE
Could not load type 'RestSharp.IRestResponse' from assembly 'RestSharp, Version=107.3.0.0

### ISSUE THREAD

**Issue by cristianormoraes** [restsharp/RestSharp#1789]
System.TypeLoadException: 'Could not load type 'RestSharp.IRestResponse' from assembly 'RestSharp, Version=107.3.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'.'

**Comment by alexeyzimarev** [comment]
Because there's no such interface in v107 
https://restsharp.dev/v107/#deprecated-interfaces
