### ISSUE TITLE
Default behavior for serializer does not support snake_case?

### ISSUE THREAD

**Issue by kendallb** [restsharp/RestSharp#1790]
**Describe the bug**
In versions of RestSharp prior to v107, the default serializer (SimpleJson) supported snake_case payloads out of the box and would happily convert them into C# POCO values

**To Reproduce**
Given the sample JSON below:
```
{
  "retail_rate": "8.70",
  "retail_currency": "USD",
}
```
it will not convert into the C# object:
```C#
public class MyPOCO 
{
    public string RetailRate { get; set; }
    public string RetailCurrency{ get; set; }
}
```

**Expected behavior**
I would expect the default serializer to somehow support this out of the box? This is probably supported out of the box if we change the JSON.NET for the seralizer as I think it supports that out of the box, but perhaps there is a way to get snake_case working out of the box with the System.Text.Json serializer?

**Comment by kendallb** [comment]
Reading up on System.Text.Json, I am not sure it's possible to use a different serializer just for deserializing, so if you change to snake_case, it will change both serialization and deserailization by default to that, which is not what we would want from the library.

I guess I can adjust my code to support this, but it would be nice if there was a way for the default serializer to convert snake_case by default to C# objects like the old library did.

**Comment by alexeyzimarev** [comment]
Right now, this can be worked around by using Newtonsoft.Json as you said, or by marking properties with the `JsonProperty` attribute. I agree, it's tedious. The question is if we should do anything at all considering this https://github.com/dotnet/runtime/issues/782

**Comment by kendallb** [comment]
Yeah I ended up just migrating to JSON.NET for this project and adding a dependency on that. Quite a lot of changes to get it successfully working on v107, but it's done now (all tests pass):

https://github.com/kendallb/easypost-async-csharp/commit/80dbaafd74b6b5fbf7d8ca8feb3f3f2f36a1f683

I did actually try setting up my own snake_case naming policy for System.Text.Json, but it always failed for me giving errors about not being able to convert a valid value in the JSON (something not mapped to a POCO field and just ignored). Oddly it had no issues when using the default camelCase support, but would always fail in snake_case mode. I eventually gave up and just flipped to JSON.net, and it all worked.

**Comment by Terebi42** [comment]
I actually have JsonProperty attributes on my entities and its not working in 1.7

      [JsonProperty("character_galactic_power")]
        public long CharacterGalacticPower { get; set; }

json : 
character_galactic_power: 3323513

deserialized: 0

**Comment by alexeyzimarev** [comment]
@Terebi42 it seems you are using the `JsonProperty` attribute from Newtonsoft.Json. System.Text.Json's own attribute is `JsonPropertyName`. If you have issues with the default serializer, I suggest first reading the docs of the serializer. RestSharp does nothing when it comes to serialization and deserialization of JSON except calling the serializer.
