### ISSUE TITLE
How to get response content without storing it in MemoryStream

### ISSUE THREAD

**Issue by Racer396** [restsharp/RestSharp#1794]
Hello!
Before v107 i use DownloadData with AdvancedResponseWriter, and as i remember, it doesn't store ResponseContent in memory and allow to write something like this:

```
               var request = new RestRequest(downloadUri, Method.GET);
                request.AdvancedResponseWriter = (stream, response) =>
                {
                    using var fStream = File.OpenWrite(filePath);
                    var buffer = new byte[1024*64];
                    long totalCount = 0;
                    while (totalCount != response.ContentLength)
                    {
                        var count = stream.Read(buffer, 0, buffer.Length);
                        totalCount += count;
                        fStream.Write(buffer, 0, count);
                    }
                };
                _client.DownloadData(request);
```

Now in v107.3, when i use DownloadDataAsync or just ExecuteAsync, it store all data in memory and only after that return me the MemoryStream.
How can i avoid storing ResponseContent in memory and write it in the file as is?
Because in my case, i need to downloading big files, which size can be a few gigabytes, and storing it in memory, on clients desktop PC - looks like a bad idea.

https://github.com/restsharp/RestSharp/blob/17a3532479809eb0439249c7a942ae4f6b41f3d2/src/RestSharp/Response/ResponseHandling.cs#L38

**Comment by alexeyzimarev** [comment]
Use `DownloadStreamAsync` https://restsharp.dev/usage.html#downloading-binary-data

**Comment by Racer396** [comment]
But the question was about DownloadStreamAsync .
Because when i use it, it store all data in memory, in MemoryStream, and only after that, it returns stream.
In first message, i ref a method from ResponseHandling, and if this method is used for DownloadAsyncStream, i dont now how it may work async as i want, without storing all in memory, because of - https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent.readasstreamasync?view=net-6.0

> The returned [Task<TResult>](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1?view=net-6.0) object will complete after all of the stream that represents content has been read.

It's returns stream only after all content was read.
Therefore, this means we have memory stream, that read all response in it, and only after that return to me this memory stream from DownloadStreamAsync method.

May be i do something wrong, and i would appreciate it if you could give an example of the correct usage.

**Comment by Racer396** [comment]
And intresting discussion about that in dotnet repo: https://github.com/dotnet/runtime/issues/31316

**Comment by alexeyzimarev** [comment]
What the referenced issue states is not exactly right. If you look at `StreamJsonAsync`, it uses `DownloadDataAsync` and continuously reads the stream. The stream content is available as soon as it gets something from the server. 

https://github.com/restsharp/RestSharp/blob/cd4c434927fac44ffe18f01642a618f06b07418e/src/RestSharp/RestClientExtensions.cs#L325-L350

The key here is this line:
https://github.com/restsharp/RestSharp/blob/cd4c434927fac44ffe18f01642a618f06b07418e/src/RestSharp/RestClientExtensions.cs#L330

**Comment by Racer396** [comment]
`CompletionOption = HttpCompletionOption.ResponseHeadersRead `
Yes, that what i need. Thank you so much! :)

**Comment by kendallb** [comment]
I just ran into this also. Wouldn't it make more sense to always set that completion option for DownloadStreamAsync? Otherwise DownloadStreamAsync really is not much point, because it defeats the purpose of actually downloading into a stream?

**Comment by kendallb** [comment]
Also that would make DownloadDataAsync be more efficient, as currently it will end up downloading the data first into a memory stream, which is then streamed into a byte[] array to return the caller. If it was actually streaming the response content, then the byte[] array is built more efficiently (internally it's streamed into a memory stream 16K at a time which is then turned into the byte array). So if we are downloading say a 2MB file, there will be a 2MB memory stream created by the DownloadStreamAsync() function, then another 2MB memory stream that the data gets copied into, which then gets turned into the final byte array.
