### ISSUE TITLE
Have you considered using JsonContent

### ISSUE THREAD

**Issue by sgalcheung** [restsharp/RestSharp#1796]
Recently I found [JsonContent](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.jsoncontent?view=net-6.0), he can directly handle any of my types and help me serialize, and there is a blog with some introduction [Sending and Receiving JSON using HttpClient with System.Net.Http.Json - Steve Gordon - Code with Steve (stevejgordon.co.uk)](https://www.stevejgordon.co.uk/sending-and-receiving-json-using-httpclient-with-system-net-http-json)

**Comment by alexeyzimarev** [comment]
Using `JsonContent` would mean losing the ability to use any other serializer, which is not desirable. It's just a wrapper around System.Text.Json serialiser, which is used by RestSharp anyway.

**Comment by sgalcheung** [comment]
Not exactly, I see that [**JsonContent**](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs) has a JsonSerializerOptions parameter which allows you to inject he specified serializer

**Comment by alexeyzimarev** [comment]
`JsonSerialzierOptions` is the options class for System.Text.Json serializer.

**Comment by sgalcheung** [comment]
I'm sure, I read it wrong, he just made a property setting of how System.Text.Json serializes, not a serializer that can be injected, maybe I should put these suggestions to the dotnet community, thank you 's answer.

**Comment by alexeyzimarev** [comment]
The `System.Net.Http.Json` is coupled to `System.Text.Json`. I don't think they will change it.

Do you have any particular reason for RestSharp to use `JsonContent`? Is there any missing feature now?

**Comment by sgalcheung** [comment]
No, RestSharp can meet my usage scenario, I'm just curious, there are many specific Content types, but it seems that StringContent is used by default

**Comment by sgalcheung** [comment]
Yes, I have browsed the source code, thank you for your answer, I will close this issue, my actual confusion is that System.Net.Http[.Json] contains many types of Content (such as FormUrlEncodedContent, StringContent, and JsonContent), why not Use a specific type to deal with the corresponding Content-Type, perhaps using StringContent is enough to meet the needs, but what is the point of these interfaces designed by the dotnet community, but this is beyond the scope of RestSharp

**Comment by alexeyzimarev** [comment]
RestSharp uses `FormUrlEncodedContent`, binary content, and different multi-part content types, not only `StringContent`. When dealing with serialized payloads, it's easier to just use `StringContent` to allow using different serializers.
