### ISSUE TITLE
[RFC] Bring back Method.GET, Method.PUT etc?

### ISSUE THREAD

**Issue by kendallb** [restsharp/RestSharp#1798]
It is not clear to me why these were changed, but it does mean another pain point for someone porting code from earlier versions of RestSharp to v107. May I suggest that we include both the C# style naming as well as the ALL CAPS style naming in the Enum? The CAPS versions could just be aliases to the other ones, so then both new code and old code will work?

**Comment by alexeyzimarev** [comment]
I am not sure if it's really a problem.

**Comment by kendallb** [comment]
It is when you have to modify a ton of code. Just another thing that makes it harder for someone to migrate.

**Comment by alexeyzimarev** [comment]
Fair enough
