### ISSUE TITLE
[RFC] Serializer should not be part of the client but part of the request?

### ISSUE THREAD

**Issue by kendallb** [restsharp/RestSharp#1810]
The way RestSharp was designed before, the serializer was a part of the client configuration as you set it on the client. This is still the same in RestSharp v107, and while I get that it kinda makes sense to attach it to the client as it's needed by both the request and the response, the problem is if we are expected to use singletons for the RestClient's in our code, the serializer now becomes a static part of that instance that you cannot change on a per request basis.

Why on each would you want to do that you ask? Well quite simply in our case we have code that needs to run in the context of *different timezones* depending on the user. So when we make those REST requests, we have a custom JSON serializer that handles timezone conversion for us as we have implemented what basically boilds down to a 'timezone per request' model in our application. It's pain because Windows has no concept of this, but we can do with wrappers around all the low level timezone stuff via DI, and it works great.

The problem is the serializer we use for JSON needs to have the correct timezone in it for the request that is being sent. So it will correctly convert whatever timestamps gets that are 'local' time (local to the user the request comes from that is not the system it runs on) and turns it into UTC on the wire. Then on the other end it converts to the local time of whatever is listening (we have distribution centers in multiple timezones), and converts it back again for the responses.

I have fixed it by making the timezone a part of the cache key for the request clients we get, so we will always have a single RestSharp client for each timezone offset we are using. Which works, but I almost missed that and it would have caused a lot of nasty timezone bugs.

So my question is, now that RestSharp is expecting folks to use singleton instances of RestClient per API endpoint, it seems that having the serializer be a part of the client setup is wrong? In fact the serializer code is a callback, so at runtime it creates a new serializer for every request so it's clearly very request centric.

**Comment by alexeyzimarev** [comment]
Hmm, a properly returned timestamp includes the timezone explicitly, so it always correctly deserializes to the right `DateTime` or `DateTimeOffset`, including the timezone. Do you have examples of APIs returning date-time without a timezone? It's a bad API design, I would say.

I would never give up on having the serializer configured on the client level. It covers A LOT of use cases. In fact, v104 and earlier (I believe) had serializer per request, and I got loads of complaints. When I added the possibility to configure the serializer on the client, they all disappeared. I hear about the timezone issue for the first time, to be honest.

Plus, embedded deserialization is completely optional, as you can use non-generic versions and deserialize yourself in a way you want.

I am not saying that it's not possible to do it per request, but I won't do it "on request level _instead of_ client level".

**Comment by kendallb** [comment]
It's not about the serialization over the wire. That is always either in the correct timezone, or in UTC (we send in UTC on the wire). Our scenario is probably unique in that we run application code that needs to run in different timezones to what the server itself is configured as. And the same application stack might be making REST requests from one bit of code running in say PST, to another bit of code that is actually running in EST. So we are hampered by the fact that Windows has no concept of timezone per request.

None of that is really relevant to RestSharp except that I need to configure a different serializer for each sending endpoint client, as it needs to know what timezone to expect the timestamps in and convert them to UTC. So I fixed it by making sure we cache the client and use the timezone of the sending client as a key and it works.

So I will close this out.

**Comment by alexeyzimarev** [comment]
> same application stack might be making REST requests from one bit of code running in say PST, to another bit of code that is actually running in EST

But you send it as `DateTime` or `DateTimeOffset` and it has the timezone?

**Comment by kendallb** [comment]
No, on the wire it's always UTC in ISO 8601 format. It's all about how it converts the input DateTime values in the C# POCO to the JSON that is what needs to be different.
