### ISSUE TITLE
HttpClient问题

### ISSUE THREAD

**Issue by daofeng-coder** [restsharp/RestSharp#1813]
在程序生命周期内，微软官方推荐HttpClient只存在一个实例对象，因为它的Dispose方法并不会真实释放全部资源。在程序内频繁实例化就会导致内存不断增加，直至溢出

[HttpClient](https://docs.microsoft.com/en-US/dotnet/api/system.net.http.httpclient?view=net-6.0) is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.

但是在实际应用中，不可能只实例化一个HttpClient，特别是需要处理Cookie的情况

**Comment by alexeyzimarev** [comment]
Please write in English
