### ISSUE TITLE
RestSharp - IRestClient Transfer-Encoding: chunked missing response body

### ISSUE THREAD

**Issue by mihaela-tudor** [restsharp/RestSharp#1818]
When making a get Request with Transfer-Encoding: chunked the body is missing but visible in postman or fiddler.

**Comment by nicusoreftene** [comment]
Annoying bug indeed, will probably consider switching to a classic HttpClient for out .net apps

**Comment by alexeyzimarev** [comment]
@nicusoreftene why wouldn't you consider fixing the issue instead?

**Comment by nicusoreftene** [comment]
> @nicusoreftene why wouldn't you consider fixing the issue instead?

Fair enough, will give it a try
