### ISSUE TITLE
Push model support for AddFile

### ISSUE THREAD

**Issue by tomaswindsor** [restsharp/RestSharp#1826]
**Is your feature request related to a problem? Please describe.**
Sometimes when you want to upload a file, you want to generate it on the fly, rather than read it from a stream. It even seems that such a support was planned, as the documentation of method FileParameter.Create clearly states:
    `/// <param name="getFile">Delegate that will be called with the request stream so you can write to it..</param>`
Which is exactly the behavior I would like (except for the name of parameter). But right now that delegate is only used to obtain the input stream. So the documentation is incorrect.

In the file RestSharp-dev\docs\v107\README.md is this:
| `AddFile(string name, Action<Stream> writer, string fileName, long contentLength, string contentType)` | Extension                        |
... which also suggests such intent, but such method doesn't exist.

**Describe the solution you'd like**
As I already mentioned above, I'd like to write to stream during the request, rather than provide input stream for the file.
System.Net.Http.PushStreamContent class could be used for that.

**Comment by alexeyzimarev** [comment]
Maybe it needs another parameter type, don't you think? The file parameter will always use the binary content.

About the docs, I'll have a look.

**Comment by tomaswindsor** [comment]
I actually realized it's not so simple to generate the file to be uploaded on the fly, as you need to specify content length prior to writing from that writer when uploading anyway.
