### ISSUE TITLE
Uploaded file has incorrectly encoded filename if this filename has non-ASCII characters

### ISSUE THREAD

**Issue by soft-cactus** [restsharp/RestSharp#1828]
**Describe the bug**
If you try to upload a file that has non-ASCII characters in its filename (eg. ÄÖäö.jpg), then Content-Disposition is encoded to smth like "=?utf-8?B?S29hbGHDhMOWw6TDti5qcGc=?="

**To Reproduce**
1. Set a breakpoint to https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/Request/RequestContent.cs#L65
2. Rename test file Koala.jpg to KoalaÄÖäö.jpg
3. Change test data (to filename = "KoalaÄÖäö.jpg") and run an upload test eg. Should_upload_from_file
4. Check fileContent.Headers.ContentDisposition value in RequestContent.AddFiles()

**Expected behavior**
fileContent.Headers.ContentDisposition - form-data; name="file"; filename="ÄÖäö.jpg"

**Actual behavior**
fileContent.Headers.ContentDisposition - form-data; name="file"; filename="=?utf-8?B?S29hbGHDhMOWw6TDti5qcGc=?="

**Notes**
For a file like Koala.jpg fileContent.Headers.ContentDisposition is form-data; name="file"; filename="Koala.jpg".
Initially, it's an issue with ContentDispositionHeaderValue (https://github.com/microsoft/referencesource/issues/140), but I don't know how to fix it there.

**Comment by asynchk** [comment]
Thanks for raising the issue I am facing the same problem

**Comment by PooraniPerumal** [comment]
I am facing the same issue.

**Comment by alexeyzimarev** [comment]
Normally, the server should be able to decide the MIME-encoded filename. The current implementation, however, doesn't support the `filename*` parameter, which is the UTF-8 encoded filename. It worked before. I think the reason for using the current code is that the default values aren't enclosed in quotes and it broke some other servers.

I wish that people who develop servers spend some time reading the docs about how this all should work... Checking some other things now.

**Comment by alexeyzimarev** [comment]
Ok, I am sorry to say but your code doesn't work. I will create another PR. When I made it work as you expected it to work (without encoding), the tests fail as the ASP.NET Core WebAPI doesn't like it. These tests only passed because your code didn't work. What you got, in fact, is the `filename*` parameter in the header, which is currently disabled by default.
