### ISSUE TITLE
Does Restsharp supports .Net Framework 4.8?

### ISSUE THREAD

**Issue by rajeshkannavelu** [restsharp/RestSharp#1830]
Hi,

Currently I'm upgrading the restsharp to 107.3.0 but the  app framework is 4.5, in order to support the latest restsharp I have to upgrade the .net framework to 4.6 instead the latest version 4.8 since the support is not available.

Is there any restsharp version that supports .net framework 4.8?

I would appreciate if someone could clarify.

**Comment by alexeyzimarev** [comment]
It's explicitly requested not to use issues for questions. Compatibility matrix is available on nuget.org for the packages, what is compatible with .NET Standard is available in Microsoft documentation.
