### ISSUE TITLE
RestSharp request fails with .NET Framework 4.8, but runs perfectly with .NET 5.0, .NET Core 3.1

### ISSUE THREAD

**Issue by jochenwezel** [restsharp/RestSharp#1832]
The identical code is used for a unit test library for following platforms with following results (all Windows 10, RestSharp 107.3)
* RUN FAILED WITH EXCEPTION: .NET Framework 4.8
* RUN SUCCESSFUL: .NET Core 3.1
* RUN SUCCESSFUL: .NET 5.0

## Exception when run with .NET Framework 4.8

Unit test start with `dotnet test --framework net48` 

Catched Exception:
``` 
CenterDevice.Rest.Exceptions.RestClientException : Expected status code "OK" but got "NoResponse"
  ----> System.Net.ProtocolViolationException : Cannot send a content-body with this verb-type.
   at CenterDevice.Rest.ResponseHandler.StatusCodeResponseHandler.ValidateResponse(RestResponse result) in D:\a\CompuMaster.CenterDevice.IO\CompuMaster.CenterDevice.IO\CenterDevice.Rest\Rest\ResponseHandler\StatusCodeResponseHandler.cs:line 26
   at CenterDevice.Rest.Clients.CenterDeviceRestClient.UnwrapResponse[T](RestResponse`1 result, DataResponseHandler`1 handler) in D:\a\CompuMaster.CenterDevice.IO\CompuMaster.CenterDevice.IO\CenterDevice.Rest\Rest\Clients\CenterDeviceRestClient.cs:line 195
   at CenterDevice.Rest.Clients.User.UserRestClient.GetLoggedInUserData(OAuthInfo oAuthInfo) in D:\a\CompuMaster.CenterDevice.IO\CompuMaster.CenterDevice.IO\CenterDevice.Rest\Rest\Clients\User\UserRestClient.cs:line 27
   at CenterDevice.IO.IOClientBase.CurrentContextUserId() in D:\a\CompuMaster.CenterDevice.IO\CompuMaster.CenterDevice.IO\CenterDevice.Rest\IO\IOClientBase.cs:line 195
   at Scopevisio.OpenApi.Test.CollectionsTest.GetCollectionIds() in D:\a\CompuMaster.CenterDevice.IO\CompuMaster.CenterDevice.IO\Scopevisio.Teamwork.Test\CollectionsTest.vb:line 14
--ProtocolViolationException
   at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
   at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
   at System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState state)
   at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at RestSharp.RestClient.<ExecuteInternal>d__1.MoveNext()
```

RestSharp client initialization:
```C#
            var options = new RestClientOptions(configuration.BaseAddress)
            {
                UserAgent = configuration.UserAgent
            };
            var client = new RestClient(options);
            //remove all XML deserializers since response is always expected as JSON, never XML
            client.UseJson();
```

**Comment by alexeyzimarev** [comment]
It's great that you found it. I will take a look if I can fix it on that level.

**Comment by jochenwezel** [comment]
> Just removing the content-type header from GET requests might not be the best idea.

I'm not familiar with the HTTP specs, but I understood it always in meaning of
* the header Content-Type is related to the provided content with the HTTP request, 
* the header Accept is related to the expected content of the HTTP response

That's why I just dropped the Content-Type header and it seems to work in my unit tests:
The HttpClient now starts sending the requests (previously the ExecuteInternal failed already before sending the request at .NET Framework 4.8) and completes as expected (at least with the web service which I use in my tests)

**Comment by alexeyzimarev** [comment]
I understand, and you are right. GET requests should not contain the `Content-Type` header, as they should not contain any body. But, you know, there are a lot of weird servers out there.

RestSharp doesn't add the content-type header to GET requests, and I specifically wrote in the documentation that people should _not_ add it manually, as it usually just break things.

**Comment by jochenwezel** [comment]
> But, you know, there are a lot of weird servers out there

I fully understand and consent, absolutely! ;-)

**Comment by Myster** [comment]
@jochenwezel Did you find a workaround where you could make GET requests with a body?
Here's what I'm trying:
```
			var request = new RestRequest("availablecourses").AddJsonBody(new
			{
				ProductId = courseId,
				RegionId = regionId,
				When = dateRange
			});
			request.AddHeader("Content-Type", "application/json");
			var response = apiClient.ExecuteWithAuth<CrmAvailableCourses>(request);
			return response.Data.AvailableCourses;
```
and I get a response.ErrorException = "Cannot send a content-body with this verb-type."

**Comment by jochenwezel** [comment]
to add Content-Type headers, I call following method in my code, for I added it at a central place:
```c#
        protected RestRequest AddContentTypeHeader(RestRequest request, string contentType)
        {
            if (request.Method == Method.Get) throw new ArgumentException("Adding header Content-Type not supported for GET requests", nameof(request));
            request.AddHeader(CONTENT_TYPE, contentType);
            return request;
        }
```

your following line makes sense only if you use e.g. HTTP-POST requests, but is forbidden (.NET 4.x) /makes no sense (.NET Core) for HTTP-GET requests:
```c#
request.AddHeader("Content-Type", "application/json");
```
so, you might just drop this line for GET requests.

for all your requests, you might want to send `Accept` headers instead, if you want to ensure to get JSON instead of XML responses.

Maybe you also want to use `client.UseJson();` 

For my personal issue, I played around with and manipulated the headers of the HTTP requests with Telerik Fiddler, https://www.telerik.com/fiddler and this helped a lot to understand what RestSharp sends out and the remote server replies.

**Comment by Nyconing** [comment]
> to add Content-Type headers, I call following method in my code, for I added it at a central place:
> 
> ```cs
>         protected RestRequest AddContentTypeHeader(RestRequest request, string contentType)
>         {
>             if (request.Method == Method.Get) throw new ArgumentException("Adding header Content-Type not supported for GET requests", nameof(request));
>             request.AddHeader(CONTENT_TYPE, contentType);
>             return request;
>         }
> ```
> 
> your following line makes sense only if you use e.g. HTTP-POST requests, but is forbidden (.NET 4.x) /makes no sense (.NET Core) for HTTP-GET requests:
> 
> ```cs
> request.AddHeader("Content-Type", "application/json");
> ```
> 
> so, you might just drop this line for GET requests.
> 
> for all your requests, you might want to send `Accept` headers instead, if you want to ensure to get JSON instead of XML responses.
> 
> Maybe you also want to use `client.UseJson();`
> 
> For my personal issue, I played around with and manipulated the headers of the HTTP requests with Telerik Fiddler, https://www.telerik.com/fiddler and this helped a lot to understand what RestSharp sends out and the remote server replies.

Not true, it is allowed and actually for some API you will need Content-Type in GET call. Like Oracle Netsuite, restlet API https://stackoverflow.com/questions/43525585/netsuite-restlet-error-code-invalid-return-data-format

Hence RestSharp isnt able to make access GET api call to Oracle Netsuite, restlet API

**Comment by alexeyzimarev** [comment]
@Nyconing yeah, the argument is not about servers accepting request body in GET requests. It's about what is possible and what is not supported by .NET. RestSharp doesn't implement the wire protocol, it uses .NET's `HttpClient` to make calls. If a particular implementation doesn't support GET requests with body, we can't do anything about it.

The approach taken by Microsoft is quite clear:

> A GET request shouldn't send a body and is used (as the method name indicates) to retrieve (or get) data from a resource
([source](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient#http-get))

I even saw an article on Microsoft Learn that explicitly said libraries should not support GET calls with a content body, but I can't find it.

**Comment by Nyconing** [comment]
I think its actually just a normal header parameter named content-type with value application/json, not a body. Only .NET framework's HttpClient has flaw treat it as a body and give error because GET dont have a body.. 

I can confirm this isnt happen on .NET 7, I have planned migration but before this we rollback to using old version...
