### ISSUE TITLE
No ClientCertificates defined in RestClient

### ISSUE THREAD

**Issue by jeff41101** [restsharp/RestSharp#1840]
**Describe the bug**
I used RestSharp in my code, here's my code
```
string domain = "https://domain.dev";
var client = new RestClient(domain + "/licenses/bindings");
string certFile = Path.GetFullPath(Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "curl", "staging.pfx"));
X509Certificate2 certificate = new X509Certificate2(certFile, "code");
client.ClientCertificates = new X509CertificateCollection() { certificate };
```
But for the last line of the code, ClientCertificates isn't defined therefore there's an error, not sure what caused this.

**To Reproduce**
So I replicated these code from another project which works in my computer, so I'm thinking maybe it's because of the the version of RestSharp? This is the current version that I'm using 'RestSharp.107.3.0'

**Desktop (please complete the following information):**
 - OS: Windows
 - .NET version 4.8.04084
 - Version 'RestSharp.107.3.0'

**Comment by alexeyzimarev** [comment]
Yeah, it's documented https://restsharp.dev/v107/#reference
