### ISSUE TITLE
Recommended Usage in docs uses GetAsync; should it be GetJsonAsync?

### ISSUE THREAD

**Issue by CaiusJard** [restsharp/RestSharp#1842]
I'm using v107.3. I get "does not contain a definitionfor .. and no accessible extension .." compiler errors when using the example code from the docs

Example code line from [Recommended Usage](https://restsharp.dev/v107/#recommended-usage) docs says:

```
    => _client.GetAsync<GitHubRepo[]>("users/aspnet/repos");
```

Should it say `GetJsonAsync`, or do we need to import something that introduces this `GetAsync<T>(string)` method? Could that import be added to the docs?

Also same question to "simplified API" in [making requests](https://restsharp.dev/v107/#making-requests) says:

```
var request = new MyRequest { Data = "foo" };
var response = await client.PostAsync<MyRequest, MyResponse>(request, cancellationToken);
// response will be of type TResponse
```

Should it be `PostJsonAsync`/have a string URL in there?

**Comment by alexeyzimarev** [comment]
You are right, those should be `GetJsonAsync` and `PostJsonAsync`. Both `GetAsync` and `PostAsync` need an instance of `RestRequest`.
