### ISSUE TITLE
Consider making ThrowIfError public

### ISSUE THREAD

**Issue by Strepto** [restsharp/RestSharp#1843]
https://github.com/restsharp/RestSharp/blob/271ddff591c02ebc114ef22239fe139727b3d431/src/RestSharp/RestClient.Async.cs#L133-L138

Throw if error is a useful helper if making own handling of RestResponses from RestClient, as seen internally in the extension methods such as . 
https://github.com/restsharp/RestSharp/blob/271ddff591c02ebc114ef22239fe139727b3d431/src/RestSharp/RestClientExtensions.cs#L167-L171

Making this public would make it easier to add other similar extension methods.

**Comment by alexeyzimarev** [comment]
These extensions are currently public
