### ISSUE TITLE
Invalid JSON returned from server with RestSharp 107.0.0 (Fine in versions prior to 107.0.0)

### ISSUE THREAD

**Issue by luke9216** [restsharp/RestSharp#1848]
I upgraded from RestSharp 106.15.0 to 107.0.0 and I am now receiving the following error in the response message when I do a POST request with a JSON body (the request JSON body has not been altered).

    "Invalid Json encountered. Details: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 1718."

This is the whole response content:

```
    {
      "resourceType": "OperationOutcome",
      "issue": [
        {
          "severity": "fatal",
          "code": "exception",
          "details": {
            "text": "Invalid Json encountered. Details: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 1718."
          }
        }
      ]
    }
```

I believe it has been caused by an internal change to RestSharp. Nothing has changed in the code except for the RestSharp version number. I have tested versions above 107.0.0 and I receive the same error.

```
        public async Task<object?> PatientCreate(Patient patient)
        {
            var request = new RestRequest("Patient", Method.POST);

            request.AddHeader("Accept", "application/fhir+json");
            request.AddHeader("Content-Type", "application/fhir+json");
            request.AddHeader("Authorization", "123");

            var ctx = new FhirJsonSerializer();
            var body = await ctx.SerializeToStringAsync(patient);
            request.AddBody(body);

            var res = await _client.ExecuteAsync(request);
            return res.Content;
        }
```

**Comment by alexeyzimarev** [comment]
Check the request body and you will see what's wrong. The guidelines are in the issue template.
