### ISSUE TITLE
Error :: The Domain part of the cookie is invalid.restsharp

### ISSUE THREAD

**Issue by rajeshkannavelu** [restsharp/RestSharp#1850]
Hello,

Recently I have migrated to RestSharp 107.3 from 105.2. When I change my code to add the cookies from RestClient, running to below issue,
 
**Error - The 'Domain'='https://api.test.com' part of the cookie is invalid.**

This is how I try to add cookie - **client.AddCookie("cookieName", cookieValue, baseUrl, request.Resource);**

If I pass null to the baseUrl and Resource, that is also not working and it is expecting the parameter to be passed.

Tried CookieContainer but same error and encode cookie value.

Kindly suggest is there a way to resolve the issue.
 
Thank you!

**Comment by Elephant-Vessel** [comment]
The value for the domain should not contain the protocol. Try Domain = api.test.com instead.
