### ISSUE TITLE
Restsharp Version 107.3.0 producing CS1545 Error using .net 2.0 Standard in Unity

### ISSUE THREAD

**Issue by 0Flush0** [restsharp/RestSharp#1856]
Using the restsharp dll for the .net 2.0 standard is producing the CS1545 error.
The Api compatibillity level is set to .NET Standard 2.0 in the Unity 3d Game engine.

**To Reproduce**

1. Download the Restsharp Version 107.3.0 from Nuget.org
2. Import the dll for .net standard in to your unity plugins folder
3.  Directly access property like "RestResponse.Content" or "RestResponse.IsSuccessful"

**Stack trace**

Assets\Scripts\Network\GameConnection.cs(51,85): error CS1545: Property, indexer, or event 'RestResponseBase.Content' is not supported by the language; try directly calling accessor methods 'RestResponseBase.get_Content()' or 'RestResponseBase.set_Content(??)'

**Desktop**
 - OS: Windows 11
 - .NET version .Net 2.0 Standard
 - Version 107.3.0

( Sry for bad english)

**Comment by ZqWong** [comment]
Same issues.

- OS: Windows 11
- .NET version .Net 4.x
- Version 107.3.0
