### ISSUE TITLE
RestSharp does not return correct status code

### ISSUE THREAD

**Issue by fairking** [restsharp/RestSharp#1859]
**Describe the bug**
Checked the postman returns 401 without and 200 withing api key. RestSharp returns always 404.

**To Reproduce**
Generate https://eazycollectservices.github.io/EazyCollectAPIv3/swagger.json via  
https://github.com/swagger-api/swagger-codegen#generators and try to call "https://playpen.eazycollect.co.uk/api/v3/client/XXXXXX/customer" withing `apiKey` header and without. It produces wrong status codes.

**Expected behavior**
Behaving as postman.

**Stack trace**
N/A

**Desktop (please complete the following information):**
 - OS: Win10
 - .NET version .netstandard2.0
 - Version the latest

**Additional context**
Please fix. Thank you.

**Comment by fairking** [comment]
Related issue: https://github.com/OpenAPITools/openapi-generator/issues/12368

**Comment by alexeyzimarev** [comment]
It's a Swagger code generator that is wrong.

**Comment by fairking** [comment]
Thanks @alexeyzimarev 

Ok. I fixed my issue by implementing own generator.
Contributors are welcome: https://gitlab.com/fairking/unigen
