### ISSUE TITLE
Xamarin.Forms Hangs

### ISSUE THREAD

**Issue by markhotchkiss** [restsharp/RestSharp#1860]
Hi Everyone,

I am trying to use RestSharp to get data from a Rest API.  Whenever I hit the "ExecuteAsync" line, the whole app hangs and it never returns.  I have a Test project, and when this calls the same method, it returns without issue.

Interestingly, adding ThrowOnError and Timeouts is having no effect at all.  It always hangs on the await client.ExecuteAsync(request) line.

I have also tried using ExecuteGetAsync() and ExecutePostAsync() methods and the same happens.

Is there an issue using RestSharp with Xamarin.Forms?

Here is my code:

```
        public async Task<string> GetValue(string id)
        {
            var clientOptions = new RestClientOptions("my-url")
            {
                ThrowOnAnyError = true,
                Timeout = 1000
            };

            var client = new RestClient(clientOptions);
            var request = new RestRequest("my-resource", Method.Get)
                {
                    Timeout = 1000
                };

            var resp = await client.ExecuteAsync(request);

            return resp.Content;
        }
```

Any help would be greatly appreciated as it is causing me a bit of a headache.

Thanks in advance!

**Comment by markhotchkiss** [comment]
Update!

In case anyone is interested, I have found that you need to update the "Button Click" event to be async rather than using GetAwaiter.

For example this will not work:
```
private void BtnTempUp_OnClicked(object sender, EventArgs e)
        {
            GetValue("").GetAwaiter().GetResult();
        }
```

This, however, will work

```
private async void BtnTempUp_OnClicked(object sender, EventArgs e)
        {
            await GetValue("");
        }
```

**Comment by alexeyzimarev** [comment]
Yeah, we have a similar discussion about calls from WPF. @kendallb implemented an async wrapper and all the sync methods are back in the latest preview, so you might try it too.

**Comment by kendallb** [comment]
Yes, that is correct. You need to be async all the way to the top, especially in UI applications. Or you need to use a proper sync wrapper if you need to tie into a sync function as GetAwaiter().GetResult() will deadlock all the time in WPF, WinForm or even ASP.net MVC application code.

**Comment by kendallb** [comment]
This is required reading to understand the nuances of async :)

https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
