### ISSUE TITLE
Get Response Code 0 On .net core6 after close fiddler

### ISSUE THREAD

**Issue by yezhi84** [restsharp/RestSharp#1864]
During my program running, if i close fiddler,  next ExecuteAsync will get response code 0

**To Reproduce**
1、Start Fiddler Before start my program
2、Start my program
3、Do something which triggers ExecuteAsync invoked
4、Close Fiddler
5、Do something else which triggers ExecuteAsync invoked. (Here, i will get response 0.)

**Stack trace**
     System.AggregateException:“One or more errors occurred. (由于目标计算机积极拒绝，无法连接。 (127.0.0.1:8888))”
     System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(System.Net.Sockets.SocketError, 
     System.Threading.CancellationToken)
    System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(short)
    System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
    System.Net.Sockets.Socket.ConnectAsync.__WaitForConnectWithCancellation|277_0(System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs, System.Threading.Tasks.ValueTask, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
    System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(string, int, System.Net.Http.HttpRequestMessage, bool, System.Threading.CancellationToken)

**Desktop**

OS: Windows 11
.NET version .Net Core 6.0 
Version 107.3.0

**Comment by alexeyzimarev** [comment]
Using Fiddler adds a proxy, and when you keep the app running with the client instance that is configured with the proxy, when you close Fiddler, the client will still try using the proxy and will fail. It's not a RestSharp issue.
