### ISSUE TITLE
Add FollowRedirects to RestRequest

### ISSUE THREAD

**Issue by cYCL157** [restsharp/RestSharp#1865]
It used to be possible to set FollowRedirects on the client before executing a request, I am no longer seeing how to do this in v107.  In following with the recommendation of using the composition pattern with RestClient, i may have some requests that i want to allow following while others i do not, so it's not feasible to set a singular value on the client.

If i missed some obvious way of handling that, i would be appreciative if that could be pointed out.

I imagine the same issue exists for any value that is on RestClientOptions that could vary by request, i.e. credentials, certificates, throw on error, etc.

**Comment by alexeyzimarev** [comment]
It's an option of `HttpMessageHandler` and therefore it can only be set on the client level.

**Comment by cYCL157** [comment]
Thanks for the response, not what i had hoped for but what I had feared.  it does sound like a RestClientFactory might really be helpful in working around some of these changes/issues.

**Comment by alexeyzimarev** [comment]
I understand that it's not what you'd hope for. but that's how HttpClient works, and RestSharp is just a wrapper around it.

All the options that aren't for `HttpMessageHandler` are available on the request level, but those that are must be set for the client. You'd normally need one instance per external API, and the issue doesn't exist, or not that apparent. Still, for multi-tenant apps, some things can be per request, and some improvements are there in the pipeline (like authenticator). But it's only for those things that RestSharp controls. `HttpMessageHandler` is not one of those.

**Comment by cYCL157** [comment]
Thanks.  I do understand the limitations of what you have to work with, not quite sure how i would deal with it -- but some of these things present issues that i don't have today in using restsharp and need to figure out how i will work around them.  If i have any stroke of genius, will be sure to share that back with you.  I have loved using restsharp and have been using it for years and as a consultant have brought it to many clients, so i have vested interesting in seeing things resolved.  Thank you for your efforts on this and for sharing with all of us!

**Comment by alexeyzimarev** [comment]
The issue with RS 106 is that when using it with settings that apply to `HttpMessageHandler`, it will create a new handler under the hood, which leads to all possible issues like hanging connections and connection pool starvation. That's how `HttpWebRequest` works after it turned to be "legacy", and there's nothing to be done about it. You can equivalently use new `RestClient` instances for requests that require different settings.
