### ISSUE TITLE
Stream.Length not supported with version 108.0

### ISSUE THREAD

**Issue by leynae** [restsharp/RestSharp#1871]
Hi,

**Describe the bug**
Before doing some operations on a stream, we check the size of the stream with the method Length

        var request = new RestRequest($"xxxxxxxxxxx?filePath={filePath}", Method.Get);
        var stream = await restClient.DownloadStreamAsync(request);

        if (stream.Length == 0)
        {
            _logger.LogWarning($"Download for file {filePath} returned an empty response");
            return null;
        }

        ...

With the version 107.3.0, this code is working correctly. The Length returned 0 in case of empty stream but with the latest version 108.0, the method threw a NotSupportedException.

How can we check if the stream is empty or not with the new version?

**Stack trace**
`System.NotSupportedException: Specified method is not supported.
at System.Net.Http.HttpBaseStream.get_Length()`

**Desktop (please complete the following information):**
 - OS: linux
 - .NET version: net 6.0
 - Version: 108.0.0]

**Comment by alexeyzimarev** [comment]
I think it's this, v108 returns the response when headers are received, but it doesn't know much about the content:

https://github.com/restsharp/RestSharp/blob/ebb1df1cb919466e6490175afb028a16e262ac40/src/RestSharp/RestClient.Async.cs#L98-L99

@kendallb thoughts? maybe make it optional?

**Comment by alexeyzimarev** [comment]
Depends on the use case, I guess. I don't know what's the reason to check the length of the stream, but it seems to be a breaking change. I would suggest keeping the current functionality as default, then we need to add a note to the changelog. Also, we could add an optional `bool streamResponse = true` so people can revert to the previous behaviour if necessary.

**Comment by kendallb** [comment]
Ahh, yes. Apologies I misread that bit :)
