### ISSUE TITLE
Posting multi form data without files does not work anymore in v107

### ISSUE THREAD

**Issue by laxman4434** [restsharp/RestSharp#1873]
We are on version 107.3.0 of RestSharp
Before upgrading to v107, following code worked to post multi form data to an authentication Api (Zesty.io)
So we post the email and password to get an authentication token.

`var request = new RestRequest( url, Method.Post);`
`if ( payload != null )`
 `{`
	`foreach ( var item in (Dictionary<string, string>)payload )`
	   `{`
		   `request.AddParameter( item.Key, item.Value );`
	   `}`
 `}`
`var resp = await restClient.ExecuteAsync( request );`

When tried from postman, the authentication works fine. Following the some snapshots from postman.

![Capture](https://user-images.githubusercontent.com/7378501/174215498-3d827b47-9d35-4700-8123-6147d4ec45b9.PNG)

![Capture1](https://user-images.githubusercontent.com/7378501/174215505-ce996742-56ad-4959-9a62-4f7ef991dce0.PNG)

RestSharp v107 documentation https://restsharp.dev/v107/#body-parameters says to use `AddBody` intsead of `AddParameter`.

Tried that as well and it didn't work for us.

Any help would be appreciated.

**Comment by mythjuha** [comment]
Try

`request.AddBody(body, "application/x-www-form-urlencoded");`

**Comment by alexeyzimarev** [comment]
@mythjuha wrong suggestion.

@laxman4434 the [default way](https://restsharp.dev/usage.html#get-or-post) to use parameters with POST is URL-endoded form. If you must post as multipart form, you need to set the request property `AlwaysMultipartFormData` to `true`. This behaviour is the same as it was in previous versions. Your Postman example uses the multipart form data.

**Comment by laxman4434** [comment]
Hi @alexeyzimarev,

Thanks for your response. I already tried with `AlwaysMultipartFormData = true`. I always get the response back as Bad request

![image](https://user-images.githubusercontent.com/7378501/174467904-af82ad95-6035-4d9d-a34c-ecb4d497512f.png)

Also, tried adding the headers as
`request.AddHeader( "Content-Type", "multipart/form-data;" );` which gives me time out error after 100s.

**Comment by alexeyzimarev** [comment]
You need to use a request tracer (I can suggest requestbin.com) to see what your request contains, and compare it with your Postman call. You also should not set the content-type header manually, as mentioned in the documentation.

**Comment by laxman4434** [comment]
thanks @alexeyzimarev. Traced the request through requestbin.com and figured out that parameters needed double quotes.

Setting 	`request.MultipartFormQuoteParameters = true;` worked for me.

Thanks once again for your help
