### ISSUE TITLE
Authorization JWT not working in Restsharp

### ISSUE THREAD

**Issue by royaldragonit** [restsharp/RestSharp#1876]
![image](https://user-images.githubusercontent.com/72593390/175196591-8ad4abd7-489b-4638-8621-654e2305a317.png)

Lastmonth worrking normal, today, i open my project and not working.

Visual: **Visual Studio 2022**
API: **JWT Bearer .NET Core 5**.
Client: **Windows Form 4.7.2**
Restsharp Version: **106.11.1**

Postman working normal but restsharp **unauthorize**.

**Comment by alexeyzimarev** [comment]
Not sure what it has to do with RestSharp.

**Comment by royaldragonit** [comment]
Postman ok. But restshafp error

**Comment by alexeyzimarev** [comment]
So what? You said it worked, but now it doesn't, what kind of help do you expect? The server doesn't authorise you. Check your request content, check the response, and find out why it doesn't work.

**Comment by royaldragonit** [comment]
> So what? You said it worked, but now it doesn't, what kind of help do you expect? The server doesn't authorise you. Check your request content, check the response, and find out why it doesn't work.

![image](https://user-images.githubusercontent.com/72593390/175940846-c31a7c96-5d70-40da-bf6c-e5c0e0dcad6e.png)
![image](https://user-images.githubusercontent.com/72593390/175940952-2906d831-0585-4935-a1e1-e3ffe2c3e7ef.png)

Header Authorization not found.
