### ISSUE TITLE
When the value of the form is null, a null reference exception is thrown

### ISSUE THREAD

**Issue by alexinea** [restsharp/RestSharp#1878]
When I submit a form item with a value of `null`, an object null reference exception is thrown.

- Type of form item: String
- The value of the form item: `null`

I don't have this problem when I use RestSharp v106. This problem appeared after I upgraded to v108.

The code locations involved are:
https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/Request/RequestContent.cs#L172

This problem may be caused by the use of the `!` operator.

**Comment by alexinea** [comment]
The current solution is to assign the initial value: `""` to the String form item with the `null` value.

**Comment by alexeyzimarev** [comment]
@kendallb

**Comment by kendallb** [comment]
What should be the normal value to pass over the wire in case of a null in the form? Just leave it out? If so I think maybe a where not null in the select would do it. Have to write a unit test case to trigger the error and then it should be easy to fix.
