### ISSUE TITLE
RestRequest post fails when using AddBody with string. This worked fine in 107.3.0.

### ISSUE THREAD

**Issue by HHasenack** [restsharp/RestSharp#1886]
This piece of code works just fine using restsharp v107.3.0 but failes when using 108.0.1
```
public async Task PostTest()
        {
            var calcId = await AddCalculationSetup();

            string paramValue = "InvalidValue";

            // Set a parameter with an invalid value
            var request = new RestRequest($"{url}/CalculationSetups/{calcId}/Parameters/InheritsFromCalcSetup").
                              AddBody(paramValue);
            var response = await restClient.ExecutePostAsync(request); 
            Assert.AreEqual(HttpStatusCode.Created, response.StatusCode, response.Content);
           . . .
```
The controller handler involved looks like this, but doesnt get called when using restclient v108, as stated before v107 works fine.

```
. . .
        /// <summary>
        /// Set a value for a parameter
        /// </summary>
        /// <param name="projectIdentifier">identifier of the project</param>
        /// <param name="itemIdentifier">identifier of the parameterized collection item</param>
        /// <param name="parameterIdentifier">identifier of the parammeter</param>
        /// <param name="value">value for the param</param>
        [HttpPost]
        [SwaggerOperation("Set a value for a parameter")]
        [Route("{parameterIdentifier}")]
        [SwaggerResponse(StatusCodes.Status201Created)]
        [SwaggerResponse(StatusCodes.Status404NotFound, Type = typeof(string))]
        [SwaggerResponse(StatusCodes.Status400BadRequest)]
        public virtual IActionResult Post(string projectIdentifier, string itemIdentifier, string parameterIdentifier, [FromBody] object value)
        { . . . }

```

The Assert in the unit test statement fails, and error returned is:

```
 PostTest
   Source: ValueSetTest.cs line 30
   Duration: 200 ms

  Message: 
Assert.AreEqual failed. Expected:<Created>. Actual:<BadRequest>. {
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-4fc8ce2dfbaa969137ff4f9482017569-1090e9c87770ee73-00",
  "errors": {
    "$": [
      "'I' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0."
    ],
    "value": [
      "The value field is required."
    ]
  }
}

  Stack Trace: 
ValueSetTest.PostTest() line 40
ThreadOperations.ExecuteWithAbortSafety(Action action)

```

- Thx, Hans

**Comment by HHasenack** [comment]
Hi alexy - sorry to get back to this after a long while. Unfortunately your proposed fix doesn't solve the problem. I even tried all the other options (Json, Binary, Xml and None), but no luck.
Only the 
```
request.AddParameter(new JsonParameter("", paramValue, RestSharp.Serializers.ContentType.Json));
```
did the trick. Though it allowed shorter notation because of default parameters:
```
request.AddParameter(new JsonParameter("", paramValue));
```
So it seems some of the logic was broken (or repaired? in release `108.0`) that made the decision to store the provide value from `AddBody` using `request.AddParameter(new JsonParameter...))` somehow.

I think I could patch this in restsharp sources, but I am unsure wether it "works as designed" in v108 or v107

as restsharp was only used in my unit testing code, I simply changed my sources to work around the problem.

Thx

**Comment by IanElsinga** [comment]
I would like to report that in version 108.0.2 this is still an issue in that the following does not work because the resulting `DataFormat` in the Parameter winds up being `None`. Because of this, the parameter is sent without quotes (not as JSON):

`request = new RestRequest(method).AddStringBody(json, DataFormat.Json);`

(where `json = "simple string value"`)

However, if you use the following, it works properly.  `DataFormat` in the Parameter is set to `Json` and the value is sent with quotes:

`request = new RestRequest(method).AddParameter(new JsonParameter("", json));`

The same problem exists with this method but I understand that this is not technically appropriate for a string:
`request = new RestRequest(method).AddJsonBody(json);`

**Comment by alexeyzimarev** [comment]
I believe there's a check that prevents setting the parameter type to JSON if the string doesn't contain a valid JSON object. Why are you trying to send a `sample string value` as a JSON as it's apparently not a valid JSON?

**Comment by alexeyzimarev** [comment]
`AddJsonBody` is designed for serializable objects, not for strings. It's clearly documented.

**Comment by IanElsinga** [comment]
Thanks Alex, I understand and agree regarding `AddJsonBody`. 

However, a single quoted string is valid JSON, and in our application is treated thus, both for client and server (asp.net core).  According to RFC7159, any JSON value is valid JSON text and valid "application/json" content, including simple strings.

**Comment by IanElsinga** [comment]
Sorry, I might not be understanding you, but an arbitrary string IS valid JSON, as indicated above according to RFC7159.  I'm actually asking about `request = new RestRequest(method).AddStringBody(json, DataFormat.Json);`. If `json` is just a single arbitrary string, it should be treated as valid JSON because `DataFormat.Json` is specified and because a single arbitrary string is valid JSON.

**Comment by alexeyzimarev** [comment]
> including simple strings with double quotes.

that is what I meant, not "just" a string. if you try to serialise a string value, you'll see that it gets double quoted.

**Comment by alexeyzimarev** [comment]
Basically, you can use:
```
AddJsonBody(str) // will serialise the string to a double-quoted string, making it a valid JSON
```

or

```
AddStringBody(str, DataFormat.Json)
```

it won't touch the string, just add it as a body, as-is

**Comment by IanElsinga** [comment]
Here is the difference, as demonstrated by requests sent from RestSharp logged by an asp.net core endpoint. Note the body field which is the string payload in question. 

The following uses `AddStringBody(str, DataFormat.Json)` and is not recognized by the controller action (AddJsonBody produces the same result):
![image](https://user-images.githubusercontent.com/3292591/194432108-336dec43-4989-4631-80d2-fe1dde9546fc.png)

While the following uses `AddParameter(new JsonParameter("", json))` and works as expected.
![image](https://user-images.githubusercontent.com/3292591/194432002-2f06c2e2-60e9-4673-ada8-18e0bf573442.png)


The one that works is sent with double quotes which makes it valid JSON. The other one is missing double quotes and is not recognized by the controller action. 

I believe that `AddStringBody(str, DataFormat.Json)` should behave the same as  `AddParameter(new JsonParameter("", str))`.  This used to work in a previous version. 

Apologies for the back and forth and I hope that I've been able to explain it better.

**Comment by IanElsinga** [comment]
Ok then it is `AddJsonBody` which is not working properly, as it now produces the same result as  `AddStringBody` as I indicated above. I actually originally had `AddJsonBody` in my code for this scenario which I had to swap out for `AddParameter`.

**Comment by alexeyzimarev** [comment]
Right, I checked the code again. It looks like I got so many complains that adding a pre-serialised JSON body using `AddJsonBody` doesn't work that I made it like this:

```
    public static RestRequest AddJsonBody<T>(this RestRequest request, T obj, string contentType = ContentType.Json) where T : class {
        request.RequestFormat = DataFormat.Json;
        return obj is string str ? request.AddStringBody(str, DataFormat.Json) : request.AddParameter(new JsonParameter("", obj, contentType));
    }
```

It's not easy to satisfy conflicting requirements. Your approach is correct in any case.

**Comment by IanElsinga** [comment]
Thanks Alexey, unfortunate, but I understand!

**Comment by alexeyzimarev** [comment]
Yeah, I also don't like that very much. But, the number of issues and questions when people were using `AddJsonBody` to send a pre-serialized string was just too much. So, I "fixed it"...

**Comment by kenliao43088** [comment]
good

**Comment by Inquirer-cubic** [comment]
https://lnkr.fun/4c50030



I caught the response
