### ISSUE TITLE
Outdated Documentation: All sync calls in favour of async calls

### ISSUE THREAD

**Issue by nesc58** [restsharp/RestSharp#1896]
The whole documentation according to "All sync calls in favour of async calls" is outdated since v108.0.0. 
A lot of sync calls are back :) (except streaming json? https://github.com/restsharp/RestSharp/pull/1800 https://github.com/restsharp/RestSharp/issues/1797 )

**Comment by alexeyzimarev** [comment]
I removed that line from the docs.

**Comment by alexeyzimarev** [comment]
I don't know what you mean by "the whole documentation is outdated". I have no plans to add examples for sync overloads as they are exactly the same, and just wrap async functions.
