### ISSUE TITLE
Please add IRestClient, IRestRequest, IRestResponse in next release

### ISSUE THREAD

**Issue by javedali-dev** [restsharp/RestSharp#1898]
We are using IRestClient, IRestRequest, and IRestResponse in tests to mock the behavior of Rest Client. Since now these interfaces are deprecated we are not able to write tests properly.

**Comment by alexeyzimarev** [comment]
There's an issue for that already. Also, `IRestRequest` and `IRestResponse` aren't coming back.

**Comment by Matthew-Davey** [comment]
For anyone else like me who stumbles across this issue, the rationale for this decision is explained better [here](https://restsharp.dev/v107/#mocking).

It may seem frustrating at first but I understand the decision.

We followed the advice and had some great success using [mocky.io](https://designer.mocky.io/) (this is not a plug, I am not affiliated with mocky.io).

**Comment by alexeyzimarev** [comment]
The client interface is back since v109. Request and response interfaces are definitely never coming back as these are data structures without functionality.

**Comment by javedali-dev** [comment]
> For anyone else like me who stumbles across this issue, the rationale for this decision is explained better [here](https://restsharp.dev/v107/#mocking).
> 
> It may seem frustrating at first but I understand the decision.
> 
> We followed the advice and had some great success using [mocky.io](https://designer.mocky.io/) (this is not a plug, I am not affiliated with mocky.io).

Just one quick note that I'm currently using the .net flavor of [wiremock](https://github.com/WireMock-Net/WireMock.Net) to mock the API and since it is in memory server it is working for my case. Hope this help other who is looking for mocking endpoints. 😊

**Comment by alexeyzimarev** [comment]
I also mentioned [MockHttp](https://github.com/richardszalay/mockhttp) in the docs as it allows to create a mock message handler and define responses to certain requests. The client will work as it would in a normal environment, but there will be no network calls made, and the handler will return those pre-defined responses.

For RestSharp integrated tests I also use a test server with minimal API that returns what I want. In that case, you can make requests over the wire to localhost, so it allows to introspect the actual request made by `HttpClientHandler` for real.
