### ISSUE TITLE
No default timeout is specified for async requests at least in 106.X versions

### ISSUE THREAD

**Issue by odinserj** [restsharp/RestSharp#1900]
**Describe the bug**

Sorry for probably resurrecting an old version of the package, just wanted to report this problem because it can significantly affect production when RestSharp is used in background processing. At least it will be possible for 106.X users to identify and resolve the issue.

The main problem is that there's no default timeout specified for asynchronous requests at least in versions 106.X. As far as I understand, that version was using `WebRequest` for making requests, and its asynchronous method `BeginGetResponse` lacks of built-in timeout support as [documented in MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.timeout?view=netframework-4.8#remarks). And although RestSharp successfully implements the timeout feature, it's not used by default with asynchronous requests, because the `RestClient.Timeout` property defaults to `0`.

For synchronous requests `WebRequest`'s own timeout is used by default, it's 100 seconds to avoid blocking threads. But although no threads blocked directly in an asynchronous case, continuations will wait forever when no timeout is used and there are network problems, leading to different delays or blocking other parts of code or systems.

Not sure whether this problem was resolved in 107.X or 108.X, I see that now `HttpClient` is used instead of `WebRequest` and unfortunately didn't have time yet to investigate it.

**To Reproduce**

The following code snippet can lead to the timeout problem, when combined with network problems:

```csharp
var client = new RestClient("http://example.com");
var request = new RestRequest(Method.POST);
request.Resource = "api/v2/orders";
request.AddHeader("X-Auth-Token", authToken);

var response = await client.ExecuteAsync(request);
```

And the following way of instantiating `RestClient` resolves all the problems:

```csharp
var client = new RestClient("http://example.com") { Timeout = 15000 };
```

**Expected behavior**

Probably default value can be set for `RestClient.Timeout` property in general, or some non-zero timeout can be used by default only for the asynchronous case, for example matching `WebRequest`'s default 100 seconds.

**Desktop (please complete the following information):**
 - OS: Windows
 - .NET Framework 4.8
 - Version 106.13.0

**Comment by alexeyzimarev** [comment]
I am sorry, but I won't be making changes in v106. It's good that you have a way to solve it by setting the timeout.

The new version uses the `HttpClient` timeout, as well is the request timeout, whatever is _less_.
