### ISSUE TITLE
Response.Content is Empty String When HTTP/1.1 409 Conflict Despite Response Body Is Not Empty

### ISSUE THREAD

**Issue by CodegoErgoSum** [restsharp/RestSharp#1903]
**Describe the bug**
Response.Content returns an empty string when the response is an HTTP/1.1 409 Conflict despite the fact that the response body is not empty.  Response.ErrorException returns System.Net.WebException: The request was aborted: The connection was closed unexpectedly.

**Code**
// LET ME KNOW IF SOMETHING IS WRONG WITH THE CODE

using System;

using RestSharp;

namespace ConsoleApp
{
	internal class Program
	{
		static void Main(string[] args)
		{
			var client = new RestClient("<url>");
			client.Timeout = -1;

			var request = new RestRequest(Method.POST);
			request.AddHeader("Authorization", "Bearer <token>");
			request.AddHeader("Content-Type", "application/json");
			request.AddHeader("Accept", "*/*");
			request.AddHeader("Accept-Encoding", "gzip, deflate, br");
			request.AddHeader("Connection", "keep-alive");

			var body = @"
			{
				""packages"":
				[
					{
						""Certificate"":""CERT97059"",
						""Comments"":""comments2"",
						""Commodities"":
						[
							{
								""CountryOfGoods"":""JP"",
								""Description"":""commodities.description2"",
								""HsTariffNumber"":""8514.4"",
								""Quantity"":1,
								""Value"":5.41,
								""Weight"":3.4
							}
						],
						""DimensionTypeValue"":2,
						""Division"":3,
						""Height"":3.55,
						""Invoice"":""INV945026"",
						""Length"":6.48,
						""License"":""LIC912209"",
						""MailType"":1,
						""Mawb"":""MAUB96529"",
						""OfficeCode"":""OC9407"",
						""OriginWebsite"":""originWebsite2.com"",
						""PostalCharges"":0,
						""ReceiverAddress1"":""receiverAddress1-2"",
						""ReceiverAddress2"":""receiverAddress2-2"",
						""ReceiverAddress3"":""receiverAddress3-2"",
						""ReceiverCity"":""receiverCity2"",
						""ReceiverCountry"":""PE"",
						""ReceiverEmail"":""receiver2@Email.com"",
						""ReceiverName"":""receiverName2"",
						""ReceiverPhoneNumber"":""+51 913461522"",
						""ReceiverState"":""Jauja"",
						""ReceiverZipCode"":""LIMA 28"",
						""SenderAddress1"":""senderAddress1-2"",
						""SenderAddress2"":""senderAddress2-2"",
						""SenderAddress3"":""senderAddress3-2"",
						""SenderCity"":""senderCity-2"",
						""SenderCountry"":""US"",
						""SenderEmail"":""sender2@Email.com"",
						""SenderIdentification"":""TMG2021001"",
						""SenderName"":""senderName2"",
						""SenderPhoneNumber"":""(721) 779-5617 x542"",
						""SenderState"":""VA"",
						""SenderZipCode"":""78425"",
						""ServiceOptValue"":1,
						""ServiceValue"":1,
						""Stamp"":""STAMP1656450537505"",
						""Tracking"":""TRACK1656450537504"",
						""Weight"":3.4,
						""WeightTypeValue"":1,
						""Width"":4.06
					}
				]
			}";

			request.AddParameter("application/json", body, ParameterType.RequestBody);

			IRestResponse response = client.Execute(request);

			Console.WriteLine(response.Content);
			Console.WriteLine("Hit ENTER to close window.");
			Console.ReadLine();
		}
	}
}

**Response**
HTTP/1.1 409 Conflict
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Tue, 02 Aug 2022 09:57:18 GMT
<JSON>

**Expected behavior**
Response.Content should ALWAYS return the response body (if any) regardless of the HTTP response.

**Stack trace**
No exception is thrown.

**Desktop (please complete the following information):**
 - OS: 
 --Edition	Windows 10 Pro
 --Version	21H2
 --Installed on	‎3/‎12/‎2021
 --OS build	19044.1826
 --Experience	Windows Feature Experience Pack 120.2212.4180.0

 - .NET Framework version 4.8

**Additional context**
None

**Comment by CodegoErgoSum** [comment]
Since it has been marked **wontfix**, kindly provide a work-around.

**Comment by alexeyzimarev** [comment]
It's marked wontfix because it's stale.

The issue described occurs with an unsupported version of RestSharp.
