### ISSUE TITLE
Internal Exception thrown

### ISSUE THREAD

**Issue by jebeke65** [restsharp/RestSharp#1910]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
Occasionally the below exception is thrown.
When retrying the call, it's ok.

**To Reproduce**
Below you can find the wrapper code

**Expected behavior**
The exceptions should not occur, as with the 106 version

**Stack trace**
tfsservice : EmptyDB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

   at System.Threading.Tasks.Task.Wait()

   at GeneralTooling.RestApi.Call(HttpMethod method, String url) in C:\TFS\TfsAdministration\POCs\BuFeTT\bufett\src\Libs\GeneralTooling\RestApi.cs:line 199

**Desktop (please complete the following information):**
=============================================
 - OS: Windows 10
 - .NET framework 4.6.2
 - Version [e.g. 107.0.4]

**Additional context**
======================
This is the wrapper that is taken care of the RestSharp.
Randomly the above exception occurs.
When returning to the previous 106 release, the problem does not occur.

public (HttpStatusCode StatusCode, string Content) Call (HttpMethod method, string url, Dictionary<string,string> Parameters, string Body)
{
                var httpMethod = method;
                var request = new RestRequest(url, ConvertMethod(httpMethod));
                if (httpMethod == HttpMethod.Post)
                {
                    request.AddHeader("Accept", "application/json, application/xml, text/json, text/x-json, text/javascript, text/xml");
                    request.AddHeader("Content-Type", "application/json");
                    request.AddQueryParameter("resultFormat", "json");
                }

                foreach (var parameter in Parameters.Where(x => x.Value != null))
                {
                    if (httpMethod == HttpMethod.Post)
                    {
                        request.AddQueryParameter(parameter.Key, parameter.Value);
                    }
                    else
                    {
                        request.AddParameter(parameter.Key, parameter.Value);
                    }
                }

                if (Body != null)
                {
                    request.AddBody(Body, "application/json");
                }

                try
                {
                    var response = _client.Execute(request);
                    return (response.StatusCode, response.Content);
                }
                catch (Exception e)
                {
                    var p = Call2( method,  url);
                    p.Wait();
                    var res = p.Result;
                    var content = res.Content.ReadAsStringAsync().Result;
                    return (res.StatusCode,content);
                }
}

**Comment by alexeyzimarev** [comment]
Sorry, you should a sync method, or properly use async.
