### ISSUE TITLE
'Cannot assign method group to an implicitly-typed variable' error when building on .net framework

### ISSUE THREAD

**Issue by disshishkov** [restsharp/RestSharp#1913]
When build on .net framework not possible to get **Value** from **Parameter** (on .net core all is ok)

when try to assign parameter.Value to some object receive a compile error "Cannot assign method group to an implicitly-typed variable"
```cs
public string Serialize(Parameter parameter)
{
   var obj = parameter.Value;
   return Serialize(obj);
}
```

when try to use directly parameter.Value receive a compile error "Argument 1: cannot convert from 'method group' to 'object'"
```cs
public string Serialize(Parameter parameter)
{
    return Serialize(parameter.Value);
}
```

 - OS: Windows
 - .NET version: .NET framework 4.7.2
 - Version: 108.0.1
 - MSBuild: 16.0

**Comment by alexeyzimarev** [comment]
Could you elaborate on your last comment? What's "the same approach"?

**Comment by disshishkov** [comment]
What is described in the article (using System.Runtime.CompilerServices.IsExternalInit) are used by MS as well

**Comment by alexeyzimarev** [comment]
IsExternalInit is referenced by RestSharp as a package, otherwise it won't compile.

**Comment by alexeyzimarev** [comment]
I don't think it can be "fixed" in any other way than converting `Parameter` from record to class, but I am against it. I believe your workaround works. ExternalInit has nothing to do with it.

**Comment by disshishkov** [comment]
Could you please add an official announcement that you dropped support .net framework. Otherwise it's a very confusing that  .net framework still in the support platform but in real it doesn't work with it.

**Comment by alexeyzimarev** [comment]
RestSharp can be used with .NET Framework. You have a case where you can't use the `Value` property as a parameter, but the value can be extracted to a variable, as you demonstrated. I don't think it means "it can't be used at all".

**Comment by disshishkov** [comment]
It's also doesn't work, just another type of error - "Argument 1: cannot convert from 'method group' to 'object'", so using restsharp with .net framework on full mode is not possible starting of v107

**Comment by Harpush** [comment]
Same for net core 3.1. I too get those errors. Can't seem to get around it unless on net 5. Seems like 107 broke support for anything less than c# 9.

**Comment by alexeyzimarev** [comment]
RestSharp code uses the latest C# version. It does not create any impediments with compiling it to .NET Framework or .NET Core 3.1. The only thing one needs to do for building RestSharp code is to have the latest .NET SDK installed.
