### ISSUE TITLE
Certificates (and other options) set after RestClient construction are ignored

### ISSUE THREAD

**Issue by Davidcc** [restsharp/RestSharp#1917]
**Describe the bug**
Setting Options.ClientCertificates on an existing instance of RestClient had no effect - certificates are not used in the request that is made.

**To Reproduce**
instantiate a RestClient.
add a certificate to the client.Options.ClientCertificates collection.
make a request - no certificate is attached.

**Expected behavior**
I expect that certificates present in the Options.ClientCertificates collection would be attached to any requests made.

**Desktop (please complete the following information):**
windows, .net Core 3.1, RestSharp v108.01

**Additional context**
Looking at the source for RestClient, it sets the certificates on HttpClientHandler if they are present when the RestClient constructor is called, but adding them to the Options after that does nothing. Perhaps the Options should be read-only? This also appears to impact any other properties of the Options.

If I set my certificate into an Options object and pass it to the RestClient constructor, it works and my certificate is passed with the request.

**Comment by alexeyzimarev** [comment]
That's how it works, sorry. I mentioned in another issue that `RestClientOptions` properties were init-only, but it caused compilation issues using legacy SDKs. Therefore, the properties were converted to mutable, but resetting the option property has no effect as those properties are already used to instantiate the message handler, and assigning new value to the property won't change the handler.

**Comment by alexeyzimarev** [comment]
Yeah, it's a good idea. It was not my change to convert `init` to `set`, the docs change should've been part of that PR. Anyway, I'll try to add something to the docs.
