### ISSUE TITLE
Serialization problem

### ISSUE THREAD

**Issue by AdemAygun** [restsharp/RestSharp#1919]
I use Restsharp without any JsonSerializerOptions. After upgrading from 106.11.7 on .net5 to 108.0.1  on .net6:

before upgrade our request:

```
{
    "DATA": [
        {
            "WORK_ORDER_NO": "W123213",
            "COMPANY_CODE": "C423432",
            "VC_FLAG": "4",
            "INVOICE_COMPANY_CODE": "C423432"
        }
    ]
}
```

But after upgrade our request started to be generated like below:

```
{
    "data": [
        {
            "worK_ORDER_NO": "W123213",
            "companY_CODE": "C423432",
            "vC_FLAG": "4",
            "invoicE_COMPANY_CODE": "C423432"
        }
    ]
}
```

**Desktop (please complete the following information):**
 - OS: Centos 7
 - .NET version:  .NET Core 6
 - Version: 108.0.1

**Additional context**

**Comment by alexeyzimarev** [comment]
Please read the docs https://restsharp.dev/v107/#default-serializers
