### ISSUE TITLE
CancellationTokenSource not respected if using IP instead of FQDN if server is offline

### ISSUE THREAD

**Issue by AndreasReitberger** [restsharp/RestSharp#1920]
**Describe the bug**

I'm using RestSharp to communicate with a print server running in the local network.
If the server is offline, the CancellationTokenSource cancels the request after 10s.

However this seems only to work, if I pass the FQDN (myserver.local).
Once using the IP, it takes extremely long till the request is cancelled.

```cs
RestClientOptions options = new(FullWebAddress)
                {
                    ThrowOnAnyError = true,
                    Timeout = 10000,
                };
                HttpClientHandler httpHandler = new()
                {
                    UseProxy = true,
                    Proxy = GetCurrentProxy(),
                    AllowAutoRedirect = true,
                };
                
                httpClient = new(handler: httpHandler, disposeHandler: true);
                restClient = new(httpClient: httpClient, options: options);
```

```cs
RestResponse respone = await restClient.ExecuteAsync(request, cts.Token).ConfigureAwait(false);
```

**To Reproduce**
The full source code, where the example above is, can be found here.
https://github.com/AndreasReitberger/KlipperRestApiSharp/blob/main/source/KlipperSharpWebApi/KlipperSharpWebApi/KlipperClient.cs#L2921

**Expected behavior**
The CancellationTokenSource cancels the request after the applied time, not only when using FQDN.

**Stack trace**
Not available

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET version: NetStandard2.1
 - Version:: 10

**Additional context**

**Comment by AndreasReitberger** [comment]
Any news?

**Comment by alexeyzimarev** [comment]
@AndreasReitberger I am not sure what news you expect, sorry. Since you have an issue you can reproduce, you can submit a PR that fixes it. It's a community project after all.

**Comment by craysiii** [comment]
Just wanted to chime in and say that I believe I am running into the same issue now.

Unfortunately, I'm not yet familiar with the actual source of RestSharp, so I will need to dig in to see what is going on there.

**Comment by alexeyzimarev** [comment]
RestSharp just passes the cancellation token to `HttpClient`, and further, we have no control over what happens. Sorry.

**Comment by craysiii** [comment]
I investigated myself and came to the same conclusion - though I realized that my problem was ultimately different.
