### ISSUE TITLE
JSON unable to deserialize to List<T> if object is not a List

### ISSUE THREAD

**Issue by jy13249** [restsharp/RestSharp#1925]
After upgrading to 108.0.1, I'm experiencing the following error when deserializing a List<object>: "Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List". 

Now before in RestSharp version 106, even if the DTO wasn't a list, the `"IRestResponse<List<object>>"` would not thrown an exception and the Response.Data would just contain 1 object. So when we needed to grab a property(like id) from the response object, we could write "Response.Data[0].id".

The DTO for this object is not a list, so yes, if I change `"RestResponse<List<object>>"` to `"RestResponse<object>",` the deserialization works. 

However there are hundreds of tests that we have written in dozens of different repositories that utilize "RestResponse<List<object>>", as well as "Response.Data[0].id". It would take a massive amount of maintenance and refactoring to make that change.

Is there anyway to set some type of setting to force the deserializer to accept a List<object> and return just 1 object from a List, such as "Response.Data[0]"? Even if the Response is not a list and is just 1 single json object with multple properties?

**Comment by alexeyzimarev** [comment]
I don't know, really. You should not try deserializing a single object as a collection; it's a basic serialisation rule. You can use a custom serializer, deserialize manually, or create a custom contract resolver. There are lots of options.
