### ISSUE TITLE
Issue After upgrading Restsharp version

### ISSUE THREAD

**Issue by myalgomate** [restsharp/RestSharp#1927]
Can someone please help on this issue, i gets hang and no error is coming. Seems like ends up with some unknow issue. I am attaching my code before and after upgrading the restsharp library.

Code in Rest sharp version 106.12.00

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RestSharp;

namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new RestClient("https://shoonyatrade.finvasia.com/NorenWClientTP/QuickAuth");
            client.Timeout = -1;
            var request = new RestRequest(Method.POST);
            request.AddHeader("Content-Type", "text/plain");
            var body = @"jData={""apkversion"":""1.0.0"",""uid"":""123456""}";
            request.AddParameter("text/plain", body, ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);
        }
    }
}

Code after upgrading to 108.0.1

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RestSharp;

namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {

            var client = new RestClient("https://shoonyatrade.finvasia.com/NorenWClientTP/QuickAuth");
            client.Options.MaxTimeout = -1;
            var request = new RestRequest("",Method.Post);
            request.AddHeader("Content-Type", "text/plain");
            var body = @"jData={""apkversion"":""1.0.0"",""uid"":""123456""}";
            request.AddParameter("text/plain", body, ParameterType.RequestBody);
            RestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);
        }
    }
}

Expected Response

{"stat":"Not_Ok","emsg":"Invalid Input :  uid or pwd or factor2 or imei or apkversion or vc or appkey or source is Missing."}

**Comment by alexeyzimarev** [comment]
I guess you already know the solution, looking at the SO question.
