### ISSUE TITLE
Parameters Order  in a post query is not respected

### ISSUE THREAD

**Issue by Soft-jp** [restsharp/RestSharp#1937]
**Describe the bug**
After update restsharp  106.15 to 108.0.2 , the order of the parameters is not respected.

**To Reproduce**
```
var request = new RestRequest("/de/cfes/{cfeId}/", Method.Post);
request.AddUrlSegment("cfeId", cfeId);
request.AddParameter("title", dcore.title);
request.AddParameter("creator", dcore.creator);
request.AddFile("dataObject", file, "application/pdf");
```

**Expected behavior**
I expect to have the dataObject parameter at the end of my post which was the case with version 106.15 but not anymore. It is at the beginning.

**Stack trace**

> POST https://xxxx/de/cfes/AVplNP7oFSCAANm5/ HTTP/1.1
> Accept: text/xml
> Authorization: Basic ZGVwb3QudGVzdEBibG9vbS10ZWNobm9sb2d5LmZyOm5RTko5NF4zdE1ZZSh+
> User-Agent: RestSharp/106.15.0.0
> Content-Type: multipart/mixed; boundary=---------157ADA56-F062-4F35-914F-B35957586B43
> Host: test.arkhineo.fr
> Content-Length: 48002
> Accept-Encoding: gzip, deflate
> 
> -----------157ADA56-F062-4F35-914F-B35957586B43
> 
> Content-Disposition: form-data; name="title"
> 
> TestTitle
> -----------157ADA56-F062-4F35-914F-B35957586B43
> Content-Disposition: form-data; name="creator"
> 
> TestCreator
> -----------157ADA56-F062-4F35-914F-B35957586B43
> Content-Disposition: form-data; name="dataObject"; filename="test.pdf"
> Content-Type: application/pdf
> 
> %PDF-1.4
> % 쏢
> ....
> trailer
> << /Size 33 /Root 1 0 R /Info 2 0 R
> /ID [<11FBFF766390B6E2798152989FA02F4E><11FBFF766390B6E2798152989FA02F4E>]
> >>
> startxref
> 44237
> %%EOF
> 
> -----------157ADA56-F062-4F35-914F-B35957586B43--

-----------------------------------------------------------------------------------

> POST https://xxx/de/cfes/AVplNP7oFSCAANm5/ HTTP/1.1
> Accept: text/xml
> Authorization: Basic ZGVwb3QudGVzdEBibG9vbS10ZWNobm9sb2d5LmZyOm5RTko5NF4zdE1ZZSh+
> User-Agent: RestSharp/108.0.2.0
> Content-Type: multipart/mixed; boundary="8df57e66-ec8f-47d0-aba3-46b5379bbb11"
> Host: test.arkhineo.fr
> Content-Length: 48330
> Accept-Encoding: gzip
> Connection: Keep-Alive
> 
> --8df57e66-ec8f-47d0-aba3-46b5379bbb11
> Content-Type: application/pdf
> Content-Disposition: form-data; name="dataObject"; filename="BLT_AMROUNEMyriam_20190531.pdf"
> 
> %PDF-1.4
> % 쏢
> %%Invocation: gs ? -dSAFER -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dPDFSETTINGS=/screen -dPDFA=1 -sPDFACompatibilityPolicy=? -sColorConversionStrategy=UseDeviceIndependentColor -dPDFACompatibilityPolicy=1 -sOutputFile=? -f ?
> 5 0 obj
> <</Length 6 0 R/Filter /FlateDecode>>
> stream
> ................
> 44237
> %%EOF
> 
> --8df57e66-ec8f-47d0-aba3-46b5379bbb11
> Content-Type: text/plain; charset=utf-8
> Content-Disposition: form-data; name="title"
> 
> TestTitle
> --8df57e66-ec8f-47d0-aba3-46b5379bbb11
> Content-Type: text/plain; charset=utf-8
> Content-Disposition: form-data; name="creator"
> 
> TestCreator

**Desktop (please complete the following information):**
 - .NET 6

**Comment by muhmuhhum** [comment]
I am running in to the same issue with multipart formdata i hava a external api i need to call and it needs the block with paramters before the block with the file

**Comment by alexeyzimarev** [comment]
Having parameters before the file can actually be fixed.

**Comment by muhmuhhum** [comment]
@alexeyzimarev How can i do this ?

**Comment by alexeyzimarev** [comment]
You can open a PR. It should be an easy fix just to reorder the content population.
