### ISSUE TITLE
AddQueryParameter Empty Value appends "=" to the parameter

### ISSUE THREAD

**Issue by RefaelAzari** [restsharp/RestSharp#1938]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
Api URL - **https://example.com/aps/2/collections/accounts?eq(id,1002305)**
when trying to POST\GET requests with empty value
the url changed to **https://example.com/aps/2/collections/accounts?eq(id,1002305)=**
or **https://example.com/aps/2/collections/accounts?eq(id,1002305)=False**
depends if setting the parameter value to "" or without value like

and the request failed
how can i manage POST\GET to the exact url https://example.com/aps/2/collections/accounts?eq(id,1002305)

**To Reproduce**
POST\GET Request to https://example.com/aps/2/collections/accounts?eq(id,1002305)
with 
Request.AddParameter("eq(id,1002305)", false);
or
Request.AddQueryParameter("eq(id,1002305)", false);

**Expected behavior**
manage POST\GET to the exact url e.g https://example.com/aps/2/collections/accounts?eq(id,1002305)

**Stack trace**

**Desktop (please complete the following information):**
 - OS: Windows10
 - .NET 6
 - Version 108.0.1

**Comment by alexeyzimarev** [comment]
Second thought - `null` could essentially not add `=`, and empty string would do that.

**Comment by RefaelAzari** [comment]
sounds great this way its very flexible

**Comment by alexeyzimarev** [comment]
I have a feeling that I've done it, but I need to double check

**Comment by RefaelAzari** [comment]
> 

i have check again (RestSharp 108.0.3) and it still happens
null adding "=False"
empty string adding "="
![devenv_iHaLr2C3by](https://user-images.githubusercontent.com/104496985/211192416-19cfc9b5-2c15-48f4-94e3-7933efa06e33.png)
![devenv_mMKKo2c3jA](https://user-images.githubusercontent.com/104496985/211192417-71f9fe5a-b3da-47ed-9f49-4056bd710dba.png)

**Comment by alexeyzimarev** [comment]
Yeah because there are no changes happening in 108 atm, all the new stuff is going to 109.

**Comment by RefaelAzari** [comment]
> Yeah because there are no changes happening in 108 atm, all the new stuff is going to 109.

Ok , i checked with Version 109.0.0-preview.1 and it doesnt work too

**Comment by alexeyzimarev** [comment]
Well, it is definitely there:

```csharp
        string GetString(string name, string? value, Func<string, string>? encode) {
            var val = encode != null && value != null ? encode(value) : value;
            return val == null ? name : $"{name}={val}";
        }
```

**Comment by alexeyzimarev** [comment]
You use string empty value, but empty string is a legit (empty) value. You need to use `null` as a value instead.

**Comment by RefaelAzari** [comment]
i used both empty and null and in both cases it doesnt word

**Comment by RefaelAzari** [comment]
i tried again with version 109.0.1
and i getting exception when using null
Value cannot be null

![image](https://user-images.githubusercontent.com/104496985/224560925-99d1a559-6b35-44ed-860c-c626402ea98f.png)

![image](https://user-images.githubusercontent.com/104496985/224560958-f14da400-7517-466d-9771-ec7f860d6255.png)

**Comment by alexeyzimarev** [comment]
It's a different issue that the OAuth1 authenticator doesn't like parameters with null values.

**Comment by RefaelAzari** [comment]
but you said to use null value and the whole fix is for that
"
You use string empty value, but empty string is a legit (empty) value. You need to use **null** as a value instead.
"

**Comment by RefaelAzari** [comment]
so what can i do instead?

**Comment by alexeyzimarev** [comment]
> but you said to use null value and the whole fix is for that

Because your issue was "AddQueryParameter Empty Value appends "=" to the parameter" and it was fixed. You never mentioned anything related to OAuth1 authenticators.

> so what can i do instead?

Open another issue and provide the necessary diagnostic details.

**Comment by RefaelAzari** [comment]
i did mentiond in the title but you changed it look above

![image](https://user-images.githubusercontent.com/104496985/224562156-a4a17bf4-3b32-42ea-a467-855738508ed7.png)
