### ISSUE TITLE
ResponseStatus is set to Error for 400 status code while in v106 it was set to Completed

### ISSUE THREAD

**Issue by bojan96** [restsharp/RestSharp#1940]
**Describe the bug**
When getting 400 bad request response from API `ResponseStatus` property of `RestResponse` is being set to `Error`.
This is unexpected since documentation for `ResponseStatus` property says following:

_Status of the request. Will return Error for transport errors.
 HTTP errors will still return ResponseStatus.Completed, check StatusCode instead_

**To Reproduce**
Make API request which will result in 400 BadRequest. `ResponseStatus` property will be set to Error

**Expected behavior**
`ResponseStatus` should be set to `ResponseStatus.Completed`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET 6
 - Version 107.x.x, 108.x.x

**Comment by bojan96** [comment]
Ok I see that web [documentation ](https://restsharp.dev/error-handling.html) says that ResponseStatus.Error is returned in case of any server error (except 404). So xml docs are outdated.
How does one differentiate between transport errors and http errors now?

**Comment by alexeyzimarev** [comment]
Maybe `IsSuccessful` is better?

**Comment by bojan96** [comment]
`IsSuccessful` is false in case of 400 bad request

**Comment by alexeyzimarev** [comment]
Here's how the response status is calculated by default:

```csharp
    public CalculateResponseStatus CalculateResponseStatus { get; set; } = httpResponse
        => httpResponse.IsSuccessStatusCode || httpResponse.StatusCode == HttpStatusCode.NotFound
            ? ResponseStatus.Completed
            : ResponseStatus.Error;
```

As you can see, it's a default implementation, and you can override it.

**Comment by bojan96** [comment]
Didn't know about this feature, I will close an issue.
