### ISSUE TITLE
405 System.Net.HttpStatusCode.MethodNotAllowed

### ISSUE THREAD

**Issue by TherdDB** [restsharp/RestSharp#1946]
var request = new RestRequest(apiUrl + baseRequest.Route, baseRequest.Method);
        request.AddHeader("Content-Type", baseRequest.ContentType);
        //request.Method = Method.Get;
        if (baseRequest.Parameter != null)
            //request.AddBody(baseRequest.Parameter);
            request.AddParameter("", JsonConvert.SerializeObject(baseRequest.Parameter), ParameterType.RequestBody);
        _client.BuildUri(request);
        var response = await _client.ExecuteAsync<T>(request, baseRequest.Method);

WebApi..  ( Only One  URL )

MAUI.. 
Windows  :  
                  GET => OK
                  Post => OK

Android   :
                  GET => No     (405)  System.Net.HttpStatusCode.MethodNotAllowed !!!!!   ( Help me!!! )
                  Post => OK

PostMan :  
Get => OK  
Post => OK

**Comment by alexeyzimarev** [comment]
The exception comes from .NET Framework, as it doesn't allow GET requests with request body on some platforms. There's nothing we can do about it.
