### ISSUE TITLE
Binary API Breaking Change in 108.0.2

### ISSUE THREAD

**Issue by GKBelmonte** [restsharp/RestSharp#1953]
**Describe the bug**
The following change:
https://github.com/restsharp/RestSharp/commit/c969747ecde091905ea9f80d3669d0c30a6c61d5?diff=split#diff-fd5240c0eeb1a04bc0c9ea9b5210c8a8ce6703011459c72d49ee4b0c08e61224R292

Introduces a default parameter to a number of extensions (`FileParameterOptions? options = null`)
Binaries previously compiled against the old version (lacking the default arg) will fail to find the method at runtime.

(see this [answer](https://stackoverflow.com/a/23517490) on SO)

What will result, will be a runtime binding exception:
```
System.MissingMethodException: Method not found: 'RestSharp.RestRequest RestSharp.RestRequestExtensions.AddFile(RestSharp.RestRequest, System.String, Byte[], System.String, System.String)'.
```

**To Reproduce**

1. Compile an assembly A using the method without the new default option (108.0.1) 
    a.  Expose that code path
3. Create a new project that depends on both that assembly and uses 108.0.2
4. Call the code path exposed in 1.a

**Expected behavior**
The method works succesfully

**Stack trace**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
It is important that the assembly produced in step 1 is referenced _as binary_ not as source (project), since its a binary breaking change, not a source breaking change.

The code of the assembly A would still compile, if REcompiled against version 108.0.2, _it is the runtime binding that would fail_.

**Comment by alexeyzimarev** [comment]
You're right. I would gladly accept a PR where the method is reverted, and the new overloaded is added with options. Then, I can release it as a minor under 108.

**Comment by GKBelmonte** [comment]
I can do that after work :)

**Comment by alexeyzimarev** [comment]
It wasn't as easy as I expected because of the optional parameters. So, it will be one more breaking change, but the impact would be only on people who use the options, and I don't think this feature is widely used.

**Comment by GKBelmonte** [comment]
ah thanks!
I was looking at it yesterday, but turns out I didnt have the right VS installed, so I started download overnight.

**Comment by alexeyzimarev** [comment]
No worries, I hope I can release it soon, so you can try.

**Comment by alexeyzimarev** [comment]
Btw you can try the latest preview to make sure it works as expected.

**Comment by GKBelmonte** [comment]
Hey Alexey!
Tried it locally, and it seems to work !

I may have to try with a full open API gen with dotnet core, but at the very least locally it, with a binary ref and a proj ref, it works!

**Comment by alexeyzimarev** [comment]
Noice, I will tag that version and release it.

**Comment by SamInfosoft** [comment]
I am getting this using Xero https://github.com/XeroAPI/Xero-NetStandard/issues/472
I suspect this fix didn't work. (using restsharp 110.2.0
Rolling back to 108.0.1 fixes it.

**Comment by Jacko1394** [comment]
On 110.2.0 I also got this error while using Xero.NetStandard.OAuth2Client (1.6.0)

**Comment by alexeyzimarev** [comment]
@Jacko1394 v110 is a major version so it is not expected to be binary compatible.
