### ISSUE TITLE
CsvConfiguration is ignored when using CsvHelper for deserialization

### ISSUE THREAD

**Issue by electrokit** [restsharp/RestSharp#1959]
When using the CsvHelper serializer, the configuration is used when serializing, but not when deserializing.

Changing the second argument to the constructor to `_configuration` fixes the problem.
https://github.com/restsharp/RestSharp/blob/df07026de44d4fe8fc777c6b9c5aaa07ae6ccb35/src/RestSharp.Serializers.CsvHelper/CsvHelperSerializer.cs#L36

**Comment by alexeyzimarev** [comment]
Please open a PR. Thanks in advance.
