### ISSUE TITLE
Identify response time out

### ISSUE THREAD

**Issue by sldev** [restsharp/RestSharp#196]
RestClient.Timeout = 60*1000?

Means if response receive time more than 60 seconds, the ResponseStatus will be set to ResponseStatus.TimedOut

Please correct me if I miss understanding.

**Comment by aloveric** [comment]
> Yes. Timeout is in milliseconds.
> 
> On Wednesday, December 21, 2011 at 2:24, sldev wrote:
> 
> > RestClient.Timeout = 60*1000?
> > Means if response receive time more than 60 seconds, the ResponseStatus will be set to ResponseStatus.TimedOut
> > Please correct me if I miss understanding.
> > 
> > Reply to this email directly or view it on GitHub:
> > #196

Thanks
