### ISSUE TITLE
restClient.DownloadData is error

### ISSUE THREAD

**Issue by hk8846** [restsharp/RestSharp#1968]
![image](https://user-images.githubusercontent.com/12498221/200729969-0a90e594-a471-4924-9f13-0cf5bc77915a.png)

Content-Disposition:attachment; filename="b9174fd1-bfe6-447d-b577-77b3701fd5de.jpg"

buglist:
1、use restClient.DownloadData("file url"), response result is show error.
2、I want to get "Content-Disposition"-> filename,but restClient not support.

**Desktop (please complete the following information):**
 - OS: win10
 - .NET version : .net 6.0
 - Version: 108.0.2

**Additional context**

**Comment by alexeyzimarev** [comment]
> response result is show error

What error?

**Comment by hk8846** [comment]
> 

{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: nginx/1.18.0
  Date: Fri, 11 Nov 2022 02:11:45 GMT
  Connection: keep-alive
  Content-Type: application/json
  Content-Length: 43
}, Trailing Headers:
{
}}

> > response result is show error
> 
> What error?

{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: nginx/1.18.0
  Date: Fri, 11 Nov 2022 02:11:45 GMT
  Connection: keep-alive
  Content-Type: application/json
  Content-Length: 43
}, Trailing Headers:
{
}}

**Comment by hk8846** [comment]
ResetSharp code  is show error:
            RestSharp.RestClient client = new RestSharp.RestClient();
            string fileUrl = "file url"; //this fileUrl return file stream.
            RestRequest request = new RestRequest(fileUrl,Method.Get);

            var result = client.DownloadData(request);
can't download file,and show error.

I change other code,can download succeeded,As follows:
            HttpClient httpClient = new HttpClient();
            HttpRequestMessage req = new HttpRequestMessage
            (
                HttpMethod.Get, "fileUrl"
            );
            req.Content = new StringContent("");
            HttpResponseMessage response = httpClient.Send(req);

            if (response.IsSuccessStatusCode)
            {
                var byteArray = response.Content.ReadAsByteArrayAsync().Result;
                string? fileName = response.Content.Headers.ContentDisposition?.FileName;

                return File(byteArray, "application/octet-stream", fileName);
            }
