### ISSUE TITLE
Updated string after calling AddUrlSegment???

### ISSUE THREAD

**Issue by hcanak** [restsharp/RestSharp#1977]
Hello,

Below url contains a placeholder, i succesfully replace the string by calling AddUrlSegment method.  All i need is the to get updated url that is : "/futures/usdt/positions" . I need this in order to calculate hash and signature. 
I hoped that there should be property of RestRequest that gives updated url but not . How can i retreive the replaced string? Thank you.

            const string EndpointUrl = @"/futures/{settle}/positions";
            var request = new RestRequest(EndpointUrl, Method.Get);
            request.AddUrlSegment("settle", "usdt");

**Comment by hcanak** [comment]
Hello @alexeyzimarev, RestRequest class does not have **BuildUrl**?

![image](https://user-images.githubusercontent.com/79494507/205366325-c3a3f772-7397-47d8-ae60-1436e6ca104e.png)

**Comment by alexeyzimarev** [comment]
No, it's on the client level.

**Comment by hcanak** [comment]
@alexeyzimarev 
ı need it in the request level.

**Comment by alexeyzimarev** [comment]
How a request URL can be possibly built when the request has no idea about the client base URL??? This function was _never_ on the request level, I am not sure exactly where this idea comes from.
