### ISSUE TITLE
RemoteCertificateValidationCallback not working

### ISSUE THREAD

**Issue by nzdvis** [restsharp/RestSharp#1978]
Ignoring SSL certificate validation errors by setting the RemoteCertificateValidationCallback callback, does not seem to work:

`var options = new RestClientOptions() {
RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
};`
`client = new RestClient(options);`

This worked in 106 on application

`ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;`

### StackTrace:

System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
23 Nov. 2022 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
23 Nov. 2022---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain

- Visual Studio 2022 on Windows 10 Pro 64bit
- .NET 6
- Version 108.0.3

**Comment by alexeyzimarev** [comment]
RestSharp doesn't do anything else than pass the function to `HttpClient`. If that doesn't work, we can't do much.

https://github.com/restsharp/RestSharp/blob/cbcc74b8645966cfefbbebd57d54f558ff78c9aa/src/RestSharp/RestClient.cs#L146-L148

**Comment by nzdvis** [comment]
I see, then I'll test with the `HttpClient` and contact them afterwards.

Thanks for the clarification.
