### ISSUE TITLE
HttpClient socket problem

### ISSUE THREAD

**Issue by 1995liuwei** [restsharp/RestSharp#2004]
It seems like HttpClient added to restsharp,and HttpClient has a problem is that:
     HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in  #SocketException errors.

So I can't new RestClient as before,then How can I avoid SocketException when use restsharp in .net core.

using this code " service.AddSingleton<IRestClient,RestClient>() " to avoid that exception?

**Comment by tacosontitan** [comment]
Is something about your particular use case preventing you from injecting the class instead of the interface?

```csharp
services.AddSingleton<RestClient>();
```

**Comment by 1995liuwei** [comment]
No

**Comment by tacosontitan** [comment]
Does injecting the class instead of the interface solve your problem? If not, can you elaborate on why?

**Comment by alexeyzimarev** [comment]
Closing due to lack of feedback.

Using a singleton is a valid option. Another way is to use the client factory and provide a resolution function when registering the client.

```csharp
builder.Services.AddHttpClient();
builder.Services.AddTransient(sp => new RestClient(sp.GetRequiredService<HttpClient>()));
```

The `RestClient` constructor that accepts an instance of `HttpClient`, however, won't be able to configure the message handler if you specify the necessary options.

The latest version can cache `HttpClient` instances, check the docs for more details.

**Comment by 1995liuwei** [comment]
> problem

> Does injecting the class instead of the interface solve your problem? If not, can you elaborate on why?
I call the webapi quite frequently,singleton has poor performance,anyway thank you for your help,I appreciate it.

**Comment by 1995liuwei** [comment]
> Closing due to lack of feedback.
> 
> Using a singleton is a valid option. Another way is to use the client factory and provide a resolution function when registering the client.
> 
> ```cs
> builder.Services.AddHttpClient();
> builder.Services.AddTransient(sp => new RestClient(sp.GetRequiredService<HttpClient>()));
> ```
> 
> The `RestClient` constructor that accepts an instance of `HttpClient`, however, won't be able to configure the message handler if you specify the necessary options.
> 
> The latest version can cache `HttpClient` instances, check the docs for more details.

Seems good,I will try it.Thank you.I expect the latest version.
