### ISSUE TITLE
Double quotes option for multipart/form-data boundary

### ISSUE THREAD

**Issue by Coolava** [restsharp/RestSharp#2011]
I tried migration 104 to 108.

But since version 107, System.net.http is used for Http Request. It makes difference.

When upload file using multipart/form-data, `AddFiles`  called. 
And it makes MultipartFormDataContent and pass boundary to parameter.

https://github.com/restsharp/RestSharp/blob/f7d3984244c4808ae7c068e028753c2857f325b9/src/RestSharp/Request/RequestContent.cs#L48-L51

Also this is :

https://github.com/restsharp/RestSharp/blob/f7d3984244c4808ae7c068e028753c2857f325b9/src/RestSharp/Request/RequestContent.cs#L211

When MultipartFormDataContent created the boundary parameter will always wrapped "(double quotes).

boundary will like this in version 107 : 
> boundary="gc0pJq0M8jU534c0p" 

But in version 104 :
> boundary=gc0pJq0M8jU534c0p 

There is no double quotes. 
According to [RFC 2046](https://www.rfc-editor.org/rfc/rfc2046#section-5.1.1) double quotes is selective option.

How about add new option in RestSharp for double quotes?

**Comment by alexeyzimarev** [comment]
The option already exists, but it wasn't applied in that case.

**Comment by alexeyzimarev** [comment]
I am wrong, the option is to use quotes around parameter names, sorry.

**Comment by alexeyzimarev** [comment]
I was able to fix it when the content type header is added manually to the request using `AddHeader`. But when the constructor of `MultipartFormDataContent` is called, RestSharp provides it with the boundary without quotes, and here what happens in .NET code:

```csharp
            string quotedBoundary = boundary;
            if (!quotedBoundary.StartsWith('\"'))
            {
                quotedBoundary = "\"" + quotedBoundary + "\"";
            }
```

I made a change to re-create the content type header to work around this.
