### ISSUE TITLE
When accessing the webpage, it waits for a long time, but the data can be requested

### ISSUE THREAD

**Issue by zgcwkj** [restsharp/RestSharp#2012]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
When accessing the webpage, it waits for a long time, but the data can be requested.

**To Reproduce**
```
var url = $"https://www.aliyun.com/";
var options = new RestClientOptions(url)
{
    Proxy = WebRequest.DefaultWebProxy,
    RemoteCertificateValidationCallback = delegate { return true; },
};
var client = new RestClient(options);
var request = new RestRequest();
var response = await client.GetAsync(request);
```

**Expected behavior**
don't wait that long

**Desktop (please complete the following information):**
 - OS: Windows
 - .NET version NET 6
 - Version 108.0.3

**Additional context**
Seems to be a certificate issue, but I'm not sure.
HttpClient direct request also has this problem.

**Comment by alexeyzimarev** [comment]
RestSharp will not be any faster than HttpClient as RestSharp uses HttpClient.

I think it's a redirect issue of the server, I don't think anything can be done.
