### ISSUE TITLE
UrlSegment parameter does not replace the value inside a QueryParameter anymore

### ISSUE THREAD

**Issue by francisharvey** [restsharp/RestSharp#2013]
I'm doing a migration from older version 105.2.3 of RestSharp to latest 108.0.3

This is the resource url:
"/entity/Default/20.200.001/StockItem?$select={fields}&$filter=InventoryID eq 'ASSEM1'"

After creating the request, I add the UrlSegmentParameter:
![image](https://user-images.githubusercontent.com/11393304/222172551-945bf86f-6130-448d-8f1f-08decc771b0e.png)

But it seems the UrlSegment parameter does not replace the value inside a QueryParameter anymore, but it was working before.

So this is the resulting request:
"https://servername/entity/Default/20.200.001/StockItem?$select=%7Bfields%7D&$filter=InventoryID%20eq%20'ASSEM1'" 

Is it the expected behavior or a bug?

**Comment by alexeyzimarev** [comment]
It is the wrong implicit behaviour of v105. Query parameters should never be part to the resource URL. RestSharp adds them when making the call. The resource URL should be `/entity/Default/20.200.001/StockItem` in your case.

**Comment by francisharvey** [comment]
Yeah you're right, I'm sorry I should have said: the is the url that I use when creating the request...
The two first query parameter are added automatically upon creation and resource field do not contains any of them, 
only '/entity/Default/20.200.001/StockItem'.

So you mean, the $select and $filter parameter part of the url should not be passed to the request constructor?
Preventing the 'dynamic' url segment functionality to take place?

The reason why it is done like this is to have a static template of the request in text and I set the 'fields' parameter dynamically calculated at runtime...

This request is a simple one with only have one parameter, but i have a bunch of other queries that use the exact same code using and this feature too:

/restapi/1.0/object/mrp.bom?fields=[{fields}]&domain=[('product_id', '=', @ID),('product_tmpl_id', '=', @ProductTemplateID)]
/restapi/1.0/object/mrp.bom.line?fields=[{fields}]&domain=[('bom_id', '=', @BomID)]
/restapi/1.0/object/mrp.bom/@BomID?vals={values}
/restapi/1.0/object/mrp.bom.line/@LineID?vals={values}

My code replaces the @valuename by actual named value in the the url before creating the request, so those are not part of my current issue.

**Comment by alexeyzimarev** [comment]
The URL segment parameter should be used for URL segments, not query parameters.
https://restsharp.dev/usage.html#url-segment
And the query string parameter adds both the name and the value to the query.
https://restsharp.dev/usage.html#query-string
All methods to add parameters have `encode` as the last argument, you might need to set to `false` so the special characters don't get encoded.

I am not sure if I give the right tips as you haven't posted your code.

**Comment by francisharvey** [comment]
Ok I understand the wrong implicit behavior you talk about...

So in this case I guess I would need to update the value of the parameter to replace the 'placeholder' with the calculated values. I should be able to do this using the method AddOrUpdateParameter(Parameter parameter) or any other overloads of it right?

Something like this:
`Dim p As Parameter = request.Parameters.TryFind("param1")`
`If p.Value = "{fields}" Then`
`     request.AddOrUpdateParameter(p.Name, "InventoryId,Description,ItemClass,BasseUOM")`
`End If`

But after the migration, i'm getting compilation issue related to the Parameter Record type, all fields of parameter are now kinda unaccessible (name, type, value), causing error at compilation...

`error BC30643: Property 'RestSharp.Parameter.Value' is of an unsupported type.`
`error BC30643: Property 'RestSharp.Parameter.Name' is of an unsupported type.`

So I can't verify the content of the param value for the placeholder...

Am I the only one with compilation errors related to this change?
Or is there a special syntax for records?

**Comment by alexeyzimarev** [comment]
`Parameter` and all its descendants are now record types. You need to use the latest .NET SDK for it to work properly. It won't break anything in your setup. Record types are supported for a few years now.

**Comment by alexeyzimarev** [comment]
I am actually unsure why you can't use `AddQueryParameter` and forget about placeholders. Maybe you can provide a bit more context.

**Comment by francisharvey** [comment]
I will try to get rid of the compiler errors above, this is the only thing preventing me to use the parameter name, type and value...

**Comment by alexeyzimarev** [comment]
Closing due to lack of feedback.
