### ISSUE TITLE
Timeout is not respected after client is created

### ISSUE THREAD

**Issue by waboziad** [restsharp/RestSharp#2017]
The MaxTimeout Option is not reflected n the httpCleint when the client is already created 
  
      private RestClient _restClient;
     int  timeout = 300; 
       _restClient = new RestClient(new RestClientOptions{BaseUrl = uri, MaxTimeout = timeout });
this works fine and when I check the _restClient.HttpClient.Timeout it reflect the value passed 

but if I tried to change the value after the Client is created 

_restClient.Options.MaxTimeout = 500;
_restClient.HttpClient.Timeout 
 it does not accept the new value and the will be still the old value

**Comment by alexeyzimarev** [comment]
You cannot change any option after the client is created. All the properties for `Options` are made get-only.

If you want to use a different timeout for an individual request, you need to use the `RestRequest.Timeout` property. However, if the `Options.Timeout` is shorter than the request timeout, the `Options.Timeout` will time out the request earlier.
