### ISSUE TITLE
Doing multipart/mixed stopped working

### ISSUE THREAD

**Issue by pysiak** [restsharp/RestSharp#2019]
I am doing OData calls where I do a multipart/mixed. It used to work, but now it doesn't.
Sample code:
```
var request = new RestRequest(url, Method.Post);
var contentType = "multipart/mixed; boundary=boundary123";
request.AddParameter(contentType, postData, ParameterType.RequestBody);
var response = await _client.ExecuteAsync(request);
```

ExecuteAsync throws *The format of value 'multipart/mixed; boundary=boundary123' is invalid*

But this contentType is MIME spec correct!
I think this might be thrown by httpclient methods dealing with adding headers. 
Is this something restsharp can fix/workaround?

**Comment by alexeyzimarev** [comment]
Setting the content type manually is an anti-pattern when using RestSharp.

Follow the docs here https://restsharp.dev/v107/#body-parameters and use `AddObject` without a content type, RestSharp will set it for you. I am not sure what `postData` is, `AddObject` take a class and adds all (or some) of its properties as form data parameters. Form boundary will be added automatically.

**Comment by alexeyzimarev** [comment]
One addition is that `AddObject` will add properties as `GetOrPost` parameters. If the request has no attachments, it will use URL-encoded form content type. It works by default in many cases as API servers can work with any form content. If you absolutely must make a POST request as multipart form, set the `AlwaysMultipartFormData` request property to `true`. If you need to override the default generate form boundary string, set the `FormBoundary` request property to `boundary123`.

**Comment by pysiak** [comment]
Thanks for taking the time to look at my issue.
Now, I know the docs, but I can't rely on that, because I'm not putting an XML or JSON, for which Content-Type sensing would work. In this particular instance I'm putting an OData batch request where the content is multipart/mixed (and has to be that string exactly) and my body looks like this. It is not a typical one-off JSON or XML, it's a bit more convoluted :-(


```
--boundary
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-Id:1

GET CurriculumItemStatuses?$filter=cisCriteria/targetUserID%20eq%20'<redacted>'%20and%20cisCriteria/curriculumID%20eq%20'<redacted>'%20and%20cisCriteria/rootCurriculumID%20eq%20'<redacted>' HTTP/1.1
Content-Type: application/json


--boundary
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-Id:2

GET CurriculumItemStatuses?$filter=cisCriteria/targetUserID%20eq%20'<redacted>'%20and%20cisCriteria/curriculumID%20eq%20'<redacted>'%20and%20cisCriteria/rootCurriculumID%20eq%20'<redacted>' HTTP/1.1
Content-Type: application/json
... and so on...
```

It used to work, but it falls over now. I was able to workaround this regression by doing
```
            var request = new RestRequest(url, Method.Post);
            var contentType = $"multipart/mixed; boundary={boundary}";
            request.AddStringBody(postData, DataFormat.None);
            request.AddHeader("Content-Type", contentType);

            var response = await ExecuteRequestAsync(request);
```

This way I, as per the restsharp docs, am using the AddStringBody to prevent content-type sensing, and set the corresponding Content-Type.

I still thing it's a bug, as in, it's a regression of working code.

Note: when I sent the issue I didn't have the workaround, yet.

**Comment by alexeyzimarev** [comment]
I am not sure why are you referring to this as a regression. In what version did it work? RestSharp uses `Content`-based objects since version 107 and by default the form boundary is randomly generated.

There's an option to override the default boundary by setting `RestRequest.FormBoundary` property.

**Comment by alexeyzimarev** [comment]
Btw if you care to provide the stack trace of the original code, it would really help. It's hard to say where it fails. I think it is here (`AddBody`):

```csharp
        return
            obj is string str                  ? request.AddStringBody(str, contentType) :
            obj is byte[] bytes                ? request.AddParameter(new BodyParameter("", bytes, contentType, DataFormat.Binary)) :
            contentType.Value.Contains("xml")  ? request.AddXmlBody(obj, contentType) :
            contentType.Value.Contains("json") ? request.AddJsonBody(obj, contentType) :
                                                 throw new ArgumentException("Non-string body found with unsupported content type", nameof(obj));
```

As you can see, RestSharp also uses `AddStringBody` and passes over the specified content type.

When the body is formed and the request format is set to `None` (your case), the content type is used to create an instance of `StringContent`:

```csharp
        return body.DataFormat switch {
            DataFormat.None   => new StringContent(body.Value!.ToString()!, _client.Options.Encoding, body.ContentType.Value),
            DataFormat.Binary => GetBinary(),
            _                 => GetSerialized()
        };
```

I think that's where it crashes.
