### ISSUE TITLE
OAuth1 AddParameter/AddQueryParameter Empty Value Gets "Value Cannot Be null" Exception

### ISSUE THREAD

**Issue by RefaelAzari** [restsharp/RestSharp#2022]
**DO NOT USE ISSUES FOR QUESTIONS**

Describe the bug
Api URL - https://example.com/aps/2/collections/accounts?eq(id,1002305)
Authentication - OAuth1

when trying to POST\GET requests with empty value when using **OAuth1** Authentication 
getting "Value Cannot Be null"  Exception

To Reproduce
POST\GET Request to https://example.com/aps/2/collections/accounts?eq(id,1002305)
with
Request.AddParameter("eq(id,1002305)",null, false);
or
Request.AddQueryParameter("eq(id,1002305)",null, false);

Expected behavior
manage to POST\GET with AddParameter\AddQueryParameter with null value using **OAuth1** Authentication

Desktop (please complete the following information):

OS: Windows10
.NET 7
Version 109.0.1

![image](https://user-images.githubusercontent.com/104496985/224564811-a4722cee-3b60-4fc0-9f0e-e3ff0cf1ce94.png)

![image](https://user-images.githubusercontent.com/104496985/224564822-5aff1fc2-b495-4b9c-8050-1c63a3882092.png)

**Comment by VictorKochetkov** [comment]
We have updated from 106.x to 108.x version and faced this issue too
