### ISSUE TITLE
Unable to reassign the Authenticator property in v109

### ISSUE THREAD

**Issue by Balkoth** [restsharp/RestSharp#2024]
**Describe the bug**
The changes introduced by making the `Authenticator` on `RestClient` immutable makes it impossible to use the same `RestClient` for authentication and after successfully authentication setting the `Authenticator` for further method calls which require the client to be authenticated.

**To Reproduce**

```cs
internal sealed class CustomRestClient : IDisposable
{
  private readonly RestClient _restClient;

  public CustomRestClient(string baseUrl) => _restClient = new RestClient(baseUrl);  

  public void Dispose() => _restClient.Dispose();

  public async Task<bool> Authenticate(string clientId, string clientSecret)
  {
    RestRequest request = new RestRequest("api/oauth2/token");
    request.AddParameter("grant_type", "client_credentials");
    request.AddParameter("client_id", clientId);
    request.AddParameter("client_secret", clientSecret);
  
    AppOAuthToken? response = await _restClient.PostAsync<AppOAuthToken>(request);
    _restClient.Authenticator = response != null && response.AccessToken != null ? new JwtAuthenticator(response.AccessToken) : default;
  
    return response != null && response.AccessToken != null;
  }
}
```

**Expected behavior**
The [docs](https://restsharp.dev/v107/#recommended-usage) state that a single instance of RestClient should be used to prevent starvation. 

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - .NET 7
 - Version 109.0.1

**Comment by Balkoth** [comment]
Working around this by initializing the `RestClient` with a `JwtAuthenticator` with an invalid token and using this to authenticate against the rest endpoint. Then after succesfully authenticating use `SetBearerToken` to set the token on the `JwtAuthenticator` for further method calls. 

```cs
internal sealed class CustomRestClient : IDisposable
{
  private const string EMPTY_TOKEN = "EMPTY_TOKEN";

  private readonly RestClient _restClient;

  public CustomRestClient(string baseUrl) => _restClient = new RestClient(new RestClientOptions(baseUrl) { Authenticator = new JwtAuthenticator(EMPTY_TOKEN) });

  public void Dispose() => _restClient.Dispose();

  public async Task<bool> Authenticate(string clientId, string clientSecret)
  {
    RestRequest request = new RestRequest("api/oauth2/token");
    request.AddParameter("grant_type", "client_credentials");
    request.AddParameter("client_id", clientId);
    request.AddParameter("client_secret", clientSecret);
  
    AppOAuthToken? response = await _restClient.PostAsync<AppOAuthToken>(request);
    ((JwtAuthenticator)_restClient.Options.Authenticator!).SetBearerToken(response != null && response.AccessToken != null ? response.AccessToken : EMPTY_TOKEN);
  
    return response != null && response.AccessToken != null;
  }
}
```

I don't know if any other than the rest endpoint i currently use, support this behaviour, so use with caution.

**Comment by alexeyzimarev** [comment]
The docs suggests using a single instance for making frequent calls. If you are doing a single call for authentication purposes you can use a separate, one-time-use client instance.

You can also hold the authenticator instance inside your wrapper:

```sharp
JwtAuthenticator _authenticator;

public CustomRestClient(string baseUrl) {
    _authenticator = new JwtAuthenticator(EMPTY_TOKEN)
    _restClient = new RestClient(new RestClientOptions(baseUrl) { 
        Authenticator = authenticator 
    });
}
```

and then call `SetBearerToken` when you have it. 

However, if you look at my old Twitter OAuth2 authenticator sample, it makes a call on-demand using a separate client instance inside the authenticator. It allows you to have full control over the flow.

I think the main deficiency of the authenticator approach with tokens is that it doesn't support token refresh. I believe we need a separate issue to discuss most common scenarios. Getting the token using grant type, client id and secret is very common. But the OIDC token and authentication token, for example, work differently.

It would be great to document specific flows in that new issue to figure out a workable solution, as we all know that the `IAuthenticator` abstraction is too weak.

**Comment by alexeyzimarev** [comment]
One comment about this:

> The [docs](https://restsharp.dev/v107/#recommended-usage) state that a single instance of RestClient should be used to prevent starvation.

That is true, but how can a single additional client instance only used for authentication (once) can cause starvation? The infamous issue with too many open sockets is caused by repeated creation of message handlers, which is not the case when we are talking about a single call to get a token.

**Comment by rassilon** [comment]
@alexeyzimarev , while migrating a C# REST library to 109 I ended up with this  [authenticator](https://gist.github.com/rassilon/63379d3c96467982d18159943945e94c) based on your old twitter example.

It is assisted with this additional logic in the core call to RestSharpClient Execute method:
`
            // NOTE: Completed was returned with earlier versions of RestSharp
            // (Pre 109.x)
            if ((response.ResponseStatus == ResponseStatus.Completed
                 || response.ResponseStatus == ResponseStatus.Error)
                && response.StatusCode == HttpStatusCode.Unauthorized
                && _authType == AuthenticationType.OAuth)
            {
                _restSharpClient.Options.Authenticator.Authenticate(_client, request);
                response = _restSharpClient.Execute(request);
            }
`

FYI...

**Comment by alexeyzimarev** [comment]
I'd really like to find out how authenticators can be made better. Checking the status code for 401 was one of my thoughts too. If you have a proposal for the authentication flow and related changes in code, please write here.

**Comment by rassilon** [comment]
Given how complex and fractured the authentication space is I think the only easy addition would be to add some assistance to the supplied Authenticator for 401 handling for expired/revoked tokens.
Maybe something like this: (pseudo-code)
```
       <inside Execute method>:
       If response status is 401:
           if request included an auth header value: (
                add some additional state to pass to .Authenticate call to hint that it might be a re-auth (either due to expiration, or token revocation, the cause really isn't important of course)
                if the returned token is different:
                    re-execute the same url with the new token from the authenticator
                else: 
                     nothing else to do, let the caller deal with the problem
```

Determining if the request has an auth header could be done a couple of different ways if more than just 'Authorization' needs to be supported.

**Comment by abc123xxx** [comment]
Is there anything new on the subject?
I also need to be able to change the authenticator after creating the RestClient.

**Comment by rassilon** [comment]
> Is there anything new on the subject? I also need to be able to change the authenticator after creating the RestClient.

Could you explain your use case a little here? I'm not sure why you'd need more than one authenticator after creating the RestClient.

**Comment by abc123xxx** [comment]
I have a specific use case in which I first have to use an OAuth1Authenticator via key and secret when logging in to a web API and then have to do another authentication with an OAuth1Authenticator. The access then takes place via another OAuth1Authenticator.

So I first need an Access Token and then a RequestToken etc.

Here is the call chain:

![image](https://github.com/restsharp/RestSharp/assets/66249676/67718b6f-742e-497e-ad28-7999b5f51352)

![image](https://github.com/restsharp/RestSharp/assets/66249676/9aead2b6-cbba-42e7-9c96-0f5b09df63a1)

![image](https://github.com/restsharp/RestSharp/assets/66249676/ca63c544-d819-4e7f-b3e0-16892e008cc8)

**Comment by alexeyzimarev** [comment]
It's always possible to use one client instance to do the first call, and then use the result of that call on the regular instance. The first instance gets disposed after making that single call. The Twitter authenticator example I made a while ago does exactly that.

The problem of _any_ property being assignable after the client instance is created, whilst it is being used is that it by definition makes the client not thread-safe. Someone might just replace the authenticator for their single call. Meanwhile the other thread does the call expecting the original authenticator, and it all becomes a mess.

**Comment by rassilon** [comment]
It seems to me that you could write an aggregated Authenticator by taking something similar to my updated authenticator sample [authenticator](https://gist.github.com/rassilon/63379d3c96467982d18159943945e94c) and adding an overridden Authenticate method and determine what authenticator actually to use based on the contents of the RestRequest, but that might be too much fragility or pain and suffering... However, that'd be up to you to decide...

**Comment by rassilon** [comment]
Additionally, the RestSharp request object has an Authenticator property that you can override the RestClient Options Authenticator property value for any request that needs to use a differing Authenticator from the default.

**Comment by abc123xxx** [comment]
ok, the request authenticator is the solution. Thank you for the tip.
