### ISSUE TITLE
DefaultParameters collection is not read-only

### ISSUE THREAD

**Issue by alexeyzimarev** [restsharp/RestSharp#2025]
The `DefaultParameters` property of `RestClient` has the `ParametersCollection` type. Although it's a read-only collection, it exposes public methods to add and remove parameters.

When using `RestClient.AddDefaultParameter` method, the collection is updated in a locked scope. However, it is possible to manipulate the collection directly by calling `client.DefaultParameters.AddParameter`, and it will be execute without locking the collection. It basically makes the client not thread-safe if default parameters are updated this way. It's not an intended use of the collection, but it has a public API, which allows people to do that.

My suggestion is to make the `DefaultParameters` property internal or private. The `AddDefaultParameter` might need to be added to the interface.

**Comment by nsulikowski** [comment]
I think this is used for logging. What about remembering the URL in a public property after the operation?

**Comment by alexeyzimarev** [comment]
@nsulikowski wrong issue? Did you mean to comment on #2026?
