### ISSUE TITLE
No overload for 'CustomJsonSerializer.SupportContentType(string)' matches delegate 'SupportsContentType'

### ISSUE THREAD

**Issue by jy13249** [restsharp/RestSharp#2032]
Hello,

I recently upgraded from v108.0.1 to 109.0.1 and am experiencing an issue with the CustomJsonSerializer class I had created.
![image](https://user-images.githubusercontent.com/62567532/225645973-21210fd5-8790-4275-9248-1733ae4a6ff2.png)
I'm not sure what happened or how to fix this. 
I've looked at the documentation and the only documentation that exists on CustomSerializers is slightly outdated and doesn't contain any SupportsContentType members. 

If I try to remove the 'SupportsContentType' member, I get a "'CustomJsonSerializer' does not implement interface member 'IRestSerializer.SupportsContentType' error.
![image](https://user-images.githubusercontent.com/62567532/225646804-2c163123-ef48-4ccf-b19c-1f187e287a90.png)

**Comment by alexeyzimarev** [comment]
You look at the code of any existing serialises like this one:

```csharp
    public SupportsContentType SupportsContentType => contentType => contentType.Value.Contains("json");
```

The change is basically to have more flexibility in the serialiser to match the content type in any way you want instead of adding a lot of different variations of content type strings.

**Comment by alexeyzimarev** [comment]
Well, `Newtonsoft.Json.JsonSerializer` apparently doesn't implement any interfaces from RestSharp. Please just look at the code of `RestSharp.Serializers.NewtonsoftJson` project. Btw you don't need to create a custom serialiser to use Json.NET.

```csharp
var client = new RestClient(
    options, 
    configureSerialization: s => s.UseNewtonsoftJson(new JsonSerializerSettings {...})
);
```
