### ISSUE TITLE
System.Text.Json dependency is broken for net6.0 when used in netstandard2.0 library

### ISSUE THREAD

**Issue by nesc58** [restsharp/RestSharp#2033]
**Describe the bug**
Conflict between System.Text.Json Version 6.0.0 and Version 7.0.0
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 
File name: 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```
When RestSharp is installed in a netstandard2.0 library project System.Text.Json will be used with version 7.0.2 in this library, because RestSharp installs System.Text.Json version 7.0.2 for netstandard2.0.
When this library is used in a net6.0 console app the errors occurs because net6.0 uses System.Text.Json in version 6.0.0 internally and System.Text.Json 7.0.2 is not installed explicit.

**To Reproduce**
1. Create a Library project with netstandard2.0
2. Install RestSharp
3. Create a wrapper class for RestSharp with custom SystemTextJsonSerializer (see WrappedClient example)
4. Create a console app with .net6.0
5. Add the library project to the console app
6. Call the constructor of the wrapped client

**Wrapped Client**
```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using RestSharp;
using RestSharp.Serializers.Json;

namespace LibraryA;

public sealed class WrappedClient
{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        Converters =
        {
            new JsonStringEnumConverter()
        },
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    private readonly RestClient _client;

    public Client()
    {
        _client = new RestClient(new RestClientOptions(), configureSerialization: sc => sc.UseSerializer(() => new SystemTextJsonSerializer(SerializerOptions)));
    }
}
```

**Console App**
```csharp
try
{
    var client = new LibraryA.WrappedClient();
    Console.WriteLine("Client created");
}
catch (Exception e)
{
    Console.WriteLine("Client creation failed");
    Console.WriteLine(e);
    throw;
}
```

**Possible Solutiosn**
I have no idea if this problem is RestSharp related. I have no idea what's the correct solution for RestSharp to fix this.
The actual dependencies are broken when a library (netstandard2.0) installs RestSharp and uses System.Text.Json e.g. to configure the serializer and the library is used in a net6.0 application.
My first thoughts are that RestSharp must fix this because RestSharp is installing the dependencies. But I have found a solution for me (see below).

So the question is: Should RestSharp fix the dependencies so it can easily be used in libraries? For example a possible solution could be installing System.Text.Json for all frameworks in Version 7.0.2. Another solution could be to install a lower version of System.Text.Json for netstandard2.0 which fits to the frameworks. I have really no idea.

**Workaround / my solution for now**:
The first possible workaround is installing System.Text.Json in version 7.0.2 explicit in the library project.
Another solution is to build the library project with `<TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>`. So the correct version of System.Text.Json will be used for net6.0

**Comment by alexeyzimarev** [comment]
Could you elaborate how RestSharp is installed as a .NET Standard library to a .NET 6 project? RestSharp builds for .NET 6 and .NET 7 as native targets. It also only references `System.Text.Json` package for .NET Standard and .NET Framework.

```xml
    <ItemGroup Condition="$(TargetFramework) != 'net6.0' And $(TargetFramework) != 'net7.0'">
        <PackageReference Include="System.Text.Json" Version="7.0.2" />
    </ItemGroup>
```

**Comment by alexeyzimarev** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/2821205/226543454-c216f8f5-ed63-41ed-979f-fdfa57279188.png">

**Comment by alexeyzimarev** [comment]
I think the only way to fix it is to remove the referenced package condition and make all the targets depend on `System.Text.Json` 7.0.2, so it will be installed.

**Comment by alexeyzimarev** [comment]
Of course the workaround is to install the `System.Text.Json` package 7.0.2 or higher to the project that references LibraryA.
