### ISSUE TITLE
ThrowOnAnyError set to false but still throws errors

### ISSUE THREAD

**Issue by AdamJurga** [restsharp/RestSharp#2038]
In version 109.0.1 errors are being thrown for all bad requests. Setting ThrowOnAnyError does not work and changing it between true and false does not change anything.

**To Reproduce**
```
  try{ 
   var options = new RestClientOptions("url")
            {
                Authenticator = new HttpBasicAuthenticator("user","password"),
                ThrowOnAnyError = false,
                MaxTimeout = 5000
            };
            var client = new RestClient(options);

            RestRequest request = new RestRequest("resource")
                .AddHeader("Content-Type", "application/json")
                .AddJsonBody(object);

           RestResponse response = await client.PostAsync(request);
}
 catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
```

**Expected behavior**
Be able to read RestResponse.ResponseStatus, now it's being thrown to "catch exception" block

**Stack trace**
   at RestSharp.RestClientExtensions.<PostAsync>d__17.MoveNext()
   at service.Common.Services.SftpService.<MakeCall>d__3.MoveNext() in PathHere\Service.cs:line 54

**Desktop (please complete the following information):**
 - OS: Win11
 - .NET version: .NET 6
 - Version - 109.0.1

**Comment by alexeyzimarev** [comment]
Please follow the contribution guidelines and at least add the stack trace.

**Comment by AdamJurga** [comment]
> Please follow the contribution guidelines and at least add the stack trace and the code sample.

sorry @alexeyzimarev, I thought that this is basic usage and filling the form it's not need. I edited my post. Please let me know if any other details are needed.

**Comment by alexeyzimarev** [comment]
Btw that's why I was asking for the code and stack trace. If you use `ExecutePostAsync` it won't throw.

I think `PostAsync` was changed to throw in order to make the API more consistent. Basically, all `Execute` functions don't throw (unless instructed) and all `Post`, `Get`, etc throw.

**Comment by AdamJurga** [comment]
> Btw that's why I was asking for the code and stack trace. If you use `ExecutePostAsync` it won't throw.
> 
> I think `PostAsync` was changed to throw in order to make the API more consistent. Basically, all `Execute` functions don't throw (unless instructed) and all `Post`, `Get`, etc throw.

Thank you and of course you are right :)

**Comment by alexeyzimarev** [comment]
I will update the docs, thanks for the heads up
