### ISSUE TITLE
DownloadStreamAsync and server error

### ISSUE THREAD

**Issue by nssoft-rlagrange** [restsharp/RestSharp#2057]
Ahh, looking at the code I think your suggestion before might work here. I think we can use the OnAfterRequest callback for the request to be able to get the response message so we can do something useful with that (basically save it off to inspect later?) when the download action completes?

If that is accurate we can close this out.

_Originally posted by @kendallb in https://github.com/restsharp/RestSharp/issues/1823#issuecomment-1084971331_
            
Hi, I'm having a similar issue : the server respond an error (406 in my case), but I don't have any indication that the download failed, and I save the body as the expected file I'm downloading (but got an error message in file).
What where you thinking to circumvent the issue ?
At the very least, I want an exception if the server doesn't return a 20X.
Regards,

**Comment by alexeyzimarev** [comment]
Have you tried setting `ThrowOnAnyError` to `true`? I looked at the `Download` code and it will throw in your case.

**Comment by nssoft-rlagrange** [comment]
I don't have this property on 108.
I found a workaround by settings the AfterRequest delegate 👍 
`Exception sharedException = null;
request.OnAfterRequest = (response) => // capture exception
{
	try
	{
		response.EnsureSuccessStatusCode();
	}
	catch(Exception e) { sharedException = e; }
	return new ValueTask(Task.FromResult(response.Content));
	
};
using (var str = await client.DownloadStreamAsync(request, token))
{
	if (sharedException != null) throw sharedException; // fire captured exception
	await str.CopyToAsync(fs);
}`

**Comment by alexeyzimarev** [comment]
`ThrowOnAnyError` is the client option that exists since v107. Before that it was the client property.

**Comment by nssoft-rlagrange** [comment]
Doesn't work, at least in my 108 version. No exception thrown, at the very least the stream is empty, so I could check the length.
My workaround work fine.

**Comment by alexeyzimarev** [comment]
It was fixed by this PR https://github.com/restsharp/RestSharp/pull/1962. I am not sure what version was release after that.
