### ISSUE TITLE
[Documentation] Code Snippets in `Intro.md` do not declare `cancellationToken`, yet use it in the examples

### ISSUE THREAD

**Issue by Rubix982** [restsharp/RestSharp#2060]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
This is regarding the documentation. The `intro.md`, or the "Basic Usage" page in "Getting Started" has code snippets that use the `cancellationToken` variable, but do not declare it.

**To Reproduce**
Please see page here, https://restsharp.dev/intro.html#basic-usage.

**Expected behavior**
Proper declaration and initialization of the `cancellationToken` variable.

**Stack trace**
Not applicable.

**Desktop (please complete the following information):**
Not applicable.

**Additional context**
None.

**Comment by alexeyzimarev** [comment]
It doesn't suppose to. It's a syntactically correct C#, but it's still pseudo-code.

**Comment by Rubix982** [comment]
Undertsood. My suggestion that having some declaration of `cancellationToken` might be okay to have, but I get your point as well.

**Comment by alexeyzimarev** [comment]
The thing is that the only way I can instantiate a cancellation token in that snippet is to create a source and get a token from it. It will be quite confusing to have the code in that example as people might thing this is what they need to do. In reality, the token comes from the outside, like an HTTP request cancellation or something similar. It's rare that one needs to create a token manually. I will add a comment to the snippet about it, I think your point is valid.

**Comment by Rubix982** [comment]
Yeah, I think, just a comment that provides context over what `cancellationToken` is supposed to be, as you have described above, would be sufficient as well (something concise).

Thank you!
