### ISSUE TITLE
HttpRequest doesn't send parameters added in Authenticator

### ISSUE THREAD

**Issue by hmG3** [restsharp/RestSharp#2061]
**Describe the bug**
After upgrading from version 109.1 to 110.0 I noticed some of our logic is broken.
A typical use case for us is to add security headers during the authentication flow.

```csharp
public override ValueTask Authenticate(IRestClient client, RestRequest request)
{
    request.AddOrUpdateParameter("X-Security-Param", "generated-security-hash");
    return ValueTask.CompletedTask;
}
```
However, it doesn't work when sending requests with form data.

While investigating, I found that now when building `RequestContent`
https://github.com/restsharp/RestSharp/blob/edce8c948c9e0fecf45959069801ad5367005327/src/RestSharp/RestClient.Async.cs#L89
 for `HttpRequestMessage` it adds only cached params
https://github.com/restsharp/RestSharp/blob/edce8c948c9e0fecf45959069801ad5367005327/src/RestSharp/Request/RequestContent.cs#L41
 but not ones added by Authenticator
https://github.com/restsharp/RestSharp/blob/edce8c948c9e0fecf45959069801ad5367005327/src/RestSharp/RestClient.Async.cs#L92

**To Reproduce**
```csharp
public class RestWrapper : IAuthenticator
{
    private readonly RestClient _restClient;

    public RestWrapper()
    {
        _restClient = new RestClient(new RestClientOptions
        {
            BaseUrl = new Uri("https://localhost"),
            Authenticator = this
        });
    }

    public ValueTask Authenticate(IRestClient client, RestRequest request)
    {
        request.AddParameter("X-Security-Param", "generated-security-hash");
        return ValueTask.CompletedTask;
    }

    public void SendRequest()
    {
        var testRequest = new RestRequest("api/v1/endpoint", Method.Post);
        testRequest.AddParameter("scope", "test");

        _restClient.Execute(testRequest);
    }
}

new RestWrapper().SendRequest() // server failure - missing X-Security-Param
```

**Comment by alexeyzimarev** [comment]
Yes, it can be fixed by moving the authenticator call a couple of lines up.

The reason why it works in most cases is that people usually use the authorisation header, and headers are added later.
