### ISSUE TITLE
GetJsonAsync<type> with Newtonsoft serializer stopped working with 110 update

### ISSUE THREAD

**Issue by almostEric** [restsharp/RestSharp#2063]
**Describe the bug**
After updating both RestSharp and RestSharp.Serializers.NewtonsoftJson to 110 (and subsequently to 110.1 and 110.2)
the RestClient.GetJsonAsync<type> call now returns a "method not allowed" error

**To Reproduce**
MenuSettings = await _serverService.RestClient.GetJsonAsync<AndroidMenuSettings>(string.Format("AndroidMenuSettings/{0}", menuId));

**Expected behavior**
I expect the object to be retrieved from the API and deserialized.

**Stack trace**
ex = {System.Net.Http.HttpRequestException: Request failed with status code MethodNotAllowed
   at RestSharp.ResponseThrowExtension.ThrowIfError[AndroidMenuSettings](RestResponse`1 response)
   at RestSharp.RestClientExtensions.<GetAsync>d__13`1[[BeerDashboard.C...

This call performed as expected in version 109.

**Comment by alexeyzimarev** [comment]
Please add the required information according to the issue template.

**Comment by almostEric** [comment]
done

**Comment by alexeyzimarev** [comment]
What's the client configuration code?

**Comment by almostEric** [comment]
HttpClient httpClient;

            JsonSerializerSettings defaultSettings = new JsonSerializerSettings
            {
                DefaultValueHandling = DefaultValueHandling.Include,
                TypeNameHandling = TypeNameHandling.All,
                ObjectCreationHandling = ObjectCreationHandling.Replace,
                NullValueHandling = NullValueHandling.Include,
                Formatting = Formatting.None,
                ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor
            };

            _httpsClientHandlerService = httpsService;
            HttpClientHandler handler = _httpsClientHandlerService.GetPlatformMessageHandler();

            handler.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;
            httpClient = new HttpClient(handler);

            httpClient.BaseAddress = new Uri(_apiUrl);
            httpClient.Timeout = new TimeSpan(0, 15, 0); //15 minutes

            RestClient = new RestClient(httpClient, configureSerialization: s => s.UseNewtonsoftJson(defaultSettings));
            RestClient.AddDefaultHeader("Content-type", "application/json");
            RestClient.AddDefaultHeader("Accept-Encoding", "gzip");

**Comment by alexeyzimarev** [comment]
So if you right now downgrade to v109 it will work?

I am not sure what the issue is, the extension definitely didn't change, it must be something else.

It would help if you can make this call to a Requestbin with both versions and see if there's any difference in the raw request.

**Comment by almostEric** [comment]
Yes,

It was working before with 109 and works again if I downgrade 

Eric

**Comment by alexeyzimarev** [comment]
What happens if you remove this line:

```
RestClient.AddDefaultHeader("Content-type", "application/json");
```

Why are you adding it anyway? GET requests with content headers might crash.

**Comment by Serenelol** [comment]
We started getting this in our Android emulator specifically - windows was fine. Removing the line @alexeyzimarev suggested worked. Not sure why we had it originally but things seem to work without it so \o/

**Comment by alexeyzimarev** [comment]
`HttpClient` has different implementations on different platforms. Unfortunately, there are some inconsistencies there. Basically, adding `Content-Type` header to `GET` calls is an anti-pattern as you don't support to have any content.
