### ISSUE TITLE
Documentation for Authentication is not correct

### ISSUE THREAD

**Issue by jmarbutt** [restsharp/RestSharp#2066]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
The documentation for the Authentication is incorrect as of the version 109. You can see the documentation here:
https://restsharp.dev/authenticators.html

**To Reproduce**
The Authenticator Property is deprecated that is used in the documentation. 

**Expected behavior**
It would be great to cut down on the confusion of the authentication methods to have the documentation updated. I would update it and do a PR myself but I can't seem to figure it out between the various discussions out there. I would like to see the "official" way of doing Basic Authentication.

**Additional context**
I am more than happy to update the docs for you if you can give me some direction but I am stuck on version 108 until I can figure it out.

**Comment by alexeyzimarev** [comment]
The docs are up to date now.
