### ISSUE TITLE
Possibility to set Serializer on RestRequest (instead of client), for client reuse with different serialisers

### ISSUE THREAD

**Issue by unhammer** [restsharp/RestSharp#2070]
**Is your feature request related to a problem? Please describe.**

I'd like to reuse RestClient for different requests, from different threads. I'd also like to have different serialisers per request (mainly for logging of url along with exact response). I can easily have one of these, but currently not both at the same time, since the serialiser is set on the client, not on the request.

**Describe the solution you'd like**
I would like to do 

```csharp
                 private static RestClient client;
                 …
                 var req = new RestRequest(url);
                 req.UseSerializer(() => new MySerializer(myargs);
```
(or `var req = new RestRequest(url, serializer: …);`) instead of having to

```csharp
                var req = new RestRequest(url);
                client = new RestClient();
                client.UseSerializer(() => new MySerializer(myargs);
```

**Describe alternatives you've considered**
There is https://github.com/restsharp/RestSharp/issues/1791#issuecomment-1073129100 which created a whole dictionary of clients to workaround the issue. I would end up with too many clients to use this workaround – preferably I'd have just one client for all requests.

**Additional context**

https://restsharp.dev/v107/#restclient-lifecycle says we should reuse, as with HttpClient :)

**Comment by alexeyzimarev** [comment]
There is also a callback `OnBeforeDeserialization` on the request level that gives you the `RestResponse` instance before it is sent to deserialiser.

**Comment by alexeyzimarev** [comment]
Fro SO:

> Very typically, you want these to be the same for calls to the same host but not for calls to different ones. For this reason, an HttpClient instance per host being called is actually a very good practice. Unless you're calling thousands of different hosts, you don't need to worry about [the infamous socket exhaustion problem](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) here. (And even if you were using a singleton, the underlying network stack would need to open a different socket per host anyway.)

The only valid reason to reuse the client for is the sake of reusing socket connections, which makes no sense when the client is used to call different base URLs. It is also very unlikely that a single base address has an API endpoints so wildly different they require different serialiser per endpoint.
