### ISSUE TITLE
await _client.GetAsync<T>(request, cancellationTokenSource.Token) never finish

### ISSUE THREAD

**Issue by tibormarchyn** [restsharp/RestSharp#2071]
**Describe the bug**
following simple code (from getting started page) never finish, it's stucked on GetAsync method. No exception thrown, no error, just reponse never come back and code never continue to "return" statement. Using sync "Get" method works correctly.

```
var _options = new RestClientOptions(ApiURL)
{
   Authenticator = new HttpBasicAuthenticator(username, password),
   MaxTimeout = 30000,
};
var _client = new RestClient(_options);
var request = new RestRequest("/objects?$top=1000&$count=true");
var cancellationTokenSource = new CancellationTokenSource();
var response = await _client.GetAsync<CustomClass>(request, cancellationTokenSource.Token);
return response;
```

**Expected behavior**
await client.GetAsync returns reponse

**Stack trace**
no stacktrace, no exception is thrown

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 latest CU
 - .NET 7
 - Version 110.2.1

**Comment by alexeyzimarev** [comment]
`GetAsync` works. There's something in your setup that produces the issue.

**Comment by tibormarchyn** [comment]
I found a deadlock in app today, so closing as invalid.
