### ISSUE TITLE
The response stream from AdvancedResponseWriter is disposed too early

### ISSUE THREAD

**Issue by bednar** [restsharp/RestSharp#2072]
**Describe the bug**
I want to stream response data to my API for advanced processing. For this purpose I use `AdvancedResponseWriter` because I also want to handle errors from remote resource (=> I cannot use `RestSharp.RestClient.DownloadStreamAsync`), but the latest changes close response stream too early. It is cause by `using` in:

`using var internalResponse = await ExecuteRequestAsync(request, cancellationToken).ConfigureAwait(false);`

- https://github.com/restsharp/RestSharp/blob/71c73f8e9aa1317a5c49d25126b1a23bd36e36c1/src/RestSharp/RestClient.Async.cs#L23
- https://github.com/restsharp/RestSharp/pull/2056

**To Reproduce**
```csharp
[Test]
public async Task AdvancedResponseWriterKeepStream()
{
    await foreach (var line in MyAsyncApi())
    {
        Console.WriteLine(line);
    }
}

private async IAsyncEnumerable<string> MyAsyncApi()
{
    using var client = new RestClient(new RestClientOptions("https://demo.ckan.org/"));
    var restRequest =
        new RestRequest(
            "dataset/c322307a-b871-44fe-a602-32ee8437ff04/resource/b53c9e72-6b59-4cda-8c0c-7d6a51dad12a/download/sample.csv");

    Stream stream = null;
    restRequest.AdvancedResponseWriter = (response, request) =>
    {
        if (!response.IsSuccessStatusCode)
        {
            throw new Exception($"Do something with unsuccessful response: {response}");
        }

        stream = response.Content.ReadAsStreamAsync().ConfigureAwait(false).GetAwaiter().GetResult();

        return new RestResponse(request);
    };

    await client.ExecuteAsync(restRequest);

    using var reader = new StreamReader(stream, Encoding.UTF8);
    while (reader.Peek() >= 0)
    {
        // advanced processing
        yield return await reader.ReadLineAsync();
    }
}
```

**Expected behavior**
Be able to stream response to `API`.

**Stack trace**
```
System.ArgumentException : Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
```

**Desktop (please complete the following information):**
 - OS: `macOS`
 - .NET version: `NET 5`
 - Version: `110.2.0`

**Comment by alexeyzimarev** [comment]
I think you are using the advanced response writer for the wrong purpose. It's meant to rewrite the response, and it should finish within the scope of one request, before the response is returned.

You might want to use `DownloadStreamAsync` or `StreamJsonAsync` instead.

**Comment by sensslen** [comment]
My use case is to inspect the headers before executing the actual download. How would this be possible with the streaming api?

**Comment by alexeyzimarev** [comment]
Ah sorry, `ExecuteRequestAsync` is private.

You still can use `OnAfterRequest`:

```csharp
    /// <summary>
    /// When supplied, the function will be called after the request is complete
    /// </summary>
    public Func<HttpResponseMessage, ValueTask>? OnAfterRequest { get; set; }
```

**Comment by alexeyzimarev** [comment]
My current thought is to change the interface signature and make Download work differently. Right now, it returns `Task<Stream?>`, which prevents the user to inspect the response for errors. It crashes if the call wasn't successful.

So, the idea is to make `ExecuteStreamAsync`, which will return `Task<RestStreamResponse>`. The response will be like `RestResponse` but instead of `Content` it will have `Stream?`. Naturally, it requires to be `IDisposable`.

The first step there was to create a source generator to create instance of `RestResponseBase` child class, as copying those properties manually is error prone (adding a new prop requires many changes). That part is done, so now this thing should be relatively easy.

**Comment by alexeyzimarev** [comment]
Continues in https://github.com/restsharp/RestSharp/issues/2226
