### ISSUE TITLE
File or assembly System.Runtime.CompilerServices.Unsafe 4.0.4.1 missing (ExecutePostAsync)

### ISSUE THREAD

**Issue by erkanKR** [restsharp/RestSharp#2075]
I installed the current stable version of RestSharp.
After call an ExecutePostAsync call, the code will throw an exception
(System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
I tried to create a simple Post Method

`   
  RestRequest request = new RestRequest("DataAPI");
  request.AddJsonBody(appointment);
  var response = await client.ExecutePostAsync(request);
`

Outlook VSTO Plugin
.Net Framework 4.8

**Comment by alexeyzimarev** [comment]
Please provide the details requested in the issue template.
