### ISSUE TITLE
order request headers

### ISSUE THREAD

**Issue by atimofeev86** [restsharp/RestSharp#2079]
I have a code:

`var options = new RestClientOptions(url)
                    {
                        Proxy = new WebProxy("http://172.16.51.199:8103")
                    };
                    var client = new RestClient(options);

                    var request = new RestRequest("");
                    request.AddHeader("Authorization", "token pkxdujXNjo0fB8VVeA1H2rc9s_XF_m0aA1uEI");
                    request.AddHeader("Accept", "application/json");
                    request.AddHeader("User-Agent", "c# 3.0");
                    request.AddHeader("Locale", "en_US");
                    request.AddHeader("Accept-Language", "en-US");
                    request.AddHeader("Content-Type", "application/json; charset=UTF-8");
                    request.AddHeader("Content-Length", "129");
                    request.AddHeader("Accept-Encoding", "gzip, deflate");

                    var requestBody = new
                    {
                        authToken = "d81932c781288890e2348e622b45b27627696e818d03bdc8c6cc60bb6be1fa43",
                        thirdPartyUserId = "google"
                    };
                    request.AddJsonBody(requestBody);
                    var response = client.PostAsync(request).Result;
                    string content1 = response.Content;`

When I sent it I seen in the burp requset:
POST /sessions HTTP/2
Host: site.com
Authorization: token pkxdujXNjo0fB8VVeA1H2rc9s_XF_m0aA1uEI
Accept: application/json
User-Agent: c# 3.0
Locale: en_US
Accept-Language: en-US
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=UTF-8
Content-Length: 129
Expect: 100-continue

{"authToken":"d81932c781288890e2348e622b45b27627696e818d03bdc8c6cc60bb6be1fa43","thirdPartyUserId":"google"}

But I need to have "Accept-Encoding: gzip, deflate" at the end headers. How can I do it?

**Comment by alexeyzimarev** [comment]
RestSharp add headers to the request message in order. It might be the message handler that reorders them.
