### ISSUE TITLE
HttpClient vs RestSharp Benchmark

### ISSUE THREAD

**Issue by ngoquoctoandev** [restsharp/RestSharp#2086]
I reused the following code for a simple review. https://github.com/CodeMazeBlog/CodeMazeGuides/tree/main/dotnet-client-libraries/HttpClientVsRestSharp/HttpClientVsRestSharp
The source code in the review I have upgraded all packages to the latest version, .NET 7, hardware information as attached image below.

My performance analysis shows that both libraries are similar in time performance. However, HttpClient performs better regarding memory allocation. Is there a way to make this library even better while keeping the same performance as HttpClient.

<img width="632" alt="image" src="https://github.com/restsharp/RestSharp/assets/78490340/3b7a350d-a95c-4278-929b-c723eb6422e1">

<img width="464" alt="image" src="https://github.com/restsharp/RestSharp/assets/78490340/12fd9260-cc3d-4f4f-b3fc-091dc2e52c46">

**Comment by alexeyzimarev** [comment]
You can't do _the same_ as RestSharp calls HttpClient. It will always be _more_ allocations and _more_ time.

It's also not clear what you are comparing, there's no code to look at. It's also unclear what are you calling, what are the payload sizes, etc.

Please, if you want to suggest performance improvements, be more specific.
