### ISSUE TITLE
Can't add Content-Type Header on Get Request

### ISSUE THREAD

**Issue by benrpatterson** [restsharp/RestSharp#2087]
**Describe the bug**
When trying to submit a GET Request with the "Content-Type" header, I get the error "Cannot send a content-body with this verb-type". I am not trying to send a body with my request, but the server I am sending my request to does require the Content-Type header.

**To Reproduce**
Create a GET request with the header "Content-Type" set.

**Expected behavior**
Successfully make the GET request with the specified Content-Type Header

**Desktop (please complete the following information):**
 - OS: Windows
 - .NET version: .NET 6
 - Version 110.2.0

**Comment by alexeyzimarev** [comment]
You have not posted the stack trace as requested, but I know that it comes from HttpClient, and not from RestSharp. We cannot do things that HttpClient cannot do.

**Comment by benrpatterson** [comment]
Yeah you are right just finished some more testing and it is the HttpClient that is throwing the error. Sorry I didn't check that earlier
