### ISSUE TITLE
Getting Could not load file or assembly Sytem.Text.Json 7.0.0.2 when updated to System.Text.Json 7.0.3 in main project

### ISSUE THREAD

**Issue by NXTwoThou** [restsharp/RestSharp#2102]
In .NET v4.8 asp.net website get this error if I update System.Text.Json to 7.0.3 when trying to do new RestClient() with 110.2.0

Could not load file or assembly 'System.Text.Json, Version=7.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Reverting to System.Text.Json 7.0.2 works.

**Comment by alexeyzimarev** [comment]
Use assembly binding redirect.
