### ISSUE TITLE
Restsharp 110.2.0 error during Zephyr integration.

### ISSUE THREAD

**Issue by prashantguleria2504** [restsharp/RestSharp#2103]
Getting below error while integrating RestSharp v 110.2.0 framework (xunit) with Zephyr, while the same Zephyr implementation is working correctly with v 106.15.0. Requests you to solve the issue in latest version 110.2.0 too.

Message:  
System.AggregateException : One or more errors occurred. (Method not found: 'Void RestSharp.RestClient..ctor(System.String)'.) (The following constructor parameters did not have matching fixture data: ZephyrFixture zephyrFixture)
---- System.MissingMethodException : Method not found: 'Void RestSharp.RestClient..ctor(System.String)'.
---- The following constructor parameters did not have matching fixture data: ZephyrFixture zephyrFixture

  Stack Trace: 
----- Inner Stack Trace #1 (System.MissingMethodException) -----
ZephyrFixture.ctor()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

**Comment by alexeyzimarev** [comment]
It's not a RestSharp issue.

**Comment by prashantguleria2504** [comment]
Hi...Thx for the response. If its not RestSharp issue then why the same code is working with RestSharp v 106 and not with 110.
Can you plz help in resolving the same.

**Comment by alexeyzimarev** [comment]
Because v110 has breaking changes as the error message you got suggests.

**Comment by prashantguleria2504** [comment]
Can you plz help how to resolve the above issue.,
