### ISSUE TITLE
is possible add method propfind to enum asMethod

### ISSUE THREAD

**Issue by freyes-lef** [restsharp/RestSharp#2124]
Hi

my request it´s similar to https://github.com/restsharp/RestSharp/issues/1689

In older versions of RestSharp i use this:

var response = client.ExecuteAsPost(request, "PROPFIND");

it,s possible add de PROPFIND method  to call to webdav server

example:
  var response = await client.ExecutePostAsync(request, Method.Propfind);

Thnks in advance

**Comment by freyes-lef** [comment]
It´s possible add the rest of methods for webdav in future previsions:

 MKCOL, MOVE, LOCK, UNLOCK 

Thanks

**Comment by alexeyzimarev** [comment]
I added a more generic issue #2166, let's discuss it there.
