### ISSUE TITLE
.net functions system.text.json not being detected when adding restsharp v110+

### ISSUE THREAD

**Issue by bengarrison** [restsharp/RestSharp#2134]
When working in a azure functions app (tested with .net 6 and 7, v4), simply adding restsharp causes BinaryData to 

To reproduce, simply make a new azure functions app, add the dependencies which are supposed to work:
```
    <PackageReference Include="RestSharp" Version="110.2.0" />
    <PackageReference Include="System.Text.Json" Version="7.0.3" />
```

then in an example function, try this:

`new BinaryData("{}").ToObjectFromJson<dynamic>();`

with the restsharp library, it throws an error of:

`Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

If you remove both restsharp and system.text.json dependencies, the code runs fine... but if you add either of em, the above error is thrown.

Also if you downgrade the restsharp package to v109, and don't include system.text.json, it works.

My presumption is that .net6 is overriding any system.text.json with version 6, and because it's a functions app, I can't do any binding redirects or other fancy stuff that i'm aware of to enforce v7 usage.

Any help would be greatly appreciated!

**Comment by bengarrison** [comment]
Just noticed this issue happens when you only reference System.Text.Json and not even include restsharp.  So seems to be some issue with azure functions in general :/  Will close.

**Comment by alexeyzimarev** [comment]
If you search StackOverflow and closed issues, you'll find that it's been raised multiple times, and the SO question has my answer.

**Comment by bengarrison** [comment]
aye I saw that as well, though no suggestions have resolved the issue unfortunately :/  Appears to be an issue that's affected ever function apps version, with Microsoft's response being basically that you're stuck with the old version :(  

https://github.com/Azure/Azure-Functions/issues/1898
https://github.com/Azure/azure-functions-host/issues/4925
