### ISSUE TITLE
The OnBeforeRequest event is never called

### ISSUE THREAD

**Issue by bveldkamp** [restsharp/RestSharp#2137]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
I have implemented both OnBeforeRequest and OnAfterRequest. OnAfterRequest works fine, but OnBeforeRequest never seems to be called.

**To Reproduce**
Sample code:
```
request = new RestRequest("something");
request.OnBeforeRequest += BeforeRequest;
request.OnAfterRequest += AfterRequest;

private ValueTask AfterRequest(HttpResponseMessage message)
{    
    return ValueTask.CompletedTask;
}

private ValueTask BeforeRequest(HttpRequestMessage message)
{
    // This code is never reached
    return ValueTask.CompletedTask;
}
```

**Expected behavior**
Both events should be called

**Desktop**
 - OS: Windows 11
 - .NET 6
 - Version 109.0.1

**Additional info**
I do have a custom authenticator, could that interfere with the OnBeforeRequest event? I would expect the event to be raised regardless.

**Comment by alexeyzimarev** [comment]
It is called:
https://github.com/restsharp/RestSharp/blob/36ebe2fae4de59ad54633b31193a7f977740b2d1/src/RestSharp/RestClient.Async.cs#L114

**Comment by bveldkamp** [comment]
You're right, I can't reproduce it in an otherwise empty application. Sorry, I should have tested that before posting here ;-)
