### ISSUE TITLE
Solution is not building because of a wrong TargetFramework in a Test.

### ISSUE THREAD

**Issue by AntonioGomes42** [restsharp/RestSharp#2139]
Hi, I downloaded the repository of this project for studying purposes, and when i tried to build the solution it gave a error.
And this error ocurred by a wrong TargetFramework informed in the **RestSharp.InteractiveTests.csproj**.
It is as follows:

The actual **RestSharp.InteractiveTests.csproj** file
![image](https://github.com/restsharp/RestSharp/assets/73271272/20b07371-38d3-4ce5-a5d4-53f20b009ba2)

How it should be:
![image](https://github.com/restsharp/RestSharp/assets/73271272/a5cb6c93-5a19-4014-8f03-2ad4a0a2319c)

After fixing it, I could build the project.

**Comment by alexeyzimarev** [comment]
It's a breaking change in .NET 8 compiler preview.
