### ISSUE TITLE
Single file upload without multipart/data (Release timeline)

### ISSUE THREAD

**Issue by sensslen** [restsharp/RestSharp#2143]
**Is your feature request related to a problem? Please describe.**
I'm trying to upload a single file without multipart/data. This has been merged with https://github.com/restsharp/RestSharp/pull/2068.

**Describe the solution you'd like**
Can you please share your plans for the next release that contains this feature?

**Describe alternatives you've considered**
I did consider forking the repo to build my own beta version.... This seems like a bad 

**Additional context**
None

**Comment by alexeyzimarev** [comment]
Why do you need to fork the repo to get a package? All merged PRs emit a new package. https://www.nuget.org/packages/RestSharp/110.2.1-alpha.0.13#versions-body-tab

**Comment by sensslen** [comment]
Thanks for sharing - I did not notice....
