### ISSUE TITLE
RestClientOptions Error: Type undefined

### ISSUE THREAD

**Issue by premy** [restsharp/RestSharp#2149]
**DO NOT USE ISSUES FOR QUESTIONS**

**Describe the bug**
trying to use RestClientOptions:
 `Dim options = New RestClientOptions("https://xxxxxx") With {
        .MaxTimeout = -1
    }
    Dim client = New RestClient(options)`

Compiler Complains: The type RestClientOptions is undefined. 
I'm using RestSharp v.110.2.0 in an asp.net 461 app

**To Reproduce**
Steps to reproduce the behavior, preferably using a code snippet. 
Post the non-working request here as well if you made it work using Postman, Swagger, or any other client.

**Expected behavior**
Post the working request here as well if you made it work using Postman, Swagger, or any other client.
You can use https://requestbin.com/r to create a public request bin and share the link in the issue.

**Stack trace**
Copy the full stack trace here if you get an exception.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - .NET version [e.g. .NET 5]
 - Version [e.g. 107.0.4]

**Additional context**

**Comment by alexeyzimarev** [comment]
`RestClientOptions` is a public class, and if you get a message it's undefined, you are missing a using/import or something else related to the basic usage of the language. Please try figuring it out.
