### ISSUE TITLE
CamelCase serialization doesn't work on System.Object after upgrading to: 110.2.0

### ISSUE THREAD

**Issue by SebastianJust** [restsharp/RestSharp#2150]
Hi, 

I've newly upgraded to version: 110.2.0.
After the upgrade, it will not serialize the data as camelCase, when using: 

```
RestResponse<object> response =  await _restClient.ExecuteGetAsync<object> (new RestRequest("/api/users")
    .AddHeader("Authorization", string.Format("Bearer {0}", token)));
object result = response.Data;
```

![image](https://github.com/restsharp/RestSharp/assets/24389114/93baa085-c2f0-442c-9748-6c7fa4e17d7b)

The object is still PascalCase.

I've tried to override the existing configuration by using the 'UseNewtonsoftJson' without any progress.

```
RestClient client = new RestClient(url, configureSerialization: s => s.UseNewtonsoftJson());
```

In addtion: I've also tried: 
```
  string json = JsonConvert.SerializeObject(response.Data, new JsonSerializerSettings
  {
      ContractResolver = new CamelCasePropertyNamesContractResolver(),
      Formatting = Formatting.Indented
  });
```

Secondly i've also tried to use the 'UseSystemTextJson'. Here is the response: 
```
{
    "valueKind": 2
}
```

Can you please help me how to fix it? Are there anyway I can configure it as it was in release: 106.15?

**Comment by alexeyzimarev** [comment]
I don't see any serialisation and deserialisation being linked in one execution path. The sample code is deserialising something, and I can't see where the serialisation issue occurs.

**Comment by SebastianJust** [comment]
@alexeyzimarev yes exactly I agree. But I think it might be the way it's deserialized that has been changed, when you returning: 'Data'. It looks like it was some kind of KeyValue before (In your previous versions). 

I've made a work around, that works.

 private static object DeserializeJson(this string json)
 {
     if(string.IsNullOrEmpty(json))
         return null;

     JToken jToken = JToken.Parse(json);

     return jToken.Type switch
     {
         JTokenType.Object => JsonConvert.DeserializeObject<ExpandoObject>(json),
         JTokenType.Array => JsonConvert.DeserializeObject<List<ExpandoObject>>(json),
         JTokenType.String => JsonConvert.DeserializeObject<string>(json),
         JTokenType.Boolean => JsonConvert.DeserializeObject<bool>(json),
         JTokenType.Bytes => JsonConvert.DeserializeObject<byte[]>(json),
         JTokenType.Date => JsonConvert.DeserializeObject<DateTime>(json),
         JTokenType.Guid => JsonConvert.DeserializeObject<Guid>(json),
         JTokenType.Integer => JsonConvert.DeserializeObject<int>(json),
         JTokenType.Uri => JsonConvert.DeserializeObject<string>(json),
         JTokenType.Float => JsonConvert.DeserializeObject<float>(json),
         _ => throw new NotImplementedException()
     };
 }

But that's not the proper way of wanna do it.

**Comment by SebastianJust** [comment]
Oh okay! Cool :) That makes sense. So do you have any extensions or something build in or, should I do something else?

**Comment by alexeyzimarev** [comment]
Sorry, I missed your response. What extensions did you mean?

**Comment by alexeyzimarev** [comment]
Btw, v106 used "SimpleJson" but RestSharp is not a deserialisation library, it allows you using any serialiser you want, but you'd need to configure it in a way it suits your needs.
