### ISSUE TITLE
Strongly Name the assemblies

### ISSUE THREAD

**Issue by geek0x23** [restsharp/RestSharp#216]
Is it possible for you guys to strongly name your assemblies?  I'm looking to use the RestClient within my ActionMailer.Net library, but I can't because it's not strongly named, and my assembly is.  I could distribute my own version, but I'd rather not do that.

Cheers!
Scott

**Comment by brondavies** [comment]
The problem today is that now I have nuget packages that depend on RestSharp and now I can't add any that depend on RestSharpSigned and vice-versa. :sob:
