### ISSUE TITLE
happy-eyeballs

### ISSUE THREAD

**Issue by dongzhaosheng73** [restsharp/RestSharp#2162]
Now that IPV6 addresses are being used more and more, does restsharp have a fallback scheme when ipv6 addresses are not available? As far as I know, there is a happy-eyeballs mechanism. I didn't see a similar problem in the question, so I brought it up to find a similar solution.

**Comment by alexeyzimarev** [comment]
RestSharp is a wrapper of `HttpClient`, it doesn't implement any low-level transport concerns. As soon as Happy Eyeballs is available in `HttpClient`, it will be available for the whole .NET ecosystem, including RestSharp.

You can track and contribute to related issues in the .NET runtime repository, I found at least two:
https://github.com/dotnet/runtime/issues/26177
https://github.com/dotnet/runtime/issues/87932

The second issue indicates that the API was approved, but it doesn't seem to be implemented yet.
