### ISSUE TITLE
Stream content as request content

### ISSUE THREAD

**Issue by khchin93** [restsharp/RestSharp#2167]
I'm frustrated when i am using this library to upload a file to GCP Storage.

RestSharp 110.2.0 do have an method `AddFile(parameterName, getFile, fileName, contentType)`  to supply a IO stream to body. However, RestSharp compose the request into multipart/formdata causes GCP Storage API to write the content into the file.
![image](https://github.com/restsharp/RestSharp/assets/47560427/fbc7942f-b5bd-4770-b781-b9b2b0fed18e)

Using native .NET HttpClient allows me to compose the IO stream as stream content
`
var request = new HttpRequestMessage {
  Content = new StreamContent(sourceFileStream),
};
`
which flawlessly achieved the goal. 

And yes, I understand that using `AddParameter(parameterName, rawByteArray, ParameterType.RequestBody)` can achieve that, but when the byte array is too big, it going to eat up a lot of memory. 

Therefore, allowing passing ContentStream as request content is really important. 

Disclaimer:
I might missing some method in RestSharp to achieve that. Your help is much appreciated

**Comment by alexeyzimarev** [comment]
It has been fixed, maybe not released https://github.com/restsharp/RestSharp/pull/2068
