### ISSUE TITLE
Using this library on a machine with IIS Crypto set to Strict causes "An error occured while sending the request"

### ISSUE THREAD

**Issue by kimboslice99** [restsharp/RestSharp#2171]
As the title says, if you use IIS Crypto and set the template to strict, the following error occurs, with no exception thrown

`An error occured while sending the request`

**Expected behavior**
I would expect an exception to be thrown if a suitable cipher is not found

**Desktop (please complete the following information):**
 - OS: Windows Server 2022
 - .NET version .NET Framework
 - Version 110.2.0

**The relevant piece of code**
```
           using (RestClient client = new RestClient("https://domain.tld/"))
            {
                var request = new RestRequest("path", Method.Get);
                try
                {
                    var restResponse = client.Execute(request);
                    if (restResponse.IsSuccessful)
                    {
                        // do stuff
                    }
                    else
                    {
                        Debug.WriteLine("response not successful " + restResponse.ErrorMessage + " " + restResponse.StatusCode);
                        return true;
                    }
                }
                catch (Exception e)
                {
                    Debug.WriteLine("exception " + e.Message);
                    return false;
                }
            }
```

**Comment by alexeyzimarev** [comment]
The message `An error occured while sending the request` is not produced by RestSharp. RestSharp passes over the HttpClient exception as `response.ErrorException`. If HttpClient doesn't return a proper exception, there's nothing that RestSharp could do.

**Comment by kimboslice99** [comment]
I came back to this after some time and found that HttpClient does in fact provide a more meaningful message and yet RestSharp just returns "An error occured while sending the request"

Here is the exception returned by HttpClient under the same conditions.
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel. 
```
I have since moved away from RestSharp, but I thought it would be worthwhile to update this.

**Comment by alexeyzimarev** [comment]
RestSharp returns the same exception as it uses the HttpClient exception as the `RestResponse.ErrorException` property value. You only needed to inspect the inner exception to understand what the issue was.
