### ISSUE TITLE
User Agent not being set when using the RestOptions class. 110.2.0

### ISSUE THREAD

**Issue by garry-edmonds** [restsharp/RestSharp#2175]
In version 106, setting the UserAgent with the RestClientOptions passes the UserAgent to the API.  But without changing any code and updating to the latest version 110.2.0 it is not sending the entered user agent, instead sending the RestClient and version instead.

Putting the UserAgent back into a header and the user agent is then passed into the requested called API.

What is the correct way to set user agent in version 107+ as documentation does not help, due to different examples depending on what page you read.

**Comment by alexeyzimarev** [comment]
I added a test for setting a custom user agent, and it passes. I can't say for sure what happens in your code, sorry.

https://github.com/restsharp/RestSharp/blob/873ecde6e0a2e22c2ab20085a0b3573a66cebcd5/test/RestSharp.Tests.Integrated/HttpHeadersTests.cs#L66

**Comment by alexeyzimarev** [comment]
Closing due to lack of feedback.
