### ISSUE TITLE
Rely on framework providing STJ

### ISSUE THREAD

**Issue by thompson-tomo** [restsharp/RestSharp#2177]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
The System.Text.Json package becomes conditional so only added for the older frameworks

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by alexeyzimarev** [comment]
I think it was like this before. I don't remember what was the reason to add the dependency explicitly.
