### ISSUE TITLE
Can't remove Accept-Encoding?

### ISSUE THREAD

**Issue by wY1k** [restsharp/RestSharp#2187]
![ssww](https://github.com/restsharp/RestSharp/assets/57378842/2dcbbaac-acd6-485b-bcda-c076e0aa0a47)

 - OS: Win10
 - .NET version .Net8
 - Version 110.2.0

**Comment by alexeyzimarev** [comment]
The header is set by HttpClient by decompression methods property. Maybe, setting it to `None` would help.
