### ISSUE TITLE
Incorrect value of cookie when the cookie has UTF-8 characters

### ISSUE THREAD

**Issue by MSLight** [restsharp/RestSharp#2197]
**Describe the bug**
In response there is some cookie that one of them has Arabic characters but the value of cookie not returned/not saved in CookieContainer correctly and characters become unreadable as question mark or for example: `ÙØÛ ÙØ­¯Û`

**To Reproduce**
```
public static async Task GetName(string username)
{
    var client = new RestClient(new RestClientOptions
    {
        FollowRedirects = false,
        Encoding = Encoding.UTF8
    });
    var request = new RestRequest("https://site.com");
    request.AddQueryParameter("UserName", username);
    RestResponse res = await client.ExecuteAsync(requestotp);

    Data.Name = res.Cookies?["CustomerName"]?.Value; //Problem is HERE. The value has Arabic characters but not received correctly
}
```

**Desktop:**
 - OS: Windows 11 Pro
 - .NET version: .Net Framework 4.6.2
 - Version 110.2.0

**Additional context**
I searched in issues but I cant find any related.

**Comment by alexeyzimarev** [comment]
It would help if you provide the cookie header value.

**Comment by MSLight** [comment]
> It would help if you provide the cookie header value.

Provided in describtion:
> for example: Ù�ØÛ� Ù�Ø­¯Û�

**Comment by alexeyzimarev** [comment]
That's not the header value, that's the cookie value. A cookie header looks like this:

```
CookieName=%D0%92+%D0...%B0%D0%B9; expires=Thu, 11-Sep-2014 19:59:18 GMT; path=/tmp/; domain=.some.domain.
```

When the server works correctly, it should not use non-ASCII characters and encode it.

**Comment by alexeyzimarev** [comment]
Closing due to lack of feedback. Feel free to open it when you can provide the details I asked.
