### ISSUE TITLE
Not found synchronous operations in restclient

### ISSUE THREAD

**Issue by paulocappelli-cit** [restsharp/RestSharp#2198]
In the migration reference for RestClient in version 107 (https://restsharp.dev/v107/#restsharp-v107), it is indicated that synchronous operations have been implemented as extensions, such as ExecuteAsGet and ExecuteAsPost.

However, after updating my project to version 110.2.0, I couldn't find these extensions.

I also noticed that in the "dev" branch, there are extensions for synchronous operations that would suit my needs, see:
https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/RestClient.Extensions.cs
https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/RestClient.Extensions.Get.cs

But in the 110.2.0 tag, I didn't find anything related.

Could someone assist me with how to create a synchronous Get or Post operation?

**To Reproduce**
Install package on version 110.2.0
Net 4.8
Windows 11

**Expected behavior**
Syncronous operations for mantain compatibily

**Stack trace**
N/A

**Additional context**
N/A

**Comment by alexeyzimarev** [comment]
I am sorry but the extensions are there, and all of them are public. I am unable to reproduce the issue, there must be something wrong with the environment you are using.
