### ISSUE TITLE
HttpBasicAuthentication in v111.0.0

### ISSUE THREAD

**Issue by strangetoo** [restsharp/RestSharp#2202]
The latest software release has caused a breaking change in the code. Specifically, the class HttpBasicAuthenticator was renamed to HttpBasicAuth. Additionally, the documentation still references the old class name, leading to potential confusion and errors.

**Comment by m-zanetti** [comment]
+1

> The latest software release has caused a breaking change in the code. Specifically, the class HttpBasicAuthenticator was renamed to HttpBasicAuth. Additionally, the documentation still references the old class name, leading to potential confusion and errors.

**Comment by alexeyzimarev** [comment]
Fixed in 111.1
