### ISSUE TITLE
OAuth1Authenticator Class missing in 111.0.0

### ISSUE THREAD

**Issue by arashberlin** [restsharp/RestSharp#2203]
**Describe the bug**
When I upgrade to the current version of RestSharp , following Classes are missing: OAuth1Authenticator  

**Desktop (please complete the following information):**
 - OS: Windows 11
 - .NET version [NET 8]
 - Version SDK 8.300, 8.0.5

**Additional context**
![23-05-2024_15-50-19](https://github.com/restsharp/RestSharp/assets/12381397/2345b119-6dfc-4dfd-889b-27a5b6c5040e)

![23-05-2024_15-58-34](https://github.com/restsharp/RestSharp/assets/12381397/5e412b28-81f6-4e26-91bf-86cfc29483f0)
![23-05-2024_15-53-39](https://github.com/restsharp/RestSharp/assets/12381397/91b2aede-c964-4d43-8a28-010e5eddfdbb)

**Comment by gunr2171** [comment]
It was renamed to `OAuth1Auth` in #2200.

**Comment by alexeyzimarev** [comment]
Yeah, it wasn't intentional. Not sure how this happened. I will revert it.

**Comment by alexeyzimarev** [comment]
Fixed in 111.1

**Comment by arashberlin** [comment]
Many Thanks
