### ISSUE TITLE
Not sending certificates with request

### ISSUE THREAD

**Issue by Janez-Z** [restsharp/RestSharp#2215]
I am trying to use RestSharp to connect to an ASP.NET web service that requires a certificate for authentication. When debugging the client does not show the certificate anyhwere in the options and the API rejects the request without running any certificate validation code. The certificate is not null when debugging and it is a .p12 file.

Client construction:

```csharp
      public EstClient(string uri, X509Certificate2 certificate)
      {
          var options = new RestClientOptions(uri)
          {
              ClientCertificates = new X509Certificate2Collection(certificate),
              
          };
          HttpClient client = new HttpClient();
          Client = new RestClient(client, options);
      }
```

Test code:

```csharp
   public void GetCaCerts()
   {
       const string uri = "https://localhost:7144/";
       const string filePath = @"certificate path.p12";
       var cert = new X509Certificate2(filePath, "passowrd");
       var privKey=cert.GetECDsaPrivateKey();
       var client = new EstClient(uri, cert);
       client.GetCertificates();
   }
   
        public void GetCertificates()
        {
            var request = new RestRequest(GetEndpoint("cacerts"));

            var result = Client.Get(request); // this is where it crashes

            if (result.StatusCode == HttpStatusCode.OK)
            {
                var certs = CMCHelper.GetCertificates(result.Content);
            }
            else
            {
                throw new Exception(result.StatusCode.ToString());
            }
        }
```

The exceptions i get:

Inner Exception 1:
IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
Inner Exception 2:
SocketException: An established connection was aborted by the software in your host machine.

desktop:
windows 11,
project using .NET 8, RestSharp version 111.1.0

API:
.NET 8, Kestrel

**Comment by Janez-Z** [comment]
Server configuration includes this:

            builder.Services.Configure<KestrelServerOptions>(options =>
            {
                options.ConfigureHttpsDefaults(options =>
                  {
                      options.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                      // options.AllowAnyClientCertificate();

                      options.ClientCertificateValidation = (cert, chain, policyErrors) =>
                      {

                          return true;
                      };
                  });
            });
            
When debugging the API project with swagger i ger prompted for a certificate and ClientCertificateValidation runs. This does not happen using RestSharp.

**Comment by alexeyzimarev** [comment]
When you provide your own instance of `HttpClient`, it won't be configured by RestSharp.
<img width="988" alt="image" src="https://github.com/restsharp/RestSharp/assets/2821205/0f2725ad-7b96-4418-bab3-6a11f18a2270">

This will work:

```csharp
  public EstClient(string uri, X509Certificate2 certificate)
  {
      var options = new RestClientOptions(uri)
      {
          ClientCertificates = new X509Certificate2Collection(certificate),
          
      };
      Client = new RestClient(options);
  }
```

**Comment by Janez-Z** [comment]
Ok, it works now. Thanks
