### ISSUE TITLE
Method in Execute-method new in v111

### ISSUE THREAD

**Issue by bbuehrer** [restsharp/RestSharp#2216]
Why you add the method-parameter in the Execute-method of RestClient in the version 111.0.0?

I add the method before in the new RestRequest and now also in the Execute-method!

```
RestRequest request = new RestRequest( methodName, Method.Get );
RestResponse response = this.restClient.Execute( request, request.Method );
```

In version 110... i have add the method (Sample: Method.Get) only in the new RestRequest!

Why this duplicated change??

**Comment by bbuehrer** [comment]
Yes for me it is a bug.

There would also have to be the “old” Execute method without the “Method”-parameter, which gets the “Method” from the request.

**Comment by alexeyzimarev** [comment]
Yeah, I think it happened by accident. I'll get it back.

**Comment by alexeyzimarev** [comment]
111.2 should be fine

**Comment by lindkj** [comment]
Just pulled into our Dev Branch. No errors on _client.Execute().

Thanks for the quick updates.
