### ISSUE TITLE
Another binary breaking change in Version 108.0.2

### ISSUE THREAD

**Issue by gregmarr** [restsharp/RestSharp#2250]
See #1953 for background, reproduction, context.

I'm not sure if it's worth a 108.0.4 at this point, since 108.0.3 is more than a year and a half old.

**Describe the bug**
The signature of RestClient.Execute changed from `(RestRequest request)` to `(RestRequest request, CancellationToken cancellationToken = default)`.
The same change was made to `RestClient.DownloadStream`.

This happened in this PR:
https://github.com/restsharp/RestSharp/pull/1870
https://github.com/restsharp/RestSharp/commit/cc74f44c926eb04eb08ac8583a27d200e7794c35

**To Reproduce**
Call RestClient.Execute() in an assembly built against 108.0.1, and then run it with 108.0.3.

**Expected behavior**
Everything works.

**Stack trace**
System.MissingMethodException: 'Method not found: 'RestSharp.RestResponse RestSharp.RestClient.Execute(RestSharp.RestRequest)'.'

**Desktop (please complete the following information):**
 - OS: Windows
 - .NET version: .Net 7 or 8
 - Version: 108.0.2

**Comment by alexeyzimarev** [comment]
Yeah, there were some issues with binary compatibility, but I cannot support old versions.

**Comment by gregmarr** [comment]
I figured that was likely the case, but wanted to at least give you the choice, and make the info available to others looking for it.  Also, I had this all written out before I found the first breakage.

Thanks.

**Comment by alexeyzimarev** [comment]
Yes, I get this. I hope people who experienced similar issues can find this one. I also think it was reported before, but I am not sure.
