### ISSUE TITLE
RestRequest post fails v-112. wehre as same is working on 106.

### ISSUE THREAD

**Issue by bindukumari638** [restsharp/RestSharp#2259]
**Remove** all the text above the next line when submitting your issue.

**Describe the bug**
We have upgraded rest sharp to latest stable version 112 and try to generate token through an API by passing client id and secret It is failing. However, if we try to generate similar token using older version of Rest Sharp API(106), works perfectly fine. What change, I need to do in my code snippet to suit the call

**To Reproduce**
var request = new RestRequest();// new RestRequest("api/attachments", Method.Post);
request.Method = Method.POST;
request.Timeout = 800000;//new TimeSpan(800000);
// request.ReadWriteTimeout = 800000;
request.AddHeader("User-Agent", "Mozilla/5.0");
request.AddHeader("Charset", "utf-8");
request.AddHeader("Content-Type", "application/json");
JObject jbody = new JObject();
jbody.Add("client_id", client_id);
jbody.Add("client_secret", client_secret);
jbody.Add("grant_type", "client_credentials");

request.AddParameter("application/json", jbody, ParameterType.RequestBody);

IRestResponse response = client.Execute(request);

**Expected behavior**
API should return a value which is used a token

**Stack trace**
No exception. Response Status code is 0

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - .NET version [e.g. .NET 6]-NET 8
 - Rest Sharp Version [e.g. 112.0.0]

**Additional context**

**Comment by alexeyzimarev** [comment]
I can only suggest to read the documentation.

**Comment by seannybgoode** [comment]
@alexeyzimarev - there is no documentation up on v112

**Comment by alexeyzimarev** [comment]
@seannybgoode this issue is not related to v112. The docs for v111 covers 99% of the current version. The code in the issue uses NewtonsoftJson `JObject` and, of course, it doesn't work. That code won't work in any version since v107.

**Comment by krisgourd** [comment]
Adding link to documentation would be helpful. In which ever version this changed in.

**Comment by alexeyzimarev** [comment]
It's on the front page https://restsharp.dev/migration
