### ISSUE TITLE
When add header "User-Agent" with whitespace value, split headers into 2

### ISSUE THREAD

**Issue by astarte19** [restsharp/RestSharp#2272]
**Bug description**
When I do a RestRequest creation and add a User-Agent header with spaces, it results in a request being sent with 2 User-Agent headers

**Reproduce**

```
return new RestRequest(resource, method)
        .AddHeader(HeaderNames.UserAgent, "Product/Version Foo.Bar");
```

This request sends the following headers:
User-Agent: Product/Version
User-Agent: Foo.Bar

**Expected behavior**
I expected one header with a value "Product/Version Foo.Bar" to be added

**Desktop**
 - OS: Windows 11
 - .NET version .NET 6
 - Version 108.0.1, but in 112.1.0 same

**Comment by alexeyzimarev** [comment]
For headers, space cannot be used inside the value

```
header-field  = field-name ":" OWS field-value OWS
field-value   = *( field-content / obs-fold )
field-content = field-vchar [ 1*( SP / HTAB ) field-vchar ]
field-vchar   = VCHAR / obs-text
```

Normally, header values are also sent unencoded. Apparently, in your case you want to encode the value. The only way to do it in RestSharp is to use `AddParameter(new HeaderParameter("name", "value with space", encode: true))`.
