### ISSUE TITLE
Invalid OAuth1 signature for GET requests

### ISSUE THREAD

**Issue by devatwork** [restsharp/RestSharp#271]
The current implemenation of the OAuth1Authenticator does not generate the signature base string properly for GET parameters causing invalid signatures according to RFC 5849 - The OAuth 1.0 Protocol, http://tools.ietf.org/html/rfc5849#section-3.4.1.

I was able to reproduce this problem using the Vimeo API. There are other people who encountered this problem as well: http://groups.google.com/group/restsharp/browse_thread/thread/43d0163e9e04ea4c.

In the method OAuth1Authenticator.AddOAuthData() the following **if** statement causes the problem.

``` csharp
// for non-GET style requests make sure params are part of oauth signature
if (request.Method != Method.GET && request.Method != Method.DELETE)
```

I will send a test+fix as a pull request as soon as I can.

**Comment by manishk73** [comment]
I would like generate oauth_nonce in my own format instead of using format provided by rest client due to some reason. As OAuthTools and OAuthWorkflow classes are internal, I cannot override behavior easily. How can I achieve this using RestClient
