### ISSUE TITLE
RestSharp ExecuteAsync request isn't correctly detecting aborts in Windows Phone

### ISSUE THREAD

**Issue by pineapplekit** [restsharp/RestSharp#323]
In Windows phone platform, I have added a asyncHandler to a ExecuteAsync request, implemented a timer to act as a timeout control of the request.

After calling abort() method, It isn't detecting aborts correctly, always return "timeout" but not "aborted" in the version 103.1.

Even in the latest version 104.0, it return an null response...

**Comment by alexeyzimarev** [comment]
Sorry guys, no more Windows Phone...
