### ISSUE TITLE
Adding 'gzip' to Header causes an exception on some Windows Phone device.

### ISSUE THREAD

**Issue by pattrawoots** [restsharp/RestSharp#357]
![restsharp-exception](https://f.cloud.github.com/assets/34550/280057/f999ffc0-9145-11e2-8d0d-18c84d7de456.png)

The following are part of my code.

RestClient restClient = new RestClient();
restClient.AddDefaultHeader("Accept-Encoding", "gzip, deflate");
restClient.CookieContainer = new CookieContainer();

RestRequest request = getDefaultRequest();
request.Resource = url;
request.Method = Method.POST;
request.AddParameter("email", username);
request.AddParameter("password", password);

IRestResponse response = await ExecuteTaskAsync(restClient, request);
return deserializeObject<LoginResponse>(response );

The code above works fine on Nokia Lumia 900 (WP7.8) and 920 (WP8), but I later found that it doesn't work on Lumia 710 with WP7.8. The app keeps throwing an exception stating '28591' is not a supported encoding name, unless 'gzip' is removed from the header 'Accept-Encoding'.

Do you have any idea about this?

Attached is the stack trace when the app got the exception.

**Comment by alexeyzimarev** [comment]
Sorry guys, no more Windows Phone...
