### ISSUE TITLE
uppercase/lowercase keys in the serialized JSON

### ISSUE THREAD

**Issue by nilsga** [restsharp/RestSharp#358]
Given the class

``` c#
public class MyClass {
    public string MyField {get;set;}
    public string MyOtherField {get;set;}
}
```

the generated JSON will be 

``` javascript
{"MyField": "field value", "MyOtherField": "other field value"}
```

However, the REST API on the other end of the wire follows another naming convention where the keys are expected to be in lowercase, like 

``` javascript
{"myField": "field value", "myOtherField": "other field value"}
```

Is there an easy way to achieve this without resorting to a custom serializer? It's such a small change that preferrably it would only be a configuration switch somewhere.

**Comment by elvisestevan** [comment]
It was opened a feature-request?

**Comment by hallem** [comment]
it was not.  if this feature is needed then RestSharp gives you the ability to use a custom de/serializer so you'd have to use that for now.
