### ISSUE TITLE
Xamarin.Android (MonoForAndroid) package doesn't work from Nuget Gallery

### ISSUE THREAD

**Issue by ghost** [restsharp/RestSharp#451]
------- Installing...RestSharp 104.3.3 -------
Adding 'RestSharp 104.3.3' to ReduMobile.
Could not install package 'RestSharp 104.3.3'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v4.0.3', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
System.InvalidOperationException: Could not install package 'RestSharp 104.3.3'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v4.0.3', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
   em NuGet.ProjectManager.ExtractPackageFilesToProject(IPackage package)
   em NuGet.ProjectManager.AddPackageReferenceToProject(IPackage package)
   em NuGet.ProjectManager.Execute(PackageOperation operation)
   em NuGet.ProjectManager.Execute(IPackage package, IPackageOperationResolver resolver)
   em NuGet.ProjectManager.AddPackageReference(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   em NuGet.ProjectManager.AddPackageReference(String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   em ICSharpCode.PackageManagement.SharpDevelopPackageManager.AddPackageReference(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   em ICSharpCode.PackageManagement.SharpDevelopPackageManager.InstallPackage(IPackage package, InstallPackageAction installAction)
   em ICSharpCode.PackageManagement.PackageManagementProject.InstallPackage(IPackage package, InstallPackageAction installAction)
   em ICSharpCode.PackageManagement.InstallPackageAction.ExecuteCore()
   em ICSharpCode.PackageManagement.ProcessPackageAction.Execute()
   em ICSharpCode.PackageManagement.PackageActionRunner.Run(IPackageAction action)
   em ICSharpCode.PackageManagement.PackageViewModel.InstallPackage(IEnumerable`1 packageOperations)
   em ICSharpCode.PackageManagement.PackageViewModel.InstallPackage()
   em ICSharpCode.PackageManagement.PackageViewModel.TryInstallingPackage()
==============================
_

Please, update Xamarin.Android (MonoForAndroid) project in Nuget packages :D :D :D :D

**Comment by hallem** [comment]
there is no nuget support for andriod right now

**Comment by hallem** [comment]
just published support for xamarin andriod ios and mono touch in nuget check it out
