### ISSUE TITLE
Cannot Use OAuth Query Parameter Authenticator when Request Resource has Query String

### ISSUE THREAD

**Issue by ghost** [restsharp/RestSharp#453]
When attempting to use RestSharp, we had a URL in our request resource structured like so:
`https://api.github.com/repos/restsharp/RestSharp/commits?sha=master`

This query would fetch the commits of the master branch of the RestSharp repository. We're attempting to fetch commits from another one, using an OAuth token for authentication.

However, the resulting URL when attempting to use the `OAuth2UriQueryParameterAuthenticator` class results in a URL of:

`https://api.github.com/repos/restsharp/RestSharp/commits?sha=master?oauth_token=abc123` (note that there are two `?`'s in the URL)

Our current workaround is to manually append the `oauth_token` query parameter to every request.

**Comment by alexeyzimarev** [comment]
Please provide sample code if you still have this issue, I will close it for now but feel free to reopen.
