### ISSUE TITLE
Add ability to customize Host header

### ISSUE THREAD

**Issue by alxbog** [restsharp/RestSharp#462]
By default the Host header is based on URL provided for the request. In some circumstances it's needed to specify host explicitly. For example, in case of port forwarding we need to specify exact IP address in URL and the Host header should be specified explicitly.

This behavior is supported by **Host** property of **HttpWebRequest** class from .NET 4. But it's not supported by RestSharp yet.

**Comment by cuibty** [comment]
+1

**Comment by chenditc** [comment]
+1
