### ISSUE TITLE
ExecuteTaskAsync null response is causing an unhandled exception

### ISSUE THREAD

**Issue by ghost** [restsharp/RestSharp#466]
I'm testing using my app offline by switching off my server. If I call ExecuteTaskAsync<T> I'm getting an unhandled exception since the server is unavailable and the response is null. 

The error arises in RestClient.Async.cs,

var async = ExecuteAsync<T>(request, (response, _) =>
{
....
});

Would it make sense to handle the case where response is null e.g. 

else if (response == null)
{
    taskCompletionSource.TrySetException(new NullReferenceException());
}

or is there a better way this should be handled ?

**Comment by alexeyzimarev** [comment]
This seems to be fixed by that PR.
