### ISSUE TITLE
RestSharp as a PCL

### ISSUE THREAD

**Issue by ekrapfl** [restsharp/RestSharp#468]
Would it be possible to make a PCL project for RestSharp?  My company uses Xamarin.Android and Xamarin.iOS to develop native apps, and currently we basically have three versions of the same "core" project (one targeted for Xamarin.Android, one for Xamarin.iOS, and one .NET 4 for our unit tests).  This also means that we have all 3 versions of the RestSharp dll (one for each of these projects).  Xamarin recently announced full support for PCLs, which means we could actually take the 2 targeted versions of the "core" project and make it truly one core dll.  However, RestSharp is holding us back in that respect because it is not "PCL-friendly".  I realize that this is a feature request, but it would be absolutely awesome if RestSharp could be compiled as a PCL!

Thanks,
Eben

**Comment by bolikdimon** [comment]
Hello.
I need a way to specify X509 Certificate for my REST requests. Is it a way of doing this?
Thank you very much.
