### ISSUE TITLE
Ability to change culture info for request parameters

### ISSUE THREAD

**Issue by sibbl** [restsharp/RestSharp#496]
I have some doubles which I want to pass as GET parameters. However, they e.g. `50.1` will be sent as `50,1` when using German language.

Whereas I can easily use `ToString` when adding the parameter with `AddParameter` method, it is not so easy when one relies on `AddObject`, like I do.

I use the following code:

```
var client = new RestClient(apiBaseUrl);

var request = new RestRequest(api);
request.RequestFormat = DataFormat.Json;
request.AddObject(data);

//...

```

Where can I change the CultureInfo that RestSharp uses?

**Comment by alexeyzimarev** [comment]
I guess this can be closed since the `CultureInfo` property can be set for any serializer.
