### ISSUE TITLE
I have twilio(.MVC,Twiml,TwilioRestClient etc), restsharp already installed still it shows error.

### ISSUE THREAD

**Issue by neelamchandra03** [restsharp/RestSharp#499]
Hello.

I went to 'manage NeuGet Package' and found that I have twilio(.MVC,Twiml,TwilioRestClient etc), restsharp  already installed into my c# project, still my project is throwing error while rebuilding it.
Error:
The type or namespace name 'Twilio' could not be found (are you missing a using directive or an assembly reference?)    

Please help me out, do I need uninstall and then re-install all?

Thanks,

**Comment by GrandaNet** [comment]
Go to Solution Explorer -> Right Click the Site -> Add Reference

You need to add the Twilio (.dll )

![1](https://cloud.githubusercontent.com/assets/11611324/6778122/7655024a-d126-11e4-84d0-e2cbf59ebb64.png)
