### ISSUE TITLE
RestSharp returns NotFound instead of Service unavailable when server is down

### ISSUE THREAD

**Issue by chobo2** [restsharp/RestSharp#508]
Hi

I have a asp.net web api project and a windows phone 8 project. When I kill my web api and do a request from wp8 I get a 404 back instead of 503.

  private readonly RestClient client = new RestClient(GlobalVariables.ApiUrl);
          var request = new RestRequest("MyController", Method.POST);
                request.AddParameter("UserId", "1");
                request.AddParameter("Name", name.Trim());

```
            var asyncHandle = client.ExecuteAsync(request, response =>
            {
                var status = response.StatusCode;
            });
```

above is my code what I would do. Is this a bug?

**Comment by Luigix75** [comment]
I have the same problem, more or less.
Basically on WP8 (not 8.1) even if the device (the actual one, not the emulator) has no network enabled, every response always has ResponseStatus = Completed (with StatusCode = NotFound)
I would expect ResponseStatus = Error but it doesn't happen.

**Comment by stlin** [comment]
I had the same issue where I can connect to the service using postman, but get notfound when I used RestSharp.  I changed the request url from http to https and it worked even though my service runs on http.
