### ISSUE TITLE
Authenticating to a Oauth 1.0 service on Windows Phone 8 when the Regional Format is set to Hungarian

### ISSUE THREAD

**Issue by Orce5** [restsharp/RestSharp#514]
I am using RestSharp 104.2.0 for WP8. I am using the standard method for Oauth 1.0 authentication and everything works great, except if the Regional Format is set to Hungary on the settings on the phone.

//Start the process by obtaining a request token for the app.

client.Authenticator = OAuth1Authenticator.ForRequestToken(ClientKey, ClientSecret); var request_token = new RestRequest("oauth/request_token", Method.POST);

This code returns a valid token for every situation except for the Hungarian Regional format in the settings on the phone.

**Comment by alexeyzimarev** [comment]
I guess this is only valid now if we can reproduce on a platform different from WP8. Please feel free to re-open the issue if you can do that. Sorry that we were unable to help you back then...
