### ISSUE TITLE
RestSharp.Deserializers.XmlDeserializer: Delay "Value" name check

### ISSUE THREAD

**Issue by patrodyne** [restsharp/RestSharp#520]
In `RestSharp.Deserializers.XmlDeserializer`, the method `GetValueFromXml(XElement root, XName name, PropertyInfo prop)` contains a special use case for the **`Value`** name. The use case occurs before _looking for elements that matches sanitized property name (Order by depth)_. The ordering prevents proper deserialization of simple elements named **`Value`**. For example, an XML representation like this:

```
<Color>
    <Name>Green</Name>
    <Value>255</Value>
</Color>
```

is deserialized to `Value = "Green255"` because the special use case for **`Value`** kicks in too early and uses the parent element as a composite value.

Moving the special logic for **`Value`**  name, works in my case...

```
// try looking for element that matches sanitized property name (Order by depth)
var element = root.Descendants()
    .OrderBy(d => d.Ancestors().Count())
    .FirstOrDefault(d => d.Name.LocalName.RemoveUnderscoresAndDashes() == name.LocalName)
    ?? root.Descendants()
    .OrderBy(d => d.Ancestors().Count())
    .FirstOrDefault(d => d.Name.LocalName.RemoveUnderscoresAndDashes() == name.LocalName.ToLower());

if (element == null)
{
    if (name == "Value".AsNamespaced(name.NamespaceName))
    {
        return root;
    }
}
else
{
    return element;
}
```

**Comment by marcus-eaton** [comment]
I have the same issue but in my case "Value" is an attribute:

` <Engine Id="1" TypeId="1" Name="Joe" Unit="Bloggs" Value="51" />`

Any tips for a work around? (I have no control over the web service's format)
