### ISSUE TITLE
Multipart Form-Data: Cannot POST Serialized Data AND File

### ISSUE THREAD

**Issue by jblacker** [restsharp/RestSharp#524]
I was quite excited to use RestSharp for a project I was working on that required use of a REST API, but unfortunately it turned out that this library could not support what I needed to do.

This API has a feature that allows for uploading of a file along with associated meta data for said file in JSON format.  Since we're pusing both JSON data and binary data it requires the POST call to be encoded as multipart/form-data.  The file needs to be in a 'form-field' named "file" and the serialized JSON data needs to be in a 'form-field' named "data."  When using RestSharp I was able to send the binary file data without issue, and the multipart/form-data encoding looked correct, however the "data" component would not be included when debugging with Fiddler.  I attempted to use both the AddBody(object) method, as well as the AddParameter(name, object, ParameterType.RequestBody) method, but neither was able to handle this properly.  I posted a [SO question](http://stackoverflow.com/questions/22799392/sending-http-post-multipart-form-data-field-using-restsharp) regarding this, but due to lack of response & available information doing research I ended up rolling my own way to handle this.  I have forked the repo and am going to look into how to correct this (or add functionality if it's purposely not including this functionality).  Closed issue #85 is very related to this issue.

**Comment by jjm340** [comment]
This is still a problem, the content type doesn't get filled out when you use the following:
`var uploadReferenceRequest = new
                {
                    assetId = assetId,
                    contentType = "audio"
                };

                IRestRequest request = CreateUpdateRequest("references");
                request.Method = Method.POST;
                
                string name = "----------" + DateTime.Now.ToString(CultureInfo.InvariantCulture);
                request.AddJsonBody(uploadReferenceRequest);
                request.AddFileBytes(name, audioByteData, "file", "application/octet-stream");`

**Comment by jjm340** [comment]
Here is what the request looks like:
`-------------------------------28947758029299
Content-Type: 
Content-Disposition: form-data; name="application/json"

{
  "assetId": "A501483382140958",
  "contentType": "audio"
}
-------------------------------28947758029299
Content-Disposition: form-data; name="----------04/07/2017 16:38:11"; filename="file"
Content-Type: application/octet-stream

ID3
`

Notice the missing content type at the top.  Its oh so close though!!

**Comment by jjm340** [comment]
Got it working, but it was a bit ghetto:

`request.AddParameter("application/json", JsonConvert.SerializeObject(uploadReferenceRequest), "application/json", ParameterType.RequestBody);
 request.AddFileBytes(name, audioByteData, "file", "application/octet-stream");`

It would be nice is AddJsonBody would work as well

**Comment by NomanChali** [comment]
```
RestRequest request = new RestRequest(requestUrl, Method.POST);
            request.AddHeader("authorization", "Basic " + ConnectionObj.authorization);
            request.AddFileBytes("file", fileContent, fileName , "application/octet-stream");

            IRestResponse<AttachmentResponse> response = _client.Execute<AttachmentResponse>(request);
            return response.Data;
```
above code worked for me. Thanks @jjm340

**Comment by aidenZhou** [comment]
@jjm340  I tried your solution but still got error. I am doing : 
                    byte[] data = await file.ReadAsByteArrayAsync();
                    var client = new RestClient("http://localhost:64409/");
                    var request = new RestRequest(urlParm, Method.POST);
                    var projectIds = new List<string>();
                    projectIds.Add("123");
                    projectIds.Add("234");                    
                    request.AddParameter("application/json", JsonConvert.SerializeObject(projectIds), "application/json", ParameterType.RequestBody);
                    request.AddFileBytes("file", data, file.Headers.ContentDisposition.FileName.Replace("\"", string.Empty), "application/octet-stream");
                    
                    var response = client.Execute(request);

I got error in response sth like: Can't bind multiple parameters ('file' and 'projectIds') to the request's content
Can someone tell me how to do this correctly?

**Comment by namilkimfree** [comment]
https://github.com/restsharp/RestSharp/issues/1427#issue-562978260
