### ISSUE TITLE
ExecuteAsync Hangs on Monodroid 

### ISSUE THREAD

**Issue by ces-tr** [restsharp/RestSharp#528]
Aplication hangs just when service is restarted , 
 not when server is running or is stopped,
There is a discussion on google groups about this problem, I dont know if its related to the Android Emulator or not.
https://groups.google.com/forum/#!topic/restsharp/SMl7sBN72xE

var client = new RestClient();
			client.BaseUrl = BaseUrl;
			//client.Authenticator = new HttpBasicAuthenticator(_accountSid, _secretKey);
			//request.AddParameter("AccountSid", _accountSid, ParameterType.UrlSegment);
			try{
				client.ExecuteAsync(request, response =>
				{
						

						try {
							if (response.ResponseStatus == ResponseStatus.Completed) {
								var result = response.Content;
								callbackRespuesta(response);
							} 
						} catch (Exception e) {
							callbackRespuesta(e);
						} 

						});

			}
			catch(Exception e){
				
				callbackRespuesta(e); 

			}

**Comment by hallem** [comment]
should be addressed now
