### ISSUE TITLE
Aborting asynchronous request may lead to WebException

### ISSUE THREAD

**Issue by msairio** [restsharp/RestSharp#531]
The method RequestStreamCallback in https://github.com/restsharp/RestSharp/blob/master/RestSharp/Http.Async.cs may throw a WebException in some circumstances. I ran into this when posting a request with outgoing data in the body and then calling asyncHandler.abort(). 

The documentation http://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.begingetresponse(v=vs.110).aspx for HttpWebRequest seems to confirm that this may happen when calling HttpWebRequest.BeginGetResponse. 

For my needs it was sufficient to add try - catch block around the line ~252 and use similar exception handling as above in the same method:

try
{
    IAsyncResult asyncResult = webRequest.BeginGetResponse(r => ResponseCallback(r, callback), webRequest);
    SetTimeout(asyncResult, _timeoutState);
}
catch (Exception ex2)
{
    // Likely cause for failing here is that the call was aborted previously
    ExecuteCallback(CreateErrorResponse(ex2), callback);
    return;
}

However, I think the proper way to deal with this would be to make async requests aware of having been aborted as someone already mentioned in the issue #323

**Comment by alexeyzimarev** [comment]
I think both are workarounds and the only _right_ way to fix this is to use proper `async` method and a cancellation token. `BeginGetResponse` does not support cancellation.
