### ISSUE TITLE
Cookies are not set during redirect

### ISSUE THREAD

**Issue by jackhftang** [restsharp/RestSharp#545]
I am testing RestSharp with [opera cookies test suite](http://testsuites.opera.com/cookies/) . It seems RestSharp do not handle set-cookie during redirection, and hence all subsequent tests fail.

``` fsharp
let client = new RestClient()
client.CookieContainer <- new System.Net.CookieContainer ()
let req = new RestRequest("http://testsuites.opera.com/cookies/001.php", Method.GET)
let res = client.Execute(req) 
if res.ErrorException <> null then
  printfn "%A" res.ErrorException
else 
  printfn "%s" res.Content
```

**Comment by sherpc** [comment]
At this time bug is still present. Maybe it's a feature?

**Comment by hallem** [comment]
It's not a feature, it's a bug.  I have just not gotten to it yet.

**Comment by kjellski** [comment]
+1 for this fix, don't know how, any advice on how to help here?

**Comment by pashidlos** [comment]
same for me :(

**Comment by RodrigoGroener** [comment]
+1

**Comment by ashw1984** [comment]
+1

**Comment by tuxuser** [comment]
Same issue for me, only a single cookie gets parsed.

Here is some more detailed info:
```cs
RestClient client = new RestClient("https://login.live.com");
RestRequest req = new RestRequest("oauth20_authorize.srf", Method.GET);

req.AddQueryParameter("response_type", "token");
req.AddQueryParameter("scope", "service::user.auth.xboxlive.com::MBI_SSL");
req.AddQueryParameter("redirect_uri", "https://login.live.com/oauth20_desktop.srf");
req.AddQueryParameter("client_id", "0000000048093EE3");
req.AddQueryParameter("display", "touch");
req.AddQueryParameter("locale", "en");

client.FollowRedirects = false;
IRestResponse resp = client.Execute(req);

Debug.Assert(resp.Cookies.Count > 1, "Cookie parsing incomplete");
```

**Returned cookie string**
`Set-Cookie=MSPRequ=lt=<OBFUSCATED>&co=1&id=N; secure= ;path=/;HTTPOnly=;version=1, uaid=<OBFUSCATED>; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1, MSPOK=$uuid-<OBFUSCATED>; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1`

**Expected parsed cookies**
`MSPOK, uaid, MSPRequ`

**Actually parsed cookies**
`MSPRequ`

**Comment by alexeyzimarev** [comment]
It is, unfortunately, how `HttpWebRequest` works.

**Comment by alexeyzimarev** [comment]
@tuxuser if you set `FollowRedirects` to `false`, you will never get to the actual endpoint, so that won't work anyway.

**Comment by alexeyzimarev** [comment]
I added a branch that porentiall can fix the issue, although, to be honest, I think we just need to wait until it is fixed in the .NET Framework. If anyone is willing to test it - please do
https://github.com/restsharp/RestSharp/tree/fix/cookies-redirect

The Opera test suite is no longer available and I have no resources that I know that can help me testing this issue. I am closing it for now.

**Comment by jotzhao** [comment]
how about the issue ? this problem occured on v110.2.0

**Comment by savicarlone1977** [comment]
I think that this is a huge bug. It did no happen with version previous than the breaking-change-107 one. Please fix because there is no any workaround, as far as I know.

**Comment by alexeyzimarev** [comment]
It is a different issue, did you guys look at the date? This issue is from 2019.

**Comment by alexeyzimarev** [comment]
RestSharp doesn't handle redirects currently, it's done by `HttpClient`. The issue to handle redirects inside RestSharp instead is open, and some work has been done there, but it's not complete.
