### ISSUE TITLE
HttpError support

### ISSUE THREAD

**Issue by jacdevos** [restsharp/RestSharp#549]
The standard type for Web API Exceptions a serialized System.Web.Http.HttpError.

It would be nice if RestSharp can automatically populate RestResponse.ErrorException with the serialized HttpError if status is not HTTP status codes 2xx.

This would make consuming API easier.

**Comment by alexeyzimarev** [comment]
It is not easy to figure out that we are speaking to a WebAPI but #774 provided a solution for that.
