### ISSUE TITLE
Get parameter optional encodeing

### ISSUE THREAD

**Issue by digitalgym** [restsharp/RestSharp#550]
Is there a way to prevent url parameters from being encoded? For example `EntryId+Is_equal_to+2` is encode when sent in a GET request. Some API's don't support encoded parameters.

**Comment by vilchinsky** [comment]
The problem getting OData queries work when adding $count, $filter etc. params. The $ symbols gets encoded. It would be nice if user could explicitly specify whether he wants parameter encoded or not.

**Comment by gligoran** [comment]
Optional encoding would be great. I'm trying to communicate with an API that expects a @ in the URL. But when I use RestRequest URL segment, the `@` gets encoded into `%40` and as a result the API call fails.

I'm using .NET 4.6 and RestSharp 105.2.3.

Just to make it clear, this is an external API. [Mailgun, to be specific](https://documentation.mailgun.com/api-mailinglists.html#mailing-lists).

**Comment by SnapPetal** [comment]
I have an api that does not encoded parameters.  Would it be possible to have a flag to skip this.

Example: 
Needs: has_type=eq:online
Sends: has_type=eq%3Bonline

**Comment by arekzaluski** [comment]
Is there any update about this issue? It seems that lots of people are not using RestSharp because of it.

**Comment by alexeyzimarev** [comment]
Use custom encoder `client.UseQueryEncoder` or parameters with type `QueryStringWithoutEncode`
