### ISSUE TITLE
NuGet Support for Xamarin.Android/Xamarin.iOS/Windows Phone 8

### ISSUE THREAD

**Issue by pierceboggan** [restsharp/RestSharp#553]
I would love to use RestSharp in my Xamarin.Android/Xamarin.iOS/Windows Phone 8 projects, particularly with PCLs (where the Xamarin components don't work), but at the moment these platforms aren't supported using the NuGet version.

**Comment by ChicagoDave** [comment]
Any progress on this?

**Comment by hallem** [comment]
Someone just updated the solution files for the current components.  I've not had a chance to get nuget packages together for it yet though.

**Comment by altso** [comment]
As far as I can see, it wasn't included in 105.1 release. Do you have any ETA?

**Comment by hallem** [comment]
It was not.  There is no ETA right now sorry.

**Comment by ravensorb** [comment]
Take a look at PortableRest [https://github.com/AdvancedREI/PortableRest]

**Comment by KraigM** [comment]
You already have the cross platform implementation, now you just need to make the assemblies have all the same name and release all the assemblies in the nuget package.  If you throw in some of @mattleibow's implementation you can be completely pseudo pcl (aka advanced pcl or bait/switch pcl).  https://github.com/mattleibow/RestSharp.Portable

**Comment by KraigM** [comment]
I would be happy to do that for you if you would like.

**Comment by hallem** [comment]
I've got a PR open right now that will solve this.  I'm in the middle of making sure the CI server can handle everything I just did.  Version 105.2.2 is going to be release very shortly with this support.

**Comment by hallem** [comment]
just published the new version with the new targets check it out

**Comment by IlSocio** [comment]
I just tried to install the updated nuget package on a PCL (Profile 259) and got an error:
"Could not install package 'RestSharp 105.2.2'. You are trying to install this package into a project that targets 'portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by hallem** [comment]
right now there is no support for multi-targeting.  you can target wp8, monoandroid, xamarin.ios, and monotouch separately but not at the same time.  there is no support for targeting portable-net45, win, and wpa81 yet.

**Comment by KraigM** [comment]
I just submitted a pull request [https://github.com/restsharp/RestSharp/pull/734] to support Pseudo PCL (aka Advanced PCL or Bait/Switch PCL)

**Comment by IlSocio** [comment]
I'm currently using the Restsharp PCL Branch and it properly works on Profile 259... 
So, you can just use the PCL Branch version to support multi-targeting.
