### ISSUE TITLE
Third Http DELETE request always hangs on .NET CF

### ISSUE THREAD

**Issue by juntek** [restsharp/RestSharp#558]
Calling Http DELETE request three times always results with the 3rd request hangup. 
The issue seems similar to the one described here: http://stackoverflow.com/questions/12799218/httpwebrequest-getrequeststream-hangs-on-multiple-runs

My code is pretty straightforward:

            var request = new RestRequest("{my_resource}", Method.DELETE);
            request.AddUrlSegment("my_resource", resource);

            RestClient client = new RestClient();
            client.Authenticator = new SimpleAuthenticator("uid", login, "pwd", password);
            client.BaseUrl = resourceUrl;

            var response = client.Execute(request);

On my desktop it works fine, prehaps due to the larger connection limit.

**Comment by hallem** [comment]
.net cf is no longer supported
