### ISSUE TITLE
POST request With 301 redirect

### ISSUE THREAD

**Issue by BaptX75** [restsharp/RestSharp#562]
Hi there,

When I want to do a POST request and the server answers "HTTP/1.1 301 Moved Permanently", the next call from the libray is a GET, and it would be a POST.

Any help ?

Best regards,

**Comment by janpieterz** [comment]
I just ran into this and debugged RestSharp to the point of the `System.Net.HttpWebRequest.GetResponse()` call. This is the place where this redirect is handled. 

For more information see https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection.

If you'd like the redirects to persist the HTTP method type a 307 or 308 redirect is needed, the 301 and 302 redirects will not persist the HTTP method on the next bounce.

@hallem seems like it's not a bug in RestSharp!

**Comment by gregmac** [comment]
Note that HttpWebRequest in .NET doesn't support HTTP 308 at all, and so neither does RestSharp.

From the .NET 4.7.1 source (https://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,5683):

* 301 & 302  - All methods are redirected to the same method but POST. POST is redirected to a GET.
* 303 - All methods are redirected to GET
* 307 - All methods are redirected to the same method.

According to this, the _only_ safe way to redirect and preserve the original request method is to use HTTP 307.
