### ISSUE TITLE
Date Header doesn't appear to be added to request

### ISSUE THREAD

**Issue by hellboy81** [restsharp/RestSharp#567]
How do I ensure that the Date header is added to the Request?

And how do I get the value that the Date header will contain?

**Comment by Moerty** [comment]
Yeah, i stuck at the same point.
I add the header with:
`request.AddHeader("Date", formattedDate);`

And i can see the Parameter in the Debugger:
![image](https://cloud.githubusercontent.com/assets/26777372/25181907/5236f9a2-2513-11e7-80f7-bd7a5173b4f8.png)

But in the end, it doesnt show up in my request.
Here is a screen from Fiddler:
![image](https://cloud.githubusercontent.com/assets/26777372/25182022/a5fbae48-2513-11e7-8d53-946cd139b2a7.png)

I have the same problem as this user from stackoverflow: [Link](http://stackoverflow.com/questions/29080778/cannot-add-date-parameter-in-rest-request-rest-sharp)
