### ISSUE TITLE
Can't post a file as request body

### ISSUE THREAD

**Issue by hallem** [restsharp/RestSharp#583]
The only way to post files to a rest endpoint is to use multi-part.  Should be able send a single file as the body and the appropriate content type.

**Comment by TheKrush** [comment]
@hallem that desn't work it takes the byte[] and just turns it into "System.Byte[]" in the actual request

**Comment by hallem** [comment]
@TheKrush interesting.  I've got it working exactly like that in an application I use.  Can you show me a code sample so I can see what you're doing?

**Comment by TheKrush** [comment]
@hallem Yeah I retract my previous statement, I was just informed our version of RestSharp was a year old, I updated it and all worked as expected.
