### ISSUE TITLE
BaseUrl is now manditory

### ISSUE THREAD

**Issue by jt000** [restsharp/RestSharp#606]
In previous versions of RestSharp, I could call the following:

```
var client = new RestClient();
var request = new RestRequest("https://server.com/api/file.json", Method.Post);
client.PostAsync(request, (response, handle) => { ... });
```

However, this now causes an ArgumentNullException at RestSharp\RestClient.cs line 258.

Is this an expected breaking change?

**Comment by tomgallard** [comment]
Just to add- this is a bit of a pain for us. Use case was making a number of callbacks to different users of the Pwinty API. We were reusing a RestClient and just creating a new RestRequest for each one, with the url the client provided (each url on a different domain). 

After this change- these callbacks started failing silently, with no indication that anything needed to be fixed. If a base url is needed- the public parameterless constructor for RestClient should be removed, or it should at least throw an exception if you attempt to make a request without setting baseurl.

**Comment by hallem** [comment]
Tom sorry to hear about the issue. As I said in another issue I'm looking into what can be done to re allow this behavior.  One thing though, it shouldn't fail silently, it should throw a null reference exception. That's how this was found to begin with. Were you suppressing the error somehow by handling it?

---Sent from Boxer | http://getboxer.com

On January 14, 2015 at 2:04:47 AM PST, Tom Gallard <notifications@github.com> wrote:Just to add- this is a bit of a pain for us. Use case was making a number of callbacks to different users of the Pwinty API. We were reusing a RestClient and just creating a new RestRequest for each one, with the url the client provided (each url on a different domain).   After this change- these callbacks started failing silently, with no indication that anything needed to be fixed. If a base url is needed- the public parameterless constructor for RestClient should be removed, or it should at least throw an exception if you attempt to make a request without setting baseurl.  —Reply to this email directly or view it on GitHub.  =

**Comment by tomgallard** [comment]
Hi- I wasn't seeing a NullReferenceException . Sample code here:
```csharp
 var c = new RestClient();
 var req = new RestRequest(callback.TargetUrl, Method.POST);
 ...
 var response = c.Execute(req);
 var success = response.StatusCode == HttpStatusCode.OK;
 if (!success)
 { }
```

This code was returning statuscode == 0 (with an errormessage / errorexception that led me to the problem)

**Comment by hallem** [comment]
Interesting... Either way I'm in the process of changing that behavior so I'm not going to invest too much time in figuring out what happened.

**Comment by jphellemons** [comment]
Isn't this breaking the current DropNet nuget package? http://stackoverflow.com/questions/28324414/get-baseurl-restsharp-error

**Comment by jt000** [comment]
I don't think it was this issue. Instead, it was the changing of BaseUrl from a string to a Uri in commit @b15ee7f60b695e0578b6def7a3e1279b62d6fccd

**Comment by jphellemons** [comment]
it seems to break stuff https://github.com/restsharp/RestSharp/issues/625 or am I wrong? If the commit you mentioned (https://github.com/restsharp/RestSharp/commit/b15ee7f60b695e0578b6def7a3e1279b62d6fccd) will fix this, will it be wrapped in a new release of the nuget package?

**Comment by jt000** [comment]
Just to clarify b15ee7f was the commit that introduced the breaking change in version 105. DropNet was built against 104 (according to the nuspec).

**Comment by ricardovsilva** [comment]
@hallem This fix still under development? Any news?

**Comment by tenbits** [comment]
It seems there are no way to request an endpoint just by a full URL, though `RestClient`  has empty contrustor, but any requests afterwards with absolute uris don't work. 
You must split your URL into partials.
```c#
var uri = new Uri(absoluteUrl);
var origin = uri.GetLeftPart(UriPartial.Authority);
var client = new RestSharp.RestClient(origin);
var req = new RestSharp.RestRequest(uri.PathAndQuery);

var data = client.DownloadData(req);	
```
Really unfriendly api.
