### ISSUE TITLE
CompactFramework Build Issues

### ISSUE THREAD

**Issue by pillakarthik** [restsharp/RestSharp#610]
I pulled the latest version and i am having trouble building the solutions:

Error   1   The type or namespace name 'UriBuilder' could not be found (are you missing a using directive or an assembly reference?)    C:\Users\kpilla\Downloads\RestSharp-master (1)\RestSharp-master\RestSharp\RestClient.cs 258 31  RestSharp.Compact
Error   2   The best overloaded method match for 'string.Join(string, string[])' has some invalid arguments C:\Users\kpilla\Downloads\RestSharp-master (1)\RestSharp-master\RestSharp\RestClient.cs 318 20  RestSharp.Compact
Error   3   Argument '2': cannot convert from 'TResult[]' to 'string[]' C:\Users\kpilla\Downloads\RestSharp-master (1)\RestSharp-master\RestSharp\RestClient.cs 318 37  RestSharp.Compact
Error   4   The type arguments for method 'System.Linq.Enumerable.Select<TSource,TResult>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource,TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.  C:\Users\kpilla\Downloads\RestSharp-master (1)\RestSharp-master\RestSharp\RestClient.cs 318 37  RestSharp.Compact
Error   5   'uint' does not contain a definition for 'TryParse' C:\Users\kpilla\Downloads\RestSharp-master (1)\RestSharp-master\RestSharp\SimpleJson.cs 838 52  RestSharp.Compact

**Comment by orrin** [comment]
Aw :(
So sad to hear you are dropping support for CF 3.5.  Could you confirm which is the last stable version to support it?

**Comment by hallem** [comment]
@orrin I think it's 104.5.  I wish we could support it a little further but between needing VS 2008 to even build it and having the SimpleJson library that RestSharp depends on not support it, it's probably not a good idea.  If I can bring support back for it I'll try but it's a low priority.
