### ISSUE TITLE
Remove support for Compact Framework

### ISSUE THREAD

**Issue by hallem** [restsharp/RestSharp#612]
Unfortunately the SimpleJson library is no longer compatible with the CF 3.5.  Based on this and the face that only VS 2008 supports it, I'm going to start removing it from the code base.

**Comment by renattomachado** [comment]
I forked this repository and I created branch from tag 104.5.0 and I published in my fork.

**Comment by cesarnava** [comment]
Hi.

Excuse me.

Where can I get the binaries, from the latest version that I support CF 3.5?

**Comment by alexeyzimarev** [comment]
@cesarnava install the package from nuget and your IDE should figure out what package version to take.
