### ISSUE TITLE
Switch the unit tests from XUnit.Net to NUnit

### ISSUE THREAD

**Issue by hallem** [restsharp/RestSharp#613]
I've been running into trouble with XUnit.Net so I'm going to be migrating the tests to NUnit

**Comment by issafram** [comment]
Look at PR #658. I tried to fix the string issue you had.

**Comment by hallem** [comment]
Thanks, looks like app veyor still failed for some reason.  I'll look at it when i have a chance or if you don't get to it first

**Comment by issafram** [comment]
@hallem  Yea I added a comment about that one in the PR.  It seems to be an issue with `SimpleServer`.  It is a strange class.  The unit tests that I changed did pass when executed in AppVeyor.  So the change itself is good.  Is there a way to rerun AppVeyor builds?

**Comment by hallem** [comment]
I just told it to rebuild... we'll see how that goes.  I'm not sure if it will update github though.

**Comment by hallem** [comment]
it just finished and it was clear... i'll merge the PR.  Thanks for finding this.

**Comment by hallem** [comment]
closing this now since there's no direct need to do it currently
