### ISSUE TITLE
RestClient with no BaseUri throws a NullReferenceException in the latest version

### ISSUE THREAD

**Issue by echief** [restsharp/RestSharp#619]
Before the latest version, this code was valid

var request = new RestRequest("https://api.twitter.com/oauth/request_token", Method.POST);
var client = new RestClient();
var response = client.Execute(request);

The same code in the latest version throws a NullReferenceException because BaseUri in RestClient object is not set. It'd work only if the code was changed to

var request = new RestRequest("/oauth/request_token", Method.POST);
var client = new RestClient("https://api.twitter.com");
var response = client.Execute(request);

the new update breaks old code and covers less use cases.

**Comment by hallem** [comment]
Great and no problem.  I'm going to create a separate issue to track the feature request.
