### ISSUE TITLE
Per request ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by petekcchen** [restsharp/RestSharp#620]
Currently I use

ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => { return true; }; 

to ignore SSL certificate check, but this is globally configuration, can we have per request setting like

HttpWebRequest request = HttpWebRequest.CreateHttp(url);
request.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => { return true; };

**Comment by hallem** [comment]
I don't immediately see why that would be a problem.  I'll take a look the next time I'm sitting down to code and see what can be done to add this to the request level.  If you're up for taking this on yourself, feel free to submit a pull request.

**Comment by deet** [comment]
I'd like to add another vote for this feature request. It would also be useful for certificate pinning.

**Comment by M3psipax** [comment]
I agree. ServicePointManager is not available for Windows Phone, so there seems to be no way to implement SSL Pinning while using RestSharp without building your own request in addition to the restsharp request. exposing a certificate validation callback would be very handy.

**Comment by dgreenbean** [comment]
I agree this would be really nice.  Unfortunately, the ServerCertificateValidationCallback property on HttpWebRequest is only available as of .NET 4.5.  Only the global property is available before that.  The closest thing I have seen to an acceptable solution for <4.5 is to use a global callback but to only return true for hostname/cert hash combinations that you actually want to trust.  I'm interested to know if someone finds something else though.

**Comment by cogree** [comment]
Curious to know what everyone thinks about having the callback on ```IRestClient``` versus ```IRestRequest```. My pull request reflects the former, but that is only because we dependency inject ```IRestClient``` with a base url, so attaching the certificate pinning callback there makes sense.

**Comment by M3psipax** [comment]
To be frank: I agree. It's perfectly logical for that callback to reside in IRestClient.
Quick question: Does your implementation work for Windows Phone?

**Comment by cogree** [comment]
@M3psipax My pull request does not include support for .NET 3.5, Silverlight, or Windows Phone.
