### ISSUE TITLE
Nuget PCL Problem

### ISSUE THREAD

**Issue by angelcalvasp** [restsharp/RestSharp#621]
I am getting an error while adding Restsharpo client I get 

Could not install package 'RestSharp 105.0.1'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Will there be a PCL compatible Restsharp Client?

**Comment by hallem** [comment]
there is one.  there just isn't a nuget package for it.  there is a portable branch in the source code currently that is/should be compatible.  I have not updated this yet as it is beyond my expertise.  I will get to it at some point.
