### ISSUE TITLE
Package doesn't target MonoAndroid, Version=v5.0

### ISSUE THREAD

**Issue by rmtuckerphx** [restsharp/RestSharp#623]
This is the NuGet error I get when trying to install RestSharp 105.0.1:

Installing 'RestSharp 105.0.1'.
Successfully installed 'RestSharp 105.0.1'.
Adding 'RestSharp 105.0.1' to iotree.
Uninstalling 'RestSharp 105.0.1'.
Successfully uninstalled 'RestSharp 105.0.1'.
Install failed. Rolling back...
Could not install package 'RestSharp 105.0.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by hallem** [comment]
The nuget package doesn't support the PCL or the Mono frameworks.  You need to clone the repo and compile it yourself for right now.

**Comment by vasundharab** [comment]
You can install it form the xamarin component store

**Comment by hallem** [comment]
just published a version that targets mono android (xamarin) to nuget
