### ISSUE TITLE
1.4.5.0 Broke Windows Phone 7.1 compatibility

### ISSUE THREAD

**Issue by vvolkgang** [restsharp/RestSharp#624]
The latest version of RestSharp can't be used in WP7.1, because the .dll is being compiled for WP8.0 since version 1.4.5.0.

Commit: https://github.com/restsharp/RestSharp/commit/9f5558f0bf54b62dddcfdb65ebbd4047021d2a2a

To solve this you'll need to have different projects, one for wp7.1 and other for wp8 because there's a lot of breaking changes, for instance, 7.1 needs AsyncCtpLibrary_Phone for async support.

Now that was a fun wild-goose chasing! (not)

**Comment by hallem** [comment]
That's correct, it did. I'll see if I can get the 7.1 capability restored but if you'd like to submit a pull request for it, that would be great.

**Comment by hallem** [comment]
windows phone 7.1 is no longer supported by windows 8/10 or vs 2013/2015 which is my dev environment.  so the library will not receive support for this.

**Comment by vvolkgang** [comment]
Fair enough. In this day and age I think it's fare to assume that "ain't nobody got time" for WP7.1, for the few brave ones that do or need, you can always leave a note in a compatibility page stating the last commit where it was still usable.
