### ISSUE TITLE
Make BaseUrl not required

### ISSUE THREAD

**Issue by hallem** [restsharp/RestSharp#625]
When the BaseUrl was changed to be a URI it also became a required field.  While it exposed a hole in the original logic, it also brought up a different use case for the library.  I'm going to take a look and see what can be done to make this an optional field, but if it's not there, then the request URL has to be fully qualified.  Using this for tracking the feature request.

**Comment by tomgallard** [comment]
Agree this would be useful. Or at least throw an exception if BaseUrl not supplied. Perhaps remove public paramaterless constructor for RestClient if we are going to require a BaseUrl - this will at least cause a compile time error for people when they upgrade, rather than run time issues.

**Comment by janhartmann** [comment]
I would agree on making BaseUrl optional. Currently writing REST request against multiple sites and using dependency injection to inject the `RestClient` with a preconfigured base url. 

This url is used for like 10 specific calls, and then I have 4 calls which has to call some other base urls. Any suggestion to come around this? 

Quick suggest is making `new RestRequest("http://anoterBaseUrl.com/trades/")` override the base url as it contains a "new url".

Let me know ;-)

**Comment by BrutalSimplicity** [comment]
For anyone who stumbles upon this really annoying configuration. Check this out. I think this would be nice to even have as an example in your Wiki.

http://www.hackered.co.uk/articles/restsharp-and-the-factory-pattern-you-really-should

**Comment by alexeyzimarev** [comment]
> dependency injection to inject the RestClient 

This is actually not a good design. You should not inject the `IRestClient`. Instead, you should create your own abstraction for the client of a service you are calling. This will allow you to make more efficient testing and also replacing the client implementation without having to change all the usages.

To be honest, I doubt that this issue is valid.

**Comment by beppe9000** [comment]
I think this is to be implemented to give more flexibility. (Who wants to make another client for a single request -_-).

**Comment by danm-de** [comment]
I did an upgrade from version 104.4.0 to 106.3.1 and was not able to spot this breaking change. Even though the _release notes_ for 105.0.0 mention a change - I did not realize that ``RestClient.BaseUrl`` is now mandatory.
>  Converted the BaseUrl to be a URI rather than a string (potential breaking change)

I like @tomgallard's proposal to **remove the parameterless public constructor**.

**Comment by alexeyzimarev** [comment]
Despite getting downvotes, I insist that injecting the `IRestClient` _is_ a bad design. Read about ports and adapters, people. The idea of having the client is for it to be specific for a certain API base. You configure it for the specific needs. You can just as well create a new instance of the client every time instead of injecting it. The obsession and overall misuse of DI containers is just amazing.

**Comment by alexeyzimarev** [comment]
@beppe9000 I was not talking about creating a client for each request.

Instead of using like
```csharp
public class MyController : Controller
{
    public MyController(IRestClient client)
    {
         _client = client;
    }

    public Something Call(int blah)
    {
        var request = new RestRequest(AppSetting["someurl")).AddParameter("blah", blah);
        return client.Get<Something>(request);
    }
}
```

people should be really understanding what interfaces are for:

```csharp
public interface IMyApiClient
{
    Something GetSomething(int blah);
}

public class MyApiClient : IMyApiClient
{
    private RestClient _client;

    public MyApiClient(string apiUrl) => _client = new RestClient(apiUrl);

    public Something GetSomething(int blah)
    {
        var request = new RestRequest("/something").AddQueryParameter("blah", blah);
        return _client.Get<Something>(request);
    }
}

public class MyController : Controller
{
    private readonly IMyApiClient _apiClient;
    
    public MyController(IMyApiClient apiClient) => _apiClient = apiClient;

    public Something Call(int blah) => _apiClient.GetSomething(blah);
}
```

How the hell a class that depends on `IRestInterface` can even be tested? Moq all the things? Madness...

**Comment by tstivers1990** [comment]
@alexeyzimarev And how, exactly, do you propose someone unit test their wrapper if they aren't using DI to inject `IRestClient` at runtime?
