### ISSUE TITLE
Signed assemblies

### ISSUE THREAD

**Issue by lewisbass** [restsharp/RestSharp#627]
I need signed assemblies in order to use RestSharp. I am getting the error:

Assembly generation failed -- Referenced assembly 'RestSharp' does not have a strong name

**Comment by propagated** [comment]
In nuget there is a decently recent version of RestSharp called RestSharpSigned. Use that instead.

**Comment by hallem** [comment]
@lewisbass @propagated is right.  There is a project on nuget called RestSharpSigned.  I actually maintain that now so it's the same version as the non-signed one.  Both come from the same code base.

**Comment by lewisbass** [comment]
Thank you!

**Comment by clarkd** [comment]
Thank you, thank you, thank you.
