### ISSUE TITLE
DateFormat property ignored when serialising JSON

### ISSUE THREAD

**Issue by spamguy** [restsharp/RestSharp#629]
I have a C# object with both a DateTime and a DateTime?. I need to send this object serialised as JSON to an API that flips out if I send DateTimes in the default format. So, I wrote:

```
RestRequest request = new RestRequest("the/api/path", Method.POST);
request.JsonSerializer = new JsonSerializer { DateFormat = "yyyy-MM-dd" };
request.DateFormat = "yyyy-MM-dd";
request.AddJsonBody(new List<Person> { person });
```

Note multiple approaches to supplying a date format. When I inspect the generated JSON, the formatting has not changed and the API call fails because of it:

```
[{"BirthDate":"1998-06-02T05:00:00Z","AdmissionDate":"2012-10-01T05:00:00Z"}]
```

If I have to I will change the property to be a string, but using a formatted date would be preferable.

**Comment by kondaskondas** [comment]
Have you checked the tests?, https://github.com/restsharp/RestSharp/blob/master/RestSharp.Tests/JsonTests.cs there's a method covering that case: Can_Deserialize_Custom_Formatted_Date

**Comment by hallem** [comment]
@spamguy I've gone over the code and there currently isn't support for custom serialization for DateTime.  The property on the JsonSerializer is ignored and has a summary comment to this effect.  My initial findings is that this isn't directly supported by SimpleJson which is the default JSON serializer.  If this is a feature you need, I'd suggest using JSON.NET for your de/serialization needs.  If you need a code sample on how to do that please let me know and I'll provide one.

**Comment by karlafortes** [comment]
oi
