### ISSUE TITLE
The best way to send binary data without using a multipart content type

### ISSUE THREAD

**Issue by hellboy81** [restsharp/RestSharp#630]
Can RestSharp send binary data without using a multipart content type?

See also [stackoverflow question](http://stackoverflow.com/questions/10158977/can-restsharp-send-binary-data-without-using-a-multipart-content-type)

**Comment by hallem** [comment]
Yes, currently it's not that intuitive but here's a gist that shows you how: https://gist.github.com/hallem/5faaa6bebde50641e928
