### ISSUE TITLE
Deserialize response to list with custom class name

### ISSUE THREAD

**Issue by qbunia** [restsharp/RestSharp#631]
Hello,
The issue looks like this: 
I get response from Rest service:
  `<api>`
`    <contractors>`
`        <contractor>`
   `           <id>4091809</id>`
       `       <value />`
   `     </contractor>`
  `  </contractors> `
`   </api>`

I like to map this response to:
var response = client.Execute<List<Contractor>>(request);

Nomatter how I tried various options using json or xml, or DeserializeAs (place above Contractor class with Name="contractor", also didnt work) attribute it didnt work. The type to which RestSharp deserialize has to be the same name as <contractor>. I used workaround like that:

    public class ContractorEntities
    {
        public List<ContractorEntity> Contractors { get; set; }
    }

    public class ContractorEntity
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }
This works, but I have to create additional class for container. Is it possible to make it work without having to create additinal container?

**Comment by hallem** [comment]
It looks like part of your message got cut off.  What was the "var response" line supposed to be?

**Comment by hallem** [comment]
so the short answer is no it wont be possible without the container
