### ISSUE TITLE
After executing a request, changing the request parameters then executing again executes the first request again

### ISSUE THREAD

**Issue by drgrieve** [restsharp/RestSharp#640]
I'm expecting the second request when execute to run the changed request.

As a workaround I'm copying the request parameters to a new request instance and executing the clone.

I'm I doing something wrong or is this a bug or intended?

**Comment by hallem** [comment]
Can you provide some sample code that demonstrates the issue you're having please?

**Comment by issafram** [comment]
@drgrieve, I added a unit test to try to recreate your issue located at f22350b11025274af8555edaf6303aa6b27e1f13.  The unit test passes so I can not recreate your scenario.  Maybe you can provide some more detail?

**Comment by hallem** [comment]
closed due to no response
