### ISSUE TITLE
Problem with deserialization of DateTime with milliseconds part

### ISSUE THREAD

**Issue by DominikPalo** [restsharp/RestSharp#643]
RestSharp internal Json deserializer cannot handle DateTime format with milliseconds part (e.g. "2014-10-13T22:11:10.000Z") which is used in lot of APIs ("2014-10-13T22:11:10Z" works ok, but "2014-10-13T22:11:10.000Z" causes throwing of DateTime parse exception).

```
System.FormatException occurred
Message: A first chance exception of type 'System.FormatException' occurred in mscorlib.dll
Additional information: Input string was not in a correct format.
```

**Comment by qujck** [comment]
Support here is lame.

Have you seen `RestRequest.DateFormat` as described [here](https://github.com/restsharp/RestSharp/wiki/Deserialization#jsondeserializer-3)

**Comment by hallem** [comment]
@DominikPalo I'll take a look at this sometime this week.  In the meantime the general recommendation is to use a different deserializer if the built in one doesn't have the support you need.  We're fairly limited on what we can change and do with it as it's a library we depend on.  I'd suggest using the JSON.NET library.  If you need a code sample on how to use that with RestSharp let me know and I'd be happy to provide one.

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
