### ISSUE TITLE
Azure WebApi HMAC authentication

### ISSUE THREAD

**Issue by freeubi** [restsharp/RestSharp#645]
Hello,

on a windowsphone project i use restsharp to connect Ftibit api. Its working perfectly.

Now i put the same code on Azure WebApi, and i got an error:
{"errors":[{"errorType":"oauth","fieldName":"oauth_signature_method","message":"Invalid signature method: HMACSHA1. Fitbit API currently supports: HMAC-SHA1"}],"success":false}

Im useing OAuth1Authenticator.ForProtectedResource(...)

I contacted with the Fitbit support, and it seems they only accept HMAC-SHA1, but the RestSharp sending without "-".

**Comment by fubar-coder** [comment]
That's strange, as this should work, because the ```oauth_signature_method``` will be set to ```SignatureMethod.ToRequestValue()```, which adds a ```-``` before the SHA1.
