### ISSUE TITLE
DeserializeAs not working with nested JSON

### ISSUE THREAD

**Issue by dprus** [restsharp/RestSharp#647]
Here's the relevant piece of JSON:

``` javascript
{
   "data":{
      "offeset":0,
      "tasks":[
         {
            "additional":{
               "detail":{
                  "connected_leechers":1,
                  "connected_seeders":0,
                  "create_time":"1425189943",
                  "destination":"Downloads/Torrents/Complete",
                  "priority":"auto",
```

Here are the classes I'm having RestSharp deserialize the JSON to:

``` cs
    public class DownloadStationResponse
    {
        public bool Success { get; set; }
        public Dictionary<string, string> Error { get; set; }
    }

    public class DownloadStationListResponse : DownloadStationResponse
    {
        public ListDataClass Data { get; set; }
    }

    public class ListDataClass
    {
        public int Total { get; set; }
        [DeserializeAs(Name = "offeset")] // Current version of DSM has a bug where this is misspelled. See: http://forum.synology.com/enu/viewtopic.php?f=223&t=97677
        public int Offset { get; set; }
        public List<DownloadTaskClass> Tasks { get; set; }
    }

    public class DownloadTaskClass
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string Username { get; set; }
        public string Title { get; set; }
        public long Size { get; set; }
        public string Status { get; set; }
        public DownloadAdditionalClass Additional { get; set; }
    }

    public class DownloadAdditionalClass
    {
        public DownloadDetailClass Detail { get; set; }
    }

    public class DownloadDetailClass
    {
        [DeserializeAs(Name = "connected_leechers")]
        public int ConnectedLeechers { get; set; }
        public string connected_seeders { get; set; }
        public long create_time { get; set; }
        public string Destination { get; set; }
        public string Priority { get; set; }
        public int TotalPeers { get; set; }
        public string Uri { get; set; }
    }
```

The issue is that after this gets deserialized from JSON the instance of DownloadDetailClass has properly initialized "create_time" however the ConnectedLeechers property is not even though I have used "DeserializeAs". In fact, from what I know about RestSharp deserialization I shouldn't even have to use DeserializeAs because it already tries to do things like adding underscores, etc.

Note also that if I rename the "create_time" property to CreateTime deserialization breaks. It shouldn't. Using DeserializeAs CreateTime (Name = "create_time") also doesn't work. But create_time works fine.

The reason I think this has something to do with the nesting is because the DeserializeAs I used on Offset in the ListDataClass works perfectly.

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
