### ISSUE TITLE
Different requests cookie issue

### ISSUE THREAD

**Issue by eapolunin** [restsharp/RestSharp#649]
If you create RestClient once and call Execute with one RestRequest that have Cookie header for example 'key=123' and then call execute with same RestClient and another RestRequest with Cookie 'key=321' client will not use new cookie value. Reason is in oldCookie newCookie filtering when create HttpMessageHandler in DefaultHttpClientFactory.

**Comment by hallem** [comment]
Your reason isn't clear.  If you found the issue can you provide more detail on where it is?

**Comment by eapolunin** [comment]
RestClient client = new RestClient();
RestRequest request = new RestRequest("test", HttpMethod.Post);
request.AddParameter("testCookie", "123",
                    ParameterType.Cookie);
await client.Execute(request); // ok header will be "Cookie : testCookie=123"

RestRequest request2 = new RestRequest("test", HttpMethod.Post);
request2.AddParameter("testCookie", "321",
                    ParameterType.Cookie); 
await client.Execute(request2); //not ok, header will be "Cookie : testCookie=123"
So, if one client executes two request and each of them have cookie param with same name but different values, client will use first cookie value in both requests

**Comment by eapolunin** [comment]
foreach (var cookieParameter in request.Parameters.Where(x => x.Type == ParameterType.Cookie && !oldCookies.ContainsKey(x.Name)))
                newCookies.Add(baseUrl, new Cookie(cookieParameter.Name, string.Format("{0}", cookieParameter.Value)));

 !oldCookies.ContainsKey(x.Name))) ->  problem, need to refresh oldcookies if same already exist

**Comment by alexeyzimarev** [comment]
I think this should be gone, the RestClient doesn't store anything now.
