### ISSUE TITLE
Headers Changed Using Patch

### ISSUE THREAD

**Issue by jaimes0812** [restsharp/RestSharp#650]
Currently using version 104.4.0.
request.Method = Method.PATCH;
request.AddHeader("Accept", "application/json");
request.AddHeader("Content-Type", "application/json");

the following is being sent...
Accept: text/html, application/xhtml+xml, */*
Content-Type: application/x-www-form-urlencoded

**Comment by fubar-coder** [comment]
You probably need to perform the following steps:

1. Remove all deserializers and just add the JSON deserializer with ```application/json``` mime type
2. Add the body using "AddBody" while using the JSON serializer for serialization of the body

**Comment by hallem** [comment]
@jaimes0812 did the above steps solve the problem?

**Comment by hallem** [comment]
closed due to no response

**Comment by jaimes0812** [comment]
I apologize for the lack in response.  My job responsibilities has taken me
onto other things and I have not been able to complete this.
