### ISSUE TITLE
No support for NET 4.5.1?

### ISSUE THREAD

**Issue by crea7or** [restsharp/RestSharp#651]
Trying to add RestSharp to Windows Universal app and getting this error:
`Install-Package : Could not install package 'RestSharp 105.0.1'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by hallem** [comment]
I'll see what I can do to get the target added soon

**Comment by hallem** [comment]
i just added the targeting to the source code... it will go out with the next nuget push which should be soon
