### ISSUE TITLE
OAuth1Authenticator duplicates OAuth Authorization parameter on second attempt

### ISSUE THREAD

**Issue by vk5880** [restsharp/RestSharp#655]
Second attempt of RestRequest using OAuth1Authenticator duplicates OAuth Authorization Parameter in request and produce duplicated header

```
var restClient = new RestClient
        {
            BaseUrl = new Uri(_configuration.Endpoint),
            Authenticator = OAuth1Authenticator.ForProtectedResource(_configuration.ConsumerKey, _configuration.ConsumerSecret, _accessToken, _accessSecret)
        };

var response = restClient.Execute<T>(request);
```

Second request:
GET [url] HTTP/1.1
Authorization: OAuth oauth_consumer_key="_",oauth_nonce="_",oauth_signature="_",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1426695689",oauth_token="_",oauth_version="1.0",OAuth oauth_consumer_key="_",oauth_nonce="_",oauth_signature="_",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1426695689",oauth_token="_",oauth_version="1.0"
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/105.0.1.0
Host: [host]
Accept-Encoding: gzip, deflate

**Comment by alexeyzimarev** [comment]
Yeah, we used to mutate the parameters collection, but it is now fixed.
