### ISSUE TITLE
Support for SimpleJson DynamicObject

### ISSUE THREAD

**Issue by BrianGenisio** [restsharp/RestSharp#662]
SimpleJson supports the ability to use [dynamic dispatching](https://github.com/facebook-csharp-sdk/simple-json/search?utf8=%E2%9C%93&q=SIMPLE_JSON_DYNAMIC), but it is turned off for RestSharp.  It uses a `#define SIMPLE_JSON_DYNAMIC` directive and it makes `JsonObject` play well with dynamic.

For example, I'd like to do this:

```js
dynamic data = client.ExecuteDynamic(request).Data;
var name = data.Name;
```

Is there a reason this compile flag has not been enabled?

**Comment by hallem** [comment]
I can't see why not.  I'll enable this and run some tests.  As long as things go ok I'll get it enabled for the next release.

**Comment by hallem** [comment]
this has been added
