### ISSUE TITLE
JSON Deserializer should always check for exact name match before checking name variants

### ISSUE THREAD

**Issue by drbenschmidt** [restsharp/RestSharp#667]
While working on deserializing some responses from an API using OData 3.0, I noticed that the `DeserializeAs` attribute still wasn't enough to bring back the `odata.*` attributes.

The current Map function in the `JsonDeserializer` should check to see if a name exists as is in the data-value dictionary before attempting to find any of the other name variations. This shouldn't break any existing implementations (that I can think of) and enable people to directly map to objects without having their name split on the period. If it does break some compatibility (say the original intent of this object was to map properties to deeper properties in the object) then another parameter should be added to the `DeserializeAs` attribute to denote either of the actions - or perhaps we could reuse the `Attribute` property? (Not sure exactly what that's used for yet.)

**Comment by hallem** [comment]
Can you give me an example of how this is causing an issue for you?  I do agree though that the deserializer should check for an exact match first.

**Comment by vilchinsky** [comment]
An example of the issue. You can request to include count value of collection from odata endpoint. The count value from request will be contained in "@odata.count" property (which is a single property but not nested one)

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
