### ISSUE TITLE
This property cannot be set after writing has started.

### ISSUE THREAD

**Issue by DumboJet** [restsharp/RestSharp#672]
This has been reported again, but it still happens:

```
This property cannot be set after writing has started.

   at System.Net.HttpWebRequest.set_ContentLength(Int64 value)
   at RestSharp.Http.WriteRequestBody(HttpWebRequest webRequest) in c:\Users\user\Desktop\RestSharp\RestSharp-master\RestSharp\Http.Sync.cs:line 241
   at RestSharp.Http.PostPutInternal(String method) in c:\Users\user\Desktop\RestSharp\RestSharp-master\RestSharp\Http.Sync.cs:line 146
   at RestSharp.Http.AsPost(String httpMethod) in c:\Users\user\Desktop\RestSharp\RestSharp-master\RestSharp\Http.Sync.cs:line 122
   at RestSharp.RestClient.DoExecuteAsPost(IHttp http, String method) in c:\Users\user\Desktop\RestSharp\RestSharp-master\RestSharp\RestClient.Sync.cs:line 90
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse) in c:\Users\user\Desktop\RestSharp\RestSharp-master\RestSharp\RestClient.Sync.cs:line 68
```

Code:

```
			var client = new RestClient("http://my.wp-server.gr/");

			string _auth = string.Format("{0}:{1}", "username", "pass");
			string _enc = Convert.ToBase64String(Encoding.ASCII.GetBytes(_auth));
			string _cred = string.Format("{0} {1}", "Basic", _enc);

			Parameter location = new Parameter() { Value = "http://www.google.com/" };
			IRestResponse response;
			RestRequest request;
			request = new RestRequest("?json_route=/posts")
				          {
					          AlwaysMultipartFormData = true,
					          //RequestFormat = DataFormat.Json,
					          Method = Method.POST,
				          };
			request.AddParameter("title", "Booooooooooooooooo!", ParameterType.RequestBody);
			request.AddParameter("content_raw", "Bodoooooooooooooooo! <a href=\"" + location.Value + "\">File</a>", ParameterType.RequestBody);
			request.AddParameter("date", DateTime.UtcNow, ParameterType.RequestBody);
			request.AddParameter("author", 1, ParameterType.RequestBody);
			request.AddParameter("status", "publish", ParameterType.RequestBody);
			request.AddHeader("Accept", "application/json");
			request.AddHeader("Authorization", _cred);

			response = client.Execute(request);
			if (response.StatusCode != System.Net.HttpStatusCode.Created)
			{
				throw new Exception("The freaking post POST at WP has failed!");
			}
```

Also, it might be good to let the exception propagate outside the library for handling.

Thanks! :)

**Comment by DumboJet** [comment]
This goes away when removing `AlwaysMultipartFormData`.

**Comment by issafram** [comment]
I added unit tests for this issue in a branch at ac24d7be4ac3f8f2258c61785c83636592a304e8.

`ExecuteAsync` seems to work fine, while `Execute` does not.

Confirmed bug.

I tried looking into it.

The codebase seems to have many differences between `Http.Sync.cs` and `Http.Async.cs`.

It is not trivial to figure out.

@hallem, would you know more about this?

**Comment by hallem** [comment]
Off the top of my head no.  I'm just waiting for some time to free up so I can look into it myself unless you want to take it on @issafram

**Comment by issafram** [comment]
@hallem, I'll try looking into it a bit more in the next couple of days,  but I guess I need some more background on why Sync and Async are so different?  I would think that the processing logic should be the exact same (same method) but just called from sync/async methods.  We seem to have alot of the same logic copied over into both classes.

**Comment by issafram** [comment]
@hallem, take a look at commit ede74573f5d6ae1d9eceeeb268149c540d02a860.  I *think* that I have resolved this issue.  All unit tests now pass including the ones I added for this specific issue.

I changed some of the internals of `WriteRequestBody` so I would feel better if you took a look at it.

If everything looks good, I can put in a PR.

**Comment by hallem** [comment]
@issafram it looks good to me.  send over the pr and i'll get it in.

**Comment by hallem** [comment]
just make sure you tag this issue in the PR so it gets closed. let me know if you don't know how

**Comment by issafram** [comment]
@hallem Doing that now.  Thanks for having some free time!  Love this project
