### ISSUE TITLE
Please update nuget package

### ISSUE THREAD

**Issue by jakejgordon** [restsharp/RestSharp#679]
It looks like nuget is getting pretty outdated. I'd love to use the new FollowRedirects property but it isn't on the latest Nuget version. Can someone push out the latest version? Thanks!

https://www.nuget.org/packages/RestSharp

**Comment by garyjohnson** [comment]
+1 on this. I need to mock DownloadData but it only recently got added to the IRestClient interface.

**Comment by hallem** [comment]
Done.  Sorry this took so long.
