### ISSUE TITLE
MissingMethodException on AddFile(string, byte[], string, string = null)

### ISSUE THREAD

**Issue by gregsdennis** [restsharp/RestSharp#688]
When attempting to add a file via byte array and leaving the last parameter to default to `null`, I get the subject error.  My usage is:

    request.AddFile(parameter.Key, rf.ContentBytes, rf.FileName);

I reflected the downloaded assembly (using ILSpy) and the method is shown, and it even has the default value on the last parameter.

I upgraded from v104.4.0 to 105.1.0.  Is there some change that's not appearing in the disassembly?

**Comment by gregsdennis** [comment]
Oh, this appears to be for .Net 4.5.1 only.

**Comment by hallem** [comment]
There was recent support for 4.5.x it's possible there are some symbols missing.  I'll take a look.   But it sounds like this isn't an issue so I'll close this out.

**Comment by gregsdennis** [comment]
How recent was this support?  I encountered this issue downloading the latest today.

How is this not an issue?  I can't run my code.
