### ISSUE TITLE
Deserialize random objects 

### ISSUE THREAD

**Issue by eugenekgn** [restsharp/RestSharp#689]
How can I deserialize something like this
{
  "001": {
            "epubdate": "",
            "source": "Anaesthesiol Reanim",
            "authors": [{}]
   },
   "002": {
            "epubdate": "",
            "source": "Anaesthesiol Reanim",
            "authors": [{}]
   }
 }

**Comment by hallem** [comment]
That's a dictionary.  I'd start there.
