### ISSUE TITLE
MissingMethodException on AddFile(string, byte[], string, string = null)

### ISSUE THREAD

**Issue by gregsdennis** [restsharp/RestSharp#690]
*NOTE* This was opened as an [issue](https://github.com/restsharp/RestSharp/issues/688) previously, but dismissed as resolved.  This is **not** resolved.  I cannot run my code and neither can my clients.

When attempting to add a file via byte array and leaving the last parameter to default to null, I get the subject error. My usage is:

    request.AddFile(parameter.Key, rf.ContentBytes, rf.FileName);

I reflected the downloaded assembly (using ILSpy) and the method is shown, and it even has the default value on the last parameter, however the error remains.

I upgraded from v104.4.0 to 105.1.0. Is there some change that's not appearing in the disassembly?

This only affects .Net versions 4.5+.

**Comment by hallem** [comment]
@gregsdennis I'm sorry but it sounded like on the previous issue that you had a workaround so I made a note of it for myself to look into and closed the issue.  To get yourself working, change the reference to RestSharp to use the .NET 4.0 version of the library rather than the 4.5+ version.

Also, you can reopen an issue at any time so there is no need to create a second one.

Lastly, please remember that this is an open source project that I maintain in my free time.

**Comment by gregsdennis** [comment]
My code is in a Nuget package (also open source, maintained in my free time) which is being referenced by a client.  I support multiple versions, just like you.  He's using .Net 4.5.1.  I'll suggest it, though.

I looked for a "re-open" option but couldn't find one.

**Comment by issafram** [comment]
Just did this using **.NET 4.5.1** with no issue.  Obviously I can't POST to Google but there was no runtime error with RestSharp, so maybe you have other issues.  Do you have the **exact** code that you were calling?

```
namespace Issue690Test_451
{
    using RestSharp;

    class Program
    {
        static void Main(string[] args)
        {
            var restClient = new RestClient("http://www.google.com");
            var restRequest = new RestRequest(Method.POST);
            restRequest.AddFile("test", new byte[1], "test.txt");
            var restResponse = restClient.Execute(restRequest);
        }
    }
}
```

**Comment by gregsdennis** [comment]
Here is my code.  It's within a wrapper class which creates request objects.

    public IRestRequest Create(string endpoint, IDictionary<string, object> parameters = null)
    {
        var request = new RestSharpRequest(_serializer, endpoint);
        if (parameters != null)
            foreach (var parameter in parameters)
            {
                if (parameter.Key == RestFile.ParameterKey)
                {
                    var rf = (RestFile)parameter.Value;
                    request.AddFile(parameter.Key, rf.ContentBytes, rf.FileName);
                }
                else
                {
                    request.AddParameter(parameter.Key, parameter.Value);
                }
            }
        return request;
    }

The runtime won't even let this method load because it can't find `request.AddFile(...)`.  Here is the exception message:

    Method not found: 'RestSharp.IRestRequest
    RestSharp.RestRequest.AddFile(System.String, Byte[], System.String)'.

**Comment by issafram** [comment]
@gregsdennis, make sure that you don't have an old version of the library referenced or in your packages folder or in the GAC.  Some research showed that could be your issue.

**Comment by gregsdennis** [comment]
@issafram / @hallem, my client has settled on the option to use the .Net 4.0 library for the current version.  Since he's not pushing this issue anymore, I won't either.  Thanks for your help.

**Comment by josenguyen** [comment]
Hello,

thank you. It works now, I understand that only v1.1.1 is available for the community edition?
I hoped to find a way to get a .eml file imported as mail into the file area. 
It looks like createDocumentSimple() behaves differently than the manual file import in the web client. I have not found a method to import a mail.
Unfortunately, I am not proficient with Java so I want to find a way to automatically mirror my imap sever with its directory structure into openkm.

[Best](http://www.bestcantool.net)

**Comment by gregsdennis** [comment]
@josenguyen, are you sure you have the right repo?
