### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by rdefreitas** [restsharp/RestSharp#693]
Any plans for a version targeting .Net Core?

**Comment by StefH** [comment]
Same as https://github.com/restsharp/RestSharp/issues/664

**Comment by hallem** [comment]
Not currently no.  There are a bunch of other things that need to get fixed first.  If you'd like to take a crack at it and send a PR though that would be great.

**Comment by hallem** [comment]
Closing since it's a duplicate issue
