### ISSUE TITLE
Unnecssary format exceptions slow down code.

### ISSUE THREAD

**Issue by talbotmcinnis** [restsharp/RestSharp#695]
StringExtensions.cs:132.  Rather than 
```
try
{
    unix = Int64.Parse(input);
}
catch (Exception) { };
```
use `Int64.TryParse` so that you don't have a flood of exceptions while debugging applications with "valid" dates.

**Comment by hallem** [comment]
Completely agree.  It's something that's been there when I took over.  I'll get it fixed.

**Comment by alexeyzimarev** [comment]
This try catch is gone already.
