### ISSUE TITLE
problem with passing parameter

### ISSUE THREAD

**Issue by geniovi** [restsharp/RestSharp#698]
i use a RestClient for call a rest webservice I have a problem with passing parameters

this is my code

var client = new RestClient(string.Format(mRequestAddress, action));
CookieContainer cookies = new CookieContainer();
cookies.Add(new Cookie("cookiename", cookievalue, "", "host"));
client.CookieContainer = cookies;

var request = new RestRequest(method);

if i use
request.AddParameter("param", "1");
................
request.AddParameter("param", "n");

it works. 
if i use
 foreach (var p in parameters)
 {
    request.AddParameter(p.Name, p.Value);
 }

not it works
why?

**Comment by hallem** [comment]
That's actually kind of weird.  What is parameters in your code?

**Comment by hallem** [comment]
closed due to no response
