### ISSUE TITLE
Does RestSharp handle Enum with [Flags] correctly?

### ISSUE THREAD

**Issue by LordMike** [restsharp/RestSharp#701]
Hi,

I'm writing a library for the [SSLLabs Assesment API](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md), and they use multiple bitfields, which translates to `enum` types in C# with the `[Flags]` attribute. But I can't seem to get it working when multiple bits are set.

An example is the `delegation` field, which has two separate values (1 and 2 for two different options). It often comes back as `3`, but RestSharp translates that field to `0`.

My Delegation Class:

```
[Flags]
public enum Delegation
{
    NonPrefixedAccess = 1,
    PrefixedAccess = 2
}
```

If I however, add a third enum option `Test = 3`, RestSharp will parse the field "correctly" and set the field to `3`, meaning my two flags are set.

I'm speculating that RestSharp is performing an "IsDefined" or similar on the Enum type, which might return false for the value "3" in my case. Could this be changed?

**Comment by hallem** [comment]
Currently no, it doesn't support that functionality.  I'll add this as a feature request and see what I can do to get it in.

**Comment by LordMike** [comment]
I ended up using Microsofts HttpClient and Newtonsoft (there was also an issue with some dates as milliseconds since the epoch, which I can't convert natively with restsharp).

**Comment by hallem** [comment]
No problem.  I'm still going to see what I can do to get the feature in.  There are plans to replace the JSON library with Newtonsoft again.  I just need to figure out how to handle the strong names.  Also having an HttpClient implementation inside RestSharp is planned at some point.

**Comment by alexeyzimarev** [comment]
It will only be possible with alternative serialisers, like Json.NET #1018
