### ISSUE TITLE
Unix timestamp, in milliseconds

### ISSUE THREAD

**Issue by LordMike** [restsharp/RestSharp#702]
Hi,

I found that issue #194 added support for timestamps with second-precision. The API I'm looking at, however, uses millisecond precision. Is there some attribute I can use to denote this difference?

Simply setting the field as a `DateTime` will give me an overflow exception (as the 1000-times-too-large number is added to the epoch).

**Comment by hallem** [comment]
Can you provide a code sample of what you're trying to do?  I'll take a look and see if the support can be added for it.

**Comment by LordMike** [comment]
I did it with Newtonsoft, but this is the idea.

The json, source: (https://api.ssllabs.com/api/v2/analyze?host=ssllabs.com&fromCache=on):

    {
        "host" : "ssllabs.com",
        "port" : 443,
        "protocol" : "HTTP",
        "isPublic" : false,
        "status" :
        "READY",
        "startTime" : 1434605452953,
        "testTime" : 1434605526218,
        "engineVersion" :
        "1.18.1",
        "criteriaVersion" : "2009j",
        "endpoints" : [{
                "ipAddress" :
                "64.41.200.100",
                "statusMessage" : "Ready",
                "grade" : "A+",
                "gradeTrustIgnored" : "A+",
                "hasWarnings" : false,
                "isExceptional" : true,
                "progress" : 100,
                "duration" : 72967,
                "eta" : 2184,
                "delegation" : 3
            }
        ]
    }



The attributes:
https://github.com/LordMike/SslLabsLib/blob/master/SslLabsLib/Objects/Analysis.cs#L52

Epoch converter:
https://github.com/LordMike/SslLabsLib/blob/master/SslLabsLib/Code/MillisecondEpochConverter.cs

**Comment by hallem** [comment]
Great thanks.

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
