### ISSUE TITLE
Detecting parameter type from string

### ISSUE THREAD

**Issue by hellboy81** [restsharp/RestSharp#705]
Is there possible to detect `ParameterType` (`QueryString` or `UrlSegment`) from  `Resource`?

**Comment by hallem** [comment]
I'm not too sure what you're referring to, can you elaborate some more?

**Comment by hellboy81** [comment]
I have JSON file with endpoint parameters

```json
url: '/customers/{id}'
params: {
  id: 'CustomerId'
} 
```

This works very well for `UrlSegment` parameters.

But If I should specify `QueryString` I have problems:

- As I mentioned I can not specify query parameter direct in url:  `/customers/{id}?param1={param1}` or  /customers/{id}{?param1}'   
- I should specify in `json` file in own sub-object:
```json
url: '/customers/{id}'
params: {
  id: 'CustomerId'
},
queryParams: {
   param1: 'param1'
}
```

Is it the only possible solution?

**Comment by hallem** [comment]
That is correct you cannot specify the query string parameters like that.
