### ISSUE TITLE
No support for json.net like JsonProperty

### ISSUE THREAD

**Issue by agray** [restsharp/RestSharp#709]
If RestSharp supported JsonProperty in the same manner as json.net, json.net can be removed as it won't be needed for advanced deserialisation.

**Comment by hallem** [comment]
so json.net isn't currently a dependency on the library.  json property is a part of the json.net library with a lot of custom work for it to function properly.  i'm not really sure what you're asking or suggesting so if you could be more clear that would be appreciated.

**Comment by agray** [comment]
It's a suggestion. If RestSharp can support this I can remove JSON.Net as I am not only using it in one place.

**Comment by hallem** [comment]
i'm not going to rebuild support for this when it's supported by the json.net library.  eventually i'll be making json.net the default de/serializer for json in restsharp
