### ISSUE TITLE
ToPascalCase extension actually converts to camelCase.

### ISSUE THREAD

**Issue by rswilley** [restsharp/RestSharp#713]
When using the ToPascalCase extension it actually converts the string to camelCase instead of PascalCase.

**Comment by hallem** [comment]
I'll take a look at this to verify and fix if necessary.

**Comment by hallem** [comment]
I've just run some tests and confirmed that this is not happening.  I'm going to close this issue for now.  If you are still experiencing it, please provide some code that demonstrates the bug and reopen this issue.  Also, I need to know the version of the library you're using and the framework version you're targeting.
