### ISSUE TITLE
Dot in JSON property problem

### ISSUE THREAD

**Issue by markoOmega** [restsharp/RestSharp#714]
Hi,

I'm having trouble with reading Json response that has dot in it's property name.

I tried this

```
    [JsonProperty("ckan.locale_default")]
    [DeserializeAs(Name = "ckan.locale_default")]
    [SerializeAs(Name = "ckan.locale_default")]
    public string CkanLocaleDefault { get; set; }
```

but with no effect.

Is there any parser that forgot to add dot or something...

Tnx,
Marko

**Comment by hallem** [comment]
Marko, the json serialization library that rest sharp uses doesn't work well with dots in the name.  you can try using a custom de/serializer using JSON.NET but as of right now we don't have support for that.  If you need help using JSON.NET let me know and I'll get you a code sample.

**Comment by khebbie** [comment]
Plus one for this feature!
If I were to fix this where would I do that?

**Comment by onlyutkarsh** [comment]
+1. Having trouble reading the response from TFS/VSTS rest response.

**Comment by Glyptic** [comment]
+1.  I built a whole project on your solution and then found out that the source had a different format for stats that include periods in the names.  Example below.  Very frustrating as now I'm going to have to rebuild the project some other way.
            public StatusAvailabilityState statusavailabilityState { get; set; }
            [DeserializeAs(Name  = "status.enabledState")]
            public StatusEnabledState statusenabledState { get; set; }
            [DeserializeAs(Name  = "status.statusReason")]
            public StatusStatusReason statusstatusReason { get; set; }
            public SyncookieStatus syncookieStatus { get; set; }
            [DeserializeAs(Name  = "syncookie.accepts")]
            public SyncookieAccepts syncookieaccepts { get; set; }
            [DeserializeAs(Name  = "syncookie.hwAccepts")]
            public SyncookieHwAccepts syncookiehwAccepts { get; set; }
            [DeserializeAs(Name  = "syncookie.hwSyncookies")]
            public SyncookieHwSyncookies syncookiehwSyncookies { get; set; }
            [DeserializeAs(Name  = "syncookie.hwsyncookieInstance")]
            public SyncookieHwsyncookieInstance syncookiehwsyncookieInstance { get; set; }
            [DeserializeAs(Name  = "syncookie.rejects")]
            public SyncookieRejects syncookierejects { get; set; }
            [DeserializeAs(Name  = "syncookie.swsyncookieInstance")]
            public SyncookieSwsyncookieInstance syncookieswsyncookieInstance { get; set; }
            [DeserializeAs(Name  = "syncookie.syncacheCurr")]
            public SyncookieSyncacheCurr syncookiesyncacheCurr { get; set; }
            [DeserializeAs(Name  = "syncookie.syncacheOver")]
            public SyncookieSyncacheOver syncookiesyncacheOver { get; set; }
            [DeserializeAs(Name  = "syncookie.syncookies")]

**Comment by Glyptic** [comment]
I have a quick and dirty solution to this problem.  Not real elegant, but works.

IRestResponse response = establishConnection(resource);
string s = response.Content;
s = s.Replace("clientside.bitsIn", "clientsidebitsIn");
            s = s.Replace("clientside.bitsOut", "clientsidebitsOut");
            s = s.Replace("clientside.curConns", "clientsidecurConns");
            s = s.Replace("clientside.evictedConns", "clientsideevictedConns");
            s = s.Replace("clientside.maxConns", "clientsidemaxConns");
response.Content = s;

This modifies the json data before its deserialized.  Hope this helps others.

**Comment by jmsmcfrlnd** [comment]
You could try using the Newtonsoft.JSON nuget package as the JSON parser, via the RestSharp.Newtonsoft.JSON library, see [RestSharp.Newtonsoft.JSON](https://github.com/adamfisher/RestSharp.Newtonsoft.Json)

**Comment by ArmindoMaurits** [comment]
When is this PR 950 getting merged into the master? Then finally "." can be deserialised.

**Comment by alexeyzimarev** [comment]
Currently the work is being done to move to netstandard. It also requires a lot of changes in the deserialisation bit because of reflections. Before this is done, we will not merge stuff. As mentioned above, you can use the NewtonsoftJson adapter.

**Comment by ArmindoMaurits** [comment]
@alexeyzimarev thank you for the quick reply. It's good to hear that you guys are on your way to the netstandard. (Too bad I have some bad compatibility issues in a .net 3.5 legacy project with other packages, so I cannot use the Newtonsoft.json adapter).

**Comment by alexeyzimarev** [comment]
@ArmindoMaurits unfortunately, 3.5 support has been removed in favour of netstandard support.

**Comment by alexeyzimarev** [comment]
Should be fixed by #950

**Comment by lankymart** [comment]
> You could try using the Newtonsoft.JSON nuget package as the JSON parser, via the RestSharp.Newtonsoft.JSON library, see RestSharp.Newtonsoft.JSON

@condiosluzverde not sure how that is relevant to this, we are talking about deserializing not serializing. That NuGet package deals with serialization only.

**Comment by alexeyzimarev** [comment]
New release will contain the fix. I also plan to add more sane interfaces for (de)serialisation so people can use whatever they want.

**Comment by temporafugiunt** [comment]
I just wanted to confirm that the 106.1.0 version **fixes this issue for me**, I had previously tried using the Newtonsoft.Json.JsonSerializer via the ISerializer implemented contributed by Daniel Crenna (@dimebrain) and that did not. So out of this box I can now get certain properties from ElasticSearch that I couldn't before. i.e.:

 **[JsonProperty(PropertyName = "docs.count")]
[DeserializeAs(Name = "docs.count")]
public string docscount { get; set; }**

Thanks for the fix!!!

**Comment by n1m4nd** [comment]
> I just wanted to confirm that the 106.1.0 version **fixes this issue for me**, I had previously tried using the Newtonsoft.Json.JsonSerializer via the ISerializer implementation contributed by Daniel Crenna (@dimebrain) and that did not work. So out of this box I can now get certain properties from ElasticSearch that I couldn't before. i.e.:
> 
> **[JsonProperty(PropertyName = "docs.count")] [DeserializeAs(Name = "docs.count")] public string docscount { get; set; }**
> 
> Thanks for the fix!!!

Version 106.1.0 also fixes the problem for me. Can we get the fix also for the stable version ?

**Comment by alexeyzimarev** [comment]
@n1m4nd 
- SimpleJson is gone from the latest version
- since v107 the default serializer is `System.Text.Json`, so you should be able to configure property names following Microsoft documentation
- Not sure why you used some custom NewtonsoftJson integration as RestSharp has a package for it
