### ISSUE TITLE
MissingMethodException on AddFile(string, byte[], string, string = null)

### ISSUE THREAD

**Issue by nlarson** [restsharp/RestSharp#715]
I am referencing the .NET 4 lib version of the dll ( v4.0.30319 ) as the work around suggests (Project is also .NET 4  anyway) but am still seeing this error. The error occurred after we upgraded to 105.1.0.0 .

**Comment by hallem** [comment]
There were some breaking changes in the library for that version.  Take a look at the new signatures and see if there is one that works for you.

**Comment by hallem** [comment]
I've confirmed that the method is there, can you provide some further details to help me help you?

**Comment by hallem** [comment]
Please reopen the issue if it's still a problem

**Comment by nlarson** [comment]
I have gotten an update to the atlassian jira API that works. It was a case of their being out of sync on the docs and the versions. Thanks for the help!
