### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by millerds** [restsharp/RestSharp#716]
I'm trying to install RestShare in my Windows 8.1 universal app (has desktop and phone components), but I keep getting this error:

"Could not install package 'RestSharp 105.1.0'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

As far as I can tell from web sites, RestSharp should support .Net 3.5+.  Is there something I'm missing?

**Comment by boskiv** [comment]
I have a same issue with blank portable project on VS 2015 RC

"Could not install package 'RestSharp 105.1.0'. You are trying to install this package into a project that targets '.NETPortable, Version=v4.5, Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"

**Comment by hallem** [comment]
@boskiv the issue you're having is because the RestSharp nuget package does not contain binaries for for the .NETPortable library.

@millerds there should be binaries for 4.5.1 in the nuget package already.  Can you verify which project is having the issue and let me know what each project in your solution that's referencing the library targets (from the project properties)?

**Comment by millerds** [comment]
So this is my first time trying out the Windows 8.1 universal template in VS 2013.  There are two app projects (one for desktop and one for phone) and a shared code "project" (which apparently gets added to each of the other two projects at compile time).  I noticed the Project Manager Console allows me to target each project when running the Install-Package comment.  When targeting the desktop project (the default) I get the error above.  When targeting the phone project I get the same error but the target framework indicated is 'WindowsPhoneApp,Version=8.1'.  I can't target the shared project.

When I look at the properties page for each app project I don't see a listing for a .Net target on the application tab as I was expecting, but instead they just show an OS target.  The desktop app project says target is Windows 8.1, and the phone app project says target is Windows Phone 8.1.  No way to change either of them.

**Comment by hallem** [comment]
Interesting.  I don't do much if any windows phone development so I'll have to try this out locally and see what I can do to get it fixed.  Thanks for letting me know.

**Comment by millerds** [comment]
FYI . . . I just now tried some other project types on the same machine and found that the Store Apps projects are the ones with the trouble (even with just a windows app . . . no phone).  If I make a Windows Desktop project then it installs fine.  Hope that helps figuring it out.

**Comment by hallem** [comment]
Thanks that does help.

**Comment by o0rebelious0o** [comment]
I'm seeing the same issue in VS2015 (RC) doing Windows 10 Universal App Development.  Have the same issue with the portable version.

Error:
```
Severity	Code	Description	Project	File	Line
Error		Could not install package 'RestSharp 105.1.0'. You are trying to install this package into a project that targets 'Windows, Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0
```

**Comment by hallem** [comment]
@o0rebelious0o there wouldn't be targeting in nuget for that yet which is why you're getting that error.  I don't have any of that installed locally and since it's not a full RTM or GM yet it's not a priority.

**Comment by AhrimanSefid** [comment]
hi.
test in win 8.1 x64 not work.

**Comment by hallem** [comment]
@AhrimanSefid I run that environment to build and test and it works fine.  it's got more to do with the project you're trying to install the package for.

**Comment by AhrimanSefid** [comment]
VS 2015 test Not Work

**Comment by AhrimanSefid** [comment]
Project "C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-
master\RestSharp.sln" (1) is building "C:\Users\Amir Hossein\Downloads\Compress
ed\RestSharp-master\RestSharp-master\RestSharp.WindowsPhone\RestSharp.WindowsPh
one.csproj" (7) on node 1 (Clean target(s)).
C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\Re
stSharp.WindowsPhone\RestSharp.WindowsPhone.csproj(345,3): error MSB4019: The i
mported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsPhone\v8.0\Mic
rosoft.WindowsPhone.v8.0.Overrides.targets" was not found. Confirm that the pat
h in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-mas
ter\RestSharp-master\RestSharp.WindowsPhone\RestSharp.WindowsPhone.csproj" (Cle
an target(s)) -- FAILED.

Project "C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-
master\RestSharp.sln" (1) is building "C:\Users\Amir Hossein\Downloads\Compress
ed\RestSharp-master\RestSharp-master\RestSharp.Silverlight\RestSharp.Silverligh
t.csproj" (8) on node 1 (Clean target(s)).
C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\Re
stSharp.Silverlight\RestSharp.Silverlight.csproj(281,3): error MSB4019: The imp
orted project "C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Micros
oft.Silverlight.CSharp.targets" was not found. Confirm that the path in the <Im
port> declaration is correct, and that the file exists on disk.
Done Building Project "C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-mas
ter\RestSharp-master\RestSharp.Silverlight\RestSharp.Silverlight.csproj" (Clean
 target(s)) -- FAILED.

Done Building Project "C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-mas
ter\RestSharp-master\RestSharp.sln" (Clean;Rebuild target(s)) -- FAILED.


Build FAILED.

"C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\R
estSharp.sln" (Clean;Rebuild target) (1) ->
"C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\R
estSharp.WindowsPhone\RestSharp.WindowsPhone.csproj" (Clean target) (7) ->
  C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\
RestSharp.WindowsPhone\RestSharp.WindowsPhone.csproj(345,3): error MSB4019: The
 imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsPhone\v8.0\M
icrosoft.WindowsPhone.v8.0.Overrides.targets" was not found. Confirm that the p
ath in the <Import> declaration is correct, and that the file exists on disk.


"C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\R
estSharp.sln" (Clean;Rebuild target) (1) ->
"C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\R
estSharp.Silverlight\RestSharp.Silverlight.csproj" (Clean target) (8) ->
  C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master\
RestSharp.Silverlight\RestSharp.Silverlight.csproj(281,3): error MSB4019: The i
mported project "C:\Program Files (x86)\MSBuild\Microsoft\Silverlight\v5.0\Micr
osoft.Silverlight.CSharp.targets" was not found. Confirm that the path in the <
Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.65

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\Net4 mkdir Download\Net4\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\Net45 mkdir Download\Net45\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\Net451 mkdir Download\Net451\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\Net452 mkdir Download\Net452\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\Silverlight mkdir Download\Silverlight\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\WindowsPhone mkdir Download\WindowsPhone\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net35 mkdir Download\package\lib\net35\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net35-client mkdir Download\package\lib\net35-cli
ent\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net4 mkdir Download\package\lib\net4\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net4-client mkdir Download\package\lib\net4-clien
t\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net45 mkdir Download\package\lib\net45\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net45-client mkdir Download\package\lib\net45-cli
ent\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net451 mkdir Download\package\lib\net451\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net451-client mkdir Download\package\lib\net451-c
lient\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net452 mkdir Download\package\lib\net452\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\net452-client mkdir Download\package\lib\net452-c
lient\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\windowsphone8 mkdir Download\package\lib\windowsp
hone8\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>if
not exist Download\package\lib\sl4 mkdir Download\package\lib\sl4\

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp\bin\Release\RestSharp.dll Download\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp\bin\Release\RestSharp.xml Download\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net4\bin\Release\RestSharp.dll Download\Net4\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net4\bin\Release\RestSharp.xml Download\Net4\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net45\bin\Release\RestSharp.dll Download\Net45\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net45\bin\Release\RestSharp.xml Download\Net45\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net451\bin\Release\RestSharp.dll Download\Net451\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net451\bin\Release\RestSharp.xml Download\Net451\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net452\bin\Release\RestSharp.dll Download\Net452\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net452\bin\Release\RestSharp.xml Download\Net452\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Silverlight\bin\Release\RestSharp.Silverlight.dll Download\Silverlig
ht\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Silverlight\bin\Release\RestSharp.Silverlight.xml Download\Silverlig
ht\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.WindowsPhone\bin\Release\RestSharp.WindowsPhone.dll Download\Windows
Phone\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.WindowsPhone\bin\Release\RestSharp.WindowsPhone.xml Download\Windows
Phone\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y LICENSE.txt Download\
        1 file(s) copied.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y readme.txt Download\
        1 file(s) copied.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y readme.txt Download\package\
        1 file(s) copied.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp\bin\Release\RestSharp.dll Download\Package\lib\net35\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp\bin\Release\RestSharp.dll Download\Package\lib\net35-client\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net4\bin\Release\RestSharp.dll Download\Package\lib\net4\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net4\bin\Release\RestSharp.dll Download\Package\lib\net4-client\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net45\bin\Release\RestSharp.dll Download\Package\lib\net45\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net45\bin\Release\RestSharp.dll Download\Package\lib\net45-client\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net451\bin\Release\RestSharp.dll Download\Package\lib\net451\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net451\bin\Release\RestSharp.dll Download\Package\lib\net451-client\

The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net452\bin\Release\RestSharp.dll Download\Package\lib\net452\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net452\bin\Release\RestSharp.dll Download\Package\lib\net452-client\

The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Silverlight\bin\Release\RestSharp.Silverlight.dll Download\Package\l
ib\sl4\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.WindowsPhone\bin\Release\RestSharp.WindowsPhone.dll Download\Package
\lib\windowsphone8\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp\bin\Release\RestSharp.xml Download\Package\lib\net35\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp\bin\Release\RestSharp.xml Download\Package\lib\net35-client\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net4\bin\Release\RestSharp.xml Download\Package\lib\net4\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net4\bin\Release\RestSharp.xml Download\Package\lib\net4-client\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net45\bin\Release\RestSharp.xml Download\Package\lib\net45\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net45\bin\Release\RestSharp.xml Download\Package\lib\net45-client\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net451\bin\Release\RestSharp.xml Download\Package\lib\net451\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net451\bin\Release\RestSharp.xml Download\Package\lib\net451-client\

The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net452\bin\Release\RestSharp.xml Download\Package\lib\net452\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Net452\bin\Release\RestSharp.xml Download\Package\lib\net452-client\

The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.Silverlight\bin\Release\RestSharp.Silverlight.xml Download\Package\l
ib\sl4\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>cop
y RestSharp.WindowsPhone\bin\Release\RestSharp.WindowsPhone.xml Download\Package
\lib\windowsphone8\
The system cannot find the path specified.

C:\Users\Amir Hossein\Downloads\Compressed\RestSharp-master\RestSharp-master>too
ls\nuget.exe update -self
Checking for updates from https://www.nuget.org/api/v2/.

**Comment by hallem** [comment]
If you trying to build rest sharp in VS 2015 you need to make sure you have all the project targets for windows phone and silver light installed as well. Since VS 2015 was just release as RTM I have not tried to build the library using it yet.

**Comment by rainergp** [comment]
I'm trying to install the RestShare Nuget Package to my Cross Platform Project (iOS & Android) and I get this error:

Could not install package 'RestSharp 105.1.0'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by hallem** [comment]
@rainergp we don't support cross platform projects yet.  the way the library is constructed we can only target a single platform at a time.  there is a new version up on nuget currently that will target some of those types directly.

**Comment by hallem** [comment]
the new version should fix all of this now

**Comment by krunalc** [comment]
Can you suggest which version of Restsharp is compatible for PCL i.e. targeting multiple platforms? I tried 105.2.3 version but I still can't add this version library into my PCL.

**Comment by hallem** [comment]
@krunalc Right now there is no support for targeting multiple platforms.

**Comment by tanvan81** [comment]
I've some error

Could not install package 'RestSharp 105.2.3'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. 

I'm working on Vs.2015, win 10, x64

tks

**Comment by Yfernandezs** [comment]
Reporting the Same error, on VS15: "Severity	Code	Description	Project	File	Line	Suppression State Error Could not install package 'RestSharp 105.2.3'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0"

**Comment by george-weare8** [comment]
I have the same issue when trying to install the package in a .NETCoreApp,Version=v2.1...

**Comment by alexeyzimarev** [comment]
@george-weare8 what package?

**Comment by george-weare8** [comment]
RestSharp. https://www.nuget.org/packages/RestSharp

Best,
George Taskos

Senior Solutions Architect

WeAre8
230 Park Avenue, 3th fl. West
New York, NY 10169
(917) 717-9067
weare8.com

Private Entrance,
71 Vanderbilt Ave
3rd Floor

________________________________

**Comment by alexeyzimarev** [comment]
@george-weare8 so, you are are getting the error

> Could not install package '**RestSharp 105.1.0**'. You are trying to install this package into a project that targets '.**NETCore,Version=v4.5.1**', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

when installing it to your .NET Core 2.1 project? I am very confused.

**Comment by george-weare8** [comment]
Sorry for the confusion, I've created a new issue. 
https://github.com/restsharp/RestSharp/issues/1314
