### ISSUE TITLE
How can I use RestClient.ExecuteTaskAsync on .Net 3.5 when using TaskParallelLibrary and AsyncBridge ?

### ISSUE THREAD

**Issue by who** [restsharp/RestSharp#718]
The NuGet packages [TaskParallelLibrary] (https://www.nuget.org/packages/TaskParallelLibrary) and [AsyncBridge.Net35] (https://www.nuget.org/packages/AsyncBridge.Net35) bring `Task`, `await`, and general support for async to .Net 3.5.

However, when I include these dependencies alongside RestSharp and attempt compiling to a .Net 3.5 target, the [preprocessor directives defined in RestClient.Async.cs](https://github.com/restsharp/RestSharp/blob/658f0984e3ec71f2119f50f7de878f155246e9ce/RestSharp/RestClient.Async.cs#L190) prevent me from using `RestClient.ExecuteTaskAsync`.

If I force the inclusion of the RestSharp .Net 4.0 DLL into my .Net 3.5 context, then I get this error when compiling (using mono):

```
error CS1684: Reference to type `System.Threading.Tasks.Task`1<RestSharp.IRestResponse<T>>' claims it is defined assembly `mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', but it could not be found
```

**Getting to the point**
So, my question is, can I use the async features of RestSharp in .Net 3.5 by shimming in the NuGet packages above?  Has anyone gotten this to work?

**Comment by hallem** [comment]
The short answer is no, the Async support in RestSharp requires .Net 4.0+
