### ISSUE TITLE
NullReferenceException on an un-replicable event

### ISSUE THREAD

**Issue by RaphaelBensussan** [restsharp/RestSharp#719]
Hi,

I'm using RestSharp 105.1.0.0 (latest on NuGet) and I have the following exception :
CLR_EXCEPTION_System.NullReferenceException_80004003_  **on**
RestSharp.RestClient+__c__DisplayClass5+__c__DisplayClass7._ExecuteAsync_b__2

I'm not able to replicate this error... I can see it trough the windows store dashboard.

Is there a known bug which has been fixed but not yet published on NuGet?
I found some similar problems but they seem to have been fixed previously ... :(
Am I the only one facing this?
Thanks

**Comment by hallem** [comment]
I've never seen that before.  Are you able to replicate it?

**Comment by RaphaelBensussan** [comment]
Actually no, I had this one time, it crashed the app, when I relaunched it, it was ok.
I've seen another closed issue, which had the same exception occurring when the remote server was offline (#552, #447)
I don't have any control on the remote server, I'm plugged on an external API.
Thanks

**Comment by RaphaelBensussan** [comment]
Sorry I'm now feeling stupid, actually it seemed to be a fault in one of my user's input checks :(
This was a non-issue :)
Thanks for your time, I really like this lib, very easy to handle and can reach a good result very easily!
