### ISSUE TITLE
Quote in request string

### ISSUE THREAD

**Issue by ITFactoryAUT** [restsharp/RestSharp#720]
Hello,
I tried the following:
var request = new RestRequest("cloud/users/{user} -d key=\"{key}\", value=\"{value}\"", Method.PUT);
But I got a bad response from the server, could this be a bug from your RestClient that it can´t handle single " in the request string? 
greetings

**Comment by hallem** [comment]
I don't think I've ever tried this.  Did you capture the request and response from the server?  I would help to know what's happening?  In the meantime I'll see what the code does when a quote is on the request path.

**Comment by ITFactoryAUT** [comment]
I think the issue is library related, because with the following code instead of using AddUrlSegments it is working fine:

    var requestString = String.Format("cloud/users -d user=\"{0}\" -d password=\"{1}\"", userName, password);
    var request = new RestRequest(requestString, Method.POST);
