### ISSUE TITLE
"The name of the parameter will be used as the Content-Type header for the request."

### ISSUE THREAD

**Issue by EricYan1** [restsharp/RestSharp#721]
Hello,
RestSharp is setting the Content-Type of a body in a multipart request to the name attribute of that body.
Is it possible for RestSharp to not behave this way and instead set the Content-Type and name of a part independently?

This is what I am getting in my JSON body part,

------boundary
Content-Disposition: form-data; name="comment"
Content-Type: comment

{ "text": "This is a comment." }
------boundary

This is what I'm looking for,

------boundary
Content-Disposition: form-data; name="comment"
Content-Type: application/json

{ "text": "This is a comment." }
------boundary

I am calling this RestSharp method,

restRequest.AddParameter("comment", "{\"text\":\"This is a comment.\"}", ParameterType.RequestBody);

Thank you.

**Comment by hallem** [comment]
I'm going to need to see more of your code to figure out what's happening.   Can you provide more?

**Comment by EricYan1** [comment]
Thanks for helping, this is a sample program I'm using to perform a multipart upload request.

RestClient httpClient = new RestClient("http://api.example.com/");
httpClient.FollowRedirects = true;
string file = "example.txt";
IRestRequest restRequest = new RestRequest("sheets/123/discussions/456/comments", Method.POST);
restRequest.AlwaysMultipartFormData = true;
restRequest.AddHeader("Authorization", "Bearer ACCESS_TOKEN");
restRequest.AddFile("file", File.ReadAllBytes(file), new FileInfo(file).Name, "application/octet-stream");
restRequest.AddParameter("comment", "{\"text\":\"This is a comment\"}", ParameterType.RequestBody);
IRestResponse restResponse = httpClient.Execute(restRequest);

The program executes without fail. Using a software like Fiddler to check the full request Restsharp built, I get,

-------------------------------28947758029299
Content-Type: comment
Content-Disposition: form-data; name="comment"

{"text":"This is a comment"}
-------------------------------28947758029299
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: application/octet-stream


<contents of example.txt>

-------------------------------28947758029299--


In the first part, Content-type and name are both "comment". I would like Content-Type to be "application/json" and name to be "comment".

**Comment by hallem** [comment]
I'm not sure what's happening here.  I'll take a look when I get a chance.

**Comment by hallem** [comment]
merged the PR that fixes this
