### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by rainergp** [restsharp/RestSharp#729]
I'm trying to install the RestShare Nuget Package in my Cross Platform Project (iOS & Android) and I get this error:

Could not install package 'RestSharp 105.1.0'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by hallem** [comment]
currently there is not nuget support for your project setup.
