### ISSUE TITLE
JSONDeserializer Creating empty objects instead of null

### ISSUE THREAD

**Issue by BHare1985** [restsharp/RestSharp#730]
using RestSharp version 105.1.0.0 and the JsonDeserializer

Given a class such as

```c#
public class Test
{
        public Dictionary<string, object> attributes { get; set; }
}
```

and Using JSON result:

```json
{
    "attributes": {
        "THIS_SHOULD_BE_NULL": null,
        "NUMBER": 6
    }
}
```

The result is a Dictionary<string, object>  where Dictionary["THIS_SHOULD_BE_NULL"] is an empty object instead of `NULL`. With Newtonsoft JSON.net the results in NULL (What I expect and want)

ps: I dont use google groups.

**Comment by hallem** [comment]
I'll check this out.  This could be a limitation of the JSON de/serializer the library uses.  I'm looking into what it would take to at least offer JSON.NET as an option, not necessarily the only.
