### ISSUE TITLE
Randomly occouring: Error getting response stream (ReadDone2): ReceiveFailure

### ISSUE THREAD

**Issue by koreus7** [restsharp/RestSharp#731]
With reference to this bug report:
https://bugzilla.xamarin.com/show_bug.cgi?id=19673

For me it happens once every 50 or so calls of:

    IRestResponse response  = await _client.ExecuteTaskAsync (request);

But as in the bug report it is not just for Async calls, seems this bug has been around a while. I have managed to reproduce it on IOS as well as the Android case from the Xamarin bug report.

**Comment by koreus7** [comment]
Update on what might be causing it, check bugzilla.

Quote from Till Lorentzen 


>Hi!
>I am not sure if this lines of mono code are correct:
>https://github.com/mono/mono/blob/master/mcs/class/System/System.Net/WebConnection.cs#L533-L536
>Why is "0" an invalid result? If I am understanding this documentation
>(https://msdn.microsoft.com/de-de/library/system.io.stream.endread(v=vs.110).aspx)
>correctly, it is a valid value and could happen if Stream.EndRead is called and
>accidentally is called at the end of the stream with no more buffered read data
>left in stream. And this seems to be a valid situation.

>The simplest way to patch the error would be to erase the marked lines of code,
>but I am not sure if that would break calls after this check or if a simple
>"return" instead of throwing an exception would be the correct way to handle
>this. I tried to figure out which unit test case is used to validate the
>functionality of this class but couldn't find it. Could you please give me an
>advice where I have got to look for it.

>Best regards

> Till

Who says it may be caused by a bug in mono.

**Comment by hallem** [comment]
I'm not sure why you opened this here.  It doesn't seem to be an issue with RestSharp

**Comment by git-naili** [comment]
This is a mono bug actually, I facing the same problem in one of my projects and many people suffering from it.
https://github.com/facebook-csharp-sdk/facebook-csharp-sdk/issues/333
https://forums.xamarin.com/discussion/15509/error-getting-response-stream-readdone2-receivefailure
http://stackoverflow.com/questions/8830653/how-do-i-handle-fix-error-getting-response-stream-readdone2-receivefailure

**Comment by keyvanarasteh** [comment]
hello all :smile: 

its **not** Xamarin or .NET's bug. :wink: 

your **server side endpoint fails when requesting.** :neutral: 

**check your API endpoint** if you own the api or contact support if you are getting API from third party company or service. 

why it happens randomly :  :wink: 
because bug is in your inner if or loop blocks and it happens when it goes through this buggy loop or if.

best regards. :smile:

**Comment by veso266** [comment]
its still happening, using latest RestSharp and latest Xamarin, not even sure how to account for it, or temporary fix it because now I just inform the user that something is wrong and he/she should try again
