### ISSUE TITLE
Download Stats, pls

### ISSUE THREAD

**Issue by shinoamakusa** [restsharp/RestSharp#738]
Would it be possible to add ability to get things such as: downloaded bytes, total bytes to download, download percent, download /start/error/success state

Thanks,
Oleg

**Comment by hallem** [comment]
oleg, i'm not sure i follow what you're asking for.  can you explain a little further?

**Comment by shinoamakusa** [comment]
I have an app which downloads images from Tumblr platform. I currently use WebClient for file download async purposes which give me an ability to track how much of the file has been downloaded and report that to Ui so it can display the percentage of download per file. I have just come across the RestSharp and like the faster speed of it ( i use now to crawl the api posts before download)

**Comment by shinoamakusa** [comment]
Any idea when will the progress reporting while downloading file async be available so I can kiss WebClient final goodbye :P ?

**Comment by alexeyzimarev** [comment]
https://github.com/cfHxqA/RestSharp.RestClientSyncUtil/blob/master/RestClient.Sync.Util.cs

**Comment by alexeyzimarev** [comment]
Tracking in #917

**Comment by simonbuehler** [comment]
hi, the repository is not available anymore 

> 
> 
> https://github.com/cfHxqA/RestSharp.RestClientSyncUtil/blob/master/RestClient.Sync.Util.cs

hi, the repository is not available anymore , anyone has a copy of it?
