### ISSUE TITLE
Allow deserialization of IList and IDictionary

### ISSUE THREAD

**Issue by DixonDs** [restsharp/RestSharp#744]
It would be great to support the deserialization of generic IList and IDictionary by deserialization to generic List and Dictionary, respectively.

**Comment by hallem** [comment]
I agree, however once the switch to using Json.Net happens we'll get this out of the box.  I just haven't had time to get to it yet.

**Comment by DixonD-git** [comment]
But are you going to change underlying SimpleJson to Json.NET or the whole (de)serialization logic? In the former case, you would still need to add IList/IDictionary support; in the later case, you would lose support of SerializeAsAttribute/DeserializeAsAttribute

**Comment by hallem** [comment]
I plan to switch it out. Yes that support would be lost for JSON but the Json.Net library has its own support for that.

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
