### ISSUE TITLE
Some packages are not compatible with UAP,Version=v10.0

### ISSUE THREAD

**Issue by shahthepro** [restsharp/RestSharp#745]
I have VS 2015 community with Windows SDK for Universal Apps installed on a Windows 10 Pro x64 OS. Everytime I try to install RestSharp using NuGet, I get the following error. 

"Install-Package : Some packages are not compatible with UAP,Version=v10.0"

**Comment by hallem** [comment]
There is no support for this project type yet.

**Comment by shahthepro** [comment]
Is there any plans in the near future?

**Comment by hallem** [comment]
Not right now no but I'll add this as a feature request.

**Comment by akshay2000** [comment]
I came here looking for this. It would be great to have UWP support since that seems *the* way from now on.

**Comment by hallem** [comment]
It's still very new. I'll see what I can do to get it in. My development environment isn't windows 10 yet so it will have to wait for that change to happen.

**Comment by dpakpaul** [comment]
Yeah, would be great to have Win 10 UWP support. There are only a couple of decent REST wrappers for .Net out there - this one and PortableREST.

**Comment by hallem** [comment]
no problem.  i'm working on getting a windows 10 environment set up so this can happen.

**Comment by shahthepro** [comment]
That's a great news to hear. I'll waiting for this one. :+1:

**Comment by vbandi** [comment]
I just want to say +1... I'd love to have RestSharp for my UWP projects.

**Comment by newnottakenname** [comment]
@hallem Any updates on this issue?

**Comment by Mikrolous** [comment]
I've the same problem too.

**Comment by calloncampbell** [comment]
Want support for UWP too please!

**Comment by wbsimms** [comment]
+1

**Comment by RoRoche** [comment]
+1

**Comment by ToyMakerGR** [comment]
+1

**Comment by nabels-coolblue** [comment]
+1

**Comment by mateialexandru** [comment]
+1

**Comment by o0rebelious0o** [comment]
+1

**Comment by jerry1621** [comment]
+1 Any updates?

**Comment by JoshuaKGoldberg** [comment]
+1

**Comment by hallem** [comment]
code for UWP support has been checked into master but nuget support is still pending.  i or the PR author need to add the targeting to the build scripts

**Comment by jerry1621** [comment]
@hallem Thanks, but this only works for x64 and x86 while it does not work for ARM-devices (e,g. Windows 10 Mobile), any plans for that?

**Comment by weird-dreams** [comment]
Is the API now ready for ARM?

**Comment by jerry1621** [comment]
@weird-dreams Still waiting for a statement of @hallem , hopefully it will be added soon :)

**Comment by weird-dreams** [comment]
Please support ARM - we are building a continuum experience on a ARM device!

**Comment by weird-dreams** [comment]
please support "_UAP,Version=v10.0_" fully (x86,x64,ARM).
Swagger creates good proxies but they do not work on my phone + desktop (continuum!) without **RestSharp**.

+++++1

**Comment by JaykeBird** [comment]
+1

**Comment by emigrating** [comment]
+2

@jerry1621 any chance you could share the modifications you made as referenced in the swagger-codegen thread? I attempted to copy your steps but it's not working.

**Comment by jerry1621** [comment]
@emigrating sure: I just edited the build.bat and added a few lines for UWP 
e.g.  there are these download-directories created by:
`if not exist Download\package\lib\net35 mkdir Download\package\lib\net35\
if not exist Download\package\lib\net4 mkdir Download\package\lib\net4\
if not exist Download\package\lib\net4-client mkdir Download\package\lib\net4-client\
if not exist Download\package\lib\net45 mkdir Download\package\lib\net45\
[...]`

so just add a line for uwp, too
`if not exist Download\package\lib\uwp mkdir Download\package\lib\uwp\`

Simply complete the build.bat by adding uwp-statements to the other statements

**Comment by fobo66** [comment]
What we can do to support UWP?

**Comment by AuroraDysis** [comment]
+1

**Comment by totht91** [comment]
+1

**Comment by nicolas255** [comment]
+1

**Comment by RaminMT** [comment]
+1

**Comment by weird-dreams** [comment]
Still no support for UWP apps on an ARM device?
Please invest some time in supporting this...
Thank you!

**Comment by mavanmanen** [comment]
Still no support....

**Comment by alexeyzimarev** [comment]
We will only support .NET Standard 2.0. UWP that is compatible with .NET Standard is in preview.

**Comment by mavanmanen** [comment]
But .net standard 2.0 support for RestSharp isn't released yet is it? Tried to use it in a .net Core 2.0 project before and it was broken. Is a pre-release for that available somewhere?

**Comment by alexeyzimarev** [comment]
It is in preview too, from today. Would be great if you can test. https://www.nuget.org/packages/RestSharp/106.0.0-alpha0277

**Comment by alexeyzimarev** [comment]
UWP & .NET Standard 2.0: A preview is now available
https://blogs.msdn.microsoft.com/dotnet/2017/08/25/uwp-net-standard-2-0-preview/

We will support UWP as any other platform by supporting .NET Standard 2.0. There will be no separate package for UWP.

**Comment by mavanmanen** [comment]
Absolutely great, thanks!

**Comment by mavanmanen** [comment]
`{System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.SystemWebProxy.GetProxy(Uri destination)
   at System.Net.ServicePointManager.ProxyAddressIfNecessary(Uri& address, IWebProxy proxy)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy)
   at System.Net.HttpWebRequest.get_ServicePoint()
   at RestSharp.Http.ConfigureWebRequest(String method, Uri url)
   at RestSharp.Http.GetStyleMethodInternal(String method)
   at RestSharp.Http.AsGet(String httpMethod)
   at RestSharp.RestClient.DoExecuteAsGet(IHttp http, String method)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)}`

**Comment by alexeyzimarev** [comment]
Well, they are in preview, expect things to improve closer to release. You can also help them by submitting issue reports.

**Comment by alexeyzimarev** [comment]
But we also plan moving to HttpClient, but this work is not easy. I have tried but then decided to postpone it. If some is willing to help - please, submit a PR. With HttpClient things will be more compatible.

**Comment by mavanmanen** [comment]
I'll take a look at the current code and see if I can do anything to help with the change to HttpClient.

**Comment by alexeyzimarev** [comment]
The alpha version is being published from develop branch. Most probably I will have to release as-is with web request. HttpClient can be done right after that. I would prefer the work on HttpClient replacing WebRequest to be started in a fork or separate branch.

**Comment by alexeyzimarev** [comment]
@mavanmanen it seems like a general issue, please switch to #992 to continue the discussion
