### ISSUE TITLE
Support forwarding to an Owin Pipeline instead of making network call

### ISSUE THREAD

**Issue by alistair** [restsharp/RestSharp#747]
We are currently using RestSharp for testing our apis.  As these api's are also using owin it would be nice if we could use RestSharp in combination with TestServer to do the following

```
var server = TestServer.Create<Startup>();
var client = new RestClient(server.Handler); // The server.Handle == HttpMessageHandler
client.Something() // Which calls into the owin pipeline instead of a real request
```

This would allow us to not have to startup a server port to test our api's.

So

1)  Is this possible now OOLB?
2)  Is this possible with a 'workaround' or third party code
2)  What would be the best way of implementing this if I was to contribute?

**Comment by hallem** [comment]
this isn't supported currently.  i will take this as a feature request.  if you'd like to submit a pr, check out the latest version of the code on a personal fork and make the changes you thing are necessary.  make sure the unit tests all run and pass and then include pass/fail unit tests for your new code.  once that's done, submit a pr and i'll review it.

**Comment by lc273734858** [comment]
We have the same demand.

**Comment by shyamgudi** [comment]
Any updates on this?

**Comment by alexeyzimarev** [comment]
If nobody who needs it, makes anything for it to happen, there will be no update. It is all in your hands.

**Comment by HeroMaxPower** [comment]
We have the same demand for thi, any updates i don't really want to use httpClient.

**Comment by chazt3n** [comment]
@HeroMaxPower I wanted to implement it and PR but we had to just drop it :( Sorry brother

**Comment by alexeyzimarev** [comment]
I guess we'll still handle it as part of the HttpClient implementation.
