### ISSUE TITLE
Merge PCL branch?

### ISSUE THREAD

**Issue by ravensorb** [restsharp/RestSharp#751]
Are there any plans on merging the code bases and rolling out a PCL version?

**Comment by hallem** [comment]
sort of... i'm not sure what state the pcl branch is in.  there is an open pr that will be merged in that should negate the need for it and bring the support into the main sln.  i just need some time to get it tested and fully reviewed.

**Comment by ravensorb** [comment]
this is great news!  I would be happy to help test if you need it.

**Comment by cfl777** [comment]
@hallem 
Hi, any progress with this? 
I tried to install on a PCL, but it failed to work.
