### ISSUE TITLE
Invalid value for attribute at deserialization

### ISSUE THREAD

**Issue by jumacabo** [restsharp/RestSharp#752]
```
    public class ClassA
    {
        public string Id { get; set; }
        public ClassB ClassB { get; set; }
    }

    public class ClassB
    {
        public string Id { get; set; }
    }

    [TestMethod]
    public void RestSharpIdBug()
    {
        string testXml =
            @"<classA id=""xx"">" +
            @"   <classB>" +
            @"      <id>yy</id>" +
            @"   </classB>" +
            @"</classA>";

        var deserializer = new RestSharp.Deserializers.XmlDeserializer();
        var classA = deserializer.Deserialize<ClassA>(new RestSharp.RestResponse { Content = testXml });
        Assert.IsNotNull(classA);
        Assert.AreEqual("xx", classA.Id);
        Assert.AreEqual("yy", classA.ClassB.Id);
    }
```

This test fail, classA.Id == classA.ClassB.Id == "yy"

**Comment by jumacabo** [comment]
Use of Deserialization attributes doesn't seems to help, same result with:

        public class ClassA
        {
            [DeserializeAs(Attribute = true, Name = "id")]
            public string Id { get; set; }
            public ClassB ClassB { get; set; }
        }

        public class ClassB
        {
            [DeserializeAs(Attribute = false, Name = "id")]
            public string Id { get; set; }
        }

**Comment by jumacabo** [comment]
Rewrite the code trying to make it in a different way but same issue, this sample doesn't work neither:

        public class ClassA
        {
            [DeserializeAs(Attribute = true, Name = "id")]
            public string IdA { get; set; }

            [DeserializeAs(Name = "classB")]
            public DifferentClass AnotherClass { get; set; }
        }

        public class DifferentClass
        {
            [DeserializeAs(Attribute = false, Name = "id")]
            public string IdB { get; set; }
        }

        [TestMethod]
        public void RestSharpIdBug()
        {
            string testXml =
                @"<classA id=""xx"">" +
                @"   <classB>" +
                @"      <id>yy</id>" +
                @"   </classB>" +
                @"</classA>";

            var deserializer = new RestSharp.Deserializers.XmlDeserializer();
            var classA = deserializer.Deserialize<ClassA>(new RestSharp.RestResponse { Content = testXml });
            Assert.AreNotEqual(classA.IdA, classA.AnotherClass.IdB);
        }

**Comment by rooflz** [comment]
Try using the XmlAttributeDeserializer rather than the XmlDeserializer. It will check the DeserializeAsAttribute and make the correct decision.

**Comment by hallem** [comment]
Did the suggestion fix your problem?

**Comment by jumacabo** [comment]
I lost the faith in this proyect when it failed to deserialze something so simple, don't understand why should I use a workaround, if it is not working it should be fixed

**Comment by hallem** [comment]
Keep in mind this is an open source project.  If you want to take a crack at fixing it then have at it and it will get reviewed.  If not it will get looked at and fixed when someone gets to it.

**Comment by aethercowboy** [comment]
I too am having this issue. It seems the best strategy would be to change the element matching to be breadth-first instead of depth-first (as it appears to be). Perhaps it should also check first for attributes, then elements, when deserializing.

I have the following structure:

    <field type="1" name="example" displayName="Example Usage">
        <itemList>
            <item id="5">
                <person>
                    <name>Bob</name>
                </person>
            </item>
        </itemList>
    </field>

And the `Field.Name` is being populated by the `Field.ItemList[0].Person.Name`. I even have `Field.Name` decorated with `[DeserializeAs(Name="name", Attribute=true)]`.

**Comment by alexeyzimarev** [comment]
You can also use `DotNetXmlSerializer`.
