### ISSUE TITLE
Better dictionary item lookup/retrival

### ISSUE THREAD

**Issue by felipegtx** [restsharp/RestSharp#757]
In several places across the project, instead of [checking for the existence of a particular key and than trying to retrieve that data](https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestClient.cs#L232) it would be better to just use [TryGetValue](https://msdn.microsoft.com/en-us/library/bb347013%28v=vs.110%29.aspx) and do both operations at once.

See [here](http://stackoverflow.com/questions/9382681/what-is-more-efficient-dictionary-trygetvalue-or-containskeyitem)

**Comment by hallem** [comment]
I'll add it to the list.  Feel free to submit a PR if you are up for making the change and testing it.

**Comment by felipegtx** [comment]
Ok @hallem! I'll give it a try as soon as I have some spare time :+1:
