### ISSUE TITLE
can not support gbk charset

### ISSUE THREAD

**Issue by xland** [restsharp/RestSharp#758]
can not support gbk charset

**Comment by hallem** [comment]
going to need a little more information before anyone can help you

**Comment by maobiwen** [comment]
不知道作者是不是手抖忘记加代码了
在 HttpResponse.cs里面加入代码吧。临时解决方案。

        public string Content
        {
            //get { return this.content ?? (this.content = this.RawBytes.AsString()); }
            get
            {
                if (string.IsNullOrEmpty(this.ContentEncoding))
                {
                    return this.content ?? (this.content = this.RawBytes.AsString());
                }
                else
                {
                    return this.content ?? (Encoding.GetEncoding(this.ContentEncoding).GetString(this.RawBytes));
                }
            }
        }
