### ISSUE TITLE
OAuth signature rejected by Twitter

### ISSUE THREAD

**Issue by nariman-haghighi** [restsharp/RestSharp#759]
Running off of `105.2.3`, I can see this issue with Twitter's `/1.1/statuses/update.json` endpoint still exists if the status you're posting has any of the following characters: `! * ' ( )`

I believe this is rooted in `Uri.EscapeDataString` not complying with RFC 3986. Some people are saying it's fixed in 4.5 but in our testing it's still there and needs the manual fix descried here:

http://stackoverflow.com/questions/846487/how-to-get-uri-escapedatastring-to-comply-with-rfc-3986

Additional context:
http://stackoverflow.com/questions/10394799/restsharp-urlencode-in-signature-base-generation-returns-invalid-string

Is there a workaround? Seems this was first reported 2+ years ago.

**Comment by hallem** [comment]
I'll have to look into this as a bug.

**Comment by alexeyzimarev** [comment]
I believe it has been fixed long ago.
