### ISSUE TITLE
Issue with trying to install RestSharp for a Portable Class through Nuget

### ISSUE THREAD

**Issue by jamesbar2** [restsharp/RestSharp#760]
Could not install package 'RestSharp 105.2.3'. You are trying to install this package into a project that targets 'portable-net45+win+MonoAndroid10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

![image](https://cloud.githubusercontent.com/assets/828489/10209470/3bda9bcc-67a1-11e5-83ab-15fb68f24560.png)

Let me know if there's a workaround for this, or what can be done. Thanks!

**Comment by ravensorb** [comment]
Unfortunately as far as I know RestSharp is not currently compatible with PCL -- I am hoping this will change soon though :smile:

**Comment by JeansReal** [comment]
+1

**Comment by hallem** [comment]
the library is not able to target multiple PCLs.  It can target iOS, Andriod, etc. individually but not all at once yet.

**Comment by KraigM** [comment]
It is supported under #734 once it gets merged in

**Comment by jamesbar2** [comment]
Awesome! Thank you!

**Comment by KraigM** [comment]
Currently it is PCL Profile78 (aka .Net 4.5+, Xamarin.iOS, Xamarin.Android, Xamarin.Mac, WP App 8+, Windows 8+, WP Silverlight 8+, Windows Store App).  

The PCL version should mostly work but each of those platforms should already be supported with platform specific versions so in the final application NuGet will choose the platform specific version (which is what you want).  But you will be able to compile a full PCL (Profile 78 or compatibile) library using RestSharp.PCL and it will be compatible with the platform version of RestSharp at runtime (JIT or AOT).

**Comment by sunthx** [comment]
+1

**Comment by xinmeng1** [comment]
+1

**Comment by aniketghode** [comment]
Actually, you can add RestSharp package to either iOS or Droid project in your solution and then in PCL browse to your solutionName/packages/RestSharp to find a RestSharp.dll and add it as a reference in your PCL project. i

It should work.

**Comment by gentledepp** [comment]
Hey guys - I just finished the PCL support. But until it is merged, you'll have to clone the repo yourselves and run the build.bat
Happy coding ;-)

**Comment by alexeyzimarev** [comment]
Sorry, this is very obsolete. .NET Standard 2.0 or .NET Framework 4.5.2 only now.
