### ISSUE TITLE
Add ability to invoke HttpWebRequest.AddRange method with long parameters

### ISSUE THREAD

**Issue by AlexeyVlg** [restsharp/RestSharp#763]
Add ability to invoke HttpWebRequest.AddRange method with long parameters.
Http.cs:

```
    private static void AddRange(HttpWebRequest r, string range)
    {
        Match m = Regex.Match(range, "(\\w+)=(\\d+)-(\\d+)$");

        if (!m.Success)
        {
            return;
        }

        string rangeSpecifier = m.Groups[1].Value;
        // Please update this:
        //int from = Convert.ToInt32(m.Groups[2].Value);
        //int to = Convert.ToInt32(m.Groups[3].Value);
        // To:
        long from = Convert.ToInt64(m.Groups[2].Value);
        long to = Convert.ToInt64(m.Groups[3].Value);

        r.AddRange(rangeSpecifier, from, to);
    }
```

**Comment by hallem** [comment]
what's the issue you're running into that this will fix?

**Comment by AlexeyVlg** [comment]
I'm trying to upload a large file with chunks to Google Drive cloud (more than 2GB). With int type I can't specify any range after 2GB.
https://developers.google.com/drive/web/manage-uploads

**Comment by sqc1999** [comment]
Why hasn't this simple issue fixed after so long time passed?
It's really annoying that I can't use 64-bit int range headers.

**Comment by johnn82** [comment]
This is still a dummy issue :)

**Comment by gentleman-turk** [comment]
This issue is also preventing me from making ranged get requests for parts of files larger than 2GB.
