### ISSUE TITLE
Timeouts for every request.

### ISSUE THREAD

**Issue by tcorrin** [restsharp/RestSharp#772]
We have written an application that is using restsharp to send 2 GET requests to a server every 5 seconds on a linux system running mono 3.12. After about 30 hours of sending these requests they start to timeout with status 0. We are also sending other requests to the same server using httpClient and these requests are not timing out. If we then restart the application then the restsharp requests no longer timeout.

**Comment by hallem** [comment]
That's some weird behavior.  I have no way of testing this though and it's kind of an edge case.  Can you test a little further and see if you can find out what's happening?  Also, being that you're running Mono on Linux it may not be RestSharp.  It may be Mono.  What version of RestSharp are you using?

**Comment by tcorrin** [comment]
After further testing we think that this may be a mono issue reather than a rest sharp issue so I am closing this ticket.
