### ISSUE TITLE
Deserialize multiple response types

### ISSUE THREAD

**Issue by TGKN** [restsharp/RestSharp#774]
Hi,
My issue is somehow related to this one
https://github.com/restsharp/RestSharp/issues/549
What I am trying to do is deserialize the response content based on the returned HttpStatusCode. I believe this could easily be done if the RestClients Deserialize method 
(IRestResponse< T > Deserialize< T >(IRestRequest request, IRestResponse raw)
was public or at least protected (currently private), or am I missing something here? So for example after calling the Execute< Person > method I'd be able to do a switch on the StatusCode and, if required, call the Deserialization part again but using a different class i.e. Deserialize< HttpError >
I like the way RestSharp does deserialization by automatically picking the correct deserializer based on content type - I don't want to reinvent this part.

**Comment by hallem** [comment]
This is definitely related.  Do you have a broader use case for it or just want to use HttpError?

**Comment by TGKN** [comment]
Hi,
No it is not only related to HttpError, I would like to be able to make the decision of which type of object is to be deserialized based on the HttpStatusCode. I've seen these requests in some google groups or stackoverflow questions but appearantly no one posted it here yet. Looking at the code I thought making the Deserialize method public would be the simplest solution to achieve what I want but of course I could be wrong...

**Comment by hallem** [comment]
Ok.  I'll take this as a feature request and see what I can do about it.

**Comment by SuperDrew** [comment]
I have the same issue so :+1: to this.

**Comment by mclark1129** [comment]
@hallem  Is there a reason that access to the ContentHandlers inside of `RestClient` are so closely guarded?  Just exposing those or creating a simple public `Deserialize<T>(RestResponse)` method on `RestClient` seems like a quick and easy way to solve the problem and provide us is with the flexibility to handle what seems like a pretty common use case.

I'm happy to even submit a PR with that change, but I'm curious to know if there are specific reasons Deserialization is so protected inside of `RestClient`.

**Comment by koszeggy** [comment]
I have the same issue and now I use reflection to call the `Deserialize<T>` method until the fix is available on the master branch.

Maybe it would be helpful if not only `Deserialize<T>` but `GetHandler` would be public, too.

My workaround:

```C#
public static class RestClientExtensions
{
    public static IRestResponse<T> Deserialize<T>(this IRestClient restClient, IRestRequest request, IRestResponse raw)
    {
        return (IRestResponse<T>)ExecuteDeserialize(restClient, typeof(T), request, raw);
    }

    // Executes the generic IRestResponse<T> Deserialize<T>(IRestRequest, IRestResponse) method on RestClient by reflection
    private static object ExecuteDeserialize(IRestClient restClient, Type targetType, IRestRequest request, IRestResponse raw)
    {
        if (restClient == null)
        {
            throw new ArgumentNullException(nameof(restClient));
        }

        var genericMethod = restClient.GetType().GetMethod("Deserialize");
        if (genericMethod == null)
        {
            throw new InvalidOperationException("Deserialize method not found");
        }

        var method = genericMethod.MakeGenericMethod(targetType);
        return method.Invoke(restClient, new object[] { request, raw });
    }
}
```

AdditionalIy I implemented a non-generic `Execute` on top of RestSharp, which returns an object (mainly either the deserialized contract or error response), which uses an non-generic `Deserialize` overload extension. It would be really helpful if I could cast the `IRestResponse<T>` to `IRestResponse<object>` but I cannot do that because the `out` covariance qualifier is not added to `IRestResponse<T>`. Now the only way to return `IRestResponse<object>` requires an insane reflection hack:

```C#
    public static IRestResponse<object> Deserialize(this IRestClient restClient, Type targetType, IRestRequest request, IRestResponse raw)
    {
        // following line would work if IRestResponse<T> was covariant: IRestResponse<out T>
        // return (IRestResponse<object>)ExecuteDeserialize(restClient, targetType, request, raw);

        // instead, we need further nasty reflections:
        var resultT = (IRestResponse)ExecuteDeserialize(restClient, targetType, request, raw);
        var result = resultT.ToAsyncResponse<object>();
        var prop = resultT.GetType().GetProperty(nameof(result.Data));

        result.Data = prop.GetValue(resultT);
        return result;
    }
