### ISSUE TITLE
Why RestClient must contain a value for BaseUrl

### ISSUE THREAD

**Issue by ChenJasonGit** [restsharp/RestSharp#775]
I think somesone and me not want to set "BaseUrl" because multi difference url in one site;

**Comment by hallem** [comment]
If you can provide a valid use case for not requiring a base url on the client I'll see what I can do.  No promises.  Also, just to make sure it's clear, this may or may not be possible without heavy changes I haven't looked yet so if it will require a big change than it will most likely not happen for a while if at all.

**Comment by stanac** [comment]
A valid use case could be that we are calling multiple APIs where one of them have only one endpoint. There is a workaround of course, but it would be nice if we could just pass single URL instead of splitting that single URL to base URL and relative URL.

**Comment by alexeyzimarev** [comment]
Duplicate of #625

**Comment by roblapp** [comment]
This is really inconvenient. Enough so that I am considering just going with HttpClient.

**Comment by Gaspa79** [comment]
A valid usecase is that you can have a cookie for a top level domain and have to use the cookie in different subdomains. I want to use the client cookiecontainer. I ended up changing the baseurl every time instead of just creating requests with different urls.
