### ISSUE TITLE
OAuth 1.0 auth not working for empty consumer secret

### ISSUE THREAD

**Issue by ivan-milovanovic-troxo** [restsharp/RestSharp#776]
I tried to use RestSharper as client for [MAAS RestAPI](https://maas.ubuntu.com/docs/api_authentication.html) and stumbled upon an issue with OAuth 1.0 authentication implementation. 

RestSharper does not allow empty consumer secret, this is incorrect cause consumer secret can be empty string. "The Consumer Secret MAY be an empty string" from [OAuth Core 1.0](http://oauth.net/core/1.0a/)

In [OAuthWorkflow](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs#L296-L299) exception is being thrown if consumer secret is empty:

```
    if (this.ConsumerSecret.IsNullOrBlank())
    {
        throw new ArgumentException("You must specify a consumer secret");
    }
```

**Comment by hallem** [comment]
No problem that's an easy fix.  I'll add it to the list.
