### ISSUE TITLE
Post Request can not invoke AddParamter,AddBody method together.

### ISSUE THREAD

**Issue by xiaoyifang** [restsharp/RestSharp#779]
eg:
post data to posturl?a=xxx

(method one)

	    var request = new RestRequest(postUrl, Method.POST);
            request.RequestFormat = DataFormat.Json;
            request.AddParameter("a", "xxx");
            request.AddBody(new { openid = openId });
            IRestResponse<UserInfo> response = client.Execute<UserInfo>(request);

if invoked like above,the body will not be sent to the remote server.
but if try another way (method two):

	    var request = new RestRequest(postUrl?a=xxx, Method.POST);
            request.RequestFormat = DataFormat.Json;
            request.AddBody(new { openid = openId });
            IRestResponse<UserInfo> response = client.Execute<UserInfo>(request);

can work.

I think there is no way to disable the method one.

**Comment by hallem** [comment]
you can't do what you're trying to.  you'd have to use a multipart form post, the first part would contain the querystring parameter you're passing and the second part would contain the body.
