### ISSUE TITLE
DownloadData SaveAs extension not found

### ISSUE THREAD

**Issue by sewarts** [restsharp/RestSharp#782]
When trying to use client.DownloadData(request).SaveAs(path);
SaveAs extension is not found.

Am using latest RestSharp.

**Comment by eiu165** [comment]
@sewarts  I am getting the same error. did you find a resolution?

**Comment by sewarts** [comment]
Looks like I gave up and to download a  file I now do this....

`Dim TryResponse As IRestResponse = DownloadFile(url)
                    If TryResponse.StatusCode = 200 Then
                        Dim arr() As Byte = TryResponse.RawBytes
                        System.IO.File.WriteAllBytes(LocalPath, arr)
                        SuccessFull = True
                        ContentType = TryResponse.ContentType
                    End If

Function DownloadFile(url as string) as IResetResponse 
Dim client As New RestClient(Left(url, 29))
        client.Authenticator = New HttpBasicAuthenticator("api", "key")
        Dim request = New RestRequest()
        request.Resource = url
        request.Method = Method.GET
        Dim MailgunResponse = client.Execute(request)
        Return MailgunResponse
End Function

`

**Comment by eiu165** [comment]
I am using abcpdf.dll to save the file 

```

  public  void SaveToDiskFromUrl(string downloadUrl, string filePath, string fileName)
    { 
        var data = this.GetDocumentContent(downloadUrl);

        Doc theDoc = new Doc();
        theDoc.Read(data); 

        theDoc.Save(filePath + fileName);
        theDoc.Clear();
    }
 
    public byte[] GetDocumentContent(string url)
    {
        var client = new RestClient(url);
        var request = new RestRequest(Method.GET);
        request.AddHeader("postman-token", "xxx");
        request.AddHeader("cache-control", "no-cache");
        request.AddHeader("authorization", "Bearer " + _userToken);
        request.AddHeader("accept", "application/json");
        IRestResponse response = client.Execute(request);
        //var x = response.RawBytes; 
        return (response.RawBytes);
    }
```

**Comment by orhanmaden** [comment]
See this SO post for the solution: https://stackoverflow.com/a/29349753/1912609

It states that it resides in the RestSharp.Extensions namespace.
