### ISSUE TITLE
Cannot set ContentType = "application/x-www-form-urlencoded; charset=UTF-8"

### ISSUE THREAD

**Issue by duongphuhiep** [restsharp/RestSharp#784]
```
var request = new RestRequest(Method.POST);
request.AddParameter("nummessage", 1);
request.AddParameter("mediatype", 31);

var client = new RestClient("LemonService.php") { Encoding = Encoding.UTF8 };
var response = client.Execute(request);
```

My `LemonService.php` expected that RestSharp will send the request with the following header

`content-type: application/x-www-form-urlencoded; charset=UTF-8`

but RestSharp only send

`content-type: application/x-www-form-urlencoded`

There is nothing in the request that tell my `LemonService.php` that the request encoding was UTF-8.

I will have to come back to `System.Net.WebRequest` for work-around

```
WebRequest webRequest = WebRequest.Create("LemonService.php"");
webRequest.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
webRequest.Method = "POST";
String request = "nummessage=" + System.Web.HttpUtility.UrlEncode("1", Encoding.UTF8)
"&mediatype=" + HttpUtility.UrlEncode("31", Encoding.UTF8)
byte[] bytes = Encoding.ASCII.GetBytes(request);
webRequest.ContentLength = bytes.Length;   //Count bytes to send
using (var os = webRequest.GetRequestStream()) {...}
```

**Comment by hallem** [comment]
i'll have to look into why that's happening

**Comment by loonytoon** [comment]
Hi,

I am also experiencing a similar issue with the code below.

> var request = new RestRequest(Method.POST);
>             request.RequestFormat = DataFormat.Json;
>             request.AddBody(body);
>             request.AddHeader("X-RequestDigest", _contextinfo.FormDigestValue);
>             request.AddHeader("Accept", "application/json; odata=verbose");
>             request.AddHeader("Content-Type", "application/json; odata=verbose");
>             request.Resource = String.Format("solutions/SSM/mad/_api/web/lists(guid'{0}')/items", listGuid);

`Content-Type: application/json; odata=verbose` becomes `Content-Type: application/json` when sent

I have similar code that uses GET rather post which successfully passes the correct Content-Type header.

I hope this extra information helps.

Cheers

Ian

**Comment by uxsoft** [comment]
I was able to reproduce the issue & made a pull request with a fix (#841)

**Comment by escobar5** [comment]
I'm having the same problem, has somebody found a workaround?

**Comment by uxsoft** [comment]
Theres a pull request for this issue, waiting to be merged...

**Comment by Wintermute79** [comment]
Same here
