### ISSUE TITLE
Protocol Version is not available

### ISSUE THREAD

**Issue by jeffesp** [restsharp/RestSharp#790]
I would like to use the HTTP version (1.0, 1.1, etc) from a `RestResponse`. This isn't available on `RestResponse` but it is available on the underlying `HttpWebResponse` as the `ProtocolVersion` property. Was this left out intentionally?

**Comment by hallem** [comment]
what's the use case for this?

**Comment by jeffesp** [comment]
I'm using RestSharp to log some information. I want to log a line like: `HTTP/1.0` or `HTTP/1.1` for the version of HTTP for the connection.

**Comment by hallem** [comment]
ok i'll go over the PR when i sit down next to do some development on the project.

**Comment by jeffesp** [comment]
Thanks. Let me know if you need any further info.
