### ISSUE TITLE
TimeOut Issue

### ISSUE THREAD

**Issue by madisettykrishna** [restsharp/RestSharp#793]
In rest sharp 104.4.0.1
here we are using time out for 5 secs but it is not responding in 5secs and we are getting the response after 1min.

Here is the sample code 

 private readonly IRestClient _client; = new RestClient();

 public async Task<bool> PingAsync()
        {
            var url = "CompleteSampleUrl";//(not only end point)
            var request = new RestRequest(url, Method.GET) { Timeout = 5000 };
            var response = await _client.ExecuteGetTaskAsync(request);
            return ProcessResponse<bool>(response);
        }

I'm calling timer like this

       public async Task StartConnecting()
        {
            if (_timer != null && _timer.Enabled)
                _timer.Stop();

            _timer = new Timer { Interval = 100 };
            _isConnectedToServer = null;
            _timer.Elapsed += async (sender, e) =>
            {
                _timer.Stop();

                try
                {
                    IsConnectedToServer = await PingAsync();
                }
                catch (Exception ex)
                {
                    IsConnectedToServer = false;
                }

                _timer.Interval = 3000;
                if (!IsConnectedToServer)
                    _timer.Start();
            };

            _timer.Start();
        }

**Comment by hallem** [comment]
you're significantly behind with your running version.  it's not really possible for me to troubleshoot or support the older versions.  if this problem persists after you update then please let me know.
