### ISSUE TITLE
Support for RSA-SHA1

### ISSUE THREAD

**Issue by rudrvij** [restsharp/RestSharp#794]
Currently RestSHarp only supports HMAC-SHA1 for signing requests. It will be great if we could support RSA-SHA1 as well.

Thanks
Vijay

**Comment by Tsaukpaetra** [comment]
Agreed. This is rather trivial I think since you already did HMAC.

Should just need implementation of the Sign function AFAICT, something like this (copypasta from another project):

            var privateKey = new RSACryptoServiceProvider();
            privateKey.FromXmlString(signingKey);

            var shaHashObject = new SHA1Managed();
            var data = System.Text.Encoding.ASCII.GetBytes(stringToSign);
            var hash = shaHashObject.ComputeHash(data);

            var signedValue = privateKey.SignHash(hash, CryptoConfig.MapNameToOID("SHA1"));

            var result = Convert.ToBase64String(signedValue, Base64FormattingOptions.None);
            return result;
