### ISSUE TITLE
How to use RestSharp Client for Batch execution in web API instead of HttpClient?

### ISSUE THREAD

**Issue by ashuthinks** [restsharp/RestSharp#796]
Currently I'm using HttpClient to process batch execution in WebAPI I wonder is it possible to use RestSharp Client for batch execution? Is there anything like MultipartContent in Restsharp ?

      private static async Task ExecuteBatchRequest()
		{
           HttpClient client = new HttpClient();
            HttpRequestMessage request;
            HttpResponseMessage response;
           //Create a request to query for customers
            HttpRequestMessage queryCustomersRequest = new HttpRequestMessage(HttpMethod.Get, serviceUrl + "/Customers");    
            //Create a message to add a customer
			HttpRequestMessage addCustomerRequest = new HttpRequestMessage(HttpMethod.Post, serviceUrl + "/Customers");   
			addCustomerRequest.Content = new ObjectContent<Customer>(addedCustomer, formatter);    
			//Create a message to update a customer    
			HttpRequestMessage updateCustomerRequest = new HttpRequestMessage(HttpMethod.Put, string.Format(serviceUrl + "/Customers/{0}", updatedCustomer.Id));     updateCustomerRequest.Content = new ObjectContent<Customer>(updatedCustomer, formatter);    
			//Create the different parts of the multipart content    
			HttpMessageContent queryContent = new HttpMessageContent(queryCustomersRequest);    
			HttpMessageContent addCustomerContent = new HttpMessageContent(addCustomerRequest);    
			HttpMessageContent updateCustomerContent = new HttpMessageContent(updateCustomerRequest);    
			//Create the multipart/mixed message content    
			MultipartContent content = new MultipartContent("mixed", "batch_" + Guid.NewGuid().ToString());    
			content.Add(queryContent);    
			content.Add(addCustomerContent);    
			content.Add(updateCustomerContent);    
			//Create the request to the batch service    
			HttpRequestMessage batchRequest = new HttpRequestMessage(HttpMethod.Post, serviceUrl + "/batch");    
            //Associate the content with the message    
            batchRequest.Content = content;    
            //Send the message    
            HttpResponseMessage batchResponse = await client.SendAsync(batchRequest);          
        }

**Comment by hallem** [comment]
rest sharp does support multi part form posts
