### ISSUE TITLE
Specifying the deserializer for text/plain etc

### ISSUE THREAD

**Issue by sicklittlemonkey** [restsharp/RestSharp#798]
https://github.com/restsharp/RestSharp/issues/276 is a  pretty common gotcha. It would be nice to have a better way of specifying this, but If you're going to stick with AddHandler() could you please add it to the docs? This SO question has > 10,000 views. ; - )
http://stackoverflow.com/questions/10324526/restsharp-not-deserializing-json-object-list-always-null/34626240

Cheers,
Nick.

**Comment by hallem** [comment]
nick, what would you consider a better way than add handler?  as for the docs, that's an easy change and i can get that in the next time i'm sitting down to work on this.

**Comment by sicklittlemonkey** [comment]
Hi Michael.

As a point for discussion here's a user expectation from that SO link: "Basically, I was wrong to assume that client.Execute was going to be able to auto-detect the return content type. It needs to be explicity set."

How about exactly that? Being able to set an option on the request (or the client) to auto detect JSON or XML. E.g. just check the first non-whitespace body char for '<' or '{'.

Or a simpler way to specify on the request that a text/plain response should be interpreted as JSON/XML.

Overriding the response ContentType using an Action is pretty ugly. Adding a handler to the client for text/plain is better, but not by much. The more swallowed into the framework the better.

Cheers,
Nick.

**Comment by zaus** [comment]
Is this the same as #789 ?  And I could be wrong but there are wildcards in the default handlers -- is that what you mean?  https://github.com/restsharp/RestSharp/blob/develop/RestSharp/RestClient.cs#L374

**Comment by alexeyzimarev** [comment]
Auto-detection based on characters in the request is not a good idea.

What can be done (in the next version) is to remove either XML by calling `client.UseJson` or JSON, by calling `client.UseXml` and then we will use the first available handler.
