### ISSUE TITLE
Multipart post changes between 105.0.1 and 105.2.3

### ISSUE THREAD

**Issue by ktodyruik** [restsharp/RestSharp#799]
Hi,

Has there been any changes between version 105.0.1 and 105.2.3 to the multipart message code? I just received an error on the server side after upgrading my RestSharp library, "Error parsing MIME multipart body part header byte 63 of data segment System.Byte[]."

When I changed the library back to the version I had been using before (105.0.1), the multipart message post worked fine.

My client code is very simple:

```
RestClient client = new RestClient("http://server");
client.Authenticator = new CustomAuthenticator());
IRestRequest request = new RestRequest("/api/handler", Method.POST);
request.RequestFormat = DataFormat.Json;
request.AddBody(jsonBodyHere);
byte[] fileContent = File.ReadAllBytes("Filename.pdf");
request.AddFile("attachment", fileContent, "Filename.pdf");
var response = client.Execute(request);
```

And on the server side I am handling the multipart post with MultipartFormDataStreamProvider.

Thanks,
Kerry

**Comment by hallem** [comment]
i just did a compare between the two versions and the only difference seem to be in tests not in the core code path for multipart.  have you been able to dig into this further?
