### ISSUE TITLE
XmlDeserializer doesn't process case when RootElement has depth > 1

### ISSUE THREAD

**Issue by ma-gu** [restsharp/RestSharp#800]
There is only one test case with RootElement, and it covers only depth = 1 case (please see it here: https://github.com/restsharp/RestSharp/blob/master/RestSharp.Tests/XmlDeserializerTests.cs#L103 )

When I'm saying 'depth' here I mean depth in XML hierarchy, i.e. for XML <root><subroot><subsubroot></subsubroot></subroot>/<root> subroot depth = 1, while subsubroot depth = 2.

**Comment by hallem** [comment]
what's the use case for this? it's not come up before to my knowledge so i'm curious how you ran across it.

**Comment by ma-gu** [comment]
I have run into this while I was creating a wrapper for AWS Alexa API (please see sample response here: https://github.com/ma-gu/AlexaApiWrapper/blob/master/AlexaApi.Test/Sample.TestData/SitesLinkingIn-yahoo.xml)

I was trying to use "SitesLinkingIn" (which have depth=4 in the path SitesLinkingInResponse/Response/SitesLinkingInResult/Alexa/SitesLinkingIn) as a RootElement at first and have encountered this error, but eventually I end up with wrapping whole response.

In code this use case looks like something like this:
```var request = new RestRequest()	{	RootElement = "SitesLinkingIn"	};```

For example, here is the code from https://github.com/restsharp/RestSharp/wiki/Recommended-Usage :

```
public Call GetCall(string callSid) {
    var request = new RestRequest();
    request.Resource = "Accounts/{AccountSid}/Calls/{CallSid}";
    request.RootElement = "Call";
    request.AddParameter("CallSid", callSid, ParameterType.UrlSegment);
    return Execute<Call>(request);
}
```

If "Call" have depth > 1 in XML response this code should fail.

**Comment by hallem** [comment]
ok i understand now.  i'll merge the PR once i've had a chance to review it the next time i sit down to work on the project.
