### ISSUE TITLE
Could not be used with unity3d when build onto android or ios  platform

### ISSUE THREAD

**Issue by unitymatrix** [restsharp/RestSharp#804]
In editor,it's Ok. while not work on mobilephone

**Comment by hallem** [comment]
i'm going to need a little more information than it doesn't work.  are you seeing an error message?

**Comment by VReelTeam** [comment]
I know I'm a fair few months late but this post makes it appear that I'm not the only one who's encountered an issue here then...

The actual problem I'm having is that the "RestSharp.105.2.3" "net35" version seems to work fine in the Unity Editor but when I build the apk for Android (in a project built for Android API Level 19 "Kit Kat") I get the below error - any ideas?

*ArgumentOutOfRangeException: Argument is out of range.
Parameter name: options
at System.Text.RegularExpressions.Regex.validate_options (RegexOptions options) [0x0003a] in /Users/builduser/buildslave/mono/build/mcs/class/System/System.Text.RegularExpressions/Regex.cs:248
at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options) [0x00017] in /Users/builduser/buildslave/mono/build/mcs/class/System/System.Text.RegularExpressions/Regex.cs:214
at RestSharp.RestClient..ctor () [0x00000] in :0
at RestSharp.RestClient..ctor (System.String baseUrl) [0x00000] in :0*

**Comment by shzaur** [comment]
just install 105.1.0
http://stackoverflow.com/a/33529086/2613974

**Comment by yazdir** [comment]
Is it possible to fix this error? I can't use the last version of RestSharp (current 105.2.3) in unity with mobile build
The error:
```
ArgumentOutOfRangeException: Argument is out of range.
```

I just do a new instance of RestClient() in `Awake` and call `Execute` in a Coroutine.

**Comment by alexeyzimarev** [comment]
You can try the new .NET Standard library out of the pre-release package and see if it is compatible with your platform.

**Comment by GwendalBroudin-Emoko** [comment]
Any news on this issue ? What are the supported platforms on the latest version ?

**Comment by alexeyzimarev** [comment]
The issue is closed. Someone who needs RestSharp to work with Unity should implement it, or at least test it.
