### ISSUE TITLE
MD5 hash of the body of the request

### ISSUE THREAD

**Issue by lty83** [restsharp/RestSharp#806]
Hello

I'm calling an API that requires me to pass over an MD5 hash of the body of the request.

After calling AddFile the body parameter is empty and I can't seem to generate an MD5 hash of the request body.

Does anyone know of any way to accomplish this? thanks in advance...

**Comment by hallem** [comment]
i don't think there is a way to do what you're trying to currently.  are you doing a straight file post or are you doing a multipart?

**Comment by lty83** [comment]
Straight file post, I actually ended up going back to HttpClient and it's working now. Unfortunately I believe you are correct that there is no way to do this.

**Comment by hallem** [comment]
you might be able to compute the hash of the file before you add it to the request.  but since you're off the library you're probably don't playing.
