### ISSUE TITLE
oauth1 not specifing parameter type

### ISSUE THREAD

**Issue by elibyy** [restsharp/RestSharp#810]
hey there,
there's a mistake in [OAuth1](https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/OAuth1Authenticator.cs#L296), it's missing the specification of the parameter type so it falls to the enum default of Cookie

**Comment by hallem** [comment]
hey thanks for pointing this out.  i've not touched the oauth section of the code yet so if you can reference the file and line that would help.  if you'd like to take a shot at fixing it feel free to submit a PR.

**Comment by tecmobo** [comment]
Phew I'm glad someone else noticed this! I created a [pull request](https://github.com/restsharp/RestSharp/pull/825) for this fix. Forgive me if I did something incorrect as it is my first pull request.

**Comment by elibyy** [comment]
@tecmobo has it right, is it going to be merged any time soon?

**Comment by fastblood** [comment]
hey, when do you think these changes will be released in nuget?
