### ISSUE TITLE
Cant add the package to a newly created Universal app 

### ISSUE THREAD

**Issue by NoNameProvided** [restsharp/RestSharp#813]
Creating a new project and trying to install RestSharp will throw the following error: 

> Package restore failed. Rolling back package changes for 'Toggl'.

Output is the following: 

> Restoring packages for 'Toggl'.
> Restoring packages for P:\Toggl\Toggl\project.json...
> RestSharp 105.2.3 is not compatible with UAP,Version=v10.0.
> Some packages are not compatible with UAP,Version=v10.0.
> RestSharp 105.2.3 is not compatible with UAP,Version=v10.0 (win10-arm).
> Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
> RestSharp 105.2.3 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
> Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
> RestSharp 105.2.3 is not compatible with UAP,Version=v10.0 (win10-x86).
> Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
> RestSharp 105.2.3 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
> Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
> RestSharp 105.2.3 is not compatible with UAP,Version=v10.0 (win10-x64).
> Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
> RestSharp 105.2.3 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
> Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
> Package restore failed for 'Toggl'.
> Package restore failed. Rolling back package changes for 'Toggl'.
> ========== Finished ==========

The Project is targeted against .Net 4.6.1 Using `uap10.0` as framework in the project.json

Note: I am on the Insider fast ring.

**Comment by hallem** [comment]
Currently RestSharp doesn't not support the UAP target via NuGet

**Comment by NoNameProvided** [comment]
Do you have any plans to add support for it? I have a Win10 machine so if you tell me what I have to do to verify the compatibility I am happy to do it!

**Comment by hallem** [comment]
i do but i need time to sit down and get the support in.  this is a side project and i've recently moved and had a few other things taking up severe amounts of time.  i'll get it in as soon as i can.  i'm working on things today and will see how far i get.

**Comment by NoNameProvided** [comment]
Thanks for your work! Please ping me here if it's done.

**Comment by hallem** [comment]
there is code merged into master but no support for nuget yet.  if you want to get and build the source you can get the support for now.  i'm working on getting it added to nuget.

**Comment by NoNameProvided** [comment]
Thanks for your works man! :)

**Comment by NoNameProvided** [comment]
Any update on adding it to nuget?

**Comment by nicolas255** [comment]
Hi, there.

Any update on this ?

**Comment by MrMashy** [comment]
Hi, I hear that there is a working build for UAP @hallem Any instructions on how I should add this into my project?

**Comment by alexeyzimarev** [comment]
RestSharp 106 and higher support .NET Standard and it should work with future versions of UWP (currently in preview).
