### ISSUE TITLE
I don't understand why in http get request all parameter keys and parameter values adduce to lovercase?

### ISSUE THREAD

**Issue by influs** [restsharp/RestSharp#815]
how do http get request with parameter keys and parameter  values with different cases(uppercase or lowercase or pell-melled)

**Comment by hallem** [comment]
i understand what you're asking but i'm not able to help without some examples, can you provide them?

**Comment by influs** [comment]
I have theese class. When i use RestSharp method AddParameter with parameters in different cases RestSharp generating request with parameters in lower case always
`class ServiceProxy : IServiceProxy
    {
        private readonly RestClient restClient;

        internal ServiceProxy()
        {
            restClient = new RestClient("somesite.com");
        }

        public IRestResponse GetHandle(Dictionary<string, string> requestParameters)
        {
            var request = new RestRequest(Method.GET)
            {
                Resource = "someresource",
                //Resource = "MobileServices/get-data.aspx?",
                RequestFormat = DataFormat.Json
            };

            foreach (var parameter in requestParameters)
            {
                request.AddParameter(parameter.Key, parameter.Value);
            }
            return restClient.Execute(request);
        }
}`

**Comment by alexeyzimarev** [comment]
It works fine now
