### ISSUE TITLE
StackOverflowException when AddJsonBody with object containing Xelement

### ISSUE THREAD

**Issue by Lechus** [restsharp/RestSharp#816]
Hi,

I have to make a request with Object that contains XElement.
When the line with restRequest.AddJsonBody(requestWithXElement) is hit I got System.StackOverflowException.
Is there any overcome or do I have to use external Json Deserialzier?

**Comment by alexeyzimarev** [comment]
so, what is the content of the `requestWithXElement`, I wonder?

**Comment by alexeyzimarev** [comment]
I think I know. SimpleJson traverses the object and `XElement` is recursive. I don't think it is a good idea to put XML-related concerns to objects that will be serialized to JSON. Or use another serializer.
