### ISSUE TITLE
Transfer-Encoding: chunked problem

### ISSUE THREAD

**Issue by Ravenheart** [restsharp/RestSharp#817]
Gretings,

RestSharp seems to have some problem with the following GET request:

http://dev.smart-ss.org:8042/instances/758c1e5b-225ad192-be723193-7bfde586-15505e02/frames/0/preview

The problem appears to be related to Transfer-Encoding: chunked, the above Uri works perfectly fine with HttpWebRequest but with RestSharp it returns an empty byte[0] array when using the .DownloadData(request) method of the RestClient class.

(Please note that the above Url may not be accessible during the weekend).

**Comment by behoyh** [comment]
I am not able to verify this endpoint works in browser or in Postman. What is the HTTP verb?

**Comment by Ravenheart** [comment]
Its a GET.

**Comment by behoyh** [comment]
![capture](https://cloud.githubusercontent.com/assets/2565745/15512899/29d0f70e-21b0-11e6-968a-3559359e61f6.PNG)

I cannot access this endpoint. Is it publicly accessible?

**Comment by Ravenheart** [comment]
It will accessible tomorrow at around 09:00, its my work laptop that I run a set of services on. Normally its on all workdays during the week, but its a holiday here so its off at the moment.

**Comment by Ravenheart** [comment]
http://dev.smart-ss.org:8042/instances/ad8dacd2-e39f0971-7e2eaef9-4b7808cd-f8ac8d1e/frames/0/preview I'm at work and it should be accessible.

**Comment by behoyh** [comment]
I can confirm the byte array is indeed empty when calling .DownloadData(). I'll poke around the codebase to try and find the underlining issue, meanwhile if you submit a pull request I'll be happy to review it.

**Comment by mihaela-tudor** [comment]
Problem still exists. If the header Transfer-Encoding: chunked is present the content-length is 0 and the body is missing.
