### ISSUE TITLE
Suggestion: make RestSharp configurable

### ISSUE THREAD

**Issue by YehudahA** [restsharp/RestSharp#819]
RestSharp uses ```HttpWebRequest``` as a requester.
Many programmers would prefer to use ```HttpClient```, because it's more testable, but unfortunately this is not possible because of compatibility issues.

I suggest to split the requesting behavior from ```RestClient``` class, and provide it using configuration and extension methods.

For example:
``` cs
var configuration = new RestClientConfiguration();

// for .NET 3.5
configuration.UseDefault();

// for .NET 4.5
configuration.UseHttpClient(); 

// for mocking
configuration.UseHttpClient(new MockHttpMessageHandler()); 

// usage
var restClient = new RestClient(configuration);
```

This pattern used in many libraries, for example AngleSharp and more.

**Comment by hallem** [comment]
I understand your ask but this would require a complete rewrite of the library to support HttpClient.  It is not something that is being considered.  Sorry
