### ISSUE TITLE
DownloadData hides errors when download fails

### ISSUE THREAD

**Issue by robi26** [restsharp/RestSharp#820]
When using RestClient.DownloadData to download a file and the file does not exist or the server returns an error the exception is hidden by the DownloadData method and cannot be handled.

**Comment by alexeyzimarev** [comment]
Now you can use the new overload, which accepts the `throwOnError` parameter.

**Comment by davetoland** [comment]
This doesn't appear to be working for me, I have set throwOnError to true, and even tried adding a line above to tell the client to ThrowOnAnyError, and whilst Visual Studio reports a 400 exception, the DownloadData method still swallows it and continues...

`try
{
    var client = GetRestClient(baseUri, credential);
    client.ThrowOnAnyError = true;
    var data = client.DownloadData(new RestRequest(downloadLink), true);
    File.WriteAllBytes(localPath, data); //<-- still gets executed
    result = true;
}
catch (Exception e)
{
    Logger.Error($"Error downloading Attachment from link: {downloadLink}", e);
}`

**Comment by davetoland** [comment]
![image](https://user-images.githubusercontent.com/19878260/75982775-3c438f80-5edf-11ea-9902-365332283b06.png)

![image](https://user-images.githubusercontent.com/19878260/75982784-41a0da00-5edf-11ea-8130-6a764260f046.png)

**Comment by davetoland** [comment]
Ok, so I've grabbed your source and built in in Debug to try and work out what's wrong here. Seems you're only throwing if the response is not an HttpWebResponse. So... by design. 
The situation for my test, is that we're intentionally passing in an incomplete URL, it targets a directory above the intended target (i.e. "image.png" fragment is missing from the end of the URL) and we're expecting the client to raise the exception.
As things stand, we've now got a byte array returned which File.WriteAllBytes happilly saves to disk, but we've got no way of telling that the file is not the intended target. 
If I try to open the file (it's an image), Windows reports a problem, that it can't open it, as you'd expect... but obviously that doesn't get caught in the code. 
Any suggestions?

**Comment by davetoland** [comment]
![image](https://user-images.githubusercontent.com/19878260/75984740-deb14200-5ee2-11ea-9ed8-65223a1dbc79.png)

**Comment by davetoland** [comment]
For anyone interested, I've got a workaround by coding it up slightly differently, and not using the DownloadData method at all. It seems like this is a bug to me, especially as we're only getting a byte array in return with no way to inspect a success or realise we've got response text as opposed to our intended data after hitting an exception, so I'm interested to hear what the RestSharp team say about this...

Anyway, this the workaround:
```
try
{
    var client = GetRestClient(baseUri, credential);
    var response = client.Execute(new RestRequest(downloadLink));

    if (response.IsSuccessful && response.RawBytes != null)
    {
        File.WriteAllBytes(localPath, response.RawBytes);
        result = true;
    }
    else
        throw new JiraResponseException($"The file download failed. {response.ErrorMessage}", HttpStatusCode.BadRequest);

}
```

**Comment by davetoland** [comment]
@alexeyzimarev

**Comment by doublehelix** [comment]
This is compounded by the fact that if you're _streaming_ a large file directly to disk with a stream-writer, you can't tell what you've streamed.
e.g.:
```csharp
var tempFilename = Path.GetTempFileName();
using (var writer = File.OpenWrite(tempFilename))
{
    var client = new RestClient(baseUri) { ThrowOnAnyError = true };
    var request = new RestRequest(path, Method.GET)
    {
        ResponseWriter = responseStream =>
        {
            using (responseStream) { responseStream.CopyTo(writer); }
        }
    };

    try
    {
        var response = client.DownloadData(request, true); // "response" here is always "null" as we're streaming to disk, not a variable.
    }
    catch (Exception)
    {
        File.Delete(tempFilename);
        throw;
    }
}
```

No exception... nothing indicating `404` / `500` (etc.) error, or any other kind of problem. As long as it's a valid web response, we have to physically inspect the contents of the file written to see what we got. I've tested with 404 errors, as well as bad "Accept" header for the content type, both of which are failure response codes from the server, but the client has no way to detect/indicate a failure.

**Comment by mhornbacher** [comment]
Should this still be open?
