### ISSUE TITLE
RestREsponse.Content returns string with UTF-8 BOM character

### ISSUE THREAD

**Issue by Lechus** [restsharp/RestSharp#826]
Hi,

Is this by design? Is there an option to not return UTF8 string with BOM character?

**Comment by hallem** [comment]
The content should just be what is returned from the server endpoint you called.  If they sent the BOM then the library wont remove it.

**Comment by alexeyzimarev** [comment]
https://datatracker.ietf.org/doc/rfc8259/?include_text=1

The JavaScript Object Notation (JSON) Data Interchange Format
RFC 8259

Paragraph 8.1

> Implementations MUST NOT add a byte order mark (U+FEFF) to the beginning of a networked-transmitted JSON text. In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

**Comment by alexeyzimarev** [comment]
So we MAY try fixing it, but, essentially, the server MUST NOT send it.
