### ISSUE TITLE
Impossible to make request with unencoded slash %2F in URL. 

### ISSUE THREAD

**Issue by benbenwilde** [restsharp/RestSharp#828]
.NET 4.6
RestSharp 105.2.3

If I supply %2F to the RestRequest as the resource, it is converted to / which is undesirable.
`new RestRequest("awesome/great%2Fcool");` => `awesome/great/cool`
If I add a UrlSegment with a regular / in it, it stays as a / which is even more undesirable!
`new RestRequest("awesome/{Id}").AddUrlSegment("Id", "great/cool");` => `awesome/great/cool`
If I try to workaround by supplying %2F, it results in double encoding (%252F) which is correct but I still can't get %2F into the url.

Notably - `new Uri("awesome/great%2Fcool")` => `awesome/great/cool`
I guess that changed in .NET 4.5

**Comment by benbenwilde** [comment]
Update - The above is true when I'm using resharper's n-unit test runner. My test must be running with CLR 4.0, thereby causing this issue. But it works fine when the app actually runs. It could be useful to document this scenario.

**Comment by jairbubbles** [comment]
Maybe we should hack the code as described here to get the same behavior between different versions of .net ?
http://blogs.perpetuumsoft.com/dotnet/about-escaping-slashes-in-net/

**Comment by alexeyzimarev** [comment]
I am not sure if this is still a valid issue, but using custom encoders for URL and query parameters everything can be solved (`UseUrlEncoder` and `UseQueryEncoder`)
