### ISSUE TITLE
Need option to quote Decimals etc. in JSON for OData compatibility

### ISSUE THREAD

**Issue by richardacre** [restsharp/RestSharp#833]
OData requires that Decimal and Int64 data is enclosed in quotes, so when using RestSharp I'm getting exceptions. Could do with a compatibility option if possible

https://blogs.msdn.microsoft.com/marcelolr/2010/07/15/odata-decimal-and-json/

**Comment by alexeyzimarev** [comment]
I'm afraid you need to use a custom serializer for this, see https://github.com/restsharp/RestSharp/wiki/Serialization
