### ISSUE TITLE
AddJsonBody will convert DateTime to UTC 

### ISSUE THREAD

**Issue by LyricsYo** [restsharp/RestSharp#834]
example:
`request.AddJsonBody(new { date=DateTime.Now });`

**Comment by hallem** [comment]
can you be more clear on your problem please?

**Comment by xbuilder** [comment]
My Time Zone is +8:00, when i Post DateTime type data '2016-5-1 8:00' to WebApi ,it will change to '2016-5-1 0:00'

**Comment by dschuesae** [comment]
Same issue here. AddJsonBody automatically convert date to UTC time.

**Comment by dshamim** [comment]
it's very annoying, noticed the issue today - I'm doing a Post using object list, adding it using AddJsonBody, it serializes dates in the list objects as UTC

**Comment by Lechus** [comment]
Adding an object with two DateTime properties using addJsonBody()
One dateTime is serialized as one hour in past (although my pc is in UTC timezone)
The other is correctly serialized.

Why?

**Comment by Lechus** [comment]
RestSharp.Serializers.JsonSerializer()
Having DateTimes in C# without Kind specified:
["1975-01-03T00:00:00Z","1974-11-30T00:00:00Z","1974-01-13T00:00:00Z","1970-12-30T00:00:00Z","1954-10-01T01:00:00Z"]

Serializing them to Json is giving for some dates time one hour in past:
["1975-01-03T00:00:00Z","1974-11-30T00:00:00Z","1974-01-13T00:00:00Z","1970-12-30T00:00:00Z","**1954-10-01T00:00:00Z**"]

If all DateTime will be specified with UTC:
newX = DateTime.SpecifyKind(x, DateTimeKind.Utc)

then serialization is correct:
["1975-01-03T00:00:00Z","1974-11-30T00:00:00Z","1974-01-13T00:00:00Z","1970-12-30T00:00:00Z","1954-10-01T01:00:00Z"]

Somehow Serializer picks some dateTimes and substract time?

**Comment by juancash** [comment]
Hi,
seems that when use request.AddBody all datetime properties are converted to UTC. Using request.AddObject(myObject) instead of request.AddBody(myObject) works for me.
Regards.

**Comment by 564064202** [comment]
@hallem 
My Time Zone is +8:00, when I Post DateTime type data '2017-5-1 18:00' to WebApi ,it will change to '2017-5-1 8:00' use AddJsonBody. How to resovle this bug? What's the diffrence between AddBody and AddJsonBody

**Comment by juancash** [comment]
@hallem Have you try AddObject?

**Comment by 564064202** [comment]
@juancash there is something wrong with AddObject
when it processes List<MyClass>
parameters number doesn't match

**Comment by juancash** [comment]
@hallem OK sorry. It's not a solution but to avoid this problem I'm not working with datetime. I'm using epoch. Seems that this project doesn't have support any more.

**Comment by VictorK** [comment]
Noticed that a new issue was created (https://github.com/restsharp/RestSharp/issues/1056) for the same, anyone know if this will be fixed or if it's part of the design?

**Comment by Wbenay** [comment]
We are already in 2018 and to this day I have not seen any solution to the problem. I had to use Newtonsoft!

**Comment by alexeyzimarev** [comment]
@Wbenay so what is your point?

**Comment by Zefek** [comment]
I use AddParameter method.
request.AddParameter(new Parameter { Name = "application/json", Type = ParameterType.RequestBody, Value = Newtonsoft.Json.JsonConvert.SerializeObject(Data) });
It works for me.

**Comment by Zefek** [comment]
I think there is chance to use own serializer through JsonSerializer property. In default serializer there is conversion into universal time (SimpleJson.cs, line 1473). This method is virtual so it could be overriden in inherited class and could be used by JsonSerializer property.

**Comment by alexeyzimarev** [comment]
We have no plans to start changing the SimpleJson code. I would advise you to assign a custom (Json.Net) serializer to the RestClient instance, it is very easy to do now. From v107 we will get Json.Net back anyway.

**Comment by Wbenay** [comment]
Em ter, 29 de mai de 2018 11:12, Alexey Zimarev <notifications@github.com
escreveu:

**Comment by hawkxu** [comment]
This is just a sample, hope it will be a bit useful

```
  class DateJsonSerializerStrategy : PocoJsonSerializerStrategy {

    private static readonly string DATE_FORMAT = @"yyyy-MM-dd\THH:mm:ss";

    protected override bool TrySerializeKnownTypes(object input, out object output) {
      if (input is DateTime) {
        output = ((DateTime)input).ToString(DATE_FORMAT);
        return true;
      }
      if (input is DateTimeOffset) {
        output = ((DateTimeOffset)input).ToString(DATE_FORMAT);
        return true;
      }
      return base.TrySerializeKnownTypes(input, out output);
    }

    public override object DeserializeObject(object value, Type type) {
      if (value != null && type != null) {
        string str = value as string;
        if (str != null && str.Length > 0) {
          if (type == typeof(DateTime) || GetNullableType(type) == typeof(DateTime))
            return DateTime.ParseExact(str, DATE_FORMAT, CultureInfo.InvariantCulture);
          if (type == typeof(DateTimeOffset) || GetNullableType(type) == typeof(DateTimeOffset))
            return DateTimeOffset.ParseExact(str, DATE_FORMAT, CultureInfo.InvariantCulture);
        }
      }
      return base.DeserializeObject(value, type);
    }

    private Type GetNullableType(Type type) {
      return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>)
        ? Nullable.GetUnderlyingType(type) : null;
    }
  }
```
and add below code at start

```
SimpleJson.CurrentJsonSerializerStrategy = new DateJsonSerializerStrategy();
```

Like the RestSharp source code, you can use multiple formats instead of one format `DATE_FORMAT`, only a little modification is needed

**Comment by chpiter** [comment]
+1
tell me why ?
