### ISSUE TITLE
Issue with JsonSerializer and DateTimeOffset

### ISSUE THREAD

**Issue by adamkes** [restsharp/RestSharp#835]
Hi Guys,

I live in the UK and I have notice the following problem. 

When I try to do json serialization from DateTimeOffset with built-in serializer I get incorrect result

DateTimeOffset - {01/04/2016 00:00:00 +01:00}

RestSharp 105.2.3.0 using built-in JsonSerializer - '2016-03-31T23:00:00Z'
RestSharp 105.2.3.0 using Newtonsoft.Json 8.0.0.0 - '2016-04-01T00:00:00+01:00'

I`m expecting to get similar results to the ones produced by Newtonsoft.Json

Thanks,

Adam

**Comment by hallem** [comment]
You can change the json serializer that the library uses to newtonsoft if you'd like.  The library that is currently being used has some limitations.  I'm trying to get it replaced but haven't had time to get to it.

**Comment by adamkes** [comment]
Hi Mike,

I have ended up actually doing it. I have noticed that in the past you have used Newtonsoft as default serializer. What was the reason to remove that dependency?

Adam

**Comment by alexeyzimarev** [comment]
Yes, it is a known issue but we won't be fixing SimpleJson. The issue can be easily resolved by using Json.Net as a serializer.
