### ISSUE TITLE
JSON Deserializer fails (without error) if the object model does not have { get; set; }

### ISSUE THREAD

**Issue by heldersepu** [restsharp/RestSharp#840]
If the object model does NOT contains the { get; set; } the IRestResponse.Data is returned with default values, Here is an example:
https://github.com/heldersepu/csharp-proj/blob/master/JsonDeserialize/JsonDeserialize/UtilClasses.cs
The response for BaseAccount2 is:
`{"Email":null,"Active":false,"CreatedDate":"0001-01-01T00:00:00"}`

I've seen cases where the model contains an IList the response contains an err like:
`ErrorException = {"Cannot create an instance of an interface."}`
I think this case should also return an error

**Comment by behoyh** [comment]
How are you casting the data from IRestResponse.Content into these classes?

**Comment by heldersepu** [comment]
static async Task<T> UseRestSharp<T>(string resource)
        {
            var request = new RestRequest(resource, Method.GET);
            request.RequestFormat = DataFormat.Json;
            request.OnBeforeDeserialization = r => { r.ContentType = "application/json"; };
            var resp = await new RestClient(url).ExecuteTaskAsync<T>(request);
            return resp.Data;
        }

**Comment by heldersepu** [comment]
That last coment is missing characters, here is a link to my code reproducing this issue:
https://github.com/heldersepu/csharp-proj/blob/master/JsonDeserialize/JsonDeserialize/Program.cs

**Comment by behoyh** [comment]
Thanks, I'll investigate this.

**Comment by behoyh** [comment]
Thanks, I will Investigate this.

**Comment by behoyh** [comment]
What are the contents of BaseAccount.json?

**Comment by heldersepu** [comment]
You should dowload the entire solution:
https://github.com/heldersepu/csharp-proj/tree/master/JsonDeserialize

**Comment by heldersepu** [comment]
And just in case, here is a direct link to the file you requested:
https://github.com/heldersepu/csharp-proj/blob/master/JsonDeserialize/JsonDeserialize/BaseAccount.json

**Comment by behoyh** [comment]
After removing dependencies form `Newtonsoft.Json`, I have reproduced the behavior. I will look into it.

**Comment by heldersepu** [comment]
Good.

I added newtonsoft to prove that the JSON file deserializes correctly.

After removing dependencies form Newtonsoft.Json, I have reproduced the
behavior. I will look into it.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/restsharp/RestSharp/issues/840#issuecomment-221887869>
