### ISSUE TITLE
Unable to add restsharp package to a new project in xamarin studio

### ISSUE THREAD

**Issue by jeevanrd** [restsharp/RestSharp#844]
Getting error saying " Could not install package 'RestSharp 105.2.3'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Pls help

**Comment by dellert** [comment]
same error

**Comment by alexeyzimarev** [comment]
Use the new version (106) that is .NET Standard 2.0 compatible
