### ISSUE TITLE
'Invalid JSON String' for POST request with application/json content type

### ISSUE THREAD

**Issue by dhrushilbadani** [restsharp/RestSharp#851]
So I was making a POST request to an endpoint that needs `application\json.` I initialized the RestClient and request and used 
`request.AddHeader("Content-Type","application/json")`
and made subsequent calls to `request.AddParameter()` but the error I get is `Invalid JSON String` with a status code of `UnsupportedMediaType` and also mentions `expected application/json or text/json body.` Any idea of what's going on?

I tried using a custom serializer as well, but to no avail. The request works successfully on Chrome's Advanced Rest Client.

**Comment by behoyh** [comment]
I was not able to replicate this issue. Do you have any more information on what you were trying to do?

**Comment by dhrushilbadani** [comment]
So, I found the workaround -- apparently `request.AddParameter("Content-Type", "application/json")` does not work, which meant my request body was not in JSON. http://itanex.blogspot.co.at/2012/02/restsharp-and-advanced-post-requests.html had a solution to this. Is there a more 'standard' way to add it the Content-type header?

**Comment by Danthar** [comment]
I have exactly the same problem:

    var client = new RestClient(endpoint);
                
                //client.AddDefaultHeader("Content-Type", "application/json"); //I expect this to be enough
                var req = new RestRequest("api/values");
                req.AddHeader("Content-Type", "application/json"); //but its not so i tried adding it here
                req.AddParameter("application/json", "test", ParameterType.RequestBody); //which didnt work so i tried adding it here
                req.Method = Method.POST;
                
                var resp = client.Execute(req);


The above described variations of me, trying to send a raw string to a REST api. Do not work. 
It does not work, because the RestSharp api does not set the Content-Type header. If i dump the entire request on the server side, it clearly shows that no Content-Type header is set.

I am not sure why this is happening. But it basically bars me from using the library.

**Comment by alexeyzimarev** [comment]
Thanks for reporting. I think the request format need to be set more conveniently.

**Comment by alexeyzimarev** [comment]
It is actually all fixed. Use AddJsonBody and both the request format and content type will be set for you
