### ISSUE TITLE
How can I get when ...

### ISSUE THREAD

**Issue by Gurcano** [restsharp/RestSharp#852]
Hi guys. I have a trouble in my project. 

I' m trying to get data from a site using RestSharp. But the site is using 2 of pages for reporting data.

Page1 taking parameters, storing .net SessionID to a cookie and redirecting to Page 2
Page2 taking cookie value and reporting.

When I try to take data; RestSharp raising "HTTP 500" error. 

Cause;
response = client.Execute(request)   don' t fit to this site. 
Request and response pages different. Page1 redirecting ...

What can I do ? Any suggestion ?

**Comment by Ariex** [comment]
have you tried like below?
``` C#
response1.Cookies.ForEach(c=>{
    request2.AddCookie(c.Name, c.Value);
});
```

and what "don't fit to this site" means?

**Comment by alexeyzimarev** [comment]
RestSharp is designed to work with REST APIs, where you send a request and get a response. You can try using HttpClient if you are crawling web pages.
