### ISSUE TITLE
Can I execute a JavaScript Code ?

### ISSUE THREAD

**Issue by Gurcano** [restsharp/RestSharp#853]
I wan' t to run a JavaScript using RestSharp. I need it for selecting some controls.
Is this possible ?

**Comment by KOTRET** [comment]
invalid issue
You are creating Requests to the server with this lib. This has absolutely **nothing** to do with executing javascript: this lib is not a browser.
But you can execute some JS if running nodejs-server that will process the request. :smirk:

**Comment by alexeyzimarev** [comment]
No, you cannot execute JS code using RestSharp.
