### ISSUE TITLE
Requests take a very long time with the latest Xamarin version

### ISSUE THREAD

**Issue by kowsari** [restsharp/RestSharp#857]
I downloaded the latest Xamarin Studio/IOS versions today (Stable Cycle 7) and async requests using RestSharp take almost a minute to complete.

I trace and can see that the requests happens correctly and the response is sent right away the IOS app written in Xamarin C# but the Async handler is not called until a minute later.

Any thoughts would be welcome.

**Comment by crbaker** [comment]
I am having the same issue, it's not on all requests but appears to happen on quite large JSON responses (mine is about 55kb).

This is not a problem with Droid, only iOS.

**Comment by Salat39** [comment]
Any thoughts how to fix this?

**Comment by Salat39** [comment]
Xamarin ModernHttpClient can help you resolve this issue.

**Comment by poimis** [comment]
@Salat39 How do you use ModernHttpClient with RestSharp? I have found that RestSharp.Portable uses HttpClientFactory that can be set to return a client with ModernHandler but haven't found yet a way to do it with Restsharp.

**Comment by alexeyzimarev** [comment]
I think it became obsolete by now since it is platform specific. If you can still reproduce this with .NET Standard library - please reopen the issue and provide a code sample, ideally a Xamarin project that builds.
