### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'RestSharp, Version=105.2.3.0

### ISSUE THREAD

**Issue by jamesytl** [restsharp/RestSharp#858]
I have added RestSharp into one of my windows form application. 
When I attempt to send a **json http post** after launch it as exe. file. it shows the below error:

> 
> System.IO.FileNotFoundException: Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
> File name: 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null'

May I know what causes this exception and how do I fix it? Thanks in advance.

**Comment by jamesytl** [comment]
I have checked the reference which shows that it reference to the RestSharp version 105.2.3.0, Copy Local is already set to True and also tried again by adding newtonsoft.json but can't as well.

**Comment by jamesytl** [comment]
Nvm fixed. Just found that I have the different restsharp.dll version in other PC.

**Comment by hunterya** [comment]
I also met this problem. How did you solve it
