### ISSUE TITLE
All requests are doubled using NTLM Authenticator

### ISSUE THREAD

**Issue by simpuc** [restsharp/RestSharp#859]
Hello,
I have a question and I am not sure this is an issue or a feature.

When I use 
client.Authenticator = new NtlmAuthenticator();
every http request is doubled. The first is with no authentication and the second is with authentication.
It works but the time to complete a request is double and so the time to complete 100 requests.

Is it possible to send authentication in the first request?

Thank you for you help
Best regards
Simone

**Comment by G-Playa** [comment]
Sounds like a function f(x)
