### ISSUE TITLE
File Upload - multipart/form-data

### ISSUE THREAD

**Issue by fiftycy** [restsharp/RestSharp#860]
Hello am trying to figure out how to make this work. I want to do this request.

$ curl https://someaddress.com/ 
-F parameter1='abc123' \
-F file=@myfile.someextension \
-F parameter2='abc123'

And this is the code i use 

`var client = new RestClient("https://someaddress.com");`

`RestRequest request = new RestRequest("/",Method.POST);`
`request.AddHeader("Content-Type", "multipart/form-data");`
`request.AddHeader("Accept", "application/json");`

`request.AddParameter("parameter1", "abc123");`
`request.AddParameter("parameter2", "abc123");`

`request.AddFile("fileData", fileStream.CopyTo, filename);`
`//request.AddFile("fileData", fileByteArray, filename);`

`var response= client.Execute(request);`

Am always getting response with status code 0. 
{"The underlying connection was closed: An unexpected error occurred on a send."}

This is the stacktrace that i can see inside the response ErrorException field.

`InnerException = {"Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."}`
`at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)`
`at System.Net.HttpWebRequest.GetRequestStream()`
`at RestSharp.Http.WriteRequestBody(HttpWebRequest webRequest)`
`at RestSharp.Http.PostPutInternal(String method)`

Any help?

**Comment by ParanoikCZE** [comment]
Hi, 
experiencing same issue (currently investigating), but seems that there are missing boundary followed with two dashes in the end of the request generated by RestRequest. Every server we tested reacts different way to this.

**Comment by ParanoikCZE** [comment]
For us, it was really caused by missing boundary, however issue was already fixed. Downloading and building source fixed the issue.

**Comment by fiftycy** [comment]
i have tried to download and build the project but it didnt work. After some time i found out that the problem was the security protocol. So i have added this line and it worked.
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

**Comment by khaledAX** [comment]
hi @fiftycy . would you mind to point to the code where you have added the code to make it work? 
Did you have to rebuild after that ?

**Comment by tomzo** [comment]
I had similar problem when using version `105.2.3`.
During POST  multipart/form-data using restsharp to nancy server, the inner exception was `Cannot close stream until all bytes are written`.
Building from master solves it.

**Comment by StefanoD** [comment]
Why is this still open?
