### ISSUE TITLE
Release req

### ISSUE THREAD

**Issue by ParanoikCZE** [restsharp/RestSharp#861]
Hi,

experiencing issues with released version but it's already fixed in master branch. We can move built RS to our internal Nuget source but we prefer to stay on official.
So, is it possible to release?

Thanks.

**Comment by DaveHogan** [comment]
The latest NuGet package (105.2.3) was released 26th August 2015.
There's been some great features and fixes since then. 

Is there any chance we could get a updated NuGet package please?
Specifically I'm interested in https://github.com/restsharp/RestSharp/pull/811

**Comment by darxis** [comment]
I am also interested in a new nuget publish...

**Comment by alexeyzimarev** [comment]
The release will be done soon (before November) but the scope is larger than some would expect :)
