### ISSUE TITLE
The execute method get correct response data, but null in json object 

### ISSUE THREAD

**Issue by shyandsy** [restsharp/RestSharp#865]
## Problem

why the customer object inresponse.Data always null？
## situation

after var response = client.Execute<T>(request)
response.Content = "{\"code\":0,\"customer\":{\"customer_id\":\"1002\",\"business_id\":\"2\",\"card_id\":\"A1A2A3A4\",\"total_credit\":\"5\",\"date_registered\":\"2016-07-13 00:51:38\",\"date_updated\":\"2016-07-13 00:51:38\"}}"

but response.Data = { code = 0, customer = null}
![image](https://cloud.githubusercontent.com/assets/5271457/16897041/4852544a-4b6b-11e6-8364-a305e06f09a7.png)
## Usage

``` c#
public Customer GetCustomerByCustomerId(string customerId)
        {
            Customer customer = null;
            GetCustomerByCustomerIdResponse response;

            var request = new RestRequest(Method.POST);
            request.Resource = "customer";
            request.RootElement = "customer";
            request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };

            request.AddParameter("card_id", customerId);

            response = Execute<GetCustomerByCustomerIdResponse>(request);

            if (response.code == 0) //successful
            ...........................
```

``` c#
public T Execute<T>(RestRequest request) where T : new()
        {
            var client = new RestClient();
            client.BaseUrl = new System.Uri(_baseUrl);
            client.AddHandler("text/plain", new JsonDeserializer());

            client.Authenticator = new HttpBasicAuthenticator(_token, "");
            //request.AddParameter("AccountSid", _accountSid, ParameterType.UrlSegment); // used on every request

            var response = client.Execute<T>(request);

            if (response.ErrorException != null)
            {
                const string message = "Error retrieving response.  Check inner details for more info.";
                var twilioException = new NetworkException();//ApplicationException(message, response.ErrorException);
                throw twilioException;
            }
            return response.Data;
```

``` c#
public class Customer
    {
        public string customer_id { get; set; }
        public string business_id { get; set; }
        public string card_id { get; set; }
        public string total_credit { get; set; }
        public string date_registered { get; set; }
        public string date_updated { get; set; }
    }

    public class GetCustomerByCustomerIdResponse
    {
        public int code { get; set; }
        public Customer customer { get; set; }
    }
```
## The struct of response data

``` js
{
  "code": 0,
  "customer": {
    "customer_id": "1006",
    "business_id": "2",
    "card_id": "12245608",
    "total_credit": "0",
    "date_registered": "2016-07-13 05:42:45",
    "date_updated": "2016-07-13 05:42:45"
  }
}

```

**Comment by ParanoikCZE** [comment]
Hi, 
actually you are getting whole object as new, not only customer. But because code is int, default is 0. So, I recommend to not use 0 as OK result. Or even better, exclude code from json and use common http status codes?
To your problem, cannot say exactly, quick checked on mine and it's deserialized correctly. Maybe there is some issue in headers, but I've also made some changes and wasn't able to break it. So, I can only recommend to download RS source and track deserialization to the issue.

**Comment by ParanoikCZE** [comment]
Hi again,
tried once more with exact your code .. and it doesn't work .. So, my research leaded me to:
request.Resource = "customer";
request.RootElement = "customer";
you are marking root element as Customer, but deserializing to GetCustomerByCustomerIdResponse

So, RS will get only customer object from content and trying to create GetCustomerByCustomerIdResponse object from it. Well, it won't fit, so default. To fix it, deserialize to Customer class or just comment those two lines, then it will work. (Tested both.)

**Comment by mowcixo** [comment]
That's probably related with #1306

**Comment by alexeyzimarev** [comment]
Documented on how to troubleshoot serialization issues.
