### ISSUE TITLE
Encoding set problem

### ISSUE THREAD

**Issue by shanvenleo** [restsharp/RestSharp#867]
HttpResponse.cs
public string Content
 {
            get { return this.content ?? (this.content = this.RawBytes.AsString()); }
 }

when i set 
`RestClient.Encoding = Encoding.GetEncoding("gb2312");`
this method called AsString() and use Encoding.UTF8,not use the RestClient.Encoding value

an alternative 
`string content = Encoding.GetEncoding("gb2312").GetString(response.RawBytes);`

**Comment by maobiwen** [comment]
看样子又是一个中国的开发者啊。
尼玛感觉我也被坑了。调试了好久。。。。

**Comment by alexeyzimarev** [comment]
We cannot guarantee that the response encoding matches the client encoding. However, we will try parsing the response encoding and fall back to UTF8 if we can't.

**Comment by ueberboss** [comment]
The current fix causes first chance exceptions when a Content-Encoding is not specified. See: https://stackoverflow.com/questions/55052160/restsharp-first-chance-exception-am-i-using-it-wrong

A possible fix for this:

```
public static string AsString(this byte[] buffer, string encoding)
{
	Encoding enc;
	if (string.IsNullOrEmpty(encoding)) // avoid an unnecessary exception
	{
		enc = Encoding.UTF8;
	}
	else
	{
		try
		{
			enc = Encoding.GetEncoding(encoding);
		}
		catch (Exception)
		{
			enc = Encoding.UTF8;
		}
	}

	return AsString(buffer, enc);
}
```

in \RestSharp-master\RestSharp\Extensions\MiscExtensions.cs

**Comment by Robelind** [comment]
This issue needs to be re-opened.

**Comment by kealist** [comment]
@alexeyzimarev  I am getting exceptions when content encoding is not specified as well

**Comment by carlhoogstoel** [comment]
I have to agree with the OP. The AsString method in the MiscExtensions.cs needs to be fixed.

**Comment by MichelMichels** [comment]
I get the same exceptions because my API provider can't properly send the content-type in the response.

**Comment by jiangfeng0103** [comment]
> 看样子又是一个中国的开发者啊。
> 尼玛感觉我也被坑了。调试了好久。。。。

这个问题解决了吗？现在还是有这个问题

**Comment by maobiwen** [comment]
> > 看样子又是一个中国的开发者啊。
> > 尼玛感觉我也被坑了。调试了好久。。。。
> 
> 这个问题解决了吗？现在还是有这个问题

解决了。自己修改了一下源代码。加了一个字符集参数的判断进去

**Comment by alexeyzimarev** [comment]
I am wondering why so many people are having this issue and nobody ever submitted a PR?

Nevertheless, it's not an unhandled exception, it doesn't throw in your face. It would be nice to avoid throwing but again, it is not producing anything more than an inconvenience and some performance degradation.

**Comment by maobiwen** [comment]
> I am wondering why so many people are having this issue and nobody ever submitted a PR?
> 
> Nevertheless, it's not an unhandled exception, it doesn't throw in your face. It would be nice to avoid throwing but again, it is not producing anything more than an inconvenience and some performance degradation.

I fixed it，but not submit。it is an simple problem， everyone can fixed it himself

**Comment by alexeyzimarev** [comment]
I fixed it. Should be fine in 106.11.3

**Comment by maobiwen** [comment]
> I fixed it. Should be fine in 106.11.3

think you for commit
