### ISSUE TITLE
Json Data in response is coming Null

### ISSUE THREAD

**Issue by roopeshkumar** [restsharp/RestSharp#868]
Hi,
   Am fairly new to Restsharp. Currently using RestSharp in my MVC 5 project and doing the below and even though I have data, am seeing null in response.Data. Can you please let me know if am doing anything wrong?

```
 private RestClient client;
        private string url = "http://localhost:58482/api/tblObjectPermission/GetAlltblObjectPermission"; 
        public TblObjectPermissionClient()
        {
            client = new RestClient(url);
        }
        public IEnumerable<tblObjectPermission> GetAlltblObjectPermission()
        {
            var request = new RestRequest("api/serverdata", Method.GET);
            request.RequestFormat = DataFormat.Json;

        var response = client.Execute<List<tblObjectPermission>>(request);

        if (response.Data == null)
            throw new Exception(response.ErrorMessage);
        return response.Data;
    }
```

Model class is
```
 public partial class tblObjectPermission
    {
        public int ObjectPermissionID { get; set; }
        public bool DeleteYN { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> SubscriberID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ObjectAccessID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<int> ChangeUser { get; set; }
        public byte[] RowVersion { get; set; }
        public virtual tblObject tblObject { get; set; }
        public virtual tsysObjectAccess tsysObjectAccess { get; set; }
    }
```

Appreciate your help.

Thanks
Roopesh

**Comment by Moykn** [comment]
Hi, i'm using restsharp and came to the same problem. To overcome this, i've done something like:

 ```
var response = client.Execute(request);
var objectPermissions =  
           Newtonsoft.Json.JsonConvert.DeserializeObject<List<tblObjectPermission>>(response.Content);
return objectPermissions
```
It' just a workaround, but it's working for me.

**Comment by mclark1129** [comment]
@roopeshkumar The first thing I would check is the content-type of the HTTP response you are getting back to make sure it matches the actual format of your response.  If your server is returning 'text/html' for everything, but returning a JSON payload, RestSharp will not know how to properly deserialize it out of the box.

**Comment by Lechus** [comment]
@roopeshkumar show RAW response.

**Comment by willtonic** [comment]
See http://stackoverflow.com/questions/10324526/restsharp-not-deserializing-json-object-list-always-null

After you declare your request, try adding a line to explicitly specify the content type as JSON:

```
var request = new RestRequest(Method.GET);
request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };

```
Worked for me.

**Comment by Van-Dame** [comment]
It's possible that your `byte[] RowVersion` is throwing it off. Changing it to `List<byte>` may help, as it did with my case. I read somewhere that RestSharp cannot deserialize arrays.

**Comment by noufionline** [comment]
Hi @Van-Dame,
Is byte[] RowVersion conversion is a known issue? will this be resolved any soon?

**Comment by alexeyzimarev** [comment]
SimpleJson serialization will not be amended because it is not our code.

**Comment by burekas7** [comment]
> See http://stackoverflow.com/questions/10324526/restsharp-not-deserializing-json-object-list-always-null
> 
> After you declare your request, try adding a line to explicitly specify the content type as JSON:
> 
> ```
> var request = new RestRequest(Method.GET);
> request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };
> ```
> 
> Worked for me.

Thanks. It solved my problem too.
But why should I need to add this line while it said that it should do it automatically here:
https://restsharp.dev/getting-started/getting-started.html#content-type

By the way, is there any difference between using PostAsync<T> or ExecuteAsync<T>?

**Comment by alexeyzimarev** [comment]
@burekas7 response content type and request content type are two different things. When using `AddJsonObject` we correctly set the request content type. But, we send the list of accepted response types according to the available deserialisers. Normally, it's JSON and XML by default. The server is responsible for setting the correct response content type. If the server doesn't do that, you use the workaround described.

**Comment by alexeyzimarev** [comment]
And, `PostAsync` does the POST request, whilst `ExecuteAsync` needs the request type as a parameter. `PostAsync` is just a convenient wrapper for `ExecuteAsync`.
