### ISSUE TITLE
Do not Serialize Null Properties on AddJsonBody

### ISSUE THREAD

**Issue by b4rj** [restsharp/RestSharp#870]
Hey guys, is there a way to not serialize null Properties?

I found this tutorial: 

http://www.opennetcf.com/2013/08/22/restsharp-dont-serialize-null-properties/

but there is no "Request.JsonSerializer.Options"

Take Care guys

**Comment by alexeyzimarev** [comment]
The PR #404 was never accepted since it changed SimpleJson source and we do not want that, we just keep a copy of it and we don't maintain it. I suggest using Json.NET as a serialiser to fix this issue.
