### ISSUE TITLE
Upload large file with Multi Part Form Data using REST API

### ISSUE THREAD

**Issue by rajkumar-qsg** [restsharp/RestSharp#871]
Hi, 

I am developing a small application to upload large file using an Rest API.  The Rest API accepts multi part form data.  The upload should happen in stream.  I am using RestSharp to invoke this API.  I could upload small files, but when tried to upload 1GB file, it is taking longer time and i could not see any file in the destination.  I am not sure, if i am using streaming or loading complete data into memory.

Please find my code below.  Please share a C# sample code to upload large file stream using multi part form data.  Is there anything i am missing in the below code:

var client = new RestClient("https://xxxxxxxxxxxxx/UploadFile");
RestRequest request = new RestRequest("/", Method.POST);
request.AddHeader("FileName", txtFileName.Text.Trim().ToString());
request.AddHeader("Content-Type", "multipart/form-data");
request.AddFile("fileData", txtFilePath.Text.Trim().ToString(), );
request.ReadWriteTimeout = 2147483647;
request.Timeout = 2147483647;
var response = client.Execute(request);

Thanks,
Rajkumar

**Comment by alexeyzimarev** [comment]
Use the `AddFile` overload that accepts the `Action<Stream>` to write to the request stream directly.

**Comment by ninjadude333** [comment]
any example for syntax using the action<stream> ?

**Comment by alexeyzimarev** [comment]
It _always_ uses the `Action`. Just check the source code of `FileParameter`
