### ISSUE TITLE
Caching doesn't work when running as a service

### ISSUE THREAD

**Issue by johnfettig** [restsharp/RestSharp#877]
RestSharp uses HttpWebRequest, which by default uses Microsoft.Win32.WinInetCache. This is documented to not work when instantiated by a service: https://support.microsoft.com/en-us/kb/238425

There should be some way to configure HttpWebRequest to use a cache that works when instantiated by a service.

**Comment by alexeyzimarev** [comment]
Definitely this will not work on xplat so we will not work in this direction. We also plan to get rid of WebRequest due to compatibility issues.
