### ISSUE TITLE
NullReferenceException from HttpBasicAuthenticator when a parameter name is null

### ISSUE THREAD

**Issue by tswett-sh** [restsharp/RestSharp#881]
The method `RestSharp.Authenticators.HttpBasicAuthenticator.Authenticate` throws a `NullReferenceException` when the `request` parameter contains a `Parameter` whose `Name` property is `null`.

The exception seems to be thrown at this line:

```
if (!request.Parameters.Any(p => p.Name.Equals("Authorization", StringComparison.OrdinalIgnoreCase)))
```

This could be fixed by either using the static version of `String.Equals`, or switching the order of the arguments:

```
if (!request.Parameters.Any(p => String.Equals(p.Name, "Authorization", StringComparison.OrdinalIgnoreCase)))
if (!request.Parameters.Any(p => "Authorization".Equals(p.Name, StringComparison.OrdinalIgnoreCase)))
```

**Comment by alexeyzimarev** [comment]
Can just use null propagation
