### ISSUE TITLE
Get actual raw request/response

### ISSUE THREAD

**Issue by sonicflare** [restsharp/RestSharp#885]
Hello,
I want to log actual http raw request/response that have been sent out to minimize troubleshooting time. Is there a way to do that?

**Comment by dgritsko** [comment]
This would be really valuable.

**Comment by vk5880** [comment]
Is it still not availiable?

**Comment by vk5880** [comment]
Please make it, so simple...

**Comment by alexeyzimarev** [comment]
@vk5880 if it is so simple, we won't you make it? I will happily accept your PR.

**Comment by alexeyzimarev** [comment]
Btw, `response.RawBytes` has always been there...

**Comment by seannybgoode** [comment]
@alexeyzimarev  - not the case for request.RawBytes though

**Comment by ferib** [comment]
@alexeyzimarev those `response.RawBytes` just seem to represent `response.Content`, but is there any other method to obtain the actual "raw" data of the request? Data that's not been deserialized?

**Comment by alexeyzimarev** [comment]
ok, so it's about the request, right? how deserialisation applies to the request? requests don't get deserialised, it's the opposite.

**Comment by ferib** [comment]
@alexeyzimarev Oh okay thanks for your answer, I tried to deserialize before using ``RestClient.Execute<string>(request)`` which didn't work, so I ended up using ``JsonConvert.DeserializeObject<string>(response.Content)`` to get the "raw" string from the response.

**Comment by alexeyzimarev** [comment]
I am not sure why would you are trying to do. Deserialise to a string? The content is already a string, what’s there to deserialise?

**Comment by ferib** [comment]
@alexeyzimarev For example, the content I requested was returned as ``\"Hello\\nWorld\"``, I didn't like the fact that it decided to add multi quotes to start and end and that it added escape characters to it. All I wanted was the string.

**Comment by alexeyzimarev** [comment]
You can just unescape the string instead.

**Comment by ferib** [comment]
@alexeyzimarev that's kind of what I'm trying to achieve yes, but don't know of any other way.

**Comment by alexeyzimarev** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.unescape?view=netcore-3.1 maybe?

**Comment by softlion** [comment]
Get actual raw request is a VERY VERY important insight to debug what's wrong without needing a HTTP logging proxy.
It's inacceptable it's not in this lib.

**Comment by alexeyzimarev** [comment]
@softlion if it's "unacceptable", I would suggest opening a pull request to make it happen. Easy, right?

**Comment by softlion** [comment]
@alexeyzimarev NP, i switched to Flurl !

**Comment by alexeyzimarev** [comment]
Of course

**Comment by ChaseFlorell** [comment]
I'm curious @alexeyzimarev  (I don't use RestSharp), can this framework accept custom Delegating Handlers?
I help maintain another project that might help solve this problem.

https://www.nuget.org/packages/HttpTracer/

**Comment by alexeyzimarev** [comment]
@ChaseFlorell thanks, it looks great!

Basically, the most obvious issue was always that RestSharp used the legacy `HttpWebRequest`, which hides the `HttpClient` instance inside it. With v107 the issue is gone. People can either use `RestClient` that instantiates its own `HttpClient`, or provide either their own `HttpClient` or `HttpMessageHandler`. This means that all the `HttpClient` instrumentation and middleware will work. 

But this particular issue is weird as RestSharp was never composing raw request bytes, it was (and is) using what .NET provides for making HTTP calls. As long as you know how to observe HTTP calls, you should be good.

Your library is trivial to connect to v107 I would assume.

**Comment by alexeyzimarev** [comment]
Ok, to make things even simpler I added an option to configure the handler for the case when one is not creating the handler themselves. That's how it can be used:

```csharp
    public MultipartFormDataTests(ITestOutputHelper output) {
        _output = output;
        _server = SimpleServer.Create(RequestHandler.Handle);

        var options = new RestClientOptions(_server.Url) {
            ConfigureMessageHandler = handler => new HttpTracerHandler(handler, new OutputLogger(output), HttpMessageParts.All)
        };
        _client = new RestClient(options);
    }
```

I added to one of the tests and it works great. Thanks again @ChaseFlorell :)

**Comment by alexeyzimarev** [comment]
It's the Xunit test output. `HttpTraceHandler` has a simple logging interface that can have any implementation.
https://github.com/BSiLabs/HttpTracer/blob/master/src/HttpTracer/Logger/ILogger.cs
