### ISSUE TITLE
Bug in readme.txt that shows after installing package

### ISSUE THREAD

**Issue by Misiu** [restsharp/RestSharp#886]
Inside readme.txt that is shown when we install ReshSharp package we see how to enable Newtonsoft.JSON serializer:

``` C#
var client = new RestClient();
client.JsonSerializer = new YourCustomSerializer();
```

but `RestClient` doesn't have `JsonSerializer` property.
This should be changed to:

``` C#
var request = new RestRequest();
request.JsonSerializer =  new YourCustomSerializer();
```

Also this allows us to specify serializer for each request. Is there an option to specify default serializer for RestClient?
Ideally this should be a property of RestClient as shown in readme.txt, so instead fixing readme.txt just add that property to `RestClient`.

**Comment by behoyh** [comment]
There is a pull request for this, let me check on that.

**Comment by Misiu** [comment]
@behoyh I've checked that. Bu t what about setting default serializer for RestClient? Is it possible to add?

**Comment by behoyh** [comment]
The default is JsonDeserializer - after you call client.Execute(request); You can't change this default.

**Comment by Misiu** [comment]
@behoyh what I mean was that in readme.txt is bug (already fixed by PR You mentioned).
In my project I'm using Newtonsoft JSON serializer and right now I must set serializer each time I make request (`request.JsonSerializer =  new YourCustomSerializer();`)
Ideally I'd like to have option to set globally JsonSerializer that RestSharp will use, in my case I'd like to set Newtonsoft as default and not use build-in.
I'd like to set that in one place as default.

**Comment by Misiu** [comment]
@behoyh there is one thing missing  - deserializer in custom serialize class You guys mention in readme.txt.

Also It would be great is we can set serializer and deserializer for client, so all request would use them.

**Comment by alexeyzimarev** [comment]
The readme is fixed and we will also change how serialisers are customised, it will be in the documentation.
