### ISSUE TITLE
RestSharp UWP Does Not Build

### ISSUE THREAD

**Issue by weswitt** [restsharp/RestSharp#887]
In the master branch the UWP project does not build. Looks like the HMACSHA256 class is not available to UWP apps.

1>------ Build started: Project: RestSharp.UWP, Configuration: Debug x86 ------
1>D:\temp\wunderground\RestSharp-master\restsharp\authenticators\oauth\OAuthTools.cs(356,21,356,31): error CS0246: The type or namespace name 'HMACSHA256' could not be found (are you missing a using directive or an assembly reference?)
1>D:\temp\wunderground\RestSharp-master\restsharp\authenticators\oauth\OAuthTools.cs(356,45,356,55): error CS0246: The type or namespace name 'HMACSHA256' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by RaminMT** [comment]
Does anyone have any workaround on this issue?

**Comment by weswitt** [comment]
I just commented out the offending lines.

**Comment by mjwsteenbergen** [comment]
See #745
