### ISSUE TITLE
Possible issue with disposing of HtttpWebRequest in Http class

### ISSUE THREAD

**Issue by Spaniol** [restsharp/RestSharp#888]
In our environment we experienced some strange issue. Sometime we got our machines hang with 100 % CPU usage. After investigation we found that many of our threads get hang in WriteRequestBody of Http class.

![hang](https://cloud.githubusercontent.com/assets/4070081/19305720/f292c5a8-907a-11e6-8b26-536dd1df6fed.png)

After digging in source code, i found one place where it's possible that resources are not properly released and it may cause usage of all available sockets, after that all next requests are in queue waiting for free socket  and hanged.

After calling GetRawResponse method if some WebException exception is thrown without HttpWebResponse in Response property exception is re-thrown and in GetResponse method exception is handled but resource are not released. you must call request.Abort() when you don't disposed response object.

The above is only an assumption but I think that it's worth to check it.

RestSharp version: 105.2.3

**Comment by alexeyzimarev** [comment]
The exception is not re-thrown, in catch we call `ExtractErrorResponse` and it composes the response, it does not throw any exception. Or you mean something else?

**Comment by alexeyzimarev** [comment]
Fixed it today actually (I hope) by wrapping the call in `using` instead of `using` inside the `ExtractResponseData`, which was really ugly.
