### ISSUE TITLE
Out of Memory issue when uploading large files

### ISSUE THREAD

**Issue by instriker** [restsharp/RestSharp#889]
When we are uploading the large files with RestSharp, we randomly get some OutOfMemory issues. This happens because RestSharp is using HttpWebRequest behind the scene, and the default value for AllowWriteStreamBuffering is true. This mean that the whole file are loaded in memory when doing the query, in case there are some redirections to be able to replay it. But If we are uploading a 500 mb file, its an issue.

What we would need is to be able to set the AllowWriteStreamBuffering to false, but there is no way right now to alter the AllowWriteStreamBuffering in the ConfigureWebRequest.

Something like this would be sufficient for our need:

`var request = new RestRequest(Method.POST);
request.AllowWriteStreamBuffering = false;
request.Files.Add(new FileParameter // ...`

**Comment by Ahmed-92** [comment]
the issue is not in the HttpWebRequest it is in RestSharp it self sence they copy the file into memory befor sending it , here is the [issue](https://github.com/restsharp/RestSharp/blob/e7c65df751427298cb59f5456bbf1f59967996be/RestSharp/RestRequest.cs#L149)

**Comment by instriker** [comment]
Note : To be able to test the memory pressure of .Net vs RestSharp 105.2.3, here is how we tested it as there is an unreleased bug fix when using the .AddFile:

``
            // In the current implementation of RestSharp, there is an issue when using AddFile with a writer.
            // It doesn't set the ContentLength, which break the queries with System.Net.ProtocolViolationException as we are not uploading 
            // the expected amount of bytes. It's fixed in an yet unreleased version, so we are using the Files.Add manually for now.
            var request = new RestRequest(Method.POST);
            request.Files.Add(new FileParameter
            {
                Name = "file",
                Writer = outStream => inStream.CopyTo(outStream),
                FileName = fileName,
                ContentLength = inStream.Length,
            });
``

**Comment by MistyKuu** [comment]
Any update on this?  I'm having exactly the same issue.

**Comment by alexeyzimarev** [comment]
@AgentCoolDevil you want to help? Do a pull request.

**Comment by Psypher9** [comment]
Is anyone still getting this error on the latest version?

**Comment by alexeyzimarev** [comment]
As @yvesmh rightfully mentioned in #1213, this issue can be solved by disabling the `WebRequest` write stream buffering. You can use the web request configuration on `IRestClient` to handle such cases.

`client.ConfigureWebRequest(x => x.AllowWriteStreamBuffering = false);`
