### ISSUE TITLE
Any way to prevent query parameter encoding?

### ISSUE THREAD

**Issue by ivanovvitaly** [restsharp/RestSharp#892]
Hey Guys,

I would like my URL parameter look exactly like this with comma

`http://myaddr.com/location?point=47.64054,-122.12934`

but when request is being sent it looks like this

`http://myaddr.com/location?point=47.64054%2C-122.12934`

Are there any way to prevent parameter encoding or just comma encoding?

Thanks!

**Comment by RaminMT** [comment]
Hi,
Exact same problem here!!

**Comment by setoy** [comment]
I might wanna jump on the opportunity and push this.

**Comment by lferrao** [comment]
Same here :/(

**Comment by Exoow** [comment]
Same problem!

**Comment by sinankeskin** [comment]
Same here.

**Comment by lferrao** [comment]
Perhaps some clarification as to why this is necessary. Even though it's a fairly well established format, not URL encoding is not always implemented the same way everywhere, and the only way to work around this is to have a method that adds parameters in raw format, allowing us to encode them specifically to meet the target service's encoding spec, so they decode correctly on the other end.

**Comment by gandarez** [comment]
That bug happens to me also

**Comment by scastria** [comment]
What is the status on this?  This should be a simple enhancement and it affects lots of people

**Comment by alexeyzimarev** [comment]
@scastria so far nobody submitted a PR that would bring this simple enhancement to lots of people. sadly.

**Comment by lferrao** [comment]
I agree with Alex, if it's a _simple enhancement_ that _affects lots of people_ then why hasn't anyone created a PR yet

**Comment by sinankeskin** [comment]
My PR just merged for this issue. Thanks @alexeyzimarev
