### ISSUE TITLE
Can't see ServerCertificateValidationCallback

### ISSUE THREAD

**Issue by toadicusrex** [restsharp/RestSharp#895]
The NET45 preprocessor directive is there, but I can't see that callback anywhere; I looked at the dll in JustDecompile and it wasn't there... I'm running .net 4.5.  Any thoughts?

**Comment by cogree** [comment]
This was addressed in #811, but the code has not yet been versioned and pushed up to NuGet. I've just been rolling my own build in the meantime.

**Comment by romanrakus** [comment]
Is there any estimates when you are going to push up this update to NuGet?
