### ISSUE TITLE
RestSharp constructor executes Regex.IsMatch 8 times

### ISSUE THREAD

**Issue by ZOXEXIVO** [restsharp/RestSharp#896]
WTF ?

**Comment by ZOXEXIVO** [comment]
#897

**Comment by tbayart** [comment]
There is no RestSharp object
Could you explain which object you're instanciating and how you detect the IsMatch call ?

**Comment by ZOXEXIVO** [comment]
See this commit https://github.com/restsharp/RestSharp/pull/897/commits/2cd51e6f3d558a19f27d3d3808304eb883d61004

**Comment by tbayart** [comment]
Could you change title to specify RestClient instead of RestSharp ? Also, the performance issue don't come because regex is called 8 times, it needs the regex to be cached to be fixed. Sadly the pool request broke the build, need to figure sur out why.

**Comment by ZOXEXIVO** [comment]
Fixed. It is not my pull request. I write directly to developer and he fix it

**Comment by tbayart** [comment]
Thanks for the information.
I will check for that useful fix.

**Comment by ZOXEXIVO** [comment]
Merged

**Comment by alexeyzimarev** [comment]
@ZOXEXIVO Haven't I merge the PR yesterday?
