### ISSUE TITLE
Recommended Usage documentation is misleading

### ISSUE THREAD

**Issue by TrueWill** [restsharp/RestSharp#898]
https://github.com/restsharp/RestSharp/wiki/Recommended-Usage

The documentation implies that `response.ErrorException` is the only thing that needs to be checked before accessing `response.Data`. That's true on a transport error, but on a 4xx error you need to check `StatusCode`. Otherwise you'll get a null value back from `Data`.

This is implied in https://github.com/restsharp/RestSharp/wiki/Getting-Started#note-about-error-handling but is not obvious in most of the example code.

**Comment by Lechus** [comment]
"Otherwise you'll get a null value back from Data." ? That depends on API server.

**Comment by alexeyzimarev** [comment]
Use IsSuccessful and your problem will disappear
