### ISSUE TITLE
client.Execute<T> must strip BOM

### ISSUE THREAD

**Issue by bjartur** [restsharp/RestSharp#900]
An UTF-8 encoded HTTP body can start with a byte-order mark (BOM) to assert byte-order. Irrespective of whether RestSharp implements the byte-order check, the the HTTP body needs to be stripped of the BOM by client.Execute<T> and only the rest of the body parsed as T.

Steps to reproduce:
===
1. Call an API that returns an HTTP body prefixed with a BOM.
2. `var output = client.Execute<Dictionary<string,string>>(request).Data`

Expected value of `output`
---
A dictionary whose first key does not start with a BOM.

Actual value of `output`
---
A dictionary whose first key looks correct, but which does not compare equal to the expected key and is prefixed with several invisible bytes (the BOM). A really subtle bug, that can only be confirmed by hexdumping the first key of the dictionary.

P.S. This issue refers excusively to the return value of Execute. It is not a duplicate of #826.

**Comment by bjartur** [comment]
In which file is the url-encoding and decoding? I can write a patch if someone tells me where the relevant code is.

**Comment by alexeyzimarev** [comment]
@bjartur I would suggest starting with a unit test that demonstrates the issue so we can work forward together to make it green.

**Comment by bjartur** [comment]
On a second thought, I won't volunteer a fix for this. This is an issue that impeded previous colleagues of mine, at a previous dayjob of mine, for a couple of days but has been debugged and worked around. Feel free to close this ticket. Maybe this will, or has been, fixed without updating this ticket, and even if not developers hitting this issue might find the above description helpful in working around the issue.

**Comment by alexeyzimarev** [comment]
It is actually similar to #826 and I agree that we probably shouldn't be considering it as an issue.

The JSON RFC clearly says that BOM must not be added to JSON response:

> JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8 [RFC3629].
> Previous specifications of JSON have not required the use of UTF-8 when transmitting JSON text. However, the vast majority of JSON- based software implementations have chosen to use the UTF-8 encoding, to the extent that it is the only encoding that achieves interoperability.
> Implementations MUST NOT add a byte order mark (U+FEFF) to the beginning of a networked-transmitted JSON text. In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

**Comment by bjartur** [comment]
This issue was encountered for an XML entity. XML entities are explicitly allowed to begin with a BOM if they are encoded in UTF-8, UTF-16 or UCS-4.

https://www.w3.org/TR/REC-xml/#sec-guessing-no-ext-info
