### ISSUE TITLE
Adding plain text as a body is confusing

### ISSUE THREAD

**Issue by KutuluMike** [restsharp/RestSharp#901]
The recommended way to add a body to an HTTP POST is to call the `AddBody `method. This method only works if you have an object to serialize to XML or JSON. If you just want to add a raw string (e.g. I'm using my own serializer, or an object that doesn't serialize properly), you have to call `AddParameter `directly. 

In this case, though, the parameters are used in a confusing way. The method call looks like it should be:

`request.AddParameter("body", "<rest_access />", "application/xml;charset=UTF-8", ParameterType.RequestBody);`

but the `name` of the parameter is used as the `Content-Type` of the POST:

```
Content-Type: body
Host: thehost:8080
Content-Length: 15
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

<rest_access />
```
Note that if I added multiple parts to the body, then things work as I expect:

```
request.AddParameter("body", "<rest_access />", "application/xml;charset=UTF-8", ParameterType.RequestBody);
request.AddFiler("attachment", filename, "application/xml;charset=UTF-8");
```
produces:

```
Content-Type: multipart/form-data; boundary=-----------------------------28947758029299
Host: thehost:8080
Content-Length: 2573964
Accept-Encoding: gzip, deflate

-------------------------------28947758029299
Content-Type: application/xml;charset=UTF-8
Content-Disposition: form-data; name="body"
```

**Comment by ohaucke** [comment]
Still no progress on this topic?

**Comment by alexeyzimarev** [comment]
@ohaucke who are you asking?

**Comment by ohaucke** [comment]
I have the same problem and found this open issue.
So i thought "give it a bump" because it is still open.

The method signature is the following:
```
AddParameter(string name, object value, string contentType, RestSharp.ParameterType type)
```
but if you use it the way you thought will be right, you get a different result.
`name` value will be used as `Content-Type` Header and `contentType` value will be ignored

**Comment by alexeyzimarev** [comment]
If the parameter type is Body, we use the content type as a name. It wasn’t me who did it that way but usually there’s no problem with that since you can only have one body parameter anyway. Is you issue also with adding a custom body?

**Comment by cajuncoding** [comment]
We experienced the same issue and only figured out the behvaiour of "name" after alot of trial and error.  This is non-intuitive, and pretty annoying because I haven't been able to find any documentation (not even in the method parameter doc / intellisense) or anything to define the behavior.

I'm very surprised this was closed without even a documentation or method doc update or anything?

**Comment by alexeyzimarev** [comment]
@cajuncoding The issue was closed as stale. Apparently, even for such an easy fix (docs, triple slash) no one is willing to contribute.

**Comment by cajuncoding** [comment]
Well, in case it helps anyone else, I just added a couple extension methods to encapsulate this, and to follow the same pattern as the `AddJsonBody()` & `AddXmlBody()` methods.  This makes it alot easier for the use cases where developers need to control the raw text and content type of the payload (e.g. content from legacy code is already serialized and creating a custom serializer won't meet the existing needs without massive re-factoring). 

```
        //BBernard - Added custom extensions for REST Sharp to provide similar simlified methods for Raw & Plain Text as the out-of-the-box package provides for Json & Xml
        #region RESTSharp Extension methods to simplify using raw text & plain text; since out-of-the-box the simplified methods only provide for Json & Xml.

        public static IRestRequest AddPlainTextBody(this IRestRequest request, string body)
        {
            request.AddRawTextBody(body, "text/plain");
            return request;
        }

        public static IRestRequest AddRawTextBody(this IRestRequest request, string body, string contentType)
        {
            request.RequestFormat = DataFormat.None;
            request.AddParameter(contentType, body, ParameterType.RequestBody);
            return request;
        }
        #endregion
```
