### ISSUE TITLE
HttpUtility.UrlEncode in restsharp vs HttpUtility.UrlEncode System.Web

### ISSUE THREAD

**Issue by paritoshmmmec** [restsharp/RestSharp#902]
Is there any difference in  HttpUtility.UrlEncode in restsharp vs HttpUtility.UrlEncode System.Web?

I am using RestSharp in my console application already. so I would prefer HttpUtility.UrlEncode  using restsharp rather than   System.Web one.

I hope if I have to decode in some web application, decoding will work using system.web if I have encoded using restsharp.

**Comment by alexeyzimarev** [comment]
The `HttpUtility` was added due to lack of this code in some platforms. It has been removed now.
