### ISSUE TITLE
Response.Content is empty for a BadRequest even though ContentLength > 0

### ISSUE THREAD

**Issue by adamelliottsweeting** [restsharp/RestSharp#910]
I'm integrating an API which returns content for responses that are not successful.
E.g. Provides validation results for fields with an incorrect data type in the request.

However, I cannot retrieve the content for a response which is not considered successful.
E.g. The response I have received is a `400 Bad Request` and I know there is content as I submitted the request manually via Postman. The `RestResponse.ContentLength` property has a value so I know that the response was provided, but the `RestResponse.Content` property is empty.

I cut out some irrelevant functions but the basics is below (VB):
```
Dim request As New RestRequest("resource", Method.POST)

' Add request headers.
request.AddHeader("Accept", "application/json")
request.AddHeader("Content-Type", "application/json")

' Add the model to the body.
request.AddJsonBody(model)

' Get the response.
Dim response As IRestResponse = RestClient.Execute(request)

' Results in Completed
Dim responseStatus = response.ResponseStatus

' Results in 400 Bad Request
Dim statusCode = response.StatusCode

' Results in integer > 0
Dim contentLength = response.ContentLength

' Results in an empty string
Dim content = response.ContentLength
```

Is there any way to get the raw `HttpResponse` object?
I can see that the response is converted to a `RestResponse` object here:
https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestClient.cs#L577
However, the `HttpResponse` is not added to this object so I have been unable to investigate any further.

Note that both `RestResponse.ErrorException` and `RestResponse.ErrorMessage` is empty as well.

**Comment by alexeyzimarev** [comment]
`response.RawBytes` always contains what we got from the server.
