### ISSUE TITLE
.Net Standard Compatibility

### ISSUE THREAD

**Issue by GrahamWilkinson** [restsharp/RestSharp#912]
Hi.

Can you tell me, are there any plans to release a .Net Standard compatible version of rest sharp?

Thanks

**Comment by totht91** [comment]
Dear @hallem I think I can help you to port this library to .NET Standard PCL.

**Comment by dsoronda** [comment]
This is already discussed [here](https://github.com/restsharp/RestSharp/issues/664)

**Comment by alexeyzimarev** [comment]
#992
