### ISSUE TITLE
async await

### ISSUE THREAD

**Issue by Messilimeng** [restsharp/RestSharp#913]
![image](https://cloud.githubusercontent.com/assets/12272166/21418774/7a6cb93c-c85e-11e6-8e1e-d81e7995656f.png)

**Comment by dgreene1** [comment]
The documentation appears to be lack in this area, but there is a method that allows for this. For reference to general async await stuff:

https://github.com/restsharp/RestSharp/issues/626#issuecomment-269385008

And then specifically what you would probably need is:
https://github.com/restsharp/RestSharp/blob/e7c65df751427298cb59f5456bbf1f59967996be/RestSharp/RestClient.Async.cs#L219

But who knows, I'm a nodeJS developer who is just checking this side of the world out. Good luck! :)
