### ISSUE TITLE
Reporting progress while receiving "application/octect-stream"

### ISSUE THREAD

**Issue by corentinaltepe** [restsharp/RestSharp#917]
Hello! Thank you for this awesome library!
I tried submitting to the Google Group but fell out of luck there.

I am aware that this question has been submitted multiple times, but the last answers are dated and I wonder whether there would be a solution available today? This is not a feature request. I'm rather looking for any workaround that would work.

Basically, I send a POST to my API and it replies with a "application/octect-stream" which can take up to several minutes to download. Link to the GitHub code [here](https://github.com/corentinaltepe/AppUpdater/blob/master/AppUpdaterClient/AppUpdater.cs#L131-L146).

```c#
public void Download()
{
     if (NewerApp == null) return;
            
      var client = new RestClient(ServerAddress);
      var request = new RestRequest("/Apps/", Method.POST);
      request.AddParameter("id", CurrentApp.EncryptedId());
      request.AddParameter("action", "download");
            
      var asyncHandle = client.ExecuteAsync<App>(request, response => {
          HandleResponseToDownloadRequest(response);
      });
}

```
I would need to report the progress of the reception of "response" to my UI to build a progress bar or something like that. I already know the expected amount of data to be received (through a previous API response), I would just need to know how many bytes were received before the full response is received and parsed.

Is there any feature like this currently? Can I access the RawBytes of 'response' while ExecuteAsync is still executing? Should I use Execute (without Asyn) instead? Should I use stream and update watch the size of the stream at regular updates?

Thank you

**Comment by Laptop765** [comment]
Here's a rough workaround that seems to work with some quick testing:

```csharp
RestRequest request = new(resource)
{
    // This will only request the headers, not the full contents
    Method = Method.Head,
};
var headResponse = await client.ExecuteAsync(request);
// This should be the total number of bytes to be downloaded
long totalBytes = headResponse.ContentLength;

// Change back to a regular GET request
request.Method = Method.Get;
var stream = await client.DownloadStreamAsync(request);

long downloadedBytes = 0;
var buffer = new byte[1024];
while ((bytesRead = await stream.ReadAsync(buffer)) > 0)
{
    // Do whatever you need to with the bytes

    // Here we keep a running total of how much we've downloaded so far
    // Percentage would be calculated as downloadedBytes / totalBytes
    downloadedBytes += bytesRead;
}
```

References:
* #1794 
* https://stackoverflow.com/questions/39742515/stream-copytoasync-with-progress-reporting-progress-is-reported-even-after-cop

**Comment by alexeyzimarev** [comment]
I think you don't need to use the `HEAD` request to get it going but instead set the request option:

```csharp
request.CompletionOption = HttpCompletionOption.ResponseHeadersRead;
```

As `DownloadStreamAsync` does set it, it should theoretically be possible to do the same there. Would be nice if someone could try to play with that function and see if it can report progress too.

**Comment by Laptop765** [comment]
I hadn't considered using `HttpCompletionOption.ResponseHeadersRead` after reading #1871 but grabbing it from `ContentLength` instead of the `Stream` makes sense. Is changing the `DownloadStreamAsync` signature a PR that you're open to accepting if I give it a shot and is there a preference between either of these signatures?

```csharp
public async Task<(Stream?, long?)> DownloadStreamAsync(...);

// VS.

public async Task<DownloadStream> DownloadStreamAsync(...);
public record DownloadStream(Stream? Stream, long? ContentLength);
```

**Comment by Laptop765** [comment]
Oh and I guess there's the question of backwards-compatibility of changing the signature - is there a preferred way to do that?

**Comment by alexeyzimarev** [comment]
The `DownloadStreamAsync` function is part of the interface, so it will be breaking. But it will be possible to create an extension that will implement the same signature. So, it won't be binary compatible, but the code won't break unless people implement the interface for whatever reason. In that case they'd need to change their implementation. It's still not the mainstream case, I hope.

**Comment by Laptop765** [comment]
That makes sense. I think I'll just stick to my workaround above and hope that this thread is helpful for anyone else who needs it 😀
