### ISSUE TITLE
T4Helper.tt -> The C# 2.0 and C# 3.5 compilers are no longer supported

### ISSUE THREAD

**Issue by MFisherIT** [restsharp/RestSharp#920]
Working with the T4Helper I got the following Warning:
`The C# 2.0 and C# 3.5 compilers are no longer supported. Templates will always be compiled with the version 4 compiler instead of 'v3.5' as specified.`

https://github.com/restsharp/RestSharp/blob/master/RestSharp/T4Helper/T4Helper.tt
Line 1

Suggestion: Remove the 'v3.5'

**Comment by alexeyzimarev** [comment]
I actually removed T4 helpers since you can just use XML schema tool (xsd.exe) go generate classes from XML and XSD files. And this is the most correct way of doing this considering you will be using .NET XML serialiser.
