### ISSUE TITLE
Serializer woes

### ISSUE THREAD

**Issue by FrankyBoy** [restsharp/RestSharp#922]
These are the two big issues which currently make it hard for me to like this library.

* The default serializer does not support any sort of property transformation. This could for instance be fixed by [uncommenting this line of code](https://github.com/restsharp/RestSharp/blob/master/RestSharp/SimpleJson.cs#L31)
* Setting a custom serializer for a client is not possible so you'd have to do it for each request, which is a pain in the butt for obvious reasons.

**Comment by alexeyzimarev** [comment]
This is planned for change to enable custom serialiser to be used on the client level. I will close this one. Follow up in #1018.
