### ISSUE TITLE
Cannot deserialize xml collections

### ISSUE THREAD

**Issue by ChangePlaces** [restsharp/RestSharp#926]
It seems that if there's a collection of nodes `<root><foo></foo><foo></foo></root>`, it's impossible to deserialize them into a list<Foo>. Instead the list is populated with one element, with all properties set to null. Has this been broken?

Has RestSharp been abandoned?

**Comment by ChangePlaces** [comment]
I've had a play, and had to make some modifications to the xml deserializer.

    protected virtual object Map(object x, XElement root)
    {
        ....
        ....
        else if (type.IsGenericType)
    #else
                else if (type.GetTypeInfo(). IsGenericType)
    #endif
                {
                    Type t = type.GetGenericArguments()[0];
                    IList list = (IList) Activator.CreateInstance(type);
                    XElement container = this.GetElementByName(root, prop.Name.AsNamespaced(this.Namespace));

                    if (container.HasElements)
                    {
                        XElement first = container.Elements().FirstOrDefault();

                        if (first != null)
                        {
                            IEnumerable<XElement> elements = container.Parent.Elements(container.Name);

                            this.PopulateListFromElements(t, elements, list);
                        }
                    }

                    prop.SetValue(x, list, null);
                }

**Comment by alexeyzimarev** [comment]
So why didn't you submit a PR to fix this?

**Comment by Zek99** [comment]
I have encountered this issue using the following XML

```
<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Root>
  <Log>
    <Messages>2</Messages>
    <Message>
      <Text>abc</Text>
    </Message>
    <Message>
      <Text>xyz</Text>
    </Message>
  </Log>
</Root>
```

Using the following classes

```
public class Root
{
    public Log Log { get; set; }
}

public class Log
{
    public int Messages { get; set; }
    public List<Message> Message { get; set; }
}

public class Message
{
    public string Text { get; set; }
}
```

**Comment by Zek99** [comment]
I had a look at the source code and figured out that the code 'expects' (for lack of a better word) that you declare a List property instead of a class containing a list. If you use `[DeserializeAs]` on the list property and specify the parent element of the list elements it will work.

For my example all I had to do was:

```
public class Log
{
    public int Messages { get; set; }
    [DeserializeAs(Name = "log")]
    public List<Message> Message { get; set; }
}
```
