### ISSUE TITLE
Posting data to URL wont work?

### ISSUE THREAD

**Issue by navid-dada** [restsharp/RestSharp#929]
I use this code to send a post request to a server but in fiddler i get different result:

```csharp
     public string ResolveUrl(int par0, string par1, int par3) {
            RestSharp.RestClient client = new RestSharp.RestClient("http://someurl.com");
            RestSharp.RestRequest request = new RestSharp.RestRequest();
            request.Resource = "/resource/" + par1+ "/blah";
            request.AddParameter("param1", par1);
            request.AddParameter("param2", par2);
            request.Method = RestSharp.Method.POST;
            //request.AddHeader("Content-Type", "application/x-www-form-urlencoded");

            var response = client.Execute(request);
            return response.Content;
        }
```
and fiddler get show this to me: 

> GET /hotel/1221/blahblah HTTP/1.1

**Comment by ericmaro** [comment]
Try using rest api, set content type to application/json. here is my code
`
            var client = new RestClient("http://someurl.com");
            var request = new RestRequest("/user/signin", Method.POST);
            request.RequestFormat = DataFormat.Json;

            request.AddHeader("X-Requested-With", "XMLHttpRequest");
            request.AddObject(
               new User
               {
                   email = email,
                   password = password,

               });
            client.ExecuteAsync(request, response =>
            {
                RunOnUiThread(delegate
                {
                    var resp = response.Content;
                    Toast.MakeText(this, resp, ToastLength.Long).Show();
                });
            });`

**Comment by alexeyzimarev** [comment]
@navid-dada I don't understand your question.

If you need to use a URL segment parameter, you should do it like this:

```csharp
request.Resource = "/resource/{parameter}/blah";
request.AddUrlSegment("parameter", par1);
```
