### ISSUE TITLE
Support for HttpMessageHandler to allow in-memory web api

### ISSUE THREAD

**Issue by juliencousineau** [restsharp/RestSharp#932]
Like HttpClient does with 

```
HttpConfiguration config = new HttpConfiguration();

WebApiConfig.Register(config);

_server = new HttpServer(config);

_client = new HttpClient(_server);
```

It can be really helpful if RestSharp can support like HttpClient!

**Comment by shyamgudi** [comment]
Any update on this? This would be helpful to have something like this in RestSharp

**Comment by alexeyzimarev** [comment]
Of course. If you need it - please do it.

**Comment by alexeyzimarev** [comment]
Duplicate of #747
