### ISSUE TITLE
Withings Returning 503 : Invalid Params

### ISSUE THREAD

**Issue by atbyrd** [restsharp/RestSharp#934]
I'm trying to connect to the withings API using RestSharp. But it is return an error to me, 503 : Invalid Params.

Client

        try
        {
            var client = new RestClient(ResourceUrl)
            {
                Authenticator = OAuth1Authenticator.ForProtectedResource(Credentials.ConsumerKey, Credentials.ConsumerSecret, Credentials.OAuthToken, Credentials.OAuthSecret)
            };
            ((OAuth1Authenticator) client.Authenticator).ParameterHandling = OAuthParameterHandling.UrlOrPostParameters;
            var request = new RestRequest("measure",Method.GET);
            request
                .AddQueryParameter("action", "getmeas")
                .AddQueryParameter("userid", Credentials.ExternalUserId)
                .AddQueryParameter("startDate", startDate.ToUnixTime().ToString())
                .AddQueryParameter("enddate", endDate.ToUnixTime().ToString());
            var response = client.Execute(request);
            wmBPList = GetWM_BloodPressure(response.Content);
        }
Generated Url

`"https://wbsapi.withings.net/v2/measure?action=getmeas&userid=12829536&startDate=14`

**Comment by adonayz** [comment]
Did you manage to get an answer for this problem?

**Comment by alexeyzimarev** [comment]
I am not sure what this is to do with RestSharp. Test the URL against the API in the browser or Postman.

**Comment by adonayz** [comment]
If anyone's looking to connect to the withings API, the following code might help. (The extended class and overridden methods are parts of my personally code)

public class WithingsConnector extends Connector {

    private WebView loginWebView = null;
    public static OAuthService service;
    public static Token requestToken;
    String secret, token;
    Token accessToken;
    String userid = "";

    /**
     *
     * @param activity
     * @param progressBarLayout
     */
    public WithingsConnector(AppCompatActivity activity, RelativeLayout progressBarLayout){
        super(SourceType.WITHINGS, activity, progressBarLayout);
    }


    @Override
    public void connect() {
        setConnected(true);
        getProgressBarLayout().setVisibility(View.GONE);
        getCredentials();
    }

    @Override
    public void disconnect() {
        setConnected(false);
        getProgressBarLayout().setVisibility(View.GONE);
    }

    @Override
    public void loadHealthData(final TextView textView) {
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        final String url = "https://api.health.nokia.com/v2/measure?action=getactivity" + "&userid=" + userid + "&date=" + dateFormat.format(currentDate) + "&oauth_token=" + token + "&oauth_token_secret=" + secret;

        WithingsAsyncTask withingsAsyncTask = new WithingsAsyncTask();

        withingsAsyncTask.setAsyncResponse(new WithingsAsyncResponse() {
            @Override
            public void onJsonRequestFinished(JSONObject result) {
                textView.setText(result.toString());
            }
        });

        withingsAsyncTask.execute(url);

    }

    public void withingsLogin(){

        if(getActivity() instanceof MainActivity){
            loginWebView = ((MainActivity) getActivity()).getLoginWebview();
            Log.i(getTAG(), "FROM MAIN");
        }else if(getActivity() instanceof AddSourcesActivity){
            loginWebView = ((AddSourcesActivity) getActivity()).getLoginWebview();
            Log.i(getTAG(), "FROM AddSources");
        }

        loginWebView.setVisibility(View.VISIBLE);

        loginWebView.getSettings().setJavaScriptEnabled(true);
        loginWebView.setWebViewClient(new MyWebViewClient(loginWebView));

        service = new ServiceBuilder().provider(WithingsApi.class)
                .apiKey(WithingsApi.getKey())
                .apiSecret(WithingsApi.getSecret())
                .build();

        new Thread(new Runnable() {
            public void run() {
                requestToken = service.getRequestToken();
                final String authURL = service.getAuthorizationUrl(requestToken);
                loginWebView.post(new Runnable() {
                    @Override
                    public void run() {
                        loginWebView.loadUrl(authURL);
                    }
                });

            }
        }).start();
    }


    class MyWebViewClient extends WebViewClient {
        WebView wvAuthorise;
        MyWebViewClient(WebView wv){
            wvAuthorise = wv;
        }
        @Override
        public void onPageFinished(WebView view, String url) {
            getUSERID(url);
        }
    }

    private void getUSERID(final String url) {

        try {
            String divStr = "userid=";
            int first = url.indexOf(divStr);

            if(first!=-1){
                userid = url.substring(first+divStr.length());

                getAccessTokenThread.execute((Object) null);
                loginWebView.setVisibility(View.GONE);
            } else {
                //...
            }

        } catch (Exception e) {
            Log.e(getTAG(),e.getMessage());
            //...
        }
    }

    private void getCredentials() {
        try {
            if (!PreferencesManager.isSourceConnected(getActivity(), SourceType.WITHINGS)) {
                withingsLogin();
            } else {
                // TODO load all users and if isn't anyone correct
                // startAuthenticationActivity
                secret = PreferencesManager.getWithingsLoginInfo(getActivity(), "secret");
                token = PreferencesManager.getWithingsLoginInfo(getActivity(), "token");
                userid = PreferencesManager.getWithingsLoginInfo(getActivity(), "userid");
                Log.i(TAG, "secret  : " + secret);
                Log.i(TAG, "token  : " + token);
                Log.i(TAG, "userid  : " + userid);
                try {
                    service = new ServiceBuilder().provider(WithingsApi.class)
                            .apiKey(WithingsApi.getKey())
                            .apiSecret(WithingsApi.getSecret()).build();
                    accessToken = new Token(token, secret);

                    //loadData();
                } catch (Exception ex) {
                    withingsLogin();
                }

            }
        } catch (Exception ex) {
            Log.e(TAG, "try on create" + ex.getLocalizedMessage());
        }
    }

    AsyncTask<Object, Object, Object> getAccessTokenThread = new AsyncTask<Object, Object, Object>() {
        @Override
        protected Object doInBackground(Object... params) {
            accessToken = service
                    .getAccessToken(requestToken, new Verifier(""));

            secret = accessToken.getSecret();
            token = accessToken.getToken();
            return null;
        }

        @Override
        protected void onPostExecute(Object result) {
            // authentication complete save the token,secret,userid
            saveUserDatatoSharedPreferences(token, secret, userid);
            //loadData();
        }

    };

    private void saveUserDatatoSharedPreferences(String token, String secret, String userid){
        PreferencesManager.setWithingsLoginInfo(getActivity(), "token", token);
        PreferencesManager.setWithingsLoginInfo(getActivity(), "secret", secret);
        PreferencesManager.setWithingsLoginInfo(getActivity(), "userid", userid);
    }


}

class WithingsApi extends DefaultApi10a {

    private static final String AUTHORIZATION_URL ="https://oauth.withings.com/account/authorize?oauth_token=%s";
    private static final String apiKey = YOUR KEY HERE;
    private static final String apiSecret = YOUR SECRET HERE;

    @Override
    public String getRequestTokenEndpoint() {
        return "https://oauth.withings.com/account/request_token";
    }

    @Override
    public String getAccessTokenEndpoint() {
        return "https://oauth.withings.com/account/access_token";
    }

    @Override
    public String getAuthorizationUrl(Token requestToken) {
        return String.format(getAUTHORIZATION_URL(), requestToken.getToken());
    }

    public static String getKey(){
        return apiKey;
    }

    public static String getSecret(){
        return apiSecret;
    }

    public static String getAUTHORIZATION_URL() {
        return AUTHORIZATION_URL;
    }
}

class WithingsAsyncTask extends AsyncTask<String, Void, JSONObject>{
    private WithingsAsyncResponse withingsAsyncResponse;

    @Override
    protected JSONObject doInBackground(String... strings) {
        JSONObject result = null;
        try {
            result = getJSONObjectFromURL(strings[0]);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (JSONException e) {
            e.printStackTrace();
        }

        return result;
    }

    @Override
    protected void onPostExecute(JSONObject result){
        withingsAsyncResponse.onJsonRequestFinished(result);
    }

    public static JSONObject getJSONObjectFromURL(String urlString) throws IOException, JSONException {
        HttpURLConnection urlConnection = null;
        URL url = new URL(urlString);
        urlConnection = (HttpURLConnection) url.openConnection();
        urlConnection.setRequestMethod("GET");
        urlConnection.setReadTimeout(10000 /* milliseconds */ );
        urlConnection.setConnectTimeout(15000 /* milliseconds */ );
        urlConnection.setDoOutput(true);
        urlConnection.connect();

        BufferedReader br = new BufferedReader(new InputStreamReader(url.openStream()));
        StringBuilder sb = new StringBuilder();

        String line;
        while ((line = br.readLine()) != null) {
            sb.append(line + "\n");
        }
        br.close();

        String jsonString = sb.toString();
        System.out.println("JSON: " + jsonString);

        return new JSONObject(jsonString);
    }

    public void setAsyncResponse(WithingsAsyncResponse withingsAsyncResponse){
        this.withingsAsyncResponse = withingsAsyncResponse;
    }
}

interface WithingsAsyncResponse{
    void onJsonRequestFinished (JSONObject result);
}
