### ISSUE TITLE
Sign Assembly

### ISSUE THREAD

**Issue by mahdiit** [restsharp/RestSharp#937]
Please sign restsharp assembly 
in signed project i got error: 
Referenced assembly does not have a strong name

i fix my issue using guide line in 
https://www.codeproject.com/tips/341645/referenced-assembly-does-not-have-a-strong-name

but if nuget package dlls signed, i think it is better
another way is download source and sign with my own key

**Comment by alexeyzimarev** [comment]
Just install it from the signed assembly package
https://www.nuget.org/packages/RestSharpSigned/
