### ISSUE TITLE
Dropping support for old flavours of .NET like Silverlight and net35 in favor of netstandard migration

### ISSUE THREAD

**Issue by ViktorHofer** [restsharp/RestSharp#938]
Hey there,

as this is one of the most downloaded projects on nuget I hope my feeling that the project is dead isn't true. Part of the .NET Core Team I'm currently evaluating the effort to migrate this library to netstandard and netcore (tests).

As netstandard does not support Silverlight or net35 and they are pretty outdated I would drop support for those. Migration to netstandard brings a lot of advantages like cross-platform support with netcore.

If the project is still maintained and if the owners are willing to get rid of some outdated flavors of .NET then I would **drive the migration**.

**Comment by ViktorHofer** [comment]
@johnsheehan

**Comment by ormico** [comment]
Did you ever get a response? @Haacked was helping out at one point. I don't know if he still is.

**Comment by ViktorHofer** [comment]
No response yet

**Comment by leftler** [comment]
Issue #664 may be relevant to this post.

**Comment by alexeyzimarev** [comment]
I am adding this as a priority

**Comment by alexeyzimarev** [comment]
In order to build the solution now, I migrated it to VS2017 and it seems to be building after fixing the UWP issue with HMACSHA256.

However, Silverlight, Monotouch and WP8/8.1 are not supported there. I would like to drop these projects from the solution and move on.

I'd like to hear if there are any objections.

**Comment by ViktorHofer** [comment]
I think you are doing the right thing. I don't have concrete usage numbers but I don't think that a lot of people are still developing for WP8/W8.1.

**Comment by alexeyzimarev** [comment]
I removed SL, WP8, WP8.1 and MonoTouch. .NET 3.5 is a bigger deal since this project actually holds all the code. The code needs to be moved to a new core project, which will target multiple frameworks and will be using the new project format. I will continue working on it as part of #991.

**Comment by TrexinanF14** [comment]
I'd like to add one vote to maintaining compatibility with .net 3.5. I think you can still use the new project format, but you'd need to multi-target. .net 3.5 is still popular as a target because of it's extremely wide compatibility.

http://markheath.net/post/supporting-net-standard-and-net-35

**Comment by alexeyzimarev** [comment]
Is it not a targeting issue, it is the code issue (ifdefs), 64 bit and async support issue and also Microsoft support for aforementioned frameworks issue. 

According to this https://github.com/Microsoft/dotnet/blob/master/releases/README.md, .NET Framework 4.5.2 is the *lowest* supported version of the .NET Framework.

**Comment by ViktorHofer** [comment]
> 3.5 is still popular as a target because of it's extremely wide compatibility.

Please explain what you mean with wide compatibility.

**Comment by HakanL** [comment]
It's quite common that users of old frameworks (3.5) has to stick with older versions of a library when the library moves on. I think it's appropriate to drop support.

**Comment by TrexinanF14** [comment]
When I say broad compatibility, my experience is with commercial users who are either stuck on older versions of .net or are on windows xp and will not be moving on due to either regulatory or compatibility reasons. Both of these groups are shrinking, but aren't negligible yet.

I'll use json.net as an example of a library that maintains back compat to .net 2.0, but also supports newer frameworks and features like async. I believe in that library's case, the async side is entirely bisected from the non-async:
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonReader.Async.cs
I'm not sure what you mean about 64 bit. Does restsharp specifically target x86/x64 rather than AnyCPU?

If the maintenance burden of net35 is too large, then yes, using an old version is a possibility.

**Comment by ViktorHofer** [comment]
> commercial users who are either stuck on older versions of .net or are on windows xp and will not be moving on due to either regulatory or compatibility reasons. Both of these groups are shrinking, but aren't negligible yet.

I disagree. Microsoft does not support Windows XP, neither does .NET Core (min. Win 7 SP1). Why should an non-funded open source library have a broader support matrix than a multi billion dollar company?

.NET Framework 4.5/4.6 even 4.7 is available on Windows 7 which should be the entry bar for Windows users. And by targeting a certain .NET Standard version even OSX and Linux users can benefit (based on the support matrix of .NET Core and Mono).

**Comment by ormico** [comment]
just throwing my $0.02 in. JSON.NET has a much larger budget/manpower pool than RestSharp I believe.

the current version supports .net 3.5 and a bunch of other stuff. why not branch or fork that version and if there are any critical bugs or security items that need fixing then they can be done there and that version can remain for anyone who can't upgrade. After all people have been using the current version for quite a while with few updates.


support for .net 3.5 could be removed from the main branch where main work can be done going forward with new features.

**Comment by devinrader** [comment]
Just a suggestion but maybe asking @JamesNK how JSON.NET manages this problem would be helpful.

**Comment by TrexinanF14** [comment]
@devinrader I'd be curious to hear from @JamesNK as well, although I don't know how busy he is. 

@ormico Yes, forking would also be an option, but it might be a relatively minor commitment to maintain net35 in the mainline. I'm asking that we investigate more before dropping support. I'm not a maintainer, so I'll leave it up to them to decide if it's too big of an ask.

**Comment by ViktorHofer** [comment]
Keeping net35 in the master branch because dropping support sounds so harsh doesn't make much sense. Data of how many are using this library on net35 would definitely help here.

**Comment by TrexinanF14** [comment]
@ViktorHofer Unfortunately, I don't think nuget distinguishes that in their package statistics. A portion of my company's product still targets net35, so at least 1? 😄

**Comment by ViktorHofer** [comment]
What's the reason that you are still targeting net35? I'm curious

**Comment by alexeyzimarev** [comment]
I also want to point out that you cannot compare a so sponsored library as Json.Net with us. It is all done in free time, all based on enthusiasm. If someone is ready to pick up support for .Net 3.5 and keep the builds working, tests working by and so on - welcome. I am not ready to put any effort on this. I can, however, put effort to netstandard support.

**Comment by JamesNK** [comment]
Supporting multiple targets is easy now with the new project system. But if you want to drop sync and only have async then that would be a legit reason to drop 3.5

If you go down that route then you can always reference 3.5 users to an older version of RestSharp. And if a group want to modify it then they can create a fork at a point where 3.5 was still supported and do whatever they like.

**Comment by alexeyzimarev** [comment]
@JamesNK it is not only about multi-targeting, but also (mainly) about ifdefs

**Comment by alexeyzimarev** [comment]
#1006

**Comment by alexeyzimarev** [comment]
> any critical bugs or security items

I would say that I have looked through all PRs and issues and none of them, for the last two years where no active work has been done on the library, can be classified like this. It is a very low chance that with so many downloads and so long time of the current version being in use, that we discover anything like this.

**Comment by ViktorHofer** [comment]
Done by #1006.
