### ISSUE TITLE
Choose not to deserialize if it is not specified to do so

### ISSUE THREAD

**Issue by skltfz** [restsharp/RestSharp#941]
i have below code

```csharp
var client = new RestClient($"{apiURL}?q={q}&s={s}");
var request = new RestRequest(Method.POST);
request.AddHeader("cache-control", "no-cache");

var response = client.Execute<CustomClass>(request);
```

and this is the custom class and this is the CustomClass

```csharp
public class CustomClass
{
            public string State { get; set; }
            public string Balance { get; set; }
            public string Detail { get; set; }
            public string GameResult{ get; set; }
}
```
everything is fine, except there is a issue, the output is something like this,

```xml
<UserBetItem>       
        <Detail>123</Detail>
        <GameResult>
            <BaccaratResult>
                <PlayerCard1>
                     <Suit>3</Suit>
                     <Rank>8</Rank>
                </PlayerCard1>          
                <ResultDetail>
                     <BRTie>false</BRTie>            
                </ResultDetail>
            </BaccaratResult>
        </GameResult>
        <Balance>104.25</Balance>
        <State>true</State>
</UserBetItem>
```
CustomClass has the properies correctly thus Detail, Balance and State can be plugged in correctly.

however, GameResult is dynamic for different game, thus the XML of this tag is always changing, I decided to store just the XML string instead of deserializing it.

but the result of GameResult became something like
`"38false"`
, which is the value string of the tags of the XML.

but I want to retrieve the entire xml string, i want the GameResult

```xml
<BaccaratResult>
    <PlayerCard1>
        <Suit>3</Suit>
        <Rank>8</Rank>
    </PlayerCard1>          
    <ResultDetail>
        <BRTie>false</BRTie>            
    </ResultDetail>
</BaccaratResult>
```
Is it possible to do so?

I am wondering why would the design try to deserialize the xml tag blindly why there is no actual class constructed. it has no meaning for any circumstances that output something like "38false" just to extract the value of the xml.

**Comment by alexeyzimarev** [comment]
Tbh I have very little idea of what you are saying without being in the context. Take a look at XML serialiser. Is is actually the one of `System.Xml`, nothing special. If you can make that default stuff work for you - RestSharp will most probably work as you want. But you might need to change your class accordingly.

**Comment by hallem** [comment]
I think @skltfz is asking if it's possible to do partial deserialization on a response. But no, that wouldn't be supported. You'd have to manually deserialize the response yourself to get this behavior.

**Comment by alexeyzimarev** [comment]
I hope that with #1018 it would be easier to add custom serialisers and do whatever you want. But I agree that we don't want to make this a feature.
