### ISSUE TITLE
“The underlying connection was closed: An unexpected error occurred on a send.” With SSL Certificate

### ISSUE THREAD

**Issue by darul75** [restsharp/RestSharp#942]
Based on this thread that solve problem I encountered with https, it would be nice to add a section in documentation about it.

Solution is to prepend rest calls with this configuration:

```c#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

new RestClient(....
```

**Comment by alexeyzimarev** [comment]
Adding to the docs now.
