### ISSUE TITLE
BuildUri(IRestRequest request) does not add default parameters

### ISSUE THREAD

**Issue by masoapps** [restsharp/RestSharp#944]
If you construct a RestClient, add a default parameter e.g. a query string ```Client.AddDefaultParameter("api_key", "EXAMPLE_API_KEY", ParameterType.QueryString);``` 

, then call BuildUri against an example request: 
```var request = new RestRequest("test", Method.GET);``` 

, then BuildUri does not build the default parameter into the output.  I noticed this while wrapping tests around a provider class  that wraps the RestClient.  Was this as designed?  If not I'm happy to submit a PR to fix.

Kind regards,
Mason

**Comment by alexeyzimarev** [comment]
Can you make a test that shows the issue? I understand the gist of it but need to look at the code.

**Comment by alexeyzimarev** [comment]
I am sure we properly add default parameters.
