### ISSUE TITLE
Contradiction of AddParameter and AddFile

### ISSUE THREAD

**Issue by kampok** [restsharp/RestSharp#945]
request.AddHeader("accept", "application/json");
            request.AddHeader("content-type", "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW");

            String text;
            String file;

            String paramStr = String.Format("------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"blocks\"\r\n\r\n{0}\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"file\"; filename=\"{1}\"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--",text, file);
            
            // --- LINE 1---
            request.AddParameter("multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW", paramStr, ParameterType.RequestBody); 

            // --- LINE 2---
            request.AddFile("file", file); 

            IRestResponse response = client.Execute(request);
The situation is that I need to send a text and a file in multipart/form-data. When I only use LINE1, the text can be sent. When I only use LINE2, the file can be sent. 
BUT, when add LINE1 and LINE2, only the file can be sent!!!

Does anybody know why?

**Comment by FelipeJz** [comment]
I would like to know too! 
There's this: https://github.com/restsharp/RestSharp/issues/524 But any of the answers worked for me. Then there's this guy that says that he figured it out: https://blog.tyrsius.com/restsharp-file-upload/ But his answer is unclear for me. Did you found the way to do it?

**Comment by alexeyzimarev** [comment]
@FelipeJz the blog posts basically says you have to set this:

```
request.AlwaysMultipartFormData = true;
```

Have you tried this?

**Comment by alexeyzimarev** [comment]
Since there is no response, I am closing this.

**Comment by namilkimfree** [comment]
Hi @alexeyzimarev .
I did set request.AlwaysMultipartFormData = true;

req.AlwaysMultipartFormData = true;
req.AddHeader("content-Type", "multipart/form-data");
req.RequestFormat = DataFormat.Json;

req.AddParameter("member", JsonConvert.SerializeObject(signup), "application/json", ParameterType.RequestBody);   ->   **it's sucess  **  but  Commenting out below fails.
//req.AddParameter(new JsonParameter("member", signup)); -> **it's fail and server message is didn't have member present**  

req.AddFileBytes("profile", memory.ToArray(), "Test.jpg");  
IRestResponse rs = client.Execute(req);



req.AddParameter("member", JsonConvert.SerializeObject(signup), "application/json", ParameterType.RequestBody);   ->   **it's sucess  **  but  Commenting out below fails.
//req.AddParameter(new JsonParameter("member", signup)); -> **it's fail and server message is didn't have member present**
