### ISSUE TITLE
client.execute(request) wont trigger ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;

### ISSUE THREAD

**Issue by garciaraul85** [restsharp/RestSharp#946]
Hi!
So I´ve a restservice over https, so currently I´m getting "Error getting response stream (Write: The authentication or decryption has failed.): SendFailure". I read that before the request I needed to do ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true; in order to bypass the certificate, but it never gets triggered.
Does anyone knows why ServerCertificateValidationCallback never gets triggered.
I even used the moztools to download all the certificates from my browswer and even install the certificate using certmgr.exe but it doesnt work

This is the entire error:
System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): 
SendFailure ---> System.IO.IOException: 
The authentication or decryption has failed. ---> 
Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.\r\n  at Mono.Security.Protocol.Tls.RecordProtocol.ProcessAlert 
(AlertLevel alertLevel, AlertDescription alertDesc) [0x00000] in <filename unknown>:0 \r\n  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) 
[0x00000] in <filename unknown>:0 \r\n  --- End of inner exception stack trace ---\r\n  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in 
<filename unknown>:0 \r\n  --- End of inner exception stack trace ---\r\n  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 \r\n  
at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 \r\n  at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) [0x00000] in <filename unknown>:0

Thanks in advance.

**Comment by pkmuru** [comment]
+1

**Comment by alexeyzimarev** [comment]
I remember this be a Mono issue tbh. Are you staying with Mono? Can you try with .NET Core and latest unstable?

**Comment by sherri-britecore** [comment]
Created MAS-75 Jira slip

**Comment by alexeyzimarev** [comment]
Well, we just call the `HttpWebRequest.GetResponse`, if Mono has a bug, we can't do anything about it.
