### ISSUE TITLE
'RestClient' does not contain a definition for 'JsonSerializer' and no extension method 'JsonSerializer'

### ISSUE THREAD

**Issue by tonywei92** [restsharp/RestSharp#947]
I read your announcement about json now not included. i followed the step you tell to register with "Client", but error as i descripted in the title. please help

**Comment by campbellja** [comment]
Hi @tonywei92 You'll need to look at IRestRequest for the JsonSerializer property: https://github.com/restsharp/RestSharp/blob/master/RestSharp/IRestRequest.cs#L38

**Comment by alexeyzimarev** [comment]
The documentation has been updated.

**Comment by campbellja** [comment]
Cheers Alexey!!


Kind Regards,

Andrew Campbell
MB: 0409 684 443
EM: campbellja@gmail.com
