### ISSUE TITLE
Is RestClient object thread safe?

### ISSUE THREAD

**Issue by speidy** [restsharp/RestSharp#951]
Hello,

I wondered if I can create one RestClient instance to be used by multiple threads concurrently?

I didn't see any statements in wiki, but found this thread: https://groups.google.com/forum/#!topic/restsharp/X8JPtcfnSlo. 
As its a bit old one, I'm asking here to make sure if anything has changed.

Thanks.
Idan

**Comment by janpieterz** [comment]
Hi @speidy ,

Just took a look, it looks like the Restclient is still not intended to be used by multiple threads, see:
https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestClient.cs#L653

**Comment by alexeyzimarev** [comment]
Hm, I think the client can be re-used, request is definitely one-off.

**Comment by alexeyzimarev** [comment]
Have you tried using this https://github.com/restsharp/RestSharp/pull/786?

**Comment by misiektg86** [comment]
So finally it is or it is not or I have to verify it?

**Comment by alexeyzimarev** [comment]
There is a comment that points out that XML serialiser is being amended per request. But I cannot see anything related to JSON in that regard. For the rest there is no state in the client itself that is being changed per request,

**Comment by AndreMantas** [comment]
I was trying to figure out if my wrapper class that uses a RestClient should be injected as a singleton or as a instance per dependency and ended up here. Any suggestions?

**Comment by alexeyzimarev** [comment]
Have you got any problems with that?

**Comment by anoordover** [comment]
As noted earlier by @janpieterz some parts are not thread safe:
Currently line https://github.com/restsharp/RestSharp/blob/398e546499b470abef6fe6ce8f7c6b4ca18b3aae/RestSharp/RestClient.cs#L657
The content of a member variable is changed. The Deserialize method is not thread safe.
Maybe a wrapper that calls this method inside a lock might make the RestClient thread safe.

**Comment by alexeyzimarev** [comment]
@anoordover I don't think the line you are pointing has anything to do with thread safety. The variable is locally scoped, it is not a class member.

**Comment by anoordover** [comment]
@alexeyzimarev Of course I'm not sure. But on line 651 the handler seems to be retrieved from ContentHandlers Dictionary via the GetHandler method. This Dictionary is a member variable. So the instances in the Dictionary are member variables/instances as well. I don't have the impression that a clone of the handler is made in the GetHandler method. To summarize I have the impression that each thread gets the same IDeserializer for the same contenttype. Of course I might be mistaken.

**Comment by alexeyzimarev** [comment]
Ah, yes, you are right. The dictionary should map content types to factory delegates but instead it maps instances and they are being manipulated... I think this can be fixed.

**Comment by zhaomuzhi** [comment]
So from which version this RestClient has become thread safe?

**Comment by Embo1** [comment]
Is this closed as Fixed or Wont fix?

**Comment by paveldayneko** [comment]
@alexeyzimarev is there any update on that? 

> Ah, yes, you are right. The dictionary should map content types to factory delegates but instead it maps instances and they are being manipulated... I think this can be fixed.

**Comment by paveldayneko** [comment]
@alexeyzimarev, got your point, thanks

**Comment by alexeyzimarev** [comment]
@paveldayneko from what we have discussed here, the only case when we change the state of the client itself is when a custom root element, XML namespace or date format is set on the request level. For all other cases, the client is thread-safe.

**Comment by alexeyzimarev** [comment]
Seems to be an easy fix.

**Comment by DSchmidlin** [comment]
Has this been released?  The last release was 106.6.7 and was 23 days ago.

**Comment by alexeyzimarev** [comment]
@DSchmidlin thank you for pointing out the exact number of days since the last release. But please also remember that I am doing this work in my free time, unpaid, and mainly getting reminders like yours instead of "thank you". Sorry mate, it will just as much time as it takes.

**Comment by alexeyzimarev** [comment]
@DSchmidlin Sorry for being rude but I am being equally frustrated.

**Comment by DSchmidlin** [comment]
@alexeyzimarev :) No offense taken.  I should have worded my question better.  How can I help?

**Comment by paveldayneko** [comment]
@DSchmidlin I can confirm that mentioned issue were fixed and released in the latest version. You can see it from commit history.

**Comment by Embo1** [comment]
@alexeyzimarev  @paveldayneko  Thank you both. Much appreciated.

**Comment by nitinkhosla79** [comment]
@alexeyzimarev Can you please advise if restsharp is threadsafe? We are facing an issue mentioned in #1449 PR.
