### ISSUE TITLE
Issue installing RestSharp for portable application

### ISSUE THREAD

**Issue by DParua** [restsharp/RestSharp#952]
Hello,

I offloaded a project which involved making a cross platform app from a website. My friend who was supposed to do the project, has given me a solution that contains a portable section and a droid section. The ios and windows apps will be made once i complete the remaining portions of the portable code.

Now, he used some packages that are failing to load completely on my system. He had compiled an apk from this code, so this code must be working, but I cannot resolve the issues with the packages. I removed the packages directory from the project he supplied to me, and rebuilt the project hoping the packages would restore themselves correctly. But I ended up with the same errors again.

Then I found that "Mono.Android" and "RestSharp" were marked with warning signs under the references list. So I removed these two, and tried installing them fresh from Nuget Package Manager. Trying to install RestSharp gave me the following error:

`Could not install package 'RestSharp 104.5.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

And I also cannot find "Mono.Android" package in the Nuget Package Manager. My friend was unable to help me out on this. Please suggest how to get this project working.

Thanks in advance.

Debopam Parua

**Comment by alexeyzimarev** [comment]
`Mono.Android` is not part of RestSharp. RestSharp 104.5.0 has no dependencies, you can check this yourself on nuget.org. But we never had proper support for PCL. We do have a library for Android, but from your issue description it is not clear, which platform are you working with. May be you can start with that.

**Comment by alexeyzimarev** [comment]
I suggest you upgrade to the latest unstable and go for .NET Core if you want to be x-plat.
