### ISSUE TITLE
Problems with Compilation VB RestSharp

### ISSUE THREAD

**Issue by nikodtbVf** [restsharp/RestSharp#953]
I have a problem Actually I develop A VB .NET Application, but I have a problem I use a RestSharp Library to consume my API Rest Request in the Debug Mode the response of the data in the request is correct, but when i generate a .exe, install the program and the api request doesn't work, make the request but don't get any response, I checked the server and this is working correctly make some request with PostMan and its fine. I think is problem with the compilation someone can help me?

Thank you

**Comment by alexeyzimarev** [comment]
It doesn't matter, which language you use. Check if your request is sent correctly using Fiddler. I doubt this is a RestSharp issue,

**Comment by alexeyzimarev** [comment]
Since there is no reply, I am closing this. If you still have this issue - please take care of providing your code.
