### ISSUE TITLE
Could not load type

### ISSUE THREAD

**Issue by rafaeltomitao** [restsharp/RestSharp#954]
Hi, 
I have a problem when starting a console application with restsharp version 105.2.3. 
I receive a message: "Could not load type 'RestSharp.RestClient' from assembly 'RestSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."

But the installed version is a 105.2.3.
I'm using .NET Framework 4.5.2

Somebody with same problem?

**Comment by JoshMcCullough** [comment]
Same problem. I had to revert to v105.0.1. So we can't use EasyPost and SquareConnect together because EasyPost requires RestSharp >= 105.0.1 while SquareConnect requires >= 105.1.0.

The reference for RestSharp v105.0.1 looks like this:

```
    <Reference Include="RestSharp, Version=100.0.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75, processorArchitecture=MSIL">
      <HintPath>..\packages\EasyPost-Official.2.2.3\lib\net45\RestSharp.dll</HintPath>
    </Reference>
```

Note the reference's version is `100.0.0.0` while the DLL version is `105.2.3`, as it should be. Why would they be out of sync?

**Comment by alexeyzimarev** [comment]
@JoshMcCullough What is `EasyPost-Official`? Does not look like RestSharp package to be honest.

**Comment by alexeyzimarev** [comment]
@rafaeltomitao Please post your packages.config and app.config files.

**Comment by JoshMcCullough** [comment]
It's a package which depends on RestSharp. The problem appears to be that the DLL version of RestSharp was not being updated, I believe.

**Comment by alexeyzimarev** [comment]
If you have a transient dependency and also have installed RestSharp separately, there might be a conflict. It just usual .NET stuff. You can see if you have any assembly binding redirect for RestSharp in app.config and also inspect the dll version in your build output folder to find out what version is actually being used.

**Comment by rafaeltomitao** [comment]
Sorry for the delay in answering.

Then I discovered here that it was a conflict in the name of the solution.
My solution was renamed RestSharp, renamed RestSharp1, and it worked perfectly.

Thank you very much for your commitment and once again apologies for the delay.

Rafael Tomitão
