### ISSUE TITLE
long time to upload a tiny file

### ISSUE THREAD

**Issue by Prakash19921206** [restsharp/RestSharp#955]
by default RestSharp is uploading with octet stream (`application/octet-stream`)
but when i upload a tiny image (50kb) to amazon web server,  it takes very long time...for some reason its not utilizing my broadband full upload speed.  as i noticed it only uses around 1 kbps or less. to get response from AWS its taking 30 - 40 seconds
however it should only take couple of seconds.
below is the code that i'm using

 ```
System.Net.WebRequest.DefaultWebProxy = null; ///this didn't help to speed up upload
 var watch = System.Diagnostics.Stopwatch.StartNew();
 var client = new RestClient("http://www.weblink_comeshere.com");
 var request = new RestRequest("/upload/image", Method.POST);
 request.AddParameter("some_message", some_string);
 request.AddHeader("Content-Type", "image/jpeg");
  request.AddFile("file", path);              

   IRestResponse response = client.Execute(request);
   var content = response.Content;
   Console.WriteLine(content);
   watch.Stop();
    var elapsedMs = watch.ElapsedMilliseconds;
   Console.WriteLine("time taken {0} ms", elapsedMs);
```
how to speed up this process?
Thanks

**Comment by alexeyzimarev** [comment]
I guess this will only be valid blame on RS if you have the same upload done using the `HttpClient` with different (faster) figure. Until then I would say this is a speculation, since there are just too many factors that can influence this.

**Comment by alexeyzimarev** [comment]
@Prakash19921206 are you still interested in moving this issue forward? If not, can you close this issue, or shall I close it?

**Comment by Prakash19921206** [comment]
@alexeyzimarev , Thanks for your reply. i'll reopen this issue if i still have same problem (in comparision with with `HttpClient `)
