### ISSUE TITLE
Allow request.AddUrlSegment(name, value) to accept an int value

### ISSUE THREAD

**Issue by ChangePlaces** [restsharp/RestSharp#956]
E.g. url segments are often used to pass ID values to the api, and rather than having to call `.ToString()` on each different use, it'd be nice to have an overload that accepts an `int` / `long` value!

**Comment by alexeyzimarev** [comment]
`IRestRequest. AddUrlSegment(string name, object value)` does `ToString` to any type sent to it. So you can add your `int` and `long` already now. Do you have any issue with that?

**Comment by ChangePlaces** [comment]
Oh really? In that case, all's good, thanks!
