### ISSUE TITLE
JsonSerializer documentation

### ISSUE THREAD

**Issue by aredfox** [restsharp/RestSharp#958]
In the documentation written at https://github.com/restsharp/RestSharp/blob/master/readme.txt the following code is metnioned:

```
var client = new RestClient();
client.JsonSerializer = new YourCustomSerializer();
```

However, there is no property `JsonSerializer` on the `RestClient` class, it needs to be set on the ´request´ object/class in stead every time...

**Comment by alexeyzimarev** [comment]
The readme has been updated.
