### ISSUE TITLE
Xml node with attributes and content at the same time

### ISSUE THREAD

**Issue by bcichonski** [restsharp/RestSharp#963]
It seems to me that when using default XmlSerializer there is no way to produce xml node that has attribute values and text content at the same time. This was originally found when my team was using RestSharp for communicating with Prestashop 1.6 API, where some nodes should look like:

```xml
<language id="1">
 Beer
</language>
```

PS: I ommit Google Group since it looks dead and abandoned.

**Comment by alexeyzimarev** [comment]
Closed by #964
