### ISSUE TITLE
AddDefaultHeader and Chinese

### ISSUE THREAD

**Issue by clarghi** [restsharp/RestSharp#965]
Hi,
I have problems sending chinese characters in header.
The code:
`var client = new RestClientEx(webApiBaseUrl);
var request = new RestRequest(SDAPICalls.LOGIN, Method.POST);
request.Parameters.Clear();
request.AddParameter("test", "昌昨米炎米昨李昌", ParameterType.HttpHeader);
IRestResponse<ReturnValues<PostLogin>> login = client.Execute<ReturnValues<PostLogin>>(request);`

If the parameter contains latin characters only no problem, but with chinese characters I obtain the error "Specified value has invalid Control characters".

Is there a way to resolve this issue?
B.R.
Cristiano Larghi

**Comment by behoyh** [comment]
I don't think URl params were meant to store anything other the ASCII characters. Why not use the body payload in your POST request?

**Comment by clarghi** [comment]
I have some params to send in every web api call. So, I have put these params in header, while in body I have put the specific params for each call.
Yes, I have resolved putting all params in body, but putting in header is cleaner in my situation.
I have read some articles in w3.org, but I have not found a clear explanation of the character encoding in header data. I though that the content-type http header specify the encoding both for header and body, but I don't know if is true.
E.g. chinese browsers how encode the header params?

**Comment by alexeyzimarev** [comment]
For your string in Chinese the URL encode will be `%E6%98%8C%E6%98%A8%E7%B1%B3%E7%82%8E%E7%B1%B3%E6%98%A8%E6%9D%8E%E6%98%8C`. Can you try this and see if it works?
