### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by emecas** [restsharp/RestSharp#966]
Using RestSharp.105.2.3\lib\net45\RestSharp.dll from NuGet

I have a API call that is only working correctly (applying the filter) in an specific way, I have tried using `%3D` instead of the 2nd `=` in the `sysparm_query` parameter since this's working both ways from a browser.

Working OK using a date
```     
    var request = new RestRequest("api/now/table/sys_choice?sysparm_offset=0&sysparm_query=sys_updated_on=2016-01-25 21:51:20", Method.GET);
```

Working OK using NULL
```   
    var request = new RestRequest("api/now/table/sys_choice?sysparm_offset=0&sysparm_query=sys_updated_on=NULL", Method.GET);
```

Not working with AddUrlSegment
```
    var request = new RestRequest("api/now/table/{table}?{offset}&{filter}", Method.GET);
    request.AddUrlSegment("table", "sys_choice"); 
    request.AddUrlSegment("offset", "sysparm_offset=0");
    //request.AddUrlSegment("filter", "sysparm_query=sys_updated_on%3DNULL");
    request.AddUrlSegment("filter", "sysparm_query=sys_updated_on=2016-01-25 21:51:20");
```                

Not working with AddParameter
```
        var request = new RestRequest("api/now/table/{table}?{offset}&{filter}", Method.GET);
        request.AddParameter("table", "sys_choice", ParameterType.UrlSegment);
        request.AddParameter("offset", "sysparm_offset=0", ParameterType.UrlSegment);
        request.AddParameter("filter", "sysparm_query=sys_updated_on=2016-01-25 21:51:20", ParameterType.UrlSegment);
```

**Comment by alexeyzimarev** [comment]
Here `new RestRequest("api/now/table/{table}?{offset}&{filter}", Method.GET);`
you do not need to specify parameters. You just need `api/now/table`.

**Comment by alexeyzimarev** [comment]
@emecas could you please reply or close this issue?

**Comment by emecas** [comment]
Thanks @alexeyzimarev 

So , I guess you mean something like this:

                var request = new RestRequest("api/now/table/{table}", Method.GET);
                request.AddUrlSegment("table", "sys_choice"); 
                request.AddParameter("offset", "sysparm_offset=0", ParameterType.UrlSegment);
                request.AddParameter("filter", "sysparm_query=sys_updated_on=2016-01-25 21:51:20", ParameterType.UrlSegment);
                IRestResponse response = client.Execute(request);
