### ISSUE TITLE
Repo dead?

### ISSUE THREAD

**Issue by darxis** [restsharp/RestSharp#975]
Hi,

Is this repository still maintained? I can see that release v105.2.3 is 2 years old... And there have been bugfixes since.
What about publishing a new nuget package? I am willing to contribute.

Owners replies would be much appreciated

**Comment by tbayart** [comment]
Looks dead for me.
Looking for a fork or a replacement

**Comment by garora** [comment]
Nothing happened new here its what it was 2 years ago! Hoping owner take a look and try to do something. I am looking for `PR` for .NET Core

**Comment by tbayart** [comment]
Most of my code use 4.6+ framework now, so i prefer to switch to HttpClient

**Comment by alexeyzimarev** [comment]
You can happily use the current version with 4.6+ framework. I think the supported framework isn't an issue here, right?

@garora Have you made a .NET Core support PR?

**Comment by garora** [comment]
@alexeyzimarev - if you guys still welcome `PR` - I can do it

**Comment by alexeyzimarev** [comment]
There are several PRs now on this topic and we of course welcome future PRs. However, I would ask for a bit of patience before we clean up things as a preparation for the next release. If you like - welcome to join our Gitter to discuss the way to go.

**Comment by garora** [comment]
@alexeyzimarev - awesome! I would love to be there.
