### ISSUE TITLE
Adding a handler for an existing content-type creates a duplicate in AcceptTypes

### ISSUE THREAD

**Issue by mayerc-MSFT** [restsharp/RestSharp#976]
We just uncovered a bug today in our code where the HTTP server would "randomly" reject our requests with HTTP 400: Bad Request: Headers are too large.  

Turns out we were registering a handler for "application/json" repeatedly. Each time we invoke AddHandler("application/json", our_handler), RestClient replaces the current handler in the ContentHandlers dictionary; however, RestClient adds a duplicate "application/json" to AcceptTypes.  Our code was registering the handler so many times that the AcceptTypes list grows large enough with duplicates that cause the server to reject the request.

We fixed the bug in our code to prevent registering the handler multiple times; however, it'd be nice for RestClient.AddHandler to be resilient to that and not add duplicates to AcceptTypes.  Feels like a simple fix would be to change RestClient.AcceptTypes from a list to a hashset.

**Comment by zaus** [comment]
fix in patch file
[0002-fix-976-don-t-duplicate-accept-types.patch.txt](https://github.com/restsharp/RestSharp/files/1724728/0002-fix-976-don-t-duplicate-accept-types.patch.txt)
