### ISSUE TITLE
是不是不支持gbk编码的反序列化呢？

### ISSUE THREAD

**Issue by maobiwen** [restsharp/RestSharp#982]
<?xml version="1.0" encoding="GBK" standalone="yes"?>
<response>
    <functionID>updateItemStock</functionID>
    <time>2017-08-19 16:55:13</time>
    <Result>
        <operCode>0</operCode>
        <operation>???????</operation>
        <outerItemID>3613171</outerItemID>
    </Result>
</response>
像这个xml，反序列出来就是 ????? ，中间是中文。。。。有人知道为什么吗？

**Comment by maobiwen** [comment]
<?xml version="1.0" encoding="GBK" standalone="yes"?>

**Comment by alexeyzimarev** [comment]
Please write in English.

**Comment by maobiwen** [comment]
I mean RestSharp can't support gbk response

but now ,I solved this problem by myshelf ,I fixed the bug
I think it is a bug
