### ISSUE TITLE
Deserializing IList

### ISSUE THREAD

**Issue by edoardofoco** [restsharp/RestSharp#983]
Hi,

This relates to issues flagged in 2012. 
ILists are still not supported when deserializing.

Please could someone document how to do tackle this issue?

**Comment by garora** [comment]
> ILists are still not supported when deserializing.
Not only IList but no support for any interface like ICollection, IList etc.

**Comment by eric-jiang** [comment]
I ended up calling Newton Json's JsonConvert.DeserializeObject() to get around the issue.

**Comment by alexeyzimarev** [comment]
Here is the template message concerning JSON serialization.

We are closing tickets that concern issues with JSON serialization after the 106.10.0 release, which includes new packages to support serialization using `NewtonsoftJson`, `Utf8Json` and `System.Text.Json`.

Most certainly, your issue will be resolved by using one of those serializers. Don't forget to check the serialization options, which can affect the ability to deserialize your request on the server-side or deserialize the response.

Please refer to the [updated documentation](http://restsharp.org/usage/serialization.html#default-serializers) about serialization.
