### ISSUE TITLE
Strip BOM before deserialize

### ISSUE THREAD

**Issue by fixer-m** [restsharp/RestSharp#986]
Before deserialize response there should be a check if it starts from [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) chars. 
If it is true, then it should be removed from string before deserialize. 
Right now if response have this BOM than deserialize doesn't work.

**Comment by alexeyzimarev** [comment]
BOM characters are valid for UTF encodings. If the server sends a response in UTF but also returns the ContentEncoding with something else (like ISO), there might be an issue, but that's incorrect server behaviour. Alternatively, using another serializer might help, please check the docs on http://restsharp.org
