### ISSUE TITLE
Make the readme.txt more accurate

### ISSUE THREAD

**Issue by JohnMcAvinue** [restsharp/RestSharp#999]
This is only minor but it does make a difference. In the readme that it is opened during installation of the package, this example is provided:

var client = new RestClient();
client.JsonSerializer = new YourCustomSerializer();

The JsonSerializer is actually on the RestRequest, and not the RestClient as indicated in the example.

**Comment by alexeyzimarev** [comment]
I suggest you make a pull request, if you think this is important. I remember I merged one about the same issue but it went missing somehow.

**Comment by alexeyzimarev** [comment]
The readme.txt file is now correct.
